= Cuducos's PhD writings 
Eduardo Cuducos
:homepage: http://about.me/cuducos

I'm a PhD student in sociology at the http://www.essex.ac.uk[University of Essex], my research focus is on crowdfunding. Here I share my writings, fell free to read, comment, criticize…

And, yes, I'm geek enough to prefer a markdown language rather than a word processor, GitHub rather than word processors' comments and tracking tools.

As you probably have discovered by yourself, I’m not a native english speaker. I’m really sorry for all the small crimes I commit with your beloved language. I’d be really glad if you point them out.

If this introduction is not enough, you can start to http://about.me/cuducos[stalk me]. 

== Text(s) available

* link:literature-review/research-design.adoc[*Post-politics and crowdfunding*]: research design with some literature review
* link:literature-review/politics.adoc[*Contemporary political theory and the possibilities within crowdfunding*]: literature review on politics -> *work in progress*

== Generating print friendly HTMLs

Use link:http://asciidoctor.org/docs/install-toolchain/[AsciiDoctor Toolchain] and commands such as:

 $ asciidoctor -a stylesheet=custom_style.css -a stylesdir=../ -o politics.html politics.adoc

== License

include::LICENSE.adoc[]

