= Crowdfunding and the reconfiguration of public and private space footnote:[Paper submitted to the _ECREA Communication and Democracy Section Conference “Political Agency in the Digital Age,”_ Copenhagen, 2015, and also presented at the _2015 Centre for European Policy Studies Winter School “From Uber to Amazon Mechanical Turk,”_ Brussels, 2015.]
Eduardo Gonçalves (University of Essex)
:revremark: Conference paper/work in progress
:revdate: February 2015
:homepage: http://cuducos.me
:numbered!:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[abstract]
== Abstract

This ongoing PhD research consists of a social and political analysis of the crowdfunding phenomenon. Platforms such as Kickstarter or Indiegogo make initiatives tangible through actions of ordinary people, dismissing institutional support from government or corporations. Through a social and political analysis of these online gatherings, my ongoing PhD research calls into question the spaces where people pursue public and private interests.

The relationship between public and private spheres of action has been long debated in the literature. Arendt criticized the role of modern state as a guardian of individual freedom, highlighting that real possibilities of political action are still restricted to political elites. Simultaneously private interests of corporations have compromised the political sphere, argued Wolin and Schedler. According to them states take decisions within the private realm, diminishing the spaces for public interests. Finally Bellah argued that this scenario and its emphasis in the private interests favored individualism. Yet, he adds, people are not comfortable with it: the lack of social ties makes them eager for connections.

This paper introduces some of my data and findings, focusing on interviews I conducted with people engaged with crowdfunding in Brazil, the UK and the USA. I start from the point that if the institutional conjuncture seems to seize the public sphere from people, citizens might be fighting back recreating the public realm within this purportedly private space. Instead of traditional political organizations (such as parties or social movements) crowdfunding benefits from practical disruptions emerged from new technologies. Yet at the same time crowdfunding might grasp what post-representativeness could be or what a post-political pragmatic approach could look like. The discussion considers political possibilities and limitations of this new setting for private and public spaces.

[.keywords]
*Keywords*: crowdfunding, internet, politics, public space, private space.

:numbered:

== Introduction

The phenomenon of crowdfunding is among several possibilities brought to existence by the emergence of the internet and web 2.0. While turn of the century platforms for blogging and social networking were focused on the production of online content by ordinary users, arguably what came next was the extrapolation of digital boundaries. Underneath this claim lies a set of changes that includes (but is not limited to) the falling costs of production of different kinds of goods and services (such as 3D printers and video production, for example), the ease of finding collaboration with others world wide, and niche online stores delivering very specialized products all around the world (from tools for peculiar hobbies, to DIY supplies and technological gadgets). Yet this scenario takes into account abstract and intangible changes, such as the idea of collaborative and crowdsourced projects (the most renowned being Linux, Wikipedia and the Human Genome Project), the debate over intellectual property (such as the struggle and changes the music industry faced after the advent of the MP3, or yet Google book-scanning efforts and the succeeding debates) and the dispute over privacy on the internet (especially after WikiLeaks, specific Anonymous operations labeled as hacktivism, and the Edward Snowden case). In sum, the internet has been pivotal to transformations that affect several spheres of social life. Within these changes crowdfunding is a specific mechanism that integrates different aspects of these novelties.

Basically crowdfunding platforms are websites on which users expose their own projects and ideas, asking for financial contributions in order to be able to execute these projects. Enthusiasts can easily help with different amounts during the period in which the campaign is online — all this process is simple and handled with a few clicks. Each proposal has its own online profile describing its intentions, motivations, justifications, budgets, targets and all details needed to relate and to to build trust within possible supporters. If the project achieves the amount needed those who helped financially to make the project happen are often rewarded. It is not rare that the simple execution of the project is considered a perk to everyone involved and interested (independently of any kind of financial collaboration). When this is the case, alternatives to copyright licenses such as Creative Commons play an important role. The biggest players in this field are Kickstarter and Indiegogo, and through crowdfunding different kinds of projects have been funded: from museums to individual's trips; from olympic athletes to personal charity; from technological gadgets to online education; from music albums to medical equipments; from comics to public transportation.footnote:[It is not the case of commenting on individual projects, but the references for the projects mentioned above are (respectively): Tesla Museum (asked for US$ 850k, raised more than US$ 1.3m – http://indiegogo.com/teslamuseum), Destino Incomum (asked for US$ 100, raised US$ 1k – http://catarse.me/destinoincomum), Larissa Juk (asked and raised US$ 10k – http://catarse.me/larissario2016), Alan Barnes Fund (asked for US$ 750, raised US$ 495k – http://gofundme.com/l0dt9o), Glif (asked for US$ 10k, raised US$ 137k – http://kck.st/bb6Tuu), Escola Livre de Jornalismo (asked and raised US$ 9k – http://catarse.me/enois), Amanda Palmer (asked for US$ 100k, raised roughly US$ 1.3m – http://kck.st/JliwH9), Avado (asked for US$ 5k, raised US$1.3m – http://medstartr.com/projects/13), Corey Mohler (raising US$ 1.1k every month – http://patreon.com/ExistentialComics), and Kansas City B-cycle (raised 60% of the US$ 700k target – http://neighbor.ly/projects/bikesharekc). All values were converted to US dollars when the project used a different currency.]
 
The fact that such a variety of ideas are becoming tangible without a formal sponsorship of incumbent institutions, such as government or corporations, makes of crowdfunding a promising case for sociological studies. This ongoing doctoral research focus on the way people engaged in this type of project employ a pro-active and hands-on mode that challenges these incumbent institutions. Interestingly the tone of this challenging attitude is not of direct confront against public administration or multinational companies, but of finding an alternative path considerably marginal from governments and corporations. Yet, in opposition to initiatives such as social movements or NGOs, crowdfunding unreservedly embraces the idea of profit and reshapes it as a sustainable mean to empower this marginal path. Profit is often dislocated from an endless accumulative disposition footnote:[As described, for example, in Weber's _The Protestant Ethic and the Spirit of Capitalism_ (1976).] and understood as a tool for autonomy, as an important resource to enable individual and collective (political) action.

The following section explores current debates in terms of political theory. Arguably nowadays society has become antipolitical, both from the individual and institutional perspectives. Based on Arendt (1998, 1973), the conceptual framework employed here takes the antipolitical argument (Schedler 1997) into account together with an approach focused on the understanding of the public and the private realm. The subsequent section offers an overview of the in-depth interviews that are the empirical support to this paper and exposes the core of the findings: from an analytical description of their lifestyle, the objective is to explore how their attitudes relate to the wider context of social institutions such as government, corporations, money and professional career. This analysis is based on their focus on individual autonomy and the controversial possibility of politics (and values inherent to the public realm) being revitalized through this process. 

== Public, private and social realm in a modern antipolitical society

The assumption underneath this research is that crowdfunding communities can be understood as politics in the sense that they create alternative spaces for people to pursue public and private interests. The division between public and private was forged in ancient Greece, when one should keep the pursue of private interests to the boundaries of the household, the core place for one's private life. That is to say that only citizens who have provided enough for them and their families were allowed to participate in the public life. This requirement was based on the role expected of this citizen when engaged with politics:

[quote]
Private wealth, therefore, became a condition for admission in public life not because its owner was engaged in accumulating it but, on the contrary, because it assured with reasonable certainty that its owner would not have to engage in providing for himself the means of use and consumption and was free for public activity. Public life, obviously, was possible only after much more urgent needs of life itself had been taken care of (Arendt 1998:64-5).

With the emergence of modern nation-states this classical distinction between the public and the private was severely affected. Modern age gave birth to the social realm which is neither public nor private — and yet dislocated considerably what was understood as public. While private life was characterized by providing the household through labor, and while the public realm was the place for action and speech, the social has taken the political space from the public, printing on it important differences: now government acts as a gigantic housekeeping organization, looking for provision for a whole nation; that is to say, labor, once relegated to the private life, now is not only allowed but placed at the center of political life. For Arendt (1998:28-9) the dividing line between the household and politics

[quote]
is entirely blurred, because we see the body of peoples and political communities in the image of a family whose everyday affairs have to be taken care of by a gigantic, nation-wide administration of housekeeping. The scientific thought that corresponds to this development is no longer political science but ‘political economy’ or ‘social economy’ or _Volkswirtschaft_, all of which indicate a kind of ‘collective house keeping;’ the collective of families economically organized into the facsimile of one super-human family is what we call ‘society,’ and its political form of organization is called ‘nation’ (Arendt 1998:28-9).footnote:[Arendt does not justify the use of the German term _Volkswirtschaft_ in this passage. Arguably it has no direct translation into English. Nonetheless it refers to a kind of economics driven by the nation's needs, the needs expressed by its households as well as by the private and public sector; in some languages, as in Dutch or Latin for example, its translation is similar to _national economy_ (_algemene economie_ or _oeconomia nationalis_ respectively).]

Arendt described a society in which the political has no room. This society has become “an organization of property-owners who, instead of claiming access to the public realm because of their wealth, demanded protection from it for the accumulation of more wealth” (Arendt 1998:68). This transformation has to be understood according to the specific ways through which modern societies have developed into representative democracies, a constant struggle between emphasizing the anew claimed by the American and French revolutions on the one hand, and, on the other hand, the will to consolidate the ideal of freedom in a stable institution. For instance Thomas Jefferson had a particular standpoint among the Founding Fathers regarding the role of the constitution in this process: in ideological terms, he wanted the constitution to be strong enough to guarantee that no hostilities will take place in the political realm, nonetheless, in order to reinforce the founding anew, this same constitution should also be flexible enough to be revised from times to times. In practical terms, the effects of these thoughts can be seen in the representative democracy model and in its well established ways to participate in the political realm: elections, elected officials, senators, representatives, parties and voters (Arendt 1973).

Perhaps this new institutional scenario has failed in fulfilling its original intents. This scheme was unable to extend the perception of participation from representatives to represented: when it comes to politics, citizens are disinterested and this fact can be found not only “among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage. Contempt for the law and the system also shows up regularly among the favored and highly placed” (Jaffe 1997:78). Sniderman and Bullock's (2004) idea of ‘menu dependence’ involves a very similar description of how ordinary people have a very discrete participation in politics. According to them, “citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties” (2004:338). The idea is that citizens are not free to compose their own menu of political choices, but only allowed to pick up one from a menu pre-established by parties and political elites. Yet Wolin’s (2004:428) analysis of contemporary politics adds another layer to this branch of critiques: for him “in both, the political and the economic context, contract appears as the essential condition of power”. In other words as the market economy would operate in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state would operate in a way that concentrates the (political) power in the hands of the political elite. By themselves the functioning of these both institutions are expanding the gap between rich and poor, rulers and ruled. And, as Arendt (1973:253) suggested, underneath this wave of critiques towards modern society, there is the displacement of the public realm itself, as well as the dilemma Jefferson had in mind:

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of being republicans and of acting as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens. 

This two-folded movement of degradation of the public and of inflation of the private has granted the space for corporations to extrapolate their private bounds and act within the public realm. Political decisions — already distant from ordinary people — gradually started to take into account a logic that does not pertain to the public realm, namely the logic of the market economy (Wollin 2004). This movement can be described as antipolitical through at least two arguments: in the one hand, it contributes to the mitigation of the public realm, which is suppressed by a self-regulated private one, the market (Schedler 1997); or, alternatively, whatever remains of the public realm starts to operate according to a logic inherent to the private sphere — what Schedler (1997) calls an inverted Habermasian colonization.footnote:[See Habermas (2005) for the original concept of colonization in that sense.] To be sure, Wolin (2004:588) highlights that both — state and market — are appropriating the methods of one another: “it is not that the state and the corporations have become partners; in the process, each has began to mimic functions historically identified with the other.” According to him, corporations’ move includes being in charge or funding health care, education and other welfare affairs; in parallel, governments’ move includes applying profits logic, notions of efficiency and management, to buoy its own actions. 

It is important to highlight that Arendt and Wollin do not deny the importance of government, party system and representative democracy for modern politics: these new elements of the public realm opened the political career for people from the lower classes, and the notion of elite enabled through the parties replaced old elites based on birth or wealth, for example (Arendt 1973). However despite these advances this process had a devastating side-effect for politics: by limiting the space for political action it consolidate the public realm as a place for private affairs. In Arendt's (1998:46) words, “the character of the public realm must change in accordance with the activities admitted into it, but to a large extent the activity itself changes its own nature too.”

The type of skills and activities held within these spaces were also impacted by these transformations. The importance given to labor and provision (formerly banished from the political), and to speech and action (formerly the core of political activity) also assume a different balance. Labor and wealth accumulation made sense as far as the household provisions required them. Excelling in speech and public action in politics was a public virtue which the whole body of citizens would benefit of. Interestingly within the modern social realm labor was introduced to the political space and, at the same time, speech and action was dislocated to the private: “while we have become excellent in the laboring we perform in public, our capacity for action and speech has lost much of its former quality since the rise of the social realm banished these into the sphere of the intimate and the private” (Arendt 1998:48). From that perspective it is possible to address the lack of interest in politics as well as the endless interest in making money, which are overlapping aspects in many critiques towards representative democracy (Wolin 2004; Mouffe 2005). Yet it is possible to set a theoretical background to accommodate the claims raised by crowdfunding communities when they affirm they are paving an alternative path, when they indirectly or directly challenge governmental and corporative sponsorship for private and public projects. The next section focuses on these claims and brings in this theoretical background to describe how crowdfunding worldviews can relate to nowadays institutional settings.

== Crowdfunding and social institutions

Drawing on 10 semi-structured in-depth interviews this paper organizes the findings of the first round of data collection for this project. According to the wider research design this stage explores the worldviews of people engaged in crowdfunding platforms in two different levels: founders or staff of these platforms, and project creators, that is, people who have recently submitted projects to these platforms. The access to this public is complicated. For instance, some of the platforms featuring among the wealthiest startups of recent years are considerably closed for interviews, only expressing themselves through their own public relations department. Yet very successful project creators usually end up dealing with thousands of followers on social media, making their attention to incoming messages relatively unreliable. In spite of that, in this initial stage I was able to interview people involved with seven different platforms (Indiegogo, CrowdCube, Catarse, Benfeitoria, Cinese and Unlock) from three different countries (USA, UK and Brazil). The interviewees, 4 women and 6 men, were from four different countries (the three above plus Romania) with ages varying from 24 to 61 years old.footnote:[Names and other references that could be used to identify informants have been anonymized, even if not all of them required that.] The entry points for access to these people involved different initiatives: attempts to direct contact through email and social media, attendance to events and places related to sharing economy and similar topics, personal contacts in the entrepreneur and technological scene in the USA and Brazil, and, mainly, snowballing.

The structure of the interview was funnel shaped: the first set of topics focused on self-identity, lifestyle, main activities, and on one's own life trajectory. Usually the conversation would end up in crowdfunding, which was exactly what was planned for the second block of the interview: discussing why they have embraced these platforms (whether it was as founder, staff or project creator) and how the experience was, or have been so far. Finally, if issues about government, corporations and formal politics have not emerged, these topics were raised in a third and final block in order to assimilate interviewee's perception about the institutional context surrounding them. 

Unintentionally the sample ended up biased towards initiatives that make efforts to differentiate themselves from the mainstream startup and entrepreneurship agenda. This was due to the aforementioned difficulty in getting access to big players in the startup and entrepreneur scene, as mentioned. For instance, even former employees of some of these platforms recurred to their former employer guidelines for declining to be interviewed, suggesting me to check their public relations material. This difficulty to gain access to the startup driven enterprises, together with the easiness to gain access to the alternative branch, reinforced the aforementioned approach on the marginal path I shall expand next.

The following section draws on interviewees' personal experiences and life choices. The idea is to grasp how they deal with making a living of their projects, including inspirations and personal aspirations. Drawing on this micro sociological approach the subsequent section discusses how their specific world view relates to social institutions, that is to say, a descriptive view of the subtle and the explicit challenges they foster. On top of that there is the sociological discussion regarding the public and the private realm as well as the possibilities for politics in modern society. 

=== Lifestyle, non-traditional pathways and motivations

One of my interviewees was drinking in a bar, with some friends, when the results of a municipal election were on the local TV. With no exception, he told me, everybody on their table was lamenting the outcome of the ballot, trying to imagine what kind of people have voted for that crap politician (which was the generalized opinion within his group). That was when something clicked for him: “Why am I here, sitting at this bar, just complaining and not getting anything done about it? How can I do that if I'm always saying that the internet is a tool that has helped to destroy and to transform industries and intermediaries?” he thought, referring to the way MP3 has changed the music industry. Claiming that the internet destroyed the culture industry may not be the precise way to describe that process, but it is undisputed that the combination of MP3 and file sharing platforms required a lot of reinvention from this industry (Allen-Robertson 2013). In spite of that this short passage is iconic in describing a set of characteristics shared among my interviewees: first, their mindset is focused on action, on a hands-on disposition to get things done (from online platforms to community gardens, from events and workshops to start ups), they are into what is often called the _maker culture_; second, and completely linked to the previous point, they have little or no patience for endless discussions, debates, assemblies or any decision process that is not focused on action itself; third, they really believe in action, that is to say, they are engaged with their actions because what they do is meaningful for them and, they argue, because they feel that it is also meaningful for people around them; fourth, they assume that what is meaningful for them can be completely meaningless for others, so their actions are not targeted in convincing people, neither in _changing the world_ — an idea often ridicularized by my interviewees; fifth, they recognize autonomy as a key requirement for their lifestyle, otherwise they feel that this impulse to gets things done can be severely constrained.

That first story was told by a young man in his early thirties, someone who had some projects funded through crowdfunding and who is involved in many different enterprises. Another interviewee, a successful businessman who has top tech startups and venture capital from Europe and the USA in his curriculum, said in an interview: “I am not a good bullshitter, I kind of like doing stuff.” He works with social entrepreneurship and in one of his enterprises in the UK he had recurred to crowdfunding. He has strong beliefs in social entrepreneurship, but reinforces: “I love these ideas people talk about, like system change and disrupting stuff, but that's not the reality. If you just talk about it, it doesn't make any difference really.” In practical terms that means that they see little value in dreamers and utopias: at the end of the day, change is a result of action.

I also interviewed someone who have founded two crowdfunding platforms in the last years. The first one is the biggest crowdfunding platform in Brazil today, but he left the company roughly an year after starting it. A few years later he decided to create a completely different platform.footnote:[Basically, the first platform was a traditional crowdfunding with projects and targets in terms of the duration of the campaign and the amount to be raised. The second one was a recurring crowdfunding platform, that is to say, instead of contributing (arguably with higher amounts) to the realization of a specific project, one can contribute (arguably with tiny amounts) in a regular basis to the maintenance of a continuous project, offering the creator a regular income throughout time. For example, after writing a romance a writer can decide to publish it as a book, setting up a budget and trying to raise that amount through a traditional crowdfunding campaign. Alternatively, if this writer's work is in the form of short stories, it might be interesting to opt for a recurring crowdfunding platform, asking for regular contributions (monthly, or every time a new story is published online, for example). The idea is that this smaller but regular income enables a different type of planning and execution, a different type of project. Yet the first platform my interviewee founded is extremely focused in curating the contents submitted by project creators, helping them to shape their projects and to build a community of fans and supporters around it. The second platform would completely eliminate any kind of intermediary, being merely an online tool with complete autonomy to project creators. So far the operation costs of the second platform involve no staff at all, only the cost of keeping the servers up — which is minimum.] He called his colleagues who were part of the group who has founded the first platform (and who were still working there). In spite of not being part of the company anymore all of them remained close friends. He shared his ideas about the new mechanism for a new crowdfunding style, and asked if they were interested in having that novelty as a new feature of their platform.  He was not selling the development of the new crowdfunding. He just needed this new model to exist so he could run some projects himself through it (something that would not be possible with the existing platforms). The guys from the first platform got excited about the new ideas, said that users were already requesting features like that, and that they would hold a meeting next week to ponder on that topic. The possibility of having a meeting holding him back from getting something done was unconceivable for him. He felt he really needed that platform and said he would not wait for a meeting. He coded the new platform in a few days, before the meeting take place. And he launched the second platform the same way he did the first: as an open-source project.

The maker culture they embrace requires a kind of autonomy that is not part of many environments, sometimes not even part of the ones they have created themselves. In that sense, their contempt for traditional careers and corporations is enormous: most of my interviewees have opted for very heterodox way to make a living, mostly getting little income from many projects, and usually recurring to different skills and passions they have in order to make money. They can profit, for example, from dancing and teaching tango, composing and recording authorial songs, coding software or offering specialized consultancy in sharing economy (to stick to the skills recurred by the guy we were talking about in the previous paragraph). I have heard many times during the interviews that it is better to count on several smaller pots, rather than to count on one single golden pot.

That does not mean, in any sense, that they do not care about money. The point is that they must have a moral alignment between what they believe in and how they make a living: as one interviewee who partially funded his master degree in the UK through crowdfunding told me, making money “is not interesting, it is too unimpressive, it is too dry and dull to make money just for the sake of it.” In fact, money is valued not as an accumulative good, but as a mean to assure autonomy: “the best way to sustain what you are doing is making profit” as another project creator, the former businessman, explained me. If they are hands-on people, engaging with actions that are specially meaningful for them, money can guarantee their dedication to these actions. It is different than thinking about money as something to be saved, something that only in a second stage will be spent or invested. Money is seen as a straightforward tool to empower autonomy, to set them free to do whatever their instincts and world views invites them to.

Finally dealing with this tension of pursuing money and, at the same time, running away from traditional careers (a common strategy to accumulate money), is what constantly pushes them towards an heterodox way to make a living: having a career would give them money, but would completely ruin their understanding of being autonomous, that is to say, they would invest a lot of time doing things that are meaningless for them and even if that could be an interesting strategy to make money, they consider it a very long diversion from their calling for action.

In spite of that money is not the only important requirement for autonomy. Getting back to the story of the interviewee who has funded two crowdfunding platforms, it is worth it to understand his motivation to leave the first one and, later, to build the second one in a way that he would not be required in its everyday maintenance. Ultimately he has not been involved in any of these platforms with primary motivation of profiting from it, that is to say, having in mind that the money made through the functioning of the platform would sustain his ambitions. His idea was slightly different: he would like to count on the mechanism offered by his platforms to make money through his artistic projects, which were his personal meaningful actions. He prefers to make money as an user of his own platform, not as a founder, CEO, manager or staff of the startup. This argument is not unusual, and in fact, it has to do with the idea of autonomy: they are struggling to run their projects on politics (as the guy of the opening story in that section), on arts (as this programmer involved in the foundation of two different platforms), on social entrepreneurship (as another one mentioned so far), as well as in areas that are not tech startups nor crowdfunding business: free education, independent journalism, sustainability and many other different fields I have learned from my interviewees. Besides the founder or creator role, their involvement in crowdfunding is seen as a way to reach a higher degree of autonomy. One woman I interviewed has created several educational projects, one of them was crowdfunded: an online and open school of journalism. She reinforced that autonomy was one of the most important values for her and for her students: on the one hand, “student's autonomy sets me free to be a better mother to my daughter; otherwise I'd just end up with more children to look after… if the student is autonomous, I can be more responsible for myself;” on the other hand, she explains, students (mainly the ones from poorest neighborhoods) do not want assistencialism or affirmative actions,footnote:[She meant affirmative actions such as the racial quotas to get in higher education, common and institutionalized in Brazil.] they want to be able to sort out their problems and to pursue their dreams by themselves.

Therefore another value is to keep these platforms within this network, within this group that shares similar ideas, that runs different small projects as a way to make a living. Many of them had prosperous careers elsewhere and decided to stick to their crowdfunding project, platform and network. And many of them have founded successful platforms and were approached by venture capital, by angels investors and declined any kind of negotiation. The following quote is from a 25 years wold woman who holds a law degree from one of the best universities of her country. She also has a couple of years of experience working as a lawyer, but two years ago she decided to quit her job and start a crowdfunding platform:

[quote]
When we had not perceived yet that we were not a startup, nothing not even close to that, we used to receive some proposals from venture capital… then we understood that we did not want a traditional path, a traditional company. We were inside a different group, trying to reinvent what a company is about. A way in which the end is not about profit, not even close to that. What is this model? We do not know yet, we are still building it. But we think that if we take that [venture capital] route we will end up in the traditional model of income, and that is not what we want. We are not willing to give in on that point.

Neither she nor the other two founders are able to make a living from their platform. Besides financial struggles, after the interview they changed their business model. Before they operated as most of the platforms operate, keeping a small percentage of all the transactions done through their system. Now they give up that percentage, the operation itself is not generating money for them anymore. This contradictory strategy illustrates what we have been describing so far: a completely heterodox relationship with money and business, blended with an explicit pursuit for autonomy. In their case the focus is in on open education and they believe they can contribute in a better way by not keeping small amounts of money in a per transaction basis. They believe that they can better support their community, the network looking for alternative forms of learning by sharing their knowledge and helping events related to the topic. The business model is not clear for them, they assume they are exploring. But that is what they believe in, that is what is guiding their decision, and that is what makes them feel autonomous. By believing in it they understand their actions have a kind of intrinsic value that would eventually pay off.

In these settings it is worth it to say that savings are an important (and probably a restrictive) part of their lifestyle.footnote:[Counting on savings among young people was much more common in Brazil than in the US or UK. A hypothesis (not explored here, but popular in the media; see Pramuk 2015 for example) is that the expensive tuition fees in the US and UK could limit the possibility of young people taking risks: as soon as they graduate, they have to start working to pay their education loans. In Brazil most of the top universities are public and free.] Many of them had the chance to prepare themselves financially before assuming certain kinds of risks. From the last example, that woman was able to save some money while working as a solicitor. Most of my interviewees has great educational and professional background. Many went to the best schools in their countries and even abroad, had great opportunities to join high ranked corporations, but declined this tradition to trace their own routes. Others were outstanding professionals and decided to change their lives. Savings, in that sense, also means that they are not afraid of failing, not because they are 100% confident in their capabilities, but because they have the feeling that if everything goes wrong, they can easily find a job and get back to their old careers. Evidently none of them want that, and only a few of them talked about it as a tangible possibility. But they cannot deny that they have a great combination of outstanding CVs, uncommon life experiences and the valuable entrepreneurship reputation that can help them to get a job or freelance any time they want. They have savings, they have a solid set of assets that could grant them a quick way out at anytime — even if that possibility sounds like a nightmare to their aspirations of autonomy.

Much more could be said about their lifestyle, such as the inspiration they take from hacker culture (Allen-Robertson 2013; Coleman 2013), open source communities (Kelty 2008; Lessig 2006) and the access to knowledge movement (Benkler 2010; Kapczynski 2010) for example. From that, for example, they put more effort on building a strong network with people with similar interests, not seeing them as competitors but as allies (for instance, some platforms are open-source and their programmers support the creation of new platforms all around the world). Unfortunately the brevity of this paper does not allow a deeper exploration of these topics — but there are plenty of studies (referenced above) covering the economic and political claims sustained by these groups. The next section approaches the profile of my interviewees from a more analytical and sociological perspective, discussing how their choices are linked to a specific reaction to an existing institutional setting and, at the same time, is an attempt to create alternative spaces free _from_ these institutions. To contemplate Berlin's (1999) critique of positive and negative freedom, the autonomy crowdfunding community is looking for is close to the idea of being free _to_ act, but they understand that this requires them to also be free _from_ any kind of institutional constrain.

=== Challenging incumbent institutions

The introduction made in the previous section was mostly descriptive of what I have been learning in fieldwork. This section situates the claims above within an institutional setting in order to clarify and analyze the alternative path put forward through crowdfunding. First the idea is to situate their contempt for corporations in a wider contempt for institutions, including also the government and the third sector — these are the institutions they want to be free _from_. Second, to see how the contempt for all these sectors (first, second and third sectors) can be understood from the perspective of different configurations of the public, private and social realm. Third, to discuss the possibility of politics within this attempt to escape any existing institutional setting.

To recapitulate the contempt for corporations and traditional careers I shall start with another quote from my interviews: “I do not like to work for companies, I avoid [working for them, or even get them involved in my projects], because companies are too dumb, too incompetent.” At that point of the interview this young man was telling me why he hardly ever works for or with companies. He continued pondering on situations when corporations are open to sponsor some of his projects, when corporations get involved in philanthropy or in cases such as corporate social responsibility:

[quote]
When we talk about companies, we talk about for-profit, what they want is profit … Always when profit is the main objective the maths they are going to do before deciding for any kind of social responsibility is: Can I make money out of it? Whatever I am going to do, does it convert in income? If it does not, the one involved is fired [from the corporation]. Sooner or later that one will be fired.”

This view might be simplistic, because the core of the problem is not profit itself. The core is the way through which decisions are made. To offer another example, for a layperson sharing economy and crowdfunding can be easily misunderstood as _quasi_ synonymous;  however when people I interviewed criticized a player of the sharing economy it was usually related to this corporation mindset. Airbnb and Uber footnote:[Financially Airbnb and Uber are the worthiest startups when it comes to online platforms based on the sharing economy ideas. Airbnb allows ordinary people to rent spare rooms for travelers (an alternative for hotels or hostels for example), and Uber allows ordinary people to offer rides on their own cars (an alternative for cabs, for example). Each of them have their market value estimated in tens of billion dollars.] emerged in another interview: “I have a real problem with it [Airbnb and Uber] because I think if they were local businessess I think they would be fantastic. I love technology but the fact that these guys, I mean, Uber, will end up owning every taxi driver in the world…” The problem is not necessarily being a corporation, being for-profit: but operating in a way that tends to concentrate too much power and, consequentially, this power can set boundaries or ordinary people autonomy. Power, scale and accumulation end up fostering a specific type of decision-making, a filter that eliminates individual autonomy in order to preserve some coherence within the organization. Corporations are unable to consider action the same way as the crowdfunding community does, so it is unfit for many of their purposes.

However what is interesting is that this contempt is extended to other kinds of organizations. For instance, many of them have been involved in NGO (non-government organizations) projects and many issues have emerged there too. For instance, one of my interviewees involved with education was running a journalism workshop for teenagers from a poor neighborhood. The activity was so solid that an outcome was the creation of a local news portal, ran by local people, with roughly 14,000 access a day — there were 15,000 habitants in that community. A lot of local people got involved, learning and working hard in the project. The instructors were payed by a NGO, but conflict emerged between them when my interviewee tried to negotiate a way to raise funds through the NGO to pay the people who were working in the website. That was not allowed due to internal and external constrains on NGO operations. To be precise, the argument they got was that the investment that came through the organization should be invested in the workshop, a free activity for anyone interested, not in paying one or another that was working hard and running the local news. That was totally unfit with the autonomy premise: “to really engage the guys it [the activity] has to be cool and has to pay for their work, otherwise they would have to work with anything else, something that might not be that interesting for them.”

When it comes to politics, for example, the overlap of this contempt with the hands-on mode results in critiques such as: “Instead of waiting for public policies to come from the sky to us, why don't we do it ourselves?” as the one who crowdfunded his tuition fees asked me. For him that was the case, for example, of his frustrated attempt to find a private or public scholarship to support his postgraduate degree. Surely government and traditional political organizations are also target of this branch of critique. Interestingly their focus is less on commonplace issues such as corruption footnote:[Even if corruption was part of their discourse they were never a strong reason to their contempt for traditional politics. Their impressions were mostly brief on that topic. For instance one young woman, when I asked if she would be more involved in traditional politics if there were more honest politicians, replied “would they still be in politics?”] and more on their lack of trust in the impersonal mechanism set up by bureaucracy. None of them were particularly interested in any kind of political organization such as parties or civic organizations — not even someone who had a close relative as a very prominent politician in the national scenario. Many of them have not voted for decades and feel distant from political decisions. Interestingly this contempt for politics does not necessarily reflected in a self-oriented (rather utilitarian) attitude: they feel that whatever they should spend their time on should be something they believed to be beneficial for their closer community — and "closer" here does not refer to their strong social ties, but to people close in the sense of interests and morals. One of the oldest persons I interviewed pondered: “I do think that there is a generation of people who feel that just making as much money as possible is not necessarily what needs to be done,” and he continued later “I think politics really seems to become marginal …  they [the young generation] are not in the slightest bit political. But I think that is a challenge everywhere, the political classes are disengaged from the voters.”

What is at the core of their contempt for the institutions is not the rules or motives themselves, but the process — something that Weber (1978) criticized as the impersonal, bureaucratic and rationalized way that corporations and governments adopted as their _modus operandi_. Many times during the interviews the topic was critiques towards bureaucracy, accusing it of being dumb, flaw and insensible, ideas that could be summarized in statements as such: “I always argue that even if you are a good guy and want to do good things, the mechanism is clumsy,” one said referring to the way public contracts between governments and private institutions work. There is no trust in the assumption that bureaucratic and rationalized institutions can be capable of selecting the best projects to be funded or of deliberating about the best ideas. Instead the perception is that these branch of institutions are dysfunctional in assuring autonomy to people.

The crowdfunding community, in that sense, is not actually fighting against these incumbent institutions — at least not in the same combative way other groups are doing it (for example Occupy, anti-G8 protests, black bloc inspired demonstrations etc.). Crowdfunding communities are occupied in finding its own ways to sustain itself, that is to say, they are not interested in confrontation such as blockades and buycotts, but in making room for alternative lifestyles, politics, values, exchanges and so on. And in order to do so, they feel they need autonomy to organize themselves without the interference and the dependence of the existing institutional settings. They want freedom _from_ institutions to be able, as individuals, to exercise their freedom _to_.

This claim for autonomy in order to pursue actions they believe in is actually mobilizing different concepts in terms of political theory. On the surface crowdfunding communities' contempt for government seems to be aligned with the critiques Arendt (1973) raised regarding the way modern representative democracies work: people outside the political elite does not feel empowered to action, what calls into question the whole organization of this governing institutions. Yet these claims seem aligned also to Wolin's (2004) discussion on how politics and corporations tend to concentrate more power (more means for action) in the hand of those who already are part of some elite. However there are also contradictions: if being aligned to that part of Arendt's work seems to be a shift towards a supposedly better political setting, looking from another perspective the expectations are diametrically opposed, that is to say, the idea of individual autonomy leads to an even more inflation of the private (and not only the mitigating of the public, but also of the social). That emphasis on the individual make these statements reject any attempt to be universal. Whenever there is a possibility of an institution shadowing individual autonomy there will be contempt.

Politically speaking this trend could suggest even higher levels of antipolitics. Schedler (1997) set some opposing pairs as a framework to understand how politics is removed from the stage, that is to say, how a given society becomes antipolitical. If crowdfunding claims seem to foster changes towards the political side when it comes to contingency (over necessity) and plurality (over uniformity), it fights back the other two pairs: it seems to be much more in favor of self-regulation (over public action) and an “anything goes” mindset (over authority). 

Maybe a counter-argument could be an approach suggested by Tocqueville (1986). If in his analysis of the newborn American democracy he saw a positive aspect in the vibrant interchange between the private and the public, and therefore one could argue that what crowdfunding is doing is not defending only the private, but mostly mitigating the social realm by criticizing the corporative economics and the political economy — elements that marked the colonization of the state by a logic born in the private realm. The focus on autonomy, in that sense, would be a call to restore the freedom to provision one's household with little interference from other instances. At the same time the “crowd” part or crowdfunding (the idea that any project needs the approval of a minimum number of people, or the importance they put on the building of a network around them) would be an opportunity to deliberate in a reformed public realm.  If the ties between corporations and government seized the public sphere from ordinary people through an expansion of the private what is happening next is ironic: citizens might be fighting back recreating the public sphere within this purportedly private sphere, i.e. taking the liberalism present in the market to engage in an environment that resemble a public sphere.

An yet alternative counter-argument would be to consider all these efforts as transitive, as a temporary movement that will sooner or later fade away, whether or not they succeed. In other words, to consider these platforms and efforts more as political claims than as concrete alternatives for the future. This quote from the interviewee who was completing his crowdfunded master degree pondered about this transitory hypothesis:

[quote]
I have some doubts about how far this can go because all these alternatives are only alternatives to the extent that they can be seen as an alternative path to something else, to the extent they are still marginal. What I call marginal is something that, given a mainstream culture, is by its cultural margins. Being there these alternatives are always pushing, the margins are always being pushed. I think that sharing economy, crowdfunding etc. are pushing them even further. But from the moment it starts to be so massive I would start to ask myself whether people will have motivation to carry on.

In sum what is clear is that the argument in favor of individual autonomy, of empowering individual for action is enough to mobilize political theories from different perspectives. Moreover it has a curious construct through which it stands in defense of the private realm, but criticizing exactly the institutions and moral grounds that are commonly blamed for the disappearance of the public realm: namely the modern nation-state and the influence corporations have gained over many other social spheres. Understanding this complex scenario is challenging not only because its outcomes are uncertain, but because they escape the most traditional oppositions in political theory: in many senses crowdfunding can be read as progressive (it does not respect the power of established elites, it is inclusive, open and accessible) and as conservative (it is for profit, it is against regulation); in many senses crowdfunding can be seen as liberal (anything goes since a certain amount of people agree with it) and as libertarian (its understanding of autonomy accepts no authority). The next section ponders on these preliminary findings to better engage with these political contradictions and tensions.

== Debate: crowdfunding and politics

According to Jaffe (1997) one of the signals of the antipolitics mechanisms is disconnectedness: since the public realm is fading out, since the private realm (embodied by the corporation market) is expanding significantly within society, the Hobbesian notion of politics is also fading out. The idea of individuals acting according to a set of agreed-upon rules is called into question and individual judgments are replacing collective structures such as legal jurisdiction, for example. The basic tension here is whether or not citizens' ability to easily connect, associate and act together through private enterprises is able to promote politics on a public understanding.

The case here is crowdfunding, but as the idea is similar to Tocqueville's (1986) arguments about the US, it is worth it to recall the paradox he put: in spite of the positives from the interchange between a strong private realm and a public ream, he considered that if citizens were familiar to grand theories such as political virtues they would handle them in a way that this knowledge would end up enclosed in their private life. In other words, in spite of the associations made in both private and public realms, judgements derived from political ideas would become merely a matter of individual choice, not as something to be discussed publicly. In the eighteenth century US, Tocqueville argued (and within crowdfunding, I suggest) this scenario could lead to an even more isolation of the individual and his political ideas.

Bellah _et al_ (2008) followed Tocqueville's argument, reinforcing the need to have individuals views scrutinized in public. However, what Bella _et al_ conclude is that contemporary society is experiencing an individualization process — and their work focus on understanding this individualization. Accordingly, they put forward four different ideal types of individualization: a biblical, a republican, a utilitarian and an expressive. For them, while the first two types are not common nowadays, the last two are very typical: one focused in a materialistic, utilitarian and rationalized disposition towards accumulation, and the other directed to a more emotional, subjective and personal pursue (Bellah _et al_ 2008, Joas and Knöbl 2009). This framework may be useful for further analysis regarding the crowdfunding communities. By now it is worth it to highlight that the contempt for politics (foreseen by Jaffe, or as part of the utilitarian individualism put forward by Bellah _et al_) has been called into question. For instance, Bennett _at al_ (2013) claimed for a slightly different concept, namely, the _disavowal of politics_. In spite of the predictions that a skeptical behavior towards politics would repel people from political action, they claim for an idea of a _skeptical engagement_ with two different possibilities: “a context of mistrust and cynicism might discourage or pervert political participation, on the one hand, or spur innovation, on the other” (2013:537). Deep down they showed how civic organizations strategically deny the label of ‘politics’ in order to better engage with and to promote change within the local community. Interestingly, this former objective included activities that can be considered very political in nature, such as joining the city council, or lobbying with the local politicians and government. Yet, this phenomenon of denying certain labels, without necessarily changing the nature of the activity, is also found elsewhere in the literature: in registering the birth of the area of social movements, Borch (2012:259-60) describes that the scholars involved strategically put aside the jargon that would link them to the negative approach to crowds and masses: “to avoid the association with the register of abnormality, irrationality, crowds and masses, scholars now argued for a more rational conception of social movements where these were seen as entities aiming to achieve specific, commonly shared purposes.” 

In sum, rather than departing from common place critiques inherited from political theory, it seems more fruitful to grasp how the crowdfunding community conceives politics and the public realm. The hypothesis is that new forms of public realm, new forms of acting according to agreed-upon rules and values might be at stage. If this hypothesis is correct these novelties may reinterpret the processes of individualization, the critiques on the mitigation of the public realm, as well as it might suggest a reconsideration of traditional concepts from political theory such as participation or engagement.

What is at stake is the inherent tension put forward by crowdfunding: on the one hand their focus on individual autonomy seems to foster an atomized private realm, relegating the decisions about what should and should not be done to the sphere of individuals' moral and judgements. On the other hand, the mechanisms embraced by crowdfunding (from the functioning of the online campaigns to the dependence built on ties within a close network) require these decisions to be handled by a greater audience: without supporters, no project becomes reality, without collaboration within the network (open source included), no action is possible. Their idea is linked to the building of an alternative space in a very personal, subjective, individual, non-expansive and local way. They refrain the idea of _changing the world_ themselves — that would be an unacceptable violence against the individuality.

The brightest possibility would be to understand that politics can be about empowering action — and not only about contemplation and deliberation, as in ancient Greece (Arendt 1998). Therefore opening more possibilities for ordinary people to act could be a form of (re)engagement in politics. In that scenario individualistic antipolitics would be declined in as so far as each idea, project or proposal would still be dependent on a plurality in order to become action (even if this plurality can be considerably smaller than the majority usually required by formal democracies). The intrinsic need of financial and community support to execute projects through crowdfunding creates a kind of gatekeeper for individual moral and judgements. However political theory also suggests a dark possibility. For instance Weber's (1986) late writings argue that his disavowal of the bureaucratic administration could be overcome by a charismatic leader — a concept usually employed as opposed to tradition and legal forms of authority with Weberian theory. He argued that a leader was necessary to revitalize the arguably inefficient German government. The problem was the “completely outmoded system of management by notables” (Weber 1986:130), that is to say, old professional and bureaucratic politicians, which was actually preventing the brightest intellectuals from engaging in politics. Charisma would be the basis of this new political leader, who should be strong enough to even dissolve the parliament if needed. Explicitly he argued for a strong president empowered through election as an alternative to challenge the power of the parliament, the outmoded system. Between Weber's and Arendt's oeuvre Germany testified the emergence of the National Socialist dictatorship. A leader in fact was granted these powers in 1934 by almost 90% of the voters. A leader that would merge the role of president and chancellor, dissolve the parliament as well as opposing parties, and interrupt all efforts to revive democracy in Germany after the Great War. Ironically a leader whose terror is of the most important inspirations for Arendt's first political writings.

What this research has accomplished so far is restricted to the relevance and tensions that crowdfunding studies can inspire in terms of social and political thought. The bias of this research along with its initial stage cannot go further than that. However the speculations from the last paragraph probably are the two most extremist positions possible in this scenario, and what crowdfunding could represent in terms of politics is somewhere in between. The continuation of this investigation, by this one and other research projects, might clarify the nature of the politics achieved by crowdfunding communities.

== References

[references]
* Allen-Robertson, J. (2013). _Digital Culture Industry: A History of Digital Distribution_. Basingstoke: Palgrave Macmilllan.
* Arendt, H. (1973[1963]). _On Revolution_. Bungay: Penguin.
* Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.
* Bellah, R., Madsen, R., Sulliva, W., Swidler, A. and Tipton, S. (2008[1985]). _Habits of the heart_. Berkeley: University of California Press.
* Benkler, Y. (2010). The Idea of Access to Knowledge and the Information Commons: Long-Term Trends and Basic Elements. In Krikorian, G. and Kapczynski, A. (eds.). _Access to Knowledge: In the Age of Intellectual Property_. New York: Zone Books.
* Bennett, E. A., Cordner, A., Klein, P. T. and Baiocchi, G. (2013). Disavowing Politics: Civic Engagement in an Era of Political Skepticism. _American Journal of Sociology_, 119(2). Pp. 518-548.
* Berlin, I (1999[1958]). Two Concepts of Liberty. In Warburton, N. (ed.) _Arguments for Freedom_. Milton Keynes: Open University. Pp. 155-165.
* Borch, C. (2012). _The Politics of Crowds: An Alternative History of Sociology_. Cambridge: Cambridge University Press.
* Coleman, E. G. (2013). _Coding Freedom: The Ethics and Aesthetics of Hacking_ [digital book]. Princeton: Princeton University Press.
* Habermas, J. (2005[1981])._The Theory of Communicative Action: Lifeworld and System_. Boston: Beacon.
* Jaffe, E. (1997). Our Own Invisible Hand: Antipolitics as an American Given. In Schedler, A. (ed.) _The end of Politics? Explorations into Modern Antipolitics_. New York: Macmillan. Pp. 57-90.
* Joas, H. and Knöbl W. (2009[2004]). _Social Theory: Twenty Introductory Lectures_. Cambridge: Cambridge University Press.
* Kapczynski, A. (2010). Access to Knowledge. A Conceptual Genealogy. In Krikorian, G. and Kapczynski, A. (eds.). _Access to Knowledge. In the Age of Intellectual Property_. New York: Zone Books.
* Kelty, C. (2008). _Two Bits: The Cultural Significance of Free Software_. Durham: Duke University Press.
* Lessig, L. (2006). _Code: Version 2.0_. New York: Basic.
* Mouffe, C. (2005). _On the Political_. London: Routledge.
* Pramuk, J. (2015) Student Debt Crushes Innovation: College President. In _CNBC_. Available at http://cnbc.com/id/102377355. Accessed 28 Jan. 2015.
* Schedler, A. (1997). Introduction: Antipolitics — Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into Modern Antipolitics_. New York: Macmillan. Pp. 1-20.
* Sniderman, P. M. and Bullock, J. (2004). A Consistency Theory of Public Opinion and Political Choice: The hypothesis of men dependence. In Saris, W. E. and Sniderman, P. M. (eds.). _Studies in Public Opinion: Attitudes, nonattitudes, measurement error, and change_. Princeton and Oxford: Princeton University Press. Pp. 337-357.
* Tocqueville, A. (1986[1835]). _De la démocratie en Amérique, I_. Paris: Gallimard.
* Weber, M. (1976[1900]). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.
* Weber, M. (1978[1922]). _Economy & Society: An Outline of Interpretive Sociology_. Berkeley: University of California Press.
* Weber, M. (1986[1919]). The Reich President. _Social Research_, 53(1). Pp. 125-132.
* Wolin, S. (2004). _Politics and Vision: Continuity and Innovation in Western Political Thought_. Princeton and Oxford: Princeton University Press.
