= Crowdfunding and the reconfiguration of public and private space
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_University of Essex_

****
*Abstract*

This ongoing PhD research consists of a social and political analysis of the crowdfunding phenomenon. Platforms such as Kickstarter or Indiegogo make initiatives tangible through actions of ordinary people, dismissing institutional support from government or corporations. Through a social and political analysis of these online gatherings, my ongoing PhD research calls into question the spaces where people pursue public and private interests.

The relationship between public and private spheres of action has been long debated in the literature. Arendt criticized the role of modern state as a guardian of individual freedom, highlighting that real possibilities of political action still restricted to political elites. Simultaneously private interests of corporations have compromised the political sphere, argues Wolin and Schedler. According to them states take decisions within the private realm, diminishing the spaces for public interests. Finally Bellah argued that this scenario and its emphasis in the private interests favored individualism. Yet, he adds, people are not comfortable with it: the lack of social ties makes them eager for connections.

This paper introduces some of my data and findings, focusing on interviews I conducted with people engaged with crowdfunding in Brazil, the UK and the USA. I start from the point that if the institutional conjuncture seems to seize the public sphere from people, citizens might be fighting back recreating the public realm within this purportedly private space. Instead of traditional political organizations (such as parties or social movements) crowdfunding benefits from practical disruptions emerged from new technologies. Yet at the same time crowdfunding might grasps what post-representativeness could be or what a post-political pragmatic approach could look like. The discussion considers political possibilities and limitations of this new setting for private and public spaces.

*Keywords* +
crowdfunding, internet, politics, public space, private space.
****

== Introduction

The phenomenon of crowdfunding is among several possibilities brought to existence by emergence of the internet and of the web 2.0. While turn of the century platforms for blogging and social networking were focused on the production of online content by ordinary users, arguably what came next was the extrapolation of digital boundaries. Underneath this claim lies a set of changes that includes (but is not limited to) the falling costs of production of different kinds of goods and services (such as 3D printers and video production, for example), the ease of finding collaboration with others world wide, and niche online stores delivering very specialized products all around the world (from tools for peculiar hobbies, to DIY supplies and technological gadgets). Yet this scenario takes into account abstract and intangible changes, such as the idea of collaborative and crowdsourced projects (the most renowned being Linux, Wikipedia and the Human Genome Project), the debate over intellectual property (such as the struggle and changes the music industry faced after the advent of the MP3, or yet Google book-scanning efforts and the succeeding debates) and the dispute over privacy on the internet (especially after WikiLeaks, specific Anonymous operations labeled as hacktivism, and the Edward Snowden case). In sum, the internet has been pivotal to transformations that affect several spheres of social life. Within these changes crowdfunding is a specific mechanism that integrates different aspects of these novelties.

Basically crowdfunding platforms are websites on which users expose their own projects and ideas, asking for financial contributions in order to be able to execute these projects. Enthusiasts can offer different amounts during the period in which the campaign is online. If the project is funded usually there are some rewards to those who made it possible. It is not rare that the simple execution of the project is considered a perk to everyone involved and interested (independently of any kind of financial collaboration). When this is the case, alternatives to copyright licenses such as Creative Commons play an important role. The biggest players in this field are Kickstarter and Indiegogo, and through this mechanism different kind of projects have been funded: from museums to individual's trips; from olympic athletes to personal charity; from technological gadgets to online education; from music albums to medical equipments; from comics to public transportation.footnote:[It is not the case of commenting on individual projects, but the references for the projects mentioned above are (respectively): Tesla Museum (asked for US$ 850k, raised more than US$ 1.3m – http://www.indiegogo.com/teslamuseum), Destino Incomum (asked for US$ 100, raised US$ 1k – http://catarse.me/destinoincomum), Larissa Juk (asked and raised US$ 10k – http://catarse.me/larissario2016), Alan Barnes Fund (asked for US$ 750, raised US$ 495k – http://gofundme.com/l0dt9o), Glif (asked for US$ 10k, raised US$ 137k – http://kck.st/bb6Tuu), Escola Livre de Jornalismo (asked and raised US$ 9k – http://catarse.me/enois), Amanda Palmer (asked for US$ 100k, raised roughly US$ 1.3m – http://kck.st/JliwH9), Avado (asked for US$ 5k, raised US$1.3m – http://medstartr.com/projects/13), Corey Mohler (raising US$ 1.1k monthly through a recurring platform – http://patreon.com/ExistentialComics), and Kansas City B-cycle (raised 60% of the US$ 700k target – http://neighbor.ly/projects/bikesharekc). All values were converted to US dollars when the project used a different currency.]
 
The fact that such a variety of ideas are becoming tangible without a formal sponsorship of incumbent institutions such as government or corporations makes of crowdfunding a promising case for sociological studies. This ongoing doctoral research focus on the way people engaged in this type of project employ a pro-active and hands-on mode that challenges these incumbent institutions. Interestingly the tone of this challenging attitude is not of direct confront against public administration or multinational companies, but of finding an alternative path considerably marginal from governments and corporations. Yet, in opposition to initiatives such as social movements or NGOs, crowdfunding unreservedly embraces the idea of profit and reshapes it as a sustainable mean to empower this marginal path. Profit is often dislocated from an endless accumulative disposition footnote:[As described, for example, in Weber's _The Protestant Ethic and the Spirit of Capitalism_ (1976).] and understood as a tool for autonomy, as an important resource to enable individual and collective (political) action.s of the private and public realm and, subsequently, how it might contribute to the comprehension of politics, both in their everyday life as well as in a wider understanding of politics.

The following section explores current debates in terms of political theory. Arguably nowadays society has become antipolitical, both from the individual and institutional perspectives. Based on Arendt (1998, 1973), the conceptual framework employed here takes the antipolitical argument into account together with an approach focused on the understanding of the public and the private realm. The subsequent section offers an overview of the in-depth interviews that are the empirical support to this paper and exposes the core of the findings: from an analytical description of their lifestyle, the objective is to explore how their attitudes relates to the wider context of social institutions such as government, corporations, money and professional career. This analysis is based on their focus on individual autonomy and the controversial possibility of politics (and values inherent to the public realm) being revitalized through this process. 

== The public and the private realms in a modern, anti political and individualist society

The assumption underneath this research is that crowdfunding communities can be understood as politics in the sense that they create alternative spaces for people to pursue public and private interests. The division between public and private was forged in ancient Greece, when one should keep the pursue of private interests to the boundaries of the household, the core place for one's private life. That is to say that only citizens who have provided enough for them and their families were allowed to participate in the public life. This requirement had some basis on the role expected of this citizen when engaged with politics:

[quote]
Private wealth, therefore, became a condition for admission in public life not because its owner was engaged in accumulating it but, on the contrary, because it assured with reasonable certainty that its owner would not have to engage in providing for himself the means of use and consumption and was free for public activity. Public life, obviously, was possible only after much more urgent needs of life itself had been taken care of (Arendt 1998:64-5).

With the emergence of modern nation-state this classical distinction between the public and the private was severely affected. Modern age gave birth to the social realm which is neither public not private — and yet dislocated considerably what was understood as public. While private life was characterized by providing the household through labor, and while the public realm was the place for action and speech, the social has taken the political space from the public, printing on it important differences: now government acts as a gigantic housekeeping organization, looking for provision for a whole nation; that is to say, labor, once relegated to the private life, now is not only allowed but placed at the center of political life. For Arendt (1998:28-9) the dividing line between the household and politics

[quote]
is entirely blurred, because we see the body of peoples and political communities in the image of a family whose everyday affairs have to be taken care of by a gigantic, nation-wide administration of housekeeping. The scientific thought that corresponds to this development is no longer political science but ‘political economy’ or ‘social economy’ or _Volkswirtschaft_, all of which indicate a kind of ‘collective house keeping;’ the collective of families economically organized into the facsimile of one super-human family is what we call ‘society,’ and its political form of organization is called ‘nation’ (Arendt 1998:28-9).

Beyond forging the social realm, Arendt is describing a society in which the political has no place. This society has become “an organization of property-owners who, instead of claiming access to the public realm because of their wealth, demanded protection from it for the accumulation of more wealth” (Arendt 1998:68). This transformation has to be understood according to the specific ways through which modern societies developed into representative democracies, a constant struggle between emphasizing the anew claimed by the American and French revolutions on the one hand, and, on the other hand, the will to consolidate the ideal of freedom in a stable institution. For instance Thomas Jefferson had a particular standpoint within the Founding Fathers regarding the role of the constitution in this process: in ideological terms, he wanted the constitution to be strong enough to guarantee that no hostilities will take place in the political realm,nonetheless, in order to reinforce the founding anew, this same constitution should also be flexible enough to be revised from times to times. In practical terms, the effects of this thoughts can be seen in the representative democracy model and in its well established ways to participate in the political realm: elections, elected officials, senators, representatives, parties and voters (Arendt 1973).

Unfortunately this new institutional scenario has failed its original intents. First, this scheme was unable to extend the perception of participation from representatives to represented: when it comes to politics, citizens are disinterested and this fact can be found not only “among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage. Contempt for the law and the system also shows up regularly among the favored and highly placed” (Jaffe 1997:78). Sniderman and Bullock's (2004) idea of ‘menu dependence’ involves a very similar description of how ordinary people have a very discrete participation in politics. According to them, “citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties” (2004:338). Yet Wolin’s (2004) analysis of contemporary politics adds another layer to this branch of critiques: for him “in both, the political and the economic context contract appears as the essential condition to power”. In other words as the market economy would operate in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state would operate in a way that concentrates the (political) power in the hands of the political elite. By themselves the functioning of these both institutions are expanding the gap between rich and poor, rulers and ruled. And, as Arendt (1973:253) reinforced, underneath this wave of critiques towards modern society, there is the displacement of the public realm itself and the dilemma Jefferson had in mind:

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of being republicans and of acting as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens. 

This two-folded movement of degradation of the public and of inflation of the private has granted the space for corporations to extrapolate their private bounds and act within the public realm. Political decisions — already distant from ordinary people — gradually started to take into account a logic that do not pertain to the public realm, namely the logic of the market economy (Wollin 2004). This movement can be described as antipolitical through at least two arguments: in the one hand, it contributes to the mitigation of the public realm, which is suppressed by a self-regulated private one, the market (Schedler 1997); or, alternatively, whatever remains of the public realm starts to operate according to a logic inherent to the private sphere — what Schedler (1997) calls an inverted Habermasian colonization.footnote:[See Habermas (2005) for the original concept of colonization in that sense.] To be sure, Wolin (2004:588) highlights that both — state and market — are appropriating the methods of one another: “it is not that the state and the corporations have become partners; in the process, each has began to mimic functions historically identified with the other.” According to him, corporations’ move includes being in charge or funding health care, education and other welfare affairs; in parallel, governments’ move includes applying profits logic, notions of efficiency and management, to buoy its own actions. 

It is important to highlight that Arendt and Wollin do not deny the importance of government, party system and representative democracy for modern politics: these new elements of the public realm opened the political career for people from the lower classes, and the notion of elite enabled through the parties replaced old elites based on birth or wealth, for example (Arendt 1973). However despite these advances this process had a devastating side-effect for politics: by limiting the space for political action it consolidate the public realm as a place for private affairs. In Arendt's (1998:46) words, “the character of the public realm must change in accordance with the activities admitted into it, but to a large extent the activity itself changes its own nature too.”

The type of skills and activities held within these spaces were also impacted by these transformations. The importance given to labor and provision (formerly banished from the political), and to speech and action (formerly the core of political activity) also assume a different balance. Labor and wealth accumulation made sense in as so far as household provisions required them. Excelling in speech and public action in politics was a public virtue which the whole body of citizens would benefit of. Interestingly within the modern social realm labor was introduced to the political space and, at the same time, speech and action was dislocated to the private: “while we have become excellent in the laboring we perform in public, our capacity for action and speech has lost much of its former quality since the rise of the social realm banished these into the sphere of the intimate and the private” (Arendt 1998:48). From that perspective it is possible to address the lack of interest in politics as well as the endless interest in making money, which are overlapping aspects in many critiques towards representative democracy. Yet it is possible to set a theoretical background to accommodate the claims raised by crowdfunding communities when they affirm they are paving an alternative path, when they indirectly or directly challenge governmental and corporative sponsorship for private and public projects. The next section focuses on these claims and brings in this theoretical background to describe how crowdfunding affords its specific marginal discourse.

== Crowdfunding and social institutions

Drawing on 10 semi-structured in-depth interviews this paper organizes the findings of the first round of data collection for this project. According to the wider research design this stage explores the world views of people engaged in crowdfunding platforms in two different levels: founders or staff of these platforms, and project creators, that is, people who have recently submitted projects to these platforms. The access to this public is not uncomplicated. For instance, some of the platforms featuring among the wealthiest startups of recent years are considerably closed for interviews, only expressing themselves through their own public relations department. Yet very successful project creators usually end up dealing with thousands of followers on social media, making their attention to incoming messages relatively unreliable. In spite of that, this initial stage was able to interview people involved with seven different platforms (Indiegogo, CrowdCube, Catarse, Benfeitoria, Cinese and Unlock) from three different countries (USA, UK and Brazil). The interviewees, 4 women and 6 men, were from four different countries (the three above plus Romania) with ages varying from 24 to 61 years old. Names and other references that could be used to identify informants have been anonymized. The entry points for access to these people involved different initiatives: attempts to direct contact through email and social media, attendance to events and places related to sharing economy and similar topics, personal contacts in the entrepreneur and technological scene in the USA and Brazil, and, mainly, snowballing.

The structure of the interview was funnel shaped: the fist topic was focused on self identity, lifestyle, main activities, and on one's own life trajectory. Usually the conversation would end up in crowdfunding, which was exactly what was planned for the second block of the interview: discussing why they have embraced these platforms (whether it was as founder, staff or project creator) and how the experience was, or have been so far. Finally, if issues about government, corporations and formal politics have not emerged, these topics were raised in a third and final block in order to assimilate interviewee's perception about the institutional context surrounding them. 

Unintentionally the sample ended up being biased towards initiatives that make efforts to differentiate themselves from the mainstream startup and entrepreneurship agenda. On the one hand, this was due to the aforementioned difficult in getting access to big players in the startup and entrepreneur scene. For instance, even former employers of some of these platforms recurred to their former employer guidelines for declining to be interviewed, suggesting me to check their public relations material. On the other hand, this difficulty to gain access to the startup driven enterprises, together with the easiness to gain access to the alternative branch, reinforces the aforementioned approach on the marginal path I shall expand on next.

The following section draws on my interviewee's personal experiences and life choices. The idea is to grasp how they deal with everyday choices regarding making a living of their projects, including inspirations and personal aspirations. Drawing on this micro sociological approach the subsequent section discusses how this specific world view identifiable within crowdfunding relates to social institutions, that is to say, a descriptive view of the subtle and the explicit challenges they foster. On top of that there is the sociological discussion regarding the public and the private realm as well as the possibilities for politics in modern society. 

=== Lifestyle, non-traditional pathways and motivations

_Approx: 3 pages_

* Maker culture, hands-on attitude: focus on action.
* Autonomy is the key driver.
* Clarify that the digital culture has a tangible aspect of accessibility, easiness to communicate, to spread the word about one's project. But also, this crowdfunding community intersects with different (and more specific) influences such as hacker culture, and access to knowledge.
* Putting all together, to the maker culture it is added an ideological component: the willing to make certain projects happen is an important motivation, even if no direct benefit is taken from this realization (maybe this is slightly different from more utilitarian market relationship, and arguably it fosters a certain kind of common good).
* How they make a living (different projects, the idea of multiple smaller pots in opposition to a traditional career and the idea of an all-in in one single pot).
* The importance of building a network based on mutual trust to sustain the individuals' projects.

=== Challenging incumbent institutions

_Approx: 5 pages_

* From a radical standpoint, one could say that there is a complete lack of trust in corporations and government; a more subtle view would argue that people engaged in crowdfunding simply do not want to depend on these incumbent and traditional institutions.
* Connect this attitude to Arendt's critique of modern societies and the mitigating of the public realm. Also to private interest being persuasive within corporations and government (Wolin).
* Extend the argument to the contempt for NGO, volunteering, social movements and other traditional a approaches to politics: when there is the attempt to be universal, to shadow the individual, there is contempt.
* The peculiar role of money (and profit) as a requirement to ensure autonomy and means for action to the individual. 
* Discuss individuality and the value of building a network: on the one hand, networks helps in putting projects through, on the other, it could be a way to rescue the idea of citizenship that was lost according to Arendt's claims (link to Bellah's individualism).

== Debate: crowd funding initiatives, the private and the public

_Approx: 2 pages_


* How their idea autonomy is linked to an ideal of building a better world in a very personal, subjective, individual, non-expansive and local way (how it is egocentric, but not egoistic; it values the individual to the extent that the idea of _let's change the world_ is a representation of an unacceptable violence against the individuality).
* The bright side: politics as action, not as contemplation (Arendt), and the possibility of a public realm, of of a different kind of awareness towards social ties (also related to Arendt's claims)
* The dark side: Weber, his hunch on the charismatic authority (the risks of trusting the charisma, the individual visions and dreams, as an escape from bureaucratic modern – and rather inefficient – institutions), and what Weber could not testify: the emergence of National Socialism (which, interestingly, was the starting point to Arendt's thought).

== References

Arendt, H. (1973). _On Revolution_. Bungay: Penguin.

Arendt, H. (1998). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.

Jaffe, E. (1997). Our Own Invisible Hand: Antipolitics as an American Given. In Schedler, A. (ed.) _The end of Politics? Explorations into Modern Antipolitics_. New York: Macmillan. Pp. 57-90.

Habermas, J. (2005)._The Theory of Communicative Action: Lifeworld and System_. Boston: Beacon.

Schedler, A. (1997). Introduction: Antipolitics — Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into Modern Antipolitics_. New York: Macmillan. Pp. 1-20.

Sniderman, P. M. and Bullock, J. (2004). A Consistency Theory of Public Opinion and Political Choice: The hypothesis of men dependence. In Saris, W. E. and Sniderman, P. M. (eds.). _Studies in Public Opinion: Attitudes, nonattitudes, measurement error, and change_. Princeton and Oxford: Princeton University Press. Pp. 337-357.

Wolin, S. (2004). _Politics and Vision: Continuity and Innovation in Western Political Thought_. Princeton and Oxford: Princeton University Press.

Weber, M. (1976). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.
