= [WORK-IN-PROGRESS] Contemporary political theory and the possibilities within crowdfunding footnote:[This text articulates a _late_ literature review suggested during the June 2014 board meeting; in the future this contents should be integrated to the literature review that is part of the project design discussed at this meeting.]
Eduardo Cuducos
:homepage: http://about.me/cuducos
:numbered:
:toc:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_2^nd^ year PhD student in sociology, University of Essex_

== Introduction: Politics and its modern foundations

The relevance of the concepts of public and private sphere is not new into political theory. This literature review aims at considering these topics under a wider political framework in order to set the basis for a doctoral research on the political consideration of the crowdfunding phenomenon.footnote:[Crowdfunding is the name given to a specific mechanism of crowdsourcing through which users can propose projects (setting the financial target in order to execute that project) and other users can back it (by financially contributing to that project). Eventually some projects are founded in this scheme, operating basically according to the action of ordinary people, i.e. without incumbent institutions explicitly supporting it.] The hypothesis is that a post-political approach to political action can reveal a relationship between political theory and what have been done under the label of crowdfunding.

Therefore the following sections discuss how these concepts, i.e. public and private sphere, are understood since the revolutions that founded the modern understanding of political issues nowadays: the American and the French Revolutions (Arendt 1973). Next, some critiques are considered into the scope of politics in terms of different ideas of centralization (and the consequent issues that emerge from this centralization). The subsequent section touch upon common critiques towards contemporary political participation and representation, namely the individualization process and the possibilities of a post-political phase. Finally, based on this theoretical review, the last part discusses research hypotheses about how crowdfunding could be comprehended as a relevant element to understand the future of politics. What is suggested is that crowdfunding have impact over the perception of the public and the private affairs, possibly taking part in this political configuration.

== Arendt’s critique of modern politics

Analyzing the American and French Revolutions, Arendt (1973) argues that the ‘spirit of revolution’ underneath these outbreaks conceals two elements that have become opposites throughout history. Moreover these elements set the stage for certain polarization within contemporary politics. According to her, the concern with stability contrasts with the spirit of the new, the one aspiring a new political body -- these concerns “seem irreconcilable and even contradictory” (Arendt 1973:222). In other words, while aspiring to create a new government, these revolutions had to confront the paradox of founding a new way to organize politics and, at the same time, of keeping it open to further adaptations -- including openness to changes as deeper as the ones they were promoting at that moment. In order to face this paradox, Arendt argued, there was a conceptual and practical loss in terms of politics:

[quote]
Perhaps the very fact that these two elements ... have become opposites in political thought and terminology -- one being used as conservatism and the other being claimed as the monopoly of progressive liberalism -- must be recognized as the symptoms of our loss ... In other words, to the extent that our political terminology is modern at all, it is revolutionary in origin. And the chief characteristic of this modern, revolutionary vocabulary seems to be that it always talks in pairs of opposites -- the right and the left, reactionary and progressive, conservationism and liberalism, to mention a few at random (Arendt 1973:223).

In fact, Arendt (1973) highlighted how the American and French uprisings ended up favoring, each one of them, a different element of this paradox: while the USA focused on the stability of the new government, France seemed to be closer to the ideal of openness to changes. In sum, “the revolution in the USA resulted in a stable political scenario, not in a long decade of instability as the post revolutionary France” (Borch 2012:125). What happen next have consequences not only in political theory but also in social theory. For instance, Christian Borch (2012) argues that the semantics of crowds in the nineteenth and twentieth-century France was characterized by a negative approach to crowds (describing them, basically, as irrational and destructive towards social order); alternatively, in the USA, these assemblies were regarded in a very positive manner (depicted as simultaneously the result and the representation of a health democracy). These interpretations of social collective behavior will appear later on this review, but before that it is important to understand the critiques in terms of political thought at the core of the unfold of these revolutions.

Arendt’s analysis ended up suggesting that in the USA ordinary people have only a minimum engagement with politics. This conclusion seems to resonate with antipolitics critiques, such as Erwin Jaffe (1997:78), who argued that this disinterest is not only found only “among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage. Contempt for the law and the system also shows up regularly among the favored and highly placed.” Yet, he adds, disconnectedness is at the core of this antipolitical process that American faces nowadays. Arendt (1973) take the Founding Father as a starting point of this process, and place the representation challenge at the spotlights: when Jefferson was reflecting upon the violent upsurging in post revolutionary France, he considered that maybe people (not only their representatives) should be able to reform the constitution from times to times (i.e. in conciliating the two elements of the spirit of revolution). Jefferson, she argued (1973:235-6), was the only one among them who pondered about the kind of freedom that was emerging in France and in the USA: 

[quote]
He [Jefferson] knew, however dimly, that the Revolution, while it had given freedom to the people, had failed to provide a space where this freedom could be exercised. Only the representatives of the people, not the people themselves, had an opportunity to engage in those activities of ‘expressing, discussing, and deciding’ which in a positive sense are the activities of freedom … Only Jefferson among the founders had a clear premonition of this tragedy, for his greatest fear was indeed lest ‘the abstract political system of democracy lacked concrete organ.’

In spite of that, Founding Fathers’ focus was on representativeness and at the end of the day what they proposed was that representation should substitute direct political action for very practical reasons -- e.g. the chamber, the congress, ‘the room will not hold them all’ in case of direct political action. Accordingly the elected should respect the will of the electors and opinions on which the election was handled. But, as Arendt (1973:236) puts, the founders “must have been the first to know how far removed this theory was from reality.” As she argued, first the “public realm was vanished” (1973:237) as government focus was mostly on administrative issues, relegating decisions to experts, i.e. keeping these decisions closed to opinion and genuine choice from ordinary people.footnote:[It is noteworthy that in terms of political thought Arendt differentiated opinion and interests: “Interest and opinion are entirely different political phenomena. Politically, interests are relevant only as group of interests, and for the purification of such group interests it seems to suffice that they are represented in such a way that their partial character is safeguarded under all conditions, even under the condition that the interest of one group happens to be the interest of the majority. Opinions, on the contrary, never belong to groups but exclusively to individuals … Opinions will rise whenever men communicate freely with one another and have the right to make their views public” (Arendt 1973:227).] Second, this displacement of the public realm, together with the representative democracy option, ended up reestablishing the boundaries between ruler and ruled, exactly the boundaries these revolutions aspired to eliminate: “once more the people are not admitted to the public realm, once more the business of government has become the privilege of a few” (Arendt 1973:237).

In a practical sense, the argument is that the power conferred to people was limited to the day of the election, what kept the public space restricted to the representative of the people in the whole period between the elections. These problematic aspects of the American Revolutions have yet further consequences:

[quote]
Opinions are formed in a process of open discussion and public debate, and where no opportunity for the forming of opinions exist, there may by moods ... but no opinion. Hence, the best the representative can do is to act as his constituents would act if they themselves had any opportunity to do so... Through pressure groups, lobbies, and other devices, the voters can indeed influence the actions of their representatives to execute their wishes at the expense of the wishes and interests of the other groups of voters. In all these instances _the voter acts out of concern with his private life and well-being_, and the residue of power he still holds in his hands resembles rather the reckless coercion with which a blackmailer forces his victim into obedience than the power that arises out of joint action and joint deliberation (Arendt 1973:268-9, emphasis added).

Once more, Arendt’s considerations resonates with contemporary political critiques. For instance, Sniderman and Bullock (2004) idea of ‘menu dependence’ involves a very similar description of how ordinary people have a very discrete participation in politics. According to them, “citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties” (2004:338).
Therefore, this ‘menu’ of choices from which ordinary people can chose is designed not by them, but by a political elite. Yet, Wolin’s (2004) analysis of contemporary politics adds another layer to this branch of critiques. He compares Marx’s and Locke’s theories to suggest that “in both, the political and the economic context contract appears as the essential condition to power”; therefore, as the market economy operates in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state operates in a way that concentrates the (political) power in the hands of the political elite. He (2004:429) goes further in denouncing Locke’s naivety:

[quote] 
Had he [Locke] been truly concerned for citizens to retain substantial powers of self-government, and had he truly valued political participation, he would have attended as to having his individuals retain the political skills acquired in the pre-contractual condition as he did to perpetuating their acquisitive instincts. So politically desensitized were Locke’s citizens that only ‘a long train of Abuse’ could stir them to revolt.

To sum up, Wolin (2004:429) consider that in this scenario, it is “virtually impossible for the citizen to recognize these powers as his own.” Strictly linked to the situation described by Sniderman and Bullock (2004) and Wolin (2004) is Arendt’s (1973:253) analysis of the Founding Fathers, particularly of Jefferson concerns:

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of _being_ republicans and of _acting_ as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens.

An alternative to this choices of representative democracy might have been French councils: both, the councils an and the party system that was linked to the American Constitution, were emerging from the modern outbreaks of these revolutions and were accompanying the nation-states forged in the process. However, stability of the unfolding in the USA contrasted with the catastrophic (in terms of politics) unfolding in France. The result was that direct political participation through councils were labeled as a “spectacular failure” (Arendt 1973:247). This failure is discussed by Arendt (1973:263), who argued that in councils “party membership played no role whatsoever” and, consequentially, they were always antagonizing (and antagonized by) other participants whose behavior was closer to party system, i.e. old parliaments and constituent assemblies. Yet, for her, councils emerged to fulfill a role that was strictly related to political participation and action; on the contrary, the role of parties has always been representation. The failure of councils, however, is perceived not only on the political realm, but also in their inability to, for example, run the factories. To Arendt, this problem is clarified by the understanding that as institutions designed for political action and participation, councils lacked the managerial and administrative skills for such task. On the other hand, parties had the advantage of handling administrative issues in a more straightforward way, given them the apparent success in the realm of politics, in the realm of a government organized around representativeness where the focus, as aforementioned, lay more on administration than in politics.

[quote]
While it is true that they were incapable of organizing, or rather of rebuilding, the economic system of the country, it is also true that the chief reason for their failure was not any lawlessness of the people, but their political qualities. Whereas, on the other hand, the reason why the party apparatus, despite many shortcomings -- corruption, incompetence and incredible wastefulness -- eventually succeeded where the councils had failed lay precisely in their original oligarchic and even autocratic structure, which made them so utterly unreliable for all political purposes (Arendt 1973: 275).

Arendt’s (1973) conclusion is that while it is understood that through voting people actually participate in the political sphere, the current scheme of representation makes the parties as a mean through which provide itself with an apparent popular support. Ultimately, parties can recruit ordinary people to this political elite, but the communication between people and representative will still resemble the one between ruler and ruled. It is important to highlight that Arendt does not deny the importance of parties in modern politics: e.g. they opened the political career for people from the lower classes, and this notion of elite through the party replace the old elites based on birth or wealth. However, she emphasized that the party framework is less meaningful in providing a government _by people than in recruiting an elite to govern the people. This movement, despite the advance in terms of democracy, has a devastating side-effect for politics -- namely that in limiting the space for political action (which is restricted to parties), it jeopardies the idea of a public space and, closing a self-degradation cycle, with a poorer public space the elite recruitment ran by parties have difficult to find aspirations to politics among ordinary people. The challenge, she added, is not to conciliate freedom and equality, but equality with authority.

[quote]
No doubt this form of government, if fully developed, would have assumed again the shape of a pyramid, which, of course, is the shape of an essentially authoritarian government. But while, in all authoritarian government we know of, authority is filtered down from above, in this case authority would have been generated neither at the top nor at the bottom, but on each of the pyramid’s layers; and this obviously could constitute the solution to one of the most serious problems of all modern politics, which is not how to reconcile freedom and equality but how to reconcile equality and authority (Arendt 1973:278).

Hence, this panorama of modern politics suggests that when it comes to politics the institutional problem contemporary societies face has to do with the mitigating of the public realm. Another way to see this issue is to put the focus on the emphasis modern political institutions have put on the private realm: by minimizing the space for ordinary people to be political, it paved a way for them to exercise their private affairs -- and this is the focus of the next section.

== Centralization and politics

Although Arendt (1978:252) focus on the loss of relevance of the private realm, she mentioned the simultaneous rise of the private realm. In her words, "conditions, not of prosperity as such, but of rapid and constant economic growth, that is, of a constantly increasing expansion of the private realm -- and these were of course the conditions of the modern age". This linkage between the expansion of the private sphere and a certain economic policy is not rare within political thought. For instance, Wolin (2004:587) affirms "although the state continues to play a for from negligible role in an increasing globalized economy, the power wielded by multinational corporations has made their cooperation and acquiescence indispensable." By these means, within contemporary governments, the logic of markets is incorporated in the logic of the state. In other words, political decision -- already distant from ordinary people, as described in the previous section -- ended up being taken not by a logic inherited form the public realm, but from the private one. This movement is described as antipolitics by in, at least, two ways: in the one hand, it contributes to the elimination of the public sphere (suppressed by a self-regulated private one, the market, in the other, it represents what Schedler (1997) calls an inverted Habermasian colonization: the life-world, attached to the idea of a private sphere, is in fact colonizing the system, roughly, the realm of public affairs.

To be sure, Wolin (2004:588) highlights that both -- state and market -- are appropriating the methods of one another: "it is not that the state and the corporations have become partners; in the process, each has began to mimic functions historically identified with the other." According to him, corporations’ move includes being in charge or funding health care, education and other welfare affairs; in parallel, governments’ move includes applying profits logic, notions of efficiency and management, to buoy its own actions. The consequences of this process of merging is related to the mitigation of the public sphere (in favor of a private one), and is directed related to politics: ultimately the consequence claimed by Wolin is that money becomes more important than votes. The public realm and the representative democracy are, once more, targeted as the victims of modern politics and economics -- this time not from a political philosophy standpoint, but from a more pragmatic analysis of power structures underneath contemporary societies.

Wolin's (2004) analysis adopts a the concept of _Superpower_ (written in capital according to the author, but kept in small caps henceforth), i.e. the power constituted by the joint enterprise of government and corporations. The peculiarity of this assemblage is its informality, is the lack of formal constitution: the superpower derives its legitimacy from a legal framework that is, in nature, democratic; however it overcome this mechanism. The author uses racism as an analogy: in spite of the fact that expressions of racism are an offense according to several legal systems, court decisions and jurisdictions, unfortunately racism is still alive on everyday practices (e.g. employment practices or segregated neighborhoods). Moreover, this informal centralization of power ends up as what Wolin call an _inverted totalitarianism_:

[quote]
The crucial element that sets off inverted totalitarianism from Nazism is that while the latter imposed a regime of mobilization upon its citizenry, inverted totalitarianism works to depoliticize its citizenry, thus paying a left-handed compliment to the prior experience of democratization. While the Nazis strove to give the masses a sense of collective power and confidence … the inverted regime promotes a sense of weakness, collective futility that culminates in the _erosion of the democratic faith, in political apathy and the privatization of the self_. Where the Nazis wanted a continuously mobilized society that would support its masters without complain and enthusiastically vote ‘yes’ at the managed plebiscites, the elite of inverted totalitarianism wants a _politically_ demobilized society that hardly votes at all (Wolin 2004:592, first emphasis added, last one in the original).

Wolin (2004) goes on to reach conclusions that goes hand in hand with other aforementioned arguments towards the formation of a political elite, i.e. a political elite that is not defined, necessarily, by a political reasoning, by the successful establishment of a public sphere -- the superpower is Wolin's way to explain how this elitism is embedded within democracy. Again, while Arendt reached similar conclusions recurring to political philosophy, Wolin defends similar conclusions from a the analysis of power structures, from the centralization of power (and the consequent effects on politics). As en example, he (2004:594) mention the media:

[quote]
For more than two centuries it has been a commonplace observation that if democracy is to flourish, its citizens must not only be educated but enjoy access to a variety of sources of knowledge and opinion … The concentration of ownership of newspapers and radio and television stations in relatively few hands had produced a near-homogeneity of culture and opinion that, when it is not trivial, is either bland or stridently conservative. The net effect of the concentration of media ownership is to enclose the civic mind within the equivalent of a hermetically sealed dome.

At this point, it worth it to highlight that the antipolitics critiques that are explicitly put forward by Schedler (199) and Jaffe (1997) are present also underneath Wolin (2004) and Arendt's (1973) writings. There is a common ground between these approaches, a common ground from which it is possible to trace a liaison between different aspects of political though and practical challenges faced by contemporary political institutions. This issues are the focus of the next section. Before moving on, it is important to clarify that the claim for a common ground does not implies a simply convergence of all critiques fomented by this group of author. For example, while for Arendt the hierarchization within democratic governments is not a problem _per se_,footnote:[See last Arendt's quote from the previous section.] for Wolin the idea of governing is anti-democratic in nature.footnote:["Governing means manning and accommodating to bureaucratized institutions that, _ipso facto_, are hierarchical in structure and elitist, permanent rather than fugitive --- in short, anti-democratic” (Wolin 2004:603).]

== Contemporary issues

The issues touched upon in the previous section relates to a series of problems that contemporary political institutions have to face. In sum, what is predicted from this series of criticism is that ordinary people would not get involved in politics: they have little expectation and opportunities to really participate in the process. Antipolitics seems to be the norm:

[quote]
Antipolitics is present when politics itself is regarded with cynicism but also seen as a contaminant of society, indeed the enemy of all other societal activity. When antipolitics flourishes, politics itself becomes the central target of opposition and is perceived in extremis as unnecessary, the potential destroyer of all that is praiseworthy in human affairs. Antipolitics in this sense inverts Hobbes’s analysis: whereas he argue that politics is the precondition for civil and human conduct, the antipolitical actor or theoretician maintains that politics is a threat to morality, enterprise and all authentically human values (Jaffe 1997:62).

This situation can be accounted by the removal of the public sphere from the everyday life of ordinary people (Arendt 1973, Wolin 2004, Schedler 1997). Following this branch of analysis, two specific topics seems to gain relevance in the political theory literature: on the one hand, the individualization process, related to the emphasis conferred to the private sphere; on the other hand, the post-political argument, related to news ways through which it is possible to conceive political participation from individuals deprived from a public sphere, and, arguably, deprived from a strict interest in the public realm. These are the foci of the next sub-sections.

=== Individualization

According to Jaffe (1997) one of the signals of the antipolitics mechanisms regarded above is disconnectedness: since the public realm is fading out, since the private realm (embodied by the corporation market) is expanding significantly within society, the Hobbesian notion politics, of individuals acting according to a set of agreed-upon rules, makes little sense. Individual judgments, Jaffe argues, is replacing collective structures such as legal jurisdiction, for example. The argument linking this focus on the individual, tangled up with the impoverishment of the dynamics of between a public and a private sphere, is recurrent in social theory. For instance, Tocqueville (1986) argued that the USA the vibrant and dynamic relationship between these two spheres was what could explain the success of American institutions he registered in the first volume of his _De la démocratie en Amérique_.

Bellah _at al_ (2008) follow Tocqueville's argument, reinforcing that "democracy can be vigorous only if citizens are prepared to go beyond the immediate private context (family and kin) and to articulate their views as individuals in a public sphere, in circle of friends, associations, in political parties etc." (Joas and Knöbl 2009:491). However, what Bella _et al_ conclude is that contemporary society is experiencing an individualization process and, therefore, their work focus on understanding this individualization. Accordingly, they put forward four different ideal types of individualization, namely: a biblical, a republican, a utilitarian and a expressive. According to the authors while the first two types are not so common nowadays (or, at least, by mid-1980s, when the book was first published), the last two types are very typical:

[quote]
For contemporary individualism, so Bellah tells us, is either utilitarian, that is, largely concerned with short-term and generally materialistic utility calculations or expressive, in other words, oriented towards satisfaction of emotional needs and the cultivation of oneself. According to Bellah, these two types of modern individualism can be attributed to two social types, which dominate modern American culture, as well as that of other countries: the manager and the therapist (Joas and Knöbl 2009:493).

This framework may be useful for further analysis regarding the crowdfunding communities. However, it is possible to sustain some hypothesis that the scenario might have changed in the last decades. The contempt for politics foreseen by Jaffe and the utilitarian facet put forward by Bellah _et al_ can be challenged by recent researches such as Bennett _at al_ (2013): in contrast to a skeptical behavior toward politics, the authors addressed this issue claiming for a slightly different concept, namely, the _disavow of politics_. In spite of the predictions that this skepticism would repel people from politics, what was found was a _skeptical engagement_ with two different possibilities: “a context of mistrust and cynicism might discourage or pervert political participation, on the one hand, or spur innovation, on the other” (2013:537). Their showed how civic organizations strategically deny the label of ‘politics’ in order to better engage with and to promote change within the local community. Interestingly, this former objective included activities that can be considered very political in nature, such as joining the city council, or lobbying with the local politicians and government.

Yet, this phenomenon of denying certain labels, without necessarily changing the nature of the activity, is also found elsewhere in the literature. For instance, in registering the birth of the area of social movements, Borch (2012:259-60) describes that the scholars involved strategically put aside the jargon that would link them to the negative approach to crowds: "to avoid the association with the register of abnormality, irrationality, crowds and masses, scholars now argued for a more rational conception of social movements where these were seen as entities aiming to achieve specific, commonly shared purposes." 

Three considerations are noteworthy to wrap up the discussion about individualization. First of all, the expressive facet claimed by Bellah _et al_ (2008) is embraced, for the scope of this research, by the post-politics stream discussed above. Second, as Bellah _at al_ (2008) reinforces, a mere claim of individualization is superficial -- it is necessary to go beyond the term itself and to comprehend the social dimensions of the focus on the individual. Third, a explicitly denial of certain labels can be scrutinized; in other words, if antipolitics argues that people are not interested in political, if they argue that there is no more space for the public realm in everyday life, it is possible to raise the question about what is understood as politics and publics nowadays -- even if abnegating a negative semantics of crowds, social movements has something to do with a longstanding sociologically tradition which links crowds to politics (Borch 2012); even if disavowing politics, people still do politics (Bennett _et al_ 2013). In sum, it seems more fruitful to grasp how the crowdfunding community conceives the public realm, than to depart from consensual critiques inherited from political theory. The hypothesis is that new forms of public realm, new forms of acting according to agreed-upon rules and values might be at stage. If this hypothesis is correct -- and the unfold of this research will tell -- these novelties may reinforce or deny the process of individualization, of mitigating of the public realm as well as call for a reconstruction of traditional concepts from political theory.

=== Post-politics

Some authors have been suggesting that the filed of politics have been changing considerably in the last decades. Arguably the idea of a citizen centered in a rational, consensual and deliberative public sphere is not conceivable anymore. According to Mouffe (2005), more traditional approaches on politics are either aggregative (exchanging arguments) or deliberative (instrumental pursuing of interests). Both streams are called into question by the post-political conditions. As Borch (2012:270, emphasis in original) argues, “the masses of today have entered a _post-political_ era, i.e. a situation which traditional understandings of politics are annulled, suspended or transcended.” Yet Borch’s and Mouffe’s standpoint reinforces Wolin’s (2004:584) argument:

[quote]
The idea of a stable, rule-oriented, centered self is rejected in favor of the freedom to invent and reinvent the self. Loyalties are merely contingent ‘solidarities,’ while alliances are things of the moment, dispensable when no longer pleasing. While this conception might seem eminently democratic, it might also reflect a changed understanding of democracy, one less centered on political citizenship and more concerned with cultural expressiveness.

In that sense, firstly, it is possible to justify why the expressiveness claimed by Bellah is left to this sub-section: it is the basis of this branch of post-politics theorization. Secondly, as Wolin (2004:590) defends, “traditional categories of citizen, democracy, state and power desperately need reformulation.” This enterprise of understanding how people gather together and act politically is have an attempt to revitalize theory in the 1970s, when Tilly (1978) launches his book _From Mobilization to Revolution_. In his words, the topic of the book has to do with “people acting together in pursuit of common interests”, suggesting that “collective action results from changing combinations of interests, organization, mobilization, and opportunity” (Tilly 1978:7). However, in spite of Tilly’s reputation in the social movement field, in terms of political theory, his attempt was not so novel. First of all, Borch (2012:259-60) considers that Tilly pivoted a downturn in the history of crowd semantics by the aforementioned disavowal of certain academic traditions: “to avoid the association with the register of abnormality, irrationality, crowds and masses, scholars now argued for a more rational conception of social movements where these were seen as entities aiming to achieve specific, commonly shared purposes.” Moreover – and more relevant for the political scope – despite Tilly’s efforts the mechanism of (organized) social movements does not promoted the reformulation of political concepts. According to him (1978:227): 

[quote]
Mob, disorder, and mass movement are top-down words. They are words of authorities and elites for action of other people -- and, often, for actions which threaten their own interests. The bottom-up approach we have taken identifies the connection between the collective actions of ordinary people and the ways they organize around their workaday interests.

This attempt to reconnect ordinary people within the political institution might be valid. however it might end up as mechanism that still dependent of the traditional government and democratic representation. According to Wolin (2004:586) there are two opposing tendencies in politics nowadays, a centrifugal and a centripetal one: “the first fears democracy because it homogenizes suppressing significant differences in favor of a monolithic ideal of ‘the people’. The second is contemptuous of democracy for its weakness yet envious of its appeal.” The major representatives of this centripetalism, according to Wolin, are e large business  corporations. But the crucial point here is what he says about the centrifugalism: “whatever remains of democratic possibilities lies with the centrifugal forces” (Wolin 2004:586). The description offered of this tendency seems to have a fit with social movement, but Wolin (2004:587) highlights that this kind of political approach is problematic: “for despite their critical attitudes towards the state -- perhaps all -- of the major centrifugal groups look to government for assistance and protection and to its courts for relief.”

[quote]
It assumed that democracy was a form of government in which the people governed. That assumption was mistaken: in part because it presented the ‘people’ as a pre-existent, continuous entity … and in part because it assumed that the authority and power to govern was what people would aspire to (Wolin 2004:602).

In sum, the point is that ordinary people, even organized around common interests in a rational way (supposedly  proper to deal with democratic institutions), would still depend on a political elite created within the representative democracy -- embracing all the problematic affairs of representations, elite recruitment, and the impoverishment of the public realm. Hence, a post-political have to avoid mechanism such as social movements because despite its focus on a bottom-up approach, it requires a top-down state to justify its means. The persistent problem is, then, how would be possible to act politically, according to a post-political standpoint. The political theory literature offer some insights on that, but apparently there is little empirical data (at least in a systematic way) regarding these insights.For clarification, this is not the case of the hypothesis of individualization, on which some empirical studies have been confronting the theory, as mentioned. Therefore this research can take these post-political insights as starting point to approach the fieldwork and, through the analysis of this empirical case, develop and/or refine this theoretical constructions.

Finally, these post-political insights usually departs from the aforementioned expressiveness (Bellah 2008), from more individual and subjective instances -- such as emotions and identification (Mouffe 2005) -- when compared to the traditional approach to citizenship. Also, from the antipolitics literature (Schedler 1997, Jaffe 1997), these insights can incorporate that one of the requirements of politics is plurality. To sum up, the challenge is to understand if (and, if so, how) crowdfunding communities conciliates plurality and individuality in terms of politics, i.e. in terms of equality and authority, and in terms of the public realm (Arendt 1973). Moreover, the underlying task is to understand how this endeavor relates to traditional political institutions, such as the representative democratic government.

== Technology, plurality and the public realm

Plurality, as the criticism towards traditional citizenship logic is also recurrent in political theory. For instance, when Tarde (2006) argued, in the nineteenth-century, that existence of several publics (instead of single crowd acting in unison) was important for a stable society. Later, Borch (2012) describes, the existence of plurality was relevant within the democracy advocates of mid-twentieth-century, such as Park and Kornhouser. More recently, authors aligned with postmodern approaches have reinforced the inescapability of a theoretical consideration of plurality (Bauman 1993, Maffesoli 1996). However, even without step into the postmodern critiques (towards modernity), it is possible to discuss the limits, challenges and consequences of this plurality. Instead of postmodern epistemological approach to pluralism, the idea is to opt for a framework where the subjectivities claimed by post-political advocates is, in fact, part of politics. In other words, this proposal assumes that post-political claims calls for a notion of post-representativeness, a new way of participating in politics.

This reconceptualization of politics has its origins in the disavowal not only of political elites, but on groups organized around it:

[quote]
Representative government, according to its advocates, favors the proliferation of interests precisely because it increases the difficulties of forming a majority, thus, in effect, fragmenting the ‘sovereign people.’ At the same time, by attenuating the connections between government and an unorganized citizenry, the processes of legislation and policy-making become vulnerable to organized interests. These, by definition, are accountable not to citizens but to their employers. Paradoxically, the more open to the pressures of organized interests, the more opaque, even mysterious, politics becomes as responsibility becomes virtually untraceable. The political problem arises when that form of corruption is normalized (Wolin 2004:600).

This reconceptualization also has its origins in the disavowal of the individualization read with a selfish tone -- the one called into question in the sub-section above. Recapitulating Bellah’s work, it is important to value how, in spite of the power of individualization, people also felt unsatisfied with this phenomena:

[quote]
According to Bellah, the remarkable thing about these undoubtedly radical individualism is that, for the most part, people acting in this individualistic way simply lack the capacity to grasp how it might be possible to link their interest with those of others. They frequently _suffer form a lack of social ties and relationship_. Furthermore, they are unable even to define what they understand a ‘good life’ to be. The interviewees articulated (consciously or unconsciously) a sense of _unease about their own unconnected lives_” (Joas and Knöbl 2009:493, emphasis added).

This raise three issues that can link this specific type of individualization with, on the one hand, the possibility of a plurality of opinions and, on the other hand, the possibility of a public sphere. The linking bridge is, for the scope of this research’s hypothesis, the advances in terms of technology, specifically the case study on crowdfunding. Individuals, according to Bellah’s account, seem completely lost: they are uncomfortable with the fact that they have been unable to establish social ties. Technology offered both: a way for this individuals express themselves and, from this expression, the opportunity for gathering around common interests. However, instead of a gathering in the traditional political term (parties, social movements), this gatherings are much more guided by the disruptions technology have been imposing upon the market, the economy. This is the specificity, in political terms, of the hypothesis of looking to crowdfunding in order to grasp what a post-representativeness could be, what a pragmatic approach to post-political could look like.

This argument does not imply that the internet, “with an infrastructure that promises unlimited and unregulated discourse that operate beyond boundaries,” automatically makes room for a “reincarnation of the public sphere” (Papacharissi 2009:231). However, this argument poses the question about what kind of space is enabled from the openness aspect of the internet. In that sense, comprehending the specificities of that space is a requirement to argue about the possibility of a reinvigorated public realm. The expressiveness related to the individualization claimed by Bellah – which is similar to the concept narcissism employed by Papacharissi (2009)– is what characterizes blogs and similar personal self-expressions over the internet. And the Papacharissi (2009) reinforces how the incumbent media is appropriating this extremely personal sources as a valuable voice within the public space, e.g. when a national wide TV news mention _the  blogs_ as an opinion or even a source, or when these companies adopt blogging themselves. Interestingly, “narcissistic behavior are structured around the self, but not motivated by selfish desire. Ironically, narcissistic behavior is motivated by the desire to connect the self to society” (Papacharissi 2009:238).

By these means, it is possible to conciliate two apparent paradox of this review: the individualization based on expressiveness is intimately linked to the social (and is not antagonizing it); moreover, this individualization based on expressiveness can be understood not as antipolitical, but as political, not as inherent to a private sphere, but also related to public sphere. Arguably, this individualization based on expressiveness can, therefore, have a democratizing effect (Papacharissi 2009). The revision of traditional political concepts, therefore, reches yet another level: “priorities here lie in broadening and overlapping private and public agendas; not retrieving the public sphere” (Papacharissi 2009:239).

It worth it no reinforce that technology is not a new player in the challenge of political and social theory. In the nineteenth-century, in Tarde’s oeuvre (2006), the invention of the newspaper were crucial to theorize on masses and crowds: according to him the press extended the potential of imitation and suggestion beyond physical proximity between individuals. In the twentieth-century, technology was again on the spotlights of social and political theory:

[quote]
The entire media landscape looked radically different when the Frankfurt scholars conducted their investigations than it did when the classical crowd theories of, say, Le Bon and Tarde appeared. While Tarde acknowledged the importance of newspapers, it was still possible at Tarde’s time, i.e. at the end of the nineteenth century, to maintain a separation between physically co-present individuals and crowds, on the one hand, and the mass-mediated public, on the other. This became increasingly difficult due to a series of developments that vastly enhanced the societal significance of the mass media in the first half of the twentieth century … but while the mass media were already playing a decisive role at that time, it was barely comparable to the magnitude it would assume in the years to come. To give but a few indications of the changing situation, daily newspaper circulation almost doubled in the USA in the time-span from 1910 to 1930. In the same period, film assumed a most prominent function as a mass entertainment medium. Radio broadcasting experienced a veritable breakthrough especially in the 1930s and 1940s, and while advertising was already firmly established as a mass medium at this point, the radio gradually came to play a key role in advertising from the late 1920s. Not to forget television. which boomed in the 1950s and 1960s (Borch 2012:222).

And surely nowadays technology still relevant for theory. For instance, Wolin ( 2004:588) argues that “the new economies created by technologically advanced societies provide equivalents for democracy’s values of participation (mass consumption), inclusion (work force), and mass empowerment (‘consumer sovereignty’, ‘shareholder democracy’).” To mention others examples, Ritzer and Jurgenson’s (2010) argue that the technology disrupted the classical Marxist approach of society, based on producers and consumers, enabling capitalism to reinvent itself; and, in the political realm, Margetts _et al_ (2013) describes how the idea and resources of leadership is completely different from the traditional political assumptions when it comes to online activism. Moreover considering that the usage of this technology is based on an expressive individualism, Wolin (2004:584) adds that “loyalties are merely contingent ‘solidarities,’ while alliances are things of the moment, dispensable when no longer pleasing.” This is the scenario where crowdfunding takes place: it creates space for participation, generating inclusion and empowerment for those who get involved (as Wolin suggested); all happen in public and relying on the reach of social media to be successful  -- involving new means of production, consumption and leadership that happens, necessarily in public (or in somewhere between the private and the public sphere). Finally, the contingency of opinions, ideas, of the solidarities put by Wolin, of leadership, consumption and production seems to be a mix that could end up empowering plurality -- instead of gathering all efforts and resources for one big cause, what is happens is a plurality of small actions.

[quote]
Perhaps, them, democracy should be about forms rather than _a_ form or constitution; and, instead of an institutionalized process, it should be about conceived as a moment of experience, a crystalized response to deeply felt grievances or needs on the part of those whose main preoccupation – demanding of time and energy – is to scratch out a decent existence. Its moment is not just a measure of fleeting time but an action that protests actualities and reveals possibilities.

[quote]
Accordingly, small scale is the only scale commensurate with the kind and amount of power that democracy is capable of mobilizing, given the political limitations imposed by prevailing modes of economic organization. The power of a democratic politics lies in the multiplicity of modest sites dispersed among local governments and institutions under local control (schools, community health services, police and fire protection, recreation, cultural institutions, property taxes) and in the ingenuity of ordinary people in inventing temporary forms to meet their needs. Multiplicity is anti-totality politics: small politics, small projects, small business, much improvisation, and hence anathema to centralization, whether the centralized state or the huge corporation (Wolin 2004:603).

[quote]
What the economic polity renders scarce for its citizens is the direct experience of politics itself and the responsibilities of power. And that is the ‘renewable resource’ unique to the political ecology of localism: unlike the corporation and its accomplice … localism can generate and continuously renew direct political experience (Wolin 2004:604).

If the informal liaison between corporations and government seized the public sphere from ordinary people through an expansion of the private sphere, through liberal markets, what is happening next is ironic: citizens might be fighting back recreating the public sphere within this _supposed to be _ private sphere, i.e. taking the liberalism present in the market to engage in environment that resemble a traditional public sphere in many ways. And this is not new when relating digital culture to politics: Coleman’s (2013)  ethnography on the ethics of free and open-source software groups consider how the hacker culture represent a liberal critique within liberalism itself. Moreover, this technological empowered space does not infer a public sphere, but at the same time, this fact does not deny a democratizing effect: “this lack of coordination or concentrated civic objective limits the contribution to the public sphere, and exemplifies how online technologies enhance democracy in ways tangential to, but not directly connected with, the public sphere” (Papacharissi 2009:238-9).

Finally, it is important to understand that this new environment has its own logics. It is naïve to suppose that openness results, automaticaly in equality and lack of authority. In Arendt’s (1973:279-80) words, the focus is to understand how, in-between equality and authority, exclusion operates:

[quote]
“To be sure, such an ‘aristocratic‘ form of government would spell the end of general suffrage as we understand it today; for only those who as voluntary members of an ‘elementary republic’ have demonstrated that they care for more than their private happiness and are concerned about the state of the world would have the right to be heard in the conduct of the business of the republic. However, this exclusion from politics should not be derogatory, since a political élite is // by no means identical with a social or cultural or professional élite. The exclusion, moreover, would not depend upon an outside body; if those who belong are self-chosen, those who do not belong are self-excluded. And such self-exclusion, far from being arbitrary discrimination, would in fact give substance and reality to one of the most important negative liberties we have enjoyed since the end of the ancient world, namely, freedom from politics (Arendt 1973:279-80).

== References

Arendt, H. (1973). _On Revolution_. Bungay: Penguin. 

Bellah, R., Madsen, R., Sulliva, W., Swidler, A. and Tipton, S. (2008). _Habits of the heart_. Berkeley: University of California Press.

Bauman, Z. (1993). _Postmodern Ethics_. Oxford: Blackwell.

Bennett, E. A., Cordner, A., Klein, P. T. and Baiocchi, G. (2013). Disavowing Politics: Civic Engagement in an Era of Political Skepticism. _American Journal of Sociology_, 119(2). Pp. 518-548.

Borch, C. (2012). _The Politics of Crowds: An Alternative History of Sociology_. Cambridge: Cambridge University Press.

Coleman, E. (2013). _Coding freedom_. Princeton: Princeton University Press.

Jaffe, E. (1997). Our Own Invisible Hand: Antipolitics as an American Given. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 57-90.

Joas, H. and Knöbl W. (2009). _Social Theory: Twenty Introductory Lectures_. Cambridge: Cambridge University Press.

Maffesoli, M. (1996). _The Time of the Tribes: The Decline of Individualism in Mass Society_. London: Sage.

Margetts, H., John, P., Hale, S. and Reissfelder, S. (2013). Leadership without Leaders? Starters and Followers in Online Collective Action. _Political Studies_.

Mouffe, C. (2005). On the Political. London: Routledge,

Papacharissi, Z. (2009). The Virtual Sphere 2.0: The internet, the public sphere, and beyond. In A. Chadwick & P. N. Howard (eds.). _Routledge Handbook of Internet Politics_. London and New York: Routledge. Pp. 230-245.

Ritzer, G. and Jurgenson, N. (2010). Production, Consumption, Prosumption: The nature of capitalism in the age of the digital ‘prosumer’. _Journal of consumer culture_, 10(1). Pp.13-36.

Schedler, A. (1997). Introduction: Antipolitics -- Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 1-20.

Sniderman, P. M. and Bullock, J. (2004). A Consistency Theory of Public Opinion and Political Choice: The hypothesis of men dependence. In Saris, W. E. and Sniderman, P. M. (eds.). _Studies in Public Opinion: Attitudes, nonattitudes, measurement error, and change_. Princeton and Oxford: Princeton University Press. Pp. 337-357.

Tarde, G. (2006). _L'opinion et la foule_. Paris: Sandre.

Tilly, C. (1978). _From Mobilization to Revolution_. Reading: Addison-Wesley.

Tocqueville, A. (1986). _De la démocratie en Amérique, I_. Paris: Gallimard.

Wolin, S. (2004). _Politics and Vision: Continuity and Innovation in Western Political Thought_. Princeton and Oxford: Princeton University Press.
