= Post-politics and crowdfunding | Draft series v5.0 footnote:[This a draft version of a research design and literature review to be discussed in a board meeting by June, 2014.]
Eduardo Cuducos
:homepage: http://about.me/cuducos
:numbered:
:toc:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_1^st^ year PhD student in sociology, University of Essex_

== Introduction

In contrast to studies on post-political societies pointing to a skeptical behavior toward politics, a recent paper from the American Journal of Sociology addressed this common issue claiming for a slightly different concept, namely, the ‘disavow of politics’, as Bennett _et al_. (2013) stated. According to them, in spite of the predictions that this skepticism would repel people from politics, what was found was a ‘skeptical engagement’ with two different possibilities: “a context of mistrust and cynicism might discourage or pervert political participation, on the one hand, or spur innovation, on the other” (2013:537). Their ethnographic fieldwork showed how civic organizations in Providence (RI, USA) strategically deny the label of ‘politics’ in order to better engage with and to promote change within the local community. Interestingly, this former objective included activities that can be considered very political in nature, such as joining the city council, or lobbying with the local politicians and government.

This scenario has a good fit with the idea of post-politics. As Borch describes, “the current turn-of-the-century society had entered a post-political state” in which “’old politics’ (arguments, debate, demonstrations) lost in significance” and “masses seemed to bypass the political as such” (2012:296-7). Although this post-political assessment (with its dismissive look to traditional politics) is part of Borch’s balance of more contemporary theories (such as Baudrillard, Sloterdijk and Maffesoli), he recalls Mouffe (2005) to argue that crowd theories might lead to a reinterpretation of politics in this scenario. According to Borch (2012:302) the key would be to avoid rational instrumentalism (“incapable of grasping that politics is not just about the pursuit of interests”) as well as a strict focus on consensus (in order to “understand that politics is also about mobilization through conflict”). By these means he proposes, according to Mouffe, that it is possible to make room for passions and identification within political crowds.

With no direct relation to civic organizations, crowd theories or politics, online communities in general have been engaging people over the internet for different purposes. The internet is the cradle of a series of spontaneous institutions where user gatherings and collaborative engagement are at the core of their services. This is the case for sites such as Kickstarter, Airbnb, CouchSurfing and Threadless, among others, including Wikipedia and the contentious WikiLeaks and The Pirate Bay. Just like the civic organizations surveyed by Bennett _et al_. (2013), most of these institutions do not advertise themselves as political (or, at least, they minimize the political facet of their activities). While the civic organizations’ ultimate goal is to enhance and support their local communities, the focus of these crowdsourcing platforms may vary considerably. Even though I shall argue that the disavowal of politics is not the only characteristic shared by civic organizations and crowdsourcing: ultimately, both end up as relevant political actors.

On the one hand, this conclusion is clear in the work of Bennett _et al_. (2013) when it comes to civic organizations. On the other hand, several studies into the internet have reinforced how collaboration over the web has significant political impact. For example (but not limited to): Lessig’s (2004 and 2006) argument about how internet software and hardware impact the legal and cultural system (including copyright and distribution issues); Benkler’s (2010) examination on the ‘access to knowledge movement’ and the information politics; Coleman’s (2013) ethnography on the ethics of free and open-source software groups, a study which characterizes hacker culture as a liberal critique within liberalism; Allen-Robertson’s (2013) analysis of how piracy was appropriated by the market, revolutionizing the digital culture industry and the politics of licensing media; or Papacharissi’s (2009) discussion on how the participative and collaborative online environments created by and for internet users forge a new approach to a public sphere within society.

In sum, the hypothesis is that internet communities and platforms can be considered as (veiled or unveiled) sources of politics, and that any possible disavowal of politics within these communities cannot be taken as an assertion that they cannot be analyzed in terms of political effects.

Yet, Bennett _et al_. (2013:535) discuss the reasons why people in civic organizations purportedly disavow politics. Among these reasons, there is “the perception that politics promotes self-interest or special interests” in opposition to the ordinary belief “that politics should be about the promotion of universal, public goods.” According to this logic, a (disavowed) political agent would be “someone who uses the state to pursue selfish interests”, including “illicit behavior, such as bribery, as well as legal profiteering and self-interested political activity, such as benefiting from one’s access to influential decision makers” (2013:535). The authors added that when it comes to advocates of social justice (especially), these “special interests” can be read as “elite interests” (2013:540).

This contempt of elites (mainly political and business elites) is also found in a possible ‘even newer spirit of capitalism.’ Taylor and Land (2014), following the theoretical stream of Boltanski and Chiapello (2005), argued that the 1990s movements which fought for the environment and for social justice, sustaining yet an anti-globalization critique, affected corporations and institutions of global governance (e.g. World Bank, WTO, IMF etc.) with the emergence of a specific entrepreneurial discourse. These movements took part in the promotion of a new spirit of capitalism – just as the 1960s youth promoted the autonomy and creativity within the workplace during the following decades, as described by Boltanski and Chiapello (2005). The even newer spirit described by Taylor and Land disavow corporations and worldwide governance institutions in a way that is subtle if compared to social movements in general (e.g. Occupy, anti-G8 protests, black bloc inspired demonstrations etc.). This new spirit seems to have prompted an aesthetic formulation capable of triggering changes in the scope of policy and management, acting through moderate means, avoiding conflict and barricade-like behavior. It is noteworthy that the civic organisations surveyed by Bennett _et al_. (2013) also had this moderate characteristic: they reject conflict in general (including political conflict, provocative arguing etc.).

That said, it is possible to trace another parallel involving the aforementioned internet communities. Groups such as The Pirate Bay, Anonymous and WikiLeaks figure as the more radical confronters in terms of politics. Accordingly, crowdsourcing institutions such as Kickstarter, Airbnb and CouchSurfing (among others) avoid social conflict – just as the civic organizations described by Bennett _et al_. (2013). These platforms bring together people with common interests, in order to enable them to provide the means through which people’s own projects can be funded.

There is a specific way of online collaboration, which is referred to as crowdfunding. These platforms allow artists, entrepreneurs and project designers in general to do an online open call to action in order to raise funds to run a specific enterprise. The platform is independent from the people who submit the project, and it is also independent from the execution of this project – i.e. it merely hosts this call to action and manage the fundraising operation (English 2013). These platforms are considered a new model in venture capital, allowing any user interested in the success of the proposed project to contribute (English 2013, Belleflamme _et al_ 2013) . According to English (2013)

[quote]
the majority of reasons people offer support to crowdfunded projects were categorised as altruistic (wanting to help a friend), as community building (wanting to be part of a creative project and help creative people as well as what was termed the social kudos of being part of a cool project) or as wanting to access the rewards that are given with donations.

Belleflamme _et al_ (2013:1) highlight that “crowdfunding has become a valuable alternative source of funding for entrepreneurs seeking external financing” and there is “an impressive growing volume of money collected through crowdfunding worldwide”. Kickstarter is one of the platforms operating under this model. Among an enormous variety of projects, Kickstarter hosts projects consisting of musicians trying to raise funds to record their own albums. In these cases, this new venture capital model enables these artists to achieve their goals without depending on record labels to produce and launch their work. Instead they can post a description, a funding goal and a deadline and, if the project can gather enough fans to fund the stipulated target, the album is produced. There are a lot of projects such as this. One of them, for example, is the Daytrip EP, by Anna Burden (vocals) and Sam DeArmond (guitar and vocals).footnote:[See the Daytrip EP project at Kickstarter – http://kck.st/Lx1Lkq.] They asked for US$ 4,000 in order to record their EP. Thereafter, 121 enthusiasts made donations varying from US$ 10 to US$ 500 and consequently they were able to finance their project. Besides being part of this collective effort to make the EP possible, backers had different rewards according to the amount they donated. Rewards varied from access to an exclusive acoustic song, to choosing a song to be recorded and included in the EP.

Other recurring examples of projects in Kickstarter are those involving creators of new products, but who had no means to produce it. In other words, these creators would usually depend on public or private funding to actually produce their idea (or even licensing or selling the creation to a company in order to make it possible, in order to properly launch it). Two great examples in this area are Pebble (a smartwatch whose target was US$ 100k and ended up getting more than US$ 10M in funding) and the Mini Robotic Printer (pledged more than half a million, when the target was US$ 400k).footnote:[Pebble was funded on May 2012 and the Mini Robotic Printer, on May 2014 – their URL are, respectively, http://kck.st/HumIV5 and http://kck.st/1qvfZQX.]

In sum, Kickstarter does not create anything, it just allows people to expose their ideas, and offers the means to users support these ideas. Users’ inputs are ideas and support, and the outcome is making some projects tangible, without depending on other instances – i.e. it works as venture capture raising, or even as a pre-sale platform. Hence, if the contempt for elites was brought to light when it comes to civic organizations (Bennett _et al_. 2013) or to Taylor and Land’s (2014) even newer spirit of capitalism, the crowdfunding mechanism possibly corroborates this contempt by dismissing the ‘elite’ from the role of funding ordinary people, putting this task in the hands of the crowd.

Finally, it is possible to add in to this scenario the differentiation between political and anti-political, employed by Barry (2002), to discuss the entanglement of technology, economy and politics. According to him, politics is ultimately a space for disagreement, which creates a paradoxical situation: “for governments to be possible, it is necessary to reach common decisions, however arbitrary, negotiated and provisional such decisions are;” however, he argues that “the fact that such common decisions have to be arrived at in the face of persisting disagreement and in the absence of ‘rational’ justification is one of the persisting circumstances of politics” (2002:270). Considering this critique, together with Mouffe’s focus on the importance of passion and identification for 21st century reinterpretation of politics, it is possible to propose a new layer of political analysis to the emergence of crowdfunding mechanisms: namely that it employs individuals’ passions and interests to displace the governmental (and, I shall add, corporative) need for consensual or rational-instrumentalist institutional decision-making.

Despite the disavowal of politics, crowdfunding might be political by being an alternative to people outside the incumbent elites and outside incumbent institutional logic, and yet an alternative which brings back passions and identification to the scope of politics. Hence, given these parallels between civic organizations, crowd theories and crowdfunding mechanisms, the objective of this research is to investigate the nature of politics nurtured by supposed non-political crowdfunding platforms. In that sense, the project is guided by this set of research questions:

1. _What is the focus of crowdfunding initiatives?_ +
Is it about (a) making things happen (whatever they are, since they are proposed and backed by ordinary people), about (b) business (since most of them emerged as startups), or, yet, about (c) politics (confronting incumbent institutions)? Are there other perspectives not foreseen by this research design at this point? Most important, how do they balance these perspectives?
2. _What are the specificities of crowdfunding politics?_ +
Is there any dimension of politics within crowdfunding? Do people involved deliberately try to set the boundaries between them and politics, as in Bennett _et al_. (2013)? Does the fact that crowdfunding focus in a more practical accomplishment (e.g. gathering fans and supporters to provide a musicians the means for recording an album), and not in the social aspect itself, cause any interference in terms of politics? By offering ordinary people alternatives to the funding dependency on incumbent institutions, are they consciously confronting these incumbent institutions?
3. _How does crowdfunding relate to politics and economics?_ +
Is there a movement towards decentralization through crowdsourcing, or are they aspiring to be new nodes, centralizing the market? What political and economic impacts can be inferred from their mechanisms and from their projects? Is it in consonance with contemporary theories that minimize crowds and politics? Is there a meaningful political and economic power in the profusion of crowdfunding communities?

== Theoretical Overview

The discussion and assumptions exposed in the pages above constantly intertwine with (at least) three areas of social sciences: politics, economics and sociology. This proposal involves a sociological account of the political and economic arrangements emerged from the latest usage of online devices and services. On the one hand, the political stream is built around the idea that the internet – and the highly connected network of individuals it creates – prompted the discussion about whether this platform empowered new forms of political participation. On the other hand, the economic stream departs from the boost in the collaborative production with projects such as Linux, Wikipedia, Firefox, and other well acknowledged open source and crowdsourced projects. This stream calls into question the more traditional capitalist and economic premises based on premises such as proprietary software. Furthermore, in terms of social theory, both streams involve a debate about whether new paradigms are actually created within these internet communities, and whether they can actually challenge incumbent political and economic institutions. The following theoretical review introduces these topics and suggests that these possible social innovations rest mainly in the promising decentralization of power and capital, creating alternatives to traditional institutions – while, at the same time, avoiding to ‘open fire,’ or directly confront them.

The first section addresses the literature regarding political approaches to the internet and to crowds in general; the objective is to properly substantiate further analysis of crowdfunding communities in terms of contemporary politics. The second section sets a sociological background to the melange of politics and economics present in several online platforms and communities; the idea is to discuss whether movements such as access to knowledge and information freedom, or yet, open and decentralized software and content production, can effectively wreak wider institutional changes. Finally, the third section sums up the political and economic streams in a framework involving the ways through which current institutions respond to this scenario. Therefore, this theoretical review argues that either the cultural institutions are partially reinvented to accommodate the same incumbent political and economic premises, or the highly connected individuals can forge new assets and organizational arrangements that would impact these incumbent premises.

=== Internet and political participation

The outbreak of the internet, and specially the advent of the so-called web 2.0,footnote:[Briefly, the user-generated web, e.g. Facebook, YouTube, Twitter (Ritzer and Jurgenson 2010).] prompted certain expectations within the political sphere. They argue that it would finally be possible to engage crowds in (online) political participation. However, as similar expectations in cases such as the penny press, radio, and television have been frustrating, the question is whether the internet would in fact allow users to “participate directly in politics rationally and responsibly”, as suggested by Margolis and Moreno-Riaño (2009:131). These authors looked for collaborative participation in candidates, parties and interest groups’ websites, finding a negative aspect to the aforementioned perspective. For them:

[quote]
Innovative political uses of the Net that challenge the established political order have made an impact, but their impact pales in comparison to the marketing goods and services (including social networks) online. In short, politics that affect the Net generally reinforce the influence of dominant social, political and economic interests … Far from empowering political parties and interest groups the established mass media and political institutions have generally ignored, increased access to and usage of the Internet has generally been accompanied by a shift of economic resources and power from the poorest classes to the richest both within and between nations (2009:132).footnote:[The authors summarize ideas from well acknowledged texts related to the cyberspace, documents expressing the overall expectations of political emancipation of those building the formative years of the web – e.g. A Declaration of the Independence of Cyberspace (Barlow 1996).]

The authors argue that there is a lack of action among internet users, and that these users are skeptical about being able to organize themselves in groups to successfully act in favor of political change. Yet the authors call attention to a centralized and top-down communication and power structure (such as in the Obama online campaign on his first presidential election), adding the lack of statistical evidence to support a social and economic restructuration from the outbreak of the internet. They conclude that the increasing usage of the internet has not enhanced democratic values. As they consider:

[quote]
Indeed, the increasing dependence of political parties upon large donations to support media driven elections campaigns, the consolidation of economic power into large globally based corporations, the continuing desire of most citizens to use the Internet for commercial rather than civic purposes, and their willingness to consume rather than create information all portend reinforcement of current socio-economic and political power structures (2009:148).

Unfortunately this approach – even if correct from its own standpoints – ignores particular dynamics of internet participation, of online initiatives, and of a post-political scenario. For instance, Margolis and Moreno-Riaño (2009) argue that fact that the list of the most used websites within the OECD nations – familiar services such as “Google, Yahoo!, YouTube, eBay, MySpace, Facebook, Flickr, Friendster, Wikipedia, Msn.com, blogger.com and YouPorn.com” (2009:155) – is composed of mainly of media sites rather than governmental ones. This sort of argument is bounded by an analysis of media sites departing from a one-to-many communication scheme, ignoring that the majority of websites listed (at least 8 out of the 12 listed above) operate in a many-to-many scheme. Theoretically, it is worth recalling the classic McLuhan’s (1994:7) phrase, “the medium is the message”, i.e. the architecture of these platforms act on their own by offering the chance of participation. In other words, YouTube, eBay, MySpace, Facebook, Flickr, Friendster, Wikipedia and blogger.com produce no content at all, they act as platforms where users can produce and consume their own contents (in contrast to, for example, printed press, where an editorial board is in charge of the content, while readers act as passive content consumers of that content). For Margolis and Moreno-Riaño (2009), apparently, there is no possibility of politics and democracy outside government, parties and internet groups.

In sum, Margolis and Moreno-Riaño (2009) expected the internet to be a kind of lubricant for a traditional public sphere, in a rational and instrumental pursue of consensus and deliberation. One of the features of this specific conception of public sphere is the “menu dependency”, concept forged by Sniderman & Bullock (2004). This idea departs from the assumption that ordinary people “pay too little attention to politics, know too little about it and invest too little in organizing their own ideas” (2004:338) and, therefore, politics is enacted representatively and its core is a menu of ideas and proposals organized by elites. Given this scenario, the internet would be useful only if it could reduce this menu dependence through a certain way, namely, making citizens pay more attention to politics, making them know more about it, and making them invest more in organizing their own proposals – shifting the model from an essentially representative approach to a more direct political engagement with the state. In that sense, Margolis and Moreno-Riaño (2009) seem precise to point out the inefficacy of the internet.

However, this is not the only possible measure to consider internet and politics. For instance:

[quote]
The inherent assumption was that digital media would inject our representative model of democracy with a healthy dose of direct democracy. Recent research on how citizens make use of online media worldwide, however, indicates that while political use of new media is vast, it does not fit the mold of the Habermasian public sphere and promotes direct democracy selectively. Specifically, while citizens are increasingly drawn to digital media, they are attracted mostly to interest group and non-partisan websites (Papacharissi 2009:239).

While Margolis and Moreno-Riaño (2009) looked for political effects of the internet in traditional structures of political action, alternative approaches are in tune with non-traditional politics, namely, a post-political momentum. In fact, even outside the ‘virtuality’ of the internet, the studies on crowds in the last decades share in common “the idea that the masses of today have entered a post-political era, i.e. a situation which traditional understandings of politics are annulled, suspended or transcended” (Borch 2012:270). Some contemporary liberal approaches on politics are either aggregative (exchanging arguments) or deliberative (instrumental pursuing of interests), which fails to capture the social changes post-politics theories have been possible measuredescribing – namely that conflict and plurality is inherent to politics and that crowd theory could offer a more accurate assessment of politics. To be sure, crowd theory could accommodate not only the rational facet which inspired such liberal approaches, but also the more spontaneous (and one may say irrational) facet of human behavior within crowds (Mouffe 2005, Borch 2012).

Hence, in a deregulated space like the internet, ordinary people are not restricted to – and should not be assessed by – the engagement with society through the virtues of traditional politics and through the engagement with the state. For instance, Papacharissi (2009) describes how a narcissistic behavior was built during the last decades, setting the tone for a branch of online participation mediated by self-expression. Following her argument, this phenomena ultimately values virtues such as the control of the environment, autonomy and the ability to question authority – they are organized around the self, but not necessarily in a selfish way; in fact, they are attempts to connect the self to society. For example, blogging sets a distinctive space, which is neither journalism nor public sphere, it is privately produced content published in online boards, blurring the private-public boundaries.

Inside his discussion of post-political crowds (but not necessarily focused on the internet) Borch’s (2012) analyzes the oeuvre of sociologists and philosophers such as Baudrillard, Sloterdijk and Maffesoli. In sum, Baudrillard’s standpoint dismissed any possibility of politics through the crowd. For Baudrillard (1994), society has shifted from an era of production and reproduction to an era of consumption, a phase in which the circulation of signs and codes takes place without any real foundation. The crowds, therefore, are merely simulations, with no active voice – a silent mass, he would state. This argument does not seem to be relevant to our scope, since researchers such as Bennett _et al_. (2013) defend that there is still politics to be found in collective behavior, even if unclaimed.

However, Sloterdijk and Maffesoli drew different conclusions (Borch 2012). Sloterdijk used a framework of vertical and horizontal differences to argue that politics was expelled from crowds due to ‘non-political entertainment’. The idea is that masses accept only horizontal differences, a type of difference that does not end up in a better or worse vertical scale of differences. For him, this approach is what characterizes contemporary society; as Borch (2012:282) summarizes:

[quote]
Masses have a profound contempt for difference. They disapprove of everything that stick out and which claims to be better than something else. Accordingly, the identity of the masses consists in their radical egalitarianism, which in Sloterdijk’s view was another way of saying their profound ‘indifference’ to any vertical difference. Instead of vertical difference, the masses endorse and embody horizontal difference, i.e. the idea that no one is better than anyone else, that all should have equal rights and possibilities, irrespective of what they have accomplished.

The scenario would end up, for Sloterdijk, in a irreparable cultural decline: as a result of the practical elimination of better and worse. Sooner or later no parameter would be found within the cultural sphere. He argued that the only hope to avoid this down slope was to look after the only areas in postmodern society where it is still possible to find vertical difference: financial markets, sports and arts (see Borch 2012).

Finally, Maffesoli’s concept of neo-tribes adds another layer to this indifference. Corroborating an apparent distance between collective behavior and politics, in Maffesoli’s analysis “the neo-tribes had no interest whatsoever in engaging in deliberate versions of liberal democracy, nor were they politically instrumental in the sense of promoting essentially economic interests” (Borch 2012:287). However, his analysis does not deny this more rational approach by offering as a counterpoint an irrational one; rather, neo-tribes are based on non-rational aesthetics. As he puts (1996:144), “this term must be emphasized: non-rational is not the irrational; it is not even defined in terms of the rational; it establishes a logic other than the one that has prevailed since the Enlightenment.” Interestingly, this aesthetical reasoning is so inherent to each neo-tribe that it practically eliminates Sloterdijk’s hope that other areas could learn from financial markets, sports and arts – for Maffesoli, neo-tribes have little influence over one another.

Still, all these theories seem to deny a place for politics within contemporary collective behavior.footnote:[It is worth mentioning that Borch’s (2012) chapter on post-political crowds debates, yet, Hardt and Negri oeuvre: The Empire and Multitude. This debate is not included here since, according to Borch, Hardt and Negri oeuvre is problematic in several ways: first, it is characterized more as a mobilizing agenda than a theoretical work (Borch 2012:288); and second, their conception of crowds ignores important theoretical contributions from the nineteenth century (namely, Geiger), ending up with a impartial (if functional for the mobilizing agenda) image of crowds (Borch 2012:291). This later critique foster a second layer of issues, such as the unidirectional focus of their concept of multitude against neo-liberal and neo-conservative institutions (again, functional to their mobilizing agenda, Borch 2012:293) or an incomplete reading of Spinoza (their source to draw the concept of multitude), an incomplete reading which purportedly select only the positive side of crowds, ignoring the negative (but, in fact, present) one (Žižek 2004:34-5).] They point to a decentralization of crowds, but offer little basis for a political understanding of contemporary collectivities. Margetts _et al_ (2013), however, have been working with the concept of a large-scale mobilization of micro-donations (mainly of time to read a post, like it, share it, retweet, comment about it etc.). Their analysis of adhesion to and success of online petitions has shown “a general shift of agency from leaders and elites to members or individuals” (Margetts _et al_ 2013:3), a scenario on which the role of the political leader is losing its relevance. Replacing this political leader figure there is a new paradigm of leadership being forged by the aggregate of a massive number of online users gathered within the network and, specially, expanded through its weak ties: now “leadership is the aggregate of many low-cost actions undertaken by those willing to start, rather than the raft of actions and characteristics of the few with it is normally associated” and, “by providing the social information, internet based platforms circumvent the need for other activities traditionally performed by leaders” (Margetts _et al_ 2013:18).

This diagnosis contrasts the menu dependency and centralized forms of democracy without overthrowing it completely. There is still a degree of leadership needed to propose an online petition, for example, but the cost of this operation has fallen considerably. Similarly, engagement through micro-donations enables participation with a minimum effort. Qualitatively, Margetts _et al_ (2013) argue, the social value of this engagement is lower, while the locus of control is the main driver to online users – i.e. people engage to have control over their own fate, not relating it to the pursue of the common good, for example. As they conclude “contemporary political mobilisation can become viable without leading individuals and organisations to undertake organisation and coordination costs, proceeding to critical mass and even achieving the policy change at which they are aimed” (2013:19).

Yet, Laughey’s (2010) research on eBay considered the concepts of user authority and of mediated interactions to better address these internet changes and possible effects on the organization of power among online users. On the one hand, “the concept of authority allows for subtler and more dynamic shifts in relations between consumers and producers. If power is about ownership of products (the means and meanings of production), authority is about the right to claim ownership of a product and its meanings” (2010:111). This user authority, on the other hand, is granted by a combination of mediated interactions (i.e. personal and private interactions, one-to-one messages) and mediated  _quasi_-interactions (i.e. public interactions, as messages left by others in one’s profile – such as a testimonial about users idoneity in one transaction – or comments, questions and answers left in a product page).

Hence, assuming this standpoint, technology and technology usage have been sociologically understood, and they have a twofold consequence highlighted by Laughey (201): on the one hand, they allow users to contribute to each other and create new organizational structures; on the other hand, this ends up as user authority, since there is a combination of authorship and transparency in these interactions, i.e. since it is traceable and clear who is contributing at each given point. This theoretical contributions are relevant since these factors were absent in the crowd and politics theory review, and they may help to understand how online crowds behave in crowdfunding communities.

These studies on online petitions and eBay support, in different ways, a more affirmative view towards the potential positives of internet and broadening of ordinary people participating in power structures. They reinforce how specific mechanisms emerging from this new technical apparatus afford different engagements within the online community. The low costs of publishing proposals, making donations and coordinate collective engagement, or the traceability of proposals and users through platform designs that are built over mediated interactions and mediated  _quasi_-interactions, enable a decentralized or – at least – more autonomous path to gathering and action; a puzzling scheme to traditional politics.

The focus of this research, hence, is to understand the extent to which it is possible to consider the crowdfunding community a source of politics, and to understand its peculiarities. In sum, the idea is to contribute to this sociological field, namely, political participation and internet. Departing from a specific and unexplored empirical approach can lead the study to better describing and conceptualizing the potential of the internet to promote participation in politics and society.

=== Decentralized and open endeavors

Borch’s (2012) work on crowds can be a starting point to understand the “latest transformation of collectivity and suggestion in the wake of the internet”, including movements such as crowdsourcing and crowdfunding (Kelty 2013). The author is more focused on the political and rational approach to this phenomenon, but pays almost no attention to the effects of the online crowds on production and consumption dynamics. On that topic, Kelty (2008) compares free and open source software development processes with conventional activities of discussion, such as advocacy and voting. For him, even if radically different from conventional approaches, free and open source communities aim at reforming, not overthrowing, these approaches. Markets, law and technical infrastructure are not enemies to be defeated; members of this kind of community believe they can trace alternative paths, eventually (but not necessarily) pushing these incumbent institutions to adapt themselves to a new socio-economic context. Karanović (2012) argues that new practices of production and consumption of media (free and open source software included) cannot be understood only in terms of utopia and dichotomies – such as free or proprietary software, or yet copyleft or copyright. They ought to be investigated beyond these premises. For her, whether the focus is freedom of information or decentralization of production, the point is that “distributed inventions rest on flexible networks, abundance of resources and individuals freely choosing the projects in which they invest their own time” (2012:187).

This melange is highlighted elsewhere. For instance, Lessig (2004) contributes to the investigation of this melange reinforcing that well established open source licenses rely on proprietary legal concepts to enforce that the code is still available after being edited and redistributed. Yet Coleman’s (2013) ethnography on free and open source development groups (hackers included) described how complex the political aspects of this particular engagement can be: as she phrases it, these communities “represent a liberal critique within liberalism”. In other words, “hackers question one central pillar of liberal jurisprudence, intellectual property, by reformulating ideals from another one, free speech”, revealing “the fault line between two cherished sets of liberal principle”. Free and open source development groups may have their own focus on coding, sharing and contributing in order to provide the community with alternatives to proprietary software. The political facet of this activity may not be in the front stage but it cannot be discarded – and that is the tone of the proposed analysis of crowdfunding.

This relation between technology and politics is the focus of works such as Lessig’s (2006) account of how code has influence over the constitution of laws, and Barry’s (2002) analysis of anti-political machines. For Lessig, the internet will not be a territory of extreme libertarian activity, and these first decades of intense usage and innovation have the role of setting a proper constitution to the internet. Constitutions, whether it is in a strict legal sense, or as a set of norms to regulate the internet, “are built, they are not found” (Lessig 2006:4). In that sense, he argues about a social process which gives birth to that constitution, leaving some choices to be made in terms of substantive (e.g. which values to prioritize or inhibit) and structural (e.g. which institutions to prioritize or inhibit) values. These choices are to be made, among other things, through our daily usage of the internet, though the way we conceive practical and technological issues, such as how to share knowledge or develop new software within this new network. This, Lessig (2006) argues, is of utmost importance in the framing of this internet constitution. If, “in real space, we recognize how law regulates – through constitutions, statutes, and other legal codes”, he puts (2006:5), “in cyberspace we must understand how a different ‘code’ regulates – how the software and the hardware … that make cyberspace what it is also regulate cyberspace as it is.” And the consequences of this internet constitution is entangled with non-internet spheres, such as regulation bodies, and laws and copyright policies, for example (Lessig 2004 and 2006, Benkler 2010, Allen-Robertson 2013) – very political spheres, I shall argue.

While most studies on technology and society mentioned here focus on the everyday life of online users, on  _quasi_ ordinary people, actions impacting wider political issues, Barry (2002) and Allen-Robertson (2013) call the attention to how institutionalized decisions (to implement one or other technology, the reinvention of the digital culture industry within companies like Apple and Amazon) in fact narrows the space for politics.

Barry (2002) employed the concept of anti-political machines to address this same relationship between technology and the political. Following Callon’s (1998) argument on the technique aspect of economics (which frames the market and its actors through a series of technologies, such as accounting tools and marketing management), Barry analyzed how specific technologies also frame the political sphere. In that sense, arguing on the entanglement of technology, economy and politics, he considered that “an action is political … to the extent it opens up possibility for disagreement” (2002:270). He argues, yet, that what is known as politics can be, in fact, anti-political. For example, a national anti-polluting policy which subjects vehicles to emission tests inscribes a possible political debate (e.g global warming, or pollution impacts on public health) into the economic sphere (since car owners start to ponder on technical specifications on pollutant emission before buying a car, on certified mechanics to properly verify the emission, and on the value of possible fines, for example, but they do not discuss global warming or health issues). The implementation of a technological device, in that sense, is anti-political since it reduces the political debate to the employment of this technology in a practical sense.

Overlapping politics and markets, Allen-Robertson’s (2013) research on the digital cultural industry offered a description of the restructuring process this specific market went through during the last two decades. The source of this process is traced back to illicit and illegal technological practices which emerged within hacker and libertarian communities. Eventually, these same technologies ended up appropriated by the industry in a process that converted them in an important part of the formal and legal market. The starting point of this story takes into account a series of substantial values shared by the creators and early adopters of peer-to-peer technology to share music over the internet (mostly illegally). These values created a kind of ‘hacker market’ that, among other things, demonstrated the low cost of distribution, dislocate copyright as personal issue, established MP3 as conceivable alternatives to CDs and encouraged the cultivation of large digital music collections. The market appropriation of this set of values has not precisely embraced it altogether, but has dealt with it creating a new market. Although inspired by hacker culture, this new market contradicts it in so many ways, Allen-Robertson argued. For instance, iTunes Music Store, Steam gaming platform or Amazon Kindle do not respect the freedom of information or other valued claimed by libertarian hackers, but they successfully incorporated aspects such as ease of access, seamless user experience and unrestricted engagement with the content. Therefore, they also successfully fit some of the existing habits and expectations generated by the ‘hackers market’ in ordinary people. They converged hacker and legitimated market on the other, preserving the ‘hacker market’ experience, but within a legitimate market framework. In parallel, the hacker values present in this debate are now represented in formal organizations, such as The Pirate Party or the NGO Electronic Frontier Foundation (EFF), marking their space in a legitimate political framework.

Therefore the participative and constitutive aspect of online environments can be analyzed through a wider definition of politics, one that is not bounded by specific values (participation in govern, parties and interest groups) and structures (representative democracy, capitalistic production). Schedler (1997) defines politics in terms of three specific social tasks it should be in charge of: defining social problems and conflicts, elaborating binding decisions and creating politics’ own rules. Yet he argues that contemporary society should avoid premises and values that promote anti-politics (instead of nurturing politics), such as public action (against self-regulated actions), plurality (against uniformity), contingency (against necessity), authority (against ‘anything goes’) and rational deliberation (against ‘partial rationalities’).

Interestingly, studies on free and open source groups (Kelty 2008, Karanović 2012, Coleman 2013) have successively shown some references to these issues. According to Papacharissi (2009:230), “technologies frequently embed assumptions about their potential uses, which can be traced back to the political, cultural, social and economic environment that brings them to life.” For her, yet, it is crucial to take into account the discourses surrounding technology to understand how society appropriates these technologies. When it comes to the dichotomies listed by Schedler (1997), the studies on free and open source cultures have offered a more complex scenario. Although they embrace the arguments of contingency and plurality, they question some of the dichotomies: instead of the excludent quarrel between public and self-regulated actions, online participation has been blurring the boundaries and, yet, actively enhancing public and private affairs and debates (as mentioned in the case of blogging, for example); instead of counterpoint authority with an anarchical ‘anything goes’ approach, it developed more flexible, rotative and open forms of community management (for instance, the way through Wikipedia editors work towards revising of its content); finally, instead of supporting a purely rational deliberation, as mentioned, it blurs the possibility of a clear separation between a pure instrumental and a more personal reasoning scheme (as mentioned, autonomy and self-expression questioning authority).

Hence, this scenario calls into question the political or anti-political effects of crowdsourcing platforms and communities, as well as the social process of constitution of substantial values related to the internet. The task here is to investigate how decentralized crowdfunding communities can operate, and what concrete possibilities it can create from this decentralization. New models for production of media, content and software (Wikipedia, social networks, Linux etc.) have to be contrasted with anti-political criticism, and the idea is to consider crowdfunding the same way to better understand its political facet.

=== Tensions and feasibility of a political and economic decentralization

There are two recent sociological approaches that also relate to this scenario, where new means of production and consumption might be linked with new approaches to economics and politics. On the one hand, there is the resurgence of the concept of ‘prosumption’ (led by George Ritzer since 2010) and, on the other hand, the debates on a possible new spirit of capitalism (proposed by Luc Boltanski and Ève Chiapello in the 1990s, but recently revisited by Scott Taylor and Christopher Land). These approaches treat in a different way the relationship between new behaviors (values and practices) and their relation to incumbent institutions. In short, the ‘prosumer’ phenomena is seen as a way through which capitalism itself (and other power institutions around it) can be affected by the novelties proposed by internet users (Ritzer and Jurgenson 2010); alternatively, the idea of a spirit of capitalism, in the sense employed by Boltanski and Chiapello (2007), is focused on how an ideology (which supports the capitalist behavior) is adapting itself when society call into question the purpose of such capital accumulation. This section briefly introduces these approaches and discusses the possibilities of applying them as a framework for the analysis of this research project.

The recent literature on ‘prosumption’ is a great example of how the combination of internet and crowds offered room for the identification and passions on the one hand, and for a possible upsurge of a new form of capitalism on the other hand. In fact, this is the argument of Ritzer and Jurgenson (2010). Yet, they argue, the idea of the ‘prosumer’ created in the 1980s was recently renewed due to the internet: “While prosumption has always been preeminent, a series of recent social changes, especially those associated with the internet and web 2.0, have given it even greater centrality” (2010:14). In their assessment, four aspects of this new internet usage are crucial to justifying their argument on the emergence of a new form of capitalism:

First, the idea of producers (capitalists) exploiting consumers (alienated) is not possible anymore (at least) in the same degree it was before, once corporative power is challenge by alternative organization schemes, such as Wikipedia, Linux and Creative Commons – i.e., the capitalist means of production is not the only way to produce anymore. Second, if people engage in labour for free (e.g. blogging about a topic one really likes), it is not coherent to comprehend this as a deeper degree of exploitation (instead of being paid for the labour, the person is doing it for free), since “prosumers seem to enjoy, even love, what they are doing and are willing to devote long hours to it for no pay” (2010:22). Third, the traditional exchange of money for services seems to be outdated by an internet where much of what is produced is offered for free, whether it is open source inspired (e.g. Wikipedia or Linux) or proprietary services (e.g. Google or Facebook) – i.e. the flows of resources and assets has changed. Forth and finally, these changes lead to a paradigm shift that takes into account abundance instead of scarcity: for online prosumers, much of the resources are unlimited in practical terms (e.g. the amount of text that can be published does not depend on tons of scarce paper and ink to be produced, neither on tons of scarce fossil fuel to be distributed; on the contrary, there is an abundance of texts being produced and published online at extremely low costs).

Despite this more optimistic point of view, there are skeptical position about this same phenomena. Boltanski and Chiapello (2005:xxiii) represent one of them. For them self-organized network

[quote]
is frequently presented today as a quasi-’revolutionary’ emancipation force (for example, in the case of the Internet or, to take a more specific example, debates about free software). The self-organization that develops into networks can certainly prove auspicious for innovation and innovators … But there is very little chance of it providing acceptable solutions in terms of social justice on its own, precisely because the network does not offer an overarching position allowing for consideration of those who find themselves on its margins, or even disconnected.

Following this critique, the authors employ the Weberian expression ‘spirit of capitalism’ in a slightly selective sense. They “call the ideology that justifies engagement on capitalism ‘spirit of capitalism’” (2005:8, emphasis in original) and they explicitly leave to the one side an important side of the Weberian debate, namely, “the actual influence of Protestantism on the development of capitalism and, more generally, of religious beliefs on economic practices” (2005:9). In other words, the authors embrace only the Weberian argument that capitalism is so unique that it required a powerful moral justification to rally to this specific way of life:

[quote]
For Max Weber, the ‘spirit of capitalism’ refers to the set of ethical motivations which, although their purpose is foreign to capitalistic logic, inspire entrepreneurs in activity conducive to capital accumulation. Given the singular, even transgressive character of the kinds of behavior demanded by capitalism when compared with other forms of life exhibited in most human societies, Weber was led to defend the idea that the emergence of capitalism presupposed the establishment of a new moral relationship between human beings and their work (2005:8-9).

However, there is an essential difference in the approach intended by Weber and by Boltanski and Chiapello. While Weber (1976) sought to identify the extra-economic sources at the origin of this moral justification (and, eventually, he would find it in the Protestant ethic), Boltanski and Chiapello (2005:11) opt for a rather different standpoint, in their words, “not upon explaining the genesis of capitalism but on understanding the conditions in which it can once again secure for itself the actors required for profit creation.” In other words, the authors are focused on the way through which capitalism struggles to maintain the _ethos_ necessary for its survival, and not – as Weber did – focused on a closer look on extra-economic influences that can impact the economic order under which production and consumption is organized. They believe that what they have been observing since Weber are variations that fit certain basic moral aspects necessary to justify a so called capitalistic behavior, a basis on which “historical variations can be observed, even if we cannot exclude the possibility that changes in the spirit of capitalism sometimes involve metamorphosis of certain of its most enduring aspects” (2005:11). Given the argumentation of their book, it is possible to consider that these possible metamorphoses are merely a theoretical door they opt to let open. Their efforts go towards describing three remarkable changes of the spirit of capitalism since its emergence, a sequence of critiques and tests that brings to life new moral justifications to sustain that basic motivation to pursuit for profit acceptable within society – a sequence that ends up with a third spirit of capitalism, emerged from (and accommodating somehow) the anti-capitalist critiques from the 1960s, i.e. the anti-bureaucratic valorization of creativity and autonomy in the workplace. In other words, despite the theoretical possibility of metamorphosis within capitalism, empirically little or no change is substantial in terms of the propensity for capital accumulation, they suggest.

It seems Boltanski and Chiapello’s (2005) do not consider the moral conditions they study powerful enough to envisage a transformation of the economic order – as Weber (1976) did, or more recently, as Ritzer and Jugerson (2010) do. For Boltanski and Chiapello the focus on studying capitalism is on the ways through which capitalism seeks moral justification to persist within society, and not on the ways through which society creates and reinvents itself. Capitalism, in that sense, offers no room for reinventing the economic order, restricting the analysis to investigate how society is reinvented to accommodate capitalistic demands.

As Taylor and Land (2014) argues, Boltanski and Chiapello were running this research in the 1990s, and after roughly two decades new demands might have emerged. Therefore, Taylor and Land point out to an even newer spirit of capitalism (the fourth, if we count the three described by Boltanski and Chiapello), created after another round of critiques and tests, namely the environmentalist and anti-capitalist critique of the last decades. This spirit, therefore, is identifiable in a specific and contemporary management discourse which praises entrepreneurship. Interestingly, they question this linearity, arguing that it may fit an analytical purpose, but it is not necessarily an empirical phenomenon. Their research

[quote]
suggests a different temporal logic to the idea of spirit. This version of the spirit suggests more of a combination of romantic nostalgia for a lost past in which life and work were integrated into a meaningful whole through a ‘craft’ identity … with a techno-utopian postalgic discourse of emancipation to be achieved through technological development and mediated community (2014:204).

According to them this is a new scenario for entrepreneurship, one which appraise technology and community – values identified by Taylor and Land (2014) during their fieldwork in a series of events called ‘Do Lectures.’ Beyond this events, this scenario also seems to have an ‘elective affinity’ with the crowdfunding community, I shall add. The idea is that these communities are perceived as a way to pursue more personal projects (rather than careers within the corporative environment), reconnecting work and life and, yet, relying on one’s own online community of friends (and friends of friends, the weak ties) to pave the way to achieve this ideal.

The idea is not to completely dismiss the critique towards the concentration of capital and power within capitalism – indeed this concentration ought to be acknowledged. However, the point is to call into question the unidirectionality of an analysis that ignores what Papacharissi (2009:242-3) calls hybrid influence:

[quote]
The rigid model of mainstream conglomerates subsuming the smaller marginal firms is being gradually replaced by a model of hybrid influence … Online public spaces do not become immune to commercialization. However, they become adept at promoting a hybrid commercially public interaction that caters to audience demands and is simultaneously more viable within a capitalist market.

In that sense, the proposed analysis of the crowdfunding community should be attentive to the both possibilities described in this section: to what extent these crowdfunded entrepreneurs and their supporters, gathered through their highly connected network, are affecting the economic order – in a more pragmatic way such as in Ritzer and Jurgenson (2010), or even in a more profound way as in Weber (1976) – and to what extent they are subtly making room for a new spirit of capitalism – as in Boltanski and Chiapello (2005).

== Methodology

Before introducing the practical approach for this research, it worth it to clarify the epistemological and methodological basis supporting its design. As mentioned, one of the conceptual references employed is the idea of a spirit of capitalism, a concept which drawbacks to Weber’s classic works. Yet the basis for the epistemological support of this proposal can also be found within the Weberian oeuvre.

Weber ultimately addressed the question of why modern capitalism emerged in the modern Western (and not anywhere else). This was the tone of the _The Protestant Ethic and the Spirit of Capitalism_ (Weber 1976) and of subsequent writings, such as the texts organized under the section ‘Religion’ in the collection organized by Gerth and Mills (Weber, Gerth and Mills 1991). In these texts, Weber investigated how religions established specific ways through which people become reconciled to the world. Different worldviews – influenced by religion – have relevant impact over practical life conduct, even outside the religious sphere, Weber argued. That was the case of the Protestant ethic, which was based in a asceticism that had an ‘elective affinity’ with modern capitalism. By these means, religion did not caused capitalism, but is one possible explanation to the fact that modern capitalism emerged strongly in northern Europe and in the USA (and not elsewhere).

It is important to highlight two aspects of this approach. First of all, according to him, the role of social science scholars is to work towards one possible explanation for social actions and institutions. This infer that other causal mechanisms should not be excluded, since other explanations could also account for the very same aspects of the social. Using his own research as a reference, Weber put (1991:268):

[quote]
No economic ethic has ever been determined solely by religion. In the face of man’s (_sic_) attitude towards the world … an economic ethic has, of course, a high measure of autonomy. Given factors of economic geography and history determine this measure of autonomy in the highest degree. The religious determination of life-conduct, however, is also one – note this – only one, of the determinants of the economic ethic. Of course, the religiously determined way of life is itself profoundly influenced by economic and political factors operating within given geographical, political, social and national boundaries.

The second aspect to consider is the influence of certain social spheres (e.g. religious, economic, political, social, geographical, national), which extrapolates the boundaries of this same social sphere. Again, in Weber’s considerations of his own oeuvre:

[quote]
An ethic based religion places certain psychological sanctions (not of economic character) on the maintenance of the attitude prescribed by it … Only in so far as these sanctions work, and above all, in the direction in which they work, which is often different from the doctrine of the theologians, does such an ethic gain an independent influence on the conduct of life and thus on the economic order (Weber 1976:197).

[quote]
For every religion we shall find that a change in the socially decisive strata has usually been of profound importance. On the other hand, the type of religion, once stamped, has usually exerted a rather far-reaching influence upon the life-conduct of very heterogeneous strata. In various ways people have sought to interpret the connection between religious ethics and interest-situations in such a way that the former appear as mere ‘functions’ of the latter. Such interpretation occurs in so-called historical materialism … as well as in a purely psychological sense (Weber, Gerth and Mills 1991:270).

This background sets the tone of the approach intended for this research: first, an analysis of worldviews related to the emergence of the crowdfunding phenomenon; second, departing from this analysis, it intends to establish inferences about crowdfunding and its relationship to social institutions (mainly the political and economic ones). The hypothesis is that politically fashioned worldviews are as relevant to the emergence of crowdfunding, as religious ones were to capitalism.

Since crowdfunding platforms and projects have a many different motivations, this research design has to be theoretically prepared to deal with veil and unveiled purposes. Therefore, the focus on worldviews better accommodates the plurality that could emerge from the fieldwork, as well as enables a wider consideration the motivations driving people to crowdfunding. The strength of this approach relies on the comprehension of a macro-institutional level understood from a micro-sociological starting point – such as in the possibility of a new form of capitalism suggested by Ritzer and Jurgenson (2010), or even in relation between the Protestant ethic and the emergence of capitalism sustained by Weber (1976). In sum, the objective here is to investigate the relationship between worldviews and the emergence of crowdfunding online communities – i.e. between the way people see crowdfunding and the way they see incumbent political and economic institutions.

According to Beer and Burrows (2007), the appropriate way to address the ‘dynamic’ internet is to opt for descriptive accounts, reconceptualizing spheres that are being redefined by the online communities and tools. For them, the challenge is “to construct more complete and differentiated descriptions of what is happening” and to give an account of “who is involved, and the practices entailed, in order to inform and enrich new concepts or reworkings of our theoretical staples” (2007). Moreover, given the emerging aspect of crowdfunding, it is not possible to follow Weber’s (or even Boltanski and Chiapello’s) methodological approach, one based on document and text analysis (Land and Taylor 2014). Alternatively, the focus will be on interacting with people involved in crowdfunding through semi-structure interviews in order to build this descriptive approach to their worldviews.

This descriptive and Weberian approach, allied with the contemporaneity of the focus of this research, has yet another characteristic to be highlighted in terms of methodology: these methodological choices afford an understanding of social changes from the standpoint of a specific worldview, making room for complementary explanations that could be found by other researches. This seems relevant and coherent since emerging fields also nurture contradictory analysis. For example, while Beer and Burrows (2007) put forward arguments towards the weakness of privacy within social network users, boyd (2014)footnote:[danah boyd intentionally signs her name without using capital letters.] describes precisely the opposite, i.e. how teenagers build a new form of privacy through the way they use their social networks.

In that sense, this research has a twofold source of data. First, and more important, semi-structured interviews will be held with people engaged with the practice of crowdfunding. The aim is to assess their point of view, and to inquiry about how they locate themselves into society – i.e. to grasp their own worldviews, values and references. Second, and complementary, the online activity of people engaged in crowdfunding might followed, since they are expected to be very into the digital culture. Therefore, what they post publicly on on blogs, Twitter, Facebook and other social networks can be accounted as their voice, can be used to better understand their worldviews and to validate the content of interviews through triangulation.

There are a vast number of crowdfunding platforms. Although Wikipedia (2014) lists more than 60 active platforms, this is clearly an incomplete list. Catarse is a Brazilian platform built in an open source license,footnote:[Catarse (2014) operates under MIT License (Open Source Initiative 2014).] i.e. anyone is free to use and adapt their source code to build a new platform. According to Catarse’s wiki (2014) there are 14 active platforms based on their source code (roughly half of them operating in other countries than Brazil, such as USA, Canada, Denmark and Argentina). Most of them (including Catarse) are not included in the current Wikipedia’s list.

This investigation considers three different branches of crowdfunding as a starting point. First there is Indiegogo, one of the firsts and most widely known platforms. Second, there is Kickstarter, the so called largest crowdfunding platform in the world.:footnote:[The “largest” is read over the news without an objective measure or comparison with other platforms (e.g. Canadian Press, 2013). Anyhow Kickstarter’s numbers are eye-catching: almost 1 billion dollar dollars pledged, more than 55 thousand projects funded, more than 5 million backers, i.e. people who supported at least one project (Kickstarter 2014).] And third, there is the open source Catarse.

In terms of hosted projects, all of them are very open. Even if they were created with some kind of public and projects in mind (e.g., Indiegogo and Kickstarter primarily focus was on creative projects, while Catarse focuses on cultural projects), they are open enough to host projects that vary considerably: from movies and music, to software and hardware technology development, including sports, civic actions, political organization, and education. Despite the similarity of projects hosted, this tripod exemplifies some interesting differences, namely: differences in terms (a) of business models, (b) of the approach to the contents published in each one of these platforms, and (c) the relationship these platforms establish with other crowdfunding platforms.

When it comes to their business models, the basic difference between Indiegogo, Kickstarter and Catarse is that the former charges a higher fee (a percentage over the total value pledged), but the project creator can collect the money pledged even if the target is not reached – this model is known as ‘keep-it-all.’ On the other hand, the other two charge a smaller fee (also a percentage over the total value pledged), but if the project target is not reached, all the money returns to the backers and no fees are collected (nor any funds is passed to the project creator) – this model is known as ‘all-or-nothing.’ Crowdfunding campaigns under this last model tends to engage not only the project creator, but also its supporters – i.e. the role of spreading the word about the campaign is crucial to make the funds be collected.

Considering the curation, Kickstarter and Catarse tend to have a more prominent curatorial layer: people from the platform tend to work together with the project creators. The focus is on refining the content to be published, in order to assure that the project has good chances of being funded. Indiegogo, in that sense, is more open and users can submit projects without the explicit platform ‘seal of approval.’

Finally, if Indiegogo and Kickstarter operate as traditional business, looking for customers (project creators as well as users to support them),footnote:[And, regarding Kickstarter, eventually getting involved in judicial cases around patents for their crowdfunding models (Purewal 2011).] Catarse departs from an heterodox market philosophy, offering its source code openly, and with no apparent fear that some ‘copycat’ would represent a risk to them. In fact, Catarse developers seem to express the completely opposite idea: they are seem helpful with other developers using their source code (i.e. they are very active in their collaborative channels: their open GitHub repository and their open Google Group mail list dedicated to developers). In other words, Catarse seems to have a very different relationship with other crowdfunding initiatives (at least, with the ones benefiting from its own source code).

Moreover, this initial tripod of platforms cover crowdfunding in different countries. Catarse is mostly focused in Brazil. Kickstarter was launched officially in the USA, the UK and Canada (Canadian Press 2013). And Indiegogo (2012) hosts projects from all over the world, working with five different currencies (American Dollars, Canadian Dollars, Australian Dollars, Euros and British Pounds). However, in addition to these three big branches, several other platforms have their own peculiarities, offering different points of view that should be considered for the sake of this research. For example:

* _Beacon_: its focus is independent writers and journalists; their supporters contribute periodically with small amounts to have access to a large amount of texts. 
* _Cinese_: a Brazilian crowdfunding platform focused on meaningful meetings supporting non-traditional learning. 
* _Crowdfunder_: its mission is to connect investors and entrepreneurs, allowing small investors to support startups with small amounts (the idea is to dilute the role of the ‘big’ investor in order to offer venture capital). 
* _Crowdrise_: it was built exclusively for charity fundraising purposes. 
* _FundAnything_: it is focused on the general public and it is backed by Donald Trump, who acts as a financial partner and who often talks about its projects in public. 
* _Neighbor.ly_: based on Catarse source code, it is a crowdfunding platform built specificaly for funding civic projects. 
* _MedStartr_: also based on Catarse, it was built exclusively to crowdfund medical projects; their lead is to promote medical innovation according to ordinary people interests. 
* _Patreon_: instead of funding one ‘big’ project, this platform offer supporters the chance to contribute periodically (usually with small amounts) to people and projects that periodically release new contents (e.g., one can commit to offer 1 dollar for each tutorial a musician uploads on YouTube).

With these 11 platforms in mind (the list above, plus the tripod Indiegogo, Kickstarter and Catarse), the idea is to interview different profiles: (a) platforms founders and staff, (b) people submitting projects to these platforms (project creators), and (c) people backing – and spreading the word about – these projects (project supporters). For each founder or staff interviewed, the idea is to interview two project creators and three project supporters. If each platform results in six interviews (according to the aforementioned ratio), we can estimate 66 interviews from this 11 platforms list. As it might be difficult to get access to some of these people the proposal is to run around 30 interviews. It is worth it to note that this is not a final list of crowdfunding platforms; it is just a starting point, and surely more platforms can be added during the research.

The data collection phase starts with the publicly available channels to contact these platforms: email, contact form, social media etc. I will be reaching them, explaining the purpose of the research and asking for collaboration. If they opt to cooperate, I can ask for interviews, and also ask if they can help me in recruiting within their users (project creators and supporters). For some of the platforms, I have no other access to them – this is the case of Crowdfunder, Crowdrise, FundAnything and Indiegogo. If they refuse to cooperate, the alternative is turn to other crowdfunding platforms in order to keep a good sample distribution – i.e. in terms of different focus on crowdfunding, different business models, a good staff, creators and supporters ratio, and other criteria described above. However, for the other platforms, I have already better access to data – this is the case of Beacon, Catarse, Cinese, Kickstarter, MedStartr, Neighbor.ly and Patreon.

Regarding Catarse, Neighbor.ly and Cinese, people involved in these platforms are linked to my personal network. I am very close to some people who worked for Engage, the company who created Catarse. However, my contacts are within Engage, while Catarse established itself as a corporate spin-off. In other words, I have means to easily access Catarse founder and staff. Within this same network there is one Catarse developer who lived for a while in the USA, where he collaborates to Neighbor.ly. This programmer can put me in touch with Neighbor.ly founders and staff as well. Finally, the founders of Cinese are also close to this Engage network: they are based on the same collaborative space where one of the projects of an Engage founder takes place. Once more my proximity with Engage can put me in touch with the possible interviewees.

As MedStartr is based on Catarse source code, probably this same network can put me in touch with them. However, to minimize bias, the priority is to approach MedStartr through a distant friend who recently uploaded a project to be crowdfunded there – he and his partners in the project (people I have never had contact with) can be interviewees, and I can explore the connections they have made there through this project.

Considering some personal contributions I have made with projects in Kickstarter and Patreon I can have access to these project creators, people I have never heard about before their projects pop out in my social networks and news feed. I can ask for interviews and ask for their collaboration in helping me to recruit among others supporters they had. Besides this entry points, I will attempt to reach further contacts in Kickstarter and Patreon through standard contact details provided openly by the platforms (emails, contact forms, social media etc.), mainly founders and staff. Yet, Jack Conte, Patreon’s founder, is an active user of his own platform and one of the rewards he offers for those who pledge US$ 100 (or more) is an exclusive video conference with him – i.e. I can pledge this amount and have access to him.

Finally, Beacon is a platform which fits the scheme where they play a curation role before publishing crowdfund campaigns. As I contribute regularly to blogs (in spite of the fact of barely updating my own blogs), I recently subscribed to Beacon and soon I will have an online meeting with them to discuss my writing and a possible crowdfunding project through their platform. I intent to use this opportunity to briefly talk about this research and try to have access to them as interviewees.

Before continuing, it is worth it to disclosuere that I have projects crowdfunded through Catarse and Nós.vc (a platform similar to Cinese), and I have also contirbuted to projects on Catarse, Nós.vc, Kickstarter and Patreon. I did not included Nós.vc in this research since the founders (and staff) are close friends – and that would be too much bias. Furthermore, the bias can be also minimized since the contacts mentioned in the last paragraphs will be trigger to a snowball process, i.e. I will ask them if they are happy to suggest someone else to be interviewed, making me reach people outside my regular network.

The focus of the semi-structured interviews will be to comprehend the point of view of the interviewees about society, business, politics and economics – especially (but not restricted to) when it comes to crowdfunding. In order to better grasp these views, the first part of interviews will not focus on crowdfunding, but on the interviewees’ perceptions of themselves within society – i.e. how they position themselves facing a given cultural, political and economic context. Yet this initial part will cover the interviewee’s aspirations and ideals when it comes to the social context. The idea is to adopt a funnel-shape questioning technique, narrowing down the subject (namely, crowdfunding) towards the final part of the interaction. By these means, the participants might get to the specific subject spontaneously. Consequently, the role of the interviewer is to conduct the interviewee in such direction only if certain topics do not emerge in that more spontaneous way (Kvale and Brinkmann 2009). Therefore it is expected that the first part of the interviews covers aspects such as the interviewees’ general opinion on government, on corporations, on civic organizations, on political views and attitudes. The intention is to get these aspects linked with their personal initiatives (linked to crowdfunding) without intervention, i.e. without stimulating the interviewee to relate them to crowdfunding. This technique is employed to avoid the risk of making the interviewee stick to one or other concept just because the interviewer mentioned it – and not because it was already part of the interviewee’s own point of view (Kvale and Brinkmann 2009).

Next the semi-structured interviews may vary among different profiles of interviewees. The next phase of the funnel is the interviewees’ relationship with a certain crowdfunding platform. For founders and managers, the conversation will focus on how they situate their business within society, their choice to found, or work for, a crowdfunding enterprise. For project creators, the exploration will shift towards the reasons why they opt to count on a crowdfunding instead of other funding possibilities. For supporters, the focus will be on what has driven them to take part in crowdfunding campaigns.

Finally, after objectively introducing the topic of crowdfunding, the last block of the interview will address the opinions and views of the interviewee about crowdfunding in a broader sense. The investigation will inquiry about what interviewees expect from crowdfunding, how they position it with ‘traditional’ social sphere (such as business, politics or culture), and yet check a more aspirational approach, in order to grasp their collective and individual expectations related to crowdfunding mechanisms.

The interviews, when possible, will be held in person (when financially possible) or remotely (using telephone, VoIP or video conference). The context that will be lacking in the remote interviews is not considered to represent a relevant loss of data in this particular case as (among other reasons) most of our participants are expected to be well articulated and used to express themselves in public (they will be entrepreneurs who found and manage online platforms, or they put their own projects online to public, or yet they voluntarily engage with these projects, spreading the word about it).

The content of the interviews will be recorded (according to the consent of the interviewee), transcribed and analyzed. It will be up to the interviewee to be anonymized or not. Next the focus will be on the coding and condensation of meaning. The idea is to condensate the most relevant units, and use the coding to categorize the bits of information. This qualitative analysis technique will lead to a grounded theory approach (Kvale and Brinkmann 2009). The next step will be to triangulate this content with other sources, with data collected from the platforms themselves and from the interviewees’ online profiles. This process allows a contextual interpretation of the meaning of these units of information, as well as validation of the content of the interviews – i.e. more basis for a grounded theory approach (Kvale and Brinkmann 2009).

This analysis process takes into account the relationship between the concepts our sources employ and their own perception of the world. The conceptual framework used by social actors can limit and determinate action or, yet, can completely reconceptualize action (Ragin 1994). Moreover, “at any particular time, one should be prepared to find that governing concepts can, and often do, lag behind the behavioral requirements of the case” (Ragin 1994:92). Having in mind the aforementioned defense for a descriptive procedure when it comes to internet (Beer and Burrow 2007), the grounded theory approach at sake intents to build an appropriate framework to describe the relationship between crowdfunding, politics and economics. Moreover, while this approach considers the benefits of generating theory from the collected data, it also positions this process face-to-face to set of already existing sociological concepts (i.e. referring to the literature review above). The advantage of this resort is to overcome possible limitations of grounded theory, i.e. to overcome the risk of end up with theory that is strictly tied to the field where the data was collected (Blaikie 2010). Given the contemporaneity of crowdfunding and the potential of internet communities to impact incumbent institutions (Ritzer and Jurgenson 2010), this design ought to deal with already existing concepts, as well as with new ones being forged in the process.

== Research Plan

The research starts with the literature review, followed by a preliminary set of interviews. This first round of interaction is analyzed to grasp possible improvements to the semi-structure guide, secondary research (i.e. research about branches of crowdfunding, possible interviewees, topics to be covered etc.) and literature review. This scheme is represented in the plans for the next 32 months (tables organized per year, months represented by the numbered columns):

*2014*

[width=”100%”,cols=”12%,8%,8%,8%,8%,8%,8%,8%,8%,8%,8%,8%”, options="header"]
|===================================================
|Task |2 |3 |4 |5 |6 |7 |8 |9 |10 |11 |12 
|Literature Review (1st round) |x |x |x |x | | |x | | | | 
|Secondary research |x |x |x |x |x |x |x |x |x |x |x 
|Interviews (1st round) | | |x |x |x | | | | | | 
|Preliminary analysis | | | | |x |x | | | | | 
|Interviews (2nd round) | | | | |x |x |x |x |x |x |x 
|Analysis | | | | | | | | |x |x |x 
|===================================================

*2015*

[width=”99%”,cols=”16%,7%,7%,7%,7%,7%,7%,7%,7%,7%,7%,7%,7%”, options="header"]
|===================================================== 
|Task |1 |2 |3 |4 |5 |6 |7 |8 |9 |10 |11 |12 
|Interviews (2nd round) |x |x |x | | | | | | | | | 
|Analysis |x |x |x |x |x |x |x |x | | | | 
|Preliminary report | | | | | | | |x |x | | | 
|Literature review (2nd round) | | | | | | | | |x |x |x |x 
|Writing | | | | | | | | | | |x |x 
|=====================================================

*2016*

[width=”99%”,cols=”10%,10%,10%,10%,10%,10%,10%,10%,10%,10%”, options="header"]
|=============================================== 
|Task |1 |2 |3 |4 |5 |6 |7 |8 |9 
|Literature review (2nd round) |x |x |x |x |x | | | | 
|Writing |x |x |x |x |x |x | | | 
|Dissertation: Draft version | | | | | |x | | | 
|Work on the feedback | | | | | | |x |x |x 
|Dissertation: final version | | | | | | | | |x 
|===============================================

== REFERENCES

Allen-Robertson, J. (2013). _Digital Culture Industry: A History of Digital Distribution_. Basingstoke: Palgrave Macmilllan.

Barlow, J. (1996). _A Declaration of the Independence of Cyberspace_. Available at: https://projects.eff.org/~barlow/Declaration-Final.html [Accessed: 24 May 2014].

Barry, A. (2002). The Anti-political Economy. _Economy and Society_, 31(2). Pp. 268-284.

Baudrillard, J. (1994). The Precession of Simulacra. In _Simulacra and Simulation_. Ann Arbor: University of Michigan Press. Pp. 1-42.

Beer, D. and Burrows, R. (2007). Sociology And, Of and In Web 2.0: Some Initial Considerations. _Sociological Research Online_, 12(5). Available at: http://socresonline.org.uk/12/5/17.html [Accessed: 03 Dec. 2013].

Belleflamme, P., Lambert, T., and Schwienbacher, A. (2013). Crowdfunding: Tapping the right crowd. _Journal of Business Venturing_, 29(1). Pp. 1-16.

Bennett, E. A., Cordner, A., Klein, P. T. and Baiocchi, G. (2013). Disavowing Politics: Civic Engagement in an Era of Political Skepticism. _American Journal of Sociology_, 119(2). Pp. 518-548.

Benkler, Y. (2010). The Idea of Access to Knowledge and the Information Commons: Long-Term Trends and Basic Elements. In Krikorian, G. and Kapczynski, A. (eds.). _Access to Knowledge: In the Age of Intellectual Property_. New York: Zone Books.

Blaikie, N. (2010). _Designing Social Research: The logic of anticipation_. 2nd ed. Cambridge: Polity Press.

Boltanski, L. and Chiapello, E. (2005). _The new spirit of capitalism_. London: Verso.

Borch, C. (2012). _The Politics of Crowds: An Alternative History of Sociology_. Cambridge: Cambridge University Press.

boyd, d. (2014). _It’s Complicated: The social lives of networked teens_. New Haven and London: Yale University Press.

Callon, M. (1998). Introduction: The Embeddedness of the Economic Markets in Economics. In Callon, M. (ed.). _The Laws of the Markets_.Oxford: Blackwell.

Canadian Press, The (2013). Kickstarter crowdfunding site officially launches in Canada: Canadian entry held up by red tape, financial regulations, co-founder says. Available at: http://www.cbc.ca/news/business/kickstarter-crowdfunding-site-officially-launches-in-canada-1.1703774 [Accessed: 20 Jan. 2014].

Coleman, E. G. (2013). _Coding Freedom: The Ethics and Aesthetics of Hacking_ [digital book]. Princeton: Princeton University Press.

English, R. (2013). Rent-a-crowd? Crowdfunding academic research. _First Monday_, 19(1). Available at: http://firstmonday.org/ojs/index.php/fm/article/view/4818/3804 [Accessed: 20 Apr. 2014].

Indiegogo (2012). International Campaigns. Available at: http://support.indiegogo.com/entries/20882543-international-campaigns [Accessed: 20 Jan. 2014].

Karanović, J. (2012). Free Software and the Politics of Sharing. In H. A. Horst & D. Miller (Eds.), _Digital Anthropology_. London: Bloomsbury. Pp. 185-202.

Kelty, C. (2008). _Two Bits: The Cultural Significance of Free Software_. Durham: Duke University Press.

Kelty, C. (2013). The Politics of Crowds: An Alternative History of Sociology. _Journal of Cultural Economy_ [online]. Available at: http://dx.doi.org/10.1080/17530350.2013.840667 [Accessed 30 Dec. 2013].

Kickstarter (2014). Kickstarter Stats. Available at: https://www.kickstarter.com/help/stats [Accessed: 20 Jan. 2014].

Kvale, S. and Brinkmann, S. (2009)._ Interviews. Learning the Craft of Qualitative Research Interviewing_. London: Sage.

Laughey, D. (2010). User Authority Through Mediated Interaction: A case of eBay-in-use. _Journal of Consumer Culture_ (10)1. Pp. 105-128.

Lessig, L. (2004). _Free Culture: How Big Media Uses Technology and the Law to Lock Down Culture and Control Creativity_. New York: Penguin Press.

Lessig, L. (2006). _Code: Version 2.0_. New York: Basic.

Maffesoli, M. (1996). _The Time of the Tribes: The Decline of Individualism in Mass Society_. London: Sage.

Margetts, H., John, P., Hale, S. & Reissfelder, S. (2013). Leadership without Leaders? Starters and Followers in Online Collective Action. _Political Studies_, n-a(n-a). Pp. 1-22.

Margolis, M. and Moreno-Riaño, G. (2009). _The Prospect of Internet Democracy_. Farnham and Burlington: Ashgate.

McLuhan, M. (1994). _Understanding Media: The Extensions of Man_. Cambridge: Massachusetts Institute of Technology Press.

Mouffe, C. (2005). _On the Political_. London: Routledge.

Open Source Initiative (2014). The MIT License. Available at: http://opensource.org/licenses/MIT [Accessed: 20 Jan. 2014].

Papacharissi, Z. (2009). The Virtual Sphere 2.0: The internet, the public sphere, and beyond. In A. Chadwick & P. N. Howard (eds.). _Routledge Handbook of Internet Politics_. London and New York: Routledge. Pp. 230-245.

Purewal, S. (2011). Kickstarter Faces Patent Suit Over Funding Idea. _PCWorld_. Available at: http://www.pcworld.com/article/241160/kickstarter_faces_patent_suit_over_funding_idea.html [Accessed: 20 Jan. 2014].

Ragin, C. (1994). _Constructing Social Research: The unity and diversity of method_. Thousands Oaks, London and New Delhi: Pine Forge Press.

Ritzer, G. and N. Jurgenson (2010). Production, Consumption, Prosumption: The nature of Capitalism in the Age of the Digital `Prosumer.' _Journal of Consumer Culture_, 10(1). Pp 13-36.

Schedler, A. (1997). Introduction: Antipolitics – Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 1-20.

Sniderman, P. M. and Bullock, J. (2004). A Consistency Theory of Public Opinion and Political Choice: The hypothesis of men dependence. In Saris, W. E. and Sniderman, P. M. (eds.). _Studies in Public Opinion: Attitudes, nonattitudes, measurement error, and change_. Princeton and Oxford: Princeton University Press. Pp. 337-357.

Taylor, S. and Land, C. (2014). The Good Old Days Yet to Come: Postalgic times for the new spirit of capitalism. _Management & Organizational History_, 9(2). Pp 202-219.

Weber, M. (1976). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.

Weber, M., Gerth, H. H., and Mills, C. W. (1991). _From Max Weber: Essays in Sociology_. London: Routledge.

Wikipedia (2014). Comparison of crowd funding services. Available at: https://en.wikipedia.org/wiki/Comparison_of_crowd_funding_services [Accessed: 20 Jan. 2014].

Žižek, S. (2024). _Organs without Bodies: Deleuze and Consequences_. New York and London: Routledge.
