= Crowdfunding and the reconfiguration of the public and private spaces
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_University of Essex_

This ongoing PhD research consists of a social and political analysis of the crowdfunding phenomenon. Platforms as Kickstarter or Indiegogo make initiatives tangible through actions of ordinary people, dismissing institutional support from government or corporations. The hypothesis is that a political analysis of these online gatherings might call into question the spaces where people pursue public and private interests.

Arendt criticized the role of modern state as a guardian of individual freedom, highlighting that real possibilities of political action still restricted to political elites. Simultaneously private interests of corporations have compromised the political sphere, argues Wolin and Schedler. According to them states take decisions within the private realm, diminishing the spaces for public interests. Finally Bellah argued that this scenario and its emphasis in the private interests favored individualism. Yet, he adds, people are not comfortable with it: the lack of social ties makes them eager for connections.

The basis of this paper are interviews with people engaged with crowdfunding in Brazil, the UK and the USA. If the institutional conjuncture seems to seize the public sphere from people, citizens might be fighting back recreating the public realm within this purportedly private space. Instead of traditional political organizations (such as parties or social movements) crowdfunding benefits from practical disruptions emerged from new technologies. Yet it might grasps what post-representativeness could be or what a post-political pragmatic approach could look like. The discussion considers political possibilities and limitations of this new setting for private and public spaces.

Keywords:: crowdfunding, internet, politics, public space, private space.

Word count:: 246

Conference:: Digital Sociology Mini-Conference within the link:http://www.essnet.org/?page_id=47[ESS Annual Meeting] (from Feb. 26 to Mar. 1st, 2015 -- New York, USA). 
