= Crowdfunding and the reconfiguration of the public and private spaces
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_University of Essex_

== Introduction

The phenomenon of crowdfunding is among the several possibilities brought to existence by the emergence of the internet and of the web 2.0. While the turn of century platforms for blogging and social networking were focused on the production of online contents by ordinary users, arguably what came next was the extrapolation of the digital boundaries. Underneath this claim lies a set of changes that includes (but is not limited to) the falling costs of production of different kinds of goods and services (from 3D printers to video production, for example), the easiness to find and collaborate with others world wide (which basically started with emails, but expanded to the most different and specific kinds of platforms), and niche online stores delivering very specialized products all around the world (from tools for peculiar hobbies, to DIY supplies and technological gadgets). Yet this scenario takes into account abstract and intangible changes, such as the idea of collaborative and crowdsourced projects (the most renowned being Linux, Wikipedia and the Human Genome Project), the debate over intellectual property (such as the struggle and changes the music industry faced after the advent of the MP3, or yet Google book-scanning efforts and the succeeding debates) and the dispute over privacy on the internet (specially after WikiLeaks, specific Anonymous operations labeled as hacktivism, and the Edward Snowden case). In sum, the internet has been pivotal to transformations that affect several spheres of the social life. And within these changes crowdfunding is a specific mechanism that puts together different aspects of these novelties.

Basically crowdfunding platforms are websites on which users expose their own projects and ideas, asking for financial contributions in order to be able to execute these projects. Enthusiasts can offer different amounts during the period in which the campaign is online. If the project is funded usually there are some rewards to those who made it possible. It is not rare that the simple execution of the project is considered a perk to everyone involved and interested (independently of any kind of financial collaboration). When this is the case, alternatives to copyright licenses such as Creative Commons play an important role. The biggest players in this field are Kickstarter and Indiegogo, and through this mechanism different kind of projects have been funded: from museums to individual's trips; from olympic athletes to personal charity; from technological gadgets to online education; from music albums to medical equipments; from comics to public transportation.footnote:[It is not the case of commenting on individual projects, but the references for the projects mentioned above are (respectively): Tesla Museum (asked for US$ 850k, raised more than US$ 1.3m – http://www.indiegogo.com/teslamuseum), Destino Incomum (asked for US$ 100, raised US$ 1k – http://catarse.me/destinoincomum), Larissa Juk (asked and raised US$ 10k – http://catarse.me/larissario2016), Alan Barnes Fund (asked for US$ 750, raised US$ 495k – http://gofundme.com/l0dt9o), Glif (asked for US$ 10k, raised US$ 137k – http://kck.st/bb6Tuu), Escola Livre de Jornalismo (asked and raised US$ 9k – http://catarse.me/enois), Amanda Palmer (asked for US$ 100k, raised roughly US$ 1.3m – http://kck.st/JliwH9), Avado (asked for US$ 5k, raised US$1.3m – http://medstartr.com/projects/13), Corey Mohler (raising US$ 1.1k monthly through a recurring platform – http://patreon.com/ExistentialComics), and Kansas City B-cycle (raised 60% of the US$ 700k target – http://neighbor.ly/projects/bikesharekc). All values were converted to US dollars when the project used a different currency.]
 
The fact that such a variety of ideas are becoming tangible without a formal sponsorship of incumbent institutions such as government or corporations makes of crowdfudning a promising case for sociological studies. This ongoing doctoral research focus on the way people engaged in this type of project employ a pro-active and hands-on mode that challenges these incumbent institutions. Interestingly the tone of this challenging attitude is not of direct confront against public administration or multinational companies, but of finding an alternative path considerably marginal from governments and corporations. Yet, in opposition to initiatives such as social movements or NGOs, crowdfunding unreservedly embraces the idea of profit and reshapes it as a sustainable mean to empower this marginal path. Profit is often dislocated from an endless accumulative disposition footnote:[As described, for example, in Weber's _The Protestant Ethic and the Spirit of Capitalism_ (1976).] and understood as a tool for autonomy, as an important resource to enable individual and collective (political) action.

Additionally the general disinterest of these individuals in traditional politics (such as elections or parties), together with their contempt for traditional careers within traditional corporations, place them in an intriguing gap: they are not the virtuous citizens as imagined by theories of representative democracy, neither they seem to fit the traditional self-interested capitalist maximizing profits through a solid and stable professional career. Therefore this peculiar characteristics invite social researchers to explore the participation of this group in contemporary society. Here the idea is to understand how this attitudes calls into question the notions of the private and public realm and, subsequently, how it might contribute to the comprehension of politics, both in their everyday life as well as in a wider understanding of politics.

The following section explores current debates in terms of political theory. Arguably nowadays society has become anti-political, both from the individual and institutional perspectives. Based on Arendt (1998, 1973), the conceptual framework employed here takes the anti-political argument into account together with an approach focused on the understanding of the public and the private realm. The subsequent section offers an overview of the in-depth interviews that are the empirical support to this paper and exposes the core of the findings: from an analytical description of their lifestyle, the objective is to explore how their attitudes relates to the wider context of social institutions such as government, corporations, money and professional career. This analysis is based on their focus on individual autonomy and the controversial possibility of politics (and values inherent to the public realm) being revitalized through this process. 

== The public and the private realms in a modern, anti political and individualist society
_Approx: 2 page_

* What is public, what is private, and how politics fits: explore Arendt's argument on the delegitimation of traditional political institutions, and how the concepts of public and private are situated in the core of this process (in other words, even the government in modern society is looking after and operating according to the private realm, leaving no space for the public one).
* Discuss the relation (and importance) of action for Arendt's understanding of politics.

== Crowdfunding and social institutions

Drawing on 10 semi-structured in-depth interviews this paper organizes the findings of the first round of data collection for this project. According to the wider research design this stage explores the world views of people engaged in crowdfunding platforms in two different levels: founders or staff of these platforms, and project creators, that is, people who have recently submitted projects to these platforms. The access to this public is not uncomplicated. For instance, some of the platforms featuring among the wealthiest startups of recent years are considerably closed for interviews, only expressing themselves through their own public relations department. Yet very successful project creators usually end up dealing with thousands of followers on social media, making their attention to incoming messages relatively unreliable. In spite of that, this initial stage was able to interview people involved with seven different platforms (Indiegogo, CrowdCube, Catarse, Benfeitoria, Cinese and Unlock) from three different countries (USA, UK and Brazil). The interviewees, 4 women and 6 men, were from four different countries (the three above plus Romania) with ages varying from 24 to 61 years old. Names and other references that could be used to identify informants have been anonymized. The entry points for access to these people involved different initiatives: attempts to direct contact through email and social media, attendance to events and places related to sharing economy and similar topics, personal contacts in the entrepreneur and technological scene in the USA and Brazil, and, mainly, snowballing.

The structure of the interview was funnel shaped: the fist topic was focused on self identity, lifestyle, main activities, and on one's own life trajectory. Usually the conversation would end up in crowdfunding, which was exactly what was planned for the second block of the interview: discussing why they have embraced these platforms (whether it was as founder, staff or project creator) and how the experience was, or have been so far. Finally, if issues about government, corporations and formal politics have not emerged, these topics were raised in a third and final block in order to assimilate interviewee's perception about the institutional context surrounding them. 

Unintentionally the sample ended up being biased towards initiatives that make efforts to differentiate themselves from the mainstream startup and entrepreneurship agenda. On the one hand, this was due to the aforementioned difficult in getting access to big players in the startup and entrepreneur scene. For instance, when I had access to the personal email address of a former staff of one of these platforms, she was unable to conceive what she could offer me beyond what was already available from the public relations material of her former employer. She ended up declining my invitation for interview, apologising and referring to her former employer guidelines of conduct. On the other hand, this difficulty to gain access to the startup driven enterprises, together with the easiness to gain access to the alternative branch, reinforces the aforementioned approach on the marginal path I shall expand on next.

The following section draws on my interviewee's personal experiences and life choices. The idea is to grasp how they deal with everyday choices regarding making a living of their projects, including inspirations and personal aspirations. Drawing on this micro sociological approach the subsequent section discusses how this specific world view identifiable within crowdfunding relates to social institutions, that is to say, a descriptive view of the subtle and the explicit challenges they foster. On top of that there is the sociological discussion regarding the public and the private realm as well as the possibilities for politics in modern society. 

=== Lifestyle, non-traditional pathways and motivations

_Approx: 3 pages_

* Maker culture, hands-on attitude: focus on action.
* Autonomy is the key driver.
* Clarify that the digital culture has a tangible aspect of accessibility, easiness to communicate, to spread the word about one's project. But also, this crowdfunding community intersects with different (and more specific) influences such as hacker culture, and access to knowledge.
* Putting all together, to the maker culture it is added an ideological component: the willing to make certain projects happen is an important motivation, even if no direct benefit is taken from this realization (maybe this is slightly different from more utilitarian market relationship, and arguably it fosters a certain kind of common good).
* How they make a living (different projects, the idea of multiple smaller pots in opposition to a traditional career and the idea of an all-in in one single pot).
* The importance of building a network based on mutual trust to sustain the individuals' projects.

=== Challenging incumbent institutions

_Approx: 5 pages_

* From a radical standpoint, one could say that there is a complete lack of trust in corporations and government; a more subtle view would argue that people engaged in crowdfunding simply do not want to depend on these incumbent and traditional institutions.
* Connect this attitude to Arendt's critique of modern societies and the mitigating of the public realm. Also to private interest being persuasive within corporations and government (Wolin).
* Extend the argument to the contempt for NGO, volunteering, social movements and other traditional a approaches to politics: when there is the attempt to be universal, to shadow the individual, there is contempt.
* The peculiar role of money (and profit) as a requirement to ensure autonomy and means for action to the individual. 
* Discuss individuality and the value of building a network: on the one hand, networks helps in putting projects through, on the other, it could be a way to rescue the idea of citizenship that was lost according to Arendt's claims (link to Bellah's individualism).

== Debate: crowd funding initiatives, the private and the public

_Approx: 2 pages_


* How their idea autonomy is linked to an ideal of building a better world in a very personal, subjective, individual, non-expansive and local way (how it is egocentric, but not egoistic; it values the individual to the extent that the idea of _let's change the world_ is a representation of an unacceptable violence against the individuality).
* The bright side: politics as action, not as contemplation (Arendt), and the possibility of a public realm, of of a different kind of awareness towards social ties (also related to Arendt's claims)
* The dark side: Weber, his hunch on the charismatic authority (the risks of trusting the charisma, the individual visions and dreams, as an escape from bureaucratic modern – and rather inefficient – institutions), and what Weber could not testify: the emergence of National Socialism (which, interestingly, was the starting point to Arendt's thought).

== References

Arendt, H. (1973[1963]). _On Revolution_. Bungay: Penguin.

Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.

Weber, M. (1976). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.
