= 1. Introduction
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:toc:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_2^nd^ year PhD student in sociology, University of Essex_

****

*Outline*

. Start with June 2013, protests going on in Brazil and a friend, pretty much engage in “disruptive innovation” lifestyle and entrepreneurship decided not to take part: if he cared so much about making a better world (at least for him), why he was ignoring the manifestation?
. Hypothesis: new form of politics, outside the mainstream parties, social movements, elections etc.
. Why crowdfunding?
.. Social entrepreneurship, freelancing, and other alternatives were too _isolated_
.. Crowdfunding (as well as these other options) had a strong reliance on people around them, on the weak and strong ties (a relationship that seemed more important than the already important networks play in the standard job market)
.. Dewey and the role of technology when it comes to democracy
.. Utopian and dystopian approaches connecting technological revolution to social change (maybe consider Pinch and Bijker's study on bikes, 1984)
.. Reinforce that the point is mostly political (more than technological).
.. If there is something social besides that, it is the indicators of a revised version of the _spirit of capitalism_ incarnated by a new lifestyle that considers money more as a process than as a thing.
****
