= Introduction
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
We are a lot of people, doing a lot. +
We are people that got together to transform and occupy public spaces, +
To propose new education models, +
And to rethink the laws of the country. +
We care for the environment, +
We have measured the magnetic field of the Earth, +
And reconnected science and society. +
Together we search for the truth of the facts and forgotten truths. +
We render the invisible ones visible. +
We fight for women empowerment and for a freer sexuality. +
We promote change and bring back traditional cultures. +
We are tireless innovators, +
Who intensely celebrate Carnival, +
And overcome any barrier to create. +
Collectively we have already organized meetings, theatre plays, songs, books, games, hundreds of movies, and comic books -- a lot of comic books. +
We are tracing a path of more independence, proximity, honesty and transparency to turn ideas into action. +
And this is only the beginning. +
In 4 years more than 1500 projects were brought to life, +
Millions of Reais were donated by 200 thousand people to carry out these initiatives.footnote:[Brazilian Real is the official Brazilian currency, usually called Real (singular) or Reais (plural).] +
And then I ask you: what if we were 1 million? +
(Catarse 2015c)footnote:[All translations of non-English quotations are my own, unless indicated otherwise.]

Catarse is the biggest Brazilian crowd funding platform and these verses were recited in a commemorative video that was posted on YouTube once the platform reached 200,000 users. A crowd funding platform, simply put, is a website in which users can do two things: on the one hand, some users, creators, can propose projects together with an ideal target for funding;  on the other hand, other users and supporters, can donate money to contribute to the success of these projects. When celebrating the 200,00 users' landmark, Catarse affirmed that roughly 10 million dollars had already changed hands from supporters to projects creators through their platform.

The numbers might not be too impressive when compared to the big international players -- for instance, the same year that Catarse celebrated the 200,000th user Kickstarter, the biggest crowd funding platform in existence, had already managed to gather 3.5 billion dollars for projects (Kickstarter 2015).footnote:[The "largest" is read over the news without an objective measure or comparison with other platforms (e.g. Canadian Press, 2013). In spite of that I could not find a platform annual report with more users, pledges collected or projects than Kickstarter among the main players in the market.] In spite of this difference in terms of the magnitude of the enterprise, the tone used to celebrate this sort of achievement is very similar among a multitude of crowd funding platforms -- Catarse and Kickstarter included, and from a sociological perspective, these verses (referenced above) are very rich.

Within the personal and welcoming tone granted by the first-person in the plural, together with the enthusiasm of the narrator, there are intriguing hints about social values, political positions and world views. There is a clear trace of civic engagement in the appreciation of public spaces, of law-making and of new educational approaches. There are ideas usually linked to left-wing politics, such as environmentalism and feminism. In addition, there are very specific and practical approaches to life, as in the hands-on culture of makers and in communities that praise a variety of forms of art. Nevertheless, these crowd funding platforms are still organized as for-profit organizations and many project creators are looking for profit, thus no one can assume all projects have a charitable basis. There is an arguably unexpected combination of elements typically related to the public and also to the private spheres.

Even when projects -- and sometimes whole platforms -- are targeting charity, there are political elements in this mixture of those spheres, as in the case of medical care:

[quote]
YouCaring has helped its users raise more than $900m since 2011 and its momentum is building, with roughly $400m coming in over the past year. The company says close to half of its 350,000 active campaigns are related to healthcare and the fastest-growing category is fundraisers for cancer (Financial Times, 2018, quotes in US dollars).

Platforms such as YouCaring and GoFundMe are dedicated to all sorts of charity crowd funding, and still the category of projects that boost their figures is that of medical campaigns. On the one hand, money changes hands only in the private sphere, from private donors to private individuals in need. On the other hand, it would be extremely naïve to discard the role of national policies in this case: the lack of a public healthcare system in the US probably has something to do with this rapid growth, and also the growth _per se_ might be read as a political statement about the government's failure to provide health support to its citizens -- after all, 60% of Americans believe it is the government's responsibility to offer universal healthcare as a basic human right (Pew Research 2017). In fact, GoFundMe's initial idea was to help people asking for donations for their holidays and weddings; nowadays the platform calls itself "the world's no.1 site for medical, illness & healing fundraising" (Financial Times, 2018).

To add yet another layer to the politics intertwined within crowd funding -- even in its charity branch -- the GoFundMe CEO clearly stated that they fight the "monopoly of traditional charities." In his words:

[quote]
This notion of democratising campaigning is when the light bulb went off in my mind. I said, "Wait a minute. This is the disruption. This is the transformation." (Financial Times 2018).

The Financial Times article is written by Barney Jopson, US _policy_ correspondent -- emphasis added.

'''

In June 2013 Brazil was going through a very intense political moment. In the middle of a  "lavish spending on World Cup soccer stadiums" (New York Times 2013) all over the country, the mayor of São Paulo announced a 0.20 Brazilian Reais (less than 0.10 US dollars) was raised in public-transit fare. In response, a social movement called _The Free Fare Movement_ went to the streets in protest but the initiative was severely punished with police brutality. These apparently local issues triggered a national reaction: in the next days, protests took place all over the country, mobilizing millions of Brazilians. These events have not passed unnoticed by international media. At their apex, for instance, they were at the front page and at within an editorial of the June 21st edition of _The New York Times_. One week later, by June 28th, the protests were featured on another front page in the same newspaper.footnote:[See New York Times 2013, Romero and Neuman 2013, and Romero 2013, respectively.]

One of the catchphrases heard everywhere was: "it's not just about 20 cents." In other words, people were not pulled onto the streets by the public-transit fare cause, neither by the excessive use of police force alone: these were merely the trigger to demonstrations based on the rather unpopular priorities of government expenditure at the time, that is to say, a lot of public money allocated to hosting a World Cup, while basic rights such as education and healthcare were left unattended and in a precarious situation (New York Times 2013). In sum, there was a lot of unvoiced public dissatisfaction and the events in São Paulo were not relevant _per se_, but the subsequent outrage was used to finally express this political climate:

[quote]
Across the nation, protesters keep taking to the streets by the thousands, venting their anger at a broad range of politicians and problems, including high taxes and deplorable public services. But a special ire has been reserved for Congress and its penchant for sheltering dozens of generously paid legislators who have been charged -- and sometimes even convicted -- of crimes like money laundering, bribery, drug trafficking, kidnapping and murder (Romero 2013).

The popular uprising was supported by massive participation in the street, accompanied by trending social media. National and international news outlets covered the numerous demonstrations. The political pressure at place was emerging from a plural, non-partisan, and spontaneous movement. The hope to democratically build a strong republic was getting a boost in Brazil.

In spite of that, Daniel, a young Brazilian entrepreneur, decided not to take part in any of these protests. He has founded different projects in the last couple of years. One of them is called _Nós.vc_, a crowd funding platform focused on education, gathering resources to making meaningful meetings happen, allowing a multitude of users to learn and share any kinds of skills. Another project he has founded is called _Estaleiro Liberdade_, a learning space focused on self-knowledge and entrepreneurship, "but in a pirate way" -- as he would put it himself. He is extremely dissatisfied with the education system, the government as an institution, and the traditional idea of a professional career. None of these institutions, according to Daniel, has offered him the kind of freedom and lifestyle he is looking for. He is not earning an income as the founder of _Nós.vc_, and _Estaleiro Liberdade_ largely operates in a pay-as-you-want scheme (they are transparent about the costs, and participants decide how much to contribute to keep the space running). Still, he makes a living out of these two projects: there is a tiny profit margin in _Estaleiro Liberdade_ and he is constantly sharing the skills he knows the best through his own platform, _Nós.vc_. He also has a couple of successful projects funded through Catarse.

Daniel's choices are clearly politically and socially motivated: he does not seem to be a typical private individual merely focused on making ends meet. Arguably, he is looking for new ways to relate to others -- this attempt at new forms of relationship might be social _per se_, but beyond that, it is also politically motivated (since he claims the government and the market does not facilitate his lifestyle). However, despite his reservations about the government, he did not feel compelled to join the biggest anti-government public demonstrations in Brazil’s recent history. Instead he stayed at home.

Both _Estaleiro Liberdade_ and _Nós.vc_ were founded in close relationship with _Engage_, a software house whose slogan was _Power to the people_. In fact, Daniel's ambitions were pretty much aligned with this idea: to offer ordinary people ways to autonomously trace their own paths, usually leading to a lifestyle that involves making a living from their own passions and projects -- an objective strongly based on the idea of individual freedom and autonomy. Among _Engage's_ main projects there were many open-source platforms and different  innovative and engaging projects focused on civic actions in Brazil and Latin America, ideas they understand to have a positive social impact. _Catarse_ is actually a spin-off of _Engage_.

Arguably, Daniel and _Engage_ are dedicating much of their time to creating something different, not only for them, but for their community. They have imprecise but optimistic ideas about common goods, about community and society, and they are engaged in making something different within these realms. And still the popular, non-partisan, non-violent protests calling into question the very core of Brazilian national politics were not interesting for Daniel -- who has opted to follow the demonstrations from his friends' online and offline testimonies.

Labeling Daniel as apolitical may be incoherent with the ideas he puts forward through his projects. However, politics as protesting, as political parties, and even as voting has completely lost its appeal for him. He would say he does not care about politics, that he only minds his own business -- but interestingly, for him that would mean making his projects as open and inclusive as possible, almost a public or common good. He does not consider himself or his projects as charity or philanthropy. On the contrary, in a candid and frank way, he is open and unapologetic about the fact that his projects are geared towards making profit. Nevertheless he left a promising career as an art director in a mainstream advertisement agency to run these projects -- a career that would probably offer him a bigger paycheck at the end of the day. His new idea of success has changed, and his idea of success now includes the individual freedom and autonomy that the corporate world could not offer him. Besides that, helping others to change their own lifestyles is part of his new idea of success.

'''

Daniel's story is typical of the crowd funding community: people who are engaged in these projects and used to these platforms are not ignoring the social and political aspects of the society in which they live. They have a specific social and political awareness that pushes them into activities to fund specific lifestyles, and at the same time, that pushes them away from traditional politics and fund raising (such as government programs, NGOs, charity or private corporate sponsoring). As Felipe, an interviewee I introduce below,footnote:[See chapter 5, _Autonomy_.] has described to me, crowd funding allows people to act on the margins of these institutions, calling social values into question while risking something slightly new. At the surface this movement suggests an interesting tension: people might be trying to forge a space _outside_ politics to, namely, _be_ political. Yet this space they are creating is not traditionally a public sphere as one might expect from political arenas -- on the contrary, the economic side of this space is skewed towards profiting from people's private ventures.

This particular clash of interests, when people try to be political outside of politics, is the main focus of this research, in particular, the notion that in doing so, they end up blurring the boundaries of what we know as the public and private spheres. This is not a critique of this blurring, but a sociological analysis of what is achieved and what is left behind within these strategies. Also, this inquiry is about the peculiar relation among the crowd funding community and the incumbent institutions they are avoiding: government and political parties, but at times also corporations and the financial market. This avoidance is put forward without a confrontation: crowd funding is more focused on pragmatic goals, such as funding and bootstrapping projects, than it is in an active critique of these institutions. The hands-on culture mentioned above seems to drive this community to put forward proposals -- that is to say, this research is about how people afford to have a voice not against the government, the state and maybe even the market -- but in spite of them. In sum, the focus within this thesis is on the political and social aspects that emerge when incumbent institutions are called into question in the public and in the private spheres -- and the role of crowd funding within this development.

As stated in the previous paragraphs, one of the main sources of data for this work is in-depth qualitative interviews. The next chapter reflects on the methodological aspects of this choice and how they have contributed to and shaped this research. Following on from that, I examine the theoretical background to this research.

In terms of theory, Arendt’s (1968, 1973, 1985, 1998 and 2005) work is given a prominent role due to her reflections on the premises of the private and public sphere and also as an aid to understanding tensions between civic society and governments in modern democracies. Her theory allows us to consider these topics and question the barriers of funding the anew in contemporary societies (as Arendt herself would put it), that is to say, to question structural and institutional settings that -- intentionally or not -- end up making it difficult for ordinary people to act and have impact on our society. This theoretical framework helps in the understanding of tensions and critiques put forward by the crowd funding community, especially when it comes to governments and corporations. Together with Arendt, the literature review also draws on scholars and theories close to the idea of antipolitics (such as Mouffe 2005 and Schedler 1997), as well as other critiques of modern states (such as Wolin  1983 and 2004, and Bellah 2008). Their work enables consideration of   crowd funding claims not only in terms of the possibility or impossibility of funding new innovations, but also to better position it in a more complex and nuanced spectrum for political action. This literature review chapter discusses, then, the limits and potentialities of crowd funding as a form of politics. Finally, in order to ponder the role of technology in this scenario, the chapter also refers to the STS (science, technology and society) literature in order to properly frame the debate on politics and digital culture, mainly bringing in studies related to open source and open knowledge societies, drawing on Pålmas’s (2006) work.

The third chapter, _Re-signifying money_ draws on my interviews with participants to explore different aspects of the crowd funding community. Their relationship to money is put in the spotlight for several reasons: to begin, the mechanism at the core of these platforms allows them to (at least partially) opt out of traditional ways of making a living  (and also of traditional ways to donate money). However, this is only the surface. Underneath this behavior lies a series of social and political statements re-signifying more traditional views on several aspects of modern life such as jobs, career, social security and life goals. This very specific world view that results from these re-significations is a rich resource not only to understand their relation to money, but to understand how they see their surroundings and how they face their overarching aspirations in life.

The fourth chapter, _Autonomy_, further probes the aspirations of  the crowd funding community. From their relation to the world (set in the previous chapter) the objective is a thick description concerning the critiques they put forward by re-signifying money. In a certain way, this chapter describes precisely which institutions are being called into question, and by which means. Once more the hands-on characteristic plays a prominent role: this action of calling into question is handled in a very pragmatic attempt to set an environment for action outside the institutions they disavow -- and not confronting or clearly criticizing these institutions. In other words, this chapter is about how the crowd funding community tries to hack the market and the government, and how the trust in the social network (not merely the online ones) is a crucial one for them to achieve what they call autonomy.

Next, in chapter 5, _A new realm to empower action_, the tensions between crowd funding and incumbent institutions is further analyzed: the descriptive tone fades out to make room for a more analytical reflection on how political theory might reinforce the potential for politics within crowd funding. The idea is to understand the emphasis they put on action, and how their take on it can relate to Arendt's concept of action (1998). In some sense, even if arguably emerging in the private realm, there are important political aspects in the supposedly public realm forged by crowd funding communities. The reflection is not precisely _if_ crowd funding is political -- I assume it is -- but the theoretical take on _how_ they afford this political voice.

Finally, in chapter 6, _Isolation, silence and absence_, I investigate the potential of putting forward an alternative to mainstream political and economic institutions -- or, more precisely, if the present status of crowd funding might be a contender in this scenario. This analysis emphasizes antipolitical aspects of the realm created by the crowd funding communities and also debates the strategic ways they handle cognitive aspects of this institutional tension. In sum, my informants' cathartic optimism about the political aspects of crowd funding depends upon a series of dissonances in order to defend the neutrality and autonomous aspects of the realm they are putting forward -- that is to say, there are more complex social relationships that they, deliberately or not, tend to veil in order to stand as a new and inherently genuine alternative to incumbent institutions.
