= Methodology and Literature Review
Eduardo Gonçalves
:revremark: Draft of chapter to the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy.
:revdate: August 2015
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

Two recurrent topics on contemporary political theory are extremely relevant in order to address the possibility of politics through crowd funding. One of them comes from the antipolitics stream (Schedler 1997), and it argues that many institutions and practices that were supposed to be political are, in fact, mitigating politics as such. According to this critique, a spread dissatisfaction with the means and ends of these institutions and practices has lead to a general disavowal of politics _per se_; politics, therefore, starts to be taken with a skeptical and cynical tone, starts to be perceived as corrosive to society. By these means, it ceases to be the realm for conflicting interests, passions and desires. Furthermore, politics ends up either as technical matter relegated to specialists, or as a rational pursue for consensus — both alternatives sustained by a strong belief in a impartial set of procedures (Mouffe 2005). The other topic, subsequently, is one way to approach this contemporary political condition through the critique of rationalization and of utilitarianism (Weber 1976, Collins 1986), as well as through the underneath and widespread individualism and disconnectedness related to these ideals (Bellah _et al_ 2008). This set of critiques argues that in the last centuries traditional republican and religious morals have been fading out in terms of relevance, being replaced by a culture that fosters the pursue of self-interest in a way that does not create, neither sustain, social ties (Bellah _et al_ 2008, Graeber 2011).

Crowd funding is a phenomenon that has been engaging millions of people, online and offline. The primary hypothesis of this research emerge as a reflection upon this fact, that is to say, supposing that this engagement might be a source of politics. The assumption is that there is a multitude of projects out there to be funded, and that the mechanism that requires public support (in the form of monetary contributions) in order to select which ones will actually be executed is a mechanism that could be read as politics: there are conflicting projects and interests, there is a public deciding what really happens in society.

To afford a proper sociological investigation of this hypothesis, the idea is to explore the nature of the social relations and world views created by crowd funding, specially in comparison to traditional approaches to conventional politics (organized parties and social movements, institutionalized procedures such as voting) and to entrepreneurship (activities primarily focused on establishing highly profitable businesses). 

Initially what needs to be covered is the specific nature of crowd funding initiatives. A naive approach would see it merely as making things happen since projects are proposed and backed by ordinary people. Alternatively, a dystopian point of view would claim that it is all about business, since most of crowd funding platforms emerged as startups (and, indeed, a couple of them actually became millionaire companies). Yet a more utopian and libertarian standpoint could label it as a political discourse and action, highlighting how crowd funding confronts incumbent institutions as the primary (and, sometimes, unique) sources for funding. Surely these are only a few stereotyped possibilities, but the objective is to understand how different ideals and purposes are balanced within crowd funding projects and communities.

Assuming that there is room for discussing politics in this scenario, the next step is to understand the specificities of that politics. By focusing on how people involved in crowd funding see themselves in the world, in relation to others in society, it is possible to understand how their world views impact the semantics of their actions and practices. In other words, by taking that into account, it is possible to depart from what they deliberatively do and expect (or, perhaps, what they deliberatively omit and disavow) and compare to more academic approaches to political action in order to understand the peculiarities of such politics. 

Finally, assuming some understating of crowd funding and of its politics, the next task is to grasp the kind of society being pursued by these communities. If they are political in some sense, this research investigates how they are concealing competing interests, what means and ends are at sake in this entrepreneurship, and how all that relates to contemporary political theory.

The areas briefly described above guided this research. They refer to three research questions that could be summarized as: What is the focus of crowd funding? What are the specificities of crowd funding politics? How does crowd funding relate to political and economical institutions? This chapter draws a theoretical and methodological framework in order to address these questions. It starts by discussing the data collection strategy, its justifications and limitations. Next it presents a literature review on political theory, mainly discussing the mitigation of politics. Finally a concise discussion on the overarching theoretical questions that makes the empirical data collection and analysis relevant as a source for a grounded sociological, that is to say, to support sociological description of crowd funding in relation to contemporary politics.

== Methodology

According to Beer and Burrows (2007), the appropriate way to address the dynamics of internet is to opt for descriptive accounts, reconceptualizing spheres that are being redefined by online communities and tools. For them, the challenge is “to construct more complete and differentiated descriptions of what is happening” and to give an account of “who is involved, and the practices entailed, in order to inform and enrich new concepts or reworkings of our theoretical staples.”

Moreover when dealing with social research on science and technology there are two commonplace stereotypes: either social reality is determined by the technological artifacts (leaving no agency for humans) or technological artifacts are fully interpreted and signified by human agency (considering technological artifacts merely subjects of human action). The idea is to be in-between these extremes, an approach that “allows us to understand technological innovation and social changes as an interplay between solid technological capacities, and the social situation of their development and use” (Allen-Robertson 2013:12). In other words the idea is to be sensible to the possibilities and limitations brought to life by technological artifacts, but also to the appropriations and semantics developed through their usage.footnote:[This approach is also based in what Hutchby (2001) called _affordances_.]

That said it worth it to reinforce that the technology put forward by crowd funding platforms is not at the core of this research as much as the possibilities opened by it. The technology is relevant as far as it can be used to understand changes in the dynamic of society. As the next chapters will explore, that is the case, for example, of the way a certain group of social actors perceives others around them (other people, other institutions) depending on how they embrace intellectual property (proprietary or free and open source code). But that is also the case of more broad social impacts, such as the resurgence of the idea of the _prosumer_ due to new communication possibilities and cheaper alternatives for production (Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010)footnote:[It is considered a resurgence since the first use of the term _prosumer_, in the 1980s, was proposed by a futurologist (Toffler 1980), and only a couple of decades later the idea could be embraced as a rooted academic perspective.] — on the one hand, internet decentralized communication, that is to say, in a different way from newspaper, radios and TV centralized broadcasting, the internet allows every one involved to receive _and_ send information over the network; on the other hand, a couple of decades ago, in order to spread a text one has written, one would need to spend a huge amount of paper, ink and oil to print it and distribute it; nowadays, with internet access, it is basically free to write and publish a multitude of texts online. This changes in the way people produce and consume (simultaneously) is seen as a way through which capitalism itself (and other power institutions around it) can be affected by the novelties proposed by internet users (Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010). 

Therefore the focus of this research is on the world views of people involved in crowd funding. The idea underneath this methodological choice considers that social actors’ conceptual framework can limit and determinate action or, yet, can completely reconceptualize it (Ragin 1994). Moreover, “at any particular time, one should be prepared to find that governing concepts can, and often do, lag behind the behavioral requirements of the case” (Ragin 1994:92). Having in mind the aforementioned defense for a descriptive procedure when it comes to internet (Beer & Burrow 2007), together with this focus on world views, the main source of data for this research was semi-structured interviews. The interviewees were people engaged with crowd funding, and the focus of the interaction was on their ‘governing concepts’ when it came to their engagement with crowd funding.

In some sense, this strategy is similar to Weber’s (1976) and Boltanski & Chiapello’s (2011) argument that underlying motivations and deterrents were fundamental to understand how society is organized. If this research differs from their historical and document data collection, it is similar to Weber’s assumption that psychological sanctions originated within some protestant sects had unforeseen behavioral impacts on society, and it is similar to Boltanski & Chiapello’s assumption that a certain ideology can justify not only the engagement with capitalism, but always explain different and changing engagement throughout time. Given the emerging aspect of crowd funding, it is not possible to follow the document data collection (Land and Taylor 2014), therefore the option for interactions with people involved in crowd funding through semi-structure interviews justifies itself once more.

Through these means the interviews offered a primary source for the construction of a grounded theory approach. One problem of grounded theory is the risk of ending up with theory that is strictly tied to the field where the data was collected (Blaikie 2010). When it comes to this specific research, this problem is flagrant when a more quantitative approach might fail to prove the relevance of crowd funding. For instance, the amount of money changing hands, the market value of platforms, the number of people involved, or the greatness of the projects being executed would probably be weak measures to compare this new communities with incumbent institutions such as corporations and governments. However given the contemporaneity of crowd funding and the potential of internet communities to impact incumbent institutions (Allen-Robertson 2013, Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010), this grounded theory can be relevant to comprehend a wider movement that includes different branches of internet groups, such as crowdsourcing, sharing and collaborative economy, social networks, free and open source software and hardware, makers movements, hacker and open spaces and so on. Mapping the moral grounds (Weber 1976, Boltanski & Chiapello 2011), the conceptual framework (Ragin 1994) of crowd funding is a way to pinpoint ideals that might be relevant for many of this new communities (for example, as Taylor & Land 2014). As Bellah _et al_ (2008:275) highlighted, approaches like that are able to grasp rich sociological insights:

[quote]
focus [on political economy] makes sense in that government and the corporations are the most powerful structures in our society and affect everything else, including our culture and our character. But as an exclusive concern, such a focus is severely limited. Structures are not unchanging. They are frequently altered by social movements, which grow out of, and also influence, changes in consciousness, climates of opinion, and culture. We have followed Tocqueville and other classical social theorists in focusing on the mores — the ‘habits of the heart’ … It make sense to study the mores not because they are powerful — in the short run, at least, power belongs to the political and economic structures — but for two other reasons. A study of the mores gives us insight into the state of society, its coherence, and its long-term viability. Secondly, it is in the sphere of the mores, and the climates of opinion they express, that we are apt to discern incipient changes of vision — those new flights of the social imagination that may indicate where society is heading.

Considering the approach described above, the interviewing method offered in-depth qualitative understanding of the world views related to the emergence of the crowd funding phenomenon. The analysis of this material enabled inferences on the social, cultural, economic, moral and political foundations of these world views. The aim is to assess interviewees’ point of view, and to inquiry about how they locate themselves into society — or, in other words, to grasp their own world views, values, references and aspirations.

'''

There are a vast number of crowd funding platforms. Although Wikipedia (2015) lists roughly 100 active platforms,footnote:[Roughly one year ago, in May 2014, this same Wikipedia article listed only 60 crowd funding platforms.] this is clearly an incomplete list. For example, Catarse is a Brazilian platform built in an open source license,footnote:[Catarse (2015a) operates under MIT License.] that is to say, anyone is free to use their source code to build a new platform. According to Catarse’s wiki (2015b) there are 15 active platforms based on their source code (roughly half of them operating in other countries than Brazil, such as USA, Canada, Denmark and Argentina). Most of them (including Catarse itself) are not included in the Wikipedia’s list. This added a new layer for reflection upon the interviews of this research: how to grasp the variety of platforms (and of different purposes behind them) during this qualitative investigation. In order to get in touch with as many world views as possible, two main strategies were adopted during the sampling.

First, the interviews were held with three different profiles: platforms founders and staff, people submitting projects to these platforms (project creators), and people backing these projects (project supporters). For each founder or staff interviewed, the idea was to interview two project creators and three project supporters -- therefore, targeting the point of views from different roles within the crowd funding community. Surely these numbers are rough guidelines, not clearcut objectives, specially because every founder is also a project supporter (and, most of the times, a project creator), and yet most project creators usually have backed some project before. But having in mind these three profiles allowed the analysis to move from an arguably idealistic point of view of founders (whether it is business or common good based, just to mention two opposing examples), to more pragmatic standpoints for project supporters.

Second, there are three main characteristics of crowd funding platforms taken into account. This characteristics are related to how platforms design the business model for the projects they host, to the way the they deal with their own intellectual property, and to the curatorial layer defined by their terms of service. Details about four platforms are helpful in clarifying and illustrating these characteristics, they are Indiegogo, the first crowd funding platform, and one of the most widely known; Kickstarter, the so called largest crowd funding platform in the world;footnote:[The “largest” is read over the news without an objective measure or comparison with other platforms (e.g. Canadian Press, 2013). Anyhow Kickstarter’s numbers are eye-catching: more than 1.75 billion dollars pledged, more than 86 thousand projects funded, more than 8.75 million backers, i.e. people who supported at least one project (Kickstarter 2015).] Catarse, the first one launched open source; and Patreon, the first one to offer what is called a recurring funding scheme.footnote:[In terms of the kind of projects hosted by these platforms, all of them are very open. Even if they were created with some kind of public or projects in mind (for example, Indiegogo and Kickstarter primarily focus was on creative projects, while Patreon and Catarse focuses are on artistic and cultural projects), they are open enough to host projects that vary considerably: from movies and music, to software and hardware technology development, including sports, civic actions, political organization, and education. Hence the three characteristics taken into account are more internal to the organization of the platforms than to the contents visible online for the ordinary user.]

When it comes to their business models, the basic difference between Indiegogo, Kickstarter and Catarse is that the first one charges a higher fee (a percentage over the total value pledged), but the project creator can collect the money pledged even if the target is not reached — this model is known as ‘keep-it-all.’ On the other hand, the other two charge a smaller fee (also a percentage over the total value pledged), but if the project target is not reached, all the money returns to the backers and no fees are collected (nor any funds is passed to the project creator) — this model is known as ‘all-or-nothing.’ crowd funding campaigns under this model arguably engage not only the project creator, but also its supporters, whose role of spreading the word about the campaign is crucial to make the funds be collected. Finally, Patreon inaugurated the idea of a ‘recurring’ contribution: instead of backing a specific project, usually with a higher amount (for example, 20 dollars for the recording of a music album), the idea is to contribute with smaller amounts to an ongoing project (for example, 1 dollar per month for a certain musician, or 1 dollar each time this musician uploads a new song). If the ‘all-or-nothing’ scheme is said to foster engagement, this engagement tends to fade away once the project is finished (in the example, when the recorded album is delivered). Alternatively, the ‘recurrent’ method would extend the engagement between project creators and its supporters for an undefined period of time, but arguably it would be a less intense engagement as it lacks a specific deadline and target.

Catarse is the only platform among this group that is open source; the other three platforms are based on proprietary software. Interestingly there was a huge difficulty in reaching someone from Kickstarter to be interviewed for this research. Also several interviewees (from other platforms) told the very same story: Kickstarter do not talk with ‘copycats,’ as one interviewee told me. If Indiegogo, Kickstarter and Patreon, by protecting their code, suggest that they operate as more traditional business, protecting the engine of their companies and looking for loyal customers (project creators as well as users to support them),footnote:[Regarding Kickstarter, it could be added that they eventually get involved in judicial cases around patents for their ‘all-or-nothing’ model (Purewal 2011).] Catarse departs from an heterodox market philosophy, offering its source code openly, and with no apparent fear that some ‘copycat’ would represent a risk to them. In fact, Catarse developers seem to express the complete opposite idea: they are actually helping other developers using their source code (they are very active in their collaborative channels: their open repository and their open mail list dedicated to developers). To be sure the idea is not to deterministically affirm that embracing proprietary software is tied with a less friendly behavior regarding others in the field of crowd funding, but to take that into account. For instance, one of Catarse’s main programmers told me that there were some conversations between Catarse and Indiegogo in which they considered to merge Indiegogo’s code base with Catarse’s one. Even if the merging had never occurred, different stories might point in different directions, requiring the analysis to pay attention to specific combination of characteristics that can afford to explain these different behaviors.

Finally, considering the curation, Kickstarter, Catarse and Patreon tend to have a more prominent curatorial layer: people from the platform tend to work together with the project creators. The focus is on refining the content to be published, in order to assure that the project has good chances of being funded — that is the difference between having a thicket or a garden, as some interviewees put. Indiegogo, in that sense, is more open and users can submit projects without the explicit platform ‘seal of approval.’

In that sense, these three characterises — intellectual property (proprietary or open source software), business model (keep-it-all, all-or-nothing, recurrent), and content policy (a more open, or a more controlling curatorial layer) — are key points to link world views sustained by interviewees to the core concepts in case: contemporary conditions for politics, individualism and disconnectedness. Moreover, this initial group of platforms covered crowd funding in different countries. Patreon is mostly an American platform, while Catarse is a Brazilian one (in the sense of the geographical disptribution of project creators and supporters). Kickstarter was launched officially in the USA, the UK and Canada (Canadian Press 2013). And Indiegogo (2012) hosts projects from all over the world, working with five different currencies (American Dollars, Canadian Dollars, Australian Dollars, Euros and British Pounds). However, in addition to these four platforms, several other have their own peculiarities, offering different points of view that should be considered for the sake of this research — for example Cinese, a Brazilian crowd funding platform focused on meaningful meetings supporting non-traditional learning; Beacon, a platform for independent writers and journalists to get recurrent contributions and, for the readers, to have access to all their archive; or MedStartr, a platform based on Catarse’s source code, built exclusively to crowd fund medical projects (their lead is to promote medical innovation according to ordinary people interests). By focusing on a sample distribution that cover different combinations regarding profiles, aspects regarding intellectual property, business model and content policy, and the variety of niche initiatives, this research covered different backgrounds, cultures, demographics and geographic differences. So far the research counts with 11 interviews with mostly project creators and platform founders and staff. These people are from the UK, Brazil, Romania and China, and the platforms involved are Benfeitoria, Catarse, Cinese, Crowdcube, Indiegogo and Unlock. 

The sampling and data collection phase started with the publicly available channels to contact the platforms: email, contact form, social media etc. I reached them, explained the purpose of the research and asked for their participation. If they opt to cooperate, I asked for interviews, and asked if they can help me in recruiting more people, for example among their users (project creators and supporters). For some of the platforms, I had no other access to them — this was the case of Indiegogo, Crowdcube and Kickstarter, for example. When they refused to cooperate, the alternative was look for other crowd funding platforms in order to keep a good sample distribution according the variables discussed in the last paragraphs. However, for the other platforms, I already had better access to data — this is the case of Catarse, Cinese, and Unlock. For these platforms I have acquaintances, or acquaintances of acquaintances, that can put me in touch with founders, current or former staff, project creators and project supporters. There is the risk of bias, but it can be minimized since these contacts were the trigger to a snowball process, that is to say, I have not interviewed them but asked them to suggest someone else to be interviewed, making me reach people outside my regular network, and expanding the sample from there.footnote:[It is worth it to disclosure that I have projects crowd funded through Catarse, and Nós.vc (a platform similar to Cinese), and I have also contirbuted to projects on Catarse, Nós.vc, Indiegogo, Kickstarter and Patreon. Contacts from these projects will not be considered for this research in order to minimize bias.]

The focus of the semi-structured interviews was on the point of view of the interviewees about society, business, politics and economics — especially (but not restricted to) when it comes to crowd funding. In order to better grasp these views, the first part of interviews was not focused on crowd funding, but on the interviewees’ perceptions of themselves within society — that is to say, how they position themselves facing a given cultural, political and economic context. Yet this initial part will covered the interviewee’s aspirations and ideals when it comes to the social context. The idea was to adopt a funnel-shape questioning technique, narrowing down the subject (namely, crowd funding) towards the final part of the interaction. By these means, the participants might get to the specific subject spontaneously. Consequently my role as an interviewer was to conduct the interviewee in such direction only if certain topics have not emerged in a more spontaneous way (Kvale and Brinkmann 2009). Therefore it was expected that the first part of the interviews would cover aspects such as the interviewees’ general opinion on government, on corporations, on civic organizations, on political views and attitudes. The intention was to get these aspects linked to their personal initiatives without intervention, that is, without stimulating the interviewee to relate them to crowd funding. This technique was employed to avoid the risk of making the interviewee stick to one or other concept just because the interviewer mentioned it — and not because it was already part of the interviewee’s own point of view (Kvale and Brinkmann 2009).

Next the interviews varied among different profiles of interviewees. The following step of the funnel is the interviewees’ relationship with crowd funding. For founders and managers, the conversation focused on how they situate their business within society, their choice to found, or work for, a crowd funding enterprise. For project creators, the exploration shifted towards the reasons why they opt to count on a crowd funding instead of other funding possibilities. For supporters, the focus was on what has driven them to take part in crowd funding campaigns.

Finally, after objectively introducing the topic of crowd funding, the last block of the interview addressed interviewees’ opinions and views about crowd funding in a broader sense. The investigation inquired about what interviewees expect from crowd funding, how they position it within ‘traditional’ social spheres (such as business, politics or culture), and yet verified the possibility of a more aspirational approach. By these means, the objective was to grasp their collective and individual expectations related to crowd funding mechanisms.

The interviews were held in person or remotely (using telephone, VoIP or video conference). The context lacking in the remote interviews were not considered to represent a relevant loss of data in this particular case as (among other reasons) most of our participants are expected to be well articulated and used to express themselves in public (they will be entrepreneurs who found and manage online platforms, or they put their own projects online to public, or yet they voluntarily engage with these projects, spreading the word about it). The content of the interviews were recorded (according to the consent of the interviewee), transcribed and analyzed. It was up to the interviewee to be anonymized or not. Next the data went through a process of coding and condensation of meaning. The idea is to condensate the most relevant units, and use the coding to categorize these bits of information. This qualitative analysis technique leaded to a grounded theory approach (Kvale and Brinkmann 2009).  Additionally this content was triangulated with other sources, with data collected from the platforms themselves and from the interviewees’ online public profiles. This process allowed a contextual interpretation of the meaning of these units of information, as well as validation of the content of the interviews — another basis for a grounded theory approach (Kvale and Brinkmann 2009).

== Literature Review

The focus of this research, identifying and describing possibilities of politics within crowd funding communities, is based on critiques from political theory towards the possibility of political action and engagement in contemporary society. Most of this framework discusses the nineteenth and twentieth centuries modern world, specially when it comes to sociological, political and philosophical implications. On the one hand, these oeuvres are reflecting upon the outcomes of the eighteenth century revolutions in the USA and in France (for example, Tocqueville 1986 or Arendt 1973); on the other, they are rethinking these results in the light of the terror spread during the two World Wars, and of the democratic states emerged thereafter (for example, Bellah _et al_ 2008 or Arendt 1998). A commonplace in such literature is to acknowledge the achievements of the Enlightenment, but, at the same time, to reinforce how it failed in completely putting forward some of the ideals that were at its core. For example Arendt (1973) did not deny the importance of modern political institutions such as parties and elections; they opened the political career for people from the lower classes, and yet the notion of forming an elite through the party replaced the old elites based on birth or wealth. However she also emphasized that the party framework is less meaningful in providing a government _by people_ than in recruiting _from people_ an elite to govern them. In other words, the central question here is not the democratic (or republican) institutions _per se_, but the tangible possibility of political action for ordinary people.

The first part of this section draws the framework of these critiques towards modern state, its democratic assumptions and failures. Next it discusses the contemporary debate built around this sort of flaws, bringing in discussions around the arguably decline of political engagement in the turn of the twenty-first century. Finally it sets some challenges in thinking political action in contemporary society. The idea is to grasp the difficulties in using traditional approaches to political institutions to understand how political action can be reinvented within nowadays tensions and conditions.

=== Modern institutions and its discontents

In terms of politics most of the ancient world was traditionally based on a distinction between the public and the private, two separated realms in which people would pursue different objectives through different means. However this scenario has changed considerably during the last centuries:

[quote]
the emergence of the social realm, which is neither private nor public, strictly speaking, is a relatively new phenomenon whose origin coincide with the emergence of modern age and which found its political form in the nation-state (Arendt 1998:28).

Therefore, there is something essentially modern in the constitution of nation-states, and this essence relates to one of the core distinctions within political theory, namely, the public and the private realm. Therefore following the emergence of the institutions created during that transition is a way to understand how this new political framework was forged. Moreover this history sets the background for the subsequent criticism regarding the successes and failures of the modern project for politics.

The division between public and private was forged in ancient Greece, when one should keep the pursue of private interests to the boundaries of the household, the core place for one’s private life. That is to say that only citizens who have provided enough for them and their families were allowed to participate in the public life. This requirement was based on the role expected of this citizen when engaged with politics:

[quote]
Private wealth, therefore, became a condition for admission in public life not because its owner was engaged in accumulating it but, on the contrary, because it assured with reasonable certainty that its owner would not have to engage in providing for himself the means of use and consumption and was free for public activity. Public life, obviously, was possible only after much more urgent needs of life itself had been taken care of (Arendt 1998:64-5). 

As Arendt put, modern age gave birth to the social realm which is neither public nor private — and, as a consequence, dislocated considerably what was understood as public. While private life was characterized by providing the household through labor, and while the public realm was the place for action and speech, the social has taken the political space from the public, printing on it important differences: now government acts as a gigantic housekeeping organization, looking for provision for a whole nation; that is to say, labor, once relegated to the private life, now is not only allowed but placed at the center of political life. For Arendt (1998:28-9) the dividing line between the household and politics

[quote]
is entirely blurred, because we see the body of peoples and political communities in the image of a family whose everyday affairs have to be taken care of by a gigantic, nation-wide administration of housekeeping. The scientific thought that corresponds to this development is no longer political science but ‘political economy’ or ‘social economy’ or _Volkswirtschaft_, all of which indicate a kind of ‘collective house keeping;’ the collective of families economically organized into the facsimile of one super-human family is what we call ‘society,’ and its political form of organization is called ‘nation’ (Arendt 1998:28-9).footnote:[Arendt does not justify the use of the German term _Volkswirtschaft_ in this passage. Arguably it has no direct translation into English. Nonetheless it refers to a kind of economics driven by the nation’s needs, the needs expressed by its households as well as by the private and public sector; in some languages, as in Dutch or Latin for example, its translation is similar to _national economy_ (_algemene economie_ and _oeconomia nationalis_ respectively).] 

This transformation, however, was not abrupt. Bellah _et al_ (2008) argue that in the beginning of modern age two strands were sort of references, both for public and private issues: a biblical and a republican strand. The first one is exemplified by the role of religion in the formation of American tradition:

[quote]
The Puritans were not uninterested in material prosperity and were prone when it came, unfortunately, to take it as a sign of God’s approval. Yet their fundamental criterion of success was not material wealth but the creation of a community in which a genuinely ethical and spiritual life could be lived (Bellah _et al_ 2008:28-9).
 
Alternatively, the republican strand is illustrated by the standpoint of one of the Founding Fathers, Thomas Jefferson:

[quote]
In general, Jefferson favored freedom of the person from arbitrary state action and freedom of the press from any form of censorship. Yet he also believed that the best defense of freedom was an educated people actively participating in government. The notion of a formal freedom that would simply allow people to do what they pleased — for example, solely to make money — was as unpalatable to Jefferson (Bellah _et al_ 2008:31).

In both cases, Bellah _et al_ (2008:31) reinforced, individual “freedom only took on its real meaning in a certain kind of society with a certain form of life;” without that moral principles, freedom would lead to social corrosion and tyranny. However, later on the nineteenth century, both strands were challenged by two sorts of individualism that withdrew this large social context. On the one hand, utilitarian individualism focused on individual self-improvement, reflecting the liberal belief that if each member of a group pursues her or his own interest, the whole community would testify the emergence of social good. In this case, the idea of interests was basically set by another Founding Father, Benjamin Franklin, whose views were determinant in framing the capitalist motivation for work and accumulation (Weber 1976, Bellah _et al_ 2008). On the other hand, expressive individualism claimed no interest for material accomplishments, but in an individual and subjective pursue for experience through life. The richness of life would be achieved nurturing the self with luxury, sensuality, intellectual and all sort of experiences one could feel to understand and express oneself in contact with nature, with the universe as a whole. Individual freedom is the norm and a disavowal for social conventions marks the tone of this branch of individualism. Therefore, if the earlier strands do not contrast individualism and the public common life, these sorts of individualism do it by conceiving a sort of self-contained individual:

[quote]
What is at issue is not simply whether self-contained individuals might withdraw from the public sphere to pursue purely private ends, but whether such individuals are capable of sustaining either a public _or_ a private life. If this is the danger, perhaps only the civic and biblical forms of individualism — forms that see the individual in relation to a larger whole, a community and a tradition — are capable of sustaining genuine individuality and nurturing both public and private life (Bellah _et al_ 2008:143, emphasis in original).

Hence this discussion — involving different realms (such as the public, private and, arguably, the social) and what is allowed in each one of them — works as a theoretical starting point to look at contemporary political institutions. Having in mind the individualistic and self-determined world views emerged in the last centuries, and going back to Arendt’s critiques, the idea is to understand if the world imagined during the Enlightenment is conceivable nowadays — in other words, if the rupture between individual and civic society brought up by individualism is compatible with the virtues expected from governing bodies. Traditionally the answer to questions like that are pointing in a negative direction. One element of arguments in such direction is calling into question the effectiveness of free markets in granting freedom to ordinary people, that is to say, to ask if rationalized economic sphere would promote the social good (or, on the contrary, if it would prevent ordinary people to act politically):

[quote]
The market idea, as Adam Smith proudly announced, banishes the authority of persons; it is a system of exchange which is legitimate only as a system. The closest we come to an image of control, reassurance, or guidance is the ‘invisible hand’ which assures fairness. But the invisible hand is also an abstraction; it is attached to the body of no single human being (Sennett 1980:43).footnote:[Interestingly Sennett (1980:44) also argues that this economic behavior compromised not only ordinary people’s potential for action, but the core freedom they were suppose to inherit from such a society: “The market ideology promised the consummation of individual freedom of action. The market in practice was anti-individualistic. It displaced masses of peasants from their land, whatever their own desires to remain. At the moments when the supply of labor in cities exceeded the demand for labor, there was in fact no labor market. If an employee did not like wages an employer paid, he could go starve; there were plenty of others to take his place … The market system of the last century, rather, made the concepts of community and individual ambivalent, and ambivalent in a peculiar way. No specific human being, no human agent, could be held accountable for disturbances in these realms.”]

But this critique is extended to the public realm as well. For Arendt (1998:68) society has become “an organization of property-owners who, instead of claiming access to the public realm because of their wealth, demanded protection from it for the accumulation of more wealth” (Arendt 1998:68) — that is to say, the logic of the instrumental individualism has taken down the biblical and the republican strands. This transformation has to be understood according to the specific ways through which modern societies have developed into representative democracies, a constant struggle between emphasizing the anew claimed by the American and French revolutions on the one hand, and, on the other hand, the will to consolidate the ideal of freedom in a stable institution. For instance Jefferson had a particular standpoint among the Founding Fathers regarding the role of the constitution in this process: in ideological terms, he wanted the constitution to be strong enough to guarantee that no hostilities will take place in the political realm, nonetheless, in order to reinforce the founding anew, this same constitution should also be flexible enough to be revised from times to times. In practical terms, the effects of these thoughts can be seen in the representative democracy model and in its well established ways to participate in the political realm: elections, elected officials, senators, representatives, parties and voters (Arendt 1973).

Perhaps this new institutional scenario has failed in fulfilling its original intents. Critiques appeared as early as the 1920s, for example, when Dewey (1954:118) affirmed that

[quote]
skepticism regarding the efficacy of voting is openly expressed, not only in theories of intellectuals, but in the words of lowbrow masses: ‘What difference does it make whether I vote or not? Things go on just the same anyway. My vote never changed anything.’

In other words, this scheme was unable to extend the perception of participation from representatives to represented: when it comes to politics, citizens seem to be disinterested and this fact can be found not only “among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage,” but also “shows up regularly among the favored and highly placed” (Jaffe 1997:78). Sniderman and Bullock’s (2004) idea of ‘menu dependence’ involves a very similar description of how ordinary people have a very discrete participation in politics. According to them, “citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties” (2004:338). The idea is that citizens are not free to compose their own menu of political choices, but only allowed to pick up one from a menu pre-established by parties and political elites. Yet Wolin’s (2004:428) analysis of contemporary politics adds another layer to this branch of critiques: for him “in both, the political and the economic context, contract appears as the essential condition of power”. In other words as the market economy operates in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state operates in a way that concentrates the (political) power in the hands of the political elite (Wolin 2004). By themselves the functioning of these both institutions are expanding the gap between rich and poor, rulers and ruled. And, as Arendt (1973:253) suggested, underneath this wave of critiques towards modern society, there is the displacement of the public realm itself and also the dilemma Jefferson had in mind:

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of being republicans and of acting as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens. 

This two-folded movement of degradation of the public and of inflation of the private has granted the space for corporations to extrapolate their private bounds and act within the public realm. Political decisions — already distant from ordinary people — gradually started to take into account a logic that does not pertain to the public realm, namely the logic of the market economy (Wollin 2004). 

In spite of advancing in many aspects, this process of modernization had a devastating side-effect for politics: by limiting the space for political action it consolidate the public realm as a place for private affairs. In Arendt’s (1998:46) words, “the character of the public realm must change in accordance with the activities admitted into it, but to a large extent the activity itself changes its own nature too.” The type of skills and activities held within these spaces were also impacted by these transformations. The importance given to labor and provision (formerly banished from the political), and to speech and action (formerly the core of political activity) also assume a different balance. Labor and wealth accumulation made sense as far as the household provisions required them. Excelling in speech and public action in politics was a public virtue which the whole body of citizens would benefit of. Interestingly within the modern social realm labor was introduced to the political space and, at the same time, speech and action was dislocated to the private:

[quote]
while we have become excellent in the laboring we perform in public, our capacity for action and speech has lost much of its former quality since the rise of the social realm banished these into the sphere of the intimate and the private (Arendt 1998:48). 

From that perspective it is possible to comprehend the lack of interest and, arguably, trust in politics; also it is possible to address the endless interest in making money. Both approaches overlap aspects in many critiques towards representative democracy, basically because they change what happens in the political realm. These changes regarding the political institutions of the modern age ended up nurturing two kind of critiques. On the one hand, there is a very optimist approach to the rationalization and individualization processes. This stream, known as post-political, claims that the possible flaws in political institutions are to be overcome with further development of these same institutions, according to same values that brought them to life. In other words, more emphasis on the rationalization would solve this possible flaws. Habermas (1992, 2005), for instance, argue that there are two instances in society — System and Lifeworld — holding different rationalities. The rationalized and instrumentalized one hosts the market and the political institutions, and this is the realm in which the individual interests are transcended in the name of anonymous demands, realized by means of instrumental, strategic action. This kind of rationality is increasingly detaching itself from the social structures, taking the shape of autonomous organizations that only communicates through mediums such as money and power — or, to put it differently, only operates in a way that holds no commitment to other norms or values. Economic and administrative rationalities are the main themes here. The other instance, the communicative one, would be the place were individuals would rationally pursue a deliberation, rationally agreeing on the functioning of the instrumental institutions. Hence, there is no value judgment between instrumental or communicative rationality; rather it is conjectured that each rationality is restricted to its own domain. The problem — part of Habermas’s patology of modernity — is that communicative rationality have been colonized by the instrumental logic. The author defends the need for reconnecting these spheres to avoid the ‘colonization,’ keeping the differentiation and autonomy of these realms. He states that only then communicative rationality will have space to collectively elaborate the ultimate aims for the social good.

Habermas’s diagnosis describes a scenario similar to the one addressed in the last section, but his agenda calls for a rational approach to argumentation, consensus and deliberation. Against this rational approach, some authors defend that rationalization would lead to a more anti-political environment. Instead of using rationality to promote consensus in a post-political space, the idea is that this process would mitigate the very nature of politics:

[quote]
Instead of trying to design the institution which, through supposedly ‘impartial’ procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant ‘agonistic’ public sphere of contestation where different hegemonic political projects can be confronted (Mouffe 2005:3).

Therefore, the lack of trust and interest in the political institutions can be described as antipolitical by (at least) two different arguments: in the one hand, it contributes to the mitigation of the public realm, which is suppressed by a self-regulated private one, the market (Schedler 1997); or, alternatively, whatever remains of the public realm starts to operate according to a logic inherent to the private sphere — what Schedler (1997) calls an inverted Habermasian colonization. To be sure, Wolin (2004:588) highlights that both — state and market — are appropriating the methods of one another: “it is not that the state and the corporations have become partners; in the process, each has began to mimic functions historically identified with the other.” According to him, corporations’ move includes being in charge or funding health care, education and other welfare affairs; in parallel, governments’ move includes applying profits logic, notions of efficiency and management, to buoy its own actions.

The point here is not to demonize corporations or governments, but to reinforce how this conjecture affects political life. Bellat _et al_ (2008:259) argued that, starting by the end of the nineteenth-century, a populist agenda “sought to expand government power over economic life for the common good” in an attempt to fight the power of well established private corporations — this establishment was creating, managing and maintaining public institutions such as universities, museums, churches, orchestras and hospitals. The argument of this populist agenda was that ordinary people should be able to decide for themselves, and economic power was taking this political power from them:

[quote]
If the Establishment vision rearticulated important aspects of the republican ideal of common good in the turn-of-the-century America, Populism was the great democratizer, insisting on the incompleteness of a republic that excluded any of its members from full citizenship (Bellah _et al_ 2008:259).

In sum, neither the rational deliberation and consensus possibility, nor the agonistic one, are hosted in nowadays political institutions. Instead, there is a disavowal for politics as such, since it is generally perceived as inefficient, misguided and corrupt. However this scenario may not eliminate politics as such, and people might find alternative ways to engage in the public and civic life (for example, as in Bennett _et al_ 2013) — and that is the topic of the next section.

=== Action and politics

The last section described what can be understood as a crisis in the contemporary political arena. The idea that voting would grant a accountable authority for the rulers and, at the same time, the sense of participation and freedom to the ruled, is, at maximum, an unfinished project (Sennett 1980). If ordinary people do not trust politics, the notion of participation and civic engagement, together with the ideals of a representative government, are called into question. However according to (Bennett _et al_ 2013:537) in spite of the predictions that this skepticism would move people away from politics, what was found was a ‘skeptical engagement’ with two different possibilities: “a context of mistrust and cynicism might discourage or pervert political participation, on the one hand, or spur innovation, on the other.” Their ethnographic fieldwork showed how civic organizations in Providence (RI, USA) strategically deny the label of ‘politics’ in order to better engage with and to promote change within the local community. Interestingly, this former objective included activities that traditionally are considered very political, such as joining the city council, or lobbying with the local politicians and government.

What the research done by Bennett _et al_ (2013) suggests is that if politics is disinteresting for people, there is still space for actions focusing on the public realm, on the common good. In other words, the political institutions might not be the instance people with a civic mindset are looking for. Wellmer (2000) commenting on Arendt’s political theory suggests that possibilities created within a given political context might be the core of a public and active sphere:

[quote]
Arendt’s concern is not with justice but with (political) freedom. Hence, her brand of universalism is neither the normative universalism of human rights nor the inherent universalism of the modern economy. Rather, it is the universalism of a human _possibility_: the possibility of creating, in the midst of contingent historical circumstances, a space of public freedom (Wellmer 200:229, emphasis in original).
ive. 

In order to comprehend this proposal it is needed to go back to Arendt’s (1998:7) framework. For her ‘action’ is the essence of the humankind, in opposition to ‘labor’ (meeting the basic needs related “to the biological process of human body”) and ‘work’ (“the unnaturalness of human existence,” including the manufacture of tools to make labor easier and more productive for example). Action, in that sense, is held between humans “without the intermediary of things or matter.” Yet the relation between action and politics is crucial to her argument:

[quote]
Action … corresponds to the human condition of plurality, to the fact that men … live on earth and inhabit the world. While all aspects of human condition are somehow related to politics, this plurality is specifically the condition — not only the _conditio sine qua non_, but the _conditio per quam_ — of all political life … Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live” (Arendt 1998:7-8).

If work and labor are held out of necessity, action is held as a virtue. Arendt (1998) differentiated immortality (typically found in Gods) from eternity (something that can be achieved by humans). As merely mortals, human beings can attempt to last for ever, not as immortals, but through actions, through worldliness deeds:

[quote]
no matter how concerned a thinker may be with eternity, the moment he sits down to write down his thoughts he cease to be concerned primarily with eternity and shift his attention to leaving some trace of them. He has entered the _vita activa_ and chosen its way to performance and potential immortality (Arendt 1998:20).

Her concept of _vita activa_ is similar to Aristotelian _bios politikos_ and to Augustinian _vita negotiosa_ or _vita actuosa_, that is to say, “a life devoted to public-political matters” (Arendt 1998:12). Therefore Arendt subscribe to the stream that defends that pursuing private interests, pursuing basic requirements for survival should not be allowed in the public sphere. Alternatively, this realm should deal with the plurality, with different interests and opinions, and with the dispute about the means to maintain this arena active. In this approach, freedom assumes a distinguished importance:

[quote]
action and politics, among all the capabilities of human life, are the only things of which we could not even conceive without at least assuming that freedom exists … Without [freedom] political life as such would be meaningless. The _raison d’être_ of politics is freedom, and its field of experience is action (Arendt 1968:146).

When it comes to this plurality and to the freedom to hold different passions in a public sphere, Mouffe (2005:9) criticized Arendt arguing that this image of the public sphere depends too much on a consensus seeking logic:

[quote]
Some theorists such as Hannah Arendt envisage the political as a space of freedom and public deliberation, while others see it as a space of power, conflict and antagonism. My understanding of ‘the political’ clearly belongs to the second perspective.

For Mouffe politics should not be focused on deliberations on the common good, but on people’s desires, emotions and fantasies, and that is why she argues for the agnonistic view: politics presupose plurality and difference, and this difference should not be flatten by any kind of political process or institution.

However, both in Arendt and in Mouffe, there is a primordial call when in comes to the public life: the need to support the emergence and maintenance of plurality throughout democratic societies. Both scholars, therefore, tend to agree that when the political institutions are closed to the creation of anew (as Jefferson feared), when political institutions are leaded by extremely rational and instrumental logic (as Mouffe criticized, since it minimize the importance of more subjective and human impulses; or as Arendt also criticized, since it narrows the boundaries between action, work and labor), and when political institutions do not favor the emergence of a public sphere for ordinary people (as Arendt argued), the democratic spirit is mitigated as a result. In opposition to this scenario, when there is a public sphere able to host different opinions, when this public sphere is not limited to a political economy materially nurturing the big family called nation, when this public sphere is putting forward people’s dreams, and, most important, when this public sphere is forging political institutions that would fit the anew, then the democratic process is successful. 

Hence, when it comes to looking for the possibility of politics in crowd funding, the focus of this research is more on exploring the potential of crowd funding as a public sphere: a multitude of communities proposing different projects and actions that are based on individual or group aspirations; a multitude that depends on a minimum public approval to happen (and here lies a presumption that this could be understood as a profit seeking activity some times, but also as a civic engaging activity from times to times); and a multitude that, through technology, is able to gather enough supporters as well as enough funds to empower ordinary people to hold political claims and actions (in the sense that they operate outside the traditional political institutions, that is to say, governments and, in some cases, corporations).

'''

The importance of technology, even if relevant, is not the core of the research. However the idea that technology is crucial in promoting democracy is not new:

[quote]
‘Invent the printing press and democracy is inevitable.’ Add to this: Invent the railway, the telegraph, mass manufacture and concentration of population in urban centers, and some form of democratic government is, humanly speaking, inevitable (Dewey 1954:110).

This idea also appears in other scholars from the last century, such as in Tarde’s (1989) _L'opinion et la foule_ from 1901, in which he defends the role of the printing and newspaper in civilizing the public; or the importance Blumer (1939) put in electronic broadcasting on setting the tone of a free society (even if he recognized the possibility of mass manipulation). Instead of subscribing to a more utopian perspective (such as Dewey’s quote above), or a dystopian one (such as the centralization inferred by the manipulation pointed out by Blumer), the idea is to be sensible to how technology contributes to the construction of reality, and, therefore, how important aspects of political institution might assume different semantics — for example, new forms political leadership (Margetts _et al_ 2013) or new social meanings for money (Dodd 2014). 

The hypothesis used to frame the research questions is based on an arguably libertarian hacker ethic, typical in many of the novelties emerging from the digital world. This ethic “represent[s] a liberal critique within liberalism” since “hackers question one central pillar of liberal jurisprudence, intellectual property, by reformulating ideals from another one, free speech” — consequently revealing “the fault line between two cherished sets of liberal principle” (Coleman 2013). Surely this hypothesis is closer to an utopian stream, what does not impede the research to call this assumption into question, specially when these more autonomous initiatives (normally from free and open source niches) start to collide with incumbent institutions, triggering a set of negotiations between the challengers, the establishment and the public (Allen-Robertson 2013). The idea is to investigate the possibility of crowd funding to challenge incumbent institutions such as government and corporations, or, in other words, the possibility of identifying elements of a public sphere in the crowd funding communities. The perspective of people engaged in crowd funding is the key to understand their motivations, and that justifies the epistemological approach on world views: at this early stage, it is more relevant to understand their political aspirations and expectations than tangible and measurable social changes.

Considering the medium and long term scenario, it is understood that, on the one hand, the focus on autonomy nurtured by the hacker ethics seems to foster an atomized private realm, relegating the decisions about what should and should not be done to the sphere of individuals' moral and judgements. On the other hand, the mechanisms embraced by crowd funding (from the functioning of the online campaigns to the dependence on strong and weak ties) require these decisions to be held by a greater audience: without supporters, no project becomes reality, without collaboration within the network (open source included), no action is possible. Their idea is linked to the building of an alternative space in a very personal, subjective, individual, non-expansive and local way.

Recurring once more to the extremes of an utopian and a dystopian perspective, the brightest possibility would be to understand that politics can be about empowering action — and not only about contemplation and deliberation, as in ancient Greece (Arendt 1998). Therefore opening more possibilities for ordinary people to act in public could be a form of (re)engagement in politics. In that scenario individualistic antipolitics would be declined in as so far as each idea, project or proposal would still be dependent on a plurality in order to become action (even if this plurality can be considerably smaller than the majority usually required by formal democracies; and surely that suggests that plurality would emerge stronger than consensus or deliberation). The intrinsic need of financial and community support to execute projects through crowd funding creates a kind of gatekeeper for individual moral and judgements, and, at the same time, create free and open spaces for the most different sort of dreams and initiatives.

However political theory also suggests a dark possibility. For instance Weber’s (1986) late writings argue that his disavowal of the bureaucratic administration could be overcome by a charismatic leader — a concept usually employed as opposed to tradition and legal forms of authority in Weberian theory. He argued that a leader was necessary to revitalize the arguably inefficient German government. The problem was the “completely outmoded system of management by notables” (Weber 1986:130), that is to say, old professional and bureaucratic politicians, which was actually preventing the brightest intellectuals from engaging in politics. Charisma would be the basis of this new political leader, who should be strong enough to dissolve the parliament if needed. Explicitly he argued for a strong president, empowered through election, as an alternative to challenge the power of the parliament, the outmoded system.

Weber passed away in 1920 and between his and Arendt’s oeuvre Germany testified the emergence of the National Socialist dictatorship. A leader in fact was granted these powers in 1934 by almost 90% of the voters. A leader that would merge the role of president and chancellor, dissolve the parliament and opposing parties and interrupt all efforts to revive democracy in Germany after the Great War. Ironically a leader whose terror is one of the most important inspirations for Arendt’s first writings on politics and philosophy. In sum, politics based on individual impulses, even if controlled by formal institutions, can destroy democracy and politics.

This sort of theoretical questions are the background of this research: the more practical predisposition of people engaged with crowd funding, as well as their justifications in terms of world views, are at the foreground of this research; at the same time the background is set by these overarching dilemmas of political theory, such as freedom, political action and what constitutes a democratic and active public sphere.

== References

[references]
* Allen-Robertson, J. (2013). _Digital Culture Industry: A History of Digital Distribution_. Basingstoke and New York: Palgrave Macmilllan.
* Arendt, H. (1968). _Between Past and Future_. New York: Penguin. 
* Arendt, H. (1973[1963]). _On Revolution_. Bungay: Penguin. 
* Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.
* Beer, D. and Burrows, R. (2007). Sociology And, Of and In Web 2.0: Some Initial Considerations. _Sociological Research Online_, 12(5).
* Bellah, R., Madsen, R., Sullivan, W. M., Swidler, A. andTipton, S. M. (2008[1985]). _Habits of the Heat: Individualism and Commitment in American Life_. Berkeley: University of California Press.
* Bennett, E. A., Cordner, A., Klein, P. T. and Baiocchi, G. (2013). Disavowing Politics: Civic Engagement in an Era of Political Skepticism. _American Journal of Sociology_, 119(2). Pp. 518-548.
* Blaikie, N. (2010). _Designing Social Research: The Logic of Anticipation_. 2nd ed. Cambridge: Polity Press.
* Blumer, H. (1939). Collective Behavior. In Park, R. E. (ed.). _An Outline of the Principles of Sociology_. New York: Barnes & Noble. Pp. 219-80.
* Boltanski, L. and Chiapello, E. (2011[1999]). _Le Nouvel Esprit du Capitalisme_. Paris: Gallimard.
* Canadian Press, The (2013). Kickstarter crowd funding Site Officially Launches in Canada: Canadian Entry Held Up by Red Tape, Financial Regulations, Co-Founder Says. Available at: http://www.cbc.ca/news/business/kickstarter-crowd funding-site-officially-launches-in-canada-1.1703774 [Accessed: 20 Jan. 2014].
* Catarse (2015a). Catarse. Available at: http://github.com/catarse/catarse [Accessed: 17 May 2015].
* Catarse (2015b). Sites Using Catarse. Available at: http://github.com/catarse/catarse/wiki/Sites-using-Catarse [Accessed: 17 May 2015].
* Coleman, E. G. (2013). _Coding Freedom: The Ethics and Aesthetics of Hacking_ [digital book]. Princeton: Princeton University Press.
* Collins, R. (1986). _Weberian Sociological Theory_. Cambridge: Cambridge University Press.
* Dewey, J. (1954[1927]). _The Public and its Problems_. Athens: Swallow Press.
* Dodd, N (2014). _The Social Life of Money. Princeton: Princeton University Press.
* Graeber, D. (2011). _Debt: The First 5,000 Years_. New York: Melville House.
* Habermas, J. (1992[1985]). _The Theory of Communicative Action: Reason and the Rationalization of Society, Vol. I_. Boston: Beacon.
* Habermas, J. (2005[1985]). _The Theory of Communicative Action: Lifeworld and System — A Critique of Functionalist Reason, Vol. II_. Boston: Beacon.
* Hutchby, I. (2001). Technologies, Texts and Affordances. _Sociology_, 35. Pp. 441-56.
* Indiegogo (2012). International Campaigns. Available at: http://support.indiegogo.com/entries/20882543-international-campaigns [Accessed: 20 Jan. 2014].
* Jaffe, E. (1997). Our Own Invisible Hand: Antipolitics as an American Given. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 57-90.
* Kvale, S. and Brinkmann, S. (2009). _Interviews. Learning the Craft of Qualitative Research Interviewing_. London: Sage.
* Kickstarter (2015). Kickstarter Stats. Available at: https://www.kickstarter.com/help/stats [Accessed: 30 May. 2015].
* Margetts, H., John, P., Hale, S. and Reissfelder, S. (2013). Leadership without Leaders? Starters and Followers in Online Collective Action. _Political Studies_, 63(2). Pp. 278-99.
* Mouffe, C. (2005). _On the Political_. London and New York: Routledge.
* Purewal, S. (2011). Kickstarter Faces Patent Suit Over Funding Idea. _PCWorld_. Available at: http://www.pcworld.com/article/241160/kickstarter_faces_patent_suit_over_funding_idea.html [Accessed: 20 Jan. 2014].
* Ragin, C. (1994). _Constructing Social Research: The Unity and Diversity of Method_. Thousands Oaks, London and New Delhi: Pine Forge Press.
* Ritzer, G. (2015). The “New” World of Prosumption: Evolution, “Return of the Same,” or Revolution? _Sociological Forum_, 30(1). Pp. 1-17.
* Ritzer, G. (2014). Prosumption: Evolution, Revolution, or Eternal Return of the Same? _Journal of Consumer Culture_, 14(1). Pp. 3-24.
* Ritzer, G. and N. Jurgenson (2010). Production, Consumption, Prosumption: The Nature of Capitalism in the Age of the Digital ‘Prosumer.’ _Journal of Consumer Culture_, 10(1). Pp 13-36.
* Schedler, A. (1997). Introduction: Antipolitics — Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 1-20.
* Sennett, R. (1980). _Authority_. New York: Alfred A, Knopf.
* Sniderman, P. M. and Bullock, J. (2004). A Consistency Theory of Public Opinion and Political Choice: The Hypothesis of Men Dependence. In Saris, W. E. and Sniderman, P. M. (eds.). _Studies in Public Opinion: Attitudes, Nonattitudes, Measurement Error, and Change_. Princeton and Oxford: Princeton University Press. Pp. 337-357.
* Tarde, G. (1989[1901])._L'opinion et la Foule_. Paris: Presses Universitaires de France.
* Taylor, S. and Land, C. (2014). The Good Old Days Yet to Come: Postalgic times for the new spirit of capitalism. _Management & Organizational History_, 9(2). Pp 202-219.
* Tocqueville, A. (1961[1840]). _De la démocratie en Amérique, II_. Paris: Gallimard.
* Tocqueville, A. (1986[1835]). _De la démocratie en Amérique, I_. Paris: Gallimard.
* Toffler, A. (1980). _The Third Wave_. New York: Morrow.
* Weber, M. (1976[1900] ). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.
* Weber, M. (1986[1919]). The Reich President. _Social Research_, 53(1). Pp. 125-132.
* Wellmer, A. (2000). Arendt on revolution. In Villa, D. _The Cambridge Companion to Hannah Arendt_. Cambridge: Cambridge University Press. Pp. 220-241.
* Wikipedia (2015). Comparison of crowd funding Services. Available at: http://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services [Accessed: 17 May 2015].
* Wolin, S. (2004). _Politics and Vision: Continuity and Innovation inWestern Political Thought_. Princeton and Oxford: Princeton University Press.
