= Methodology
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

Crowd funding is a phenomenon that has been engaging millions of people, online and offline. Kickstarter, one of the biggest platforms among them, raised its supporter base (backers, as they call users that contribute to campaigns) from almost 9 million to more than 14 million in the last 3 years - a crowd big enough to back almost 140 thousand projects with a total sum surpassing 3.5 billion US dollars (Kickstarter 2015, Kickstarter 2018). Indiegogo, another platform, had 2.5 million active users in 2015 alone (Indiegogo 2018). The numbers and the pace they have grown in the last few years are described below (also from Kickstarter 2015, Kickstarter 2018):

[%header, cols="<,^,^,^", format=csv]
.Kickstarter figures from 2015 to early 2018
|===
Total,Jan./2015,Jan./2018,%
USD pledged,1.75B,3.47B,98%
Backers,8.8M,14.1M,60%
Projects funded,86K,137K,59%
|===

In addition to these statistics, this community appears to be proud of the quality of its achievements. In its 2016 balance Kickstarter highlights the achievements of some projects funded through the platforms: during that year the London Design Museum added 6 Kickstart funded pieces to its permanent collection; 19 Kickstarter funded films made their way to Tribeca Film Festival; 4 Kickstarter funded projects received a Grammy nominations and another three were listed by Times magazine in their inventions of the year list.

In the face of such a meaningful increase, the primary hypothesis of this research is an invitation for an in-depth reflection about the social implications of this expansion. The assumption is that there is a multitude of projects out there to be funded and a very specific mechanism to decide which one of them will be funded. The decisions derived from this mechanism are primarily based on monetary contributions. However, in the background lies a complex network of social ties that can foster or deter contributions: the range of users' social networks, the ability or appeal to attract spontaneous media, the alignment to popular or niche causes and so on. Therefore, underneath this funding scheme, crowd funding also operates as a platform for political agency: there are conflicting projects and interests and there is also a public deciding what really happens with each of these possibilities. Crowd funding is clearly a form of political engagement, but the nature, scope and the implication of its legitimacy and power as a political tool is still uncertain for both adherents and external observers. My aim is to explore the social relations and world views created by crowd funding, especially in comparison to traditional approaches to conventional politics (organized parties and social movements, institutionalized procedures such as voting) and to entrepreneurship (activities primarily focused on establishing highly profitable businesses).

Initially what needs to be covered is the specific nature of crowd funding initiatives. Since projects are proposed and backed by ordinary people, a naive approach would see it merely as a way to bring ordinary ideas to life. Alternatively, a more cynical point of view would claim that it is all about business, since most crowd funding platforms emerged as startups (and, indeed, a couple of them actually became millionaire companies). Yet a more utopian and libertarian standpoint could claim it is all about  a very specific political discourse; possibly they would argue that crowd funding confronts corporations and government -- traditional institutions that usually act as sources for funding (and in some circumstances these incumbent institutions can be a unique source of funding). Perhaps these are only a few stereotypes, but the objective is to understand how different ideals and purposes are balanced within crowd funding projects and communities.

The areas briefly described above guide this research. They refer to three research questions that could be summarized as: What are the specificities, biases and limitations of crowd funding politics? How does crowd funding relate to incumbent political and economic institutions? What is the nature and the social implications of the political worldview put forward by members of the crowd funding communities? This chapter draws upon a methodological framework in order to address these questions. It begins by discussing the data collection strategy, its justifications and limitations.

== Data collection and analysis

The data collection included 26 interviews with platform founders and staff, project creators, supporters and experts. These informants are from the 8 different countries including 5 continents. This mix allowed me to investigate experiences from more than 10 different crowd funding platforms from 4 different countries. In fact, many of the interviewees have experience in more than one platform, but for the sake of simplicity, in the following table I listed only the one that was prominent in each interview. Finally, a few of them asked me to mention them by pseudonyms; in order to protect their identity I am not explicitly distinguishing them from the ones who have not asked for pseudonyms. Also, I am not using (real or fake) family names for any of my informants:

[%header, cols="<,<,<,^,<", format=csv]
.Interviewee profiles
|===
Name,Profile,Platform,Gender,Nationality
Adam,Supporter,Ulule (France),♂,France
Amanda,Creator,Catarse (Brazil),♀,Brazil
Anna,Founder,Cinese (Brazil),♀,Brazil
Brittany,Creator,GoFundMe (USA),♀,USA
Carla,Supporter,Kickstarter (USA),♀,Brazil
Chris,Expert,,♂,UK
Daniel,Founder,Unlock (Brazil),♂,Brazil
Daniel,Supporter,Benfeitoria (Brazil),♂,Brazil
Daniel,Supporter,Kickstarter (USA),♂,Germany
Emily,Founder,PeopleFundIt (UK),♀,UK
Felipe,Expert,,♂,Brazil
Felipe,Creator,Benfeitoria (Brazil),♂,Brazil
Giovana,Staff,Cinese (Brazil),♀,Brazil
Juliana,Supporter,Catarse (Brazil),♀,Brazil
Lisandro,Supporter,Kickstarter (USA),♂,Brazil
Maria,Creator,Indiegogo (USA),♀,Romania
Miguel,Founder,Catarse (Brazil),♂,Brazil
Noah,Supporter,Indiegogo (USA),♂,USA
Pedro,Creator,Catarse (Brazil),♂,Brazil
Rodrigo,Staff,Neighborly (USA),♂,USA
Sam,Expert,,♂,USA
Stephen,Expert,,♂,UK
Talita,Supporter,Kickstarter (USA),♀,Brazil
Victor,Creator,Patreon (USA),♂,Brazil
Wei,Supporter,Kickstarter (USA),♂,China
William,Founder,ProduceRun (USA),♂,Australia,USA
|===

The sampling and data collection phase began with the publicly available channels to contact individuals at crowd funding platforms: email, contact form, social media etc. I reached them, explained the purpose of the research and asked for their participation. If they opted to cooperate, then I would invite them to an interview and also utilized the method of snowball sampling (that is to say, I would ask them to suggest other people I could also reach). Usually I would try to snowball different profiles: for example, when talking to staff I would ask if they could think of a particular supporter or project creator that might accept my invitation for an interview. In spite a couple of positive responses, this strategy was not that successful: I received no replies to many emails and posts; when I did obtain a response, usually it was a typical customer support text with standardized responses. It was invariably the case that the message within these responses was that anything I would like to know about their platform was already available on their institutional web pages. The few real conversations I managed to obtain using this approach ended up in declined interviews -- and in the case of the biggest platforms, I usually read that their company discourages (or forbids) them to take part in interviews.

At this point I was required to work on a different strategy for data collection and I reverted to my personal background: I have been writing computer codes since I was a child. During my early twenties this hobby became my main professional activity for a brief period. From this experience I was already in touch with the free and open-source software community and also with groups of web developers, especially within communities guided by hacktivism (which ended up as the topic of my Master's thesis in sociology). There are a great amount of people from these civic-minded tech communities that have become involved in crowd funding, thus I consulted with previous colleagues in order to facilitate my access to informants. I could easily reach the ones I already knew and ask them for ideas, asking them who I should contact and requesting introductions. Snowballing succeeded from thereon, allowing me to collect valuable data for this research.

This access to data requires some notes in terms of positionality. Even with friendly introductions from colleagues from think tanks or working in the Silicon Valley I still had no access to some platforms I would like to have heard from -- this was the case, for example, of Indiegogo and Kickstarter. As mentioned earlier, the larger firms and platforms I approached declined to take part. The other, smaller platforms offered me great openness to talk and to contribute, utilizing the snowballing technique. This was the case, for example, of Neighborly, PeopleFundIt, Catarse, Cinese, and Unlock. I tried to avoid using any informant from my closer social network, reverting to acquaintances, not to friends, even if I was not interviewing them directly. They were entry points to the fieldwork, not informants -- in other words, in order to minimize bias I interacted with people I knew to reach people outside my regular network, expanding the sample from there.

But this does not mean the study was free of bias or limitations. Most importantly, it is appropriate to highlight that the use of qualitative methods is not intended to generalize findings but aims at a detailed and in-depth description of a specific field. In my case I was cautious to avoid extending my arguments further than my data collection allowed me to. What follows is a careful discussion based on an important share of the crowd funding community: enthusiasts that at maximum are project creators in the big players such as Kickstarter and Indiegogo, but no voice from inside these big players. Maybe Catarse is an exception as it is the biggest crowd funding platform operating in Brazil. But that just adds another layer in terms of positionality, that of my homeland: many of my previous contacts are Brazilian, and even if they have been working in many different countries, I have greater access to data in Brazil than in any other country.

Also, I have projects crowd funded through Catarse and Nós.vc and I have also contributed to projects on Catarse, Nós.vc, Indiegogo, Kickstarter and Patreon. Contacts from these projects were not considered for this research in order to minimize bias. Finally, during the research I informally monitored some social media and forums on the internet, looking for posts related to crowd funding and some interviewees (then unknown to me) I approached after reading some post or comment that they shared publicly and which mentioned crowd funding.

The focus of the semi-structured interviews was on opinions of the interviewees about society, business, politics and economics -- especially (but not restricted to) when it comes to crowd funding. In order to better grasp these views, the first part of the interviews did  not explicitly mention crowd funding but investigated interviewees' personal trajectory and identity: I asked them to introduce themselves, to tell me about what they like to do, how they make a living and other background information that allowed me to contextualize the experiences that they were about to share with me. The idea was to adopt a funnel-shaped questioning technique, narrowing down the subject (namely, crowd funding and politics) towards the final part of the interaction. By these means, informants might get to the specific subject spontaneously -- if not, the next steps of the funnel would discreetly attempt to direct the conversation in such a direction. My role as an interviewer was to guide the interviewee in such a direction only if certain topics had not emerged in a more spontaneous way (Kvale and Brinkmann 2009). At the maximum what was expected for the first part of the interviews was to have a brief idea about the interviewee's general opinion on government, corporations, civic organizations, political views and attitudes. At this point these ideas were elicited from personal stories (when someone declined a job offer from a corporation in order to work in a NGO, for example) and not mentioned explicitly. The intention was to touch upon these aspects without intervention, that is to say, without stimulating the interviewee to relate these topics to crowd funding. This technique was employed to avoid the risk of making the interviewee stick to one or other concept just because the interviewer mentioned it -- and not because it was already part of the interviewee's own point of view (Kvale and Brinkmann 2009).

The following step of the funnel is the interviewees' relationship with crowd funding; this step varied according to the informant's profile. For founders and managers, the conversation focused on how they situate their business within society, their choice to found, or work for, a crowd funding enterprise (and their motives to not work elsewhere when that was the case). For project creators, the exploration shifted towards the reasons why they opted to count on crowd funding instead of other funding possibilities. For supporters, the focus was on what had driven them to take part in crowd funding campaigns, their expectations and feeling about such experiences. Finally, with experts, I would inquire about how they ended up in their field of expertise. My experience in this block of the interviewed confirmed that the context provided by their personal background was a pretty useful interviewing technique: usually the transition to this part of the interview was seamless and spontaneous, as a sort of continuation of their life trajectory at a certain point. This was valuable in terms of the non-intervention methodology described above. Moreover, during the interview and the analysis, the personal background offered important hints to expand on informants' experiences with crowd funding.

After getting to the main subject, that is to say, after the interview had definitively shifted towards crowd funding,  the last block addressed interviewees' opinions and views about crowd funding in a broader sense. The investigation inquired about what interviewees expect from crowd funding, how they position it within more traditional social spheres (such as business, politics or culture), and yet verified the possibility of a more aspirational approach when it comes to the social context. If needed, I would more firmly conduct the conversation in a way that invited them to share with me their perceptions of themselves within society -- that is to say, how they position themselves facing a given cultural, political and economic context. By these means, the objective was to grasp their collective and individual expectations related to crowd funding mechanisms and to society in general.

The following table summarizes this funnel shaped design, moving from a more open and spontaneous conversation to a more focused and guided one:

[%header, format=csv]
.Funnel-shaped interviewing technique
|===
Stage, Objectives, Typical topics
"*1. Personal background* (more open, more spontaneity)", Contextualize and better comprehend each interviewee,"Who they are, who do they work with, what do they enjoy in their free time, educational and professional background."
*2. Crowd funding experience*, In-depth understating of their relationship with crowd funding,"How did they get involved with crowd funding, drivers & barriers they feel, how they perceive other funding alternatives."
"*3. Values, objectives & aspirations* (more focused, more guided)", "Comprehension of the core values guiding them, projection of their will in terms of social, economic, cultural and political change", "Whether they consider crowd funding political or not, what they are trying to achieve in life (and how crowd funding might or might not contribute), what are the main issues to be tackled in society (and how crowd funding relates to them)."
|===

The interviews were held in person or remotely (using telephone, VoIP or video conference) between May 2014 and December 2015. The context lacking in the remote interviews was not considered to represent a relevant loss of data in this particular case, since most people I talked to was very well articulated. In fact, this expressiveness relates to their engagement with crowd funding; after all they were either leaders and entrepreneurs who have founded and who manage online platforms, or creators putting their own projects online to public, or yet enthusiastic supporters who voluntarily engaged with these projects, spreading the word about them.

The content of the interviews were recorded (according to the consent of the interviewee), transcribed and analyzed. Next, the data went through a process of labeling and condensation of meaning. These labels (sometimes also referred as "codes" in methodological literature) and these meanings are a key aspect of qualitative content analysis: in practical terms, they "are immediate, are short, and define the action or experience described" (Kvale and Brinkman 2009:202). Labeled sentences and paragraphs were then grouped in similar topics, such as incumbent institutions, internet culture and lifestyle. Inside these groups, many subgroups emerged:

* _Incumbent institutions_: corporations, governments, NGOs and volunteering;
* _Internet culture_: crowd funding, hacker culture, online collaboration and social networks;
* _Lifestyle_: life trajectory, personal motivations and values, maker culture, relationship to money and career, freedom and autonomy, collaborative cultures, commons, communities and networks, politics, sharing economy and social entrepreneurship.

Each of these groups and subgroups were revisited later, that is to say, after I read the transcriptions and labeled their meaningful parts, I re-read every bit, not in the context of the interview, but group by group -- or, more precisely, subgroup by subgroup. This allowed me to have a better understanding of each of these categories and their meaning to my interviewees. It is worth noting that these labels emerged both from my hypothesis (that is to say, _a priori_ to data collection) and from the data collection process (that is to say, _a posteriori_, when a topic was recurrent in many interviews and I considered it relevant and created a label for it). Also, the same sentence or paragraph could hold as many labels as needed to give it the proper weight -- and that allowed me to link groups and subgroups, understating the relationship between them according to my informants' point of view.

This framework made it possible to navigate through relevant topics which emerged from the data collection, linking them and understanding how they impacted upon each other; in other words, it allowed me to create inductive clusters based on the world views of the interviewees. In addition, when part of the clusters acted as a central node connecting many different topics, this was considered a very relevant area -- that was the case in the relationship to money and autonomy, which became chapters in this thesis. That way, in Kvale and Brinkman's (2009:202) terms,

[quote]
the analysis has gradually moved from descriptive to more theoretical levels, leading to a 'saturation' of the material by coding process, when no new insights and interpretations seem to emerge from further codings.

Additionally, this content was triangulated with other sources, with data collected from the platforms themselves and from the interviewees' online public profiles. This process allowed a contextual interpretation of the meaning of these units of information, as well as validation of the content of the interviews. Validity and reliability emerged from the constant comparison and association between these different sources, offering consistency to the analysis (Golafshani 2003).

== The broad and nuanced crowd funding community

Addressing the ways through which people create and reinvent relationships using digital medias is not a trivial task. According to Beer and Burrows (2007), a powerful way to address the dynamics of the internet is to opt for descriptive accounts, reconceptualizing spheres that are being redefined by online communities and tools. For them, the challenge is "to construct more complete and differentiated descriptions of what is happening" and to give an account of "who is involved, and the practices entailed, in order to inform and enrich new concepts or reworkings of our theoretical staples."

Moreover, when dealing with social research on science and technology there are two commonplace analytical simplifications: either social reality is determined by the technological artifacts (leaving no agency for humans) or technological artifacts are fully interpreted and signified by human agency (considering technological artifacts as merely subjects of human action). The idea is to be "in-between" these extremes, an approach that "allows us to understand technological innovation and social changes as an interplay between solid technological capacities, and the social situation of their development and use" (Allen-Robertson 2013:12). In other words, the idea is to be sensitive not only to the possibilities and limitations brought to life by technological artifacts, but also to the appropriations and semantics developed through their usage.footnote:[This approach is also based in what Hutchby (2001) called _affordances_.]

That said, it is worth reinforcing that the technology put forward by crowd funding platforms is not at the core of this research as much as the possibilities opened by its usage. The technology is relevant in as far as it can be used to understand changes in the dynamics of society. As the next chapters explore, that is the case, for example, in the way a certain group of social actors perceive others around them (other people, other institutions) depending on how they embrace intellectual property (proprietary or free and open source code). But that is also the case in terms of broader social impacts, such as the resurgence of the idea of the prosumer due to new communication possibilities and cheaper alternatives for production (Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010)footnote:[It is considered a resurgence since the first use of the term _prosumer_, in the 1980s, was proposed by a futurologist (Toffler 1980), and only a couple of decades later the idea could be embraced as a rooted academic perspective.] A simplistic take on that issue could take into account merely how the mechanics of production has changed: on the one hand, the internet has decentralized communication, that is to say, in a different way from newspaper, radio and TV centralized broadcasting, in that the internet allows everyone involved to receive _and_ send information over the network; on the other hand, a couple of decades ago, in order to disseminate a text one had written, one would need to spend a huge amount on its printing and distribution. As a result, subsequent to the popularization of the internet, it is now basically free to write and publish a multitude of texts online. Technology, economy and production as a whole have changed and surely these novelties and its impacts cannot be downplayed. However, observers like Rizter suggest the social sciences has stalled at pointing out that vast change are taking place, while largely failing to explore in detail  how capitalism (as well as other power institutions around it) are reshaped by the new culture developed among the multitude of internet users (Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010).

These overarching social rearrangements are not obvious, especially when the technological and social innovations underpinning them are in their infancy. Crowd funding platforms are relatively new and in cases like that, the mindset of members of this community is a powerful indicator about what can be expected from this new social group and its potential impact upon society. Therefore, capturing the world views pushing people into these platforms is the approach of this research. The idea underlying this methodological choice considers that social actors' conceptual framework can limit and determine action or, yet, can completely re-conceptualize it (Ragin 1994). Moreover, "at any particular time, one should be prepared to find that governing concepts can, and often do, lag behind the behavioral requirements of the case" (Ragin 1994:92). The combination of the descriptive approach suggested by Beer and Burrows (2007), together with the stress on world views, paved the way to yet another methodological recourse: referring to semi-structured in-depth interviews as the main source of data collection. I held 26 interviewees with people engaged with crowd funding and throughout these interactions I could learn about how they see themselves in the world and collect relevant information about their own backgrounds. This context allowed me to comprehend their opinions, choices and values in an insightful way and it was then possible to conduct a rich sociological analysis of their 'governing concepts,' especially when it came to their engagement with crowd funding.

In some sense, this strategy is similar to Weber's (1976) and Boltanski & Chiapello's (2011) argument that underlying motivations and deterrents are fundamental to understand how society is organized. If this research differs from the historical and document data collection, it is similar to Weber's assumption that psychological sanctions that originated within some protestant sects had unforeseen behavioral impacts on society, and it is similar to Boltanski & Chiapello's assumption that a certain ideology can justify not only the engagements with capitalism, but always explain different and changing engagement throughout time. In addition to my interviews, I did consult "grey literature"  and press releases from crowd funding platforms, as well as other publicly available texts they publish on social media and blogs. 

Some scholars argue that qualitative social research might fail in achieving theoretical relevance outside the field in which data was collected.footnote:[That is, for example, a risk in referring to qualitative research and a grounded theory approach, as put by Blakie (2010). In spite of that, it is worth highlighting that the author does not discourage the employment of this methodological approaches.] However, when it comes to this specific research, a quantitative measure could be problematic. On the one hand, the amount of money changing hands, the market value of platforms, the number of people involved, or the enormity of the projects being executed would probably be weak measures to compare these new communities with incumbent institutions such as corporations and governments. On the other hand, measuring the economic impact or running surveys on people's opinions related to crowd funding would be strategies that do not interact so well with explicitly qualitative concepts such as world views and governing concepts that predate more significant social changes. Given the contemporaneity of crowd funding and the potential of internet communities to impact incumbent institutions (Allen-Robertson 2013, Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010), this qualitative approach is relevant for comprehending a wider movement that includes different branches of internet groups, such as crowdsourcing, sharing and collaborative economy, social networks, free and open source software and hardware, makers movements, hacker and open spaces and so on.

Mapping the moral grounds (Weber 1976, Boltanski & Chiapello 2011) and the conceptual framework (Ragin 1994) of crowd funding is a way to pinpoint ideals that might be relevant to many of these new communities (for example, as in Taylor & Land 2014). As Bellah _et al_ (2008:275) highlighted, approaches like that are able to grasp rich sociological insights:

[quote]
[The] focus [on political economy] makes sense in that government and the corporations are the most powerful structures in our society and affect everything else, including our culture and our character. But as an exclusive concern, such a focus is severely limited. Structures are not unchanging. They are frequently altered by social movements, which grow out of, and also influence, changes in consciousness, climates of opinion, and culture. We have followed Tocqueville and other classical social theorists in focusing on the mores -- the 'habits of the heart' … It makes sense to study the mores not because they are powerful -- in the short run, at least, power belongs to the political and economic structures -- but for two other reasons. A study of the mores gives us insight into the state of society, its coherence, and its long-term viability. Secondly, it is in the sphere of the mores, and the climates of opinion they express, that we are apt to discern incipient changes of vision -- those new flights of the social imagination that may indicate where society is heading.

Considering the approach described above, the interviewing method offered in-depth qualitative understanding of the world views related to the emergence of the crowd funding phenomenon. Furthermore, this source was considered together with a textual analysis based on the websites and materials circulated by the platforms and the community built around them. The analysis of both sources enabled inferences on the social, cultural, economic, moral and political foundations of these world views. The aim is to assess interviewees' points of view, and to inquire about how they locate themselves within society -- or, in other words, to grasp their own world views, values, references and aspirations. Finally, these findings are invaluable information to propose guidelines for a conceptual framework which takes account of the social relations between people in the crowd funding community and social institutions, a framework that ultimately helps us in understanding the social role played by and aspired to of these social actors.

Although Wikipedia (2015) lists roughly 100 active platforms,footnote:[This figure is from 2015. In May 2014 this same Wikipedia article mentioned only 60 crowd funding platforms. This is a 60% increase in platform numbers in 12 months.] this is clearly an incomplete list. For example, Catarse is a Brazilian platform built on an open source license.footnote:[Catarse (2015a) operates under MIT License.] This means anyone is free to use their source code to build a new platform. According to Catarse's wiki (2015b) there are 15 active platforms based on their source code, roughly half of them operating in countries other than Brazil (including locations such as the USA, Canada, Denmark and Argentina). Most of these platforms, including Catarse itself, are not included in Wikipedia's list. Such diversity has to be taken into account in the interview strategy for this research. During this qualitative investigation an important challenge is to grasp the variety of possible different purposes behind different platforms. To contemplate this diversity, two main strategies were adopted during the sampling in order to understand as many world views as possible.

First, the interviews were held with three different types of profile: platforms founders and staff, people submitting projects to these platforms (project creators), and people backing these projects (project supporters). For each founder or staff interviewed, the idea was to interview two project creators and three project supporters -- this would allow for having informants with differing points of views within the crowd funding community. In essence, this ratio was mostly used as a rule of thumb, not as a restrictive or normative guideline, especially because these categories overlap: most of the time a founder is also a project supporter or even a project creator; most project creators have usually backed some projects in the past, and are often still backing projects during and after their own campaigns. In spite of that, keeping these three profiles in mind allowed the analysis to move from an arguably idealistic point of view in the case of founders (whether it be business or common good based, just to mention two opposing examples), to more pragmatic standpoints from project supporters. In addition to these profiles directly involved in the crowd funding community I also spoke to experts in topics relevant to the field: scholars and entrepreneurs in areas such as sharing economy, tech startups and social impact-driven ventures.

Second, there are three main characteristics of crowd funding platforms to be considered. These characteristics relates from how platforms design their business model, to the way that they deal with their own intellectual property, and to the curatorial layer sometimes included in their service. Details about four specific platforms are helpful in clarifying and illustrating these characteristics, namely: Indiegogo, the first crowd funding platform, and one of the most widely known; Kickstarter, the so-called largest crowd funding platform in the world; Catarse, the first open source one; and Patreon, the first one to offer a recurring funding mechanism.footnote:[In terms of the kind of projects hosted by these platforms, all of them vary widely. Even if they were created with some kind of public or projects in mind (for example, Indiegogo and Kickstarter primary focus was on creative projects, while Patreon and Catarse focuses are on artistic and cultural projects), they are open enough to host projects that vary considerably: from movies and music, to software and hardware technology development, including sports, civic actions, political organization, and education. Hence the directions publicly announced might be internal guidelines and not something clearly perceived by the general public.]

When it comes to their business models, the basic difference between Indiegogo, Kickstarter and Catarse is that the first one charges a higher fee (a percentage of the total value pledged), but the project creator can collect the money pledged even if the target is not reached within a given deadline -- this model is known as 'keep-it-all.' On the other hand, the other two charge a smaller fee (also a percentage over the total value pledged), but if the project target is not reached until the deadline, all the money returns to the backers and no fees are collected (nor any funds passed to the project creator) -- this model is known as 'all-or-nothing.' Crowd funding campaigns under this model, they claim, are stronger in terms of engagement: supporters, in order to contribute to the success of the funding campaign, need to spread the word about the project if they want it to succeed. Supporters as well as creators need to work together to bring more attention to the initiative. Finally, Patreon inaugurated the idea of a 'recurring' contribution: instead of backing a specific project, usually with a higher amount (for example, 20 dollars for the recording of a music album), the idea is to contribute with smaller amounts to an ongoing project (for example, 1 dollar per month for a certain musician, or 1 dollar each time this musician shares a new song). If the 'all-or-nothing' scheme is said to foster engagement, this engagement tends to fade away once the project is finished (in the example, when the recorded album is delivered). Alternatively, the 'recurrent' method would extend the engagement between project creators and its supporters for an undefined period of time. Arguably this mechanism would risk a less intense engagement since it lacks a specific deadline and target.

Catarse is the only open source platform among them; the other three platforms are based on proprietary software. Interestingly there was a huge difficulty in reaching someone from Kickstarter to be interviewed for this research. Also, several interviewees (from other platforms) told the very same story: Kickstarter do not talk with 'copycats,' as one interviewee told me. If Indiegogo, Kickstarter and Patreon, by protecting their code, suggest that they operate as a more traditional business, protecting the engine from possible competitors,footnote:[Regarding Kickstarter, it could be added that they eventually get involved in judicial cases around patents for their 'all-or-nothing' model (Purewal 2011).] Catarse opts for a different market philosophy, offering its source code openly without any apparent fear that some 'copycat' would be a risk to them. In fact, Catarse developers seem to express the complete opposite idea: they are actually helping other developers using their source code (they are very active in their collaborative channels: their open repository and their open mail list is dedicated to developers). Certainly the idea is not to affirm that embracing proprietary software is an indicator of a less friendly behavior towards others in the field of crowd funding, however, such findings cannot pass unnoticed. In order to support the opposite idea, that is to say, in order to disfavor any relationship between proprietary software and openness to connect with other stakeholders, one of Catarse's core developers told me that there were some conversations between Catarse and Indiegogo in which they intended to merge Indiegogo's and Catarse's source code. The merging has never occurred, but the point is that different stories might point in different directions, requiring the analysis to pay attention to specific combinations of characteristics and avoiding rushing into conclusions. In summary, the point is that these categories might illuminate one aspect or another, but they are not deterministic in any sense.

Finally, considering the curatorial layer, Kickstarter, Catarse and Patreon tend to have a more prominent curatorial layer: people from the platform tend to work together with the project creators before and during the campaign. The focus is on refining the content to be published online in an attempt to make the project more likely to succeed. As some informants argued, this is the difference between having a thicket or a garden: they carefully cultivate every project, as gardeners cultivate their flowers, in order to raise the bar when it comes to the projects and campaigns. Indiegogo is more open and users can submit projects without the explicit platform 'seal of approval.'

In that sense, these three characteristics -- intellectual property (proprietary or open source software), business model (keep-it-all, all-or-nothing, recurrent), and content policy (the relevance put on the curatorial layer) -- are key points to link world views sustained by interviewees to the core concepts in case: contemporary conditions for politics, individualism and disconnectedness. Moreover, this initial group of platforms covered crowd funding in different countries. Patreon is mostly an American platform, while Catarse is a Brazilian one (in the sense of the geographical distribution of project creators and supporters). Kickstarter was launched officially in the USA, the UK and Canada (Canadian Press 2013). And Indiegogo (2012) hosts projects from all over the world, working with five different currencies (American Dollars, Canadian Dollars, Australian Dollars, Euros and British Pounds). However, in addition to these four platforms, several others have their own peculiarities, offering different points of view that should also be considered; for example Cinese, also a Brazilian crowd funding platform, is focused on meaningful meetings supporting non-traditional learning; Beacon, which is a platform for independent writers and journalists to get recurrent contributions to keep writing new pieces; or yet MedStartr, a platform based on Catarse's source code, built exclusively to crowd fund medical projects (their catchphrase claims that ordinary people's interests, not multinational corporations, should drive medical innovation). By focusing on a sample distribution that covers all this diversity (profiles, intellectual property, business model, content policy, niches), this research covered different backgrounds, cultures, demographics and geographical differences.

