= Methodology and Literature Review
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

Two recurrent topics on contemporary political theory are extremely relevant in order to address the possibility of politics through crowdfunding. One of them comes from the antipolitics stream (Schedler 1997), and it argues that many institutions and practices that were supposed to be political are, in fact, mitigating politics as such. According to this critique, a spread dissatisfaction with the means and ends of these institutions and practices has lead to a general disavowal of politics _per se_; politics, therefore, starts to be taken with a skeptical and cynical tone, starts to be perceived as corrosive to society. By these means, it ceases to be the realm for conflicting interests, passions and desires. Furthermore, politics ends up either as technical matter relegated to specialists, or as a rational pursue for consensus — both alternatives sustained by a strong belief in a impartial set of procedures (Mouffe 2005). The other topic, subsequently, is one way to approach this contemporary political condition through the critique of rationalization and of utilitarianism (Weber 1976, Collins 1986), as well as through the underneath and widespread individualism and disconnectedness related to these ideals (Bellah _et al_ 2008). This set of critiques argues that in the last centuries traditional republican and religious morals have been fading out in terms of relevance, being replaced by a culture that fosters the pursue of self-interest in a way that does not create, neither sustain, social ties (Bellah _et al_ 2008, Graeber 2011).

Crowdfunding is a phenomenon that has been engaging millions of people, online and offline. Kickstarter, arguably the most popular platform among them, raised its supporter base (backers, as they call users that contribute to campaigns) from almost 9 million to more than 14 million in the last 3 years - a crowd big enough to back almost 140 thousand projects with a total sum surpassing 3.5 billion US dollars (Kickstarter 2015a, Kickstarter 2018). Indiegogo, another platform, had 2.5 million active users in 2015 alone (Indiegogo 2018). The numbers and the pace they haave grown in the last few years are described above (also from Kickstarter 2015a, Kickstarter 2018):

[%header,format=csv]
|===
Total,2015,2018,%
USD pledged,1.75B,3.47B,98%
Backers,8.8M,14.1M,60%
Projects funded,86K,137K,59%
|===

In addition to these statistics this community seams to be proud about the quality of its achievements. In its 2016 balance Kickstarter highlights the achievements of some projects funded through the platforms: during that year the London Design Museum added 6 Kickstart funded pieces to its permanent collection, 19 Kickstarter funded films made their way to Tribeca Film Festival, 4 Kickstarter funded projects received a Grammy nominations and other three were listed by Times magazine in their inventions of the year list.

In face of such a meaningful increase the primary hypothesis of this research is an invitation for an in-depth reflection about the social implications of this expansion. The assumption is that there is a multitude of projects out there to be funded and a very specific mechanism to decide which one of them will be funded. The decisions derived from this mechanism are primarily based on monetary contributions. However in background lies a complex network of social ties that might foster or deter contributions: the range of users' social networks, the ability or appeal to attract spontaneous media, the alignment to popular or niche causes and so on. Therefore underneath this funding scheme crowdfunding also operates as a platform for political agency: there are conflicting projects and interests, and there is also a public deciding what really happens with each of these possibilities. Crowdfunding is clearly a form of political engagement, but the nature, scope and the implication of its legitimacy and power as a political tool is still uncertain for both adherents and external observers. To afford a proper sociological investigation on these topics my aim is to explore the social relations and world views created by crowdfunding, especially in comparison to traditional approaches to conventional politics (organized parties and social movements, institutionalized procedures such as voting) and to entrepreneurship (activities primarily focused on establishing highly profitable businesses). 

Initially what needs to be covered is the specific nature of crowdfunding initiatives. Since projects are proposed and backed by ordinary people, a naive approach would see it merely as a way to bring ordinary ideas to life. Alternatively, a more cynical point of view would claim that it is all about business, since most of crowdfunding platforms emerged as startups (and, indeed, a couple of them actually became millionaire companies). Yet a more utopian and libertarian standpoint could claim it is all about  a very specific political discourse; possibly they would argue that crowdfunding confronts corporations and government – traditional institutions that usually act as sources for funding (and in some circumstances these incumbent institutions can be be unique source of funding). Surely these are only a few stereotypes, but the objective is to understand how different ideals and purposes are balanced within crowdfunding projects and communities.

The areas briefly described above guide this research. They refer to three research questions that could be summarized as: What are the specificities, bias and limitations of crowdfunding politics? How does crowdfunding relate to incumbent political and economical institutions? What is the nature and the social implications of the political world view put forward by members of the crowdfunding communities?  This chapter draws a methodological and theoretical framework in order to address these questions. It starts by discussing the data collection strategy, its justifications and limitations. Next it presents a literature review on political theory, mainly discussing the mitigation of politics. Finally a concise discussion on the overarching theoretical questions that connects the data collection strategy to a coherent sociological description of crowdfunding in relation to contemporary society and its political tensions.  

== Methodology

Addressing the ways through which people create and reinvent relationships using digital medias is not a trivial task. According to Beer and Burrows (2007) a powerful way to address the dynamics of internet is to opt for descriptive accounts, reconceptualizing spheres that are being redefined by online communities and tools. For them, the challenge is “to construct more complete and differentiated descriptions of what is happening” and to give an account of “who is involved, and the practices entailed, in order to inform and enrich new concepts or reworkings of our theoretical staples.”

Moreover when dealing with social research on science and technology there are two commonplace analytical simplifications: either social reality is determined by the technological artifacts (leaving no agency for humans) or technological artifacts are fully interpreted and signified by human agency (considering technological artifacts merely subjects of human action). The idea is to be in-between these extremes, an approach that “allows us to understand technological innovation and social changes as an interplay between solid technological capacities, and the social situation of their development and use” (Allen-Robertson 2013:12). In other words the idea is to be sensible to the possibilities and limitations brought to life by technological artifacts, but also to the appropriations and semantics developed through their usage.footnote:[This approach is also based in what Hutchby (2001) called _affordances_.]

That said it worth it to reinforce that the technology put forward by crowdfunding platforms is not at the core of this research as much as the possibilities opened by it. The technology is relevant as far as it can be used to understand changes in the dynamic of society. As the next chapters explore, that is the case, for example, of the way a certain group of social actors perceives others around them (other people, other institutions) depending on how they embrace intellectual property (proprietary or free and open source code). But that is also the case of more broad social impacts, such as the resurgence of the idea of the _prosumer_ due to new communication possibilities and cheaper alternatives for production (Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010)footnote:[It is considered a resurgence since the first use of the term _prosumer_, in the 1980s, was proposed by a futurologist (Toffler 1980), and only a couple of decades later the idea could be embraced as a rooted academic perspective.] A simplistic take on that issue could take into account merely how the mechanics of production has changed: on the one hand, internet decentralized communication, that is to say, in a different way from newspaper, radios and TV centralized broadcasting, the internet allows every one involved to receive _and_ send information over the network; on the other hand, a couple of decades ago, in order to spread a text one has written, one would need to spend a huge amount of paper, ink and oil to print it and distribute it. As a result, it is basically free to write and publish a multitude of texts online nowadays, after the popularization of the internet. Technology, economy, and production as whole have changed and surely these novelties and its impacts cannot be minimized. However social sciences ought to go beyond that point and focus on how capitalism  (as well as other power institutions around it) was reshaped by the new culture developed among the multitudes of internet users (Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010). 

These overarching social rearrangements are not obvious especially when the technological and social innovations underneath them are in their early stages. Crowdfunding platforms are relatively new and in cases like that the mindset of members of this community are powerful indicators about what can be expected from this new social group and from its impacts on society. Therefore capturing the world views pushing people into these platforms is the approach for this research. The idea underneath this methodological choice considers that social actors’ conceptual framework can limit and determinate action or, yet, can completely reconceptualize it (Ragin 1994). Moreover, “at any particular time, one should be prepared to find that governing concepts can, and often do, lag behind the behavioral requirements of the case” (Ragin 1994:92). The combination of the descriptive approach suggested by Beer and Burrow (2007) together with the stress on world views paved to the way to yet another methodological recourse: recurring to semi-structured in-depth interviews as the main source for data collection. I held roughly 30 interviewees with people engaged with crowdfunding (more on the interviews and on the interviewees in the next pages) and throughout these interactions I could learn about hos they see themselves in the world and collect relevant information about their own backgrounds. This context allowed my to comprehend their opinions, choices and values in a insightful way and then it was possible to make a rich sociological analysis of their ‘governing concepts,’ especially when it came to their engagement with crowdfunding.

In some sense, this strategy is similar to Weber’s (1976) and Boltanski & Chiapello’s (2011) argument that underlying motivations and deterrents were fundamental to understand how society is organized. If this research differs from their historical and document data collection, it is similar to Weber’s assumption that psychological sanctions originated within some protestant sects had unforeseen behavioral impacts on society, and it is similar to Boltanski & Chiapello’s assumption that a certain ideology can justify not only the engagement with capitalism, but always explain different and changing engagement throughout time. Given the emerging aspect of crowdfunding, it is not possible to follow the document data collection (Land and Taylor 2014), therefore the option for interactions with people involved in crowdfunding through semi-structure interviews appear once more as a solid methodological choice for this research.

Some scholars argue that qualitative social research might fail in achieving theoretical relevance outside the field in which data was collected.footnote:[That is, for example, a risk in recurring to qualitative research and a grounded theory approach, as put by Blakie (2010). It worth highlighting that the author does not discourage the combination of these methodological approaches though.] However when it comes to this specific research a quantitative measure could be problematic. On the one hand, the amount of money changing hands, the market value of platforms, the number of people involved, or the greatness of the projects being executed would probably be weak measures to compare this new communities with incumbent institutions such as corporations and governments. On the other hand, measuring the economic impact or running surveys on people opinions related to crowdfunding would be strategies that do not dialogue so well with very qualitative concepts such as world views and governing concepts that predates more significant social changes. Given the contemporaneity of crowdfunding and the potential of internet communities to impact incumbent institutions (Allen-Robertson 2013, Ritzer 2015, Ritzer 2014, Ritzer and Jurgenson 2010), this qualitative approach is relevant for comprehending a wider movement that includes different branches of internet groups, such as crowdsourcing, sharing and collaborative economy, social networks, free and open source software and hardware, makers movements, hacker and open spaces and so on. Mapping the moral grounds (Weber 1976, Boltanski & Chiapello 2011), the conceptual framework (Ragin 1994) of crowdfunding is a way to pinpoint ideals that might be relevant for many of these new communities (for example, as in Taylor & Land 2014). As Bellah _et al_ (2008:275) highlighted, approaches like that are able to grasp rich sociological insights: 

[quote]
focus [on political economy] makes sense in that government and the corporations are the most powerful structures in our society and affect everything else, including our culture and our character. But as an exclusive concern, such a focus is severely limited. Structures are not unchanging. They are frequently altered by social movements, which grow out of, and also influence, changes in consciousness, climates of opinion, and culture. We have followed Tocqueville and other classical social theorists in focusing on the mores — the ‘habits of the heart’ … It make sense to study the mores not because they are powerful — in the short run, at least, power belongs to the political and economic structures — but for two other reasons. A study of the mores gives us insight into the state of society, its coherence, and its long-term viability. Secondly, it is in the sphere of the mores, and the climates of opinion they express, that we are apt to discern incipient changes of vision — those new flights of the social imagination that may indicate where society is heading.

Considering the approach described above, the interviewing method offered in-depth qualitative understanding of the world views related to the emergence of the crowdfunding phenomenon. Furthermore this source was considered together with a textual analysis based on the websites and materials circulated by the platforms and the community as a whole. The analysis of both sources enabled inferences on the social, cultural, economic, moral and political foundations of these world views. The aim is to assess interviewees’ point of view, and to inquiry about how they locate themselves into society — or, in other words, to grasp their own world views, values, references and aspirations. Finally these findings are valuable information to propose guidelines for a conceptual framework in which the social relations between people in the crowdfunding community and social institutions, a framework that ultimately helps us in understanding the social role played and aspired by these social actors.

There are a vast number of crowdfunding platforms. Although Wikipedia (2015) lists roughly 100 active platforms,footnote:[This figure is form 2015. In May 2014 this same Wikipedia article mentioned only 60 crowdfunding platforms. This is a 60% increase in platform numbers in 12 months.] this is clearly an incomplete list. For example, Catarse is a Brazilian platform built in an open source license.footnote:[Catarse (2015a) operates under MIT License.] This means anyone is free to use their source code to build a new platform. According to Catarse’s wiki (2015b) there are 15 active platforms based on their source code, roughly half of them operating in other countries than Brazil (including locations such as the USA, Canada, Denmark and Argentina). Most of these platforms, including Catarse itself, are not included in the Wikipedia’s list. Such diversity has to be taken into account in the interview strategy for this research. During this qualitative investigation an important challenge is to grasp the variety of possible different purposes behind different platforms. To contemplate this diversity two main strategies were adopted during the sampling in order to rapport to as many world views as possible.

First, the interviews were held with three different profiles: platforms founders and staff, people submitting projects to these platforms (project creators), and people backing these projects (project supporters). For each founder or staff interviewed, the idea was to interview two project creators and three project supporters -- this would allow us to have informant with different point of views within the crowdfunding community. Surely this ratio mostly a rule of thumb, not a restrictive or normative guideline, especially because these categories overlap: most of the times a founder is also a project supporter or even a project creator; most project creators usually have backed some project in the past, and still backing projects during and after their own campaigns. In spite of that keeping these three profiles in mind allowed the analysis to move from an arguably idealistic point of view of founders (whether it is business or common good based, just to mention two opposing examples), to more pragmatic standpoints from project supporters. In additional to these profiles directly involved in the crowdfunding community I also spoke to experts in topics relevant to the field: scholars and entrepreneurs in areas such as sharing economy, tech startups and social impact driven ventures.

Second, there are three main characteristics of crowdfunding platforms to be considered. This characteristics relates to how platforms design their business model, to the way the they deal with their own intellectual property, and to the curatorial layer sometimes included in their service. Details about four specific platforms are helpful in clarifying and illustrating these characteristics, namely: Indiegogo, the first crowdfunding platform, and one of the most widely known; Kickstarter, the so called largest crowdfunding platform in the world;footnote:[The “largest” is read over the news without an objective measure or comparison with other platforms (e.g. Canadian Press, 2013).] Catarse, the first open source one; and Patreon, the first one to offer a recurring funding mechanism.footnote:[In terms of the kind of projects hosted by these platforms, all of them vary widely. Even if they were created with some kind of public or projects in mind (for example, Indiegogo and Kickstarter primarily focus was on creative projects, while Patreon and Catarse focuses are on artistic and cultural projects), they are open enough to host projects that vary considerably: from movies and music, to software and hardware technology development, including sports, civic actions, political organization, and education. Hence the directions publicly announced might be internal guidelines and not something clearly perceived by the general public.]

When it comes to their business models, the basic difference between Indiegogo, Kickstarter and Catarse is that the first one charges a higher fee (a percentage over the total value pledged), but the project creator can collect the money pledged even if the target is not reached within a given deadline — this model is known as ‘keep-it-all.’ On the other hand, the other two charge a smaller fee (also a percentage over the total value pledged), but if the project target is not reached until the deadline, all the money returns to the backers and no fees are collected (nor any funds is passed to the project creator) — this model is known as ‘all-or-nothing.’ Crowdfunding campaigns under this model, they claim, are stronger in terms of engagement: supporters, in order to contribute to the success of the funding campaign, need to spread the word about the project if they want it to succeed. Supporters as well as creators need to work together to bring more attention to the initiative. Finally Patreon inaugurated the idea of a ‘recurring’ contribution: instead of backing a specific project, usually with a higher amount (for example, 20 dollars for the recording of a music album), the idea is to contribute with smaller amounts to an ongoing project (for example, 1 dollar per month for a certain musician, or 1 dollar each time this musician shares a new song). If the ‘all-or-nothing’ scheme is said to foster engagement, this engagement tends to fade away once the project is finished (in the example, when the recorded album is delivered). Alternatively, the ‘recurrent’ method would extend the engagement between project creators and its supporters for an undefined period of time. Arguably this mechanism would risk a less intense engagement since it lacks a specific deadline and target though.

Catarse is the only open source platform among them; the other three platforms are based on proprietary software. Interestingly there was a huge difficulty in reaching someone from Kickstarter to be interviewed for this research. Also several interviewees (from other platforms) told the very same story: Kickstarter do not talk with ‘copycats,’ as one interviewee told me. If Indiegogo, Kickstarter and Patreon, by protecting their code, suggest that they operate as more traditional business, protecting the engine from possible competitors,footnote:[Regarding Kickstarter, it could be added that they eventually get involved in judicial cases around patents for their ‘all-or-nothing’ model (Purewal 2011).] Catarse departs from an different market philosophy, offering its source code openly without any apparent fear that some ‘copycat’ would be a risk to them. In fact, Catarse developers seem to express the complete opposite idea: they are actually helping other developers using their source code (they are very active in their collaborative channels: their open repository and their open mail list dedicated to developers). To be sure the idea is not to affirm that embracing proprietary software is an indicator of a less friendly behavior towards others in the field of crowdfunding, however such findings cannot pass unnoticed. In order to support the opposite idea, that is to say, in order to disfavor any relationship between proprietary software and openness to connect with other stakeholders, one of Catarse’s core developers told me that there were some conversations between Catarse and Indiegogo in which they intended to merge Indiegogo’s and Catarse’s source code. The merging had never occurred, but the point is that different stories might point in different directions, requiring the analysis to pay attention to specific combination of characteristics and avoiding rushing into conclusions. In sum the point is that these categories might illuminate one aspect or another, but they are not deterministic in any sense.

Finally, considering the curatorial layer, Kickstarter, Catarse and Patreon tend to have a more prominent curatorial layer: people from the platform tend to work together with the project creators before and during the campaign. The focus is on refining the content to be published online in an attempt to make the project more likely to succeed. As some informants put, this is the difference between having a thicket or a garden: they carefully cultivate every project, as gardeners cultivate their flowers, in order to raise the bar when it comes to the projects and campaigns. Indiegogo is more open and users can submit projects without the explicit platform ‘seal of approval.’

In that sense, these three characteristics — intellectual property (proprietary or open source software), business model (keep-it-all, all-or-nothing, recurrent), and content policy (the relevance put on the curatorial layer) — are key points to link world views sustained by interviewees to the core concepts in case: contemporary conditions for politics, individualism and disconnectedness. Moreover, this initial group of platforms covered crowdfunding in different countries. Patreon is mostly an American platform, while Catarse is a Brazilian one (in the sense of the geographical disptribution of project creators and supporters). Kickstarter was launched officially in the USA, the UK and Canada (Canadian Press 2013). And Indiegogo (2012) hosts projects from all over the world, working with five different currencies (American Dollars, Canadian Dollars, Australian Dollars, Euros and British Pounds). However, in addition to these four platforms, several other have their own peculiarities, offering different points of view that should also be considered; for example Cinese, also a Brazilian crowdfunding platform, is focused on meaningful meetings supporting non-traditional learning; Beacon, which is a platform for independent writers and journalists to get recurrent contributions to keep writing new pieces; or yet MedStartr, a platform based on Catarse’s source code, built exclusively to crowdfund medical projects (their catchphrase claims that ordinary people interests, not multinational corporations, should drive medical innovation). By focusing on a sample distribution that cover all this diversity (profiles, intellectual property, business model, content policy, niches), this research covered different backgrounds, cultures, demographics and geographic differences.

The data collection included 26 interviews with platform founders and staff, project creators, supporters and experts. These informants are from the 8 different countries including 5 continents. This mix allowed me to investigate experiences from more than 10 different crowdfunding platforms from 4 different countries. In fact many of the interviewees have experience in more than one platform, but for the sake of simplicity in the following table I listed only the one that was prominent in each interview. Finally a few of them asked me to mention them by pseudonyms; in order to protect their identity I am not explicitly distinguishing them from the ones who have not asked for pseudonyms. Also I am not using (real or fake) family names for any of my informant:

[%header, format=csv]
|===
Given name,Profile,Platform,Gender,Nationality
Adam,Supporter,Ulule (France),♂,France
Amanda,Creator,Catarse (Brazil),♀,Brazil
Anna,Founder,Cinese (Brazil),♀,Brazil
Brittany,Creator,GoFundMe (USA),♀,USA
Carla,Supporter,Kickstarter (USA),♀,Brazil
Chris,Expert,,♂,UK
Daniel,Founder,Unlock (Brazil),♂,Brazil
Daniel,Supporter,Benfeitoria (Brazil),♂,Brazil
Daniel,Supporter,Kickstarter (USA),♂,Germany
Emily,Founder,PeopleFundIt (UK),♀,UK
Felipe,Expert,,♂,Brazil
Felipe,Creator,Benfeitoria (Brazil),♂,Brazil
Giovana,Staff,Cinese (Brazil),♀,Brazil
Juliana,Supporter,Catarse (Brazil),♀,Brazil
Lisandro,Supporter,Kickstarter (USA),♂,Brazil
Maria,Creator,Indiegogo (USA),♀,Romania
Miguel,Founder,Catarse (Brazil),♂,Brazil
Noah,Supporter,Indiegogo (USA),♂,USA
Pedro,Creator,Catarse (Brazil),♂,Brazil
Rodrigo,Staff,Neighborly (USA),♂,USA
Sam,Expert,,♂,USA
Stephen,Expert,,♂,UK
Talita,Supporter,Kickstarter (USA),♀,Brazil
Victor,Creator,Patreon (USA),♂,Brazil
Wei,Supporter,Kickstarter (USA),♂,China
William,Founder,ProduceRun,♂,Australia,USA
|===

The sampling and data collection phase started with the publicly available channels to contact individuals at crowdfunding platforms: email, contact form, social media etc. I reached them, explained the purpose of the research and asked for their participation. If they opt to cooperate, then I would invite them to an interview and also recurred to snowballing sampling (that is to say, I would ask them to suggest other people people I could reach). Usually I would try to snowball different profiles: for examples, when talking to staff I would ask if they could think of a particular supporter or project creator that might accept my invitation for an interview. In spite a couple of positive responses this strategy was not so successful: I have got no reply for many emails and posts; when it happen to have a response, usually it was a typical costumer support text with standardized responses. It was nor rare to read in these responses that anything I would like to know about their platform was already available in their institutional web pages. The few real conversations I could start using this approach ended up in declined interviews -- and when it was the case of the biggest platforms, it was not rare to read that their company discourage (or forbids) them to take part in interviews.

At this point it I needed to work on a different strategy for data collection and I recurred to my personal background: I write computer code since I was a child. During my early twenties this hobby became my main professional activity for a brief period. From this experience I was already part of free and open-source software and developers, especially within communities guided by hactivism (which ended up as the topic of one of my master thesis in sociology). There is a great amount of people from these civic-minded tech communities that have get involved in crowdfunding, thus I recurred to my previous colleagues in order to facilitate my access to data. I could easily reach the ones I already knew and ask them for ideas, asking them who should I contact, ask them for introductions. Snowballing succeeded from there allowing me to collect valuable data for this research.

These access to data requires some notes in terms of reflexitivity. Even with friendly introductions from colleagues from think tanks or working in the Silicon Valley I still have no access to some platforms I would like to have — this was the case of Indiegogo, Crowdcube and Kickstarter, for example. As mentioned, the larger firms and platforms I contacted declined to take part. The other, smaller platforms offered me great openness to talk and to contribute with the snowballing technique. This was the case, for example, of Neighborly, PeopleFundIt, Catarse, Cinese, and Unlock. Hence there are at least two bias as a consequence of these methodological barriers and facilitators. First I avoided any informant from my closer social network, recurring to acquaintances, not to friends, even if I was not interviewing them directly. They were entry points to the fieldwork, not informants -- in other words in order to minimize bias I interacted with people I knew to reach people outside my regular network, expanding the sample from there.

Second it worth it to highlight that qualitative methods do not intend to generalize its findings, but aims at a detailed and in-depth description of a specific field. In my case I was cautious to avoid extending my arguments further than my data collection allowed me to. What follows is a careful discussion based on an important share of the crowdfunding community: enthusiasts that at maximum are project creators in the big players such as Kickstarter and Indiegogo, but no voice from inside these big players. Maybe Catarse is an exception as it is the biggest crowdfudning operating in Brazil. But that just add another layer to the reflexitivity, my home land: many of my previous contacts are Brazilian, and even if they have been working in many different countries, I have greater access to data in Brazil than in any other country.

Also I have projects crowdfunded through Catarse, and Nós.vc (a platform similar to Cinese) and I have also contributed to projects on Catarse, Nós.vc, Indiegogo, Kickstarter and Patreon. Contacts from these projects were not considered for this research in order to minimize bias. Finally during the research I informally monitored some social media and forums on the internet looking for posts related to crowdfuding and some interviewees (then unknown to me) I approached after reading some post or comment they have publicly shared mentioning crowdfunding.

The focus of the semi-structured interviews was on the point of view of the interviewees about society, business, politics and economics — especially (but not restricted to) when it comes to crowdfunding. In order to better grasp these views, the first part of interviews was not explicitly mentioning crowdfunding, but investigating interviewees’ personal trajectory and identity: I asked them to introduce themselves, to tell me about what they like to do, how do they make a living and other background information that allowed me to contextualize the experiences they were about to share with me.  The idea was to adopt a funnel-shape questioning technique, narrowing down the subject (namely, crowdfunding and politics) towards the final part of the interaction. By these means, informants might get to the specific subject spontaneously -- if not the next steps of the funnel would discreetly attempt to conduct the conversation in such direction. My role as an interviewer was to guide the interviewee in such direction only if certain topics have not emerged in a more spontaneous way (Kvale and Brinkmann 2009). At maximum what was expected for the first part of the interviews was to have an brief idea about the interviewee's general opinion on government, corporations, civic organizations,  political views and attitudes. At this point these ideas were comprehended from personal stories (when someone declined a job offer from a corporation in order to work in a NGO, for example) and not mentioned explicitly. The intention was touch upon these aspects without intervention, that is to say, without stimulating the interviewee to relate these topics to crowdfunding. This technique was employed to avoid the risk of making the interviewee stick to one or other concept just because the interviewer mentioned it — and not because it was already part of the interviewee’s own point of view (Kvale and Brinkmann 2009).

The following step of the funnel is the interviewees’ relationship with crowdfunding; this step varied according to the informant profile. For founders and managers, the conversation focused on how they situate their business within society, their choice to found, or work for, a crowdfunding enterprise (and their motives to not work elsewhere when that was the case). For project creators, the exploration shifted towards the reasons why they opt to count on crowdfunding instead of other funding possibilities. For supporters, the focus was on what has driven them to take part in crowdfunding campaigns, their expectations and feeling about such experiences. Finally with experts I would inquiry about how did they end up in their field of expertise. My experience in this block of the interviewed confirmed that the context provided by their personal background was a pretty useful interviewing technique: usually the transition to this part of the interview was seamless and spontaneous, as a sort of continuation of their life trajectory at a certain point. This was valuable in terms of the non-intervention methodology described above. Moreover during the interview and the analysis the personal background offered important hints to expand on informants experiences with crowdfunding.

After stepping in the main subject, that is to say, after the interview was definitively shifted towards crowdfunding,  the last block addressed interviewees’ opinions and views about crowdfunding in a broader sense. The investigation inquired about what interviewees expect from crowdfunding, how they position it within ‘traditional’ social spheres (such as business, politics or culture), and yet verified the possibility of a more aspirational approach when it comes to the social context. If needed I would more firmly conduct the conversation in a way that invited them to share with me their perceptions of themselves within society — that is to say, how they position themselves facing a given cultural, political and economic context. By these means, the objective was to grasp their collective and individual expectations related to crowdfunding mechanisms and to society in general. The following table summarizes this funnel shaped design, moving from a more open and spontaneous conversation to a more focused and guided one:

[%header, format=csv]
|===
Stage, Objectives, Typical topics
"*1. Personal background* (more open, more spontaneity)", Contextualize and better comprehend each interviewee,"Who they are, what do they work with, what do they enjoy in their free time, educational and professional background."
*2. Crowdfunding experience*, In-depth understating of their relationship with crowdfunding,"How did they get involved with crowdfunding, drivers & barriers they feel, how do they perceive other funding alternatives."
"*3. Values, objectives & aspirations* (more focused, more guided)", "Comprehension of the core values guiding them, projection of their will in terms of social, economic, cultural and political change", "Whether they consider crowdfunding political or not, what they are trying to achieve in life (and how crowdfudning might or might not contribute), what are the main issues to be tackled in society (and how crowdfunding relate to them."
|===

The interviews were held in person or remotely (using telephone, VoIP or video conference) between May 2014 and December 2015. The context lacking in the remote interviews were not considered to represent a relevant loss of data in this particular case. Among other reasons most participants were expected to be well articulated and used to express themselves in public -- after all they are entrepreneurs who found and manage online platforms, or they put their own projects online to public, or yet they voluntarily engage with these projects, spreading the word about it. The content of the interviews were recorded (according to the consent of the interviewee), transcribed and analyzed. Next the data went through a process of coding and condensation of meaning. The idea was to condensate the most relevant units, and use the coding to categorize these bits of information. Additionally this content was triangulated with other sources, with data collected from the platforms themselves and from the interviewees’ online public profiles. This process allowed a contextual interpretation of the meaning of these units of information, as well as validation of the content of the interviews.

== Literature Review

NOTE: [LM] Your opening framing of the literature – situating the thesis in a longer historical understanding of modern political systems – is not necessary off-base, but I think you need greater specificity in order to make clearer why it’s necessary to state that major changes have taken place in political governance over the past 200 years. I mean, that fact is a little bit obvious and pertinent to all theses, so you need to make a stronger case for why the historical framing is central to your own particular research questions.

NOTE: [LM] literature that we have emphasized that you need to point to, e.g. contemporary work on crowdfunding, social entrepreneurship, and platform capitalism. You do mention this literature (Palmas, etc), on page 106 and elsewhere, and this is good. But it should be alluded to earlier in your lit review. As mentioned before, this doesn’t have to be the core of your literature review. Your core focus – on Arendt and other political theorists – is already clear and quite well-done – a very good first draft that just needs a fair bit of polishing. But you also need to have a ‘nutshell’ summary of other relevant literature too, especially as you refer to them later. I would say something like: The core literatures informing my research are political theories of the relationship between the public and private realms, and particularly work by Arendt, Wolin and Bellah. But I also draw from more recent analysis in economic sociology on the rise of crowdfunding and its commercial and social implications, as well as literature from science and technology studies (STS) and the sociology of ignorance on the ways that political action is conscribed by often unspoken commercial or political exigencies that undermine the possibility of effective public engagement in Arendt’s sense. 

The focus of this research, identifying and describing possibilities of politics within crowdfunding communities, is based on critiques from political theory towards the possibility of political action and engagement in contemporary society. Most of this framework discusses the nineteenth and twentieth centuries modern world, especially when it comes to sociological, political and philosophical implications. On the one hand, these oeuvres are reflecting upon the outcomes of the eighteenth century revolutions in the USA and in France (for example, Tocqueville 1986 or Arendt 1973).  on the other, they are rethinking these results in the light of the terror spread during the two World Wars, and of the democratic states emerged thereafter (for example, Bellah _et al_ 2008 or Arendt 1998). Commonly, this literature acknowledges the achievements of the Enlightenment, but, at the same time, emphasizes how it failed in completely putting forward some of the ideals that were at its core. For example Arendt (1973) did not deny the importance of modern political institutions such as parties and elections; they opened the political career for people from the lower classes, and yet the notion of forming an elite through the party replaced the old elites based on birth or wealth. However she also emphasized that the party framework is less meaningful in providing a government _by people_ than in recruiting _from people_ an elite to govern them. In other words, the central question here is not the democratic (or republican) institutions _per se_, but the tangible possibility of political action for ordinary people.

The first part of this section draws the framework of these critiques towards modern state, its democratic assumptions and failures. Next it discusses the contemporary debate built around this sort of flaws, bringing in discussions around the arguable decline of political engagement in the turn of the twenty-first century. Finally it sets some challenges in thinking political action in contemporary society. The idea is to grasp the difficulties in using traditional approaches to political institutions to understand how political action can be reinvented within nowadays tensions and conditions.

=== Modern institutions and its discontents

In terms of politics most of the ancient world was traditionally based on a distinction between the public and the private, two separated realms in which people would pursue different objectives through different means. However this scenario has changed considerably during the last centuries:

[quote]
the emergence of the social realm, which is neither private nor public, strictly speaking, is a relatively new phenomenon whose origin coincide with the emergence of modern age and which found its political form in the nation-state (Arendt 1998:28).

Therefore, there is something essentially modern in the constitution of nation-states, and this essence relates to one of the core distinctions within political theory, namely, the public and the private realm. Therefore following the emergence of the institutions created during that transition is a way to understand how this new political framework was forged. Moreover this history sets the background for the subsequent criticism regarding the successes and failures of the modern project for politics.

The division between public and private was forged in ancient Greece, when one should keep the pursue of private interests to the boundaries of the household, the core place for one’s private life. That is to say that only citizens who have provided enough for them and their families were allowed to participate in the public life. This requirement was based on the role expected of this citizen when engaged with politics:

[quote]
Private wealth, therefore, became a condition for admission in public life not because its owner was engaged in accumulating it but, on the contrary, because it assured with reasonable certainty that its owner would not have to engage in providing for himself the means of use and consumption and was free for public activity. Public life, obviously, was possible only after much more urgent needs of life itself had been taken care of (Arendt 1998:64-5). 

NOTE: [LM] Occasionally, I’m confused or not convinced by your interpretation – e.g. when you say on page 33 that Arendt suggests that pursuing basic survival needs should not be the prerogative or within the remit of the public sphere. I want to understand this better – I am consulting Arendt more closely myself so I can advise better here.

In modern times, in contrast, Arendt suggests that a distinctive realm takes on new rhetorical salience, the realm of the ‘social’, a space she sees as  neither public nor private — and, as a consequence, dislocated considerably what was understood as public. While private life was characterized by providing the household through labor, and while the public realm was the place for action and speech, the social has taken the political space from the public, printing on it important differences: now government acts as a gigantic housekeeping organization, looking for provision for a whole nation; that is to say, labor, once relegated to the private life, now is not only allowed but placed at the center of political life. For Arendt (1998:28-9) the dividing line between the household and politics

[quote]
is entirely blurred, because we see the body of peoples and political communities in the image of a family whose everyday affairs have to be taken care of by a gigantic, nation-wide administration of housekeeping. The scientific thought that corresponds to this development is no longer political science but ‘political economy’ or ‘social economy’ or _Volkswirtschaft_, all of which indicate a kind of ‘collective house keeping;’ the collective of families economically organized into the facsimile of one super-human family is what we call ‘society,’ and its political form of organization is called ‘nation’ (Arendt 1998:28-9).footnote:[Arendt does not justify the use of the German term _Volkswirtschaft_ in this passage. Arguably it has no direct translation into English. Nonetheless it refers to a kind of economics driven by the nation’s needs, the needs expressed by its households as well as by the private and public sector; in some languages, as in Dutch or Latin for example, its translation is similar to _national economy_ (_algemene economie_ and _oeconomia nationalis_ respectively).] 

This transformation, however, was not abrupt. Bellah _et al_ (2008) argue that in the beginning of modern age two strands were sort of references, both for public and private issues: a biblical and a republican strand. The first one is exemplified by the role of religion in the formation of American tradition:

NOTE: The ‘sort of’ is confusing.

[quote]
The Puritans were not uninterested in material prosperity and were prone when it came, unfortunately, to take it as a sign of God’s approval. Yet their fundamental criterion of success was not material wealth but the creation of a community in which a genuinely ethical and spiritual life could be lived (Bellah _et al_ 2008:28-9).
 
Alternatively, the republican strand is illustrated by the standpoint of one of the Founding Fathers, Thomas Jefferson:

[quote]
In general, Jefferson favored freedom of the person from arbitrary state action and freedom of the press from any form of censorship. Yet he also believed that the best defense of freedom was an educated people actively participating in government. The notion of a formal freedom that would simply allow people to do what they pleased — for example, solely to make money — was as unpalatable to Jefferson (Bellah _et al_ 2008:31).

In both cases, Bellah _et al_ (2008:31) reinforced, individual “freedom only took on its real meaning in a certain kind of society with a certain form of life;” without that moral principles, freedom would lead to social corrosion and tyranny. However, later on the nineteenth century, both strands were challenged by two sorts of individualism that withdrew this large social context. On the one hand, utilitarian individualism focused on individual self-improvement, reflecting the liberal belief that if each member of a group pursues her or his own interest, the whole community would testify the emergence of social good. In this case, the idea of interests was basically set by another Founding Father, Benjamin Franklin, whose views were determinant in framing the capitalist motivation for work and accumulation (Weber 1976, Bellah _et al_ 2008). On the other hand, expressive individualism claimed no interest for material accomplishments, but in an individual and subjective pursue for experience through life. The richness of life would be achieved nurturing the self with luxury, sensuality, intellectual and all sort of experiences one could feel to understand and express oneself in contact with nature, with the universe as a whole. Individual freedom is the norm and a disavowal for social conventions marks the tone of this branch of individualism. Therefore, if the earlier strands do not contrast individualism and the public common life, these sorts of individualism do it by conceiving a sort of self-contained individual:

[quote]
What is at issue is not simply whether self-contained individuals might withdraw from the public sphere to pursue purely private ends, but whether such individuals are capable of sustaining either a public _or_ a private life. If this is the danger, perhaps only the civic and biblical forms of individualism — forms that see the individual in relation to a larger whole, a community and a tradition — are capable of sustaining genuine individuality and nurturing both public and private life (Bellah _et al_ 2008:143, emphasis in original).

Hence this discussion — involving different realms (such as the public, private and, arguably, the social) and what is allowed in each one of them — works as a theoretical starting point to look at contemporary political institutions. Having in mind the individualistic and self-determined world views emerged in the last centuries, and going back to Arendt’s critiques, the idea is to understand if the world imagined during the Enlightenment is conceivable nowadays — in other words, if the rupture between individual and civic society brought up by individualism is compatible with the virtues expected from governing bodies. Traditionally the answer to questions like that are pointing in a negative direction. One element of arguments in such direction is calling into question the effectiveness of free markets in granting freedom to ordinary people, that is to say, to ask if rationalized economic sphere would promote the social good (or, on the contrary, if it would prevent ordinary people to act politically):

[quote]
The market idea, as Adam Smith proudly announced, banishes the authority of persons; it is a system of exchange which is legitimate only as a system. The closest we come to an image of control, reassurance, or guidance is the ‘invisible hand’ which assures fairness. But the invisible hand is also an abstraction; it is attached to the body of no single human being (Sennett 1980:43).footnote:[Interestingly Sennett (1980:44) also argues that this economic behavior compromised not only ordinary people’s potential for action, but the core freedom they were suppose to inherit from such a society: “The market ideology promised the consummation of individual freedom of action. The market in practice was anti-individualistic. It displaced masses of peasants from their land, whatever their own desires to remain. At the moments when the supply of labor in cities exceeded the demand for labor, there was in fact no labor market. If an employee did not like wages an employer paid, he could go starve; there were plenty of others to take his place … The market system of the last century, rather, made the concepts of community and individual ambivalent, and ambivalent in a peculiar way. No specific human being, no human agent, could be held accountable for disturbances in these realms.”]

But this critique is extended to the public realm as well. For Arendt (1998:68) society has become “an organization of property-owners who, instead of claiming access to the public realm because of their wealth, demanded protection from it for the accumulation of more wealth” (Arendt 1998:68) — that is to say, the logic of the instrumental individualism has taken down the biblical and the republican strands. This transformation has to be understood according to the specific ways through which modern societies have developed into representative democracies, a constant struggle between emphasizing the anew claimed by the American and French revolutions on the one hand, and, on the other hand, the will to consolidate the ideal of freedom in a stable institution. For instance Jefferson had a particular standpoint among the Founding Fathers regarding the role of the constitution in this process: in ideological terms, he wanted the constitution to be strong enough to guarantee that no hostilities will take place in the political realm, nonetheless, in order to reinforce the founding anew, this same constitution should also be flexible enough to be revised from times to times. In practical terms, the effects of these thoughts can be seen in the representative democracy model and in its well established ways to participate in the political realm: elections, elected officials, senators, representatives, parties and voters (Arendt 1973).

Perhaps this new institutional scenario has failed in fulfilling its original intents. Critiques appeared as early as the 1920s, for example, when Dewey (1954:118) affirmed that

[quote]
skepticism regarding the efficacy of voting is openly expressed, not only in theories of intellectuals, but in the words of lowbrow masses: ‘What difference does it make whether I vote or not? Things go on just the same anyway. My vote never changed anything.’

In other words, this scheme was unable to extend the perception of participation from representatives to represented: when it comes to politics, citizens seem to be disinterested and this fact can be found not only “among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage,” but also “shows up regularly among the favored and highly placed” (Jaffe 1997:78).

Sniderman and Bullock’s (2004) idea of ‘menu dependence’ involves a very similar description of how ordinary people have a very discrete participation in politics. According to them, “citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties” (2004:338). The idea is that citizens are not free to compose their own menu of political choices, but only allowed to pick up one from a menu pre-established by parties and political elites. Yet Wolin’s (2004:428) analysis of contemporary politics adds another layer to this branch of critiques: for him “in both, the political and the economic context, contract appears as the essential condition of power”. In other words as the market economy operates in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state operates in a way that concentrates the (political) power in the hands of the political elite (Wolin 2004). By themselves the functioning of these both institutions are expanding the gap between rich and poor, rulers and ruled. And, as Arendt (1973:253) suggested, underneath this wave of critiques towards modern society, there is the displacement of the public realm itself and also the dilemma Jefferson had in mind:

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of being republicans and of acting as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens. 

This two-folded movement of degradation of the public and of inflation of the private has granted the space for corporations to extrapolate their private bounds and act within the public realm. Political decisions — already distant from ordinary people — gradually started to take into account a logic that does not pertain to the public realm, namely the logic of the market economy (Wollin 2004). 

In spite of advancing in many aspects, this process of modernization had a devastating side-effect for politics: by limiting the space for political action it consolidate the public realm as a place for private affairs. In Arendt’s (1998:46) words, “the character of the public realm must change in accordance with the activities admitted into it, but to a large extent the activity itself changes its own nature too.” The type of skills and activities held within these spaces were also impacted by these transformations. The importance given to labor and provision (formerly banished from the political), and to speech and action (formerly the core of political activity) also assume a different balance. Labor and wealth accumulation made sense as far as the household provisions required them. Excelling in speech and public action in politics was a public virtue which the whole body of citizens would benefit of. Interestingly within the modern social realm labor was introduced to the political space and, at the same time, speech and action was dislocated to the private:

[quote]
while we have become excellent in the laboring we perform in public, our capacity for action and speech has lost much of its former quality since the rise of the social realm banished these into the sphere of the intimate and the private (Arendt 1998:48). 

From that perspective it is possible to comprehend the lack of interest and, arguably, trust in politics; also it is possible to address the endless interest in making money. Both approaches overlap aspects in many critiques towards representative democracy, basically because they change what happens in the political realm. These changes regarding the political institutions of the modern age ended up nurturing two kind of critiques. On the one hand, there is a very optimist approach to the rationalization and individualization processes. This stream, known as post-political, claims that the possible flaws in political institutions are to be overcome with further development of these same institutions, according to same values that brought them to life. In other words, more emphasis on the rationalization would solve this possible flaws. Habermas (1992, 2005), for instance, argue that there are two instances in society — System and Lifeworld — holding different rationalities. The rationalized and instrumentalized one hosts the market and the political institutions, and this is the realm in which the individual interests are transcended in the name of anonymous demands, realized by means of instrumental, strategic action. This kind of rationality is increasingly detaching itself from the social structures, taking the shape of autonomous organizations that only communicates through mediums such as money and power — or, to put it differently, only operates in a way that holds no commitment to other norms or values. Economic and administrative rationalities are the main themes here. The other instance, the communicative one, would be the place were individuals would rationally pursue a deliberation, rationally agreeing on the functioning of the instrumental institutions. Hence, there is no value judgment between instrumental or communicative rationality; rather it is conjectured that each rationality is restricted to its own domain. The problem — part of Habermas’s patology of modernity — is that communicative rationality have been colonized by the instrumental logic. The author defends the need for reconnecting these spheres to avoid the ‘colonization,’ keeping the differentiation and autonomy of these realms. He states that only then communicative rationality will have space to collectively elaborate the ultimate aims for the social good.

Habermas’s diagnosis describes a scenario similar to the one addressed in the last section, but his agenda calls for a rational approach to argumentation, consensus and deliberation. Against this rational approach, some authors defend that rationalization would lead to a more anti-political environment. Instead of using rationality to promote consensus in a post-political space, the idea is that this process would mitigate the very nature of politics:

[quote]
Instead of trying to design the institution which, through supposedly ‘impartial’ procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant ‘agonistic’ public sphere of contestation where different hegemonic political projects can be confronted (Mouffe 2005:3).

Therefore, the lack of trust and interest in the political institutions can be described as antipolitical by (at least) two different arguments: in the one hand, it contributes to the mitigation of the public realm, which is suppressed by a self-regulated private one, the market (Schedler 1997); or, alternatively, whatever remains of the public realm starts to operate according to a logic inherent to the private sphere — what Schedler (1997) calls an inverted Habermasian colonization. To be sure, Wolin (2004:588) highlights that both — state and market — are appropriating the methods of one another: “it is not that the state and the corporations have become partners; in the process, each has began to mimic functions historically identified with the other.” According to him, corporations’ move includes being in charge or funding health care, education and other welfare affairs; in parallel, governments’ move includes applying profits logic, notions of efficiency and management, to buoy its own actions.

The point here is not to demonize corporations or governments, but to reinforce how this conjecture affects political life. Bellah _et al_ (2008:259) argued that, starting by the end of the nineteenth-century, a populist agenda “sought to expand government power over economic life for the common good” in an attempt to fight the power of well established private corporations — this establishment was creating, managing and maintaining public institutions such as universities, museums, churches, orchestras and hospitals. The argument of this populist agenda was that ordinary people should be able to decide for themselves, and economic power was taking this political power from them:

[quote]
If the Establishment vision rearticulated important aspects of the republican ideal of common good in the turn-of-the-century America, Populism was the great democratizer, insisting on the incompleteness of a republic that excluded any of its members from full citizenship (Bellah _et al_ 2008:259).

In sum, neither the rational deliberation and consensus possibility, nor the agonistic one, are hosted in nowadays political institutions. Instead, there is a disavowal for politics as such, since it is generally perceived as inefficient, misguided and corrupt. However this scenario may not eliminate politics as such, and people might find alternative ways to engage in the public and civic life (for example, as in Bennett _et al_ 2013) — and that is the topic of the next section.

=== Action and politics

The last section described what can be understood as a crisis in the contemporary political arena. The idea that voting would grant a accountable authority for the rulers and, at the same time, the sense of participation and freedom to the ruled, is, at maximum, an unfinished project (Sennett 1980). If ordinary people do not trust politics, the notion of participation and civic engagement, together with the ideals of a representative government, are called into question. However according to (Bennett _et al_ 2013:537) in spite of the predictions that this skepticism would move people away from politics, what was found was a ‘skeptical engagement’ with two different possibilities: “a context of mistrust and cynicism might discourage or pervert political participation, on the one hand, or spur innovation, on the other.” Their ethnographic fieldwork showed how civic organizations in Providence (RI, USA) strategically deny the label of ‘politics’ in order to better engage with and to promote change within the local community. Interestingly, this former objective included activities that traditionally are considered very political, such as joining the city council, or lobbying with the local politicians and government.

What the research done by Bennett _et al_ (2013) suggests is that if politics is disinteresting for people, there is still space for actions focusing on the public realm, on the common good. In other words, the political institutions might not be the instance people with a civic mindset are looking for. Wellmer (2000) commenting on Arendt’s political theory suggests that possibilities created within a given political context might be the core of a public and active sphere:

[quote]
Arendt’s concern is not with justice but with (political) freedom. Hence, her brand of universalism is neither the normative universalism of human rights nor the inherent universalism of the modern economy. Rather, it is the universalism of a human _possibility_: the possibility of creating, in the midst of contingent historical circumstances, a space of public freedom (Wellmer 200:229, emphasis in original).
ive. 

In order to comprehend this proposal it is needed to go back to Arendt’s (1998:7) framework. For her ‘action’ is the essence of the humankind, in opposition to ‘labor’ (meeting the basic needs related “to the biological process of human body”) and ‘work’ (“the unnaturalness of human existence,” including the manufacture of tools to make labor easier and more productive for example). Action, in that sense, is held between humans “without the intermediary of things or matter.” Yet the relation between action and politics is crucial to her argument:

[quote]
Action … corresponds to the human condition of plurality, to the fact that men … live on earth and inhabit the world. While all aspects of human condition are somehow related to politics, this plurality is specifically the condition — not only the _conditio sine qua non_, but the _conditio per quam_ — of all political life … Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live” (Arendt 1998:7-8).

If work and labor are held out of necessity, action is held as a virtue. Arendt (1998) differentiated immortality (typically found in Gods) from eternity (something that can be achieved by humans). As merely mortals, human beings can attempt to last for ever, not as immortals, but through actions, through worldliness deeds:

[quote]
no matter how concerned a thinker may be with eternity, the moment he sits down to write down his thoughts he cease to be concerned primarily with eternity and shift his attention to leaving some trace of them. He has entered the _vita activa_ and chosen its way to performance and potential immortality (Arendt 1998:20).

Her concept of _vita activa_ is similar to Aristotelian _bios politikos_ and to Augustinian _vita negotiosa_ or _vita actuosa_, that is to say, “a life devoted to public-political matters” (Arendt 1998:12). Therefore Arendt subscribes to the stream that defends that pursuing private interests, pursuing basic requirements for survival should not be allowed in the public sphere. Alternatively, this realm should deal with the plurality, with different interests and opinions, and with the dispute about the means to maintain this arena active. In this approach, freedom assumes a distinguished importance:

NOTE: Do not rush into conclusions (after ‘Alternatively’). 

[quote]
action and politics, among all the capabilities of human life, are the only things of which we could not even conceive without at least assuming that freedom exists … Without [freedom] political life as such would be meaningless. The _raison d’être_ of politics is freedom, and its field of experience is action (Arendt 1968:146).

When it comes to this plurality and to the freedom to hold different passions in a public sphere, Mouffe (2005:9) criticized Arendt arguing that this image of the public sphere depends too much on a consensus seeking logic:

[quote]
Some theorists such as Hannah Arendt envisage the political as a space of freedom and public deliberation, while others see it as a space of power, conflict and antagonism. My understanding of ‘the political’ clearly belongs to the second perspective.

For Mouffe politics should not be focused on deliberations on the common good, but on people’s desires, emotions and fantasies, and that is why she argues for the agnonistic view: politics presupose plurality and difference, and this difference should not be flatten by any kind of political process or institution.

However, both in Arendt and in Mouffe, there is a primordial call when it comes to the public life: the need to support the emergence and maintenance of plurality throughout democratic societies. Both scholars, therefore, tend to agree that when the political institutions are closed to the creation of anew (as Jefferson feared), when political institutions are leaded by extremely rational and instrumental logic (as Mouffe criticized, since it minimize the importance of more subjective and human impulses; or as Arendt also criticized, since it narrows the boundaries between action, work and labor), and when political institutions do not favor the emergence of a public sphere for ordinary people (as Arendt argued), the democratic spirit is mitigated as a result. In opposition to this scenario, when there is a public sphere able to host different opinions, when this public sphere is not limited to a political economy materially nurturing the big family called nation, when this public sphere is putting forward people’s dreams, and, most important, when this public sphere is forging political institutions that would fit the anew, then the democratic process is successful. 

NOTE: [JAR] One sentence (from ‘Both scholars…’ until ‘…mitigated as a result’). Break down.

Hence, when it comes to looking for the possibility of politics in crowdfunding, the focus of this research is more on exploring the potential of crowdfunding as a public sphere: a multitude of communities proposing different projects and actions that are based on individual or group aspirations; a multitude that depends on a minimum public approval to happen (and here lies a presumption that this could be understood as a profit seeking activity some times, but also as a civic engaging activity from times to times); and a multitude that, through technology, is able to gather enough supporters as well as enough funds to empower ordinary people to hold political claims and actions (in the sense that they operate outside the traditional political institutions, that is to say, governments and, in some cases, corporations).

'''

The importance of technology, even if relevant, is not the core of the research. However the idea that technology is crucial in promoting democracy is not new:

[quote]
‘Invent the printing press and democracy is inevitable.’ Add to this: Invent the railway, the telegraph, mass manufacture and concentration of population in urban centers, and some form of democratic government is, humanly speaking, inevitable (Dewey 1954:110).

This idea also appears in other scholars from the last century, such as in Tarde’s (1989) _L'opinion et la foule_ from 1901, in which he defends the role of the printing and newspaper in civilizing the public; or the importance Blumer (1939) put in electronic broadcasting on setting the tone of a free society (even if he recognized the possibility of mass manipulation). Instead of subscribing to a more utopian perspective (such as Dewey’s quote above), or a dystopian one (such as the centralization inferred by the manipulation pointed out by Blumer), the idea is to be sensible to how technology contributes to the construction of reality, and, therefore, how important aspects of political institution might assume different semantics — for example, new forms political leadership (Margetts _et al_ 2013) or new social meanings for money (Dodd 2014). 

The hypothesis used to frame the research questions is based on an arguably libertarian hacker ethic, typical in many of the novelties emerging from the digital world. This ethic “represent[s] a liberal critique within liberalism” since “hackers question one central pillar of liberal jurisprudence, intellectual property, by reformulating ideals from another one, free speech” — consequently revealing “the fault line between two cherished sets of liberal principle” (Coleman 2013). Surely this hypothesis is closer to an utopian stream, what does not impede the research to call this assumption into question, especially when these more autonomous initiatives (normally from free and open source niches) start to collide with incumbent institutions, triggering a set of negotiations between the challengers, the establishment and the public (Allen-Robertson 2013). The idea is to investigate the possibility of crowdfunding to challenge incumbent institutions such as government and corporations, or, in other words, the possibility of identifying elements of a public sphere in the crowdfunding communities. The perspective of people engaged in crowdfunding is the key to understand their motivations, and that justifies the epistemological approach on world views: at this early stage, it is more relevant to understand their political aspirations and expectations than tangible and measurable social changes.

Considering the medium and long term scenario, it is understood that, on the one hand, the focus on autonomy nurtured by the hacker ethics seems to foster an atomized private realm, relegating the decisions about what should and should not be done to the sphere of individuals' moral and judgements. On the other hand, the mechanisms embraced by crowdfunding (from the functioning of the online campaigns to the dependence on strong and weak ties) require these decisions to be held by a greater audience: without supporters, no project becomes reality, without collaboration within the network (open source included), no action is possible. Their idea is linked to the building of an alternative space in a very personal, subjective, individual, non-expansive and local way.

Returning once more to the extremes of an utopian and a dystopian perspective, the brightest possibility would be to understand that politics can be about empowering action — and not only about contemplation and deliberation, as in ancient Greece (Arendt 1998). Therefore opening more possibilities for ordinary people to act in public could be a form of (re)engagement in politics. In that scenario individualistic antipolitics would be declined in as so far as each idea, project or proposal would still be dependent on a plurality in order to become action (even if this plurality can be considerably smaller than the majority usually required by formal democracies; and surely that suggests that plurality would emerge stronger than consensus or deliberation). The intrinsic need of financial and community support to execute projects through crowdfunding creates a kind of gatekeeper for individual moral and judgements, and, at the same time, create free and open spaces for the most different sort of dreams and initiatives.

However political theory also suggests a dark possibility. For instance Weber’s (1986) late writings argue that his disavowal of the bureaucratic administration could be overcome by a charismatic leader — a concept usually employed as opposed to tradition and legal forms of authority in Weberian theory. He argued that a leader was necessary to revitalize the arguably inefficient German government. The problem was the “completely outmoded system of management by notables” (Weber 1986:130), that is to say, old professional and bureaucratic politicians, which was actually preventing the brightest intellectuals from engaging in politics. Charisma would be the basis of this new political leader, who should be strong enough to dissolve the parliament if needed. Explicitly he argued for a strong president, empowered through election, as an alternative to challenge the power of the parliament, the outmoded system.

Weber passed away in 1920 and between his and Arendt’s oeuvre Germany testified the emergence of the National Socialist dictatorship. A leader in fact was granted these powers in 1934 by almost 90% of the voters. A leader that would merge the role of president and chancellor, dissolve the parliament and opposing parties and interrupt all efforts to revive democracy in Germany after the Great War. Ironically a leader whose terror is one of the most important inspirations for Arendt’s first writings on politics and philosophy. In sum, politics based on individual impulses, even if controlled by formal institutions, can destroy democracy and politics.

This sort of theoretical questions are the background of this research: the more practical predisposition of people engaged with crowdfunding, as well as their justifications in terms of world views, are at the foreground of this research; at the same time the background is set by these overarching dilemmas of political theory, such as freedom, political action and what constitutes a democratic and active public sphere.

NOTE: [LM] Relating the literature review to your specific research questions should be a key goal throughout the discussion over page 15 to 30. Overall, this is a fairly rich and sound discussion, especially when it comes to Arendt and Wolin. The last section on Weber and charisma is not necessarily linked in a clear manner to the earlier sections. My main concerns is that this rich discussion is more of an analysis of different developments in political theory, rather than a review of the literatures that accompanied and informed your research questions. I.e. the link to your specific questions is not made sufficiently clear throughout. I also think that much of this discussion is more appropriate for one of your substantive chapters than a literature summary, so there could be some cutting and pasting to do once you have a full draft. For the most part, I think that quite small terminological changes are all that is needed to make these linkages to your research questions clearer: I.e. most of the current analysis can stand in some form in your thesis, it simply needs some reframing so that it bears upon your research questions more directly. I also think other literatures should be mentioned under ‘literature review’: i.e. more recent work in economic sociology on platform capitalism or new relationships between private actors and the state. You need to briefly state your awareness and review of these highly relevant bodies of work.

NOTE: [JAR] Is is about the common association of technology with emporwement + freedom *or* is it about cultures/ideologies around tech development? *Or* both?
