= 2. Methodology and Literature Review
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:toc:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_2^nd^ year PhD student in sociology, University of Essex_

Two recurrent topics on contemporary political theory are extremely relevant in order to address the possibility of politics through crowdfunding. One of them comes from the _antipolitics_ stream (Schedler 1997), and it argues that many institutions and practices that were supposed to be political are, in fact, mitigating politics as such. According to these critiques, a spread dissatisfaction with the means and ends of these institutions and practices has lead to a general disavowal of politics _per se_; politics, therefore, starts to be taken with a skeptical and cynical tone, to be perceived as corrosive to the society. By these means, it ceases to be the realm for conflicting interests, passions and desires. Furthermore, politics end up either as technical matter relegated to specialists, or as a rational pursue for consensus -- both alternatives sustained by a strong belief in a impartial set of procedures (Mouffe 2005). The other topic, subsequently, is one way to approach this contemporary political condition through the critique of rationalization and of utilitarianism (Weber 1976, Collins 1986), as well as through the underneath and widespread individualism and disconnectedness related to these ideals (Bellah _et al_ 2008). This set of critiques argues that in the last centuries traditional republican and religious morals have been fading out in terms of relevance, being replaced by a culture that fosters the pursue of self-interest in a way that does not create, neither sustain, social ties (Bellah _et al_ 2008, Graeber 2011).

Crowdfunding is a phenomenon that has been engaging millions of people, online and offline. The primary hypothesis of this research emerge as a reflection upon this fact, that is to say, supposing that this engagement might be a source of politics. The assumption is that there is a multitude of projects out there to be funded, and that the mechanism that requires public support (in the form of monetary contributions) that select which ones will actually be executed is a mechanism that can be read as politics: there is a public deciding what really happens in society, there are conflicting projects and interests, 

To afford a proper sociological exploration of this hypothesis, the idea is to explore the nature of the social relations and world views created by crowdfunding, specially in comparison to traditional approaches to traditional politics (organized parties and social movements, or institutionalized procedures such as voting) and entrepreneurship (activities primarily focused on establishing a profitable business). 

Initially what needs to be covered is the specific nature of crowdfunding initiatives. A naive approach would see it as merely about making things happen since projects are proposed and backed by ordinary people. Alternatively, a dystopian point of view would claim that it is all about business, since most of crowdfunding platforms emerged as startups (and, indeed, a couple of them actually became millionaire companies). Yet a more utopian and libertarian standpoint could label it as a political discourse and action highlighting how crowdfunding confronts incumbent institutions as the primary (and, sometimes, unique) sources for funding. Surely these are only a few stereotyped possibilities, but the objective is to understand how different ideals and purposes are balanced within crowdfunding projects and communities.

Assuming that is there room for discussing politics in this scenario, the next step is to understand the specificities of that politics. By focusing on how people involved in crowdfunding see themselves in the world, in relation to others in society, it is possible to understand how their world views signify their actions and practices. In other words, by taking that into account, it is possible to depart from what they deliberatively do and expect (or, perhaps, what they deliberatively omit and disavow) and compare to more academic approaches to political action in order to understand the peculiarities of such politics. 

Finally, assuming some understating of crowdfunding and of its politics, the third task is no grasp the kind of society is being pursued by these communities. If they are political in some sense, this research investigates how they are concealing competing interests, what means and ends are at sake in this entrepreneurship, and how all that relates to contemporary political theory.

The three areas briefly describe above have been guiding this research, they refer to three research questions that could be summarized as: What is the focus of crowdfunding? What are the specificities of crowdfunding politics? How does crowdfunding relate to political and economical institutions?  This chapter draws a theoretical and methodological framework in order to address these questions. It starts by discussing the data collection strategy, its justifications and limitations. Next it presents a literature review on political theory, namely discussing the mitigation of the political realm and individualism in current society. Finally a short discussion on how to link the empirical (data collection and analysis) and theoretical assumptions in order to offer a grounded sociological description of crowdfunding and contemporary politics.

== Methodology

According to Beer and Burrows (2007), the appropriate way to address the ‘dynamic’ internet is to opt for descriptive accounts, reconceptualizing spheres that are being redefined by the online communities and tools. For them, the challenge is “to construct more complete and differentiated descriptions of what is happening” and to give an account of “who is involved, and the practices entailed, in order to inform and enrich new concepts or reworkings of our theoretical staples” (2007). Moreover, given the emerging aspect of crowdfunding, it is not possible to follow Weber’s (1976), or even Boltanski and Chiapello’s (2011) approach based on document and text analysis (Land and Taylor 2014). Alternatively, the focus will be on interacting with people involved in crowdfunding through semi-structure interviews in order to build this descriptive approach.

Moreover when dealing with social research on science and technology there are two commonplace extremes: either social reality if determined by the technological artifacts (leaving no agency for humans) or technological artifacts are fully interpreted and signified by human agency (considering technological artifacts merely subjects of human action). The idea is to be in-between these extremes, an approach that “allows us to understand technological innovation and social changes as an interplay between solid technological capacities, and the social situation of their development and use” (Allen-Robertson 2013:12). In other words the idea is to be sensible to the possibilities and limitations brought to life by technological artifacts, but also to the appropriations and semantics developed through their usage -- what Hutchby (2001) called _affordances_.

That said it worth it to reinforce that the technology put forward by crowdfunding platforms is not at the core of this research as much as the possibilities opened by it. The technology is relevant as far as it can be used to understand changes in the dynamic of society. As the next chapters will explore, that is the case, for example, of the way a certain group of social actors perceives others around them (other people, other institutions) depending on how they embrace intellectual property (proprietary or free and open source code). But that is also the case of more broad social impacts, such as the resurgence of the idea of the _prosumer_  due to new communication possibilities and cheaper alternatives for production (Ritzer & Jurgenson 2010) -- on the one hand, internet decentralized communication, that is to say, in a different way from newspaper, radios and TV centralized emission and distribution, the internet allow every one involved to receive _and_ send information all over the network; on the other hand, a couple of decades ago, in order to spread a text one has written, one would need to spend a huge amount of paper, ink and oil to print it and distribute it; nowadays, with internet access, it is basically free to write and publish a multitude of texts online.

Therefore the focus of this research is on the world views of people involved in crowdfunding. The idea underneath this methodological choice considers that social actors’ conceptual framework can limit and determinate action or, yet, can completely reconceptualize it (Ragin 1994). Moreover, “at any particular time, one should be prepared to find that governing concepts can, and often do, lag behind the behavioral requirements of the case” (Ragin 1994:92). Having in mind the aforementioned defense for a descriptive procedure when it comes to internet (Beer & Burrow 2007), the interviews will be interactions with people engaged with crowdfunding focusing on their ‘governing concepts’ to understand their behavior, that is to say, their engagement with crowdfunding. If this approach differs from Weber’s (1976) and Boltanski & Chiapello’s (2011) historical and document data collection, it is similar to Weber’s assumption that psychological sanctions originated within some protestant sects had unforeseen behavioral impacts on society, and it is similar to Boltanski & Chiapello’s assumption that a certain ideology can justify not only the engagement with capitalism, but always explain different and changing engagement throughout time.

Through these means the interviews offered a primary source for the construction of a grounded theory approach. One problem of grounded theory is the risk of ending up with theory that is strictly tied to the field where the data was collected (Blaikie 2010). When it comes to this specific research, this problem is flagrant when a more quantitative approach might fail to prove the relevance of crowdfunding. For instance, the amount of money changing hands, the market value of platforms, the number of people involved, or the greatness of the projects being executed would probably be weak measures to compare this new communities with incumbent institutions such as corporations and governments. However given the contemporaneity of crowdfunding and the potential of internet communities to impact incumbent institutions (Allen-Robertson 2013, Ritzer and Jurgenson 2010), this grounded theory can be relevant to comprehend a wider movement that includes different branches of internet groups, such as crowdsourcing, sharing and collaborative economy, social networks, free and open source software and hardware, makers movements, hacker and open spaces and so on. Mapping the moral grounds (Weber 1976, Boltanski & Chiapello 2011), the conceptual framework (Ragin 1994) of crowdfunding is a way to pinpoint ideals that might be relevant for many of this new communities (for example, as Taylor & Land 2014).

Considering the approach described above, the interviewing method offers in-depth qualitative understanding of the world views related to the emergence of the crowdfunding phenomenon. The analysis of this material enable the intended research to make inferences on the social, cultural, economic, moral and political foundations of these world views. The aim is to assess their point of view, and to inquiry about how they locate themselves into society – i.e. to grasp their own world views, values and references.

There are a vast number of crowdfunding platforms. Although Wikipedia (2015) lists roughly 100 active platforms,footnote:[Roughly one year ago, in May 2014, this same Wikipedia article listed only 60 crowdfunding platforms.] this is clearly an incomplete list. For example, Catarse is a Brazilian platform built in an open source license,footnote:[Catarse (2015a) operates under MIT License.] that is to say, anyone is free to use their source code to build a new platform. According to Catarse’s wiki (2015b) there are 15 active platforms based on their source code (roughly half of them operating in other countries than Brazil, such as USA, Canada, Denmark and Argentina). Most of them (including Catarse itself) are not included in the Wikipedia’s list. This adds a new layer for reflection upon the interviews of this research: how to grasp the variety of platforms (and, probably, of different purposes behind them) during this qualitative investigation. In order to get in touch with as many world views as possible, two main strategies were adopt during the search for interviewees.

First, the interviews were held with three different profiles: platforms founders and staff, people submitting projects to these platforms (project creators), and people backing – and spreading the word about – these projects (project supporters). For each founder or staff interviewed, the idea is to interview two project creators and three project supporters. Therefore, the idea is to get the point of views from different roles within the crowdfunding community. Surely these numbers are more targets than clearcut objectives, specially because every founder is also a project supporter (and, most of the times, a project creator), and most project creators usually have backed some project before. But having in mind these three profiles allows the analysis to move from an arguably idealistic point of view (whether it is business or common good based, just to mention two opposing examples) of founders, for example, to more pragmatic standpoints for project supporters.

Second, there are three main characteristics of crowdfunding platforms to be taken into account. This characteristics are related to how platforms design the business model for the projects they host, to the way the they deal with their own intellectual property, and to the curatorial layer defined by their terms of service. Some details about four of these platforms might help to illustrate these points: Indiegogo, the first crowdfunding platform,  and one of the most widely known; Kickstarter, the so called largest crowdfunding platform in the world;footnote:[The “largest” is read over the news without an objective measure or comparison with other platforms (e.g. Canadian Press, 2013). Anyhow Kickstarter’s numbers are eye-catching: almost 1 billion dollar dollars pledged, more than 55 thousand projects funded, more than 5 million backers, i.e. people who supported at least one project (Kickstarter 2014).] Catarse, the first one launched open source; and Patreon, the first one to offer a recurring funding scheme (instead of one-off contribution to a specific and dated project, the idea is to support an on going project with smaller recurrent contributions).footnote:[In terms of the kind of projects hosted by these platforms, all of them are very open. Even if they were created with some kind of public or projects in mind (for example, Indiegogo and Kickstarter primarily focus was on creative projects, while Patreon and Catarse focuses are one on artistic and cultural projects), they are open enough to host projects that vary considerably: from movies and music, to software and hardware technology development, including sports, civic actions, political organization, and education. Hence the three characteristics taken into account are more internal to the organization of the platforms than to the contents visible online for the ordinary user.]

When it comes to their business models, the basic difference between the Indiegogo, Kickstarter and Catarse is that the first one charges a higher fee (a percentage over the total value pledged), but the project creator can collect the money pledged even if the target is not reached – this model is known as ‘keep-it-all.’ On the other hand, the other two charge a smaller fee (also a percentage over the total value pledged), but if the project target is not reached, all the money returns to the backers and no fees are collected (nor any funds is passed to the project creator) – this model is known as ‘all-or-nothing.’ Crowdfunding campaigns under this last model tends to engage not only the project creator, but also its supporters – i.e. the role of spreading the word about the campaign is crucial to make the funds be collected. Finally, Patreon inaugurated the idea of a ‘recurring’ contribution: as aforementioned, instead of backing a very specific project, usually with a higher amount (for example, 20 dollars for the recording of a music album), the idea is to contribute with smaller amounts to an ongoing project (for example, 2 dollars per month for a certain musician, or 2 dollars each time this musician uploads a new song). If the ‘all-or-nothing’ scheme is said to foster engagement, this engagement tends to fade away once the project is finished (in the example, when the recorded album is delivered). Alternatively, the ‘recurrent’ method would extend the engagement between project creators and its supporters for an undefined period of time, but arguably, a less intense engagement as it lacks a specific deadline and target.

Catarse is the only platform among this group that is open source; the other three platforms are based on proprietary software. Interestingly there was a huge difficulty in reaching someone from Kickstarter to be interviewed for this research. Also several interviewees (from other platforms) told the very same story: Kickstarter do not talk with ‘copycats’, as one interviewee told me. If Indiegogo, Kickstarter and Patreon, by protecting their code, suggest that they operate as more traditional business, protecting the engine of their business and looking for customers (project creators as well as users to support them) -- and, regarding Kickstarter, eventually getting involved in judicial cases around patents for their ‘all-or-nothing’ crowdfunding model (Purewal 2011) -- Catarse departs from an heterodox market philosophy, offering its source code openly, and with no apparent fear that some ‘copycat’ would represent a risk to them. In fact, Catarse developers seem to express the completely opposite idea: they are seem helpful with other developers using their source code (they are very active in their collaborative channels: their open repository and their open mail list dedicated to developers). To be sure the idea is not to deterministically affirm that embracing the option for proprietary software is tied with less friendly behavior with others in the field of crowdfunding, but to take that into account. For instance,  one of Catarse’s main programmers told me that there were some conversations between Catarse and  Indiegogo in which they considering to merge Indiegogo’s code base with Catarse’s one. Even if the merging had never occurred, different stories might point in different directions, requiring the analytical phase to pay attention to specific combination of characteristics that can afford to explain this different behaviors.

Finally, considering the curation, Kickstarter, Catarse and Patreon tend to have a more prominent curatorial layer: people from the platform tend to work together with the project creators. The focus is on refining the content to be published, in order to assure that the project has good chances of being funded -- that is the difference between having a thicket or a garden, as some interviewees put. Indiegogo, in that sense, is more open and users can submit projects without the explicit platform ‘seal of approval.’

In that sense, these three characterises -- intellectual property (proprietary or open source software), business model (keep-it-all, all-or-nothing, recurrent), and content policy (a more open, or a more controlling curatorial layer) -- are key points to link the more open word views sustained that the interviewees might recur to to the core concepts in case: individualism and disconnectedness, and, from the, to address the contemporary condition for politics. Moreover, this initial group of platforms cover crowdfunding in different countries. Patreon is mostly and USA platform, while Catarse is mostly focused in Brazil. Kickstarter was launched officially in the USA, the UK and Canada (Canadian Press 2013). And Indiegogo (2012) hosts projects from all over the world, working with five different currencies (American Dollars, Canadian Dollars, Australian Dollars, Euros and British Pounds). However, in addition to these four platforms, several other have their own peculiarities, offering different points of view that should be considered for the sake of this research -- for example Cinese, a Brazilian crowdfunding platform focused on meaningful meetings supporting non-traditional learning, Beacon, a platform for independent writers and journalists to get recurrent contributions and for the readers to have access to all their archive, or MedStartr, a platform based on Catarse’s source code, built exclusively to crowdfund medical projects (their lead is to promote medical innovation according to ordinary people interests). By focusing on a sample distribution that cover different combinations regarding  different people profile, the three characteristics regarding intellectual property, business model and content policy, and the variety of niche initiatives, this research tend to cover different backgrounds, cultures, demographics and geographic differences.

The sampling and data collection phase starts with the publicly available channels to contact the platforms: email, contact form, social media etc. I will be reaching them, explaining the purpose of the research and asking for collaboration. If they opt to cooperate, I can ask for interviews, and also ask if they can help me in recruiting within their users (project creators and supporters). For some of the platforms, I have no other access to them – this is the case of Indiegogo, Kickstarter and Beacon. If they refuse to cooperate, the alternative is turn to other crowdfunding platforms in order to keep a good sample distribution according  the variables discussed in the last paragraphs. However, for the other platforms, I have already better access to data – this is the case of Catarse, Cinese, MedStartr and Patreon. For these platforms I have friends, or friends of friends, that can put me in touch with founders, current or former staff, project creators and project supporters. There is the risk of bias, but it can be minimized since the contacts mentioned in the last paragraphs will be the trigger to a snowball process, that is to say, I will ask them if they are happy to suggest someone else to be interviewed, making me reach people outside my regular network, and expanding the sample from there.footnote:[It is worth it to disclosure that I have projects crowdfunded through Catarse and Nós.vc (a platform similar to Cinese), and I have also contirbuted to projects on Catarse, Nós.vc, Kickstarter and Patreon. Contacts from these projects will not be considered for this research in order to minimize bias.]

The focus of the semi-structured interviews will be to comprehend the point of view of the interviewees about society, business, politics and economics – especially (but not restricted to) when it comes to crowdfunding. In order to better grasp these views, the first part of interviews will not focus on crowdfunding, but on the interviewees’ perceptions of themselves within society – i.e. how they position themselves facing a given cultural, political and economic context. Yet this initial part will cover the interviewee’s aspirations and ideals when it comes to the social context. The idea is to adopt a funnel-shape questioning technique, narrowing down the subject (namely, crowdfunding) towards the final part of the interaction. By these means, the participants might get to the specific subject spontaneously. Consequently, the role of the interviewer is to conduct the interviewee in such direction only if certain topics do not emerge in that more spontaneous way (Kvale and Brinkmann 2009). Therefore it is expected that the first part of the interviews covers aspects such as the interviewees’ general opinion on government, on corporations, on civic organizations, on political views and attitudes. The intention is to get these aspects linked with their personal initiatives (linked to crowdfunding) without intervention, i.e. without stimulating the interviewee to relate them to crowdfunding. This technique is employed to avoid the risk of making the interviewee stick to one or other concept just because the interviewer mentioned it – and not because it was already part of the interviewee’s own point of view (Kvale and Brinkmann 2009).

Next the semi-structured interviews may vary among different profiles of interviewees. The next phase of the funnel is the interviewees’ relationship with a certain crowdfunding platform. For founders and managers, the conversation will focus on how they situate their business within society, their choice to found, or work for, a crowdfunding enterprise. For project creators, the exploration will shift towards the reasons why they opt to count on a crowdfunding instead of other funding possibilities. For supporters, the focus will be on what has driven them to take part in crowdfunding campaigns.

Finally, after objectively introducing the topic of crowdfunding, the last block of the interview will address the opinions and views of the interviewee about crowdfunding in a broader sense. The investigation will inquiry about what interviewees expect from crowdfunding, how they position it with ‘traditional’ social sphere (such as business, politics or culture), and yet check a more aspirational approach, in order to grasp their collective and individual expectations related to crowdfunding mechanisms.

The interviews, when possible, will be held in person (when financially possible) or remotely (using telephone, VoIP or video conference). The context that will be lacking in the remote interviews is not considered to represent a relevant loss of data in this particular case as (among other reasons) most of our participants are expected to be well articulated and used to express themselves in public (they will be entrepreneurs who found and manage online platforms, or they put their own projects online to public, or yet they voluntarily engage with these projects, spreading the word about it). The content of the interviews will be recorded (according to the consent of the interviewee), transcribed and analyzed. It will be up to the interviewee to be anonymized or not. Next the focus will be on the coding and condensation of meaning. The idea is to condensate the most relevant units, and use the coding to categorize the bits of information. This qualitative analysis technique will lead to a grounded theory approach (Kvale and Brinkmann 2009). The next step will be to triangulate this content with other sources, with data collected from the platforms themselves and from the interviewees’ online profiles. This process allows a contextual interpretation of the meaning of these units of information, as well as validation of the content of the interviews – another basis for a grounded theory approach (Kvale and Brinkmann 2009).

== Literature Review

The focus of this research, identifying and describing possibilities of politics within crowdfunding communities, is based on critiques from political theory towards the possibility of political action and engagement in contemporary society. Most of this framework discusses the nineteenth and twentieth centuries modern world, specially when it comes to  sociological, political and philosophical implications. On the one hand, these oeuvres are reflecting upon the outcomes of the eighteenth century revolutions in the USA and in France (for example, Tocqueville 1986 or Arendt 1973); on the other, they are rethinking these results in the light of the terror spread during the two World Wars, and of the democratic states emerged thereafter (for example, Bellah _et al_ 2008 or Arendt 1998). A commonplace in such literature is to acknowledge the achievements of the Enlightenment, but to reinforce how it failed in completely putting forward some of the ideals that were at its core. For example Arendt (1973) did not deny the importance of modern political institutions such as parties and elections; they opened the political career for people from the lower classes, and the notion of forming an elite through the party replaced the old elites based on birth or wealth. However she also emphasized that the party framework is less meaningful in providing a government _by people_ than in recruiting, _from people_, an elite to govern them. In other words, the central question here is not the democratic (or republican) institutions _per se_, but the tangible possibility of political action for ordinary people.

The first part of this section draws the framework of these critiques towards modern state, its democratic assumptions and failures. Next it discusses the contemporary debate built around this sort of flaws bringing in discussions around the arguably decline of political engagement in the turn of the twenty-first century. Finally it sets some challenges in thinking political action in contemporary society. The idea is to grasp the difficulties in studying politics today through the traditional approaches to political institutions, or, to put it differently, to take theory into account to understand how political action can be reinvented within nowadays tensions and conditions.

=== Modern institutions and its discontents

In terms of politics most of the ancient world was traditionally based on a distinction between the public and the private, two separated realms were people would pursue different objectives through different means. However this scenario was changed considerably during the last centuries: “the emergence of the social realm, which is neither private nor public, strictly speaking, is a relatively new phenomenon whose origin coincide with the emergence of modern age and which found its political form in the nation-state” (Arendt 1998:28). Therefore, there is something essentially modern in the constitution of nation-states, and that also relates to one of the core distinctions within political theory, namely, the public and the private realm. Therefore following the emergence of the institutions created during that transition is a way to understand how this new political framework was forged. Moreover this history sets the background for the subsequent criticism regarding the successes and failures of the modern project for politics.

The division between public and private was forged in ancient Greece, when one should keep the pursue of private interests to the boundaries of the household, the core place for one’s private life. That is to say that only citizens who have provided enough for them and their families were allowed to participate in the public life. This requirement was based on the role expected of this citizen when engaged with politics:

[quote]
Private wealth, therefore, became a condition for admission in public life not because its owner was engaged in accumulating it but, on the contrary, because it assured with reasonable certainty that its owner would not have to engage in providing for himself the means of use and consumption and was free for public activity. Public life, obviously, was possible only after much more urgent needs of life itself had been taken care of (Arendt 1998:64-5). 

Modern age gave birth to the social realm which is neither public nor private -- and, as a consequence, dislocated considerably what was understood as public. While private life was characterized by providing the household through labor, and while the public realm was the place for action and speech, the social has taken the political space from the public, printing on it important differences: now government acts as a gigantic housekeeping organization, looking for provision for a whole nation; that is to say, labor, once relegated to the private life, now is not only allowed but placed at the center of political life. For Arendt (1998:28-9) the dividing line between the household and politics

[quote]
is entirely blurred, because we see the body of peoples and political communities in the image of a family whose everyday affairs have to be taken care of by a gigantic, nation-wide administration of housekeeping. The scientific thought that corresponds to this development is no longer political science but ‘political economy’ or ‘social economy’ or _Volkswirtschaft_, all of which indicate a kind of ‘collective house keeping;’ the collective of families economically organized into the facsimile of one super-human family is what we call ‘society,’ and its political form of organization is called ‘nation’ (Arendt 1998:28-9).footnote:[Arendt does not justify the use of the German term _Volkswirtschaft_ in this passage. Arguably it has no direct translation into English. Nonetheless it refers to a kind of economics driven by the nation’s needs, the needs expressed by its households as well as by the private and public sector; in some languages, as in Dutch or Latin for example, its translation is similar to _national economy_ (_algemene economie_ and _oeconomia nationalis_ respectively).] 

[quote]
The Puritans were not uninterested in material prosperity and were prone when it came, unfortunately, to take it as a sign of God’s approval. Yet their fundamental criterion of success was not material wealth but the creation of a community in which a genuinely ethical and spiritual life could be lived (Bellah _et al_ 2008:28-9).

Alternatively, the republican strand is illustrated by the standpoint of one of the Founding Fathers, Thomas Jefferson:

[quote]
In general, Jefferson favored freedom of the person from arbitrary state action and freedom of the press from any form of censorship. Yet he also believed that the best defense of freedom was an educated people actively participating in government. The notion of a formal freedom that would simply allow people to do what they pleased -- for example, solely to make money -- was as unpalatable to Jefferson (Bellah  _et al_ 2008:31).

In both cases, Bellah _et al_ (2008:31) reinforced,individual “freedom only took on its real meaning in a certain kind of society with a certain form of life;” without that moral principles, freedom would lead to social corrosion and tyranny. However, in later on the nineteenth century both strands were challenged by two sorts of individualism that withdrew this large social context. On the one hand, utilitarian individualism focused on individual self-improvement, reflecting the liberal believe that if each member of a group pursues her or his own interest, the whole community would testify the emergence of social good. In this case, the idea of interests was basically set by another Founding Father, Benjamin Franklin, whose views were determinant for framing the capitalist motivation for work and accumulation (Bellah _et al_ 2008, Weber 1976). On the other hand, expressive individualism claimed no interest for material accomplishments, but in an individual and subjective pursue for experience through life. The richness of life would be achieved nurturing the self with luxury, sensuality, intellectual and all sort of experiences one could feel to understand and express oneself in contact with nature, withe the universe as a whole. Individual freedom is the norm and a disavowal for social conventions marks the tone of this branch of individualism. Therefore, if the earlier strands do not contrast individualism and the public common life, these sorts of individualism do it by conceiving a sort of self-contained individual:

[quote]
What is at issue is not simply whether self-contained individuals might withdraw from the public sphere to pursue purely private ends, but whether such individuals are capable of sustaining either a public _or_ a private life. If this is the danger, perhaps only the civic and biblical forms of individualism -- forms that see the individual in relation to a larger whole, a community and a tradition -- are capable of sustaining genuine individuality and nurturing both public and private life (Bellah _et al_ 2008:143, emphasis in original).

Hence, this discussion linking different realms of life (such as the public, private and, arguably, the social), together with the discussion of the background for what is pursued in each of these realms, works as a theoretical starting point to look at contemporary political institutions. Having in mind the individualistic and self-determined world views emerged in the last centuries, and going back to Arendt’s critiques, the idea is to understand if the world imagined during the Enlightenment is conceivable nowadays -- in other words, if the rupture between individual and civic society brought up by individualism is compatible with the virtues expected from governing bodies. Traditionally the answer to questions like that are pointing in a negative direction. One element of arguments in such direction if calling into question the effectiveness of free markets in granting freedom to ordinary people, that is to say, to ask if rationalized economic sphere would promote the social good (or, on the contrary, if it would prevent ordinary people to act politically):

[quote]
The market idea, as Adam Smith proudly announced, banishes the authority of persons; it is a system of exchange which is legitimate only as a system. The closest we come to an image of control, reassurance, or guidance is the ‘invisible hand’ which assures fairness. But the invisible hand is also an abstraction; it is attached to the body of no single human being (Sennett 1980:43).footnote:[Interestingly Sennett (1980:44) also argues that this economic behavior compromised not only ordinary people potential for action, but the core freedom they were suppose to inherit from such a society: “The market ideology promised the consummation of individual freedom of action. The market in practice was anti-individualistic. It displaced masses of peasants from their land, whatever their own desires to remain. At the moments when the supply of labor in cities exceeded the demand for labor, there was in fact no labor market. If an employee did not like wages an employer paid, he could go starve; there were plenty of others to take his place … The market system of the last century, rather, made the concepts of community and individual ambivalent, and ambivalent in a peculiar way. No specific human being, no human agent, could be held accountable for disturbances in these realms.”]

But this critique is extended to the public realm as well. For Arendt (1998:68) society has become “an organization of property-owners who, instead of claiming access to the public realm because of their wealth, demanded protection from it for the accumulation of more wealth” (Arendt 1998:68) -- that is to say, the logic of the instrumental individualism has taken down the republican strand. This transformation has to be understood according to the specific ways through which modern societies have developed into representative democracies, a constant struggle between emphasizing the anew claimed by the American and French revolutions on the one hand, and, on the other hand, the will to consolidate the ideal of freedom in a stable institution. For instance Jefferson had a particular standpoint among the Founding Fathers regarding the role of the constitution in this process: in ideological terms, he wanted the constitution to be strong enough to guarantee that no hostilities will take place in the political realm, nonetheless, in order to reinforce the founding anew, this same constitution should also be flexible enough to be revised from times to times. In practical terms, the effects of these thoughts can be seen in the representative democracy model and in its well established ways to participate in the political realm: elections, elected officials, senators, representatives, parties and voters (Arendt 1973).

Perhaps this new institutional scenario has failed in fulfilling its original intents. Critiques appeared as early as the 1920s, for example, when Dewey (1954:118) affirmed that “skepticism regarding the efficacy of voting is openly expressed, not only in theories of intellectuals, but in the words of lowbrow masses: ‘What difference does it make whether I vote or not? Things go on just the same anyway. My vote never changed anything.’” In other words, this scheme was unable to extend the perception of participation from representatives to represented: when it comes to politics, citizens are disinterested and this fact can be found not only “among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage. Contempt for the law and the system also shows up regularly among the favored and highly placed” (Jaffe 1997:78). Sniderman and Bullock’s (2004) idea of ‘menu dependence’ involves a very similar description of how ordinary people have a very discrete participation in politics. According to them, “citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties” (2004:338). The idea is that citizens are not free to compose their own menu of political choices, but only allowed to pick up one from a menu pre-established by parties and political elites. Yet Wolin’s (2004:428) analysis of contemporary politics adds another layer to this branch of critiques: for him “in both, the political and the economic context, contract appears as the essential condition of power”. In other words as the market economy would operate in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state would operate in a way that concentrates the (political) power in the hands of the political elite. By themselves the functioning of these both institutions are expanding the gap between rich and poor, rulers and ruled. And, as Arendt (1973:253) suggested, underneath this wave of critiques towards modern society, there is the displacement of the public realm itself, as well as the dilemma Jefferson had in mind:

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of being republicans and of acting as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens. 

This two-folded movement of degradation of the public and of inflation of the private has granted the space for corporations to extrapolate their private bounds and act within the public realm. Political decisions -- already distant from ordinary people -- gradually started to take into account a logic that does not pertain to the public realm, namely the logic of the market economy (Wollin 2004). 

In spite of advancing in many aspects, this process of modernization had a devastating side-effect for politics: by limiting the space for political action it consolidate the public realm as a place for private affairs. In Arendt’s (1998:46) words, “the character of the public realm must change in accordance with the activities admitted into it, but to a large extent the activity itself changes its own nature too.” The type of skills and activities held within these spaces were also impacted by these transformations. The importance given to labor and provision (formerly banished from the political), and to speech and action (formerly the core of political activity) also assume a different balance. Labor and wealth accumulation made sense as far as the household provisions required them. Excelling in speech and public action in politics was a public virtue which the whole body of citizens would benefit of. Interestingly within the modern social realm labor was introduced to the political space and, at the same time, speech and action was dislocated to the private: “while we have become excellent in the laboring we perform in public, our capacity for action and speech has lost much of its former quality since the rise of the social realm banished these into the sphere of the intimate and the private” (Arendt 1998:48). 

From that perspective it is possible to comprehend the lack of interest and, arguably, trust in politics; also it is possible to address the endless interest in making money. These both critiques are overlapping aspects in many critiques towards representative democracy, basically because they change what happens in the political realm, as predicted in the post-politics and antipolitical streams discussed in the next section (Arendt 1973; Bellah _et al_ 2008; Wolin 2004; Mouffe 2005).

=== Post-politics and antipolitics

These changes regarding the political institutions of the modern age ended up nurturing two kind of critiques On the one hand, there is a very optimist approach to the rationalization and individualization processes. This stream, known as post-political, claims that the possible flaws in political institutions are to be overcome with further development of these same institutions, according to same values that brought them to life. In other words, more emphasis on the rationalization would solve this possible flaws. Habermas (1992, 2005), for instance, argue that there are two instances in society -- System and Lifeworld -- holding different rationalities. The rationalized and instrumentalized one osts the market and the political institutions, and this is the realm in which the individual interests are transcended in the name of anonymous demands, realized by means of instrumental, strategic action. This kind of rationality is increasingly detaching itself from the social structures, taking the shape of autonomous organizations that only communicates through a mediums such as money and power -- or, alternatively, that holds no commitment to other norms or values. Economic and administrative rationalities are the main themes here. The other instance, the communicative one, would be the place were a individuals would rationally pursue a deliberation, rationally agree on the functioning of the instrumental institutions. Hence, there is no value judgment between instrumental or communicative  rationality; rather it is conjectured that each rationality is restricted to its own domain. The problem -- part of Habermas’s patology of modernity --  is that communicative rationality have been colonized by the instrumental logic. The author defends the need for reconnecting these spheres avoiding the colonization, keeping the differentiation and autonomization of these realms. He states that only then will communicative rationality have space to collectively elaborate the ultimate aims for the social good.

Habermas’s diagnosis describes a scenario similar to the one addressed in the last section, but his agenda calls for a rational approach to argumentation, consensus and deliberation. Against this rational approach, some authors defend that rationalization would lead to a more anti-political environment. Instead of using rationality to promote consensus in a post-political space, the idea is that this process would mitigate the very nature of politics:

[quote]
Instead of trying to design the institution which, through supposedly ‘impartial’ procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant ‘agonistic’ public sphere of contestation where different hegemonic political projects can be confronted (Mouffe 2005:3).

Therefore, the lack of trust and interest in the political institutions an be described as antipolitical through at least two arguments: in the one hand, it contributes to the mitigation of the public realm, which is suppressed by a self-regulated private one, the market (Schedler 1997); or, alternatively, whatever remains of the public realm starts to operate according to a logic inherent to the private sphere -- what Schedler (1997) calls an inverted Habermasian colonization.[4] To be sure, Wolin (2004:588) highlights that both -- state and market -- are appropriating the methods of one another: “it is not that the state and the corporations have become partners; in the process, each has began to mimic functions historically identified with the other.” According to him, corporations’ move includes being in charge or funding health care, education and other welfare affairs; in parallel, governments’ move includes applying profits logic, notions of efficiency and management, to buoy its own actions.

=== Technology and crowds: some notes on culture and politics

Start with Dewey and technological optimism.

=== Action and politics

… (Arendt, Mouffe, Sennett?) … +
… Intersection with economy, money and lifestyle (Graeber and Dodd)? …

== Analysis & Overarching theoretical questions

. World view when it comes to action (self-interest and politics, the focus is the realization of projects, not necessarily money)
. How they position they self in the world (resignifying money as a process, not a thing)
. Possibility of politics
. What is the nature of the political participation of crowdfunding?
. What to expect from it, dark and bright side (Weber, Arendt)

== TODO

* Add Ritzer on Prosumption (2014 & 2015)
* Consider hypothesis on what kind of morals are expected to be found within crowdfunding communities
* Add a balance of the current sample

== References

Allen-Robertson, J. (2013). _Digital Culture Industry: A History of Digital Distribution_. Basingstoke and New York: Palgrave Macmilllan.

Arendt, H. (1973[1963]). _On Revolution_. Bungay: Penguin. 

Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.

Beer, D. and Burrows, R. (2007). Sociology And, Of and In Web 2.0: Some Initial Considerations. _Sociological Research Online_, 12(5).

Bellah, R., Madsen, R., Sullivan, W. M., Swidler, A. and Tipton, S. M. (2008[1985]). _Habits of the Heat: Individualism and Commitment in American Life_. Berkeley: University of California Press.

Blaikie, N. (2010). _Designing Social Research: The Logic of Anticipation_. 2nd ed. Cambridge: Polity Press.

Boltanski, L. and Chiapello, E. (2011[1999]). _Le Nouvel Esprit du Capitalisme_. Paris: Gallimard.

Canadian Press, The (2013). Kickstarter Crowdfunding Site Officially Launches in Canada: Canadian Entry Held Up by Red Tape, Financial Regulations, Co-Founder Says. Available at: http://www.cbc.ca/news/business/kickstarter-crowdfunding-site-officially-launches-in-canada-1.1703774 [Accessed: 20 Jan. 2014].

Catarse (2015a). Catarse. Available at: http://github.com/catarse/catarse [Accessed: 17 May 2015].

Catarse (2015b). Sites Using Catarse. Available at: http://github.com/catarse/catarse/wiki/Sites-using-Catarse [Accessed: 17 May 2015].

Collins, R. (1986). _Weberian Sociological Theory_. Cambridge: Cambridge University Press.

Dewey, J. (1954[1927]). _The Public and its Problems_. Athens: Swallow Press.

Graeber, D. (2011). _Debt: The First 5,000 Years_. New York: Melville House.

Habermas, J. (1992[1985]). _The Theory of Communicative Action: Reason and the Rationalization of Society, Vol. I_. Boston: Beacon.

Habermas, J. (2005[1985]). _The Theory of Communicative Action: Lifeworld and System – A Critique of Functionalist Reason, Vol. II_. Boston: Beacon.

Hutchby, I. (2001). Technologies, Texts and Affordances. _Sociology_, 35. Pp. 441-56.

Indiegogo (2012). International Campaigns. Available at: http://support.indiegogo.com/entries/20882543-international-campaigns [Accessed: 20 Jan. 2014].

Jaffe, E. (1997). Our Own Invisible Hand: Antipolitics as an American Given. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 57-90.

Kvale, S. and Brinkmann, S. (2009). _Interviews. Learning the Craft of Qualitative Research Interviewing_. London: Sage.

Kickstarter (2014). Kickstarter Stats. Available at: https://www.kickstarter.com/help/stats [Accessed: 20 Jan. 2014].

Mouffe, C. (2005). _On the Political_. London and New York: Routledge.

Purewal, S. (2011). Kickstarter Faces Patent Suit Over Funding Idea. _PCWorld_. Available at: http://www.pcworld.com/article/241160/kickstarter_faces_patent_suit_over_funding_idea.html [Accessed: 20 Jan. 2014].

Ragin, C. (1994). _Constructing Social Research: The Unity and Diversity of Method_. Thousands Oaks, London and New Delhi: Pine Forge Press.

Ritzer, G. and N. Jurgenson (2010). Production, Consumption, Prosumption: The Nature of Capitalism in the Age of the Digital ‘Prosumer.’ _Journal of Consumer Culture_, 10(1). Pp 13-36.

Schedler, A. (1997). Introduction: Antipolitics -- Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 1-20.

Sennett, R. (1980). _Authority_. New York: Alfred A, Knopf.

Sniderman, P. M. and Bullock, J. (2004). A Consistency Theory of Public Opinion and Political Choice: The Hypothesis of Men Dependence. In Saris, W. E. and Sniderman, P. M. (eds.). _Studies in Public Opinion: Attitudes, Nonattitudes, Measurement Error, and Change_. Princeton and Oxford: Princeton University Press. Pp. 337-357.

Taylor, S. and Land, C. (2014). The Good Old Days Yet to Come: Postalgic times for the new spirit of capitalism. _Management & Organizational History_, 9(2). Pp 202-219.

Tocqueville, A. (1961[1840]). _De la démocratie en Amérique, II_. Paris: Gallimard.

Tocqueville, A. (1986[1835]). _De la démocratie en Amérique, I_. Paris: Gallimard.

Weber, M. (1976[1900]). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.

Wikipedia (2015). Comparison of Crowdfunding Services. Available at: http://en.wikipedia.org/wiki/Comparison_of_crowdfunding_services [Accessed: 17 May 2015].

Wolin, S. (2004). _Politics and Vision: Continuity and Innovation in Western Political Thought_. Princeton and Oxford: Princeton University Press.
