= 2. Methodology and Literature Review
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:toc:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_2^nd^ year PhD student in sociology, University of Essex_

****

*Outline* (~8000-900 words)


. Introduction
.. Original research questions
.. Original theoretical background 
. Methodology & Data collection
.. Interviews: bias of people involved (grasp a specific world views instead of a quantitative assessment of immediate impact)
.. Spirits of capitalism and their cores (Weber, Boltanski and Chiapello, Taylor and Land)
.. Similarities to Weber's, but not able to focus on historical analysis
.. The focus is not to describe them, but their world view (as in Weber, the psychological sanctions differ from the theology of the religion)
.. Secondary data (blog posts, news, social network): external validity and also context (institutional relationship: is they are an isolation bubble, this secondary data represents, at least, the margins of that bubble, how it relates to an external world)
. Analysis
.. World view when it comes to action (self-interest and politics, the focus is the realization of projects, not necessarily money)
.. How they position they self in the world (resignifying money as a process, not a thing)
.. Possibility of politics
. Literature review on politics
.. Modern institutions and its discontents (Arendt)
.. Action and politics (Arendt, Bellah)
.. Post-politics, post-representativeness, post-engagement (Tocqueville, Bellah, Mouffe)
.. Intersection with economy, money and lifestyle (Graeber and Dodd)
. Overarching theoretical questions
.. What is the nature of the political participation of crowdfunding?
.. What to expect from it, dark and bright side (Weber, Arendt)

****
