= Literature Review
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

Two recurrent topics on contemporary political theory are extremely relevant in order to address the possibility of politics through crowd funding. One of them comes from the antipolitics stream (Schedler 1997), and it argues that many institutions and practices that were supposed to be political do, in fact, weaken politics as such. According to this critique, a growing dissatisfaction with the means and ends of these institutions and practices has led to a general disavowal of politics _per se_; politics, therefore, starts to be taken with a skeptical and cynical tone and begins to be perceived as corrosive to society. By these means, it ceases to be the realm of conflicting interests, passions and desires. Furthermore, politics ends up either as a technical matter relegated to specialists or as a rational pursuit of consensus — both alternatives sustained by a strong belief in an impartial set of procedures (Mouffe 2005).

The other topic, subsequently, is one way to approach this contemporary political condition through the critique of rationalization and of utilitarianism (Weber 1976, Collins 1986), as well as through the underneath and widespread individualism and disconnectedness related to these ideals (Bellah _et al_ 2008). This set of critiques argues that in the last centuries traditional republican and religious morals have been fading out in terms of relevance, being replaced by a culture that fosters the pursuit of self-interest in a way that does not create nor sustain social ties (Bellah _et al_ 2008, Graeber 2011).

Both these topics refer to the corrosive aspect of modernization, which call into question the promises of the Enlightenment. The focus of this research is based on these critiques from political theory towards the possibility of political action and engagement in contemporary society. Most of this theoretical framework discusses the modern world framed by nineteenth and twentieth century political philosophy. On the one hand, these oeuvres are reflecting upon the outcomes of the eighteenth-century revolutions in the USA and in France (for example, Tocqueville 1986 or Arendt 1973). On the other hand, they are rethinking these results in the light of the terror spread during the two World Wars, and, at the same time, taking into account the democratic states which emerged thereafter (for example, Bellah _et al_ 2008 or Arendt 1998). The core literatures informing my research are political theories of the relationship between the public and private realms, and particularly the work of Arendt, Wolin and Bellah.

I also draw from  other sources, including, but not limited to: the contemporary critique of economic theory and especially money (for example, Graeber 2011 and Dodd 2014); the growth of digital cultures and its commercial and social implications (for example, Palmås 2006 and Ritzer and Jurgenson 2010); literature from science and technology studies (for example, Shedler 1997 and Allen-Robertson 2013) and the sociology of ignorance (for example, McGoey 2015), especially to reflect upon the ways that political action is conscribed by often unspoken commercial or political exigencies that undermine the possibility of effective public engagement in Arendt's sense. However, the more traditional and historical debates on modern political thought mentioned in the previous paragraph draws a steady framework to understand politics within crowd funding: if the hypothesis is that there is a tension between the crowd funding community and incumbent institutions such as the government and corporations, this solid framework of political thought affords a rich and complex comprehension about these institutions. Beyond a bold understanding of how they emerged and how they ended up with some of their core characteristics, the idea is to consider the critiques raised by the crowd funding communities as substantial (in opposition to circumstantial or only contextual critiques). In other words, the assumption is that crowd funding might not be criticizing more recent traces of capitalism and democracy (something that might have emerged together with the internet). On the contrary, the idea is to frame social crowd funding implications in a historical and structured stream of social thought that call these institutions into questioning. In order to achieve that I refer to this longer historical understanding of the modern political system – which, in cases such as Arendt, requires us to dive into political debates from the Ancient Greeks.

Commonly this literature acknowledges the achievements of the Enlightenment, but, at the same time, emphasizes how it failed in completely putting forward some of the ideals that were at its core. For example, Arendt (1973) did not deny the importance of modern political institutions such as parties and elections; they opened the political career for people from the lower classes, and yet the notion of forming an elite through the party simply replaced the old elites based on birth or wealth. However, she also emphasized that the party framework is less meaningful in providing a government _by people_ than in recruiting _from people_ an elite to govern them. In other words, the central question here is not the democratic (or republican) institutions _per se_, but the tangible possibility of political action for ordinary people. In a simplistic statement this might be one of the main points targeted by crowd funding: granting ordinary access to decision making about public goods that these institutions might have failed to deliver.

The first part of this section draws upon the framework of these critiques towards the modern state as well as its democratic assumptions and failures. Next, it discusses the contemporary debate built around this concepts and its flaws, bringing in discussions around the arguable decline of political engagement in the turn of the twenty-first century. Finally, it sets some challenges in thinking about political action in contemporary society. The idea is to grasp the difficulties in using traditional approaches to political institutions to understand how political action can be reinvented within contemporary tensions and conditions. This is the overarching theoretical background to which I will contrast my sociological analysis based on the data I collected. These critiques form the pillar for a sociological understanding of crowd funding in the early twenty-first century.

== Modern institutions and its discontents

In terms of politics, most of the ancient world was traditionally based upon a distinction between the public and the private, two separate realms in which people would pursuit different objectives through different means. However, this scenario has changed considerably during the last centuries:

[quote]
… the emergence of the social realm, which is neither private nor public, strictly speaking, is a relatively new phenomenon whose origin coincided with the emergence of modern age and which found its political form in the nation-state (Arendt 1998:28).

Therefore, there is something essentially modern in the constitution of nation-states, and this essence relates to one of the core distinctions within political theory, namely, the public and the private realm. Following the emergence of the institutions created during that transition is a way to understand how this new political framework was forged. Moreover, this history sets the background for the subsequent criticism regarding the successes and failures of the modern project for politics.

The division between public and private was forged in ancient Greece, when one should keep the pursue of private interests to the boundaries of the household, the core place for one's private life. That is to say, only citizens who have provided enough for themselves and their families were allowed to participate in public life. This requirement was based on the role expected of this citizen when engaged with politics. Referring to Aristotle, who was one of the first to argue in that direction, this is how Arendt (1998:64-5) described this situation:

[quote]
Private wealth, therefore, became a condition for admission in public life not because its owner was engaged in accumulating it but, on the contrary, because it assured with reasonable certainty that its owner would not have to engage in providing for himself the means of use and consumption and was free for public activity. Public life, obviously, was possible only after much more urgent needs of life itself had been taken care of.

In modern times, in contrast, Arendt suggests that a distinctive realm takes on new rhetorical salience, the realm of the 'social', a space she sees as neither public nor private — and, as a consequence, this novelty has considerably dislocated what was understood as public. While private life was characterized by providing for the household through labor, and while the public realm was the place for action and speech, the social has taken the political space from the public, printing on it important differences: now government acts as a gigantic housekeeping organization, looking for provision for a whole nation; that is to say, labor, once relegated to the private life, is not only now allowed, but is placed at the core of political life. For Arendt (1998:28-9) the dividing line between the household and politics

[quote]
… is entirely blurred, because we see the body of peoples and political communities in the image of a family whose everyday affairs have to be taken care of by a gigantic, nation-wide administration of housekeeping. The scientific thought that corresponds to this development is no longer political science but 'political economy' or 'social economy' or _Volkswirtschaft_, all of which indicate a kind of 'collective house keeping;' the collective of families economically organized into the facsimile of one super-human family is what we call 'society,' and its political form of organization is called 'nation' (Arendt 1998:28-9).footnote:[Arendt does not justify the use of the German term _Volkswirtschaft_ in this passage. Arguably it has no direct translation into English. Nonetheless it refers to a kind of economics driven by the nation's needs, the needs expressed by its households as well as by the private and public sectors; in some languages, as in Dutch or Latin for example, its translation is similar to _national economy_ (_algemene economie_ and _oeconomia nationalis_ respectively).]

This transformation, however, was not abrupt. Bellah _et al_ (2008) argue that in the beginning of the modern age two strands were pillars both for public and private issues: on the one hand they mention a biblical strand; on the other hand, a republican one. The first of them is exemplified by the role of religion in the formation of what the authors labeled the American tradition:

[quote]
The Puritans were not uninterested in material prosperity and were prone when it came, unfortunately, to take it as a sign of God's approval. Yet their fundamental criterion of success was not material wealth but the creation of a community in which a genuinely ethical and spiritual life could be lived (Bellah _et al_ 2008:28-9).

Alternatively, the republican strand is illustrated by the standpoint of one of the Founding Fathers, Thomas Jefferson:

[quote]
In general, Jefferson favored freedom of the person from arbitrary state action and freedom of the press from any form of censorship. Yet he also believed that the best defense of freedom was an educated people actively participating in government. The notion of a formal freedom that would simply allow people to do what they pleased — for example, solely to make money — was as unpalatable to Jefferson (Bellah _et al_ 2008:31).

In both cases Bellah _et al_ (2008:31) reinforced: individual "freedom only took on its real meaning in a certain kind of society with a certain form of life;" without those moral principles, freedom would lead to social corrosion and tyranny. However, later on in the nineteenth century, both strands were challenged by two concurrent interpretations of individualism that would pull the individual away from this large social context. On the one hand, utilitarian individualism focused on individual self-improvement, reflecting the liberal belief that if each member of a group pursues their own interests, the whole community would testify to the emergence of social good. In this case, the idea of interests was basically set by another Founding Father, Benjamin Franklin, whose views were determinant in framing the capitalist motivation for work and accumulation (Weber 1976, Bellah _et al_ 2008).

On the other hand, expressive individualism claimed no interest in material accomplishments, but in an individual and subjective pursuit of experience through life. The richness of life would be achieved by nurturing the self with luxury, sensuality, the intellectual and all sorts of experiences that could help them to express themselves. Individual freedom became the norm supported by this expressive take, and a disavowal for social conventions marked the tone of this branch of individualism. Therefore, if the biblical and the republican strands do not contrast individualism and the public life, these approaches to individualism play the challenging role; they do it by conceiving a sort of self-contained individual:

[quote]
What is at issue is not simply whether self-contained individuals might withdraw from the public sphere to pursue purely private ends, but whether such individuals are capable of sustaining either a public _or_ a private life. If this is the danger, perhaps only the civic and biblical forms of individualism — forms that see the individual in relation to a larger whole, a community and a tradition — are capable of sustaining genuine individuality and nurturing both public and private life (Bellah _et al_ 2008:143, emphasis in original).

Therefore, this complex scenario in which modern states, government and corporations evolved is constantly conciliating different realms and what interests are allowed in each of them; these spaces are the public, the private and, arguably, the social realms. It is from this theoretical starting point that this research looks at contemporary political institutions and the political agency of crowd funding. Having in mind the individualistic and self-determined world views which have emerged in the last centuries (as Bellah _et al_ described) and having in mind Arendt's critiques regarding the existence of the so called social realm, a primary critique would be to understand to what extent the world imagined during the Enlightenment is conceivable nowadays. Put another way, the idea is to investigate  if the rupture between individual and civic society brought up by individualism is compatible with the virtues expected from governing bodies. Traditionally the answer to questions like these are suggestive of a negative tone. One element of arguments in such a direction is calling into question the effectiveness of free markets in granting freedom to ordinary people, that is to say, to ask if a rationalized economic sphere would promote the social good (or, on the contrary, if it would prevent ordinary people from political agency):

[quote]
The market idea, as Adam Smith proudly announced, banishes the authority of persons; it is a system of exchange which is legitimate only as a system. The closest we come to an image of control, reassurance, or guidance is the 'invisible hand' which assures fairness. But the invisible hand is also an abstraction; it is attached to the body of no single human being (Sennett 1980:43).footnote:[Interestingly Sennett (1980:44) also argues that this economic behavior compromised not only ordinary people's agency, but the core freedom they were supposed to inherit from such a society: "The market ideology promised the consummation of individual freedom of action. The market in practice was anti-individualistic. It displaced masses of peasants from their land, whatever their own desires to remain. At the moments when the supply of labor in cities exceeded the demand for labor, there was in fact no labor market. If an employee did not like wages an employer paid, he (_sic_) could go starve; there were plenty of others to take his place … The market system of the last century, rather, made the concepts of community and individual ambivalent, and ambivalent in a peculiar way. No specific human being, no human agent, could be held accountable for disturbances in these realms."]

But this critique is extended to the public realm as well. Society has become "an organization of property-owners," claims Arendt (1998:68), owners "who, instead of claiming access to the public realm because of their wealth, demanded protection from it for the accumulation of more wealth." Ultimately this means that the logic of instrumental individualism has taken down Bellah's biblical and republican strands. This transformation has to be understood according to the specific ways through which modern societies have developed into representative democracies. Arendt (1973) suggested this process encapsulated a constant struggle between, on the one hand, emphasizing the anew claimed by the American and French revolutions, and, on the other hand, the will to consolidate the ideal of freedom in a stable institution.

For instance, Jefferson had a particular standpoint among the Founding Fathers regarding the role of the constitution in an attempt to conciliate this tension: in ideological terms, he wanted the constitution to be strong enough to guarantee that no hostilities will take place in the political realm. Nonetheless, in order to reinforce the fledgling  anew, this same constitution should also be flexible enough to be revised from time to time. In practical terms, the effects of these thoughts can be seen in the representative democracy model and in its well-established ways to participate in the political realm: elections, elected officials, senators, representatives, parties and voters (Arendt 1973). A great many scholars, however, have argued that this new institutional scenario has failed in fulfilling its original intents. Critiques appeared as early as the 1920s, for example, when Dewey (1954:118) affirmed that:

[quote]
… skepticism regarding the efficacy of voting is openly expressed, not only in theories of intellectuals, but in the words of lowbrow masses: 'What difference does it make whether I vote or not? Things go on just the same anyway. My vote never changed anything.'

In other words, this scheme was unable to extend the perception of participation from representatives to the represented: when it comes to politics, citizens seem to be disinterested and this fact can be found not only "among those who feel left out or mistreated or who have learned that the rules of the game often operates to their disadvantage," but also "shows up regularly among the favored and highly placed" (Jaffe 1997:78).

Sniderman and Bullock's (2004) idea of 'menu dependence' involves a very similar description of how ordinary people have a bounded participation in politics. According to them, "citizens in representative democracies can coordinate their responses to political choices insofar as the choices themselves are coordinated by political parties" (2004:338). The idea is that citizens are not free to compose their own menu of political choices, but only allowed to pick up one from a pre-established agenda put up by parties and political elites. Yet Wolin's (2004:428) analysis of contemporary politics adds another layer to this branch of critiques: for him "in both, the political and the economic context, contract appears as the essential condition of power". In other words, as the market economy operates in a way that concentrates the (economic) power in the hands of the economic elite, the liberal state operates in a way that concentrates the (political) power in the hands of the political elite (Wolin 2004).

All these voices seam to converge on the critique that the specific way these political institutions work is expanding, rather than minimizing the gap between rich and poor, rulers and ruled. And again, as Arendt (1973:253) has suggested, underneath this wave of critiques towards modern society, there is the displacement of the public realm itself (together, once more, with the dilemma Jefferson had in mind):

[quote]
What he [Jefferson] perceived to be the mortal danger to the republic was that the Constitution had given all power to citizens, without giving them the opportunity of being republicans and of acting as citizens. In other words, the danger that all power was given to the people in their private capacity of being citizens.

This two-folded movement of the degradation of the public and of the inflation of the private has granted the space for corporations to extrapolate their private bounds and act within the public realm. Political decisions — already distant from ordinary people — gradually started to take into account a logic that does not pertain to the public realm, namely the logic of the market economy (Wolin 2004). In spite of advancing in many aspects, this process of modernization had a devastating side-effect for politics: by limiting the space for political action it consolidates the public realm as a place for private affairs. In Arendt's (1998:46) words, "the character of the public realm must change in accordance with the activities admitted into it, but to a large extent the activity itself changes its own nature too."

The types of skills and activities held within these spaces were also impacted by these transformations. The importance given to labor and provision (formerly banished from the political), and to speech and action (formerly the core of political activity) have also been reconfigured in a different balance. Labor and wealth accumulation made sense in as far as the household provisions required them. Excelling in speech and public action in politics was a public virtue which the whole body of citizens would benefit from. Interestingly, within the modern social realm labor was introduced to the political space and, at the same time, speech and action was dislocated to the private:

[quote]
… while we have become excellent in the laboring we perform in public, our capacity for action and speech has lost much of its former quality since the rise of the social realm banished these into the sphere of the intimate and the private (Arendt 1998:48).

From that perspective it is possible to comprehend the lack of interest, trust and reliability in politics nowadays. Also, it is possible to address the endless interest in making money. Both approaches overlap aspects in many critiques towards representative democracy, basically because they impact upon what takes place in the political realm. These changes ended up nurturing two kinds of critiques: on the one hand, there is a very optimistic approach to the rationalization and individualization processes. This stream, known as post-political, claims that the possible flaws in political institutions are to be overcome with the further development of these same institutions, according to the same values that brought them to life. In other words, more emphasis on rationalization itself would solve these possible flaws.

Habermas (1992, 2005), for example, argued that there are two instances in society — system and lifeworld — holding different rationalities. The instrumentalized one hosts the market and the political institutions, and this is the realm in which the individual interests are transcended in the name of anonymous demands, realized by means of instrumental, strategic action. This kind of rationality is increasingly detaching itself from social structures, taking the shape of autonomous organizations that only communicate through mediums such as money and power — or, to put it differently, only operate in a way that holds no commitment to other norms or values. Economic and administrative rationalities are the main themes here. The other instance, the communicative one, would be the place where individuals would rationally pursue a deliberation, rationally agreeing on the functioning of the instrumental institutions. Hence, there is no judgement between instrumental or communicative rationality; rather it is conjectured that each rationality is restricted to its own domain. The problem — part of Habermas's pathology of modernity — is that communicative rationality has been colonized by the instrumental logic. The author defends the need for reconnecting these spheres to avoid the so called 'colonization,' keeping the differentiation and autonomy of these realms. He states that only then will communicative rationality have room to collectively elaborate the ultimate aims for the social good.

On the other hand, against this rational approach, some authors defend that rationalization would lead to a more antipolitical environment. In opposition to Habermas's agenda, that is to say, arguing against the promotion of further rationality into the political realm, other scholars have claimed this would end up mitigating politics even more. Instead of using rationality to promote consensus in a post-political space, the idea for advocates of this branch is that this rationalizing process would harm the very nature of politics itself:

[quote]
Instead of trying to design the institution which, through supposedly 'impartial' procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant 'agonistic' public sphere of contestation where different hegemonic political projects can be confronted (Mouffe 2005:3).

Therefore, the lack of trust and interest in political institutions can be described as antipolitical via (at least) two different arguments: on the one hand, it contributes to the mitigation of the public realm, which is suppressed by a self-regulated private one, the market (Schedler 1997); alternatively, whatever remained of the public realm has started to operate according to a logic inherent to the private sphere — what Schedler (1997) calls an inverted Habermasian colonization. To be sure, Wolin (2004:588) highlights that both — state and market — are appropriating the methods of one another, in that "it is not that the state and the corporations have become partners; in the process, each has begun to mimic functions historically identified with the other." According to him, corporations' moves include being in charge or funding health care, education and other welfare affairs; in parallel, governments' moves include applying profits logic, and notions of efficiency and management to buoy its own actions. As McGoey (2015) has argued, bold problems emerge when public responsibilities are dislocated to the private sphere (even in the case of the non-profit private realm): as impaired as modern states can be, they are still public institutions that are held accountable in some sense (even if only during a few seconds in the ballot box every other year). In the process of transferring its function to the private helm, civic society would risk losing this minimal room for political agency.footnote:[At this point it is worth highlighting that the sociology of consumption  has a strong, coherent and incisive argument in favor of categorizing consumption as political agency (for example, Micheletti 2003). In spite of that, these scholars are not arguing that this political side of consumption is better, worse or that it should replace in any sense the more traditional forms of political agency. It sounds hard to believe that political consumption _alone_ would afford to grant ordinary people participation in the decision-making process within the public or social realm.]

The point here is not to demonize corporations or governments, but to reinforce how this conjecture affects political life. Bellah _et al_ (2008:259) argued that, beginning at the end of the nineteenth-century, a populist agenda "sought to expand government power over economic life for the common good" in an attempt to fight the power of well-established private corporations. This establishment, at this point, was already creating, managing and maintaining institutions typically associated with the public sphere: universities, museums, churches, orchestras and hospitals. The argument of this populist agenda was that ordinary people should be able to decide for themselves, and economic power was taking this political power from them:

[quote]
If the Establishment vision rearticulated important aspects of the republican ideal of common good in the turn-of-the-century America, Populism was the great democratizer, insisting on the incompleteness of a republic that excluded any of its members from full citizenship (Bellah _et al_ 2008:259).

In sum, neither the rational deliberation and consensus possibility, nor the agonistic one, are hosted in contemporary political institutions. Instead, there is a disavowal of politics, since it is generally perceived as inefficient, misguided and corrupt. However, this scenario may not eliminate politics as such, and people might find alternative ways to engage in public and civic life — and that is the topic of the next section.

== Action, technology and politics

The last section described what can be understood as a crisis in the contemporary political arena. The idea that voting would grant an accountable authority for the rulers and, at the same time, the sense of participation and freedom to the ruled, is, at maximum, an unfinished project (Sennett 1980). If ordinary people do not trust politics, the notion of participation and civic engagement, together with the ideals of a representative government, are called into question.

However according to Bennett _et al_ (2013:537), in spite of the predictions that this skepticism would move people away from politics, what was found was a 'skeptical engagement' with two different possibilities: "a context of mistrust and cynicism might discourage or pervert political participation, on the one hand, or spur innovation, on the other." Their ethnographic fieldwork showed how civic organizations in Providence (RI, USA) strategically deny the label of 'politics' in order to better engage with the local community and in order to promote change within it. Interestingly, this former objective included activities that are traditionally considered very political, such as joining the city council, or lobbying with the local politicians and government. In a similar tone, Tufekci (2014:202) describes that in civic movements organized over the internet, people also refrain from the more traditional ways of political action: "they don’t form political parties, organize formal organizations, file lawsuits, or other common tactics of movements with policy demands."

What the research completed by Bennett _et al_ (2013) suggests is that if politics is disinteresting for people, there is still space for actions focusing on the public realm, on the common good. In other words, the political institutions might not be the instance people with a civic mindset are looking for. Wellmer (2000), commenting on Arendt's political theory, suggests that possibilities created within a given political context might be the core of a public and active sphere:

[quote]
Arendt's concern is not with justice but with (political) freedom. Hence, her brand of universalism is neither the normative universalism of human rights nor the inherent universalism of the modern economy. Rather, it is the universalism of a human _possibility_: the possibility of creating, in the midst of contingent historical circumstances, a space of public freedom (Wellmer 200:229, emphasis in original).

This proposal, based on the possibility of creation of the anew, is at the core of Arendt's framework. For her (1998:7) 'action' is the essence of humankind, in opposition to 'labor' (meeting the basic needs related "to the biological process of the human body") and 'work' ("the unnaturalness of human existence," including the manufacture of tools to make labor easier and more productive for example). Action, in that sense, is held between humans "without the intermediary of things or matter." Yet the relation between action and politics is crucial to her argument:

[quote]
Action … corresponds to the human condition of plurality, to the fact that men (_sic_) … live on earth and inhabit the world. While all aspects of human condition are somehow related to politics, this plurality is specifically the condition — not only the _conditio sine qua non_, but the _conditio per quam_ — of all political life … Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men (_sic_) were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live (Arendt 1998:7-8).

If work and labor are held out of necessity, action is held as a virtue. Arendt (1998) differentiated immortality (typically found in Gods) from eternity (something that can be achieved by humans). As merely mortals, human beings can attempt to last forever, not as immortals, but through actions, through worldly deeds:

[quote]
… no matter how concerned a thinker may be with eternity, the moment he sits down to write down his thoughts he cease to be concerned primarily with eternity and shift his attention to leaving some trace of them. He has entered the _vita activa_ and chosen its way to performance and potential immortality (Arendt 1998:20).

Her concept of _vita activa_ inherited from the Aristotelian _bios politikos_ and from the Augustinian _vita negotiosa_ or _vita actuosa_ – that is to say, the freedom to create the anew is a virtue, a kind of indicator of "a life devoted to public-political matters" (Arendt 1998:12). Therefore, Arendt subscribes to the stream that defends that pursuing private interests, pursuing basic requirements for survival should not be the focus of the public sphere. Unfortunately, her diagnosis of modern society also noted that the public realm as such was dislocated in favor of the social one, a space in which this virtue is not necessarily a priority anymore. The social realm is governed by the necessities of providing, not by the freedom to create. This cherished freedom, a pillar for civic virtues, is then at risk. And if it is at risk, the consequence is that any possibility of political life would also be at risk:

[quote]
… action and politics, among all the capabilities of human life, are the only things of which we could not even conceive without at least assuming that freedom exists … Without [freedom] political life as such would be meaningless. The _raison d'être_ of politics is freedom, and its field of experience is action (Arendt 1968:146).

Besides this displacement discussed by Arendt herself, there are more critiques to this Greek-based tradition of political thought. Scholars such as Mouffe (2005) suggest that this emphasis on freedom and deliberation is too optimistic for a space in which political power and struggles are arguably more relevant. However, both Arendt and Mouffe overlap at a certain point, namely, the need to support the emergence and maintenance of plurality throughout democratic societies. For Arendt the focus is put on plurality as a consequence of freedom; for Mouffe plurality is the precondition that power struggles cannot be eliminated for democracy's sake.

Despite the more apparent tensions, there is a series of convergences in both scholars: first, when political institutions are barriers to the creation of anew, even for the ones taking part in it, the problem is flagrant (as Jefferson feared) – Arendt and Mouffe would probably agree there is no real possibility for plurality in this case. Second, the problem would also be flagrant when political institutions do not favor the emergence of ordinary people to the public sphere – again both scholars would agree this might mitigate plurality and freedom. Third, it would also be problematic to have a political institution led by extremely rational and instrumental logic. For Mouffe, this situation would minimize the importance of more subjective and human impulses required in an agonistic political sphere; for Arendt, this situation would narrow the boundaries between action, work and labor. In opposition to all these scenarios described above, both scholars would probably argue that the democratic process would only be successful  when there is a public sphere able to host different opinions; when this public sphere is not limited to an economy nurturing the big family called nation; when this public sphere is putting forward people's dreams, and, most importantly, when this public sphere is forging different forms of political agency free enough to create the anew.

Hence when it comes to comprehending the political agency within crowd funding, the focus of this research is more on exploring the potential of crowd funding as a public sphere: a multitude of communities proposing different projects and actions that are based on individual or group aspirations; a multitude that depends on a minimum public approval to happen (whether it is a purely profit seeking activity or a civic engaging activity); and a multitude that, through technology, is able to gather enough supporters as well as enough funds to empower ordinary people to hold political claims and actions (in the sense that they operate outside the traditional political institutions, that is to say, outside governments and, in some cases, corporations).

The importance of technology _per se_, even if relevant, is not at the core of this research. However, the idea that technology is crucial in promoting democracy is at its core. This argument is definitively not new; take for example Dewey's (1954:110) words:

[quote]
'Invent the printing press and democracy is inevitable.' Add to this: Invent the railway, the telegraph, mass manufacture and concentration of population in urban centers, and some form of democratic government is, humanly speaking, inevitable.

And even earlier than Dewey, other scholars were already discussing this relationship between technology and democracy. For instance, scholars from the nineteenth century, such as in Tarde's (1989) _L'opinion et la foule_ from 1901, were already arguing that printing and newspapers would have a civilizing effect on the public. A couple of decades later, Blumer (1939) highlighted the importance of electronic broadcasting on setting the tone of a free society (even if he recognized the possibility of mass manipulation). Instead of subscribing to a more utopian perspective (such as Dewey's quote above), or a dystopian one (such as the centralization inferred by the manipulation pointed out by Blumer), this research is sensitive to how technology contributes to the construction of reality, and, therefore, how important aspects of political institution might assume different semantics — for example, new forms of political leadership (Margetts _et al_ 2013) or new social meanings for money (Dodd 2014).

At this point there are two important branches to take into account. On the one hand there is a debate on whether new technology platforms such as crowd funding or car ride and lodging applications (for example, Uber and Airbnb) are disrupting, allowing people and markets to enjoy more freedom and competition, or, alternatively, whether they are a mechanism operating in consonance with long-standing incumbent institutions. In the first case the argument would be that this economic freedom would revolutionize how we deal with our private needs, providing more opportunities to make and save money. In the light of the concepts of freedom and politics discussed so far, this might result in lightening the weight of private interests as resources which be more fairly shared among all – that is the typical argument of the sharing economy (Botsman 2010).

Conversely, this same phenomenon could be described as wealth trickling down to new players that would keep power in their hands without affecting the overall balance of power in society. Simply put, and in spite of the optimistic aspirations of the sharing economy, these new technological platforms might be just replacing incumbent institutions without confronting the emphasis on the private realm – this argument is typical in platform capitalism (Tufekci 2014, 2015 and 2016) and in the gig economy (Shaw and Graham 2017) debates.

From a more geographical perspective, Shaw and Graham (2017:908) reinforce that technology has a direct impact on the way public spaces are produced and controlled through the flows of digital information:

[quote]
From smartphone applications to GPS devices, Uber, Wikipedia and TripAdvisor, the code and content relating to the buildings and spaces of our cities is often as important as their bricks and mortar. Consequently, the power afforded to traditional actors of urban power—developers, planners, landlords—is now rivalled by the rise of new informational monopolies such as Alphabet Inc.’s Google.

This is the core discussion held under the label of platform capitalism. According to Tufekci (2016), the (once) open internet is now dominated by ad-financed platforms that require a high level of control of these flows of information. In order to achieve this objective, platforms usually offer user friendly digital services (free of charge or for competitive fees). By bringing users in, these platforms are collecting data in emails, messages, social networks, navigation applications and so on. This mechanism grants different powers to these actors: on the one hand, they are financially powerful as they have valuable data-based profiles to sell to advertisers, they are organizationally powerful due to the network effect and they are powerful in controlling possibilities in the public and private spheres:footnote:[As Tufekci (2016:73) explains, "network effects, also called network externalities, are the tendency of the value of some products or services to increase as more people use them, and to become less worthwhile when they are not used by others, even if the less popular product or service is objectively better, cheaper, faster, or more diverse in its offerings. For many online applications, everyone wants to be where everyone else is."]

[quote]
These platforms own the most valuable troves of user data; control the user experience; have the power to decide winners and losers, through small changes to their policies and algorithms, in a variety of categories, including news, products, and books; and use their vast earnings to buy up potential competitors (Tufekci 2016:68).

Interestingly for both sides of this discussion, sharing economy and platform capitalism, the role of the current modern state is crucial; for example, as in Pasquale's (2016:317) conclusions:

[quote]
As the technological reorganization of lodging, transit, and other vital services accelerates, the platform cooperativists offer a hopeful message. Even if governance disaggregates, from territorial to functional logics, we can still create communities of concern and vectors of competition. If platform cooperatives can balance those two imperatives — promoting more streamlined services while respecting fair labor practices and community norms and obligations — they may well be able to succeed. But they are only likely to provide a real and enduring alternative to the current, compromised giants of platform capitalism if governments give them some initial breathing room (as infant industries), and promote a level playing field over time.

This critique highlights the fact that alternatives forged within incumbent institutions have their own limits. In an attempt to implement a profitable sharing economy, entrepreneurs ended up following the same mechanism that rules corporations; as an effect, their power of unleashing concentration of power is called into questioning. Also, their financial dilemma of how to be sustainable is frequently an eminent dilemma:

[quote]
If there were ever a need to expand our conception of humanity beyond the restricted "homo economicus" who works only for his or her benefit, the explosion of user-generated content on the Internet has provided major evidence. However, creative and altruistic output alone does not provide financing for servers, coders, and database management. As the public Internet scaled up and grew in numbers of participants, many websites faced a dilemma: whether to charge their users, or to sell users’ eye-balls to advertisers (Tufekci 2016:72).

There is yet another branch discussing technology, markets and politics, one drawing from counterculture and hacktivism. According to Palmås (2006), these are forms of political engagement that attempt to operate in a way that is marginal to the mainstream values and _modus operandi_ of incumbent institutions. Counterculture attempts to understand how these institutions work and uses its knowledge to 'jam' its functioning. Subversive art and other strategies taking technology into account are ways to confront the mainstream culture by blocking some of its gears. In these acts the appropriation of technology is relevant, but not crucial. However, it is within the hacktivism movement that technology takes a really prominent place in this argument. The change underlying this statement happens at an abstract level: instead of merely using new technologies, the hacker movement (mainly the free and open-source culture) reads the world through the lens of technology. In a pragmatic way, instead of hacking into the city with an urban intervention to confront incumbent values (as counterculture might do), hacktivism tries to understand how these incumbent institutions work and ponders this knowledge as they would ponder a computer code; it is not something to be jammed, but something that can be reprogrammed for better functioning.

This branch usually sustains a trend of civic movements that are non-institutional and horizontal. The hacker mindset as described above allows members of these movements to easily overcome barriers that would be needed in order to properly build an institution for them. Instead, they focus on a thick engagement and even without this kind of institutional foundation these are strong movements in the contemporary public sphere:

[quote]
Overall, this new configuration of protest movements and civics is strong in some dimensions (attention, coordination, publicity, etc.) and less potent in others (elections, policy changes). Using the affordances of digital tools, protesters can skip over some of the tedious work of yesterday’s movements but are then left with protests that lack the institutional capacity such work engenders (Tufekci 2014:207).

All these possible interpretations of how technology impacts upon action and how institutional powers reinforce that technology is a meaningful aspect for political agency, allowing different statements to be made in public. Crowd funding can be related to many aspects of these branches: even if born within a civic-minded hacker culture, most of these platforms opt for a business model undeniably linked to the entrepreneur culture. Ultimately this culture is a refurbished private realm operating at the core of platform capitalism; even if they wave a civic-minded banner, they lack sufficient proof to convince scholars on that point (see Pasquale 2016 or McGoey's 2015 discussion on 'TED Heads' for example). Yet crowd funding is usually advertised as a sharing economy example, that is to say, a platform that would succeed in better employing resources to allow more agency (political agency included) to ordinary people. Surely these are useful typologies for this research, buts as typologies the real value of these analytical simplifications does not rely on embracing one of these possibilities; on the contrary, it relies on understanding the complexities and tensions that make all these possibilities valid to the comprehension of crowd funding.

This complexity is not exclusive to crowd funding. Hacktivim itself has its own share of tensions and contradictions. The ethical assumptions of this culture, for instance, "represent a liberal critique within liberalism" since "hackers question one central pillar of liberal jurisprudence, intellectual property, by reformulating ideals from another one, free speech" — consequently revealing "the fault line between two cherished sets of liberal principle" (Coleman 2013). Yet these more libertarian approaches collide with incumbent institutions, triggering a set of negotiations between the challengers, the establishment and the public (Allen-Robertson 2013). Hence this research requires an in-depth investigation of how crowd funding challenges incumbent institutions such as government and corporations. The focus is on identifying elements of a public sphere in the crowd funding communities cohabiting with elements of the private realm; from there the idea is to understand the peculiarities of this mélange: how does it differ from the tensions and contradictions within incumbent institutions, what kind of proposal does it advance and what kinds of values are discouraged and so on. In sum, it is not expected to find out a clear and objective direction for the crowd funding community. The aim is to understand which forces, with what purpose, and in which situations steer the community in one or other direction. In order to achieve that, the perspective of people engaged in crowd funding is key to understanding these movements and oscillations – and that justifies the epistemological approach on world views: it is more relevant to understand their political aspirations and expectations than to try to forge tangible and measurable parameters of concrete social changes.

In terms of these tensions it is worth mentioning that a hacker civic-mind might weigh too much on autonomy, nurturing an atomized private realm; this would relegate decisions about what should and should not be done to the sphere of individuals' morals and judgements. On the other hand, the mechanisms embraced by crowd funding (from the functioning of the online campaigns to the dependence on strong and weak ties) require these decisions to be held by a greater audience: without supporters, no project sees the light of day; without collaboration within the network (open source included), no action is possible. Interestingly, it seems that a very pecuniary mechanism might be the argument for crowd funding to frame itself as a space closer to (and not more distant) from a public sphere. Either way, even in a more pragmatic approach than the one described in the last paragraph, there are still tensions and complexities to be taken into account in this field.

Reiterating the research questions, the literature discussing how technology relates to freedom and empowerment (whether it is fostering or mitigating them) is crucial to ponder on the specificities, biases and limitations of political agency in crowdfunding. This argument takes into account not only the common (and arguably naïve) association of technology with empowerment and freedom, but also the influence of cultures and ideologies present in technological and entrepreneurship fields. This literature offered a solid reference to map influences and boundaries of this agency. From the political theory point of view, it seemed improbable to consider that any political agency within crowd funding would not refer to incumbent institutions, agreeing or disagreeing with them. The theoretical literature introduced in the last section, the one dating back from Ancient Greek thought and discussing how the idea of public and private realms has advanced since them, plays a crucial role in this research: it situates claims, critiques and advocacies found within crowd funding in a bold conceptual framework. With this strategy it was possible to better understand the context, boundaries and innovative aspects of this political agency, especially when calling into question the functioning of incumbent institutions. As mentioned, the steady conceptual framework put forward by Arendt, Bellah and Wolin allowed me to frame crowd funding claims in a long and historical stream of political thought, calling into question incumbent institutions such as the government and corporations – and, at the same time, confront a possible interpretation of these claims as a novelty in the context of the awakening of the digital era. Finally, the combination of these strategies allowed the comprehension of informants’ world views, both in the context of the role played by technology in politics and also in the context of historical theoretical advocacy confronting or supporting the way the modern state is currently and historically organized.
