= 3. Resignifying money
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

*Eduardo Gonçalves* +
_3^rd^ year PhD student in sociology, University of Essex_

[opening]#To begin to free ourselves, the first things we need to do is to see ourselves again as historical actors, as people who can make a difference in the course of world events (Graeber, 2011:383).#

If the main argument in this research is mostly theoretical and political, the basis sustaining this argument is strongly sociological. Therefore this chapter starts to articulate the sociological analysis of the interviews by discussing the way they approach money in their everyday life. It is no accident that money is a starting point for this research: first of all, the platforms at the core of this study are basically set up to collect money, to fund projects that arguably could be funded through other means. What is at sake here is that the choice for crowd funding must be understood sociologically. 

Second, money is at the core of several sociological debates that aims at establishing not only the basis of modernity but of sociology itself – in two simplistic examples, money is a crucial topic in Marx's _Capital_ and in Weber's _Protestant Ethic_. Therefore it is important to debate the role of money not only from the microsociological perspective (the world view of the interviewees, people engaged in crowd funding communities), but also from a macrosociological standpoint (understanding the role money plays in the constitution of incumbent institutions of our times, such as representative democracies and multinational corporations).  

Third, and most important, the micro and macrosociological take on money are not opposed or disconnected. Both interpretations contribute to the pillars of the theoretical and political critique put forward by crowd funding communities: resignifying money is the first step of a complex mélange that ends up not only as a political critique, but as a new – if restricted – possibility for political action. This first step is crucial to build autonomy (discussed in the next chapter), and, next, to call into question institutions that are still based on a more traditional approach to money.

This chapter starts describing how people who mostly contribute to crowd funded projects engage in such campaigns and how they see money in their everyday lives. As the analysis move on to people with higher engagement with crowd funding, the process of resignification of money becomes clearer and more rooted in specifics aspects that compose a particular world view. Although this process is not so explicit in the first group, a will to see ideas they believe in coming through is already there. And money — together with the freedom and power to choose which projects to fund — is what is empowering this will, making this into something real.

== Playing the patron

Talita is a young professional who lives in São Paulo, Brazil's biggest metropolitan area. Every month she spare some time to browser her favorite crowd funding platforms. “To poke around Kickstarter is already an habit,” she says. She first learned about crowd funding a couple of years ago, but she does not remember exactly how. Maybe it was through a friend, social media in general, or a news aggregator. Since then she became what might be labeled as a heavy user, pledging in many projects:

[quote]
I thought “that's cool” [when I first saw a crowd funding project]. I clicked and started to browse and to get to know Kickstarter. And I started to look the entire site looking of projects to pledge in, and to buy a bunch of stuff through Kickstarter. I have, for example an bike flashlight [...], a revolutionary bike bell, an awesome one. I have a wonderful pen that is a 3D printer. I have lots of stuff from Kickstarter. Lots of books. I contributed with many student film productions. I have never got anything in return, but [I know] working with art is not easy, so they need this support.

Carla, another young woman from São Paulo has a similar habit:

[quote]
So I have a monthly budget, something around 15 dollars,  that I spare for crowd funding […] But, for example, this month I contributed to more projects, I spent 35 dollars. Last month I spent a little less. As I am already collaborating with a few recurrent projects, this year I am sparing less to these [one-off] projects.

These two quotes bring in three interesting elements to the analysis. First of all, these two interviewees represent the massive and intense acceptance crowd funding had within certain groups. Even if it was not that common to find people who have internalized the habit of periodically visits to crowd funding platforms, different sources described how they put a lot of money in a wide variety of projects: Daniel is a German industrial designer passionate about games, design and craftsmanship; he and her wife have designed and built themselves different parts of their new house. He has lost count of how many boardgames he had acquired through different crowd funding platforms — and he has design furniture and DIY (do-it-yourself) gadgets to add to that list yet. He estimated that probably he have already supported between 150 and 200 projects. Another Daniel, a Brazilian press officer and writer, has also lost count of how many books he had supported in crowd funding platforms. Adam, from  Paris, works with digital marketing and also as a filmmaker. He has supported many independent film productions and a few initiatives that he felt strongly identified with, such as a mobile application for women to mark in a map locations where they have been harassed, or artistic civic interventions. Juliana, a postgraduate student from Brazil, also have backed numerous projects based on ideological drivers, and also projects from friends and local musicians. Lisandro, a Brazilian psychologist and amateur writer, have had access to a lot of books and films through crowd funding, and as Daniel, many games too.

The examples show that several perspectives can justify their pledges in crowd funding projects: personal taste and habits, political ideas, personal relationships, interest for new, creative gadgets etc. However there is a more sociological way to look at these drivers — and this is the second element that these quotes bring in: what all these reasons have in common is the feeling that outside this parallel, marginal market called crowd funding some projects would not be able to succeed. For instance, when Talita says that working with art is not easy, she is saying that the projects she has supported, the people behind them, would have little chance outside crowd funding. At this point her claim could be that either the incumbent institutions that traditionally have been funding art would not have enough resources to fund more art projects, or that these institutions would not have interest in supporting the kind of art she would like to see in her life. In both cases her small support — together with a multitude of other small contributions — has made these projects real. In other words the perspective of the interviewees sustains that these mechanism of funding is allowing a wide variety of projects to exist, a lot of projects that would not exist if they depended on more traditional funding resources.

Daniel, the German industrial designer interested in boardgames, even compared the German and American market in these area: according to him board game business in the USA is more concentrated in the hand of a few companies, with more traditional, well established guidelines for the development and launching of new products. On the other hand, he describe the German the market as a more open environment to new ideas: companies there take the risk if launching different concepts in the market, allowing smaller game makers to have a shot in the business. Therefore, he argues, crowd funding for boardgames has built a bigger and more active community in the USA when compared to his homeland. The lack of space offered by incumbent institutions, instead of suffocating the community, have empowered them in a different direction.footnote:[To be clear, Daniel does not seem to dislike the American or the German community. He is active in both, participating in online and in person board game groups. In this part of the interview he was just describing that he sees a difference in the way the communities are organizing themselves and responding to externalities. He seemed enthusiastic about the way Americans could find a way outside the established market, but, at the same time, satisfied to see that Germans have the possibility to launch their own games through the local companies.]

The reflections held by Daniel illustrates a point that will be explored later in this thesis, a calling into question of the efficiency of the decision making processes inside incumbent institutions. However it is important to highlight how money is used in this point to bypass problems of these incumbent institutions. If they perceive that well established companies are not empowering “everybody,” ordinary people can choose to support any project, idea, person they would like to support via crowd funding. If companies and government in a risk-averse behavior ignore ideas that ordinary people find interesting, these ideas can be fund through crowd funding. If minorities cannot find voice, whether it is in the public space or in the supermarket, crowd funding can be their microphone. To be clear politically speaking this last example is achieved through more political and civic projects, such as the ones mentioned by Adam. Juliana also takes this discourse:

[quote]
I think that this kind of projects, projects from crowd funding platforms, enables a lot of debates that are hindered in our everyday life, specially when it comes to respect and empowerment. I have supported many activism projects. […] In São Paulo sometimes it looks like that being an activist is considered a kind crime by a lot of people. Take cycling, for example, or even veganism. I am a vegetarian and I am in touch with people from this area. I ask myself how to fund raise in these scenario, when for the mostly reactionary population it [our cause] sounds like an insult. Thus this thing of promoting and putting forward activist actions is an important driver for me — I have helped several projects in this areas.

Commercially speaking, similar possibilities are made tangible via crowd funding. Beyond Daniel's example regarding the American and German board game market there are other relevant issues: some products, maybe believed to not have a relevant market, are basically ignored by incumbent corporations. That is why Talita loves some bike gadgets she has found through crowd funding, for example: none of the established bike equipments brands have succeeded in meeting her needs, but some maker did. The same is valid for DIY projects Daniel backed, or even the case of art funded in these platforms. The interviewees strongly believe that ideas left aside by a risk-averse business logic can become successful in crowd funding. Daniel, the one involved in the board game communities, even consider that while big corporations invests a lot in research nowadays (trying to foresee the probable success of failure of products during the research and development stage), crowd funding itself is a kind of market research: ideas are threw there and the response is clear, some succeed and some fail. Furthermore, he argued, crowd funding can be a cheap alternative to market research accessible for ordinary people or even small companies without resources for this kind of investment. 

Wei, a Chinese postgraduate student who have acquired some electronic gadget through crowd funding, probably would agree with Daniel, but he is a little disapointed with these platforms. He understands the basic idea behind them, and he surely thinks it is cool how innovative projects can easily emerge there. But he call into question the role expected from some companies that are using this system merely as a cheap alternative to marketing research. He explicitly  mentioned that some projects on Kicksatrter are basically used to call the attention to the project. For him most platforms are slowing changing into a window shop for investors (and not a mean to make projects viable outside the corporation and traditional politics mentality). Similar critiques are also held from times to times by the media, for example in this _The Atlantic_ article:

[quote]
GasWatch is a real company […] with a history of manufacturing and distributing products in the propane tank metrics space. They seem less likely to flake, but it does make you wonder why they’d trouble themselves to run a crowdfunding campaign in the first place, and for as little as $25,000. In short, because crowdfunding is a kind of marketing more than a kind of investing or pre-ordering. A place to dream about a future rather than to live in it.

To summarize, the first point in this section highlighted the relevant acceptance crowd funding platforms had among a certain group. The second point suggested that the fact that crowd funding builds possibilities outside the realm of traditional politics and market is important to understand this acceptance. Following this stream the third and last point in this section sustains that the interviewees do not see themselves merely employing their own money to buy things that are not available in the supermarket and shopping malls. They do not see themselves merely donating for certain political and civic causes either. Money is used as political tool to empower initiatives marginalized by incumbent institutions, enabling a voice to the person deciding where to put her or his money, a choice in a world perceived as limited by options offered by well established political groups and corporations.

For instance, Daniel mentioned the Karma Chakhs project in Germany. The urban and casual fashion had already set the stage for the success of Converse footwear, but later news and activist groups started to accuse the company of employing highly unacceptable means in the production of the shoes. After a major merging in the corporate sphere, the production chain became the target of reports denouncing the use child labor, high degrees of exploitation and non-sustainable raw materials. Instead of abandoning the aesthetic of that specific shoes (by then already a trade mark), a group started a fair-trade alternative, via crowd funding:

[quote]
A hundred years ago, US Basketballer Chuck Tailor designed those lovely sneakers for Converse and the All Stars-Team. Those so-called Chucks turned into an epitome for timelessness, simplicity and rebellion. The problem about them: Ever since Nike bought the brand Converse nine years ago, they are being produced under unfair conditions in China, India and Malaysia. The poor seamstresses are being yelled at and badly paid. Whoever buys todays Chucks, buys bad karma. I don't want Nike to decide how those shoes are being produced. Chucks belong to their fans and that is why I want to produce my own: Fair trade, with good karma (Le-Mentzel, 2012).

The project asked for for more than 20 thousands dollars, and raised more than 150% of this target. A year later they were back in the same crowd funding platform asking for roughly 40 thousands dollars. That time they raised more than 200% of the target (Hoffmann & Feddersen 2013). According to Daniel this is not only a matter of offering an alternative in a market where the rules are set by big corporations. For him this is a social expression worth of attention, it is a concrete signal that young Germans want to have voice over the decision-making, a signal that if they care about what happen in the middle of supply chain, they will find an way to put that idea forward. Yet Daniel adds that the if same generation can have this degree of influence over (or, at least, this power to call into question) big corporations, they will also find alternatives to organize work and production. Namely Daniel considered that several initiatives backed via crowd funding highlight and empower a new way of making business, a way that values projects made in spare time, projects driven by dreams, by passion.

Maybe Daniel's take on that topic might sound as an utopia, but it is undeniable that way people engaged in crowd funding see themselves highly corroborates Daniel's statement. As Lisandro put “somehow you are playing the patron, you are allowing things to happen, things that nobody knew, nobody wanted, or nobody imagined would happen.” His choice for this specific term, patron, is meaningful: it suggests that despite the social privilege that defined the patronage system, it was the kings and nobles, popes and the wealthy class in general that used to support art for centuries. They were in an important position that allowed them not only to rule kingdoms and religions, but to decide what kind of art and artists would survive. And that is exactly the sense Lisandro is recalling when he describes crowd funding nowadays: supporting a project is not a gesture bounded to the freedom to consume, or to the freedom to support a political idea. Supporting a crowd funded project is to exercise the power to decide which ideas will become real world projects, which artists, makers, business person will succeed  — just as patrons. 

Surely believing in this argument does not imply that crowd funding power is as big as the power or corporations or political parties. In spite of this power struggle, this view consolidates crowd funding as a marginal and alternative power. In Carla's words, “we create, hack this crazy system we live in; the more [crowd funding] initiatives the better.” And, as wealth was important for the patronage system, money (in relative smaller proportions) is important in crowd funding. However, even if people engaged in crowd funding are usually well-off, this importance transcend the view of money as a richness to be accumulated: at least sociologically money is relevant as tool to foster a marginal and alternative decision-making process, a movement in clear dissonance with the way incumbent institutions have been exercising their powers.

Patreon is the pioneer recurring crowd funding platform. Their about page has a single line text: “we want to help every creator in the world achieve sustainable income” —  beyond the platform name this indicates that they see themselves as tool to gather a bunch of small contributors to build a body that would act as a patron. Below this line there is a list with the title “meet our team” introducing the visitor to a dozen of people. They are presented through a profile picture, a job title and a less than one line description. One of the members of this gallery is Muppet, a cute and shaggy-haired brown dog. His job title is “director of growth” (Patreon 2016). Surely this could be seen merely as a startup joke, but the choice for the pet's job title also points to the proper role money should play in this community — or, to be more precise, about the role money should not play: money is not about growth, accumulation or a first priority measure for success.

In this scenario money is a mean to make decisions about a great variety of projects, to have a voice and to back projects that probably would not be funded otherwise. Money grants social voice and freedom of choice not because of one's disproportional wealth (as it was within the patronage system), but because crowd funding allowed a bigger part of society to have this voice and this choice. In other words, if this used to be restricted to an aristocracy (whether it is within traditional patronage, or in nowadays corporations and political parties), crowd funding is making it accessible to a bigger portion of society: the technological part of the mechanism does the magic of gathering a multitude of small contributions and, together, they are powerful enough to back a multitude of projects. Surely this claim does not states that this is a possibility fully accessible to everyone. The interviewees background suggests that being well-off is a kind of requirement in most of situations, that is to say, one has to have her or his own needs covered to be able to spare some money for crowd funding platforms. Furthermore one cannot ignore that another type of “capital” is important in order to engage in crowd funding: a minimum level of digital literacy, including but not limited to access to internet, trust in online systems, familiarity with social media etc. If crowd funding is a social and political milestone, it still limited to given social group. Even though, for this strata crowd funding is assumed to be more than a alternative market. It is seem as a space that better welcomes diversity, political minorities, a logics that diverge from the profit-driven business class and world views, a logic that is dislocated in most areas of modern life.

In sociological terms, this seems to be more than the emergence of new business that have not emerged yet. This movement seem to be calling into questioning the role of money as a rule to the everyday life. In his recent anthropological analysis of money, Graeber argued:

[quote]
Any number of names have been coined to describe the new dispensation, from the “democratization of finance” to the “financialization of everyday life.” Outside the United states, it came to be known as “neoliberalism.” As an ideology, it meant that not just the market, but capitalism … became the organizing principle of almost everything. We were all to think of ourselves as tiny corporations, organized around the same relationship of investor and executive: between the cold, calculating math of the banker, and the warrior who, indebted, has abandoned any sense of personal honor and turned himself into a kind of disgraced machine (2011:376-7).

The way these users of crowd funding are employing money seems to go beyond this financial logic. It does not deny that money is an important criteria in modern society. The fact that the power to play the patron through crowd funding depends on having spare money in the end of the month shows that money still an important “organizing principle of almost everything.” But at the same time the motivation to spend something that otherwise would have been saved shows a will to put some ideas and projects forward — and this can be understood as a political action in the sense it is more a public expression than an act of consuming or investing.footnote:[As we will see later, for Arendt (1998) this difference is crucial because it puts this choices out of the sphere of labor, and throw it to the two other possibilities: work and/or action.] In other words it is clear that money is important for crowd funding due to its universal value, but beyond that, it is also important to note that money is a mean to make political claims against the concentration of decision power, a contradictory manner to raise the voice against the way our society is organized. If it does not question capitalism itself, it is questioning the power configuration and exercise sustained by capitalism and “neoliberalism” during the last decades. The following section goes further in the ways through which people more engaged in crowd funding (project creators and platform founders and staff) extend this critique even further.

== Money as a fuel to autonomy

If users of crowd funding platforms described above could be profiled as industrial designers, journalists, psychologists or press officers, for example, it is impossible to do the same with people that delve even deeper in these communities. Many of these interviewees see crowd funding as a way (among many others) to make a living. Many of them do not hold a traditional job, and certainly cannot be described with single (or even a couple of) job title. In spite of that they participate in many different initiatives demonstrating they can handle a diverse set of skills. They can profit, for example, from dancing and teaching tango, from composing and recording authorial songs, from coding software or from offering specialized consultancy in sharing economy — to stick to Daniel's skills, a guy who founded two different crowd funding platforms in Brazil. With this variety of activities comes the lack of a traditional job title. And together with the lack of a job tile there is a question that is repeated over and over to them: how do you make a living? Pedro is a Brazilian in his late twenties. He mixes entrepreneurial and tech skills, together with a deep interest for politics, to put forward a diverse set of projects: from local and free educational initiatives related to technology, to publishing illustrated books about politics for kids, including running a hackspace, many projects funded with government support, and crowd funded projects as well. When I raised that question about how was he making a living, he seemed pretty tired of addressing this topic, and then he was very straightforward with me:

[quote]
Well, this is one of the first thing people ask, always, everywhere. And I think that if the person made this question, she or he either made the wrong question or has not understood a word I have said. […] People are like “ok, but how do you make a living?” I just told them about a lot of awesome stuff, projects and the first doubt is where does the money come from? The money comes. I can tell you exactly where the money came from in every project I do. But that is not the answer people are looking for. They ask me how do I make money because they want to find a way for them to make money. Thus I say I make money just like anybody else: working. I work, people pay me. They reward me for my services. […] And what do I do? Software development, consultancy, I have done publishing, video, events…

This quote is representative of a lifestyle that was found widely among these interviewees: I have heard several times, from different people, that they prefer to count on several (ordinary) geese than to count on a (single) goose that lays golden eggs. Pedro's answer is strategic in the sense of calling the attention to what really matter for him: the awesome projects, in his own words. By saying that there is nothing special in the way he makes a living, he is turning the spotlights back to what he wants to value. This faith in the projects and in this lifestyle is at the core of the assumption that there will always be money for interesting projects.

Emily, a British woman who as part of a team that launched a crowd funding platform in 2011, introduces this difference when it comes to the motivation to get involved in crowd funding:

[quote]
I don't think there is many people who set out because they are like “I want to make millions of pounds.” They kind of set out because they are like “I think this is a really interesting business model.” It shifts things so that some of the most effective Kickstarter projects are the ones that effectively get user information, get to connect with users. You get to iterate and change your project much faster […] and you get advanced orders, so the risk is lower. It feels like a much more connected relationship that those projects typically have with the people who will be using [the outcome of that] project.

The first thing to highlight in this quote is that it does not dismisses the importance of money: “you get advanced orders, so the risk is lower.” Even though money does not seem to play a protagonist role: the connection to the users seems way more relevant; therefore, a business model that empower this relationship sounds more attractive than a more traditional market exchange. Yet Emily believes that people who are interested in making a lot of money, as fast as possible, exist in crowd funding communities — but that is not what pushed her to get involved. Taking into account her own experience, while working setting up the platform in the UK, they had two good well established references from the USA: Indiegogo and Kickstarter. She pondered about the position these platforms have assumed:

[quote]
We interviewed with Kickstarter, Indiegogo, a bunch of different platforms just saying “look, we are doing this over here in the UK.” We were even open, if any of those platforms wanted to launch under similar principles in the UK, we would be really happy to point the audience that we had at them […] Kickstarter is financially driven. I think that is their main priority. I think it is something that is around, things like the environment […] It wasn't a good fit and they just had no desire to really be open. Indiegogo were more open. They have [shared] a lot of their data and learnings […] I think that Indiegogo were fantastic, they had a bunch of information talking about typical statistics.

It is clear in Emily's description that not every crowd funding community share the same principles, specially when it comes to money. At this point it is important to take my interviewees' family background into account: the kind of choices and judgements they made seem to have been built throughout their life trajectory in spite of their family values. Anna moved from a different state to São Paulo to do her high school (and a couple of years later her sister followed her). She was enrolled in one of the most traditional and high quality schools in São Paulo city. She told me that “until the senior year it would be weird to even entertain the idea of going to a not so traditional university.” She graduated from one of the best law schools in the country, worked in great law firms and later she quit to start a crowd funding platform focused on learning, Cinese.

Felipe, who funded his Master degree in the UK through a crowd funded project told a story slightly different, but that shares the sense the he should trace a traditional career path:

[quote]
We have been told about the best professions, we have been raised with this idea. A good profession is one with a good salary, because at the end of the day that is how we make a living, isn't it? Our parent's generation went through very difficult times, the country's economy wasn't in good health. Thus it was a kind of _every man for himself_; and that is embedded with them, that one has to get a job in order to provide some financial stability to one's family. Now I thing we are in a different time, a time in which we can be more flexible.

In fact most of my interviewees have a great educational and professional background. Many went to the best schools in their countries and abroad.Rodrigo is from Wales, but now is a CPO at an American crowd funding platform. He holds a BA from University of Oxford, a MS from MIT (Massachusetts Institute of Technology), and recently he started a PhD at Stanford University. Among the Brazilians, many hold graduate or postgraduate degrees from traditional schools in journalism (Cásper Líbero Foundation), law (Pontifical Catholic University of São Paulo), business (Getúlio Vargas Foundation) and communication (School of Higher Education in Advertising and Marketing), for example. However instead of holding a traditional career path — something like applying for internship in a multinational company, finding a job just after graduating, and celebrating a promotion to a management position before they are 30 years old — they drop out of this kind of expected career. Despite their outstanding professional profiles, they decided to pursue different paths. And yet there were some who, despite coming from a family that would support their formal education, are dropped out from college, or never started at a university and still were very successful in their alternative initiatives.

Hence it is important to consider that when it comes to this interviewees, the ones more engaged in crowd funding, what matter is not only to understand why funding projects through (or making a living out of) crowd funding. The choice they made arguably is rooted in an alternative take on the more traditional understanding of career and money. If Pedro held that he makes money just like anybody else, by being paid for employing his skills, one might suggest that there is no difference in the exchange going on there, and in the one in more traditional careers: someone performs a service and is rewarded for it. However for for most of my interviewees (Pedro included) there are subtle differences, not in the exchange, but in its meaning.

Pedro particularly does not seam to like describing things this way because of several reasons. Maybe the most important one is that, according to him, “while one has money, money is not a problem; money only becomes a problem when one is short on money”. Definitively he is not rich, and he is not claiming that there is an abundance of money whenever he needs it. However he believes that if his skills and ideas are relevant to others, there will be money – and this is what really matters for him. It is not important if it is from public or private open calls and biddings, traditional contracts with the public and private sector, contracts with NGOs, informal economy or barter, among man other possible sources, including crowd funding.

Anna, at the time of the interview, was in the middle of a reflection regarding this same issue. She the other Cinese founders have been running the platform for a couple of years, but currently the great question was how to keep the it sustainable in terms of money:

[quote]
We are in a kind of desperate phase. We think Cinese is already successful, it works. It's a great network, we have a lot of work to do, we generated a lot of things, but this is not bringing money in. So we got that there's something wrong going on. We are doing something wrong. And we are in this phase trying to find out what is wrong; how we could change this percentage based remuneration, something that is super rooted in the idea of scarcity. It makes it more expensive for those who use the platform, so it's not what we want.

In their platform there are meetings for sharing knowledge, skills, techniques, any kind of educational experience or meeting. People pay to register to some of these activities and then they keep a small percentage of these values — only if the activity takes place (in case it does not reach the minimum amount of participants, all the money return to the users). Later, when I was talking to Giovana, Anna's partner in Cinese, she added: “being financially sustainable it not only a need anymore, it is also a matter of people saying ‘there is a value in what you do.’” On the one hand they might be challenging Pedro's belief that there will always be money for interesting projects. But on the other hand, they are basically claiming the money as they believe in their initiative. Their judgement consider that the platform is going well, even if they depend on their saving to cover all their living costs.

In these settings it is worth it to say that savings are an important (and probably a restrictive) part of their lifestyle.footnote:[Counting on savings among young people was much more common in Brazil than in the US or UK. A hypothesis (not explored here, but popular in the media; see Pramuk 2015 for example) is that the expensive tuition fees in the US and UK could limit the possibility of young people taking risks: as soon as they graduate, they have to start working to pay their education loans. In Brazil most of the top universities are public and free, and even the private ones have mostly affordable tuition fees and funding options that alleviate the restrictive aspect of it.] Many of them had the chance to prepare themselves financially before assuming certain kinds of risks. As most of my interviewees has great educational and professional background, went to the best schools, they had great opportunities to join high ranked corporations, jobs, and projects; that is to say, some could build their own safety net. Savings, in that sense, also means that they are not afraid of failing, not because they are 100% confident in their capabilities, but because they have the feeling that if everything goes wrong, they can easily find a job and get back to their old careers. Evidently none of them want that, and only a few of them talked about it as a tangible possibility. But they cannot deny that they have a great combination of outstanding CVs, uncommon life experiences and the valuable entrepreneurship reputation that can help them to get a job or freelance any time they want. They have savings, they have a solid set of assets that could grant them a quick way out at anytime — even if that possibility sounds like a nightmare to their aspirations.

Making a living out of crowd funding, in this specific situation, becomes a secondary priority. Maria is a Romenian woman who, as Felipe did, partially covered her Master degree in the UK through a crowd funding project. She is a journalist and photographer, mostly freelancing since she graduated. She described me her relation with money:

[quote]
I had a lot of thoughts around money and pricing lately, about asking for money and how do you price yourself. You know how much is an hour of your life worth, but also it is skills sharing, you know? How much is an hour of my life equal to someone else's who is giving me another service? How am I going to make a living as a freelance if I feel bad for asking for money? And I always looked at money as this kind of bad thing that I don't really want to deal with. I never wanted to be rich or have three cars and four holiday houses or anything like that. So I haven't placed value on money in my life and I realise that it is partly because of my attitude towards money. And I really think I'm really bored with it [money], I'm over the attitude of feeling guilty for pricing and feeling like I'm somehow using people. If I would ask for [money] I would end up just working for free because I didn't want to price myself. Now I see it exactly like this: I wouldn't use out of personal preference but because it's still a very heavy way of exchanging and relating. I will then use it as a resource that comes and goes. It's not something that I want to hoard, but it's something that can enable me to put in practise things that are meaningful to me; and I think that is a positive, yeah, yeah. So I'm working hard at reminding myself of that as well.

[IMPORTANT]
From a reluctant attitude towards, to find ways to resignify it. What is meaningful for them?

Another Felipe, from Brazil, is one of the founder of Softa, the software house that developed Catarse. Catarse was the first crowd funding platform of the country and the first crowd funding platform in the world to be made open-source. Catarse is still the biggest crowd funding platform in Brazil. Felipe highlights the role Catarse has been playing:

[quote]
Catarse is not billionaire. It does not generate billions. But for sure it helped to change the national scenario. To be clear, Catarse helped to change the whole creativity scenario in Brazil. Music, drama, comic books, documentaries, you name it. When you have a direct connection with your fan base, even if someone with money stops investing in you, you still can raise hundred thousand dollars easily if people treasure what you have done.

Once more there is the trust that money would come, and there is also satisfaction (or even proud) underneath the idea that he contributed to it. At this point of the interview I was intentionally comparing Catarse to the multi billion dollar Kickstarter. Felipe felt very comfortable with the money and experience Catarse granted him (he is nor directly involved in the platform anymore), and becoming or nor a billionaire seemed far away from his aspirations. Even though, taking Felipe as a representative of a subset of my interviewees, it would not make sense to label them as radicals trying to dismiss money at all. On the contrary: they assume money is an important mean to put ideas forward, to support projects they believe in, and to sustain communities and creations. However this is not due only to money's inherent value, or due to the possibility to exchange it worldwide. Many have argued that money is not a thing by itself (Dodd 2014) and that money ultimately represent social relations of debt, marking a never ending, back and forth series of _I own you_ in close communities of trust (Graeber 2011). Crowd funding seems to embrace this social understanding of money, but in a pragmatic way that does not dismiss the utilitarian employment of money — and that is what they need in order to make projects tangible. Or, to put it in other words, even if money is a kind of entity detached from any moral assumption, its accumulation is not necessarily valued. Power derived from great concentration of money, the power to decide what projects are being funded, is exactly the problem crowd funding is trying to tackle at first place: the idea is to create opportunity for projects that could not find a place in a world dominated by governments and corporations. 

== Debate

[IMPORTANT]
Reinforce the three objectives of this section: reinforce how different money is for them, reinforce that money should be employed is something meaningful, and reinforce that, as a consequence, money makes more sense in circulation than in accumulation.

In the beginning of _The Protestant Ethic and the Spirit of Capitalism_ Weber (1976) recurs to Benjamin Franklin to describe what was the _historical reality_  he was taking into account to forge the concept of _the spirit of capitalism_:footnote:[Weber employed the expression _historical reality_ in the very beginning of the _The Protestant Ethic and the Spirit of Capitalism_ in order to describe his methodological approach: "Such an historical concept [the spirit of capitalism\] … cannot be defined according to the formula _genus proximum, differentia specifica_, but it must be gradually put together out of the individual parts which are taken from historical reality to make it up" (Weber 1976:13).]

[quote]
Remember, that money is of the prolific, generating nature. Money can beget money, and its offspring can beget more, and so on. Five shillings turned is six, turned again it is seven and threepence, and so on, till it becomes a hundred pounds. The more there is of it, the more it produces every turning, so that the profits rise quicker and quicker. He that kills a breeding-sow, destroys all her offspring to the thousandth generation. He that murders a crown, destroys all that it might have produced, even scores of pounds (Franklin, cited by Weber 1976:15).

At the same time this passage highlights two distinct characteristics attributed to money: on the one hand there is the property of self multiplication, the idea that money, if handled properly, can generate more money in the form of profit or as return of investments. On the other hand, it reflects an arguably universal will to accumulate money, as  this accumulation was a virtue _per se_. In these circumstances money is desired not because it holds any moral value, but because accumulation became an end in itself (Simmel 1978, Weber 1976, Hirschman 1977).

In the last few decades, major works in  academia have addressed the roots of this behavior. In heterodox economics, for instance, Hirschman (1977) described how the Enlightenment dehumanized _passions_ into economical and commercial terms such as _interest_. Within sociology, Weber (1976:116) argued that the asceticism of certain Protestant religions condemned the enjoyment of life in the form of consumption, leading to an “accumulation of capital through ascetic compulsion to save”:

[quote]
The capitalistic system so needs this devotion to the calling of making money, it is an attitude toward material goods which is so well suited to that system, so intimately bound up with the conditions of survival in the economic struggle of existence, that there can to-day no longer be any question of necessary connection of that acquisitive manner of life with any single _Weltanschauung_. In fact, it no longer needs the support of any religious forces, and feels the attempts of religion to influence economic life, in so far as they can still be felt at all, to be as much as an unjustified interference as its regulation by the State (Weber 1976:33-4). 

_Weltanschauung_ is a German term for world view. This chapter has described how people involved in crowd funding are departing from, and at the same time are forging, an alternative world view. By these means they are able to distance themselves from a more traditional approach to money, that is to say, from the logic of the institutions that share an understanding of money as something to be accumulated. Money, for them, is something that should circulate, an approach closer to what Dodd's (2014) described as an utopian money.

[IMPORTANT]
Linking paragraph missing: this world view (micro perspective) is pushing a calling into question of the institutional arrangement (macro perspective).

> “The only thing that’s clear is that new ideas won’t emerge without the jettisoning of much of our accustomed categories of thought … and formulating new ones. This is why I spent so much of this book talking about the market, but also about the false choice between state and market that so monopolized political ideology for the last centuries that it made it difficult to argue about anything else” (2011:384).

== Bibliography

Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.

Bogost, I. (2015). The Internet of Things You Don’t Really Need, _The Atlantic_. Available at: http://www.theatlantic.com/technology/archive/2015/06/the-internet-of-things-you-dont-really-need/396485/ [Accessed: 23 Jun. 2015].

Dodd, N. (2014). _The Social Life of Money_. Princeton and Oxford: Princeton University Press.

Graeber, D. (2011). _Debt: The First 5,000 Years_. New York: Melville House.

Hirschman, A. (1977). _The Passions and the Interests. Political Arguments for Capitalism before Its Triumph_. Princeton: Princeton University Press.

Hoffmann, S. & Feddersen, O. (2013). Karma Chakhs 2. _Startnext_. Available at: https://www.startnext.com/karma-chakhs2 [Accessed: 15 May 2016].

Le-Mentzel, V. B. (2012). Karma Chakhs. _Startnext_. Available at: https://www.startnext.com/en/karma-chakhs [Accessed: 15 May 2016].

Patreon (2016). Patreon: About. _Patreon_. Available at: https://www.patreon.com/about [Accessed: 22 May 2016].

Pramuk, J. (2015) Student Debt Crushes Innovation: College President. In CNBC. Available at http://cnbc.com/id/102377355. Accessed 28 Jan. 2015.

Simmel, G. (1978[1900]). _The Philosophy of Money_. London and New York: Routledge.

Weber, M. (1976[1900]). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.
