= 3. Resignifying money
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

*Eduardo Gonçalves* +
_3^rd^ year PhD student in sociology, University of Essex_

[opening]#To begin to free ourselves, the first things we need to do is to see ourselves again as historical actors, as people who can make a difference in the course of world events (Graeber, 2011:383).#

If the main argument in this research is mostly theoretical and political, the basis sustaining this argument is strongly sociological. Therefore this chapter starts to articulate the sociological analysis of the interviews by discussing the way they approach money in their everyday life. It is no accident that money is a starting point for this research: first of all, the platforms at the core of this study are basically set up to collect money, to fund projects that arguably could be funded through other means. What is at sake here is that the choice for crowd funding must be understood sociologically. 

Second, money is at the core of several sociological debates that aims at establishing not only the basis of modernity but of sociology itself – in two simplistic examples, money is a crucial topic in Marx's _Capital_ and in Weber's _Protestant Ethic_. Therefore it is important to debate the role of money not only from the microsociological perspective (the world view of the interviewees, people engaged in crowd funding communities), but also from a macrosociological standpoint (understanding the role money plays in the constitution of incumbent institutions of our times, such as representative democracies and multinational corporations).  

Third, and most important, the micro and macrosociological take on money are not opposed or disconnected. Both interpretations contribute to the pillars of the theoretical and political critique put forward by crowd funding communities: resignifying money is the first step of a complex mélange that ends up not only as a political critique, but as a new – if restricted – possibility for political action. This first step is crucial to build autonomy (discussed in the next chapter), and, next, to call into question institutions that are still based on a more traditional approach to money.

This chapter starts describing how people who mostly contribute to crowd funded projects engage in such campaigns and how they see money in their everyday lives. As the analysis move on to people with higher engagement with crowd funding, the process of resignification of money becomes clearer and more rooted in specifics aspects that compose a particular world view. Although this process is not so explicit in the first group, a will to see ideas they believe in coming through is already there. And money — together with the freedom and power to choose which projects to fund — is what is empowering this will, making this into something real.

== Playing the patron

Talita is a young professional who lives in São Paulo, Brazil's biggest metropolitan area. Every month she spare some time to browser her favorite crowd funding platforms. “To poke around Kickstarter is already an habit,” she says. She first learned about crowd funding a couple of years ago, but she does not remember exactly how. Maybe it was through a friend, social media in general, or a news aggregator. Since then she became what might be labeled as a heavy user, pledging in many projects:

[quote]
I thought “that's cool” [when I first saw a crowd funding project]. I clicked and started to browse and to get to know Kickstarter. And I started to look the entire site looking of projects to pledge in, and to buy a bunch of stuff through Kickstarter. I have, for example an bike flashlight [...], a revolutionary bike bell, an awesome one. I have a wonderful pen that is a 3D printer. I have lots of stuff from Kickstarter. Lots of books. I contributed with many student film productions. I have never got anything in return, but [I know] working with art is not easy, so they need this support.

Carla, another young woman from São Paulo has a similar habit:

[quote]
So I have a monthly budget, something around 15 dollars,  that I spare for crowd funding […] But, for example, this month I contributed to more projects, I spent 35 dollars. Last month I spent a little less. As I am already collaborating with a few recurrent projects, this year I am sparing less to these [one-off] projects.

These two quotes bring in three interesting elements to the analysis. First of all, these two interviewees represent the massive and intense acceptance crowd funding had within certain groups. Even if it was not that common to find people who have internalized the habit of periodically visits to crowd funding platforms, different sources described how they put a lot of money in a wide variety of projects: Daniel is a German industrial designer passionate about games, design and craftsmanship; he and her wife have designed and built themselves different parts of their new house. He has lost count of how many boardgames he had acquired through different crowd funding platforms — and he has design furniture and DIY (do-it-yourself) gadgets to add to that list yet. He estimated that probably he have already supported between 150 and 200 projects. Another Daniel, a Brazilian press officer and writer, has also lost count of how many books he had supported in crowd funding platforms. Adam, from  Paris, works with digital marketing and also as a filmmaker. He has supported many independent film productions and a few initiatives that he felt strongly identified with, such as a mobile application for women to mark in a map locations where they have been harassed, or artistic civic interventions. Juliana, a postgraduate student from Brazil, also have backed numerous projects based on ideological drivers, and also projects from friends and local musicians. Lisandro, a Brazilian psychologist and amateur writer, have had access to a lot of books and films through crowd funding, and as Daniel, many games too.

The examples show that several perspectives can justify their pledges in crowd funding projects: personal taste and habits, political ideas, personal relationships, interest for new, creative gadgets etc. However there is a more sociological way to look at these drivers — and this is the second element that these quotes bring in: what all these reasons have in common is the feeling that outside this parallel, marginal market called crowd funding some projects would not be able to succeed. For instance, when Talita says that working with art is not easy, she is saying that the projects she has supported, the people behind them, would have little chance outside crowd funding. At this point her claim could be that either the incumbent institutions that traditionally have been funding art would not have enough resources to fund more art projects, or that these institutions would not have interest in supporting the kind of art she would like to see in her life. In both cases her small support — together with a multitude of other small contributions — has made these projects real. In other words the perspective of the interviewees sustains that these mechanism of funding is allowing a wide variety of projects to exist, a lot of projects that would not exist if they depended on more traditional funding resources.

Daniel, the German industrial designer interested in boardgames, even compared the German and American market in these area: according to him board game business in the USA is more concentrated in the hand of a few companies, with more traditional, well established guidelines for the development and launching of new products. On the other hand, he describe the German the market as a more open environment to new ideas: companies there take the risk if launching different concepts in the market, allowing smaller game makers to have a shot in the business. Therefore, he argues, crowd funding for boardgames has built a bigger and more active community in the USA when compared to his homeland. The lack of space offered by incumbent institutions, instead of suffocating the community, have empowered them in a different direction.footnote:[To be clear, Daniel does not seem to dislike the American or the German community. He is active in both, participating in online and in person board game groups. In this part of the interview he was just describing that he sees a difference in the way the communities are organizing themselves and responding to externalities. He seemed enthusiastic about the way Americans could find a way outside the established market, but, at the same time, satisfied to see that Germans have the possibility to launch their own games through the local companies.]

The reflections held by Daniel illustrates a point that will be explored later in this thesis, a calling into question of the efficiency of the decision making processes inside incumbent institutions. However it is important to highlight how money is used in this point to bypass problems of these incumbent institutions. If they perceive that well established companies are not empowering “everybody,” ordinary people can choose to support any project, idea, person they would like to support via crowd funding. If companies and government in a risk-averse behavior ignore ideas that ordinary people find interesting, these ideas can be fund through crowd funding. If minorities cannot find voice, whether it is in the public space or in the supermarket, crowd funding can be their microphone. To be clear politically speaking this last example is achieved through more political and civic projects, such as the ones mentioned by Adam. Juliana also takes this discourse:

[quote]
I think that this kind of projects, projects from crowd funding platforms, enables a lot of debates that are hindered in our everyday life, specially when it comes to respect and empowerment. I have supported many activism projects. […] In São Paulo sometimes it looks like that being an activist is considered a kind crime by a lot of people. Take cycling, for example, or even veganism. I am a vegetarian and I am in touch with people from this area. I ask myself how to fund raise in these scenario, when for the mostly reactionary population it [our cause] sounds like an insult. Thus this thing of promoting and putting forward activist actions is an important driver for me — I have helped several projects in this areas.

Commercially speaking, similar possibilities are made tangible via crowd funding. Beyond Daniel's example regarding the American and German board game market there are other relevant issues: some products, maybe believed to not have a relevant market, are basically ignored by incumbent corporations. That is why Talita loves some bike gadgets she has found through crowd funding, for example: none of the established bike equipments brands have succeeded in meeting her needs, but some maker did. The same is valid for DIY projects Daniel backed, or even the case of art funded in these platforms. The interviewees strongly believe that ideas left aside by a risk-averse business logic can become successful in crowd funding. Daniel, the one involved in the board game communities, even consider that while big corporations invests a lot in research nowadays (trying to foresee the probable success of failure of products during the research and development stage), crowd funding itself is a kind of market research: ideas are threw there and the response is clear, some succeed and some fail. Furthermore, he argued, crowd funding can be a cheap alternative to market research accessible for ordinary people or even small companies without resources for this kind of investment. 

Wei, a Chinese postgraduate student who have acquired some electronic gadget through crowd funding, probably would agree with Daniel, but he is a little disapointed with these platforms. He understands the basic idea behind them, and he surely thinks it is cool how innovative projects can easily emerge there. But he call into question the role expected from some companies that are using this system merely as a cheap alternative to marketing research. He explicitly  mentioned that some projects on Kicksatrter are basically used to call the attention to the project. For him most platforms are slowing changing into a window shop for investors (and not a mean to make projects viable outside the corporation and traditional politics mentality). Similar critiques are also held from times to times by the media, for example in this _The Atlantic_ article:

[quote]
GasWatch is a real company […] with a history of manufacturing and distributing products in the propane tank metrics space. They seem less likely to flake, but it does make you wonder why they’d trouble themselves to run a crowdfunding campaign in the first place, and for as little as $25,000. In short, because crowdfunding is a kind of marketing more than a kind of investing or pre-ordering. A place to dream about a future rather than to live in it.

To summarize, the first point in this section highlighted the relevant acceptance crowd funding platforms had among a certain group. The second point suggested that the fact that crowd funding builds possibilities outside the realm of traditional politics and market is important to understand this acceptance. Following this stream the third and last point in this section sustains that the interviewees do not see themselves merely employing their own money to buy things that are not available in the supermarket and shopping malls. They do not see themselves merely donating for certain political and civic causes either. Money is used as political tool to empower initiatives marginalized by incumbent institutions, enabling a voice to the person deciding where to put her or his money, a choice in a world perceived as limited by options offered by well established political groups and corporations.

For instance, Daniel mentioned the Karma Chakhs project in Germany. The urban and casual fashion had already set the stage for the success of Converse footwear, but later news and activist groups started to accuse the company of employing highly unacceptable means in the production of the shoes. After a major merging in the corporate sphere, the production chain became the target of reports denouncing the use child labor, high degrees of exploitation and non-sustainable raw materials. Instead of abandoning the aesthetic of that specific shoes (by then already a trade mark), a group started a fair-trade alternative, via crowd funding:

[quote]
A hundred years ago, US Basketballer Chuck Tailor designed those lovely sneakers for Converse and the All Stars-Team. Those so-called Chucks turned into an epitome for timelessness, simplicity and rebellion. The problem about them: Ever since Nike bought the brand Converse nine years ago, they are being produced under unfair conditions in China, India and Malaysia. The poor seamstresses are being yelled at and badly paid. Whoever buys todays Chucks, buys bad karma. I don't want Nike to decide how those shoes are being produced. Chucks belong to their fans and that is why I want to produce my own: Fair trade, with good karma (Le-Mentzel, 2012).

The project asked for for more than 20 thousands dollars, and raised more than 150% of this target. A year later they were back in the same crowd funding platform asking for roughly 40 thousands dollars. That time they raised more than 200% of the target (Hoffmann & Feddersen 2013). According to Daniel this is not only a matter of offering an alternative in a market where the rules are set by big corporations. For him this is a social expression worth of attention, it is a concrete signal that young Germans want to have voice over the decision-making, a signal that if they care about what happen in the middle of supply chain, they will find an way to put that idea forward. Yet Daniel adds that the if same generation can have this degree of influence over (or, at least, this power to call into question) big corporations, they will also find alternatives to organize work and production. Namely Daniel considered that several initiatives backed via crowd funding highlight and empower a new way of making business, a way that values projects made in spare time, projects driven by dreams, by passion.

Maybe Daniel's take on that topic might sound as an utopia, but it is undeniable that way people engaged in crowd funding see themselves highly corroborates Daniel's statement. As Lisandro put “somehow you are playing the patron, you are allowing things to happen, things that nobody knew, nobody wanted, or nobody imagined would happen.” His choice for this specific term, patron, is meaningful: it suggests that despite the social privilege that defined the patronage system, it was the kings and nobles, popes and the wealthy class in general that used to support art for centuries. They were in an important position that allowed them not only to rule kingdoms and religions, but to decide what kind of art and artists would survive. And that is exactly the sense Lisandro is recalling when he describes crowd funding nowadays: supporting a project is not a gesture bounded to the freedom to consume, or to the freedom to support a political idea. Supporting a crowd funded project is to exercise the power to decide which ideas will become real world projects, which artists, makers, business person will succeed  — just as patrons. 

Surely believing in this argument does not imply that crowd funding power is as big as the power or corporations or political parties. In spite of this power struggle, this view consolidates crowd funding as a marginal and alternative power. In Carla's words, “we create, hack this crazy system we live in; the more [crowd funding] initiatives the better.” And, as wealth was important for the patronage system, money (in relative smaller proportions) is important in crowd funding. However, even if people engaged in crowd funding are usually well-off, this importance transcend the view of money as a richness to be accumulated: at least sociologically money is relevant as tool to foster a marginal and alternative decision-making process, a movement in clear dissonance with the way incumbent institutions have been exercising their powers.

Patreon is the pioneer recurring crowd funding platform. Their about page has a single line text: “we want to help every creator in the world achieve sustainable income” —  beyond the platform name this indicates that they see themselves as tool to gather a bunch of small contributors to build a body that would act as a patron. Below this line there is a list with the title “meet our team” introducing the visitor to a dozen of people. They are presented through a profile picture, a job title and a less than one line description. One of the members of this gallery is Muppet, a cute and shaggy-haired brown dog. His job title is “director of growth” (Patreon 2016). Surely this could be seen merely as a startup joke, but the choice for the pet's job title also points to the proper role money should play in this community — or, to be more precise, about the role money should not play: money is not about growth, accumulation or a first priority measure for success.

In this scenario money is a mean to make decisions about a great variety of projects, to have a voice and to back projects that probably would not be funded otherwise. Money grants social voice and freedom of choice not because of one's disproportional wealth (as it was within the patronage system), but because crowd funding allowed a bigger part of society to have this voice and this choice. In other words, if this used to be restricted to an aristocracy (whether it is within traditional patronage, or in nowadays corporations and political parties), crowd funding is making it accessible to a bigger portion of society: the technological part of the mechanism does the magic of gathering a multitude of small contributions and, together, they are powerful enough to back a multitude of projects. Surely this claim does not states that this is a possibility fully accessible to everyone. The interviewees background suggests that being well-off is a kind of requirement in most of situations, that is to say, one has to have her or his own needs covered to be able to spare some money for crowd funding platforms. Furthermore one cannot ignore that another type of “capital” is important in order to engage in crowd funding: a minimum level of digital literacy, including but not limited to access to internet, trust in online systems, familiarity with social media etc. If crowd funding is a social and political milestone, it still limited to given social group. Even though, for this strata crowd funding is assumed to be more than a alternative market. It is seem as a space that better welcomes diversity, political minorities, a logics that diverge from the profit-driven business class and world views, a logic that is dislocated in most areas of modern life.

In sociological terms, this seems to be more than the emergence of new business that have not emerged yet. This movement seem to be calling into questioning the role of money as a rule to the everyday life. In his recent anthropological analysis of money, Graeber argued:

[quote]
Any number of names have been coined to describe the new dispensation, from the “democratization of finance” to the “financialization of everyday life.” Outside the United states, it came to be known as “neoliberalism.” As an ideology, it meant that not just the market, but capitalism … became the organizing principle of almost everything. We were all to think of ourselves as tiny corporations, organized around the same relationship of investor and executive: between the cold, calculating math of the banker, and the warrior who, indebted, has abandoned any sense of personal honor and turned himself into a kind of disgraced machine (2011:376-7).

The way these users of crowd funding are employing money seems to go beyond this financial logic. It does not deny that money is an important criteria in modern society. The fact that the power to play the patron through crowd funding depends on having spare money in the end of the month shows that money still an important “organizing principle of almost everything.” But at the same time the motivation to spend something that otherwise would have been saved shows a will to put some ideas and projects forward — and this can be understood as a political action in the sense it is more a public expression than an act of consuming or investing.footnote:[As we will see later, for Arendt (1998) this difference is crucial because it puts this choices out of the sphere of labor, and throw it to the two other possibilities: work and/or action.] In other words it is clear that money is important for crowd funding due to its universal value, but beyond that, it is also important to note that money is a mean to make political claims against the concentration of decision power, a contradictory manner to raise the voice against the way our society is organized. If it does not question capitalism itself, it is questioning the power configuration and exercise sustained by capitalism and “neoliberalism” during the last decades. The following section goes further in the ways through which people more engaged in crowd funding (project creators and platform founders and staff) extend this critique even further.

== Money ought to circulate

If users of crowd funding platforms described above could be profiled as industrial designers, journalists, psychologists or press officers, for example, it is impossible to do the same with people that delve even deeper in these communities. Many of these interviewees see crowd funding as a way (among many others) to make a living. Many of them do not hold a traditional job, and certainly cannot be described with a single job title (or even with a couple of job titles). In spite of that they participate in many different initiatives demonstrating they can handle a diverse set of skills. They can profit, for example, from dancing and teaching tango, from composing and recording authorial songs, from coding software or from offering specialized consultancy in sharing economy — to stick to Daniel's skills, a guy who founded two different crowd funding platforms in Brazil. With this variety of activities comes the lack of a traditional job title. And together with the lack of a job tile there is a question that is repeated over and over to them: how do you make a living?

Pedro is a Brazilian in his late twenties. He mixes entrepreneurial and tech skills, together with a deep interest for politics, to put forward a diverse set of projects: from local and free educational initiatives related to technology, to publishing illustrated books about politics for kids, including running a hackspace and many projects funded with government support, donations, his own savings and crowd funding as well. When I raised the question about how was he making a living, he seemed pretty tired of addressing this topic, and then he was very straightforward with me:

[quote]
Well, this is one of the first thing people ask, always, everywhere. And I think that if the person made this question, she or he either made the wrong question or has not understood a word I have said. […] People are like “ok, but how do you make a living?” I just told them about a lot of awesome stuff, awesome projects and the first doubt is where does the money come from? The money comes. I can tell you exactly where the money came from in every project I do. But that is not the answer people are looking for. They ask me how do I make money because they want to find a way for them to make money. Thus I say I make money just like anybody else: working. I work, people pay me. They reward me for my services. […] And what do I do? Software development, consultancy, I have done publishing, video, events…

This quote is representative of a lifestyle that was found widely among these interviewees: I have heard several times, from different people, that they prefer to count on several (ordinary) geese than to count on a (single) goose that lays golden eggs. Furthermore Pedro's answer is strategic in the sense of calling the attention to what really matter for him: the awesome projects, in his own words. By saying that there is nothing special in the way he makes a living, he is turning the spotlights back to what he wants to emphasize. This faith in the projects and in this lifestyle is at the core of his assumption that there will always be money for interesting projects. The focus is on his actions, not on the money to sustain the action themselves, neither on the way Pedro himself is making a living.

Emily is a British woman who as part of a team that launched a crowd funding platform in the country in 2011. They were pioneers in the UK. As Pedro, she also discussed this primary focus on projects, not on money, as a relevant topic when it comes to the motivation to get involved in crowd funding:

[quote]
I don't think there is many people who set out because they are like “I want to make millions of pounds.” They kind of set out because they are like “I think this is a really interesting business model.” It shifts things so that some of the most effective Kickstarter projects are the ones that effectively get user information, get to connect with users. You get to iterate and change your project much faster […] and you get advanced orders, so the risk is lower. It feels like a much more connected relationship that those projects typically have with the people who will be using [the outcome of that] project.

The first thing to highlight in this quote is that it does not dismisses the importance of money: “you get advanced orders, so the risk is lower.” Even though money does not seem to play a protagonist role: the connection to the users seems way more relevant. Therefore a business model that empower this relationship between creators and users sounds more attractive than a more traditional market exchange. Yet Emily believes that even though people who are interested in making a lot of money, as fast as possible, exist in crowd funding communities, this is not what pushed her to get involved. Taking into account her own experience, while setting up the platform in the UK, they had two good well established references from the USA: Indiegogo and Kickstarter. She pondered about the position these platforms have assumed so far:

[quote]
We interviewed with Kickstarter, Indiegogo, a bunch of different platforms just saying “look, we are doing this over here in the UK.” We were even open. If any of those platforms wanted to launch under similar principles in the UK we would be really happy to point the audience that we had at them […] Kickstarter is financially driven. I think that is their main priority. I think it is something that is around, things like the environment […] It wasn't a good fit and they just had no desire to really be open. Indiegogo were more open. They have [shared] a lot of their data and learnings […] I think that Indiegogo were fantastic, they had a bunch of information talking about typical statistics.

It is clear in Emily's description that not every crowd funding community shares the same principles, specially when it comes to money. Hence it is relevant to understand how this heavy users and people dedicated to crowd funding users forge their take on money. A starting point for this debate might be their family background. On the one hand, the kind of choices and judgements many of my interviewees have been making seem to have been built throughout their life trajectory in spite of their family values. It was common to find people that at a certain point of life changed their career path, change city, job, professional activity and the way they make money. On the other hand even if this movement configures a kind of rupture, they were able to weave a safety net in advance. 

Anna moved from a different state to São Paulo for her high school, and a couple of years later her sister followed her. She was enrolled in one of the most traditional and high quality schools in São Paulo city. She told me that “until the senior year it would be weird to even entertain the idea of going to a not so traditional university” — referring to the projections her family had for her. Fast forward a couple of years and she was graduating from one of the best law schools in the country. Next she worked in great law firms before she quitted to start a crowd funding platform focused on learning, Cinese. Her sister followed a similar path, including a master in the UK, to later join Anna as Cinese co-founder. Their life story so far illustrate the kind of rupture explored in this section.

In fact most of my interviewees have a great educational and professional background. Many went to the best schools in their countries and abroad. Rodrigo, for example, born in Wales, is a CPO at an American crowd funding platform. He holds a BA from University of Oxford, a MS from MIT (Massachusetts Institute of Technology), and recently he started a PhD at Stanford University. Among the Brazilians, many hold graduate or postgraduate degrees from traditional schools in journalism (Cásper Líbero Foundation), law (Pontifical Catholic University of São Paulo), business (Getúlio Vargas Foundation) and communication (School of Higher Education in Advertising and Marketing), for example. As Anna and her sister, instead of sticking to a more traditional career path — something like applying for an internship in a multinational company, finding a job just after graduating, and celebrating a promotion to a management position before they are 30 years old — they change. Despite their outstanding professional profiles, and despite their family values that have been supporting them through their formal education, they decided to pursue different trajectories.

Surely this cannot be generalized. Among the interviewees I have met some people that, in spite of coming from families that would support their formal education, they have dropped out from college or have never started at one. Still they were very successful in their professional life so far.

Felipe, who funded his Master degree in the UK through a crowd funded project, discussed this rupture taking into account his own family values, but at the same time he was justifying why he was able to do something different from that traditional career path:

[quote]
We have been told about the best professions, we have been raised with this idea. A good profession is one with a good salary, because at the end of the day that is how we make a living, isn't it? Our parent's generation went through very difficult times, the country's economy wasn't in good health. Thus it was a kind of _every man for himself_ (_sic_); and that is embedded with them, that one has to get a job in order to provide some financial stability to one's family. Now I thing we are in a different time, a time in which we can be more flexible.

Hence it is important to consider that when it comes to these interviewees, that is to say, to the ones more engaged in crowd funding, what matter is not only to understand they choice for crowd funding, but a more overarching set of values that pushed them to follow a non-traditional career path. In other words, even if they value money, they do not seem to value the more traditional and arguably stable means to achieve a sort of financial stability. For instance, if Pedro held that he makes money just like anybody else (by being paid for employing his skills) one might suggest that there is no difference between the exchange going on there and the one in the more traditional labor market: someone performs a service and is rewarded for it. However for for most of my interviewees there are subtle differences, not in the exchange, but in its meaning.

Pedro particularly does not seam to like describing things this way — after all he clearly stated that he makes money just as anybody else. Yet his view on money varies depending on the context. At a certain point of the interview, when the topic was making a living, he sustained that “while one has money, money is not a problem; money only becomes a problem when one is short on money.” His strategy was the same as described before: stop thinking about money and run your project, embrace the hands on mode and if the project is interesting enough, the money will come. However when discussing how he handled money in his own projects, he made a slightly different statement: 

[quote]
I think this _hands on_ imperative is always there. And money is not a problem, there is money, we can find how to sort that out. But having money doesn't mean a better situation. Usually when we make some money this becomes a problem: “wow, now we have money, let's do it!” […] I don't want people focusing on the money. I want people to get involved because they decide to put their energy on it. When people run out of energy, if there is nobody else out there to get things done, the project can be called off, it's not essential to human existence anymore.

There is still a despise for money in favor of the prominent role attributed to motivation, to personal values and interests. But this time even having money can be a problem. His issue reflects the classical Simmelian dark side of money: money dehumanize social action bringing corruption to the table (Simmel 1978) — Pedro has to know people who work with him are doing that due to shared ideals, not because they see an opportunity to make some extra cash. This despise for money together with the belief that there will always be money might erroneously suggest that Pedro is rich, which is not true. He is not claiming that there is an abundance of money whenever he needs it. However he believes that if his skills and ideas are relevant to others, there will be money – and this is what really matters for him. In fact he makes money from public or private open calls and biddings, traditional contracts with the public sector, contracts with NGOs, informal economy and barter, among many other possible sources (crowd funding included). Therefore money is an important part of the projects and of is lifestyle; the challenge here is to resignify it not as a wealthy to be desired, accumulated, but merely as a fuel needed to put ideas forward (as well as to survive, pay the bills and so on).

When I interviewed Anna she was in the middle of a reflection regarding this same issue. She and the other Cinese founders have been running the platform for a couple of years but at that time the great question was how to keep it financially sustainable; and from this debate the meaning they expect from money emerged in bold terms:

[quote]
We are in a kind of desperate phase. We think Cinese is already successful, it works. It's a great network, we have a lot of work to do, we generated a lot of things, but this is not bringing money in. So we got that there's something wrong going on. We are doing something wrong. And in this phase we are trying to find out what is wrong; how could we change this percentage based remuneration, something that is super rooted in the idea of scarcity. It makes it more expensive for those who use the platform, so it's not what we want.

In their platform users post any kind of meeting focused on sharing knowledge, skills, techniques; in sum, any kind of educational experience. People pay to register to some of these activities and then the platform keeps a small percentage of these values if the activity is confirmed (that is to say, in case it reaches the minimum amount of participants; otherwise all the money return to the users). Later, when I was talking to Giovana, a staff at a crowd funding platform, she added: “being financially sustainable it not only a need anymore, it is also a matter of people saying ‘there is a value in what you do.’” On the one hand these two statements by Anna and Giovana might be challenging Pedro's belief that there will always be money for interesting projects. On the other hand, they are basically claiming the money as they believe in their initiative: their judgement consider that the platform is going well, and even if they depend on their saving to cover all their living costs, they avoid pushing the percentage method further (what in the end of the day would grant them more money) because it is not coherent to the their principles.

Underneath their reluctance regarding the current business model there is also a critique to decisions based on the idea of scarcity, as Anna put. In other words what she is saying is that money should not be treated as something scarce, to be accumulated. They need more money to keep the project online, but they are very critical when it comes the means to achieve that — different means would represent different ways to see money:

[quote]
When we had not perceived yet that we were not a start up, nothing not even close to that, we used to receive some proposals from venture capital. But then we understood that we did not want a traditional path, a traditional company. We were inside a different group, trying to reinvent what a company is about. A way in which the end is not about profit, not even close to that. What is this model? We do not know yet, we are still building it. But we think that if we take that [venture capital] route we will end up in the traditional model of income, and that is not what we want. We are not willing to give in on that point.

For Anna and Cinese co-founders the core principles of the project should be enough to determine if the platform is successful. Yet in technical terms they believe that having more activities online does not represent an proportional increase in their costs to keep the platform running, so the percentage model adopted became problematic: while the actual percentage is not covering the bills, raising it would mean jeopardizing the main objective of the platform — it would make more expensive to organize learning activities through their platform. They were still trying to find a way out when I interviewed her.

In these settings it is worth it to say that savings are an important (and probably a restrictive) part of their lifestyle.footnote:[Counting on savings among young people was much more common in Brazil than in the US or UK. A hypothesis (not explored here, but popular in the media; see Pramuk 2015 for example) is that the expensive tuition fees in the US and UK could limit the possibility of young people taking risks: as soon as they graduate, they have to start working to pay their education loans. In Brazil most of the top universities are public and free, and even the private ones have mostly affordable tuition fees and funding options that alleviate the restrictive aspect of it.] Many of them had the chance to prepare themselves financially before assuming certain kinds of risk. As most of my interviewees have a great educational and professional background, they also have opportunities to join high ranked corporations, jobs, and projects — that is to say, despite eventual savings, their profiles represent their own safety net.

In that sense savings and high competitive profiles in the jobs market means that they are not (too) afraid of failing. It does not mean that they are 100% confident in their capabilities, but they are confident that if everything goes wrong, they can easily find a job, a freelance, get back to their old careers and so on. Evidently none of them want that; in fact just a few of them entertained this possibility in the interview as something really tangible or conceivable. But it is difficult to deny that they have a great combination of outstanding CVs, uncommon life experiences, rare mix of skills, and the valuable entrepreneurship reputation that can help them to be offered a post relatively quick in the market. Furthermore, usually due to their successful professional background prior to crowd funding, they have savings. All in all they have a solid set of assets that could grant them a quick way out at anytime — even if that possibility sounds like a nightmare to their aspirations.

This arguably solid safety net has influence over the way they embrace the possibility of making a living out of crowd funding, whether it is a project creator or by getting involved in the platforms themselves. They consider that it is an utopia to actually live without money, so they have to make money somehow. However they value the subjective meanings of money, as well as they value the subjective means inherent to the different ways they could make money for themselves. From this stand point, and backed by their own safety net, making money is put on the background but not dismissed at all. Maria is a Romenian woman who, as Felipe did, partially covered her Master degree in the UK through a crowd funding project. She is a journalist and photographer, mostly freelancing since she graduated. She described her relation with money:

[quote]
I had a lot of thoughts around money and pricing lately, about asking for money and how do you price yourself. You know how much is an hour of your life worth, but also it is skills sharing, you know? How much is an hour of my life equal to someone else's who is giving me another service? How am I going to make a living as a freelance if I feel bad for asking for money? And I always looked at money as this kind of bad thing that I don't really want to deal with. I never wanted to be rich or have three cars and four holiday houses or anything like that. So I haven't placed value on money in my life and I realise that it is partly because of my attitude towards money. And I really think I'm really bored with it [money], I'm over the attitude of feeling guilty for pricing and feeling like I'm somehow using people. If I would ask for [money] I would end up just working for free because I didn't want to price myself. Now I see it exactly like this: I wouldn't use out of personal preference but because it's still a very heavy way of exchanging and relating. I will then use it as a resource that comes and goes. It's not something that I want to hoard, but it's something that can enable me to put in practise things that are meaningful to me; and I think that is a positive, yeah, yeah. So I'm working hard at reminding myself of that as well.

If money is not something to be accumulated, not something to be taken as a rule to measure a person wealth or value, Maria's quote configures it as something that should flow. A highly competitive take on money, as it was a scarce good, would compromise these interviewees' endeavors: they would never be sure if people are engaging with their projects due to ideals or due to pecuniary interests, they would feel sabotaged in their attempt to disrupt the traditional career path, and most importantly they would doubt the effectiveness of their own projects. Cinese is out there to create and nurture a network focused on learning, not to make their founder billionaires, Anna would argue. However it is another Felipe, from Brazil, that better illustrates this point. He is one of the founder of Softa, the software house that developed Catarse. This initiative was the first crowd funding platform of the country and the first crowd funding platform in the world to be made open-source. Catarse is still the biggest crowd funding platform in Brazil. Felipe highlights the role Catarse has been playing:

[quote]
Catarse is not billionaire. It does not generate billions. But for sure it helped to change the national scenario. To be clear, Catarse helped to change the whole creativity scenario in Brazil. Music, drama, comic books, documentaries, you name it. When you have a direct connection with your fan base, even if someone with money stops investing in you, you still can raise hundred thousand dollars easily if people treasure what you have done.

At this point of the interview I was intentionally comparing Catarse to the multi billion dollar Kickstarter. Felipe felt very comfortable with the money and experience Catarse granted him (he is not directly involved in the platform anymore). I could notice that becoming or not a billionaire seemed far away from his aspirations. Even though it would not make sense to label him as radicals trying to dismiss money at all — on the contrary: he reinforced how people involved in Softa were able to profit from Catarse and from other successful projects. Eventually Softa became another company that adopted the motto “power to the crowd,” meaning that they started to only run projects that they believed to subscribe to this ideal. But when Felipe was pondering on the life paths of founders who left the company he did it not mentioning money; instead he recurred to personal aspirations and values:

[quote]
Those people mastered the technical side of Catarse. They left Brazil following a brilliant insight, “dude, I want my family to be safe.” And then with jobs abroad paying tons of dollars it got easy to read and show the history of civilization to your 10 years old son, and to travel with him around the old continent while discussing the history behind each place with him. Isn't it? Those are things that even with a 20 thousand dollar, or 25 thousand dollars wages in Brazil  no one can do that. It's difficult. So there are a lot of questions to take into account.footnote:[Those wages are considered high in most Brazilian cities according to Felipe. In the country the minimum wage is less than 3 thousand dollars per year.]

Hence the idea is that money is an important mean to put ideas forward, to support projects they believe in, to sustain communities and creations and also to enable them to adopt a lifestyle that diverges from the corporative career path these people would have been believed to follow. Any of these possibilities corroborate money's inherent value as well as the possibility to exchange it worldwide. But at the same time none of these possibilities seems to lead inextricably to stand for the accumulation of money. In sociology many have argued that money is not a thing by itself (Dodd 2014) and that money ultimately represent social relations of debt, marking a never ending, back and forth series of _I own you_ in close communities of trust (Graeber 2011). Crowd funding seems to embrace this social understanding of money, but in a pragmatic way that does not dismiss the utilitarian employment of money — and that is what they need in order to make projects tangible, in order to do a history study trip with one's on children, in order to sustain the rupture discussed in this section. Or, to put it in other words, even if money is a kind of entity detached from any moral assumption, its accumulation is not necessarily valued. 

Later on, still comparing the revenues and objectives of Catarse and Kickstarter, Felipe added that the American start up opted for a tech shop approach, building a strong network supporting the tech and makers scene. He added also that being in the USA is also a competitive advantage — it is the first option for global creators, gathering not only pledges from Americans but from people based all around the world. And Kickstarter got pretty considering these objectives, he added. One of the founders of Catarse also mentioned that Catarse embraced a community building strategy, an option to be closer to project creators:

[quote]
Nowadays our success rate is 56%. For example this is better than Kickstarter's rate. We are more and more working closer to the projects and thinking that every project has to have conditions to reach their target […] When a project is successful, the creator wins and also we win.

According to him, and according to Felipe, being or not a billionaire does not work as a measure to Catarse's success. At the end of the day what really matters is that Catarse “changed the whole creativity scenario in Brazil” — and, for that, they needed money to be circulating through their platform. Catarse's open source culture pushed them to open their balance to the public. In the year of 2013 almost 1.5 million dollars was made in pledges in successful projects in the platform. From that total 87% went direct to project creators, 4% was used to pay the payment gateway and almost 2% to taxes. Only 7% of the money is used to keep the platform online, to pay for infrastructure, and for staff. In opposition to Anna, Catarse believes that giving their dimension the percentage scheme is working for them. They can operate in a low percentage rate, the feel they are empowering project creators, and they strongly believe their business model is promoting change in Brazilian cultural scene. This math I made here is only employed by them to support the idea that they are mostly a platform that facilitate the circulation of money; or, in other words, is only used in an attempt to distance themselves from the image of a middleman, favoring the image of an tool for empowerment.

== The moral behind circulating money

There is a comic in the internet picturing what arguably is a layperson perception of a middleman: it starts with a building on fire, a desperate man and another character wearing a cape, just like a superhero. This former one also has a big “MM” in his chest. The desperate man asks for the superhero help: “My wife is in that burning building! Please help me, Middle Man!” Then the Middle Man superhero points his finger at another superhero, considerably stronger than him: “This sounds like a job for that guy!” The last part of the comics shows the stronger superhero flying and saving the desperate men's wife. Middle Man looks peaceful grabbing a cup of tea or coffee (DenBleyker 2015). The Middle Man in this context is someone basically useless. At maximum he knew the right guy for a given task and, as he was the first savior that came to the mind of the desperate man, maybe he took some credit for the heroic act done by the other superhero.

The resistance to the image of a middleman among the crowd funding community is meaningful because it puts together different aspects of how this community deals with money: in their opinion crowd funding means a strong connection between creators and public, squeezing the room for middleman like recording labels, publishing corporations and so on. Crowd funding, according to this argument, would empower ordinary people and promote diversity, since the approval of these middlemen is not necessary anymore. Yet according to this image the role of the middleman is an obstacle in at least three ways of power. First it is seen as a greed actor that keeps most of the money,sales, leaving almost nothing to the real creators; a common critique in that sense is made against digital content stores such as iTunes Music Store and Spotify, business that pays a very tiny percentage to the musicians themselves. Second these middlemen configure a market in which only the most famous and popular creator are able to survive; after all with just this tiny percentage only a high volume of sales would assure a reasonable income. Third in such space there is a small incentive for niche markets because they might not reach the required volume to be profitable. In other words this is a power derived from a mechanism that allows great concentrations of money; a power that, as a consequence, is able to decide which projects are going to thrive and which projects are going to fade out unnoticed. And these problems are exactly the problem crowd funding is trying to tackle at first place: the idea is to create opportunity for projects that could not find a place in a world dominated by governments and corporations, the means to achieve that is using crowd funding to connect ordinary people with the creators of projects they enjoy and believe in. 

However a side effect of the position taken by crowd funding is that they end up being the very definition of middle man by economic theory: an actor that conquer its position in the market because it reduces transaction costs (Wang 1999) Platforms help people find interesting projects, they ate basically window shop for alternative cultures. Platforms enable any project to have an electronic address accessible world widely, promoting their call for actions, asking for money, standing up for causes and so on. In creates a hub connecting this two sides of the same business. Yet they also reduce transactional cost because they enhance trust within the community; a common example repeated by the interviewees is that probably a “manually organized” crowd funding would not be as successful as these online platforms. Trust would be a serious issue if they were supposed to make a deposit in someone else account with the promise that if the minimum amount required to kick off the project was not reached this person would return the money. Online crowd funding platforms assume this role, bringing more trust to the network. Furthermore crowd funding platforms most of the times act as a curator to projects they host (including the power to decline projects in some cases): they argue that they could have thicket or a garden. That is to say, if they remove the curatorial layer, the anything goes policy would end up in not so polished projects, a wasteland and its thicket. Thus they argue that in many cases having a curatorial layer makes the platform looks safer, more attractive and more reliable — a beautiful and flowery garden.

Therefore they need a strategy to balance the middlemen image, that is to say, to favor the bright side of it. And that is why the building of a network, a community, the emphasis put on connecting people is the first pillar: it really created a digital space where people can look for the very specific projects, local creators, alternative scene and so on. But only connecting people would not work. The earlier internet with its network of blogs and social networks would have done the job before crowd funding platforms emerged. Money had to start changing hands in order to allow projects to thrive — and that is the second pillar of their strategy. They would say that money enters the scene out of necessity, not out of greed, of capitalist mind set to work and to save. Finally, in order to trace a more definitive line separating them from more traditional capitalist middlemen, crowd funding platforms employs an undeniable political discourse: they are a middlemen (even if they veil this fact) that empowers ordinary people, that fight against the institution that concentrate power and dictates the north for creative, tech, start up, artistic communities. This is achieved when they push the spotlight away from money and directs it to the “awesomeness” of their projects, when they measure their success through the community they have helped to form and through the niche markets they helped to thrive, when they distance themselves from regular corporations and even start ups. They grant themselves the noble mission to empower ordinary people, that is to say, to stand up before incumbent institutions. They are the ones who made possible that music album from the band next door refused by all the big recording labels. They are the ones that made possible the urban intervention that gave voice to a minority the government insisted to ignore. They are the ones behind the geeks who created that fancy gadget no big player from the Silicon Valley took the risk to launch. They bridged tons of donations to cover medical treatment of victims who had no access to hospitals, drugs and doctors. And meanwhile they put all those noble objectives before money.

In this perspective if money is not definitively put in the background, the discourse sustains that money is merely mean to achieve these noble objectives. To reinforce what is underneath this idea it is important to clarify what is called into question in this movement.
In the beginning of _The Protestant Ethic and the Spirit of Capitalism_ Weber (1976) recurs to Benjamin Franklin to describe what was the _historical reality_  he was taking into account to forge the concept of _the spirit of capitalism_:footnote:[Weber employed the expression _historical reality_ in the very beginning of the _The Protestant Ethic and the Spirit of Capitalism_ in order to describe his methodological approach: "Such an historical concept [the spirit of capitalism\] … cannot be defined according to the formula _genus proximum, differentia specifica_, but it must be gradually put together out of the individual parts which are taken from historical reality to make it up" (Weber 1976:13).]

[quote]
Remember, that money is of the prolific, generating nature. Money can beget money, and its offspring can beget more, and so on. Five shillings turned is six, turned again it is seven and threepence, and so on, till it becomes a hundred pounds. The more there is of it, the more it produces every turning, so that the profits rise quicker and quicker. He that kills a breeding-sow, destroys all her offspring to the thousandth generation. He that murders a crown, destroys all that it might have produced, even scores of pounds (Franklin, cited by Weber 1976:15).

At the same time this passage highlights two distinct characteristics attributed to money: on the one hand there is the property of self multiplication, the idea that money, if handled properly, can generate more money in the form of profit or as return of investments. On the other hand, it reflects an arguably universal will to accumulate money, as  this accumulation was a virtue _per se_. In these circumstances money is desired not because it holds any moral value, but because accumulation became an end in itself (Simmel 1978, Weber 1976, Hirschman 1977). Both these views are contested within the crowd funding communities: they do not deny that money generates more money, but they prefer to see that money empowers action, makes projects tangible. Therefore accumulating money is also put in the background: money makes sense in circulation. Even the need to save is debatable: on the one hand, they depend on their safety net to take more risks. On the other hand accumulated money does not results in action, does not help them to achieve their life aspirations.

Regarding the moral question surrounding money it is worth to discuss how it is possible to assume that money can be, at the same time, a kind of amoral and universal measure, as well as an entity endowed of moral judgements (Zelizer, 1994 and 2007). In heterodox economics, for instance, Hirschman (1977) described how the Enlightenment dehumanized _passions_ into economical and commercial terms such as _interest_. Within sociology, Weber (1976:116) argued that the asceticism of certain Protestant religions condemned the enjoyment of life in the form of consumption, leading to an “accumulation of capital through ascetic compulsion to save”:

[quote]
The capitalistic system so needs this devotion to the calling of making money, it is an attitude toward material goods which is so well suited to that system, so intimately bound up with the conditions of survival in the economic struggle of existence, that there can to-day no longer be any question of necessary connection of that acquisitive manner of life with any single _Weltanschauung_. In fact, it no longer needs the support of any religious forces, and feels the attempts of religion to influence economic life, in so far as they can still be felt at all, to be as much as an unjustified interference as its regulation by the State (Weber 1976:33-4). 

_Weltanschauung_ is a German term for world view. This chapter has described how people involved in crowd funding are departing from, and at the same time are forging, an alternative world view. And this alternative world view is the one in charge of attributing to money a different aura than the one this “devotion to the calling of making money” — crowd funding has its own calling, that is to say, from the logic of the institutions that share an understanding of money as something to be accumulated, from the logic of institutions that assure their own power through the accumulation of money. Money with crowd funding communities become something that should circulate, an approach closer to what Dodd's (2014) described as an utopian money.

Finally, by attempting to challenge this incumbent institutions, the main players in the neoliberal market as well the government supporting this economic policies, crowd funding establishes itself as a political discourse. In Graeber's _Debt_ (2011) he sustains that it is possible to make such a clain by resignifying money: 

> “The only thing that's clear is that new ideas won't emerge without the jettisoning of much of our accustomed categories of thought … and formulating new ones. This is why I spent so much of this book talking about the market, but also about the false choice between state and market that so monopolized political ideology for the last centuries that it made it difficult to argue about anything else” (Graeber 2011:384).

Crowd funding communities seems to be in the stream of this argument. By resignifying money in their everyday live they contribute to a new world view that corroborates the false opposition between market and state. Ironically this is achieved through one pillar of the neoliberal capitalism and another one from the democratic nations: the idea of the middlemen and the idea that the state should look after minorities. Those paradoxes are not denied, but the strategy they adopt is clearly pushing in the direction of the positive interpretation of what they could represent. In other words, they fine tune their strategy as a political, not as a matter of business or management. And in fact there is some consistency in that claim: the next chapter explores how this resignified and flowing money empowers autonomy, an important aspect to _action_ (as in Arendt 1998).

== Bibliography

Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.

Bogost, I. (2015). The Internet of Things You Don’t Really Need, _The Atlantic_. Available at: http://www.theatlantic.com/technology/archive/2015/06/the-internet-of-things-you-dont-really-need/396485/ [Accessed: 23 Jun. 2015].

Catarse (2013). Nossa taxa de serviço – Parte 1: de onde vem e pra onde vai o dinheiro do Catarse. _Catarse_. Available at http://blog.catarse.me/nossa-taxa-de-servico-parte-1-de-onde-vem-e-pra-onde-vai-o-dinheiro-do-catarse/ [Accessed 8 Feb. 2014].

DenBleyker, R. _Explosm_. Available at: http://explosm.net/comics/3869 [Accessed in 18 Mar. 2015].

Dodd, N. (2014). _The Social Life of Money_. Princeton and Oxford: Princeton University Press.

Graeber, D. (2011). _Debt: The First 5,000 Years_. New York: Melville House.

Hirschman, A. (1977). _The Passions and the Interests. Political Arguments for Capitalism before Its Triumph_. Princeton: Princeton University Press.

Hoffmann, S. & Feddersen, O. (2013). Karma Chakhs 2. _Startnext_. Available at: https://www.startnext.com/karma-chakhs2 [Accessed: 15 May 2016].

Le-Mentzel, V. B. (2012). Karma Chakhs. _Startnext_. Available at: https://www.startnext.com/en/karma-chakhs [Accessed: 15 May 2016].

Patreon (2016). Patreon: About. _Patreon_. Available at: https://www.patreon.com/about [Accessed: 22 May 2016].

Pramuk, J. (2015) Student Debt Crushes Innovation: College President. In CNBC. Available at http://cnbc.com/id/102377355. Accessed 28 Jan. 2015.

Simmel, G. (1978[1900]). _The Philosophy of Money_. London and New York: Routledge.

Wang, N. (1999) Transaction Costs and the Structure of the Market, _American Journal of Economics and Sociology_, 58(4). Pp. 784-805.

Weber, M. (1976[1900]). _The Protestant Ethic and the Spirit of Capitalism_. London and New York: Routledge.

Zelizer, V. (1994). _The Social Meaning of Money_. New York: BasicBooks.

Zelizer, V. (2007). Pasts and Futures of Economic Sociology, _American Behavioral Scientist_, 50. Pp. 1056-69.
