= Autonomy
Eduardo Gonçalves
:revremark: Draft of chapter to the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy.
:revdate: August 2016
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men (sic) were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live (Arendt 1973:8).

The last chapter's discussion on money is one element of a complex mélange that defines a specific world view widely adopted by the crowd funding community. Another element of this mélage is the understanding of what is at stake when they purportedly adopt an alternative and marginal lifestyle — especially when it comes to the notion of making a living out of a career. Maybe a first impression about people who are trying to resignify money would point towards an utopia, a desire to change the world. And in fact that was what Felipe told me:

[quote]
[The bachelor degree in] geography gave me incredible tools to work with sustainability. And then, when I was 20, 22 years old I was totally addicted to working and changing the world. And I'd work as hard as possible, for free, out of passion.

Before starting his partially crowd funded master degree he had been an undergraduate student in two different fields: economics and geography. He opted for these courses because he felt the world was sick and needed to be saved: he would claim natural resources were disappearing, escalating levels of pollution were condemning the environment, and people were deeply deluded and exhausted in their obsession for work and making a living. The result, yet according to him, was a toxic world with serious personal and social issues. This situation was unbearable for him and thus he thought something had to be done.

When he was starting his higher education Felipe went for economics because, as he put, “it would provide me with knowledge about the system, about social life, and later I could get into ecology, ecological economics, green economy.” The _system_ is a way many interviewees would use to address the overarching values fostered by the incumbent institutions,  such as corporative market and the national states. After a couple of years Felipe changed his mind: “I had taken a too long diversion to actually get to the point where I could study sustainability, study labor, cultural and social alternatives.” He started to look for alternatives and geography seemed like a good idea: “according to the programme I would study natural sciences, social science, humanities and the correlation between them.” He then changed from economics to geography trying to do something to save the world — or, at least, trying to prepare himself to do so.

From this background it is comprehensible that when he graduated he was up to pursue arguably overarching objectives: he was aiming at changing the world, at changing the system. Later, at the time of the interview, Felipe himself would label these objectives as naïve:

[quote]
I have worked for NGOs, it is a little bit of my trajectory. And there are other things. I have worked in the market for big companies such as Petrobras which is a semi-public corporation. And I have worked for small initiatives. And I started to see that I did not believe in the idea that we would change the system form inside out. […] Actually I do not think it is about changing the system. I think it is all about bringing an alternative, from the outside — that is why my blog is called _On the Edge_, it is a culture living in the margins, it flirts with the real and the anew, what is not there yet.

His master degree focused on the collaborative economy. According to him this route seemed promising because “it moves away from the default of changing the system.” Specifically he claims that this route does not take a combative position against the system (or, at least, against the monetary system, as he mentioned in the interview): “let's leave the monetary system there, let it go. It will change if it has to.” Yet he thinks it is a waste of time to fight the monetary system, it is like “throwing small stones against a big wall.”

Interestingly his position does not imply that he had abandoned the idea of doing something to make the world a better place. It means he had scaled down his actions, keeping his ambitions as high as they were before. Once he realized he will not change the system from inside out, he adopted a new strategy that focus on small actions, on possibilities within his reach. It is not about solving the problem for everybody, it is not a revolutionary take on the world. It dismisses the global and outward expectation of _changing the world_ and replace it with a local and inward version of it.

Engage was one startup from Brazil that used to work under the motto _power to the people_. One of their co-founders summarized this process described by Felipe in a few words (as this co-founder has himself went through a similar change in terms of life objectives):

[quote]
Engage was built with that ‘change the world’ idea in mind. And my history with Engage was all about getting tired of this chip chatting. But I do believe we are changing the world. I do not consider myself a dreamer. I am a very pragmatic guy who, at the same time, dreams a lot — otherwise I would not be able to be pragmatic.

Life stories like that raise important topics for discussion, topics that clearly take the process of resignification of money to another level — to be more precise topics that justifies this resignifcation with some purpose. Governments and corporations can act as constrains to actions and thus the strategy is to minimize the relevance of these institutions within the crowd funding communities lifestyle — namely what they are pursuing is autonomy. Surely the approach to autonomy discussed here emerged from the fieldwork and the idea is not to measure, corroborate or deny how autonomous my informants really are. What is relevant is to understand what they see as autonomy, how they pursue it, why they do it, and how this relates to the social and political framing of their choices. The first section of this chapter looks into the problematic escaping strategies towards autonomy, a series of tensions in the struggle to reject certain institutions while, at the same time, they are actually recurring to other institutions. 
This part investigates why from their standpoint change from the inside out is more feasible in some institutions than others. The second section of the chapter takes into account more radical attempts that instead of trusting in other existing institutions try to forge a non-institutional alternative. Interestingly in both cases they distance themselves from incumbent institutions without confrontation, and from their choices they end up building a new set of values that minimize the importance of these institutions. This is the core of their pursue for autonomy — not only for themselves, but for all the peers taking part in this endeavour.

== Distancing themselves from (some) institutions

Autonomy is a major driver to my interviewees' choices and this specific criterion leads them to perceive institutions as obstacles in fulfilling their life expectations. Surely not all institutions are barriers and a lot of judgement takes place in their strategies to position themselves into the world, to pursue their ideal of autonomy. Their movements accepting or denying certain institutions tell a lot about what they understand as autonomy. Felipe's case, for instance, points towards the problems of trying to promote change from inside out, but a lot of other interviewees believe that institutional arrangements can help them in the arduous task of making a difference in such a sick world. Carla, for instance, started a promising career in the advertisement market, but at a certain point she started to have similar thoughts as Felipe:

[quote]
I hold a degree in advertisement, I worked for 10 years in advertisement agencies with planning and research. Then a couple of years ago I started to realize that all my investment in terms of time, of daily efforts, of commuting, and of focus on the projects I'd run, all that was kind of useless. I worked in an agency and I was part of a process that would end up to a banner in the end of the day. It was a communication piece that would only feed this Machiavellian system.

Carla was pondering not merely about her dissatisfaction with her job. Her reflections target two very specific things: on the one hand the purpose of the market she was contributing to and, on the other hand, what was painful in this process was not only that this market was going somewhere she would not approve, but that in the way she was investing all her most personal values: her efforts, her time, her focus and so on. Furthermore she told me: “I felt there was something missing, I could be contributing through other ways to project development, to innovation… to innovate with positive impact.” Her strategy to go to the margins, to the edge of a well stablish market was to specialize in design for social impact (she now holds a master degree in such field) and to try to engage with projects more focused on the city, on urban spaces close to her. Now she works in the strategic innovation market having experience at consultancies focused on positive impacts on society. Other interviewees also opted for working for this kind of companies: usually they are small to middle size offices, they hold multinationals such as Coca-Cola, Nestlé and Petrobras in their portfolio, but at the same time they value and develop projects for NGOs, civic activism and for the public sector. From times to times this small companies also have their own projects, that might become spin offs — that was the case of Catarse, for example.

Brittany is an American woman and in the interview she mentioned the choices she felt that were available for her after graduating:

[quote]
It's interesting to be able to create projects instead of just typing on a keyboard, and those were the kind of job opportunities I had: doing more office work for any organizations that were not particularly exciting as well. At that time too it was so competitive that I think I would have ended up having to be more focused on something with a better paycheck and not necessarily a job that is fun.

In other other she felt that all the traditional job opportunities were uninteresting, bureaucratic and limiting her creative and her “hands on” impulse. She is very concerned about the natural resources, climate change and the environment in general. But at the same time she did not wanted to work neither for the government nor for NGOs: “I don't have anything against the government, but I'm just more personally interested in private industry.” Therefore she moved abroad and started to work for a private park and nature reserve where she could start to manage projects instead of doing office and paper work. Her choice for a private environment was on purpose:

[quote]
I consider myself an eco-capitalist. I've never really imagined myself working for the government or NGOs. I am more interested in doing change through the private industry. Private industry is not restrained by borders as long as you have the right market incentives.

She believes that there is a higher chance of promoting substantial changes in the world from a private institution, with no borders — but she reinforces that the right incentives should be set by the public sector. Still she believes that federal government might be too big to understand her reality and to do the right moves:

[quote]
There is so many stupidity sometimes, because you have to deal with someone who will deliberate on an environmental project and they are 300 kilometers away, and they have no idea about what your reality is actually like. I do not think this is the most effective to do environmental policy. That is why it is nice to work on a private reserve because we have a relationship with the [local] public government, we are bordering a state park. I have a bit more liberty. We work a lot with the people from here. We do not have to deal with people who have never been in the area and do not know anything about it.

In different degrees what Carla and Brittany are claiming is that they want to be able to choose what kind of projects and action they enable in their everyday life. And yet this claim is sustained by a world view that consider governments and corporations too big to feel what individuals really face in their daily routines. If Brittany example is more clear (she even mentioned the _think global, act local_ motto during the interview), Carla's one might need further discussion: in spite of the multinational clients all the projects and deeds she mention in the interview are related to the urban space and civic activism projects she has been involved with. The consultancy she works for might not be exclusively focused on this kind of projects but she considers that since there is room for them, it makes the job more attractive than the other ones she had had in the past.

These two women are somehow recurring to the private sphere because they believe society needs change — namely one of them would say it needs some positive impact, the other would say it is compromised due to climate change and other eminent environmental catastrophes. Underneath these arguments lies the responsibility the state bear in such scenario. For Brittany, part of the problem is the distance between the spheres of the government in charge, and the reality of the governed people. Carla has not been explicit in supporting this view but her actions seems to corroborate it. During the interview she was listing some causes for the lack of social impact in many projects and she ended up saying that “it cannot be a single NGO, it is not Greenpeace that is going to sort that out, it is not the UN alone that is going to do it. It really has to be something massive.” At first this was intriguing: Greenpeace and UN are massive institutions after all. She explained it next:

[quote]
I think it [the solution] should be decentralized. That is part of Box's Brazilian Dream Project, the idea of microrevolutions, but the thing is that companies should also be decentralized. Thus when I say “something big” it is something that belongs to the people, that is part of everyone's concerns. Therefore not only people, but companies need to have an active role for a better society.footnote:[Box 1824, mentioned by Carla as _Box_ is Brazilian consultancy that built a great reputation publishing researches on Brazilian culture — most of them on Creative Commons licenses, free to read and watch on the internet. Those reports usually are shaped in short videos that easily become viral on the internet. Carla has freelanced for this consultancy.]

If this quote sounds too abstract or utopian, Carla offered as an example the case of public bikes in São Paulo. In a similar scheme to Barclay's bikes in London, they were structured through a private and public partnership, coincidentally backed by a nationwide bank too, the Brazilian bank Itaú:

[quote]
[Take the case of] Itaú's bikes: there are various issues that could be risen, a lot of questioning on whether it was more about marketing than about a proper solution [for public transportation]. But this was a social innovation to the city because it was considered within a mobility and civic movement […] People who were not using bicycles before are trying it now. Despite the [commercial] interests (because I do not believe they [Itaú] are just being nice, they are a bank) it is a social innovation.

Hence from Carla's point of view there is an important factor that is being close to people, to civic activism. Or in other words, being local — something that overarching federal governments and multinational corporations fail to achieve, as many of my informants would put it. In sum the problem does not relies on the private or public realm, but in the distance between individual and institution. To add another example, Noah is a graduate student in political theory also from the USA. Throughout his life he has been involved with civic activism and he has also contributed to some crowd funding campaigns. He told me about one of the projects he has been involved, one in which his group was very close to the city council:

[quote]
The objective of the organization I volunteered at was at the city level and we ended up getting a majority progressive city counsel. […] The city runs the airport and they decided that they were going to renegotiate the contracts for the food in the airport. They did not want to have corporate restaurants. They wanted to reach out to all very famous local businesses, restaurants and say “would you like a branch in the airport?” […] That was sort of one policy they want but the point I am trying to make is that I am always focused on building power at the local level, in the face of structures that are configuring the social relations at a larger scale. International trade treaties and national immigration policy [for example], these are all things that are sort of structural, but we were coming up with local ways to resist. Sort of asserting local power in the face of this larger structure.

The critique built by these people who at a certain point have recurred to crowd funding is not targeting explicitly the public or the private sphere, as Noah's example clarifies. They are at the same time targeting a specific world view that puts individuals as dependent of paternalist, of embracing government and corporations. In their nightmares they probably would be complaining that there are no jobs out there and that the government is not properly regulating corporations when it comes to the protection of the environment. But that is not what they are doing. Actually they have no intention of working for these corporations and many of them have no interest in voting for example. Most of my Brazilian interviewees (where voting is compulsory) have declined to vote in the past few years.

Stephen is a experienced British entrepreneur who mentor many social entrepreneurs. He points out that due to the economic crisis there are no jobs being created, therefore “being self employed for increasingly a greater proportion of the population is the only option.” In this scenario he sees crowd funding as a promising alternative since in many cases not even banks would fund certain entrepreneurs. But in opposition to most business men who praise the success of new companies such as Uber or Airbnb he is quite critical about them. Another example he mentioned in the interview was a British short term car rental:

[quote]
It started as Street Car which was a UK company, which is cool. Nice service, nice cars. It was bought by Zipcar which is an American company. The service went down a bit, the cars went a bit crappier. And it is now owned by Avis […] It is very hard because clearly it is having an impact. It does take a lot of cars off to the road. But on the other hand it is now part of a big corporation.  And it is working for shareholders rather than to the communities. And I think a lot of this stuff, for me, would be much more interesting if somehow you could keep it at a local level, a community level.  But you cannot do that […] The biggest obstacle is how you rethink money or if can you rethink money – and if you cannot then actually everything is all a bit meaningless because it all comes down to cash in the end.

Therefore if the critique does not target the public or the private in specific, it suggests that both spheres nowadays are driven by money. Corporations and government, my interviewees would claim, are distant from people's needs and reality because they are organized in a way that focus on making money and also on delivering money through a lifestyle based in an overarching policy that values jobs, wages and benefits. The problem is that the crowd funding communities are resignifying money, and consequentially they are not settling down for a comfortable job that offers them some financial stability. Their personal views on the world, on this system seems more important than the values being delivered and nurtured in most national states policies and in most corporate environments.

*TODO: bring Wollin in*

The stories mentioned above position the problem in the size of the organization: for them bigger institutions put the decision making progress away from their everyday lives. Therefore their strategy involves working in small scale institutions that enable three valuable things: conciliating personal values within their everyday life activities, being able to promote some actions with some impact, and avoiding bureaucratic and impersonal decision processes. The motto _think global, act local_ seems to have a perfect fit with this ambitions: the thinking part allow them to channel their dreams and aspiration to action; the acting part is taken locally, that is to say, is more feasible and easy to put forward than more ambitious projects that would require layers of deliberation. This deliberation if not handled at the personal level would be compromised, they would say: when people's opinion are framed into instrumentalized and racionalized institutional processes the only rule that matter is cash — and that is the kind of value that is not appealing to this specific community.

Hence action is of utmost importance for them. Their idea of autonomy is to be able to act, to put ideas forward, to experiment and learn from it. Carla herself is very clear on that point: she is not sure if Itaú's bike scheme is the best for São Paulo, she would not oppose a totally public nor a totally private initiative to compare them all later:

[quote]
It is very difficult to get it right the first time, thus we have to test, to hack, to experiment. I praise the initiatives with that mindset. And actually that is why I really like crowd funding. Crowd funding is a way to engage, to motivate, to show possible futures — that is what really matters.

*TODO: Summarize theoretical points together with Carla's last quote in this section.*

== Avoiding institutions

=== Context

[quote]
they’re using other people’s money so we understand but on the other hand, the state that the economy’s in everywhere and these people, you know, there’s a big opportunity for people to become entrepreneurs which I think is slightly overplayed […]. The jobs are, you know, no-one… there’s no jobs being created in the last 5 years. […] Maybe we all feel slightly better off because things are not quite as bad as they were but actually there’s no real jobs created so… so I think on the self employment and entrepreneurship is… is the way forward and therefore having people get access to money, the bank’s don’t do it so, err, crowd funding is quite interesting for that. And it has, as you see and as I’ve said, it has some very inherent faults I think.
— Stephen 

[quote]
P: um estatuto... eu voltei um pouco atrás na história... a gente começou a desenhar o estatuto, e quando a gente começou a desenhar o estatuto, a gente viu que ia ser impossível criar uma organização, porque a gente não concordava com um texto em comum... a gente tinha princípios e nortes... se gostava e se encontrava pra cozinhar e tal, mas... pra montar uma organização que tivesse um texto duro, um estatuto social dizendo o que a gente ia fazer, um queria fazer jornalismo, o outro queria fazer fotografia... e aí... foda-se, sabe, não precisa ter isso, sabe? Cada um faz o seu, e, ao invés da gente ter a associação, a organização, a ONG, a gente vai ter um espaço onde cada um faz o seu e todo mundo faz junto. 

[quote]
LO: acontecer... você vê... de fato a gente conseguiu a abrir uma via alternativa, né, a todo financiamento... ao modelo de financiamento que existe hoje no Brasil, né... o financiamento público, financiamento privado dos bancos... se começou a ver projeto sendo realizado, coisas, cara... o mundo se abriu … […] assim... e de fato não existia, cara: não existia uma maneira de você fazer projeto aqui no Brasil, de organizar projeto pequeno..

=== Bold rejection of institutions

[quote]
I didn’t want to erm kind of play the rules of the system just to get a very alternative education institution I just found I like this, this is ridiculous and even if I could get a loan from the bank would I really want a loan off the bank to go and study alternative you know education, like new economy and this is ridiculous.
— Maria

[quote]
A: E a coisa da empresa, e aí... que é daonde a gente vem e tira o dinheiro, e tal... que o problema é que a empresa sempre quer botar o bedelho... ela quer customizar. Então, se você busca uma independência de projeto, assim, bicho, sabe aquela coisa de jornalismo, "bota só a marquinha e não interfere no conteúdo editorial?". É difícil...

[quote]
A: A: Não, a gente entendeu que não era na ONG porque eles não queriam remunerar os meninos... então, a gente, "pô, a gente tem que criar um negócio que a gente consiga remunerar", né, ter essa autonomia de... de fazer o que a gente acredita, porque pra engajar o moleque tem que ser legal e tem que dar dinheiro pra ele... porque ele tá num momento... senão ele tem que trampar pra ganhar dinheiro e ele não percebe que ele quer trampar com aquilo que ele quer...

=== Micro inwards revolutions

[quote]
Então, enchi o saco dessa coisa... bababá mudar o mundo, mas... por exemplo, assim, ó: por que que o Unlock é tão importante pra mim - tirando as coisas que eu acho legal nele, em si? Porque eu sonho - e aí, palavra vem bem - em não precisar tem preço pras coisas... em não precisar criar serviços só por criar serviços... só pra resolver a questão financeira, né... então... isso reflete, em mim, uma vontade de que outras pessoas façam isso também... por: 1) mudar a vida dessas pessoas, assim como eu sinto que vai mudando a minha aos poucos... o fato de eu olhar e ver que eu tenho... eu e o Larusso temos 750 pila garantido aqui com o Unlock... do Unlock... já me dá uma segurança diferente do que a que me dava quando era... 200, sabe... quando não existia isso, né? Ou seja, cada lucrinho a mais que eu vou tendo por mês, porque eu tenho cinco unlocks, né, eu somo eles e vejo mais ou menos quanto eu já tenho garantido pro mês, assim... enquanto durar, né... porque as pessoas...
— DW

[quote]
DW:  Sou músico, né, e lá por 2008 eu interrompi minha carreira de músico porque eu tava exausto e especialmente exausto dum desequilíbrio muito grande entre a energia que tu coloca e o que tu recebe em troca, né... e eu decidi que eu ia aprender a fazer... na época, era marketing, a palavra que eu usava... pra, quando voltar, se voltar, voltar fazendo direito, né, fazendo duma forma que eu não fosse me esgotar como eu me esgotei. Aí eu passei uns dois anos mais startupeiros […] buscando todo tipo de escala que uma startup busca... só que no meio tempo eu comecei a dançar tango, bem nesses anos iniciais aí, […] quando começaram a surgir os projetos de tango na minha cabeça - as vontades de fazer coisas de tango -, eu sabia que eu não queria fazer algo onde eu investia um monte pra depois descobrir se tinha público e aí uma das ideias que eu tive foi, por exemplo, fazer uma milonga onde as pessoas pagassem antecipado, mas se não tivesse o mínimo de pessoas, não rolava a milonga. […] e nesse processo eu conheci o Kickstarter... aí eu disse "bah, cara, tudo... absolutamente tudo o que eu queria... todos os meus problemas acabaram" […]

[quote]
A: (incompreensível) autonomia do aluno... ele me libera pra ser mãe da minha filha, porque senão cê fica cheio de filho pelo mundo.. […] Enfim, então a autonomia do aluno é isso... você pode ser mais responsável por você mesma, quando o outro tem autonomia.

=== Hands on & money to work (not the opposite): autonomy is what empowers action

DW & Unlock from conference paper

SR not a bullshitter

[quote]
DW: quando fiz o Mailee por exemplo, quando me envolvi junto com os guris pra fazer o Mailee, foi, tipo assim... bah, ganhar muito dinheiro com isso pra ter dinheiro sobrando e poder fazer as coisas bacanas... essa era a visão. Quando eu conheci o crowdfunding, eu comecei a pensar que isso era desnecessário, que eu só precisava viabilizar as coisas em si... mas, a real é que eu nunca botei um projeto no Catarse...

[quote]
P: eu trabalho muito com o imperativo do fazer, né... cê pode ficar discutindo muito, mas isso é pra quem tem tempo...

[quote]
A: A: A gente... os meninos não tão na escola, né, eles evadem muito no Ensino Médio... e a gente falou, "pô, cadê os moleques?", "tão na internet", "como eles aprendem?", "tutorial no Youtube"... de matemática a maquiagem... e aí a gente ficou seis meses pensando em linguagem e rherherherherhé pra lançar um módulo de videoaulas. Aí lançamos ano passado e botamos no ar... arrumamos uma produtora parceira, que fez com a gente na raça, sem grana e tal... e botamos no ar pra ver. E a gente conseguiu três mil alunos. Aí a gente falou "não, bicho, tem uma coisa aí... tem uma demanda aí, então vamos fazer". E aí, como que nós vamos fazer? Não temos dinheiro pra fazer. E aí vem a história do Catarse. É uma coisa que é... pra todo mundo, né... a gente... qualquer um pode acessar... videoaula tem que ser de graça, porque é pra jovem do Ensino Médio, um pouquinho depois – eles têm muma dificuldade com essa coisa de grana pronta... então tinha que ser de graça. E daí como é que a gente ia financiar? Onde a gente ganha dinheiro? Produzindo conteúdo e fazendo pesquisa jovem... São as duas únicas formas da E.nos ganhar dinheiro. O que não pode faltar na E.nos? Formação. Que senão não tem moleque que vai trabalhar nessas duas áreas... mas a formação ainda não dá dinheiro pra gente, nesse momento. Então, a gente continua dando aula gratuita presencial... e a nossa plataforma tinha que ser tudo de graça, por isso a gente falou "pô, vamos fazer no Catarse"

[quote]
LO:  os intermediadores nesse processo ficam com uma porcentagem muito grande... ou então, no caso duma editora, o autor vai ganhar 10% e a editora 90%. Então o que o cara vê no Catarse é uma possibilidade de se conectar diretamente com os fãs dele, porque, no fundo, a editora vai estar vendendo exatamente pras mesmas pessoas, está vendendo pros fãs daquele autor. […] falar com essa pessoa. No caso da lei Rouanet, também, que os gatekeepers desse negócio aí são as grandes empresas […] fica muito na mão de grandes empresas, que vão apoiar projetos de grandes estrelas, entendeu, de gente que tem um capital social muito alto, assim, o Tony Ramos, o filho da não sei quem e não sei quem... então também fica difícil, entendeu, de ele... de conseguir isso. Muita gente  

'''

[quote]
RES: And it is… it is quite commercial so therefore there will be a… there will be a natural kind of, um, there will be some wastage when people come together I think. I don’t… I get the feeling that… that the control won’t be… I don’t think you’d get that with a new role quite frankly because I think the regulations make it too… it… it has to be if not super local, at least national because of… because of the, you know, the legals around financial things like that so I think that will… but I think there’s no doubt that crowd funding platforms have to be, um, it’s all about reach and that’s why Kick Starter is the… is the gorilla in the field because they’ve got the reach. Indigo does quite a good job. Um, err, and I think some of, you know, the Crowd Queue, you know, Crowd Queues receivers have built up some of them now so I think that… I think that’s good but I think the real challenge is… is, um, and Buzzbank for instance when we started working for Buzzbank, they were new and it was hopeless because the technology is… is nothing in the Crowd funding. It’s all about marketing and reach. They were new and we… we were struggling to get people to raise 3 or 4 grand because they didn’t have a [unclear – 17.54], they didn’t have a presence. They didn’t have a presence. So I think it’s, um, but I think the real dangers are that… that you… it’s this kind of a dragons den syndrome where everybody thinks they’re an entrepreneur… Everybody thinks they’re, um, they’re an investor which is good, which is clearly what produces the volume, the critical mass but there’s… have you ever tried… have you tried to get any… any… any stats out of any crowd funding platforms?
— SR

[quote]
“É só o que importa... porque é isso, autonomia é política  sujeito mais autônomo... e crítico, porque essas também são palavras que andam... você não pode ser autônomo sem ser crítico... (incompreensível) você tá dependendo” — Pedro

[quote]
Porque, se não tem diretamente a ver com política... porque aí tem outra coisa, que o Ônibus Hacker me ensinou, é que a compreensão do que é você fazer política é muito mais expandida do que... a gente, por exemplo, eu comecei a fazer (incompreensível). E eu defendo (incompreensível) porque ele quer vir com autonomia, e tudo o que tem a ver com autonomia, na verdade, é um instrumento político, de politização do indivíduo, saca? (incompreensível)
— Pedro

== References

[references]
* Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.
