= Autonomy
Eduardo Gonçalves
:revremark: Draft of chapter to the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy.
:revdate: August 2016
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

// Describe the way they define and pursue autonomy, as they dismiss external judgement in general (specially from incumbent institutions) they are not afraid to assume their own subjective judgements about the world and about their own choices; yet, by assuming this subjectivity, they usually dismiss the idea of _changing the world_ as they would like to make room for everybody to be autonomous (specially when it comes to being independent from any incumbent institutions).

[.lead]
Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men (sic) were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live (Arendt 1973:8).

The last chapter's discussion on money is one element of a complex mélange that defines a specific world view widely adopted by the crowd funding community. Another element of this mélage is to understand what is at stake when they purportedly adopt an alternative and marginal lifestyle — especially when it comes to the notion of making a living out of a career. Maybe a first impression about people who are trying to resignify money would point towards an utopia, a desire to change the world. And in fact that was what Felipe told me:

[quote]
[The degree in] geography gave me incredible tools to work with sustainability. And then, when I was 20, 22 years old, I was totally addicted to working and changing the world. And I'd work as hard as possible, for free, out of passion.

Before going to his partially crowd funded master degree, he had been an undergraduate student in two different fields: economics and geography. He opted for these courses because he felt the world was sick and needed to be saved: he would claim natural resources were disappearing, escalating levels of pollution were condemning the environment, and people were deeply deluded and exhausted in their obsession of working and making a living. The result, yet according to him, was a toxic world with serious personal and social issues. This situation was unbearable for him and thus he thought something had to be done.

When he was starting his higher education Felipe went for economics because, as he put, “it would provide me with knowledge about the system, about social life, and later I could get into ecology, ecological economics, green economy.” The _system_ is a way many interviewees would use to address the overarching values fostered by the incumbent institutions,  such as corporative market and the arguably states. After a couple of years Felipe changed his mind: “I had taken a too long diversion to actually get to the point where I could study sustainability, study labor, cultural and social alternatives.” He started to look for alternatives and geography looked good: “according to the programme you would study natural sciences, social science, humanities and the correlation between them.” He then changed from economics to geography trying to do something to save the world — or, at least, trying to prepare himself to do so.

With this background it is comprehensible that he graduated ready to pursue arguably overarching objectives: he was aiming at changing the world, at changing the system. Later, at the time of the interview, Felipe himself would label these objectives as naïve:

[quote]
I have worked for NGOs, it is a little bit of my trajectory. And there are other things. I have worked in the marketplace for big companies, such as Petrobras which is a semi-public corporation. And I have worked for small initiatives. And I started to see that I did not believe that we would change the system form inside out. […] Actually I do not think it is about changing the system. I think it is all about bringing an alternative, from outside — that is why my blog is called _On the Edge_, it is a culture living in the margins, it faces the real and the anew, what is not there yet.

His master degree focused on the collaborative economy. According to him this route seemed promising because “it moves away from the default of changing the system.” Specifically he claims that this route does not take a combative position against the system (or, at least, against the monetary system, as he mentioned in the interview): “let's leave the monetary system there, let it go. It will change if it has to.” Yet he thinks it is a waste of time to fight the monetary system, it is like “throwing small stones against a big wall.”

Interestingly his position does not imply that he had abandoned the idea of doing something to make the world a better place. It means he had scaled down his actions, keeping his ambitions as high as they were before. Once he realized he will not change the system from inside out, he adopted a new strategy that focus on small actions, on possibilities within his reach. It is not about solving the problem for everybody, it is not a revolutionary take on the world. It dismisses the global and outward expectation of _changing the world_ and replace it with a local and inward version of it.

Engage is the start up from Brazil that worked with the motto _power to the people_. One of their co-founders summarized this process described by Felipe in a few words (as this co-founder has himself went through a similar change in terms of life objectives):

[quote]
Engage was built with that ‘change the world’ idea in mind. And my history with Engage was all about getting tired of this chip chatting. But I do believe we are changing the world. I do not consider myself a dreamer. I am a very pragmatic guy that at the same time dreams a lot — otherwise I would not be able to be pragmatic.

Life stories like that raise important topics for discussion, topics that clearly take the process of resignification of money to another level — to be more precise topics that imbue this resignifcation with some purpose. Governments and corporations can act as constrains to actions and thus the strategy is to minimize the relevance of these institutions within the crowd funding communities lifestyle — namely what they are pursuing is autonomy. Surely the approach to autonomy discussed here emerged from the fieldwork and the idea is not to measure, corroborate or deny how autonomous my informants really are. What is relevant is to understand what they see as autonomy, how they pursue it, why they do it, and how this relates to the social and political framing of their choices. The first section of this chapter looks into the problematic escaping strategies towards autonomy, a series of tensions in the struggle to reject certain institutions and, at the same time, recurring to another institutions. This part investigates why they perceive change from inside out more feasible in some institutions and less feasible in others. The second part takes into account more radical attempts that instead of trusting in other existing institutions try to forge a non-institutional alternative. Interestingly in both cases they distance themselves from incumbent institutions without confrontation, and by their choices they end up building a new set of values that minimize the importance of these institutions. Ad this is the core of their pursue for autonomy — not only for themselves, but for all the peers taking part in this endeavour.

== Avoiding the shadows of institutions

… 

== Avoiding the need for institutions

… 

'''

== Organize this bits according to the new structure

=== Power is arranged locally

Noah is a graduate student in political theory from the USA. Throughout his life he has been involved with civic actions and he has also contributed to some crowd funding campaigns. He told me about one of the case he has been involved, one in which his group was very close to the city council:

[quote]
The city runs the airport and they [city council] decided they were going to renegotiate the contract for the food in the airport. They didn't want to have corporate restaurants, they wanted to reach out all those very famous local restaurants and “say would you like a branch in the airport?” […] The point I'm trying to make is that I'm always focused on building power at the local level — in the face of structures that are configuring the relations, social relations in a much larger scale, [for example] the international trade treaties and the national immigration policy. […] We were coming up with local ways to resist the above and sort of asserting local power in the face of this larger structure. That was my experience as an activist.

[quote]
I didn’t want to erm kind of play the rules of the system just to get a very alternative education institution I just found I like this, this is ridiculous and even if I could get a loan from the bank would I really want a loan off the bank to go and study alternative you know education, like new economy and this is ridiculous.
— Maria

[quote]
they’re using other people’s money so we understand but on the other hand, the state that the economy’s in everywhere and these people, you know, there’s a big opportunity for people to become entrepreneurs which I think is slightly overplayed but nevertheless I think being self employed for increasingly a greater proportion of the population is the only option. The jobs are, you know, no-one… there’s no jobs being created in the last 5 years. […] Maybe we all feel slightly better off because things are not quite as bad as they were but actually there’s no real jobs created so… so I think on the self employment and entrepreneurship is… is the way forward and therefore having people get access to money, the bank’s don’t do it so, err, crowd funding is quite interesting for that. And it has, as you see and as I’ve said, it has some very inherent faults I think.
— Stefen 

[quote]
A: E a coisa da empresa, e aí... que é daonde a gente vem e tira o dinheiro, e tal... que o problema é que a empresa sempre quer botar o bedelho... ela quer customizar. Então, se você busca uma independência de projeto, assim, bicho, sabe aquela coisa de jornalismo, "bota só a marquinha e não interfere no conteúdo editorial?". É difícil...

[quote]
Então, enchi o saco dessa coisa... bababá mudar o mundo, mas... por exemplo, assim, ó: por que que o Unlock é tão importante pra mim - tirando as coisas que eu acho legal nele, em si? Porque eu sonho - e aí, palavra vem bem - em não precisar tem preço pras coisas... em não precisar criar serviços só por criar serviços... só pra resolver a questão financeira, né... então... isso reflete, em mim, uma vontade de que outras pessoas façam isso também... por: 1) mudar a vida dessas pessoas, assim como eu sinto que vai mudando a minha aos poucos... o fato de eu olhar e ver que eu tenho... eu e o Larusso temos 750 pila garantido aqui com o Unlock... do Unlock... já me dá uma segurança diferente do que a que me dava quando era... 200, sabe... quando não existia isso, né? Ou seja, cada lucrinho a mais que eu vou tendo por mês, porque eu tenho cinco unlocks, né, eu somo eles e vejo mais ou menos quanto eu já tenho garantido pro mês, assim... enquanto durar, né... porque as pessoas...
— DW


=== Hands on culture, makers culture, hacker culture

DW & Unlock from conference paper

SR not a bullshitter

[quote]
DW: quando fiz o Mailee por exemplo, quando me envolvi junto com os guris pra fazer o Mailee, foi, tipo assim... bah, ganhar muito dinheiro com isso pra ter dinheiro sobrando e poder fazer as coisas bacanas... essa era a visão. Quando eu conheci o crowdfunding, eu comecei a pensar que isso era desnecessário, que eu só precisava viabilizar as coisas em si... mas, a real é que eu nunca botei um projeto no Catarse...

[quote]
P: eu trabalho muito com o imperativo do fazer, né... cê pode ficar discutindo muito, mas isso é pra quem tem tempo...

[quote]
P: um estatuto... eu voltei um pouco atrás na história... a gente começou a desenhar o estatuto, e quando a gente começou a desenhar o estatuto, a gente viu que ia ser impossível criar uma organização, porque a gente não concordava com um texto em comum... a gente tinha princípios e nortes... se gostava e se encontrava pra cozinhar e tal, mas... pra montar uma organização que tivesse um texto duro, um estatuto social dizendo o que a gente ia fazer, um queria fazer jornalismo, o outro queria fazer fotografia... e aí... foda-se, sabe, não precisa ter isso, sabe? Cada um faz o seu, e, ao invés da gente ter a associação, a organização, a ONG, a gente vai ter um espaço onde cada um faz o seu e todo mundo faz junto. 

=== Make money to work instead of working for money

[quote]
Então, enchi o saco dessa coisa... bababá mudar o mundo, mas... por exemplo, assim, ó: por que que o Unlock é tão importante pra mim - tirando as coisas que eu acho legal nele, em si? Porque eu sonho - e aí, palavra vem bem - em não precisar tem preço pras coisas... em não precisar criar serviços só por criar serviços... só pra resolver a questão financeira, né... então... isso reflete, em mim, uma vontade de que outras pessoas façam isso também... por: 1) mudar a vida dessas pessoas, assim como eu sinto que vai mudando a minha aos poucos... o fato de eu olhar e ver que eu tenho... eu e o Larusso temos 750 pila garantido aqui com o Unlock... do Unlock... já me dá uma segurança diferente do que a que me dava quando era... 200, sabe... quando não existia isso, né? Ou seja, cada lucrinho a mais que eu vou tendo por mês, porque eu tenho cinco unlocks, né, eu somo eles e vejo mais ou menos quanto eu já tenho garantido pro mês, assim... enquanto durar, né... porque as pessoas...
— DW

[quote]
DW:  Sou músico, né, e lá por 2008 eu interrompi minha carreira de músico porque eu tava exausto e especialmente exausto dum desequilíbrio muito grande entre a energia que tu coloca e o que tu recebe em troca, né... e eu decidi que eu ia aprender a fazer... na época, era marketing, a palavra que eu usava... pra, quando voltar, se voltar, voltar fazendo direito, né, fazendo duma forma que eu não fosse me esgotar como eu me esgotei. Aí eu passei uns dois anos mais startupeiros […] buscando todo tipo de escala que uma startup busca... só que no meio tempo eu comecei a dançar tango, bem nesses anos iniciais aí, […] quando começaram a surgir os projetos de tango na minha cabeça - as vontades de fazer coisas de tango -, eu sabia que eu não queria fazer algo onde eu investia um monte pra depois descobrir se tinha público e aí uma das ideias que eu tive foi, por exemplo, fazer uma milonga onde as pessoas pagassem antecipado, mas se não tivesse o mínimo de pessoas, não rolava a milonga. […] e nesse processo eu conheci o Kickstarter... aí eu disse "bah, cara, tudo... absolutamente tudo o que eu queria... todos os meus problemas acabaram" […]

[quote]
LO: acontecer... você vê... de fato a gente conseguiu a abrir uma via alternativa, né, a todo financiamento... ao modelo de financiamento que existe hoje no Brasil, né... o financiamento público, financiamento privado dos bancos... se começou a ver projeto sendo realizado, coisas, cara... o mundo se abriu … […] assim... e de fato não existia, cara: não existia uma maneira de você fazer projeto aqui no Brasil, de organizar projeto pequeno..

[quote]
A: (incompreensível) autonomia do aluno... ele me libera pra ser mãe da minha filha, porque senão cê fica cheio de filho pelo mundo.. […] Enfim, então a autonomia do aluno é isso... você pode ser mais responsável por você mesma, quando o outro tem autonomia.

[quote]
A: A: Não, a gente entendeu que não era na ONG porque eles não queriam remunerar os meninos... então, a gente, "pô, a gente tem que criar um negócio que a gente consiga remunerar", né, ter essa autonomia de... de fazer o que a gente acredita, porque pra engajar o moleque tem que ser legal e tem que dar dinheiro pra ele... porque ele tá num momento... senão ele tem que trampar pra ganhar dinheiro e ele não percebe que ele quer trampar com aquilo que ele quer...

[quote]
A: A: A gente... os meninos não tão na escola, né, eles evadem muito no Ensino Médio... e a gente falou, "pô, cadê os moleques?", "tão na internet", "como eles aprendem?", "tutorial no Youtube"... de matemática a maquiagem... e aí a gente ficou seis meses pensando em linguagem e rherherherherhé pra lançar um módulo de videoaulas. Aí lançamos ano passado e botamos no ar... arrumamos uma produtora parceira, que fez com a gente na raça, sem grana e tal... e botamos no ar pra ver. E a gente conseguiu três mil alunos. Aí a gente falou "não, bicho, tem uma coisa aí... tem uma demanda aí, então vamos fazer". E aí, como que nós vamos fazer? Não temos dinheiro pra fazer. E aí vem a história do Catarse. É uma coisa que é... pra todo mundo, né... a gente... qualquer um pode acessar... videoaula tem que ser de graça, porque é pra jovem do Ensino Médio, um pouquinho depois – eles têm muma dificuldade com essa coisa de grana pronta... então tinha que ser de graça. E daí como é que a gente ia financiar? Onde a gente ganha dinheiro? Produzindo conteúdo e fazendo pesquisa jovem... São as duas únicas formas da E.nos ganhar dinheiro. O que não pode faltar na E.nos? Formação. Que senão não tem moleque que vai trabalhar nessas duas áreas... mas a formação ainda não dá dinheiro pra gente, nesse momento. Então, a gente continua dando aula gratuita presencial... e a nossa plataforma tinha que ser tudo de graça, por isso a gente falou "pô, vamos fazer no Catarse"

[quote]
LO:  os intermediadores nesse processo ficam com uma porcentagem muito grande... ou então, no caso duma editora, o autor vai ganhar 10% e a editora 90%. Então o que o cara vê no Catarse é uma possibilidade de se conectar diretamente com os fãs dele, porque, no fundo, a editora vai estar vendendo exatamente pras mesmas pessoas, está vendendo pros fãs daquele autor. […] falar com essa pessoa. No caso da lei Rouanet, também, que os gatekeepers desse negócio aí são as grandes empresas […] fica muito na mão de grandes empresas, que vão apoiar projetos de grandes estrelas, entendeu, de gente que tem um capital social muito alto, assim, o Tony Ramos, o filho da não sei quem e não sei quem... então também fica difícil, entendeu, de ele... de conseguir isso. Muita gente  

=== Downplaying incumbent institutions

[quote]
A: A gente entendeu que o jornalismo era, na verdade, uma ferramenta incrível... né, de transformação de mundo, mas não ao exercer o jornalismo, mas ao ensinar jornalismo para que outras pessoas pudessem olhar pras suas comunidades e descobrir coisas... ainda mais aqui a coisa é tão... tão concentrada, a mídia é tão concentrada, tipo você abrir essa caixinha de Pandora e mostrar como faz... podia ajudar a galera a entender melhor o próprio lugar de onde vinha.

==== Do not depend on the job market

[quote]
RES: And it is… it is quite commercial so therefore there will be a… there will be a natural kind of, um, there will be some wastage when people come together I think. I don’t… I get the feeling that… that the control won’t be… I don’t think you’d get that with a new role quite frankly because I think the regulations make it too… it… it has to be if not super local, at least national because of… because of the, you know, the legals around financial things like that so I think that will… but I think there’s no doubt that crowd funding platforms have to be, um, it’s all about reach and that’s why Kick Starter is the… is the gorilla in the field because they’ve got the reach. Indigo does quite a good job. Um, err, and I think some of, you know, the Crowd Queue, you know, Crowd Queues receivers have built up some of them now so I think that… I think that’s good but I think the real challenge is… is, um, and Buzzbank for instance when we started working for Buzzbank, they were new and it was hopeless because the technology is… is nothing in the Crowd funding. It’s all about marketing and reach. They were new and we… we were struggling to get people to raise 3 or 4 grand because they didn’t have a [unclear – 17.54], they didn’t have a presence. They didn’t have a presence. So I think it’s, um, but I think the real dangers are that… that you… it’s this kind of a dragons den syndrome where everybody thinks they’re an entrepreneur… Everybody thinks they’re, um, they’re an investor which is good, which is clearly what produces the volume, the critical mass but there’s… have you ever tried… have you tried to get any… any… any stats out of any crowd funding platforms?
— SR

==== The job market is uninteresting

[quote]
At least if you can be passionate about it, there's… there's clearly a use for that and I think that… that also helps around… that also is another reason for the social community, it also tends to be, you know, a more personal look for people sometimes. So that can help but yeah, I think it's… listen the reality is as I said there aren't jobs, as simple as that…
— SR


[quote]
Se for ver o que eu recebi até agora da Little Big Money, a maioria deve ter sido consultoria, ainda... porque eles tavam aprendendo a fazer negócio online... eles são da fundação... Fundación Capital, que é uma fundação financiada pela Fundação Ford. E eles são muito durangos na coisa de internet, então eu e o Tomás passamos um bom tempo ali plantando sementinhas de... desde linha startup até filosofia de compartilhar as coisas e não criar barreiras, uma série de coisas nesse sentido que têm a ver com uma visão de mundo diferente da que eles tão acostumados, né... +
— DW

'''

[quote]
“É só o que importa... porque é isso, autonomia é política  sujeito mais autônomo... e crítico, porque essas também são palavras que andam... você não pode ser autônomo sem ser crítico... (incompreensível) você tá dependendo” — Pedro

[quote]
Porque, se não tem diretamente a ver com política... porque aí tem outra coisa, que o Ônibus Hacker me ensinou, é que a compreensão do que é você fazer política é muito mais expandida do que... a gente, por exemplo, eu comecei a fazer (incompreensível). E eu defendo (incompreensível) porque ele quer vir com autonomia, e tudo o que tem a ver com autonomia, na verdade, é um instrumento político, de politização do indivíduo, saca? (incompreensível)
— Pedro

'''
 
== References

[references]
* Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.
