= Autonomy
Eduardo Gonçalves
:revremark: Draft of chapter to the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy.
:revdate: March 2017
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men (sic) were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live (Arendt 1973:8).

The last chapter's discussion on money is one element of a complex mélange that defines a specific world view widely adopted by the crowd funding community. Another element of this mélage is the understanding of what is at stake when they purportedly adopt an alternative and marginal lifestyle — especially when it comes to the notion of making a living out of a career. Maybe a first impression about people who are trying to resignify money would point towards an utopia, a desire to change the world. And in fact that was what Felipe told me:

[quote]
[The bachelor degree in] geography gave me incredible tools to work with sustainability. And then, when I was 20, 22 years old I was totally addicted to working and changing the world. And I'd work as hard as possible, for free, out of passion.

Before starting his partially crowd funded master degree he had been an undergraduate student in two different fields: economics and geography. He opted for these courses because he felt the world was sick and needed to be saved: he would claim natural resources were disappearing, escalating levels of pollution were condemning the environment, and people were deeply deluded and exhausted in their obsession for work and making a living. The result, yet according to him, was a toxic world with serious personal and social issues. This situation was unbearable for him and thus he thought something had to be done.

When he was starting his higher education Felipe went for economics because, as he put, “it would provide me with knowledge about the system, about social life, and later I could get into ecology, ecological economics, green economy.” The _system_ is a way many interviewees would use to address the overarching values fostered by the incumbent institutions,  such as corporative market and the national states. After a couple of years Felipe changed his mind: “I had taken a too long diversion to actually get to the point where I could study sustainability, study labor, cultural and social alternatives.” He started to look for alternatives and geography seemed like a good idea: “according to the programme I would study natural sciences, social science, humanities and the correlation between them.” He then changed from economics to geography trying to do something to save the world — or, at least, trying to prepare himself to do so.

From this background it is comprehensible that when he graduated he was up to pursue arguably overarching objectives: he was aiming at changing the world, at changing the system. Later, at the time of the interview, Felipe himself would label these objectives as naïve:

[quote]
I have worked for NGOs, it is a little bit of my trajectory. And there are other things. I have worked in the market for big companies such as Petrobras which is a semi-public corporation. And I have worked for small initiatives. And I started to see that I did not believe in the idea that we would change the system form inside out. […] Actually I do not think it is about changing the system. I think it is all about bringing an alternative, from the outside — that is why my blog is called _On the Edge_, it is a culture living in the margins, it flirts with the real and the anew, what is not there yet.

His master degree focused on the collaborative economy. According to him this route seemed promising because “it moves away from the default of changing the system.” Specifically he claims that this route does not take a combative position against the system (or, at least, against the monetary system, as he mentioned in the interview): “let's leave the monetary system there, let it go. It will change if it has to.” Yet he thinks it is a waste of time to fight the monetary system, it is like “throwing small stones against a big wall.”

Interestingly his position does not imply that he had abandoned the idea of doing something to make the world a better place. It means he had scaled down his actions, keeping his ambitions as high as they were before. Once he realized he will not change the system from inside out, he adopted a new strategy that focus on small actions, on possibilities within his reach. It is not about solving the problem for everybody, it is not a revolutionary take on the world. It dismisses the global and outward expectation of _changing the world_ and replace it with a local and inward version of it.

Engage was one startup from Brazil that used to work under the motto _power to the people_. One of their co-founders summarized this process described by Felipe in a few words (as this co-founder has himself went through a similar change in terms of life objectives):

[quote]
Engage was built with that ‘change the world’ idea in mind. And my history with Engage was all about getting tired of this chip chatting. But I do believe we are changing the world. I do not consider myself a dreamer. I am a very pragmatic guy who, at the same time, dreams a lot — otherwise I would not be able to be pragmatic.

Life stories like that raise important topics for discussion, topics that clearly take the process of resignification of money to another level — to be more precise topics that justifies this resignifcation with some purpose. Governments and corporations can act as constrains to actions and thus the strategy is to minimize the relevance of these institutions within the crowd funding communities lifestyle — namely what they are pursuing is autonomy. Surely the approach to autonomy discussed here emerged from the fieldwork and the idea is not to measure, corroborate or deny how autonomous my informants really are. What is relevant is to understand what they see as autonomy, how they pursue it, why they do it, and how this relates to the social and political framing of their choices. 

As this chapter describes, there are similarities and differences in terms of the rejection of corporations and government. Although it is common to see the disavowal for both coming together, from times to times one of them, the corporation, is seen as an alternative to the boundaries of the other: even when not completely discarded, the government is hardly ever seen as efficient in terms of granting the autonomy crowd funding community is looking for. On that point it is interesting to see what is the expected role of institutions: on the one hand it really seems states in general is loosing its appeal as an authority (for example, as in Wolin 2004); but on the other hand, if people are free to explore new economic arrangements and new social relationships (as in crowd funding) some institution might be responsible for the freedom empowering these novelties.

To be clear the question raised in the last paragraph relates to Berlin's (1999) _positive_ and _negative_ freedom — or in other words _freedom for_ and _freedom from_. While the later refers to situations in which there is an absence of interference in one's actions, the first one emphasize the deciding power (over the possibility of being decided for). In that context it is worth it to explore the following discussion on autonomy within the crowd funding community having in mind some recent institutional transformations that are crucial to comprehend how my interviewees position themselves in relation to the institutions they seem to reject. For instance Wolin (2004:588) suggests that :

[quote]
The changes in capitalism have weakened the authority of the state as the supreme power in society. Globalization is the euphemism for continuous expansion abroad and the constriction of politics at home, narrowing the points of entry so that only the pressure of money can gain political access […] Although the state continues to play a far form negligible role in an increasingly globalized economy, the power wielded by multinational corporations has made their cooperation and acquiescence indispensable. The cooperation of corporate power is now a vital element of domestic, foreign and military politics. Competition and rivalry occur less between state and corporations and more between corporations vying for influence over the state or subsides from it.

In this scenario what used to be seen as traditional roles expected form government started to be played by corporations when they started to provide not only their employees with social benefits — for example funding cultural and educational initiatives. But at the same time arguably money is replacing citizenry as the core of the quality measurement of the success or failures of national and regional democracies: "state actors have become dependent more on corporate power than on their own citizens" (Wolin 2004:589).

Finally Wolin (2004:586) suggests to opposing political tendencies to deal with this situatoin: a centrifugal that “fears democracy because it homogenizes suppressing significant differences in favor of a monolithic ideal of ‘the people’” and a centripetal which “is contemptuous of democracy for its weakness yet envious of its appeal.” Maybe the way my interviewees downplay government is  signal that they are closer to this last tendency — tendency that Wolin belives is the least promising for democracy.footnote:[“Whatever remains of democratic possibilities lies with the centrifugal forces. Yet their political prospects are the more problematical. For despite their critical attitudes towards the state – perhaps all – of the major centrifugal groups look to government for assistance and protection and to its courts for relief. This requires some accommodation to the political culture that surrounds the national government and many state governments, and that, increasingly, has become indistinguishable from corporate culture” (Wolin 2004:587).]. In order to offer some basis to this debate this chapter looks into the problematic escaping strategies towards autonomy, a series of tensions in the struggle to reject certain institutions while, at the same time, the same social actors are actually recurring to other institutions. The first part of the chapter focuses on a more optimistic branch: people from whom corporations and governments are problematic but they still act in the sense of trying to change that. The second part is based on more radical accounts in which the rejection is so bold that they usually try to opt-out of the power of these incumbent institutions. Interestingly in both cases they distance themselves from the institutions without confrontation, and from their choices they end up building a new set of values that, for them, minimizes the importance of these institutions. This is the core of their pursue for autonomy — not only for themselves, but for all the peers taking part in this endeavour.

== Hacking incumbent institutions

Autonomy is a major driver to my interviewees' choices and this specific criterion leads them to perceive institutions as obstacles in fulfilling their life expectations. Surely not all institutions are barriers and a lot of judgement takes place in their strategies to position themselves into the world, to pursue their ideal of autonomy. Their movements accepting or denying certain institutions tell a lot about what they understand as autonomy. Felipe's case, for instance, points towards the problems of trying to promote change from inside out, but a lot of other interviewees believe that institutional arrangements can help them in the arduous task of making a difference in such a sick world. Carla, for instance, started a promising career in the advertisement market, but at a certain point she started to have similar thoughts as Felipe:

[quote]
I hold a degree in advertisement, I worked for 10 years in advertisement agencies with planning and research. Then a couple of years ago I started to realize that all my investment in terms of time, of daily efforts, of commuting, and of focus on the projects I'd run, all that was kind of useless. I worked in an agency and I was part of a process that would end up to a banner in the end of the day. It was a communication piece that would only feed this Machiavellian system.

Carla was pondering not merely about her dissatisfaction with her job. Her reflections target two very specific things: on the one hand the purpose of the market she was contributing to and, on the other hand, what was painful in this process was not only that this market was going somewhere she would not approve, but that in the way she was investing all her most personal values: her efforts, her time, her focus and so on. Furthermore she told me: “I felt there was something missing, I could be contributing through other ways to project development, to innovation… to innovate with positive impact.” Her strategy to go to the margins, to the edge of a well stablish market was to specialize in design for social impact (she now holds a master degree in such field) and to try to engage with projects more focused on the city, on urban spaces close to her. Now she works in the strategic innovation market having experience at consultancies focused on positive impacts on society. Other interviewees also opted for working for this kind of companies: usually they are small to middle size offices, they hold multinationals such as Coca-Cola, Nestlé and Petrobras in their portfolio, but at the same time they value and develop projects for NGOs, civic activism and for the public sector. From times to times this small companies also have their own projects, that might become spin offs — that was the case of Catarse, for example.

Brittany is an American woman and in the interview she mentioned the choices she felt that were available for her after graduating:

[quote]
It's interesting to be able to create projects instead of just typing on a keyboard, and those were the kind of job opportunities I had: doing more office work for any organizations that were not particularly exciting as well. At that time too it was so competitive that I think I would have ended up having to be more focused on something with a better paycheck and not necessarily a job that is fun.

In other other she felt that all the traditional job opportunities were uninteresting, bureaucratic and limiting her creative and her “hands on” impulse. She is very concerned about the natural resources, climate change and the environment in general. But at the same time she did not wanted to work neither for the government nor for NGOs: “I don't have anything against the government, but I'm just more personally interested in private industry.” Therefore she moved abroad and started to work for a private park and nature reserve where she could start to manage projects instead of doing office and paper work. Her choice for a private environment was on purpose:

[quote]
I consider myself an eco-capitalist. I've never really imagined myself working for the government or NGOs. I am more interested in doing change through the private industry. Private industry is not restrained by borders as long as you have the right market incentives.

She believes that there is a higher chance of promoting substantial changes in the world from a private institution, with no borders — but she reinforces that the right incentives should be set by the public sector. Still she believes that federal government might be too big to understand her reality and to do the right moves:

[quote]
There is so many stupidity sometimes, because you have to deal with someone who will deliberate on an environmental project and they are 300 kilometers away, and they have no idea about what your reality is actually like. I do not think this is the most effective to do environmental policy. That is why it is nice to work on a private reserve because we have a relationship with the [local] public government, we are bordering a state park. I have a bit more liberty. We work a lot with the people from here. We do not have to deal with people who have never been in the area and do not know anything about it.

In different degrees what Carla and Brittany are claiming is that they want to be able to choose what kind of projects and action they enable in their everyday life. And yet this claim is sustained by a world view that consider governments and corporations too big to feel what individuals really face in their daily routines. If Brittany example is more clear (she even mentioned the _think global, act local_ motto during the interview), Carla's one might need further discussion: in spite of the multinational clients all the projects and deeds she mention in the interview are related to the urban space and civic activism projects she has been involved with. The consultancy she works for might not be exclusively focused on this kind of projects but she considers that since there is room for them, it makes the job more attractive than the other ones she had had in the past.

These two women are somehow recurring to the private sphere because they believe society needs change — namely one of them would say it needs some positive impact, the other would say it is compromised due to climate change and other eminent environmental catastrophes. Underneath these arguments lies the responsibility the state bear in such scenario. For Brittany, part of the problem is the distance between the spheres of the government in charge, and the reality of the governed people. Carla has not been explicit in supporting this view but her actions seems to corroborate it. During the interview she was listing some causes for the lack of social impact in many projects and she ended up saying that “it cannot be a single NGO, it is not Greenpeace that is going to sort that out, it is not the UN alone that is going to do it. It really has to be something massive.” At first this was intriguing: Greenpeace and UN are massive institutions after all. She explained it next:

[quote]
I think it [the solution] should be decentralized. That is part of Box's Brazilian Dream Project, the idea of microrevolutions, but the thing is that companies should also be decentralized. Thus when I say “something big” it is something that belongs to the people, that is part of everyone's concerns. Therefore not only people, but companies need to have an active role for a better society.footnote:[Box 1824, mentioned by Carla as “Box” is Brazilian consultancy that built a great reputation publishing researches on Brazilian culture — most of them on Creative Commons licenses, free to read and watch on the internet. Those reports usually are shaped in short videos that easily become viral on the internet. Carla has freelanced for this consultancy.]

If this quote sounds too abstract or utopian, Carla offered as an example the case of public bikes in São Paulo. In a similar scheme to Barclay's bikes in London, they were structured through a private and public partnership, coincidentally backed by a nationwide bank too, the Brazilian bank Itaú:

[quote]
[Take the case of] Itaú's bikes: there are various issues that could be risen, a lot of questioning on whether it was more about marketing than about a proper solution [for public transportation]. But this was a social innovation to the city because it was considered within a mobility and civic movement […] People who were not using bicycles before are trying it now. Despite the [commercial] interests (because I do not believe they [Itaú] are just being nice, they are a bank) it is a social innovation.

Hence from Carla's point of view there is an important factor that is being close to people, to civic activism. Or in other words, being local — something that overarching federal governments and multinational corporations fail to achieve, as many of my informants would put it. In sum the problem does not relies on the private or public realm, but in the distance between individual and institution. To add another example, Noah is a graduate student in political theory also from the USA. Throughout his life he has been involved with civic activism and he has also contributed to some crowd funding campaigns. He told me about one of the projects he has been involved, one in which his group was very close to the city council:

[quote]
The objective of the organization I volunteered at was at the city level and we ended up getting a majority progressive city counsel. […] The city runs the airport and they decided that they were going to renegotiate the contracts for the food in the airport. They did not want to have corporate restaurants. They wanted to reach out to all very famous local businesses, restaurants and say “would you like a branch in the airport?” […] That was sort of one policy they want but the point I am trying to make is that I am always focused on building power at the local level, in the face of structures that are configuring the social relations at a larger scale. International trade treaties and national immigration policy [for example], these are all things that are sort of structural, but we were coming up with local ways to resist. Sort of asserting local power in the face of this larger structure.

The critique built by these people who at a certain point have recurred to crowd funding is not targeting explicitly the public or the private sphere, as Noah's example clarifies. They are at the same time targeting a specific world view that puts individuals as dependent of paternalist, of embracing government and corporations. In their nightmares they probably would be complaining that there are no jobs out there and that the government is not properly regulating corporations when it comes to the protection of the environment. But that is not what they are doing. Actually they have no intention of working for these corporations and many of them have no interest in voting for example. Most of my Brazilian interviewees (where voting is compulsory) have declined to vote in the past few years.

Stephen is a experienced British entrepreneur who mentor many social entrepreneurs. He points out that due to the economic crisis there are no jobs being created, therefore “being self employed for increasingly a greater proportion of the population is the only option.” In this scenario he sees crowd funding as a promising alternative since in many cases not even banks would fund certain entrepreneurs. But in opposition to most business men who praise the success of new companies such as Uber or Airbnb he is quite critical about them. Another example he mentioned in the interview was a British short term car rental:

[quote]
It started as Street Car which was a UK company, which is cool. Nice service, nice cars. It was bought by Zipcar which is an American company. The service went down a bit, the cars went a bit crappier. And it is now owned by Avis […] It is very hard because clearly it is having an impact. It does take a lot of cars off to the road. But on the other hand it is now part of a big corporation.  And it is working for shareholders rather than to the communities. And I think a lot of this stuff, for me, would be much more interesting if somehow you could keep it at a local level, a community level.  But you cannot do that […] The biggest obstacle is how you rethink money or if can you rethink money – and if you cannot then actually everything is all a bit meaningless because it all comes down to cash in the end.

Therefore if the critique does not target the public or the private in specific, it suggests that both spheres nowadays are driven by money. Corporations and government, my interviewees would claim, are distant from people's needs and reality because they are organized in a way that focus on making money and also on delivering money through a lifestyle based in an overarching policy that values jobs, wages and benefits. The problem is that the crowd funding communities are resignifying money, and consequentially they are not settling down for a comfortable job that offers them some financial stability. Their personal views on the world, on this system seems more important than the values being delivered and nurtured in most national states policies and in most corporate environments.

The stories mentioned above position the problem in the size of the organization: for them bigger institutions put the decision making progress away from their everyday lives. Therefore their strategy involves working in small scale institutions that enable three valuable things: conciliating personal values within their everyday life activities, being able to promote some actions with some impact, and avoiding bureaucratic and impersonal decision processes. The motto _think global, act local_ seems to have a perfect fit with this ambitions: the thinking part allow them to channel their dreams and aspiration to action; the acting part is taken locally, that is to say, is more feasible and easy to put forward than more ambitious projects that would require layers of deliberation. This deliberation if not handled at the personal level would be compromised, they would say: when people's opinion are framed into instrumentalized and racionalized institutional processes the only rule that matter is cash — and that is the kind of value that is not appealing to this specific community.

Hence action is of utmost importance for them. Their idea of autonomy is to be able to act, to put ideas forward, to experiment and learn from it. Carla herself is very clear on that point: she is not sure if Itaú's bike scheme is the best for São Paulo, she would not oppose a totally public nor a totally private initiative to compare them all later:

[quote]
It is very difficult to get it right the first time, thus we have to test, to hack, to experiment. I praise the initiatives with that mindset. And actually that is why I really like crowd funding. Crowd funding is a way to engage, to motivate, to show possible futures — that is what really matters.

All the quotes so far are somehow critical about corporations and governments: Carla had to cherry-pick in which consultancy to work for (and maybe with which clients to work with) because there is a discomfort with the kind of project most corporations invest on, for example. Brittany also cherry-picked, but she was harsher on the government side — characterized as inefficient (distant from the real everyday life of people) and limited (by national borders). Noah seems to disagree with bug players from the food industry and tries to minimize the impact these corporations have in his region by acting close to the government, to the city council. Stephen believes that the economic policies put forward by governments with the support of multinational corporations failed to provide jobs and stability to citizens, and even banks (a kind of corporation regulated to certain degree by governments) are failing in helping people to bootstrap their ideas. In spite of that these people are not so distant neither from governments nor from corporations: they try to hack them, to make these institutions working in a way that is more in tune with their aspirations. The next section discusses strategies to attempt a greater step, a kind of bypass in these incumbent institutions.

== From avoidance to autonomy

As the previous section described there is a clear and intentional will to find alternative ways of making a living within the crowd funding community, a way that would circumvent the corporative and public sectors. Even if this holds true to all of my interviewees there is a group within them that take this disavowal for these institutions further. At this point it worth it to go back to Stephen's consideration of the job market. In fact his argument follows some general trends: for example self-employment rates have been rising slightly in the UK since 2002 while unemployment rates increased by 50% in the same period (OECD 2013).footnote:[According to the OECD Factbook (2013) between 2002 and 2010 self-employment raised from 12.7% to 13.8% and the long-term unemployment rate raised from 21.7% to 33.4%. Stephen's interview was in 2014.] However the feeling that there are no jobs out there is not the only reason underneath the disavowal for these institutions. Sometimes there is also a perception that if they frame their professional activity in the form of a formal organization — whether it is a corporation or NGO — is not the best way for them to actually do what they are willing to do. Pedro told me about a time when he was one of the founders of a kind of hacker space in Brazil: 

[quote]
We were drafting a statute, a charter and then we realized that it would be impossible to start an organization because we could not agree on a common text. We had principles, we were heading to the same direction, we liked each other and we used to get together. But it would not work to frame an organization with a charter, a social statute saying what we would be doing. Some would like to do journalism, some were willing to do photography…  whatever, we do not need a statute, right? Instead of an organization, a NGO we ended up with a space where everybody could work on their own stuff together.

Contrasting with Stephen, Pedro do not actually expect that any institution will provide him the best framework for his, and his friends', professional affairs. In his opinion formalizing an organization would mean an onus without a bonus: they do not want to be limited by any regulation about what kind of professional activities they are supposed to run,footnote:[In Brazil there are regulations based on UN's International Standard Industrial Classification — as there are similar regulations in many other countries, as my interviewees reported. For them this means that when setting up an organization one must restrict the kind of projects one is going to execute — but, as some examples presented earlier, many of my interviewees have a very heterodox professional path, and they would like to act as technology consultants at the same time they teach dancing.] they do not want to pay taxes for opening an organization because they do not feel there is anything in return except boundaries. In sum they feel better acting by their own.

From Stephen and Pedro it is possible to grasp a tone in the disavowal for corporations, NGOs and the public sector that goes further in terms of skepticism: while many of the quotes from the previous represented life choices in terms of better or worst organizations to work with, there are cases in which the disbelief is so bold that actually pulls people to a kind of libertarian attitude. While Carla and Brittany are satisfied in the kind of project and institutional arrangement surrounding their professional activities, other interviews expressed a harsh opinion on the incumbent institutions discussed here. For Stephen, in _quasi_ non-existent job market, one probably would have little chance to be able to choose a job that has a good fit with one's life purposes. At the same time Pedro probably would see Brittany's choices as limiting because a lot of money, time and efforts are wasted in taxes and bureaucracy to keep the business open. Specially when it comes to the private market, Pedro highlighted:

[quote]
The problem is that companies will always meddle, you cannot do things your way. Thus if you want a project to be independent, there is no way [to work with corporations behind you]. Take the classic journalism example, the chitchat that just adding the logo to something would not interfere with the content. That's tough to believe in.

In such a scenario crowd funding thrives as an alternative, a way a bootstrap projects without ties to any corporative or governmental funding. Actually this is what Miguel, a co-founder of one of the biggest Brazilian crowd funding platforms, told me:

[quote]
Indeed we have opened an alternative model of funding in Brazil, an alternative to public funding, private funding, bank loans… And then we started to see projects flourishing, things happening. It opened a whole new world for people. […] And in fact this was something that did not existed before: back then there was no way to fund a project, a small project, here in Brazil.

This last part of this chapter explores how this avoidance of institutions is forged from a very similar idea of autonomy as discussed earlier. Autonomy might be clearer in Pedro's arguably idealistic quotes, but even from a more pragmatic tone autonomy is behind  Stephen's standpoint: one would not depend on corporations offering jobs to make a living. And more importantly: for some of them a kind of real autonomy is impossible within the current incumbent institutions.

Maria is a Romanian woman who partially funded her master degree through crowd funding. Amanda is a Brazilian entrepreneur who runs some open journalism schools, mainly in poor neighborhoods around big metropolis. At a certain point both of them faced the possibility, maybe even the need to partner with some of these institutions they disavowal. Maria was approved in a kind of her dream school, but she could not afford the tuition fees. Amanda was running a very successful communication project in one of the poorest areas of São Paulo, but she was not satisfied with the mindset of the NGO that was behind her. Both of them dismissed the most standard choices shown to them: Maria have not considered a bank loan, and Amanda actually considered leaving the NGO (what would mean the end of the project). Respectively, that is what they told me:

[quote]
I did not want to kind of play the rules of the system just to get to a very alternative education institution. This is ridiculous. And even if I could get a loan from the bank would I really want a loan off the bank to go and study alternative education, like new economy? This is ridiculous (Maria).

[quote]
We realized that it would not work with the NGO because the NGO declined to pay the boys. We were like “we have to start something that can afford to pay the boys, so they can be autonomous” — we ought to do that because that is what we believe in. We believe that it worth it to engage the boys if it is cool for them and if it pays them back. Otherwise they will look for a job from which they can make a living of and they would not realize that this is what they really would like to do (Amanda).

Those quotes might raise an interesting tension: one might see Maria's option as a subtle way to refuse money and its possible benefits while, on the other hand, Amanda's opinion would be the opposite — that is to say, an explicit movement in the sense of vouching money a protagonist role. Before getting into this discussion it worth it to highlight that both woman are actually pointing in the same direction when in comes to repealing the current mindset behind incumbent institutions. Maria does not want to get involved with banks (arguably corporations with strong ties to governmental affairs such as federal reserve and interest policies). Amanda does not believe that current alternative funding social impact projects are worth it: charity, government benefits and non-profit organizations are not actually causing impact because they do not provide autonomy. 

The _quasi_ paradoxical approach to money although can be analyzed throughly in order to clarify that even if they point in different directions two things are still common place for them: first of all, as discussed in the previous chapter money is mostly a social relationship and nor merely a amoral of exchange value; second at the core of their decision is a emphasis in how one can enjoy autonomy and base their own relationship with the world in an autonomous way. Let's get back to Maria's case as her story is not straightforward as Amanda's. Maria told me that after her bachelor degree she was working as a volunteer in some projects:

[quote]
I was a bit disillusioned seeing that when you are offering your services in terms of volunteering it is a fine line between being exploited and being helpful. I felt I was being exploited because I was not getting the learning […] but then I had very good exchanges. I think it just brings the idea of skills and exchange and how we measure that. Its very subjective from person to person to think about what each one thinks is fair to invest and give back in this exchange — and here money is not involved. It was an interesting question that was posed there.

From thoughts like that it is clear that Maria was already calling into question how problematic exchanges are. In her case how uncomfortable she felt trading her skills for money or for anything else. However the problem, as she told me, was not put on the exchange _per se_ but in the context. For instance, as a photographer and journalist crowd funding her tuition fees her first thought was to offer a big book with photos taken by herself and stories she would wrote about everyone who pledged in her campaign. That was too much work for a short deadline, so she took an even more personal route: “for example a photograph, or you would get one of my essays or my dissertation, a song, maybe a photography services if there was a big company” — that was what she went for. She was telling a story and sharing her experience with her supporters — and the exchange was a platform for that. In other words she felt she was moving away from a kind of pecuniary exchange that would me meaningless through a more personal or social lens. 

[quote]
I was trying to stay out of politics and economy, I just did not want to have anything to do with it in any way. It was kind of putting it all in a bad guys box and do not want to deal with it. I went through the other, alternative route, local villages and what is happening out there — that is not mainstream. I was very curious in seeing what is happening and what is the drive for these people to really go off the grid. Is this really possible? Because this sounded like utopia for me back then. So I just wanted to experience it myself and also I wanted to see if I could ever live or make my own alternative way of being.

At this point she uses a couple of keywords that led to the idea that there is a standard career path, a standard way to make a living that was not interesting for her. At the same time, as this is the _mainstream_, one have to be willing to decline to go with the flow and start to trace one's own path. For her the possibility of making this move is a gesture of autonomy. Thus when facing the tuition fees invoice, Maria opted for the riskier path: not asking for a loan but for friends, and friends of friends and so on. Not messing up with the “bad guys” was possible because this other way granted enough autonomy for her.

Getting back to Amanda's story, when she expanded this idea of autonomy regarding her “boys” — the guys that participated in the social and entrepreneurial activities she hosted — the context was a completely different one. Two main points must be highlighted here: they were poor in a very unequal country and they were teenagers. According to Amanda they were already dealing with a lot of social and peer pressure: maybe they were considering drop out of school to try to find a (probably unskilled) job and contribute to the family budget; maybe some of their friends were getting well of working close do drug dealers or other gangs around and they were considering this possibility; maybe they do not even considered journalism was for them at the first place.footnote:[As in Bourdieu's (1990) classical argument on reproduction.] In other words Amanda felt money was important for them to be autonomous and escape the kind of mainstream within their social context. Arguably if the project could support them with some money they would be more confident in considering communication as a career option — and with this confidence they can enjoy a higher degree of autonomy. Finally Amanda also belives that their autonomy has to do with her own autonomy: “their autonomy sets me free to be the mother of my daughter, otherwise I would end up full of other children to take care of — I only can look after myself if they are autonomous.”

This is a very common characteristic among my interviewees: their own purpose in life. Amanda loves her job, the projects she runs. But she loves being a mother and she sees those projects as a way to make it possible for her to be good mother. It is not about a world wide revolt against corporations, NGOs and governments, but the opposite: a set of choices based on micro inwards revolutions. A set that and the end of the day offer them the feeling they are more capable of being autonomous than they would be in a full time job, for example. A set that also empower them to get involved in different projects making a living of them. A set that connects these projects with their very personal ambitions in this life.

Another of my interviewees has co-founded a recurring crowd funding platform in Brazil in which he have five different projects. He was the person who coded the platform from the scratch, but most of the projects are related to his career as musician and as a tango dancer and teacher. However there is another project he hosts there: as the platform charges no fees at all it is supported by a crowd funding campaign within the platform itself.

[quote]
So I got tired of this chitchat about changing the world. Why is that platform so cherished? […] Because I dream of a world in which we do not put price on things, a world in which we do not create services just for the sake of creating it, just to put up with the financial situation. So all that has to do with a will that other people could do what I am doing. To change their life as I am changing mine, in baby steps. 

NOTE: Money to work (not work for money)

[quote]
DW: quando fiz o Mailee por exemplo, quando me envolvi junto com os guris pra fazer o Mailee, foi, tipo assim... bah, ganhar muito dinheiro com isso pra ter dinheiro sobrando e poder fazer as coisas bacanas... essa era a visão. Quando eu conheci o crowdfunding, eu comecei a pensar que isso era desnecessário, que eu só precisava viabilizar as coisas em si... mas, a real é que eu nunca botei um projeto no Catarse...

[quote]
P: eu trabalho muito com o imperativo do fazer, né... cê pode ficar discutindo muito, mas isso é pra quem tem tempo...

[quote]
A: A: A gente... os meninos não tão na escola, né, eles evadem muito no Ensino Médio... e a gente falou, "pô, cadê os moleques?", "tão na internet", "como eles aprendem?", "tutorial no Youtube"... de matemática a maquiagem... e aí a gente ficou seis meses pensando em linguagem e rherherherherhé pra lançar um módulo de videoaulas. Aí lançamos ano passado e botamos no ar... arrumamos uma produtora parceira, que fez com a gente na raça, sem grana e tal... e botamos no ar pra ver. E a gente conseguiu três mil alunos. Aí a gente falou "não, bicho, tem uma coisa aí... tem uma demanda aí, então vamos fazer". E aí, como que nós vamos fazer? Não temos dinheiro pra fazer. E aí vem a história do Catarse. É uma coisa que é... pra todo mundo, né... a gente... qualquer um pode acessar... videoaula tem que ser de graça, porque é pra jovem do Ensino Médio, um pouquinho depois – eles têm muma dificuldade com essa coisa de grana pronta... então tinha que ser de graça. E daí como é que a gente ia financiar? Onde a gente ganha dinheiro? Produzindo conteúdo e fazendo pesquisa jovem... São as duas únicas formas da E.nos ganhar dinheiro. O que não pode faltar na E.nos? Formação. Que senão não tem moleque que vai trabalhar nessas duas áreas... mas a formação ainda não dá dinheiro pra gente, nesse momento. Então, a gente continua dando aula gratuita presencial... e a nossa plataforma tinha que ser tudo de graça, por isso a gente falou "pô, vamos fazer no Catarse"

[quote]
LO:  os intermediadores nesse processo ficam com uma porcentagem muito grande... ou então, no caso duma editora, o autor vai ganhar 10% e a editora 90%. Então o que o cara vê no Catarse é uma possibilidade de se conectar diretamente com os fãs dele, porque, no fundo, a editora vai estar vendendo exatamente pras mesmas pessoas, está vendendo pros fãs daquele autor. […] falar com essa pessoa. No caso da lei Rouanet, também, que os gatekeepers desse negócio aí são as grandes empresas […] fica muito na mão de grandes empresas, que vão apoiar projetos de grandes estrelas, entendeu, de gente que tem um capital social muito alto, assim, o Tony Ramos, o filho da não sei quem e não sei quem... então também fica difícil, entendeu, de ele... de conseguir isso. Muita gente  

'''

[quote]
RES: And it is… it is quite commercial so therefore there will be a… there will be a natural kind of, um, there will be some wastage when people come together I think. I don’t… I get the feeling that… that the control won’t be… I don’t think you’d get that with a new role quite frankly because I think the regulations make it too… it… it has to be if not super local, at least national because of… because of the, you know, the legals around financial things like that so I think that will… but I think there’s no doubt that crowd funding platforms have to be, um, it’s all about reach and that’s why Kick Starter is the… is the gorilla in the field because they’ve got the reach. Indigo does quite a good job. Um, err, and I think some of, you know, the Crowd Queue, you know, Crowd Queues receivers have built up some of them now so I think that… I think that’s good but I think the real challenge is… is, um, and Buzzbank for instance when we started working for Buzzbank, they were new and it was hopeless because the technology is… is nothing in the Crowd funding. It’s all about marketing and reach. They were new and we… we were struggling to get people to raise 3 or 4 grand because they didn’t have a [unclear – 17.54], they didn’t have a presence. They didn’t have a presence. So I think it’s, um, but I think the real dangers are that… that you… it’s this kind of a dragons den syndrome where everybody thinks they’re an entrepreneur… Everybody thinks they’re, um, they’re an investor which is good, which is clearly what produces the volume, the critical mass but there’s… have you ever tried… have you tried to get any… any… any stats out of any crowd funding platforms?
— SR

[quote]
“É só o que importa... porque é isso, autonomia é política  sujeito mais autônomo... e crítico, porque essas também são palavras que andam... você não pode ser autônomo sem ser crítico... (incompreensível) você tá dependendo” — Pedro

[quote]
Porque, se não tem diretamente a ver com política... porque aí tem outra coisa, que o Ônibus Hacker me ensinou, é que a compreensão do que é você fazer política é muito mais expandida do que... a gente, por exemplo, eu comecei a fazer (incompreensível). E eu defendo (incompreensível) porque ele quer vir com autonomia, e tudo o que tem a ver com autonomia, na verdade, é um instrumento político, de politização do indivíduo, saca? (incompreensível)
— Pedro

'''
[quote]
John Mackey, founder of Whole Foods: “In 2005, [Whole Foods Market] did $4,7 billion in sales and realized $136 million in net profits,” and adds that “on percentage basis, Whole Foods Market is the most profitable public food retailing business in the United States, with the highest net profit percentage, sales // growth and sales per square foot.” On the other hand, he seems to refuse the label of a standard successful corporation: “When executed well, business increases prosperity, ends poverty, improves the quality of life, and promotes the health and longevity of the world population at an unprecedented rate” (Mackay 2006, cited by Elkington & Hartigan 2008:53-4).

'''

[quote]
The authors seem to agree that indeed that is what make Whole Foods a social entrepreneurship: “… it with asking why Whole Foods is a social business. One part of the answer is that it has done a great deal to drive the whole food and organic food concepts into the commercial mainstream” (2008:50).

[quote]
The term ‘antipolitics’, however, should not be misconstructed as a synonym for mere opposition to particular regimes or confused with electoral opposition that arises in the normal course of contemporary democratic or quasidemocratic practices, as Andreas Schedler points out … Antipolitics is present when politics itself is regarded with cynicism but also seen as a contaminant of society, indeed the enemy of all other societal activity. When antipolitics flourishes, politics itself becomes the central target of opposition and is perceived in extremis as unnecessary, the potential destroyer of all that is praiseworthy in human affairs. Antipolitics in this sense inverts Hobbes’s analysis: whereas he argue that politics is the precondition for civil and humane conduct, the antipolitical actor or theoretician maintains that politics is a threat to morality, enterprise and all authentically human values” (62).

'''

“What the economic polity renders scarce for its citizens is the direct experience of politics itself and the responsibilities of power. And that is the ‘renewable resource’ unique to the political ecology of localism: unlike the corporation and its accomplice … localism can generate and continuously renew direct political experience” (604).

“The aim is not to level in the name of equality or to cherish nostalgia, but, by gaining some measure of control over coordinations and decisions intimately affecting the everyday lives of ordinary citizens, to relieve serious and remediable distress and to extend inclusion beyond the enjoyment of equal // civil rights by making access to educational and cultural experiences and healthy living conditions a normal expectation” (604-5).

== References

[references]
* Arendt, H. (1998[1958]). _The Human Condition_. 2 ed. Chicago and London: University of Chicago Press.
* Berlin, Isaiah (1999[1958]). Two Concepts of Liberty. In Nigel Warburton. _Arguments for Freedom: Milton Keynes: Open University. Pp. 155-165.
* Bourdieu, P. and Passeron, J.-C. (1970). _La Reproduction. Éléments pour une Théorie du Système d'Enseignement_. Paris. Minuit.
* Elkington, J. & Hartigan, P. (2008). _The Power of Unreasonable People. How Social Entrepreneurs Create Markets that Change the World_. Harvard Business Press: Boston.
* Jaffe, E. (1997). Our Own Invisible Hand: Antipolitics as an American Given. In Schedler, A. (ed.) _The end of Politics? Explorations into modern antipolitics_. New York: Macmillan. Pp. 57-90.
* OECD (2013). ,OECD Factbook 2013: Economic, Environmental and Social Statistics_, OECD Publishing, Paris.
* Wolin, S. (2004). _Politics and Vision: Continuity and Innovation in Western Political Thought_. Princeton and Oxford: Princeton University Press.
