= Autonomy
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
Action would be an unnecessary luxury, a capricious interference with general laws of behavior, if men (sic) were endlessly reproducible repetitions of the same model, whose nature or essence was the same for all and as predictable as the nature or essence of any other thing. Plurality is the condition of human action because we are all the same, that is, human, in such a way that nobody is ever the same as anyone else who ever lived, lives or will live (Arendt 1973:8).

The last chapter's discussion of money is one element of a complex mélange that defines a specific world view widely adopted by the crowd funding community. Another element of this mélange is the understanding of what is at stake when this community purportedly adopts an alternative and marginal lifestyle -- especially when it comes to the notion of making a living out of a career. Maybe a first impression about people who are trying to re-signify money would point towards a utopia, a desire to change the world. And in fact that was what Felipe told me:

[quote]
[The Bachelor's degree in] geography gave me incredible tools to work with sustainability. And then, when I was 20, 22 years old I was totally addicted to working and changing the world. And I'd work as hard as possible, for free, out of passion.

Before starting his partially crowd funded Master's degree he had been an undergraduate student in two different fields: economics and geography. He opted for these courses because he felt the world was sick and needed to be saved: he would claim natural resources were disappearing, escalating levels of pollution were condemning the environment, and people were deeply deluded and exhausted in their obsession for work and making a living. The result, according to him, was a toxic world with serious personal and social issues. This situation was unbearable for him and thus he thought something had to be done.

When he was beginning his higher education, Felipe went for economics because, as he put, "it would provide me with knowledge about the system, about social life, and later I could get into ecology, ecological economics, green economy." The _system_ is a concept that many interviewees would use to address the overarching values fostered by the incumbent institutions,  such as the corporative market and the nation states. After a couple of years Felipe changed his mind: "I had taken a too long diversion to actually get to the point where I could study sustainability, study labor, cultural and social alternatives." He started to look for alternatives and geography seemed like a good idea: "according to the program I would study natural sciences, social science, humanities and the correlation between them." He then changed from economics to geography, trying to do something to save the world -- or, at least, trying to prepare himself to do so.

From this background it is comprehensible that when he graduated he was up to pursue arguably overarching objectives: he was aiming at changing the world, at changing the system. Later, at the time of the interview, Felipe himself would label these objectives as naïve:

[quote]
I have worked for NGOs, it is a little bit of my trajectory. And there are other things. I have worked in the market for big companies such as Petrobras which is a semi-public corporation.footnote:[Petrobras is actually a major Brazilian company. It has been listed in Forbes 500 for 22 years, figuring in the 58th position in the 2016 ranking.] And I have worked for small initiatives too. I started to see that I did not believe in the idea that we would change the system form inside out. […] Actually, I do not think it is about changing the system. I think it is all about bringing an alternative, from the outside -- that is why my blog is called _On the Edge_, it is a culture living in the margins, it flirts with the real and the anew, what is not there yet.

His Master's degree focused on the collaborative economy. According to him this route seemed promising because "it moves away from the default of changing the system." Specifically, he claims that this route does not take a combative position against the system (or, at least, against the monetary system, as he mentioned in the interview): "let's leave the monetary system there, let it go. It will change if it has to." Yet he thinks it is a waste of time to fight the monetary system, it is like "throwing small stones against a big wall."

Interestingly, his position does not imply that he had abandoned the idea of doing something to make the world a better place. It means he had scaled down his actions, keeping his ambitions as high as they were before. Once he realized he will not change the system from inside out, he adopted a new strategy that focuses on small actions, on possibilities within his reach. It is not about solving the problem for everybody, it is not a revolutionary take on the world. It dismisses the global and outward expectation of _changing the world_ and replacing it with a local and inward version of it.

Engage was one startup from Brazil that used to work under the motto _power to the people_. One of their co-founders summarized this process described by Felipe in a few words (as this co-founder has himself been through a similar change in terms of life objectives):

[quote]
Engage was built with that 'change the world' idea in mind. And my history with Engage was all about getting tired of this chip chatting. But I do believe we are changing the world. I do not consider myself a dreamer. I am a very pragmatic guy who, at the same time, dreams a lot -- otherwise I would not be able to be pragmatic.

Life stories like that raise important topics for discussion, topics that clearly take the process of the re-signification of money to another level -- to be more precise, topics that justify this re-signification with a more specific purpose. Governments and corporations can act as constraints to actions and thus the strategy is to minimize the relevance of these institutions within the crowd funding communities' lifestyle -- namely what they are pursuing is autonomy. It is the case that the approach to autonomy discussed here emerged from the fieldwork and the idea is not to measure, corroborate or deny how autonomous my informants really are. What is relevant is to understand what they see as autonomy, how they pursue it, why they do it, and how this relates to the social and political framing of their choices.

As this chapter describes, there are similarities and differences in terms of the rejection of corporations and government. Although it is common to see the disavowal for both coming together from time to time, the corporative alternative is seen as an alternative to the boundaries of the other -- in other words, even when not completely discarded, the government is hardly ever seen as efficient in terms of granting the autonomy which the crowd funding community is looking for. On that point it is interesting to see what the expected role of institutions is: on the one hand it really seems that states in general are losing their appeal as an authority (for example, as in Wolin 2004); but on the other hand, if people are free to explore new economic arrangements and new social relationships (as in crowd funding) some institutions might be responsible for the freedom empowering these novelties.

To be clear, the question raised in the last paragraph relates to Berlin's (1999) positive and negative freedom -- or in other words _freedom for_ and _freedom from_. While the latter refers to situations in which there is an absence of interference in one's actions, the first one emphasizes the deciding power (over the possibility of being decided for). In that context it is prudent to explore the following discussion on autonomy, having in mind some recent institutional transformations that are crucial to comprehend how my interviewees relate freedom and autonomy to these institutions they seem to reject. For instance, Wolin (2004:588) suggests that:

[quote]
The changes in capitalism have weakened the authority of the state as the supreme power in society. Globalization is the euphemism for continuous expansion abroad and the constriction of politics at home, narrowing the points of entry so that only the pressure of money can gain political access […] Although the state continues to play a far form negligible role in an increasingly globalized economy, the power wielded by multinational corporations has made their cooperation and acquiescence indispensable. The cooperation of corporate power is now a vital element of domestic, foreign and military politics. Competition and rivalry occur less between state and corporations and more between corporations vying for influence over the state or subsides from it.

According to Wolin (2004), what used to be seen as traditional roles expected from government started to be played by corporations: instead of merely paying salaries to employees, the private sector started to provide a wider community with funding to cultural and educational initiatives, for example. But at the same time money replaced citizenry as the core of quality measure for success and failures within many national and regional democratic institutions: "state actors have become dependent more on corporate power than on their own citizens" (Wolin 2004:589).

Finally, Wolin (2004:586) suggests two opposing political tendencies to deal with this situation: a centrifugal one that "fears democracy because it homogenizes suppressing significant differences in favor of a monolithic ideal of 'the people'" and a centripetal one which "is contemptuous of democracy for its weakness yet envious of its appeal." Maybe the way my interviewees downplay government is a signal that they are closer to this second tendency --  precisely the tendency Wolin (2004:587) believes to be the least promising for democracy:

[quote]
Whatever remains of democratic possibilities lies with the centrifugal forces. Yet their political prospects are the more problematical. For despite their critical attitudes towards the state -- perhaps all -- of the major centrifugal groups look to government for assistance and protection and to its courts for relief. This requires some accommodation to the political culture that surrounds the national government and many state governments, and that, increasingly, has become indistinguishable from corporate culture.

This chapter looks into the strategies the crowd funding community has traced in order to grant themselves more autonomy. This attempt involves a series of rejections of certain institutions and would be best described as an attempt to pave an alternative way that is independent from these rejected institutions. And this is because what is at stake is not a confrontation, but the relegation of the importance of some institutions. From the sociological perspective there are tensions in the struggle to reject institutions, especially when they are incumbent in the modern states and that is the case of corporation and governments. The first part of the chapter focuses on a more optimistic branch: people for whom corporations and governments are problematic but who still act in the sense of trying to change these institutions. The second part is based on more radical accounts in which the rejection is so bold that they usually try to opt-out of the power of these incumbent institutions. Interestingly, in both cases they distance themselves from the institutions without confrontation, and from their choices they end up building a new set of values that, for them, minimizes the importance of these institutions. This is the core of their pursuit of autonomy -- not only for themselves, but for all the peers taking part in this endeavor.

== Hacking incumbent institutions

Autonomy is a major drive in my interviewees' choices and this specific criterion leads them to perceive institutions as obstacles to fulfilling their life expectations. However, not all institutions are barriers and a lot of judgement takes place in their strategies to position themselves into the world, to pursue their ideal of autonomy. Their movements accepting or denying certain institutions are revealing of what they understand as autonomy. Felipe's case, for instance, points towards the problems of trying to promote change from the inside out, but a lot of other interviewees believe that institutional arrangements can help them in the arduous task of making a difference in an arguably sick world, as Felipe has describe it in his interview. Carla, for instance, started a promising career in the advertising market but at a certain point she started to have similar thoughts to Felipe:

[quote]
I hold a degree in advertisement, I worked for 10 years in advertisement agencies with planning and research. Then a couple of years ago I started to realize that all my investment in terms of time, of daily efforts, of commuting, and of focus on the projects I run, all that was kind of useless. I worked in an agency and I was part of a process that would end up in a banner in the end of the day. It was a communication piece that would only feed this Machiavellian system.

Carla was pondering not merely her dissatisfaction with her job. Her reflections target two very specific things. First, the purpose of the market she was contributing to and how she felt about it is encompassed in her use of the term "Machiavellian," which characterizes this market as unscrupulous -- and it is noteworthy that, similar to Felipe, she emphasizes the coercion of this mindset by labeling it as a "system." It is not a Marxist alienation when it comes to individuals and labor, but a more intimate disapproval of how professional life is organized. To be clear, by quoting Marx I am not inferring that Carla would subscribe to Marxist theory as a whole -- actually she might not subscribe to it at all. However, the description she offers of her relation to her previous jobs relates to Marx's (2007:72) description of workers who have no chance but to subject themselves to their proletarian condition:

[quote]
His (_sic_) labour is therefore not voluntary, but coerced; it is _forced labor_. It is therefore not the satisfaction of a need; it is merely a _means_ to satisfy needs external to it. Its alien character emerges clearly in the fact that as soon as no physical or other compulsion exists, labor is shunned like the plague. External labor, labor in which man alienates himself (_sic_), is a labor of self-sacrifice, of mortification" (emphasis in the original).

Second, this feeling regarding certain jobs was not merely a political disapproval of the purpose of the companies she was working for. This disapproval was a very personal urge to stop investing her most valuable and integral assets in something she did not believe in: her efforts, her time, her energy and focus. As she told me: "I felt there was something missing, I could be contributing in other ways to project development, to innovation… to innovate with positive impact." In opposition to the Marxist conception of the proletarian, she felt she had other options: similar to Felipe, she needed to go to the margins. Her strategy was to specialize in design for social impact (she now holds a Master's degree in such a field) and to try to engage with projects more focused on the city, on urban spaces close to her. Now she works in the strategic innovation market, having experience at consultancies focused on a positive impact on society. Other interviewees also opted for working for this kind of company: usually they are small to middle sized offices, they hold multinationals such as Coca-Cola, Nestlé and Petrobras in their portfolio, but at the same time they value and develop projects for NGOs, civic activism and for the public sector. From time to time these small companies also have their own projects, that might become spin offs -- that was the case of Catarse, for example.

Brittany is an American woman and in the interview she mentioned the choices she felt were available to her after graduating:

[quote]
It's interesting to be able to create projects instead of just typing on a keyboard, and those were the kind of job opportunities I had: doing more office work for any organizations that were not particularly exciting as well. At that time too it was so competitive that I think I would have ended up having to be more focused on something with a better paycheck and not necessarily a job that is fun.

In other words, she felt that all the traditional job opportunities were uninteresting, bureaucratic and limiting her creative and her hands-on impulse. She is very concerned about natural resources, climate change and the environment in general. At the same time, however, she did not want to work either for the government nor for NGOs: "I don't have anything against the government, but I'm just more personally interested in private industry." Therefore, she joined a private park, a nature reserve, in a position in which she could start and manage projects instead of doing office and paper work. Her choice for a private environment was deliberate:

[quote]
I consider myself an eco-capitalist. I've never really imagined myself working for the government or NGOs. I am more interested in doing change through the private industry. Private industry is not restrained by borders as long as you have the right market incentives.

She believes that there is a higher chance of promoting substantial changes in the world from a private institution, with no borders -- but she reinforces that the right incentives should be set by the public sector. Still she believes that federal government might be too big to understand her reality and make the right moves:

[quote]
There are so many stupidities sometimes, because you have to deal with someone who will deliberate on an environmental project and they are 300 kilometers away, and they have no idea about what your reality is actually like. I do not think this is the most effective to do environmental policy. That is why it is nice to work on a private reserve because we have a relationship with the [local] public government, we are bordering a state park. I have a bit more liberty. We work a lot with the people from here. We do not have to deal with people who have never been in the area and do not know anything about it.

To differing degrees, what Carla and Brittany are claiming is that they want to be able to choose what kind of projects and action they enable in their everyday life -- they want to be in control of the anew which emerges from their actions. Also, this claim is sustained by a world view that considers governments and corporations too big to feel what individuals really face in their daily routines. If Brittany's example is clearer (she even mentioned the _think global, act local_ motto during the interview), Carla's one might need further discussion: in spite of the multinational clients, all of the projects and deeds she mentions in the interview are related to the urban space and civic projects she has been involved with. The consultancy she works for might not be exclusively focused on these kinds of projects but she considers that since there is room for them, it makes the job more attractive than the other ones she had had in the past.

These two women are somehow referencing  the private sphere because they believe society needs change -- it appears that Carla is arguing that what is needed is some positive impact in the world, while it appears that Brittany is arguing that the world is compromised due to climate change and other eminent environmental situations. Underlying these arguments is the responsibility that the state bears in such scenarios. For Brittany, part of the problem is the distance between the governments in charge and the reality of the governed people. Carla has not been explicit in supporting this view, but her actions seem to corroborate it. During the interview she was listing some probable causes for the lack of social impact in many projects. At this point she ended up saying that "it cannot be a single NGO, it is not Greenpeace that is going to sort that out, it is not the UN alone that is going to do it. It really has to be something massive" -- this quote might be intriguing since Greenpeace and UN are massive institutions after all. To avoid any doubt, she expanded on this:

[quote]
I think it [the solution] should be decentralized. That is part of Box's Brazilian Dream Project, the idea of microrevolutions, but the thing is that companies should also be decentralized. Thus when I say "something big" it is something that belongs to the people, that is part of everyone's concerns. Therefore, not only people, but companies need to have an active role for a better society.footnote:[Box 1824, mentioned by Carla as "Box," is a Brazilian consultancy that has built a great reputation publishing researches on Brazilian culture -- most of them on Creative Commons licenses, free to read and watch on the internet. Those reports usually are shaped in short videos that easily become viral on the internet. As a disclaimer I must add that Carla told me she has freelanced for this consultancy.]

If this quote sounds too abstract or utopian, Carla offered as an example the case of public bikes in São Paulo. In a similar scheme to Barclay's bikes in London, the scheme was structured through a public-private partnership, coincidentally backed by a nationwide bank too, a Brazilian bank, Itaú:

[quote]
[Take the case of] Itaú's bikes: there are various issues that could be risen, a lot of questioning on whether it was more about marketing than about a proper solution [for public transportation]. But this was a social innovation to the city because it was considered within a mobility and civic movement […] People who were not using bicycles before are trying it now. Despite the [commercial] interests (because I do not believe they [Itaú] are just being nice, they are a bank) it is a social innovation.

Hence, from Carla's point of view there is an important factor which is being close to people, to civic activism. Or in other words, being local -- something that overarching federal governments and multinational corporations fail to achieve, as many of my informants have asserted. They appear to be arguing that at the end of the day these massive institutions would become the _system_, a black box in which money and power is the only possible rule -- picturing the context in consonance with Wolin (2004), for example. In sum, the problem does not reside within the private or public realm _per se_, but in the distance between individual and institution.

To add another example, Noah is a graduate student in political theory, also from the USA. Throughout his life he has been involved with civic activism and he has also contributed to some crowd funding campaigns. He told me about one of the projects he has been involved in, one in which his group was very close to the city council:

[quote]
The objective of the organization I volunteered at was at the city level and we ended up getting a majority progressive city counsil. […] The city runs the airport and they decided that they were going to renegotiate the contracts for the food in the airport. They did not want to have corporate restaurants. They wanted to reach out to all very famous local businesses, restaurants and say "would you like a branch in the airport?" […] That was sort of one policy they want but the point I am trying to make is that I am always focused on building power at the local level, in the face of structures that are configuring the social relations at a larger scale. International trade treaties and national immigration policy [for example], these are all things that are sort of structural, but we were coming up with local ways to resist. Sort of asserting local power in the face of this larger structure.

The critique built by these people who at a certain point have recurred to crowd funding is not targeting explicitly the public or the private sphere, as Noah's example clarifies. They are at the same time targeting a specific world view that puts individuals as dependent of a paternalist institutionalism led by government and corporations. However, instead of fighting these issues with an overarching argument of more regulation nation-wide, for example, they prefer to opt-out, and push local changes so more people opt-out, of national or multinational corporations, as well as from policies that weaken local people. This focus on the local level and on local action has pushed many of them away from the ballot itself. The same rationale that makes them refuse to work for or support these corporations also makes them be completely uninterested in voting, for example. Most of my Brazilian interviewees -- where voting is compulsory -- have declined to vote for years.

Stephen is an experienced British entrepreneur who mentors many social entrepreneurs. He points out that due to the economic crisis there are no jobs being created, therefore "being self-employed for an increasingly greater proportion of the population is the only option." In this scenario he sees crowd funding as a promising alternative since in many cases not even banks would fund certain entrepreneurs such as people in debt, people with no guarantees, as he would put it. But in opposition to most business men who praise the success of new companies such as Uber or Airbnb, he is quite critical about them. He made his point during the interview with an example of a British short-term car rental:

[quote]
It started as Street Car which was a UK company, which is cool. Nice service, nice cars. It was bought by Zipcar, which is an American company. The service went down a bit, the cars went a bit crappier. And it is now owned by Avis […] It is very hard because clearly it is having an impact. It does take a lot of cars off to the road. But on the other hand, it is now part of a big corporation.  And it is working for shareholders rather than to the communities. And I think a lot of this stuff, for me it would be much more interesting if somehow you could keep it at a local level, a community level.  But you cannot do that […] The biggest obstacle is how you rethink money or if can you rethink money -- and if you cannot then actually everything is all a bit meaningless because it all comes down to cash in the end.

He is not precise in pointing out how to make and keep innovation local, but he is very sharp in his disapproval of global corporations taking over local business. If the critique does not target the public or the private specifically, it suggests that both spheres nowadays are driven by money. It would appear that my interviewees are claiming that corporations and government are distant from people's needs and reality because they are organized in a way that focuses on making money and also on distributing money through a lifestyle framed by the _system_ -- that is to say, a lifestyle based on an overarching policy that values jobs, wages and benefits. The problem is that the crowd funding communities are re-signifying money and consequentially they are not settling down in a comfortable job that offers them some financial stability. Their personal views on the world, on this system, seems more important than the values being delivered and nurtured in most national states policies and in most corporate environments.

The question these stories raise is rooted in the size of the organizations, but the core issues are _quasi_ inevitable consequences projected by my interviewees: for them bigger institutions put the decision making process away from their everyday lives. Therefore, their strategy involves working in small scale institutions that enable three valuable things; conciliating personal values within their everyday life activities, being able to promote some actions with some impact, and avoiding bureaucratic and impersonal decision processes. The motto _think global, act local_ seems to have a perfect fit with these ambitions: the thinking part allows them to channel their dreams and aspirations to action; the acting part is taken locally, that is to say, is more feasible and easy to put forward than more ambitious projects that would require layers of deliberation. In other words, instead of a global _workers of the world, unite!_ chant, they are reaching out to their close network and starting small, with baby steps. Deliberation in general would be compromised if not handled at the personal level: when people's opinions are framed into instrumentalized and rationalized institutional processes the only rule that matters is cash -- and that is the kind of value that is not appealing to this specific community.

Hence, action is of the utmost importance to them. Their idea of autonomy is to be able to act, to put ideas forward, to experiment and learn from it. This hands-on model is believed to be the best shortcut for a positive impact, for promoting and enabling change in the here and now. The impact and change expected are not to be felt immediately worldwide: their expectation is also focused on a micro sphere, their own lives and feelings. Carla herself is very clear on that point: she is not sure if Itaú’s bike scheme is the best for São Paulo, also she would not oppose a totally public or a totally private initiative to compare them all later -- the important point is to go into action and to get feedback at the local level:

[quote]
It is very difficult to get it right the first time, thus we have to test, to hack, to experiment. I praise the initiatives with that mindset. And actually that is why I really like crowd funding. Crowd funding is a way to engage, to motivate, to show possible futures -- that is what really matters.

All the quotes so far are somehow critical about corporations and governments: Carla had to cherry-pick consultancies to work for (and maybe with which clients to work with) because there is a discomfort with the kind of project most corporations invest in. Brittany also cherry-picked, but she was harsher on the government side -- characterized as inefficient (distant from the real everyday life of people) and limited (by national borders). Noah seems to disavow the big players from the food industry and tries to minimize the impact these corporations have in his region by acting close to the government, to the city council. Stephen believes that the economic policies put forward by governments (policies in tune with the interests of multinational corporations) failed to provide jobs and stability for citizens; for him, even banks (a kind of corporation regulated to certain degree by governments) are failing in helping people to bootstrap their ideas. In spite of that, these people are not so distant either from governments or from corporations: they try to hack them, to make these institutions work in a way that is more coherent with their aspirations. The next section discusses strategies that can be seen as attempts at a greater step: for some people, hacking these incumbent institutions is not enough and the idea is to bypass them.

== From avoidance to autonomy

As the previous section described, there is a clear and intentional will to find alternative ways of making a living within the crowd funding community, a way that would circumvent the corporative and public sectors. Even if this holds true for all of my interviewees, there is a group within them that take this disavowal of  these institutions further. At this point it is worth referring to Stephen’s consideration of the job market. In fact, his argument follows some general trends: for example, self-employment rates have been rising slightly in the UK since 2002 while unemployment rates increased by 50% in the same period (OECD 2013).footnote:[According to the OECD Factbook (2013) between 2002 and 2010 self-employment raised from 12.7% to 13.8% and the long-term unemployment rate raised from 21.7% to 33.4%. Stephen's interview was in 2014.] However, the feeling that there are no jobs out there is not the only reason underneath the disavowal for these institutions. There are also clues suggesting that for them framing their professional activity in the form of a formal organization -- whether it is a corporation or NGO -- is not the best way to actually do what they are willing to do. Pedro told me about a time when he was one of the founders of a kind of hacker space in Brazil:

[quote]
We were drafting a statute, a charter and then we realized that it would be impossible to start an organization because we could not agree on a common text. We had principles, we were heading to the same direction, we liked each other, and we used to get together. But it would not work to frame an organization with a charter, a social statute saying what we would be doing. Some would like to do journalism, some were willing to do photography…  whatever, we do not need a statute, right? Instead of an organization, an NGO we ended up with a space where everybody could work on their own stuff together.

In contrast to Stephen, Pedro does not actually expect that any institution will provide the best framework for his and his friends' professional affairs. In his opinion, formalizing an organization would mean an onus without a bonus: they do not want to be limited by any regulation about what kind of professional activities they are supposed to run,footnote:[In Brazil there are regulations based on UN's International Standard Industrial Classification, very similar to regulations in many other countries, as my interviewees reported. For them this means that when setting up an organization one must restrict the kind of projects one is going to execute. As some aforementioned examples, many of my interviewees have a very heterodox professional path, and they would like to act as technology consultants and in parallel they would be teaching tango, composing and playing music.] they do not want to pay taxes for opening an organization because they do not feel they are getting anything in return except boundaries. In sum, they feel better acting on their own.

From Stephen and Pedro, it is possible to grasp the skeptical tone of the disavowal of corporations, NGOs and the public sector: while many of the quotes from the previous section illustrated life choices in terms of better or worst organizations to work with, there are cases in which the disbelief is so bold that it actually pulls people to a kind of libertarian attitude. While Carla and Brittany are satisfied in the kind of projects and institutional arrangements surrounding their professional activities, other interviewees expressed a harsher opinion regarding the incumbent institutions discussed here. For Stephen, in an almost non-existent job market one probably would have little chance to be able to choose a job that has a good fit with one's life purposes. At the same time it would appear that Pedro would probably see Brittany’s choices as limiting because a lot of money, time and effort is wasted in taxes and bureaucracy to keep the company running -- a lot of assets that would be best invested directly on environmental issues, for example, especially when it comes to the private market, as Pedro highlighted:
[quote]
The problem is that companies will always meddle, you cannot do things your way. Thus, if you want a project to be independent, there is no way [to work with corporations behind you]. Take the classic journalism example, the chitchat that just adding the logo to something would not interfere with the content. That's tough to believe in.

In such a scenario crowd funding thrives as an alternative, a way to bootstrap projects without ties to any corporative or governmental funding. Actually, this is what Miguel, a co-founder of one of the biggest Brazilian crowd funding platforms, told me:

[quote]
Indeed, we have opened an alternative model of funding in Brazil, an alternative to public funding, private funding, bank loans… And then we started to see projects flourishing, things happening. It opened a whole new world for people. […] And in fact, this was something that did not existed before: back then there was no way to fund a project, a small project, here in Brazil.

This last part of this chapter explored how this avoidance of institutions is forged from a very similar idea of autonomy as discussed earlier. Autonomy might be clearer in Pedro's arguably idealistic quotes, but even from Stephen's more pragmatic standpoint autonomy is present: one would not depend on corporations offering jobs to make a living. More importantly, for some of them a kind of real autonomy is impossible within the current incumbent institutions -- that is literally Pedro's position, for example.

Maria is a Romanian woman who partially funded her Master’s degree through crowd funding. Amanda is a Brazilian entrepreneur who runs some open journalism workshops, mainly in poor neighborhoods around metropolitan areas. At a certain point both of them faced the possibility of partnering with some of these institutions the crowd funding community seems to disavow. Maria was approved in a kind of dream school for her, but she could not afford the tuition fees. Amanda was running a very successful communication project in one of the poorest areas of São Paulo, but she was not satisfied with the mindset of the NGO behind her. Both dismissed the most standard choices presented to them: Maria had not considered a bank loan, and Amanda pushed to leave the NGO, which meant the end of the project. Respectively, they told me their stories:

[quote]
I did not want to kind of play the rules of the system just to get to a very alternative education institution. This is ridiculous. And even if I could get a loan from the bank would I really want a loan from the bank to go and study alternative education, like new economy? This is ridiculous (Maria).

[quote]
We realized that it would not work with the NGO because the NGO refused to pay the boys (_sic_). We were like "we have to start something that can afford to pay the boys, so they can be autonomous" -- we ought to do that because that is what we believe in. We believe that it is worth it to engage the boys if it is cool for them and if it pays them back. Otherwise they will look for a job from which they can make a living of and they would not realize that this [communication] is what they really would like to do (Amanda).

Those quotes might raise an interesting tension: one might see Maria's option as a subtle way to refuse money and its possible benefits, while on the other hand Amanda's opinion would be the opposite; an explicit movement in the sense of vouching money in a protagonist role. It is worth it highlighting that both women are actually pointing in the same direction when it comes to rejecting the current mindset behind incumbent institutions. Maria does not want to get involved with banks (arguably corporations with strong ties to governmental affairs such as the federal reserve and interest policies). Amanda does not believe that more traditional social projects are worth it: charity, government benefits and non-profit organizations are not actually causing impact because they do not foster autonomy.

This apparent paradoxical approach to money however, can be analyzed thoroughly in order to clarify that even if they seem to be pointing in different directions, they do share some common ground: first of all, as discussed in the previous chapter, money is mostly a social relationship marker, not merely an amoral token for exchange and the accumulation of value; second, at the core of their decision is an emphasis on how one can enjoy autonomy and root their own relationship with the world in an autonomous way. Let's get back to Maria's case as her story might not be as straightforward as Amanda's. Maria told me that after her Bachelor's degree she was working as a volunteer in some projects:

[quote]
I was a bit disillusioned seeing that when you are offering your services in terms of volunteering it is a fine line between being exploited and being helpful. I felt I was being exploited because I was not getting the learning […] but I had very good exchanges. I think it just brings the idea of skills and exchange and how we measure that. It's very subjective from person to person to think about what each one thinks is fair to invest and give back in this exchange -- and here money is not involved. For me it was an interesting question that was posed there.

From thoughts like that it is clear that Maria was already calling into question how problematic exchanges are, in her case how uncomfortable she felt trading her skills for money or for anything else. However, the problem, as she told me, was not put on the exchange _per se_ but in the context. For instance, as a photographer and journalist crowd funding her tuition fees, her first thought was to offer a big book with photos taken by herself and stories she would write about everyone who pledged for her campaign. That was too much work for a short deadline, so she took an even more personal route: "for example a photograph, or you would get one of my essays or my dissertation, a song, maybe photography services if you were a big company" -- that was what she went for in terms of perks for her crowd funding contributors. She was telling a story and sharing her experience with her supporters -- and the exchange was a platform for that. In other words, she felt she was moving away from a kind of pecuniary exchange that would be meaningless from her point of view, and at the same time she was embracing a more personal or social lens to comprehend and forge these exchanges:

[quote]
I was trying to stay out of politics and economy, I just did not want to have anything to do with it in any way. It was kind of putting it all in a "bad guys box" and do not want to deal with it. I went through the other, alternative route, local villages and what is happening out there -- that is not mainstream. I was very curious to see what is happening and what is the drive for these people to really go off the grid. Is this really possible? Because this sounded like utopia for me back then. So, I just wanted to experience it myself and also I wanted to see if I could ever live or make my own alternative way of being.

At this point she was framing a series of very personal ways to comprehend life choices around her and clearly there is a stereotyped standard career path, a standard way to make a living that was not interesting for her. At the same time  this is the mainstream in her standpoint, thus one would have to be willing to fight the temptation to go with the flow. In that sense her life choice was to start to trace her own path outside this trail. For her the possibility of making this diversion, the possibility of creating her own route, is a gesture of autonomy. Thus, when facing the tuition fees invoice Maria opted for the arguably riskier path: not asking for a loan in a bank but for friends, and friends of friends and so on. Not messing up with the "bad guys" was not only a possibility but -- most importantly -- the option she actually chose because this way granted enough autonomy for her.

Looking back to Amanda's story -- specifically when she expanded the idea of autonomy to her "boys," to the teenagers that participated in the social and entrepreneurial activities she hosted -- the context was a completely different one. Two main points must be highlighted here: they were poor in a very unequal country and they were young. According to Amanda they were already dealing with a lot of social and peer pressure: maybe they were considering dropping out of school to try to find a (probably unskilled) job and contribute to the family budget; maybe some of their friends were getting well off working for drug dealers or gathering in gangs, which would make these real possibilities for her teenagers in the short term; maybe they have not even considered that journalism was for them at the first place.footnote:[As in Bourdieu's (1990) classical argument on reproduction: the weight of classes and personal trajectories is not only a matter of privileges and constraints, it is also a way of forging what one considers conceivable for the future. In Amanda's interview the context in which the teenagers are considered is made clear in lines such as: "In general the boys are not going to school, most of them are high school dropouts. And when we asked 'where are they?' we realized they were on the internet. And then we asked again 'and where do they learn things?' just in time to realize it was with tutorials on  YouTube about mathematics, about makeup, whatever. Then we spent about 6 months working on the language and the blah blah blah to launch educational videos. […\] We had no money to do it, thus we ended up in Catarse, we need to open the videos for everyone, free access to everybody: these educational videos had to be free because we were thinking about high school teens, they have no money."] In other words, Amanda felt money was important for them to be autonomous and escape the kind of mainstream within their social context. Arguably, if the project could support them with some money they would be more confident in considering communication as a career option -- and with this confidence they are better empowered, they have a higher degree of autonomy. Once more, money is understood in a very peculiar social context, playing a very important role in negotiating with power structures (e.g. peer pressure, repression, etc.).  Finally, Amanda also believes that their autonomy has to do with her own autonomy: "their autonomy sets me free to be the mother of my daughter, otherwise I would end up full of other children to take care of -- I only can look after myself if they are autonomous."

This is a very common characteristic among my interviewees: their own purpose in life. Amanda loves her job, the projects she runs. But she loves being a mother and she sees those projects as a way to make it possible for her to be a good mother. It is not about a worldwide revolt against corporations, NGOs and governments, but the opposite; a set of choices based on micro inwards revolutions; a set of choices that at the end of the day offers them the feeling they are more capable of being autonomous than they would be in a full-time job in an organization, for example; a set of choices that also empowers them to get involved in different projects making a living out of the multitude of them, not of a single one; a set of choices that connects these projects with their utmost personal ambitions in life.

Another of my interviewees has co-founded a recurring crowd funding platform in Brazil in which (by the date of the interview) he has five different projects. He was the person who coded the platform from scratch, but most of the projects are related to his career as musician and as a tango dancer and teacher. However, there is another project he hosts there: as the platform charges no fees at all it is supported by a crowd funding campaign within the platform itself. It is interesting to take into account the importance he puts on these options:

[quote]
I got tired of this chip chatting about changing the world. So why is this platform so cherished for me? […] Because I dream of a world in which we do not put price on things, a world in which we do not create services just for the sake of creating it, just to put up with the financial situation. So all that has to do with a will that other people could do what I am doing. To change their life as I am changing mine, in baby steps.

For him this idea has matured with time. A couple of years ago he was a partner in a more traditional tech startup. He told me the history behind one of the most successful products they developed there, a mailing platform: "the idea was making a lot of money, so we would have money to do cool stuff -- that was what we had in mind." They actually achieved it somehow: the company became successful in the market. However, as the company grew bigger, more demanding clients and projects ended up consuming all his time -- and little was left for the cool stuff, for music and tango, for social impact projects, for working in projects that would change their lives and help other people change theirs too.

As mentioned earlier, making money is not the exact issue they are addressing. The real problem is finding ways to support -- financial support included -- their dream projects. The interesting part is that in spite of this kind of idealistic world view, they are very pragmatic -- many interviewees used different words such as "I work with the hands-on imperative in mind, I cannot waste my time in endless discussions, this is for those who have time to waste," as Pedro once told me, or "I am not a good bullshitter, I kind of like doing stuff," as Stephen described himself. Sometimes the common sense might say people work for money, but in their case, they seem to make money in order to work -- in order to be autonomous and  work with things they really believe in.

In that scenario crowd funding is a proxy for autonomy for many of my respondents: they do not depend on corporations, the job market or the government to bootstrap and run their projects; therefore, they feel completely empowered to choose what to work with and who to work with. In the process they also reinforce their distance from incumbent institutions, feeling that the proximity to their peers is also an interesting asset -- being close to, and exchanging with partners in the projects, people with whom they exchange skills, supporters of their crowd funding campaigns etc. is a way to make the money (and other kind of valuable resources) available. And this movement, by empowering them and by doing it without the incumbent institutions,  makes the rejection of government and corporations even bolder. For example, that's what Miguel takes into account:

[quote]
[In traditional funding] the intermediaries in the process keep a significant percentage. If it's a publisher the author gets 10% and they get 90%. So, one gets that crowd funding is a possibility to be directly connected to one's fan base -- and in the end of the day the publisher would end up selling to exactly the same people, to the fans of that author. […] That is true also when it comes to laws that foster cultural investments from the private sphere: the gatekeepers are corporations […] and they gain a lot of decision power, they support mainly celebrities' projects, people that already have a great amount of social capital.

Crowd funding then is a way to create and reinforce networks of people with something in common, and within these networks, amongst people with similar objectives in life and similar world views, my interviewees feel more empowered, more autonomous. Growing big is usually seen as a risk to autonomy -- usually it is perceived a way of losing track of profits (as Miguel just said) and of decision making:

[quote]
It has to be if not super local, at least national because of the legals around financial things. I think there is no doubt that crowd funding platforms have to be local. It's all about reach and that is why Kickstarter is the gorilla in the field: because they have got the reach. Indigogo does quite a good job too. Crowd Cube have built up some [in the UK] and I think that is good, but I think this is the real challenge.

Finally, the matter of the scale of their operations is yet another argument to distance themselves from governments and corporations. For some of the people I interviewed it does not matter what are the motivations and purposes behind governors and CEOs: keeping close to people you depend on is a way to assure autonomy -- and usually they see that these organizations lose it when they scale up.

'''

Throughout this chapter dissonant points of view were put together to describe how the crowd funding community forges their own version of autonomy. For Pedro, autonomy "is what really matters, that is it: autonomy, a more autonomous and critical individual" -- and indeed this is very representative of my data collection. In a more descriptive approach they have their own version of autonomy that is not a standard career path with a good salary, benefits and social security. Their version emphasizes the freedom to choose where to invest their times and skills -- and referring to Berlin's typology of freedom, this _freedom to_ choose has a strong tie with the _freedom from_ interference in these choices. Actually, their version of autonomy is kind of sloppy when it comes to the _freedom from_. They usually emphasize how their own choices (in a microsociological sphere) guarantee the avoidance of external interference, but sometimes they are negligent with the social context (in a macrosociological sphere) that might be even more relevant for such freedom: as discussed in the previous chapter, they enjoy a series of privileges from their family and educational backgrounds, as well as from their own skills -- this seems to makes it easier for them to focus on the _freedom to_ and be more negligent with the _freedom from_ idea.

From a more analytical approach it is clear that this approach to autonomy puts crowd funding away from a purely technological arrangement and reinforces the political side of it. When Pedro reinforced that autonomy is what matters, he complemented his idea, describing how this was politically engaging people -- according to his own words, politics is not only about political candidates, parties, elections and government: "it is about a wider comprehension about what you do as political. It is a political instrument, it is the politicization of the individual." According to him this was a way to hack society in the sense of making current institutions work for you and not the other way around. A more formal way to put that is saying that this is a political statement against the amount of power held by incumbent institutions and -- more importantly -- against the valuation processes fostered by these institutions. The critique covers the institutional impact in the everyday life of most citizens: arguments that ultimately are related to the alienation of social relations in money (as discussed in the previous chapter), and the disavowal for the way private affairs are tangled up in the public sphere (for example as in Arendt 1998 and Wolin 2005 aforementioned).footnote:[See chapter 3, _Literature review_.]

Furthermore, crowd funding is not a unanimous route for autonomy and surely not a unanimous political expression. Pedro himself finds it quite time and energy consuming to run a successful crowd funding campaign (and he has run a couple of them) and mostly this is the last resort for him. Also, Stephen is quite critical about the buzz around crowd funding:

[quote]
Technology is nothing in crowd funding. It is all about marketing and reach. […] It is this kind of a Dragons' Den syndrome where everybody thinks they are an entrepreneur, everybody thinks they are an investor  -- which is good, which is clearly what produces the volume, the critical mass. But have you ever tried to get any stats out of any crowd funding platforms?footnote:[Dragons' Den is a reality TV show in which participants try to pitch their ideas to a board of venture capitalists to get investments.]

The question raised here is basically a critique towards the accountability of crowd funding projects -- as Stephen comes from the venture capital market he feels like sometimes project creators are mostly black boxes: one does not always know what is actually done with surplus money (when a campaign raises more money than it asked for), and he would argue it is basically a subjective and optional practice to share reports about how the money was in fact employed, or even reports about the impact and success of projects. For others, these questions do not matter at all: this would be just a vestige of a corporative and market mindset in which pricing things is more important than vouching for people and ideas.

In spite of this divergence the political tone of this idea of autonomy is valuable from a sociological point of view: in the light of the way everyday life choices are relevant to the triumph of autonomy -- especially when it comes to an anti-growth attitude -- it represents a microsociological version of the macrosociological political ecology stream. Wolin's (2004:604-5) appealing considerations about this topic are coherent to my interviewees world view:

[quote]
What the economic polity renders scarce for its citizens is the direct experience of politics itself and the responsibilities of power. And that is the "renewable resource" unique to the political ecology of localism: unlike the corporation and its accomplice … localism can generate and continuously renew direct political experience.  […] The aim is not to level in the name of equality or to cherish nostalgia, but, by gaining some measure of control over coordinations and decisions intimately affecting the everyday lives of ordinary citizens, to relieve serious and remediable distress and to extend inclusion beyond the enjoyment of equal civil rights.

Surely this idea of political engagement "beyond the enjoyment of equal civil rights" -- or any kind of more abstract political right -- is what is at stake when the crowd funding community describes itself as pragmatic, as a group of hands on people; also it is what is at stake when Pedro says that individuals ought to be more autonomous and broaden the perception of what is it to be political; or what is at stake when Arendt (1973) criticizes representative democracies in the sense they reserved the possibility of acting politically for very specific moments every other year in the voting cabinet. Being able to engage in action, and not only in work or labor, is the way Arendt believed it was possible to be truly political, the way to reinforce human plurality (1998).

However, it is compulsory to question if this kind of action afforded by the crowd funding community is indeed a new possibility in terms of political action. The following chapter on politics focuses on that topic but for now it is prudent to explore how this action emerged from the idea of autonomy and how particular traces of this autonomy render interesting questions in terms of political theory. The strategy crowd funding traced to avoid incumbent institutions has the interesting side effect of grouping people together around common interests -- and actually these social ties are protagonists in granting autonomy for people within this group. Interestingly, this arrangement tends to eliminate debate, to eliminate conflict as people are grouped by common interest. This may illustrate what Mouffe (2005:3) labels as highly antipolitical:

[quote]
Instead of trying to design the institution which, through supposedly "impartial" procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant "agonistic" public sphere of contestation where different hegemonic political projects can be confronted.

This trace of confrontation is absent in the orchestration of autonomy described here. _Grosso modo_, anything goes since a project creator can gather around his idea a bunch of people interested in the same principles. And again this is another red light for scholars of antipolitical trends in modern societies: politics "must be able to impose internal constraints on its members" according to  Schedler (1997:8).

Therefore, in spite of all the political significance of the attitudes and life styles embraced by crowd funding communities there are unresolved issues when it comes to advancing the comprehension of these behaviors as political. On an ideological level they are clearly confronting the power of incumbent institutions, the power of the system, as they say. And that is already meaningful enough to characterize the group as a bearer of substantial political voice. In addition, they do not act merely as an opposition that offers no alternative way out of the mainstream: in fact they are very resourceful in hacking the _status quo_ and in paving the way to new social arrangements -- that is precisely what they are doing when they re-signify money and promote their take on autonomy. However, their disavowal for political institutions might be a hiatus in their attempt to enhance the possibilities of politics in contemporary societies:

[quote]
The term "antipolitics", however, should not be misconstructed as a synonym for mere opposition to particular regimes or confused with electoral opposition that arises in the normal course of contemporary democratic or quasidemocratic practices, as Andreas Schedler points out […]footnote:[Jaffe (1997) is referring to Schedler (1997) in this quote.] Antipolitics is present when politics itself is regarded with cynicism but also seen as a contaminant of society, indeed the enemy of all other societal activity. When antipolitics flourishes, politics itself becomes the central target of opposition and is perceived in extremis as unnecessary, the potential destroyer of all that is praiseworthy in human affairs. Antipolitics in this sense inverts Hobbes's analysis: whereas he argues that politics is the precondition for civil and humane conduct, the antipolitical actor or theoretician maintains that politics is a threat to morality, enterprise and all authentically human values (Jaffe 1997:62).

The next chapter, _A new realm to empower action_, will go further in exploring the way crowd funding can be read as political, directing linking it back to Arendt's concept of action and the possibility of the anew. From that it renders it unlikely that these networks assembled by a similitude of ideas is actually a core political component in the analysis of crowd funding as a possibility of politics, inviting the discussion for the following chapter, _Isolation, silence and absence_, a critique that reiterates this discussion about the antipolitical aspect of this community and frames it in a more analytical context of political theory.
