= Politics within crowdfunding communities: the bright side (provisional title)
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
In all of us there is a dimension of obligation, constraint, necessity or compulsion which is external, and there is also a share of freedom, of creativity which Hannah Arendt places under the label of action (Caillé 2009:112).

From the previous chapter it might be clear that linking crowdfunding communities choices to Arendt's idea of action is a way to understand everyday decisions of my interviewees as political. Also in the previous chapters the tone was mostly descriptive: the idea so far was to introduce the readers the world views I was put in touch during my data collection. Now that we share a common knowledge about how crowdfunding community see themselves into the world it is the role of this chapter to start shifting the attention to those overarching theoretical claims – that is to say, to better delineate the ground on which it makes sense to recur to Arendt when it comes to analyze crowdfunding and politics. Surely these claims cannot go further uncontested and need to be scrutinized in order to clarify its achievements and limitations – and this is the purpose of this chapter and of the next one too.

That said discussing politics through Arendt lens is _per se_ a specific analytical standpoint. The first part of this chapter discusses the boundaries brought in by this theoretical choice as well as the relevance of such perspective for the thesis. Next the purpose of the second part of the chapter is to discuss how the world view of the crowdfunding community in relation to this theoretical background. In other words to explore how the will to trace their own marginal path, the will to escape incumbent institutions demonstrated by my interviewees can be understood as a political gesture. In addition this last part of the chapter discusses questions such as the extent of the impact put forward by this political gesture, and how they relate to the ideas of common good and to the public sphere.

Arendt's oeuvre discusses politics from different standpoints – right from her first major work on totalitarianism (1951) to her later writings on the French and the American revolutions (1973). Her books and essays are also in depth analysis of central events of her time such as the Holocaust and the Eichmann judgement in Israel (a former Nazi official brought to the courts after the Second World War). These texts raised important critiques to contemporary political theory, specially when it comes to a civic and republican discussion of modernity during the mid twentieth century:

[quote]
Arendt’s thesis that political freedom can only exist in a limited space seems to mark a radical break with the liberal-democratic tradition and with its universalism of human and civil rights. […] She takes it to be a human (that is, moral) right to have civil or citizens’ rights. However, in contrast to the liberal tradition, Arendt considers such rights not as the _substance_, but only as a necessary _precondition_ of political freedom. According to her, it is a _fateful error_ to confuse the constitutionally based guarantee of basic civil rights with the constitution of political freedom (Wellmer 2000:223, emphasis in original).

In such terms her political theory focused mostly in the critique of the idea of representative democracy arguing in favor of a more participative engagement in the public sphere. In other words she claims that representative democracy has failed to offer an ongoing precondition of participation offering instead the right to participate each other year in the ballot box (1973). Critiques raised towards Arendt's theory usually call into question the importance she gave to that argument while left aside other factors that arguably would be more relevant in terms of political science and philosophy.

For instance Mouffe (2005:9) pondered that “some theorists such as Hannah Arendt envisage the political as a space of freedom and public deliberation, while others see it as a space of power, conflict and antagonism.” Arguably this critique would frame Arendt's theory as optimist and naïve when it comes to the public sphere. Arendt's argument is Aristotelian in the sense that according to her a virtuous life of free and unique citizens would lead to a civic participation in the public arena – this participation would be _per se_ considered the origin of the democracy. It is comprehensible to consider that such scenario might nurture an imaginary of politics as an organized precondition in which very polite actors employ well versed rhetoric to stand up for what they believe in. In spite of that this might not be the case; maybe the virtue of engaging in the public sphere has not come with neat debates as a requirement.footnote:[In fact there are reports of “heated arguments” in the Ancient Greek (Fine 1983).] Either way the point is that the climate of such arena was not Arendt's focus on discussing the political: instead of focusing in the tensions at stake while citizen act in public, her oeuvre focus on what leaded (or should have lead) citizens to the public arena. Her political theory in that sense is mostly introspective in relation to the citizens themselves and not predictive of how the public space should look like.

Other scholars such as Wolin (1983, 2004) would probably agree with Arendt (1973, 1998) on the statement that modern states basically have malfunctioned because what was supposed to be a public arena has become entangled up with too many private interests. In fact both scholars claim that the modern state function as a massive corporation: for her modernity has delegated the political realm to the background in favor of an inflated social realm – that is to say, states are mostly worried about provisioning for a social security system and keeping up with economic indexes (or yet: modern states are not focusing in securing ways to bring human pluralism to the foreground). For him the power multinational corporations achieved in the last decades seconds them to a political power that has entangled them into government themselves. In both scenarios a specific logic would be at place, namely the way the market mindset sets the bar for reproducing the means of human existence. However while Arendt considers human pluralism the exceptional characteristic that would justify the engagement in the public life, Wolin has a different approach to why people should care about it:

[quote]
For historically, democracy has been the means by which the many have sought access to political power in the hope that it could be used to redress their economic and social lot. The “natural” state of society contains important distinction of wealth, birth, and education that are typically extended into political power. Thus social power is translated into political power which is then used to increase social power. Democracy is the attempt of the many to reverse the natural cycle of power, to translate social weakness into political power in order to alleviate the consequences of what is not so much their condition as their lottery (Wolin 1983:3).

Once more Arendt's introspective take on political theory creates a certain dissonance. Following Wolin's thoughts democracy would have a certain teleology that is absent in her reflections on what would be the motives to assembly in public. Wolin's citizens are probably better depicted as activists with an agenda bringing them together as a group while Arendt's citizens are forged from a radical philosophical understanding of the uniqueness of each human being.

Definitively the point here it is not a matter of standing up for one or another scholar. The purpose of this debate is to take those critiques into account in order to better delineate the purpose of recurring to Arendt for this analysis. The ideas of public, social and private interests are not clear-cut throughout my interviewees reflections. On the one hand crowdfunding communities are not typical entrepreneurs looking for funding to bootstrap their unicorn startup. On the other hand neither they are typical political parties or social movements fighting for a political agenda. In fact people creating and pledging in these online campaigns might have a lot in common among them, political agenda included, however most of them would not say they are acting politically. At maximum some of them could entertain this idea of being political after being asked about it but even though they would not see themselves as actors in a public space build for political debates. Their perception about what they are doing when engaging in a multitude of proposals hosted in crowdfunding platforms is definitively not linked to more traditional institutions such as a political party or a social movement.

== The failed attempt of incumbent institutions joining crowdfunding

At this point it is worth it to note two possible dissonances. First crowdfunding is not a new mechanism and political parties  as well as social movements have already used some of these platforms for fund raising. In Brazil, for instance, eminent leaders of the Labor Party once sentenced by the Supreme Court to pay high fines launched three crowdfunding campaigns, one per person, to raise money to cover these penalties. Some of them were actually millionaires and, not necessarily related to this fact, the crimes they were sentenced for included corruption and money laundering. A judge from the Supreme Court called into question the initiative claiming that according to the Brazilian Constitution a felon could not outsource his penalty, even using an analogy that no one can serve at the prison in the behalf of the felon. He also reacted with sarcasm in a letter to a senator from the Labor Party inviting them to launch a crowdfunding campaign to refund the public treasure for the diversion of funds they were sentenced for. In spite of his rants, and in spite of some public dissatisfaction (specially from people not sympathetic to left wing politics) no further action was taken (Gazeta do Povo 2014).

Second crowdfunding is also not new for business: as mentioned by my Chinese interviewee numerous campaigns seems to be more focused in venture capital than in anything else. Also Victor, an interviewee from São Paulo who is a journalist focused on motor sports, commented on a crowdfunding campaign Caterham lanchued in late 2014. Caterham was a Formula 1 team that went bankrupt before the end of that season:

[quote]
At first sight it was bizarre, we have never seen that before in Formula 1. Definitively it was not something usual, a lot of people still overlook crowdfunding. So our point was that they [Caterham] were running a crowdfunding campaign for one purpose, which clearly was automobile racing, right? We could not see any purpose beyond that, they would race a grand prix and that is it.

Later on Victor adds that this purpose is way different from, as he put, a person who wants to have their album recorded. In fact he has not explicitly disagreed with Caterham's initiative but it was cleat that Victor was not comfortable with the purpose of their crowdfunding – or maybe the lack of purpose: “it was something without a purpose because it was elitist” he considered referring to the high values a given team has to afford in order to race in Formula 1. In spite of that as the story unfolded many fans of Caterham, of their charismatic driver Kamui Kobayashi, and of motor sports in general pledged on their campaign. Victor pondered that this engagement was surprising for him: he would not expect that such a capitalist venture would receive as much donations as they received. In the end as the campaign that asked for £2.35 million succeeded (CrowdCube 2015) Victor pondered:

[quote]
People do not see restriction in such initiative because as we know people and corporations need it, because global economy has changed. No one is actually giving money away in sponsorship as they did before and the public really feels like they can support their idols, something they like.

The cases of the sentenced politicians from Brazilian Labor Party and the case of the bankrupt Formula 1 team are possible dissonances from my interviewees as they are very specific and questionable purposes for crowdfunding. In other words that is not what people I talked with have in mind when they first consider crowdfunding. Hence by affirming that crowdfunding community is not about market entrepreneurs or political institutions I am not denying that these approaches exist. One the one hand such statement arguably overlooking these cases is a coherent interpretation of what I have heard from my interviewees. On the other hand it is also a more interesting analytical path: as this is not a quantitative investigation it seams more valuable in terms of sociology and political theory to explore social values underneath the views from my field work that would sustain such arguments. 

When it comes to this sociological consideration of crowdfunding this research needs a step back in order to clarify the theoretical arguments at stake. A possible start for that movement is to ponder on the influence of hacker culture as a radical political critique on contemporary society – and this claim might begin on the downfall of counter culture (Palmås 2006). _The Rebel Sell_ by Heath and Potter (2005) claims that the attempts by counterculture movements to “jam” capitalism have basically failed. The importance of this argument is that after the fall of socialism counterculture have been the main stream of radical political order calling into question the _status quo_ of capitalism. The most basic argument in the book is that in spite of being inspired by left wing ideas counterculture initiatives are easily incorporated in the market logic, making them innocuous in terms of promoting social change – the cover of the book exemplifies that situation in a _quasi_ comic way: a picture of a mug with the classic Che Guevara face illustration printed on it. Even if _The Rebell Sell_ is not a traditional academic writing according to Palmås (2006) the diagnosis they trace have a lot of similarities with more standard scholar arguments such as Sennett (2002) or Boltanski and Chiapello (2014), as I will discuss in the next paragraphs.

Therefore the sort of critique raised by Victor when he called into question the purpose of a crowdfunding for a Formula 1 team is a great invitation to jump in this overarching social debate. In other words the point is that in a contemporary society in which even counterculture movements can be easily embraced by capitalism (Heath and Potter 2005) there is enough material from my interviewees to discuss how crowdfunding helps them to steer away from these boundaries.

Probably my interviewees would agree with Boltanski and Chiapello (2014) when they sustain that even if capitalism has changed over the decades it is still a source of indignation. One of the reasons the authors recur to support this claim is that anyhow capitalism always ends up in oppression:

[quote]
Capitalism as [is] a source of _oppression_, inasmuch as it is opposed to the freedom, autonomy, and creativity of the human beings who are subject, under its sway, on the one hand to the domination of the market as an impersonal force … and on the other hand to the forms of subordination involved in the condition of wage-labour (Boltanski and Chiapello 2014:37, emphasis in original).

First of all as Victor pondered whether or not he was comfortable with Caterham's campaign this tension between oppression and the mixture of freedom, autonomy and creativity was at stake, specially when he compared that campaign with an hypothetical musician trying to get their first album recorded. For him the Formula 1 team was just trying to keep cars on the racing track, which is fine for Victor. However, even a passionate motor sports fan as Victor pondered that an artist trying to put his art forward, a musician trying to make money out of his personal and intimate work, was somehow more interesting for crowdfunding. Getting back to Boltanski and Chiapello (2014) this tension might be considered under set of philosophical debates dating back from the Enlightenment:

[quote]
Rooting itself in the liberal values derived from the spirit of Enlightenment, it [the social critique] denounces the falsity of an order that pretends to accomplish the modern project of liberation only the better to betray it. Far from liberating the human potentialities of autonomy, self-organization and creativity, capitalism excludes people from running their own affairs, subjects human beings to the domination of instrumental rationality, and keeps them imprisoned in an “iron cage” (Boltanski and Chiapello 2014:40).

The authors sustain the 1968 generation as well as the following ones offered a new take on capitalism: by valuing individual creativity and autonomy over hyper hierarchical structures the level of oppression put forward by capitalism would be minimized. However none of that has succeeded in making people feel freer (Boltanski and Chiapello 2014). Other authors such as Sennett (2002) hold very similar claims, downsides included:

[quote]
The apostles of the new capitalism argue that their version of … three subjects – work, talent, consumption – adds up to more freedom in modern society … My quarrel with them is not whether their version of the new is real; institutions, skills, and consumption patterns have indeed changed. My argument is that these changes have not set people free (Sennett 2002:10).

In other words maybe Victor's reluctance to match the purpose of the Formula 1 team and the purpose of the musician next door is related to the nature of what is being sustained with the fruits from the campaign in each case. Using crowdfunding as a mere fund raising mechanism for a motor sports team was not the proper perspective – and maybe that is why he later reinforced that sports fans felt they were closer to the team by supporting them, not only from the grandstands but also with financial contributions that were crucial to keep the team in the championship. Victor seemed to constantly remember the fact that a Formula 1 team is _per se_ a millionaire investment: just an year before Caterham's crowdfunding initiative NBC Sports (2013) estimated a top Formula 1 team budget was close to half a billion dollars per season. And this recollections seemed to be pretty sharp in his judgements of whether or not crowdfunding and Formula 1, in that scenario, made sense for him.

In order to conciliate and justify this tension he employed the counterexample the case of the musician – a classical example of someone “liberating the human potentialities of autonomy, self-organization and creativity” (Boltanski and Chiapello 2014:40, cited above) – to sort of justify why he cannot entertain this idea for so long. At the same time he reinforced changes on the individual level when it comes to the Formula 1 case: fans were finally feeling closer to the sport they used to see only on the television, fans being part of the sport through financial contributions, and financial contributions that seemed to be crucial to the continuation of Caterham in the championship.footnote:[Surely there were more tangible rewards: official team clothing, spare parts of the real Formula 1 car and a dinner with the drivers – depending on the amount pledged. However Victor has not brought attention to these rewards during the interview, therefore his focus was totally on the feeling of the fans instead of the official rewards.]

The main difference is that in the first case, the Formula 1 team, nothing new is actually being created. Money is being pledged as an investment for the continuation of a corporation. The same is valid for Wei's case, the Chinese I interviewed. He was disappointed after the campaign he pledged for was taken off-line as a request of a venture capitalist that has just bought the patents of the product launched in that very crowdfunding campaign. Once the real people behind the crowdfunding fades out, the interest of my interviewees faded out too. Or tu put it differently: once corporations starts to be protagonists in the crowdfunding scene, the interest of my interviewees steer to other directions.

Finally the question this research address at this point is the reason why my data sustains this very specific credo when it comes to crowdfunding. A way to see it is to go back to the attempts to oppose mainstream political and economical thought. Or in other words to try to understand my interviewees choices in a broader context of a sociological struggle framing tensions between the _status quo_ of capitalism and the feeling of freedom enjoyed by citizens in the twentieth-first century. This disappointment within the crowdfunding community can be understood in comparison to cultural changes emerged on the 1968, as mentioned. In Palmås (2006:100) words:

[quote]
Beyond the misconceptions about the year 1968, we also have to acknowledge that the late 1960s made a lasting impact on Western culture. … These few years saw the baby boomer generation mounting a furious attack on authority – and this critical approach to hierarchies has stayed with us since then (Palmås 2006:100).

This impact goes beyond a mere confrontation in terms of organizational structure of corporations and institutions in general. According to Palmås this impact is at the core of the debate on how technology is calling into question market economies – if not technology itself cultures emerged from tech groups, that is to say, hacker culture and free and open source culture. In contrast to late 1960s, 1970s and 1980s counterculture willing to jam the _modus operandi_ of capitalism, the culture inaugurated with the dot com bubble in the late 1990s is mostly dedicated to finding alternative ways in spite of capitalism. Arguably this new positioning is only possible by a new way os seeing the world – not as a motor to be jammed, but as a computer network to be explored (and arguably exploited):

[quote]
Monopolistic, bureaucratic, disciplinary, sluggish, and slightly laughable cathedrals were increasingly challenged by self-organising and intelligent bazaars of hackers, activists or consumers. While imposing and powerful, economic power structures ought not to be described as rigid motors, but as a hackable computer networks (Palmås 2006:96).

In this quote the author recurring to a famous analogy by Eric S. Raymond in his essay _The Cathedral and the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary_. This text compares top-down organizations and bottom-up communities having Linux developers community as a sort of case study for his arguments – this text is arguably a pillar for the hacker and free and open source communities. This reference when employed in Palmås argument, and specifically in this crowdfunding sociological analysis, gives a special meaning for the apparent subjective judgment sustained by Victor and Wei, for example. What is at stake is a political claim about the same structures questioned by the 1968 generation, that is to say, an attempt do be free citizens in a free world. Following Palmås the point is that instead of merely confronting the political strategies of previous generations such as counterculture, they have a new method to put their political voice forward:

[quote]
The children of the ‘99 revolution shun the … deconstruction methodologies that their parents invented. Instead they employ a hacker attitude towards reality, exploring new forms of activism and critique. A key point here is that the ‘99ers are as interested in reconstruction (of self- organised structures) as in deconstruction (of hierarchies). Drawing from organisational principles from the world of computers, they are interested in engaging in hands-on building of tangible structures (Palmås 2066:102).

In a broader perspective the point here is that even if crowdfunding have been used by incumbent institutions there are a series of caveats that should not pass unnoticed. First of all is what I have learnt directly from my interviews: their focus is on the possibility of a peer to peer relationship, so when this structure is disrupted by an uninvited institution the magic disappears for them. The importance of such distinction as well as the relationship of this distinction to the hacker culture is so great that it appeared almost literally in the words of one of my interviewees.

For instance Miguel was about to graduate from a business school, and he was entertaining the idea of starting a social entrepreneurship with a class mate. Eventually their initiative took off but during the interview he highlighted what was the trigger for that. Before quoting him it worth it to mention who is Thiago – a person Miguel will eventually cite. Thiago ended up as another co-founder of the platform Miguel was about to bootstrap. The importance of his sudden appearance is his background: a well versed software developer, a common face in the free and open source software community helping people run local, national and international events within community. That said, this is the story Miguel told me:
 
[quote]
A social business has to make profits, that is what keeps it positive. So I started to study more and more about it. The startup environment was very important, we were able to meet people running [social] business online, we were finding matches [to our ideas]. At this point the startup model made a lot of sense for us. And then came Thiago. We started to discuss our ideas and Thiago brought a lot of different references, a lot of experience from open source. And that was a better match with our ideas of social business. And that was precisely when I realized crowdfunding has impact over the very basic idea of funding, in a peer to peer level. That made a lot of sense, that totally shaped our ideas.

In addition Daniel, one of the founders of Brazilian biggest crowdfunding platform, is even clearer when it comes to the rejection of the hierarchical structures (mentioned by Palmås 2006 and Boltanski and Chiapello 2014). At a certain point during the interview he sustained that Catarse, the platform he founded, was mostly a community while Kickstarter was basically a business:
[quote]
There is also an structural aspect. Kickstarter is a corporation with a clearcut set of partners, a set of investors, a series of bureaucratic structures that make it compulsory for them to even have an [executive] board.

I have already discussed Daniel's impetus to action and how he feels bounded by bureaucratic structures in the previous chapter. Actually the whole idea of autonomy explored there is a set of strategies to overcome decision making processes that seems to put people – understood here as creative and autonomous individuals — in the background. Therefore this world view of the crowdfunding community is not merely an important part of their positioning in the world but also fits with a very specific stream of radical political thought calling into question core incumbent institutions sustaining the market economy: namely the type of structures criticized since the 1968 social movements.

Interestingly if this sounds like a kind of confrontational left wing an anti-capitalism or anti-corporation stunt, crowdfunding community also claims they do not have any expectation that the government is a possible alternative, opposing even regulation in most cases — and again this is the basis of their understanding of autonomy discussed in the previous chapter. In other words while calling capitalism into question they seems to believe in a radical sort of freedom that fits a radical right wing stunt: anti-state, anti-regulation or, to put it differently, defending every kind of negative freedom (Berlin 1999) that might step in their strategies to make a living while doing what they believe in. If Wollin and Arendt (as mentioned in the opening of this chapter) have their motives to justify a blurred thin line separating the way government and corporations works nowadays, the crowdfunding community seems to agree with the scholar. For my interviewees both structures, the government and the corporation, suffer from the same weakness: they are unduly bureaucratic and this bureaucracy invariably obfuscates the real people underneath these structures. To put it simple decisions are always made following guidelines and regulations, always focused in predetermined targets (usually money and power). Individual uniqueness, creativity and autonomy are not a priority — even when these structures try to appropriate the crowdfunding mechanism.

== Political crowdfunding

When it comes to the modern states Arendt raises two sorts of critiques. As mentioned first there is more overarching critique when she denounces the lack of a public realm – and consequentially the lack of action in a society basically functioning merely around labor and work. Second there is a more structural critique when she claims that the possibility of action was effectively displaced to a couple of seconds when voting in a ballot box each other year (Arendt 1973). Hence understaing the concept action is crucial to dialogue with both critiques.

Therefore this last block of the present chapter better delineates the concept of action to trace parallels with the world view sustained by the crowdfunding community and what Arendt expected in terms of the political realm. In spite of that the intention is not to sustain that these parallels are the only way to sociologically comprehend the position of crowdfunding communities — on the opposite: the following chapter has a competing and no exclusive standpoint to take part at this same debate. The idea is offer a framework capable of accommodating tensions in a meaningful sociological perspective. 

=== Creating a new public realm

First there is the completely absence of a real public realm. For her (1998) the private realm, that is to say, the space of intimacy, of the household is place for labor – a kind of activity that is focused on the most basic human needs in terms of sustainability of us all as a race (putting bread on the table is a way to summarize it). The private realm is also the place in which we work creating tools to make labor easier so basically our private lives comprehends labor and work in these terms. In ancient Greek there was also the public realm, an exclusive place for what she called action, or “a space for the doers of great deeds and speaker of great words” as Achilles would put it.footnote:[“The hero, the ‘doer of great deeds and speaker of great words,’ as Achilles was called, needed the poet – not the prophet, but the seer – whose divine gift sees in the past what is worth telling in the present and the future. This pre-polis past of Greece is the source of the Greek political vocabulary that still survives in all European languages” (Arendt 2005:45).] Action is the only way through which human essence and uniqueness would strive for immortality – or in other words the proper realm for citizens to fight for what they believe (instead of simply fighting for putting bread on the table).

The public arena in this tradition is the place for action and, in the case of ancient Greek, was also the core of democracy, of the state. However for Arendt (2005:47) this tradition is lost and nowadays modern states have other principles at their core:

[quote]
It was never even considered by our tradition of political thought, which began after the ideal of the hero, the ‘doer of great deeds and speaker of great words,’ had given way to that of the statesman (_sic_) as lawgiver, whose function was not to act but to impose permanent rules on the changing circumstances and unstable affairs of acting men (_sic_).

For her this radical change is the public realm actually put an end on that space as it used to be. In her words what he have now is a social realm, a mimic of the public realm in which the logic is not action but a massive bookkeeping logic: the public space instead of being “a space for the doers of great deeds and speaker of great words” ended up as a immense support for what we do in our private space, that is to say, to support labor and work (Arendt 1998). Following this argument politicians in office and in campaign hardly ever are seen as “doers of great deeds and speaker of great words” but most of the time are bureaucratic leaders whose actions are signing bills to keep economy growing and, consequentially, providing jobs and a welfare to a giant private sphere, whether it is the country, the state or municipality (let aside continental blocks such as the European Union).

This focus, according to my interviewees, is playing in favor of the _status quo_ of these incumbent institutions. Thus they feel like politics and politicians in general are not helping them to empower individual creativity and autonomy. The result of Arendt's argument together with my interviewees skeptical take on politics is a overarching disavowal to what we consider to be our public realm (or social realm, as Arendt would put it). In the middle of my interview with Maria, the Romanian girl who crowdfunded the tuition for her master degree, she was commenting on her disapproval of politics and I asked if are there better, or at least more honest politicians. She replied with another question: “Would they still be in politics?”

In spite of corruption and other arguably illegal and immoral aspects of politics the point is that the structure of the state itself is the target of protesters such as the ones form 1968 – and as we discussed they are strongly related to the dot com bubble, hacker and free and open software cultures (Palmås 2006). Together with the values of these groups is the will of crowdfunding communities to empower individual creativity and autonomy. And this will, my interviewees would argue, are not contemplated by politicians:

[quote]
Then you realise politics is so much associated with financial growth and I just haven't heard of a political discourse that is honest and humane in a long time. [A discourse that] can be a good model for people, that actually they [politicians] should represent. Thus I think that's why I'm just disillusioned … we putting power in the hands of people that usually are not doing their job which is representing the bigger mass of people's interests (Maria).  

Maria's quote, if understood in the context of the autonomy discussed earlier, shows how distant nowadays structures of power are from the crowdfunding communities. Also the debate so far has shown that part of what Maria cited as “the bigger mass of people's interests” is a detachment from and a disavowal for this very same power structures. Yet if crowdfunding community's will is more autonomy, the fit with Arendt's description of action is very appealing: first of all, as discussed in the chapter on the resignifiation of money, labor and work are put aside, next the focus on autonomy is put on the foreground to allow them to be “doers of great deeds and speaker of great words.”

Earlier on this chapter I mentioned that according to Arendt (1998) action is the only way through which humans can strive for immortality. For her merely mortals human beings can attempt to last for ever – even as mortals – through actions. Her argument sustaining this philosophical provocation  opposes mortal humans with immortal gods – and specially gods that are _per se_ doers of great deeds. Therefore action is the unique way through which worldliness deeds can confer a human been a status similar to the divine status: doer of deeds that last forever. For her this is the idea of _vita activa_:

[quote]
No matter how concerned a thinker may be with eternity, the moment he sits down to write down his thoughts he cease to be concerned primarily with eternity and shift his attention to leaving some trace of them. He has entered the _vita activa_ and chosen its way to performance and potential immortality (Arendt 1998:20).

_Vita activa_ is “a life devoted to public-political matters” (Arendt 1998:12) and therefore the core of Arendt's concept of action. At this point it may be simpler to discuss the distinction between labor, work and action. The point is not a mere classification in which the fulfilling of the most basic needs  is labeled labor, the employment of skills to make labor easier is labeled work and great deeds are labeled action. It neither is a mere division in terms of private and public realm. Even is those claims are valid, they are too simplistic for the comprehension of action.

The concept of action encompasses a important dimension of human condition itself. First of all it has to do with human uniqueness, that is to say, to the fact that action only makes sense as each human being is essentially different from any other human being. If humans were equal action would not be necessary but more radically probably this differentiation of human from nature would not exist either – in fact Arendt (1998:46) claims this one-ness is the “specimen of the animal species man-kind” (_sic_). Second this kind of activities focused in deeds and not in labor and work is also intrinsically human:

[quote]
The plurality of men (_sic_) … constitutes the political realm. It does so, first, in the sense that no human ever _exists_ in the singular, which gives action and speech their specifically political significance, since they are the only activities which not only are affected by the fact of plurality, as are all human activities, but are altogether unimaginable apart from it. It is possible to conceive of a human world in the sense of a man-made (_sic_) artifice erected on the earth under the condition of the oneness of man … But an acting and speaking being existing in the singular cannot possibly be conceived (Arendt 2005:63, emphasis on original).

Therefore the crowdfunding communities do not seem to be excited with larger corporations and politicians joining their movement. What might me at stake is the lack of human spontaneity, the lack of this intrinsic uniqueness my interviewees miss in the logic of the decision making and valuing processes upheld by corporations and bureaucracies. Another way to put it is that my interviewees are looking to relate to human beings, not institutions: institutions, as Arendt claims, are locked in the private realm and arguably the crowdfunding community is sick of it. 

Another way to sustain the disavowal for a more formal and less spontaneous human characteristic in this space is to recur to a quantitative linguistic research suggesting that low expressiveness is a typical trace of scam on crowdfunding projects: “scammers deliberately try to deceive people by intentionally providing less information and writing more carefully, and less informally” (Shafqat _et al_ 2016:99).footnote:[Their analysis focused on metrics such as non-immediacy (verbs in the first person), expressivity (ratio of adjevtives and adverbs to nouns and verbs) and informality (ratio of misspelled words). They conclude “expressiveness of the language of scammers is low, due to over-control and less conviction about what is being said” (Shafqat _et al_ 2016:99)] The conclusion is drawn from the fact that when comparing scam and non-scam projects on crowdfunding, scammers tend to use less words, specially verbs and adverbs and, at the same time, showing less spelling errors. On the one hand there is no data on the success or failure in terms of the funds raised by scammers and non-scammers, but on the other hand researches like that reinforce that the formality that is typical in the corporation and political worlds are not the rule in crowdfunding.

Juliana is a regular supporter of crowdfunding campaigns specially when they are related to causes she believes in like vegetarianism and cycling. She also support local musicians and artistic projects. As a cyclist she is also into projects proposing new design of bike tools and gadgets – apparels she sees as functional in a pragmatic way (such as plugging them to her bike and using it in her everyday life) as well as political (making biking easier is a political claim in urban mobility debates). She summarized her motivations to join crowdfunding campaigns ultimately as a progressive political action, or yet a political provocation:

[quote]
Crowdfunding platforms enables a lot of actions that are constrained in our everyday life, actions related to autonomy and empowerment. I supported a lot of activism related projects … I feel like for the more reactionary population in town [empowering activism] might sound insulting. Thus I believe promoting activism is really a thing for me. I see many projects I supported that way.

She literally said her pledges in crowdfunding campaign are empowering in a political sense — even when buying a gadget. For her the source of this empowerment lies in the fact that the pledges and projects make her political views tangible in the world. It is her way to be political in modern life. This phenomenon is not new: for instance Giddens (1991) argues that nowadays the notion of self-identity is not given _a priori_ by the institutions in a given individual trajectory; on the contrary people are constantly building a narrative to support their desired self-identity. From sociological streams like that one can comprehend even consumption as a political act (Micheletti 2003) – what would be an unusual diversion for ancient Greek and for Arendt. However the point here is not to discuss if a commercial relationship concerns the private or the public realm but to describe the world view from which my interviewees consider crowdfunding. For them it is definitively not about a marketplace: that is why they claim an specific relation to money, that is why they focus on autonomy for humans to be humans in the sense of spontaneity, authenticity and, as Arendt would put, uniqueness — meaning that different citizens are putting their unique and intimate ideas forward in a democratic arena, seeking for support to be able to achieve great deeds.

The next section draws from that argument of crowdfunding as action to describe situations in which my interviewees perceive themselves as actors in modern societies, even if the representative democracies seems do discourage this sort of action outside organized movements or in elections periods (Arendt 1973). As discussed earlier the tone is not of confronting the _status quo_ of government and corporations, but of navigating on the margins of these institutions. In other words it is about allowing people to have voice not against these institutions, but in spite of them.

=== Empowering action

Just as Juliana and many other interviewees Talite seems to engage in crowdfunding for purposes beyond the usual perks. She is a regular crowdfunding supporter keeping the habit of browsing platforms such as Kickstarter every month to check up new and interesting projects to support. She does not seem to be into provocations as Juliana would probably be: even an earlier adopter of different technologies (such as social media or streaming services) when the innovation is illegal or in a grey area Talita prefers to wait for government to explicitly regulate the newcomers before jumping in. She claims she has no illegal downloaded MP3 (opting instead to buy them on Google Play store) and she just started to ride Uber when São Paulo mayor signed a bill regulating the activity of the startup in the city.  In a similar argument as Juliana, she told she is not into crowdfunding merely because of gadgets:

[quote]
Kickstarter is not a shopping mall. Surely the rewards are cool, I do love getting them. When one of them arrives it makes me super happy. But I do not support [crowdfunding projects] necessarily having these rewards in mind. I support [them] because I feel like saying “congratulations, dude. You have got a great idea, take 10 dollars. Or 50. Whatever.” It really depends on what they have created. For me it works as a donation, it is the same as when I donate to the Red Cross or to the Médecins Sans Frontières: I open Kickstarter looking for cool projects and give money so the people [involved in these projects] can keep on thinking cool stuff.

Juliana and Talita's purposes represent pretty well other people I talked to in the crowdfunding community: many agree that engaging in such projects is a way to put ideas forward. And for them that was the main purpose in crowdfunding.

Lisandro is a Brazilian that has contributed to many campaigns for board games, amateur literature and other artistic projects. He told me his wife mocks him when she catches him on a crowdfunding website: “go play patron.” In spite of the playful tone she employs, sounding mostly as a joke, he seems to agree with her point of view: “In fact I am playing the patron, I am allowing things to happen. Things that nobody else wanted to happen, things no one actually knew or expected to happen.” When I interviewed him he draw a clearcut line splitting two kind of projects: on the on hand he labeled “projects” the ones that basically offered an product as a reward — sometimes he refers to these as “kickstarters” whether or not the website itself was indeed Kickstarter. On the other had he had labeled “authors” campaigns he pledged independent of a possible reward – that is to say, he was supporting the author, the creator of a project.

[quote]
I see it as a way to support an author, one is not only supporting a specific project. The funny thing is that most of the times I get frustrated with kickstarters … than in projects that I am in fact supporting the author. Thus most of the times I am supporting an author I end up overlooking a eventual sin they might commit. That is to say I do not stop believing that what they are doing, their action. This is what really matters. This has to go on because this is a way to achieve things that normally would not happen.

An “eventual sin” in that context was a project that failed to deliver the promised reward. That as not so disappointing for him because in such cases the focus of his support was in the action, in the idea the creator had, not in a material good Lisandro was expecting. In a similar tone, Juliana told me:

[quote]
It would break trust if they [a given project] ended up not delivering the reward … But I would be fine if they offer an explanation, because this could give birth to a more affective tie between us. Usually this is the case of projects I feel strongly connected with: maybe they [the creators] are my friends, or they are fighting for a cause I believe in. So there is already this sort of strong tie. If it is not a proper cause, at least it is something that really affects me, something I care about … So what I expect from such projects is that they succeed, I hope they can achieve what they are looking for. I would like to get my reward, to use the product, to see if it really works… and if it does I would probably recommend it all around. But if they fail to deliver it that would not make me stop believing in crowdfunding, that would not make me curse them or anything like that.

Such statements together with the dismissal of formal institutions in the crowdfunding arena are typical markers of a cultural shift. For instance Pålmas (2006) argued that this is the case of the 1968 generation: they have not overthrown any institution or specific political agenda but the effect of that political agitation “made lasting impact on Western culture.” According to him this shift it was “a furious attack on authority – and this critical approach to hierarchies has stayed with us since then” — in other words “people simply did not see the world in the same way after this period” (Pålmas 2006:100-1). Until that point all the anti-hierarchical, anti-bureaucratic, anti-corporation and anti-government discourse held by the crowdfunding community might have been seen as a cultural shift as well — or even as a mere continuation of the 1968 one.

To be clear the point is that crowdfunding communities have not overthrown any corporation or government. They have not pushed any multinational or political party to bankruptcy or shaken any incumbent market or political process. And probably they would never achieve any of this. As argued before that is not their target; naïvely they prefer to run in the margins minding their own business while keeping institutions away from their everyday life. To Pålmas (2006) the first generation of the twentieth first century would probably not follow the step of twentieth century. He uses the analogy of seeing the world as a motor that even if it could be jammed would still follow a more specific set of rules. The alternative emerged together with the emergence of informatics and of the internet is seeing the world as an open computer network to be hacked. To illustrate this argument he cites Muhammad Yunus as an example, a Bangladeshi man awarded with a Nobel Peace Prize for the creation of micro credit:

[quote]
Rather than a purely social movement, microcredit is a socio-technical movement, enrolling humans as well as non-humans (such as financial instruments). Rather than a symbolic event (a display of public dissent; an event that throws gravel into the societal machinery) it is a tangible, techno-cultural innovation. Rather than seeing the system (the world of finance and banking) as a motor that follows pre-defined _modus operandi_, Yunus saw the economy as an open structure (or, if you will, an assemblage), whose mode of operation can change if new components are plugged into it. Most crucially, Yunus was naïve enough to develop innovations for this system, even though the essentialist Natural laws that are said to govern the system would suggest that such hacks are impossible (Pålmas 2006:83).

If seen through that lens the crowdfunding community focus on action, on enabling things that would not be backed by incumbent institutions, is a way to address problems of the world with a hacker mindset — or, in Pålmas analogy, to see society as an open computer network instead of a motor. Following this argument the tone of the projects put forward within crowdfunding communities is not a new marketplace trying adapt itself to the meet the expectations of traditional market transactions. In fact it is the opposite, it consists of typical market transactions hacked to work according to a completely different logic. This new logic resignifies money, praises autonomy over bureaucracy and hierarchy, and allow individuals to have a political voice independent from more traditional political institutions.

By these means Arendt's conception of action together with this hacker take on the structures of power of modern societies properly describes the crowdfunding community objectives: by downplaying any institution that might shadow individual wills and dreams the idea is to empower humans to go public about their projects. These projects have to tangible: campaigns requires a minimum budget and he realization depends on the total raised. To sum up the idea is to put ideas online and end up with deeds to reassure the trust between creators and backer.

Is is important to note that Arendt view of action was always tied to a formal rhetoric in the public arena (1998). That might not be the case in crowdfunding specially when a very attentive communication might raise suspicions of scam (Shafqat _et al_ 2016). In other words it seems that a personal tone reinforcing the individuality rather than the formal aspect of the presentation is preferred in this new political space. However such change can be a signal of how far hierarchical and bureaucratic organizations have gone in annihilating action from every single aspect of human life during the twentieth century. As Boltanski and Chiapello (2005), Heath and Potter (2005) and Pålmas (2006) argued since 1968 the world is calling this bureaucratization into questioning with different levels of success and of pragmatism. crowdfunding is, therefore, playing this very same game. crowdfunding mechanism in this scenario is a mix of showcase of ideas and fund raising: arguably powerful recipe to empower people to action – or, in Arandt's sense, a receipt to empower doers of great deeds. The greatness of the deeds comes from the uniqueness of each human being involved in the process: whether it is the creator that step up into the public arena of the crowdfunding platforms with their own ideas, or the supporters who feel part of the realisation of the deeds because they allowed the creators to succeed (spreading the world, discussing and, mainly, donating money for the endeavor).

Furthermore nowadays the possibility of being political active in spite of the formal political structure is _per se_ a bold claim. As discussed, Arendt (1973) claims modern democracies offer citizens too much freedom in their private lives but very rare opportunities to actually exercise their free will in politics. Yet when they do options are limited by a predefined menu put forwarded by organized political parties (Sniderman and Bullock 2004). On top of that there is the power conferred to money, mainly in the case of corporations and lobby (Wollin 2004). Crowdfunding motivations represented by the world views of my interviewees seems to clearly establish a dialogue with all these social debates, it is their way to to step in this debate and to addressing issued in power structures of modern societies.

'''

The title of this chapter was already a disclaimer for the reader: if there were harsh critiques to crowdfunding communities they would be saved for another opportunity. Also the promise of the title signaled that there is a important political aspect in crowdfunding that should not be dismissed. In terms of social theory there are arguments and stories supporting that my interviewees are engaging with major debates regarding incumbent institutions such as the market and the government. Also the arguments so far hopefully sustains that in different degrees of consciousness my interviewees are dialoguing with power structures as political actors.

Yet the title of this chapter also announces a certain optimism that the reader might align with an utopian view of the internet and, generally speaking, of technology as a whole. First I must clarify that this optimism is sound and clear in most of my interviews – even people that see crowdfunding as a kind of intermediary step to a uncertain future believe that by now crowdfunding is powerful in putting forward ideas that would probably be left aside by mainstream economic and political thought.

In sum my interviewees are pretty excited about becoming protagonists through crowdfunding. For instance Lisandro even joked that if until the 1990s people would struggle for their “15 minutes of fame” nowadays people will de “famous dos 15 people” instead. In spite of that surely there are also critiques and boundaries on crowdfunding pointed out by my interviewees. Next chapter departs from them to debate possible downsides of this sort of politics put forward by crowdfunding communities. 
