= A new realm to empower action
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
In all of us there is a dimension of obligation, constraint, necessity or compulsion which is external, and there is also a share of freedom, of creativity which Hannah Arendt places under the label of action (Caillé 2009:112).


In the last chapters, I drew on Arendt's ideas about human action in order to explore the everyday decisions of my interview informants. Also, in the previous chapters the focus was on introducing readers to the world views I discovered during my data collection. Now that we share a common knowledge about how the crowd funding community see themselves within the world it is the role of this chapter to start shifting the attention to those overarching theoretical claims -- that is to say, to better delineate the ground on which it makes sense to refer to Arendt when it comes to analyzing crowd funding and politics. The purpose of this and the following chapter is to analyze and scrutinize the claims and limitations of the responses of my informants.

That said, discussing politics through Arendt's lens is _per se_ a specific analytical standpoint. The first part of this chapter discusses the boundaries inherent in this theoretical choice as well as the relevance of such a perspective for the thesis. Next, the purpose of the second part of the chapter is to discuss the world view of the crowd funding community in relation to this theoretical background. In other words, to explore how the will to trace their own marginal path, the will to escape incumbent institutions demonstrated by my interviewees, can be understood as a political gesture. In addition, this last part of the chapter discusses questions such as the extent of the impact put forward by this political gesture, and how they relate to the ideas of common good and to the public sphere.

Arendt's oeuvre discusses politics from different standpoints -- right from her first major work on totalitarianism (1951) to her later writings on the French and the American revolutions (1973). Her books and essays are also in-depth analyses of central events of her time such as the Holocaust and the Eichmann judgement in Israel (a former Nazi official brought to the courts after the Second World War). These texts raised important critiques to contemporary political theory, especially when it comes to a civic and republican discussion of modernity during the mid-twentieth century:

[quote]
Arendt's thesis that political freedom can only exist in a limited space seems to mark a radical break with the liberal-democratic tradition and with its universalism of human and civil rights. […] She takes it to be a human (that is, moral) right to have civil or citizens' rights. However, in contrast to the liberal tradition, Arendt considers such rights not as the _substance_, but only as a necessary _precondition_ of political freedom. According to her, it is a _fateful error_ to confuse the constitutionally based guarantee of basic civil rights with the constitution of political freedom (Wellmer 2000:223, emphasis in original).

In such terms her political theory focused mostly on the critique of the idea of representative democracy, arguing in favor of a more participative engagement in the public sphere. In other words, she claims that representative democracy has failed to offer an ongoing precondition of participation, offering instead the right to participate every other year in the ballot box (1973). Critiques raised towards Arendt's theory usually call into question the importance she gave to that argument while leaving aside other factors that arguably would be more relevant in terms of political science and philosophy.

For instance, Mouffe (2005:9) pondered that "some theorists such as Hannah Arendt envisage the political as a space of freedom and public deliberation, while others see it as a space of power, conflict and antagonism." This critique frames Arendt's theory as optimistic and naïve when it comes to the public sphere, but this is a simplification of her work. Arendt's argument is Aristotelian in the sense that, according to her, a virtuous life of free and unique citizens would lead to a civic participation in the public arena -- this participation would be _per se_ considering the origin of the democracy. It is comprehensible to consider that such a scenario might nurture an imaginary of politics as an organized precondition in which very polite actors employ well-versed rhetoric to stand up for what they believe in. In spite of that, this might not be the case; maybe the virtue of engaging in the public sphere has not come with neat debates as a requirement.footnote:[In fact, there are reports of "heated arguments" in the Ancient Greek (Fine 1983).] Either way the point is that the climate of such an arena was not Arendt's focus on discussing the political: instead of focusing on the tensions at stake while citizens act in public, her oeuvre focuses on what led (or should have lead) citizens into the public arena. Her political theory in that sense is mostly introspective in relation to the citizens themselves and not predictive of how the public space should look.

Other scholars such as Wolin (1983, 2004) would probably agree with Arendt (1973, 1998) on the statement that modern states have basically malfunctioned because what was supposed to be a public arena has become entangled with too many private interests. In fact, both scholars claim that the modern state functions as a massive corporation: for Arendt modernity has delegated the political realm to the background in favor of an inflated social realm -- that is to say, states are mostly worried about provisioning for a social security system and keeping up with economic indexes (as yet, modern states are not focusing on securing ways to bring human pluralism to the foreground). For Wolin the power that multinational corporations have achieved in the last decades seconds them to a political power that has entangled them into government themselves. In both scenarios a specific logic would be in place, namely the way the market mindset sets the bar for reproducing the means of human existence. However, while Arendt considers human pluralism the exceptional characteristic that would justify the engagement in public life, Wolin has a different approach as to why people should care about it:

[quote]
For historically, democracy has been the means by which the many have sought access to political power in the hope that it could be used to redress their economic and social lot. The "natural" state of society contains important distinction of wealth, birth, and education that are typically extended into political power. Thus, social power is translated into political power which is then used to increase social power. Democracy is the attempt of the many to reverse the natural cycle of power, to translate social weakness into political power in order to alleviate the consequences of what is not so much their condition as their lottery (Wolin 1983:3).

Once more, Arendt's introspective take on political theory creates a certain dissonance. Following Wolin's thoughts, democracy would have a certain teleology that is absent in her reflections on what would be the motives to assemble in public. Wolin's citizens are probably better depicted as activists with an agenda bringing them together as a group, while Arendt's citizens are forged from a radical philosophical understanding of the uniqueness of each human being.

Definitively, the point here is not a matter of standing up for one or another scholar. The purpose of this debate is to take those critiques into account in order to better delineate the purpose of referring to Arendt for this analysis. The ideas of public, social and private interests are not clear-cut throughout my interviewees' reflections. On the one hand, crowd funding communities are not typical entrepreneurs looking for funding to bootstrap their unicorn startup. On the other hand, neither are they typical political parties or social movements fighting for a political agenda. In fact, people creating and pledging in these online campaigns might have a lot in common, political agenda included, however, most of them would not say they are acting politically. At maximum some of them could entertain this idea of being political after being asked about it but even then they would not see themselves as actors in a public space built for political debates. Their perception about what they are doing when engaging in a multitude of proposals hosted in crowd funding platforms is definitively not linked to more traditional institutions such as a political party or a social movement.

== The failed attempt of incumbent institutions joining crowd funding

At this point it is worth noting two possible dissonances. First, crowd funding is not a new mechanism and political parties  as well as social movements have already used some of these platforms for fundraising. In Brazil, for instance, eminent leaders of the Labor Party once sentenced by the Supreme Court to pay high fines launched three crowd funding campaigns, one per person, to raise money to cover these penalties. Some of them were actually millionaires and, not necessarily related to this fact, the crimes they were sentenced for included corruption and money laundering. A judge from the Supreme Court called into question the initiative, claiming that according to the Brazilian Constitution a felon could not outsource his penalty, even using an analogy that no one can serve at the prison on the behalf of the felon. He also reacted with sarcasm in a letter to a senator from the Labor Party inviting them to launch a crowd funding campaign to refund the public treasury for the diversion of the funds they were sentenced for. In spite of his rants and in spite of some public dissatisfaction (especially from people not sympathetic to left wing politics) no further action was taken (Gazeta do Povo 2014).

Second, crowd funding is also not new for business: as mentioned by my Chinese interviewee, numerous campaigns seem to be more focused on venture capital than on anything else. Also, Victor, an interviewee from São Paulo who is a journalist focused on motor sports, commented on a crowd funding campaign Caterham launched in late 2014. Caterham was a Formula 1 team that went bankrupt before the end of that season:

[quote]
At first sight it was bizarre, we have never seen that before in Formula 1. Definitively it was not something usual, a lot of people still overlook crowd funding. So our point was that they [Caterham] were running a crowd funding campaign for one purpose, which clearly was automobile racing, right? We could not see any purpose beyond that, they would race a grand prix and that is it.

Later on, Victor adds that this purpose is way different from, as he put it, a person who wants to have their album recorded. In fact, he has not explicitly disagreed with Caterham's initiative but it was clear that Victor was not comfortable with the purpose of their crowd funding -- or maybe the lack of purpose: "it was something without a purpose because it was elitist" he considered, referring to the high values a given team has to afford in order to race in Formula 1. In spite of that, as the story unfolded, many fans of Caterham, of their charismatic driver Kamui Kobayashi, and of motor sports in general, pledged on their campaign. Victor pondered that this engagement was surprising to him: he would not expect that such a capitalist venture would receive as many donations as they received. In the end the campaign succeeded in raising £2.35 million (CrowdCube 2015). Victor pondered this:

[quote]
People do not see restriction in such an initiative because as we know people and corporations need it, because global economy has changed. No one is actually giving money away in sponsorship as they did before, and the public really feels like they can support their idols, something they like.

The cases of the sentenced politicians from the Brazilian Labor Party and the case of the bankrupt Formula 1 team are possible dissonances from my interviewees' ideas as they are very specific and questionable purposes for crowd funding. In other words, that is not what people I spoke to have in mind when they first consider crowd funding. Hence, by affirming that the crowd funding community is not about market entrepreneurs or political institutions I am not denying that these approaches exist. One the one hand, such a statement arguably overlooking these cases is a coherent interpretation of what I have heard from my interviewees. On the other hand, it is also a more interesting analytical path: as this is not a quantitative investigation it seems more valuable in terms of sociology and political theory to explore social values underlying the views from my field work that would sustain such arguments.

When it comes to the sociological consideration of crowd funding, this research needs the creation of a type of distance in order to clarify the theoretical arguments at stake. A possible beginning of that clarification is to ponder on the influence of hacker culture as a radical political critique on contemporary society -- and this claim might begin on the downfall of counter culture (Palmås 2006). _The Rebel Sell_ by Heath and Potter (2005) claims that the attempts by counterculture movements to "jam" capitalism have basically failed. The importance of this argument is that after the fall of socialism, counterculture has been the main stream of radical political order calling into question the _status quo_ of capitalism. The most basic argument in the book is that in spite of being inspired by left wing ideas, counterculture initiatives are easily incorporated in the market logic, making them innocuous in terms of promoting social change -- the cover of the book exemplifies that situation in a _quasi_-comic way: a picture of a mug with the classic Che Guevara face illustration printed on it. Even if _The Rebel Sell_ is not traditional academic writing according to Palmås (2006), the diagnosis they trace has a lot of similarities with more standard scholarly arguments such as Sennett (2002) or Boltanski and Chiapello (2011), as I will discuss in the next paragraphs.

Therefore, the sort of critique raised by Victor when he called into question the purpose of a crowd funding for a Formula 1 team is a great invitation to jump into this overarching social debate. In other words, the point is that in a contemporary society in which even counterculture movements can be easily embraced by capitalism (Heath and Potter 2005), there is enough material from my interviewees to discuss how crowd funding helps them to steer away from these boundaries.

It would appear that my interviewees would agree with Boltanski and Chiapello (2011) when they sustain that even if capitalism has changed over the decades it is still a source of indignation. One of the reasons the authors mention to support this claim is that anyhow capitalism always ends up in oppression:

[quote]
Capitalism as [is] a source of _oppression_, inasmuch as it is opposed to the freedom, autonomy, and creativity of the human beings who are subject, under its sway, on the one hand to the domination of the market as an impersonal force … and on the other hand to the forms of subordination involved in the condition of wage-labour (Boltanski and Chiapello 2011:86, emphasis in original).

First of all, as Victor pondered whether or not he was comfortable with Caterham's campaign, this tension between oppression and the mixture of freedom, autonomy and creativity was at stake, especially when he compared that campaign with a hypothetical musician trying to get his/her first album recorded. For him the Formula 1 team was just trying to keep cars on the racing track, which is fine for Victor. However, even a passionate motor sports fan such as Victor pondered that an artist trying to put his art forward, a musician trying to make money out of his personal and intimate work, was somehow more interesting for crowd funding. Getting back to Boltanski and Chiapello (2011), this tension might be considered a under set of philosophical debates dating back to the Enlightenment:

[quote]
Rooting itself in the liberal values derived from the spirit of Enlightenment, it [the social critique] denounces the falsity of an order that pretends to accomplish the modern project of liberation only the better to betray it. Far from liberating the human potentialities of autonomy, self-organization and creativity, capitalism excludes people from running their own affairs, subjects human beings to the domination of instrumental rationality, and keeps them imprisoned in an "iron cage" (Boltanski and Chiapello 2011:91).

The authors maintain that the 1968 generation, as well as the following ones offered a new take on capitalism: by valuing individual creativity and autonomy over hyper hierarchical structures, the level of oppression put forward by capitalism would be minimized. However, none of that has succeeded in making people feel freer (Boltanski and Chiapello 2011). Other authors such as Sennett (2002) hold very similar claims, downsides included:

[quote]
The apostles of the new capitalism argue that their version of … three subjects -- work, talent, consumption -- adds up to more freedom in modern society … My quarrel with them is not whether their version of the new is real; institutions, skills, and consumption patterns have indeed changed. My argument is that these changes have not set people free (Sennett 2002:10).

In other words, maybe Victor's reluctance to match the purpose of the Formula 1 team and the purpose of the musician next door is related to the nature of what is being sustained with the fruits from the campaign in each case. Using crowd funding as a mere fund raising mechanism for a motor sports team was not the proper perspective -- and maybe that is why he later reinforced that sports fans felt they were closer to the team by supporting them, not only from the grandstands but also with financial contributions that were crucial to keeping the team in the championship. Victor seemed to constantly remember the fact that a Formula 1 team is _per se_ a millionaire investment: just a year before Caterham's crowd funding initiative, NBC Sports (2013) estimated a top Formula 1 team budget was close to half a billion dollars per season. And these recollections seemed to be pretty sharp in his judgements of whether or not crowd funding and Formula 1, in that scenario, made sense for him.

In order to conciliate and justify this tension, he employed the counterexample of the case of the musician -- a classical example of someone "liberating the human potentialities of autonomy, self-organization and creativity" (Boltanski and Chiapello 2011:91, cited above) -- to sort of justify why he cannot entertain this idea for long. At the same time, he reinforced changes on the individual level when it comes to the Formula 1 case: fans were finally feeling closer to the sport they used to see only on the television, fans being part of the sport through financial contributions, and financial contributions that seemed to be crucial to the continuation of Caterham in the championship.footnote:[Surely there were more tangible rewards: official team clothing, spare parts of the real Formula 1 car and a dinner with the drivers -- depending on the amount pledged. However Victor has not brought attention to these rewards during the interview, therefore his focus was totally on the feeling of the fans instead of the official rewards.]

The main difference is that in the first case, that of the Formula 1 team, nothing new is actually being created. Money is being pledged as an investment for the continuation of a corporation. The same is valid for Wei's case, the Chinese respondent I interviewed. He was disappointed after the campaign he pledged for was taken off-line at the request of a venture capitalist that had just bought the patents of the product launched in that same crowd funding campaign. Once the real people behind the crowd funding faded out, the interest of my interviewees faded out too. Or to put it differently, once corporations begins to be protagonists in the crowd funding scene, the interest of my interviewees steered towards other directions.

Finally, the question this research addresses at this point is the reason why my data sustains this very specific credo when it comes to crowd funding. A way to see it is to go back to the attempts to oppose mainstream political and economic thought, or, in other words, to try to understand my interviewees' choices in a broader context of a sociological struggle framing tensions between the _status quo_ of capitalism and the feeling of freedom enjoyed by citizens in the twentieth-first century. This disappointment within the crowd funding community can be understood in comparison to cultural changes which emerged in 1968, as mentioned previously. Palmås (2006:100) argues:

[quote]
Beyond the misconceptions about the year 1968, we also have to acknowledge that the late 1960s made a lasting impact on Western culture. … These few years saw the baby boomer generation mounting a furious attack on authority -- and this critical approach to hierarchies has stayed with us since then (Palmås 2006:100).

This impact goes beyond a mere confrontation in terms of the organizational structure of corporations and institutions in general. According to Palmås, this impact is at the core of the debate on how technology is calling into question market economies -- if not technology itself. Such cultures emerged from tech groups, that is to say, hacker culture and free and open source culture. In contrast to the late 1960s, 1970s and 1980s counterculture, which was willing to jam the _modus operandi_ of capitalism, the culture inaugurated with the dot com bubble in the late 1990s and is mostly dedicated to finding alternative ways in spite of capitalism. Arguably, this new positioning is only possible via a new way of seeing the world -- not as a motor to be jammed, but as a computer network to be explored (and arguably exploited):

[quote]
Monopolistic, bureaucratic, disciplinary, sluggish, and slightly laughable cathedrals were increasingly challenged by self-organising and intelligent bazaars of hackers, activists or consumers. While imposing and powerful, economic power structures ought not to be described as rigid motors, but as a hackable computer networks (Palmås 2006:96).

In this quote the author refers to a famous analogy by Eric S. Raymond in his essay _The Cathedral and the Bazaar: Musings on Linux and Open Source by an Accidental Revolutionary_. This text compares top-down organizations and bottom-up communities, having Linux developers community as a sort of case study for his arguments -- this text is arguably a pillar for the hacker and free and open source communities. This reference, when employed in Palmås argument, and specifically in this crowd funding sociological analysis, gives a special meaning for the apparent subjective judgement sustained by Victor and Wei, for example. What is at stake is a political claim about the same structures questioned by the 1968 generation, that is to say, an attempt to be free citizens in a free world. Following Palmås, the point is that instead of merely confronting the political strategies of previous generations such as counterculture, they have a new method to put their political voice forward:

[quote]
The children of the '99 revolution shun the … deconstruction methodologies that their parents invented. Instead they employ a hacker attitude towards reality, exploring new forms of activism and critique. A key point here is that the '99ers are as interested in reconstruction (of self-organised structures) as in deconstruction (of hierarchies). Drawing from organisational principles from the world of computers, they are interested in engaging in hands-on building of tangible structures (Palmås 2066:102).

In a broader perspective, the point here is that even if crowd funding has been used by incumbent institutions there are a series of caveats that should not pass unnoticed. First of all is what I have learnt directly from my interviews: their focus is on the possibility of a peer to peer relationship, so when this structure is disrupted by an uninvited institution the magic disappears for them. The importance of such a distinction, as well as the relationship of this distinction to the hacker culture, is so great that it appeared almost literally in the words of one of my interviewees.

For instance, Miguel was about to graduate from a business school, and he was entertaining the idea of starting a social entrepreneurship with a classmate. Eventually their initiative took off but during the interview he highlighted the trigger for that idea. Before quoting him it is worth providing some background information on Thiago -- a person Miguel will eventually cite. Thiago ended up as another co-founder of the platform Miguel was about to bootstrap. The importance of his sudden appearance is his background: a well-versed software developer, a common face in the free and open source software community, helping people run local, national and international events within the community. That said, this is the story Miguel told me:

[quote]
A social business has to make profits, that is what keeps it positive. So, I started to study more and more about it. The startup environment was very important, we were able to meet people running [social] business online, we were finding matches [to our ideas]. At this point the startup model made a lot of sense for us. And then came Thiago. We started to discuss our ideas and Thiago brought a lot of different references, a lot of experience from open source. And that was a better match with our ideas of social business. And that was precisely when I realized crowd funding has impact over the very basic idea of funding, in a peer to peer level. That made a lot of sense, that totally shaped our ideas.

In addition, Daniel, one of the founders of the biggest Brazilian crowd funding platforms, is even clearer when it comes to the rejection of the hierarchical structures (which resonates Palmås 2006 as well as Boltanski and Chiapello 2011). At a certain point during the interview he sustained that Catarse, the platform he founded, was mostly a community while Kickstarter was basically a business:

[quote]
There is also a structural aspect. Kickstarter is a corporation with a clear-cut set of partners, a set of investors, a series of bureaucratic structures that make it compulsory for them to even have an [executive] board.

I have already discussed Daniel's impetus to action and how he feels bounded by bureaucratic structures in the previous chapter.footnote:[See chapter 5, _Autonomy_.] Actually, the whole idea of autonomy explored there is a set of strategies to overcome decision making processes that seem to put people -- understood here as creative and autonomous individuals -- in the background. Therefore, this world view of the crowd funding community is not merely an important part of their positioning in the world but also fits with a very specific stream of radical political thought calling into question core incumbent institutions sustaining the market economy: namely the type of structures criticized since the 1968 social movements.

Interestingly, if this sounds like a kind of confrontational left wing and anti-capitalism or anti-corporation stunt, the crowd funding community also claims it does not have any expectation that the government is a possible alternative, opposing even regulation in most cases -- and again this is the basis of their understanding of autonomy discussed in the previous chapter. In other words, while calling capitalism into question they seem to believe in a radical sort of freedom that fits a radical right wing stunt: anti-state, anti-regulation or, to put it differently, defending every kind of negative freedom (Berlin 1999) that might thwart their strategies to make a living while doing what they believe in. If Wolin and Arendt (as mentioned in the opening of this chapter) have as their motives the justification of a blurred thin line separating the way government and corporations work nowadays, the crowd funding community seems to agree with these scholars. For my interviewees, both structures, the government and the corporation suffer from the same weakness: they are unduly bureaucratic and this bureaucracy invariably obfuscates the real people underneath these structures. To put it simply, decisions are always made following guidelines and regulations, always focused on predetermined targets (usually money and power). Individual uniqueness, creativity and autonomy are not a priority -- even when these structures try to appropriate the crowd funding mechanism.

== A political realm within crowd funding

When it comes to the modern states, Arendt raises two sorts of critiques. As mentioned, first, there is a more overarching critique when she denounces the lack of a public realm -- and consequentially the lack of action in a society basically functioning merely around labor and work. Second, there is a more structural critique when she claims that the possibility of action was effectively displaced to a couple of seconds when voting in a ballot box every other year (Arendt 1973). Hence understating the concept of action is crucial to a dialogue with both critiques.

Therefore, this last block of the present chapter better delineates the concept of action in order to trace parallels with the world view sustained by the crowd funding community and what Arendt expected in terms of the political realm. In spite of that, the intention is not to sustain that these parallels are the only way to sociologically comprehend the position of crowd funding communities -- on the contrary: in my next chapter, I introduce a competing standpoint within this same debate. My aim is develop a framework capable of understanding  tensions in a meaningful sociological perspective.

=== Creating a new public realm

First there is the complete absence of a real public realm. For Arendt (1998) the private realm, that is to say, the space of intimacy of the household is the place for labor -- a kind of activity that is focused on the most basic human needs in terms of sustainability for all of us as a race (putting bread on the table is a way to summarize it). The private realm is also the place in which we work, creating tools to make labor easier so basically our private lives comprehend labor and work in these terms. In ancient Greece there was also the public realm, an exclusive place for what she called action, or "a space for the doers of great deeds and speaker of great words" as Achilles would put it.footnote:["The hero, the 'doer of great deeds and speaker of great words,' as Achilles was called, needed the poet -- not the prophet, but the seer -- whose divine gift sees in the past what is worth telling in the present and the future. This pre-polis past of Greece is the source of the Greek political vocabulary that still survives in all European languages" (Arendt 2005:45).] Action is the only way through which human essence and uniqueness would strive for immortality -- or in other words the proper realm for citizens to fight for what they believe in (instead of simply fighting to put bread on the table).

The public arena in this tradition is the place for action and, in the case of the ancient Greeks, was also the core of democracy, of the state. However, for Arendt (2005:47) this tradition is lost and nowadays modern states have other principles at their core:

[quote]
It was never even considered by our tradition of political thought, which began after the ideal of the hero, the 'doer of great deeds and speaker of great words,' had given way to that of the statesman (_sic_) as lawgiver, whose function was not to act but to impose permanent rules on the changing circumstances and unstable affairs of acting men (_sic_).

For her this radical change in the public realm actually put an end to that space as it used to be. In her words what we have now is a social realm, a mimic of the public realm in which the logic is not action but a massive bookkeeping logic: the public space instead of being "a space for the doer of great deeds and speaker of great words" ends up facilitating mostly private activities. That is to say, in opposition to the her idea of public realm, the social realm is framed in a way that supports the private enterprise, labor and work (Arendt 1998).  Following this argument, politicians in office and in campaigns are hardly ever seen as "doers of great deeds and speaker of great words" but most of the time are bureaucratic leaders whose actions are signing bills to keep the economy growing and, consequentially, providing jobs and welfare to a giant private sphere, whether it is the country, the state or a municipality (let alone continental blocks such as the European Union).

This focus, according to my interviewees, is playing in favor of the _status quo_ of these incumbent institutions; according to them even elected representatives are immersed in this mega operation of bookkeeping guided by numbers and economic indexes -- precisely the metrics of success adopted by governments and corporations. Thus, they feel like politics and politicians in general are not helping them to empower individual creativity and autonomy. The result of Arendt's argument, together with my interviewees' skeptical take on politics, is an overarching disavowal to what we consider to be our public realm (or social realm, as Arendt would put it). In the middle of my interview with Maria, the Romanian girl who crowd funded the tuition for her Master's degree, she was commenting on her disapproval of politics and I asked if there are better or at least more honest politicians. She replied with another question: "Would they still be in politics?"

In spite of corruption and other arguably illegal and immoral aspects of politics the point is that the structure of the state itself is the target of protesters such as the ones from 1968 -- and as we discussed, they are strongly related to the dot com bubble, hacker and free and open software cultures (Palmås 2006). Together with the values of these groups is the will of crowd funding communities to empower individual creativity and autonomy. And this will, my interviewees would argue, is not contemplated by politicians:

[quote]
Then you realise politics is so much associated with financial growth and I just haven't heard of a political discourse that is honest and humane in a long time. [A discourse that] can be a good model for people, that actually they [politicians] should represent. Thus, I think that's why I'm just disillusioned … we putting power in the hands of people that usually are not doing their job which is representing the bigger mass of people's interests (Maria).

Maria's quote, if understood in the context of the autonomy discussed earlier, shows how distant contemporary structures of power are from the crowd funding communities. Also, the debate so far has shown that part of what Maria cited as "the bigger mass of people's interests" is a detachment from and a disavowal of these very same power structures. Yet if the crowd funding community's will is more autonomy, the fit with Arendt's description of action is very appealing: first of all, as discussed in the chapter on the re-signification of money, labor and work are put aside and the focus on autonomy is put in the foreground to allow them to be "doers of great deeds and speaker of great words."

Earlier on in this chapter I mentioned that according to Arendt (1998) action is the only way through which humans can strive for immortality. For her, merely mortal human beings can attempt to last forever -- even as mortals -- through actions. Her argument sustaining this philosophical provocation compares mortal humans with immortal gods -- and especially gods that are  _per se_ doers of great deeds. Therefore, action is the unique way through which worldly deeds can confer upon a human been a status similar to the divine status: a doer of deeds that last forever. For her this is the idea of _vita activa_:

[quote]
No matter how concerned a thinker may be with eternity, the moment he (_sic_) sits down to write down his (_sic_) thoughts he (sic_) cease to be concerned primarily with eternity and shift his attention to leaving some trace of them. He (_sic_) has entered the _vita activa_ and chosen its way to performance and potential immortality (Arendt 1998:20).

_Vita activa_ is "a life devoted to public-political matters" (Arendt 1998:12) and therefore the core of Arendt's concept of action. At this point it may be simpler to discuss the distinction between labor, work and action. The point is not a mere classification in which the fulfilling of the most basic needs  is labeled labor, the employment of skills to make labor easier is labeled work and great deeds are labeled action. Neither is it a mere division in terms of the private and public realm. Even if those claims are valid, they are too simplistic for the comprehension of action.

The concept of action encompasses an important dimension of the human condition itself. First of all, it has to do with human uniqueness, that is to say, to the fact that action only makes sense as each human being is essentially different from any other human being. If humans were equal, action would not be necessary but more radically probably this differentiation of human from nature would not exist either -- in fact Arendt (1998:46) claims this one-ness is the "specimen of the animal species man-kind" (_sic_). Second, these kinds of activities which are focused on deeds and not in labor and work are also intrinsically human:

[quote]
The plurality of men (_sic_) … constitutes the political realm. It does so, first, in the sense that no human ever _exists_ in the singular, which gives action and speech their specifically political significance, since they are the only activities which not only are affected by the fact of plurality, as are all human activities, but are altogether unimaginable apart from it. It is possible to conceive of a human world in the sense of a man-made (_sic_) artifice erected on the earth under the condition of the oneness of man … But an acting and speaking being existing in the singular cannot possibly be conceived (Arendt 2005:63, emphasis on original).

Therefore, the crowd funding communities do not seem to be excited with larger corporations and politicians joining their movement. What might be at stake is the lack of human spontaneity, the lack of this intrinsic uniqueness my interviewees miss in the logic of the decision making and valuing processes upheld by corporations and bureaucracies. Another way to put it is that my interviewees are looking to relate to human beings, not institutions: institutions, as Arendt claims, are locked in the private realm and arguably the crowd funding community is disillusioned by this.

Another way to sustain the disavowal for a more formal and less spontaneous human characteristic in this space is to refer to a quantitative linguistic research suggesting that low expressiveness is typical trace of scamming within crowd funding projects: "scammers deliberately try to deceive people by intentionally providing less information and writing more carefully and less informally" (Shafqat _et al_ 2016:99).footnote:[Their analysis focused on metrics such as non-immediacy (verbs in the first person), expressivity (ratio of adjectives and adverbs to nouns and verbs) and informality (ratio of misspelled words). They conclude "expressiveness of the language of scammers is low, due to over-control and less conviction about what is being said" (Shafqat _et al_ 2016:99)] The conclusion is drawn from the fact that when comparing scam and non-scam projects within crowd funding, scammers tend to use less words, especially verbs and adverbs and, at the same time, showing less spelling errors. On the one hand there is no data on the success or failure in terms of the funds raised by scammers and non-scammers, but on the other hand researches like that reinforce that the formality that is typical in the corporate and political worlds are not the rule in crowd funding.

Juliana is a regular supporter of crowd funding campaigns, especially when they are related to causes she believes in like vegetarianism and cycling. She also supports local musicians and artistic projects. As a cyclist she is also into projects proposing new designs of bike tools and gadgets -- apparels she sees as functional in a pragmatic way (such as plugging them to her bike and using it in her everyday life) as well as political (making biking easier is a political claim in urban mobility debates). She summarized her motivations to join crowd funding campaigns ultimately as a progressive political action, or yet a political provocation:

[quote]
Crowd funding platforms enables a lot of actions that are constrained in our everyday life, actions related to autonomy and empowerment. I supported a lot of activism related projects … I feel like for the more reactionary population in town [empowering activism] might sound insulting. Thus, I believe promoting activism is really a thing for me. I see many projects I supported that way.

She literally said her pledges in crowd funding campaigns are empowering in a political sense -- even when buying a gadget. For her the source of this empowerment lies in the fact that the pledges and projects make her political views tangible in the world. It is her way to be political in modern life. This phenomenon is not new: for instance, Giddens (1991) argues that nowadays the notion of self-identity is not given _a priori_ by the institutions in a given individual trajectory; on the contrary people are constantly building a narrative to support their desired self-identity. From sociological streams like that one can comprehend even consumption as a political act (Micheletti 2003) -- what would be an unusual diversion for the ancient Greeks and for Arendt. However, the point here is not to discuss if a commercial relationship concerns the private or the public realm but to describe the world view from which my interviewees consider crowd funding. For them it is definitively not about a marketplace: that is why they claim a specific relation to money, that is why they focus on autonomy for humans to be humans in the sense of spontaneity, authenticity and, as Arendt would put it, uniqueness -- meaning that different citizens are putting their unique and intimate ideas forward in a democratic arena, seeking for support to be able to achieve great deeds.

The next section draws from that argument of crowd funding as action to describe situations in which my interviewees perceive themselves as actors in modern societies, even if the representative democracies seem to discourage this sort of action outside organized movements or in election periods (Arendt 1973). As discussed earlier the tone is not of confronting the _status quo_ of government and corporations, but of navigating on the margins of these institutions. In other words, it is about allowing people to have a voice not against these institutions, but in spite of them.

=== Empowering action

Just as Juliana and many other interviewees argued, Talita seems to engage in crowd funding for purposes beyond the usual perks. She is a regular crowd funding supporter keeping the habit of browsing platforms such as Kickstarter every month to check up on new and interesting projects to support. She does not seem to be into provocations as Juliana would probably be: even as an earlier adopter of different technologies (such as social media or streaming services), when the innovation is illegal or in a grey area Talita prefers to wait for the government to explicitly regulate the newcomers before jumping in. She claims she has no illegal downloaded MP3s (opting instead to buy them on Google Play store) and she just started to ride Uber when the São Paulo mayor signed a bill regulating the activity of the startup in the city.  In a similar argument as to Juliana, she told me that she is not into crowd funding merely because of gadgets:

[quote]
Kickstarter is not a shopping mall. Surely the rewards are cool, I do love getting them. When one of them arrives, it makes me super happy. But I do not support [crowd funding projects] necessarily having these rewards in mind. I support [them] because I feel like saying "congratulations, dude. You have got a great idea, take 10 dollars. Or 50. Whatever." It really depends on what they have created. For me it works as a donation, it is the same as when I donate to the Red Cross or to the Médecins Sans Frontières: I open Kickstarter looking for cool projects and give money so the people [involved in these projects] can keep on thinking cool stuff.

Juliana and Talita's purposes represent pretty well the other people I talked to in the crowd funding community: many agree that engaging in such projects is a way to put ideas forward. And for them that was the main purpose in crowd funding.

Lisandro is a Brazilian that has contributed to many campaigns for board games, amateur literature and other artistic projects. He told me that his wife mocks him when she catches him on a crowd funding website, saying, "go play patron." In spite of the playful tone she employs, sounding mostly as a joke, he seems to agree with her point of view: "In fact I am playing the patron. I am allowing things to happen, things that nobody else wanted to happen, things no one actually knew or expected to happen." When I interviewed him he drew a clearcut line splitting two kind of projects: on the on hand he labeled "projects" the ones that basically offered a product as a reward -- sometimes he refers to these as "kickstarters" whether or not the website itself was indeed Kickstarter. On the other hand he had supported "authors" campaigns by pledging funds independent of a possible reward -- that is to say, he was supporting the author, the creator of a project.

[quote]
I see it as a way to support an author, one is not only supporting a specific project. The funny thing is that most of the times I get frustrated with kickstarters … than in projects that I am in fact supporting the author. Thus, most of the times I am supporting an author I end up overlooking an eventual sin they might commit. That is to say I do not stop believing that what they are doing, their action. This is what really matters. This has to go on because this is a way to achieve things that normally would not happen.

An "eventual sin" in that context was a project that failed to deliver the promised reward. That was not so disappointing for him because in such cases the focus of his support was on the action, on the idea the creator had, not in a material way. In a similar tone, Juliana told me:

[quote]
It would break trust if they [a given project] ended up not delivering the reward … But I would be fine if they offer an explanation, because this could give birth to a more affective tie between us. Usually this is the case of projects I feel strongly connected with: maybe they [the creators] are my friends, or they are fighting for a cause I believe in. So, there is already this sort of strong tie. If it is not a proper cause, at least it is something that really affects me, something I care about … So what I expect from such projects is that they succeed, I hope they can achieve what they are looking for. I would like to get my reward, to use the product, to see if it really works… and if it does I would probably recommend it all around. But if they fail to deliver it that would not make me stop believing in crowd funding, that would not make me curse them or anything like that.

Such statements, together with the dismissal of formal institutions in the crowd funding arena, are typical markers of a cultural shift. For instance, Palmås (2006) argued that this is the case of the 1968 generation: they have not overthrown any institution or specific political agenda but the effect of that political agitation "made lasting impact on Western culture." According to him this shift was "a furious attack on authority -- and this critical approach to hierarchies has stayed with us since then" -- in other words "people simply did not see the world in the same way after this period" (Palmås 2006:100-1). Until that point, all the anti-hierarchical, anti-bureaucratic, anti-corporation and anti-government discourse held by the crowd funding community might have been seen as a cultural shift as well -- or even as a mere continuation of the 1968 one.

To be clear, the point is that crowd funding communities have not overthrown any corporation or government. They have not pushed any multinational or political party to bankruptcy or shaken any incumbent market or political process, and probably they would never achieve any of this. As argued before, that is not their target; naïvely they prefer to run in the margins, minding their own business, while keeping institutions away from their everyday life. To Palmås (2006) the first generation of the twentieth first century would probably not follow the step of the twentieth century. He uses the analogy of seeing the world as a motor that even if it could be jammed would still follow a more specific set of rules. The alternative emerged together with the emergence of informatics and of the internet in seeing the world as an open computer network to be hacked. To illustrate this argument, he cites Muhammad Yunus as an example, a Bangladeshi man awarded with the Nobel Peace Prize for the creation of micro credit:

[quote]
Rather than a purely social movement, microcredit is a socio-technical movement, enrolling humans as well as non-humans (such as financial instruments). Rather than a symbolic event (a display of public dissent; an event that throws gravel into the societal machinery) it is a tangible, techno-cultural innovation. Rather than seeing the system (the world of finance and banking) as a motor that follows pre-defined _modus operandi_, Yunus saw the economy as an open structure (or, if you will, an assemblage), whose mode of operation can change if new components are plugged into it. Most crucially, Yunus was naïve enough to develop innovations for this system, even though the essentialist Natural laws that are said to govern the system would suggest that such hacks are impossible (Palmås 2006:83).

If seen through that lens, the crowd funding community's focus on action, on enabling things that would not be backed by incumbent institutions, is a way to address problems of the world with a hacker mindset -- or, in Palmås analogy, to see society as an open computer network instead of a motor. Following this argument, the tone of the projects put forward within crowd funding communities is not a new marketplace trying to adapt itself to meet the expectations of traditional market transactions. In fact, it is the opposite since it consists of typical market transactions hacked to work according to a completely different logic. This new logic resignifies money, praises autonomy over bureaucracy and hierarchy, and allows individuals to have a political voice independent of more traditional political institutions.

By these means Arendt's conception of action, together with this hacker take on the structures of power of modern societies, properly describes the crowd funding community objectives: by downplaying any institution that might shadow individual wills and dreams the idea is to empower humans to go public about their projects. These projects have to be tangible: campaigns require a minimum budget and their realization depends on the total raised. To sum up, the idea is to put ideas online and end up with deeds to reassure the trust between creators and backers.

It is important to note that Arendt's view of action was always tied to a formal rhetoric in the public arena (1998). That might not be the case in crowd funding especially when a very attentive communication might raise suspicions of a scam (Shafqat _et al_ 2016). In other words, it seems that a personal tone reinforcing the individuality rather than the formal aspect of the presentation is preferred in this new political space. However, such change can be a signal of how far hierarchical and bureaucratic organizations have gone in annihilating action from every single aspect of human life during the twentieth century. As Boltanski and Chiapello (2011), Heath and Potter (2005) and Palmås (2006) have argued, particularly since 1968, different global societies have called this bureaucratization into question, with different levels of success and of pragmatism. Crowd funding is, therefore, playing this very same game. The crowd funding mechanism in this scenario is a mix of a showcase of ideas and fund raising, an arguably powerful recipe to empower people to action -- or, in Arendt's sense, a receipt to empower doers of great deeds. The greatness of the deeds comes from the uniqueness of each human being involved in the process, whether it is the creator that steps up into the public arena of the crowd funding platforms with his/her own ideas, or the supporters who feel part of the realization of the deeds because they allowed the creators to succeed (spreading the world, discussing and, mainly, donating money for the endeavor).

Furthermore, nowadays the possibility of being politically active in spite of the formal political structure is _per se_ a bold claim. As discussed, Arendt (1973) claims that modern democracies offer citizens too much freedom in their private lives but very rare opportunities to actually exercise their free will in politics. Yet when they do, options are limited by a predefined menu put forwarded by organized political parties (Sniderman and Bullock 2004). On top of that there is the power conferred to money, mainly in the case of corporations and lobby (Wolin 2004). Crowd funding motivations represented by the world views of my interviewees seems to clearly establish a dialogue with all of these social debates, it is their way to step in this debate and to address issues in the power structures of modern societies.

'''

The title of this chapter was already a disclaimer for the reader: if there were harsh critiques to crowd funding communities they would be saved for another opportunity. Also, the promise of the title signaled that there is an important political aspect in crowd funding that should not be dismissed. In terms of social theory there are arguments and stories supporting that my interviewees are engaging with major debates regarding incumbent institutions such as the market and the government. Also, the arguments so far hopefully sustain that in different degrees of consciousness my interviewees are dialoguing with power structures as political actors.

Yet the title of this chapter also announces a certain optimism that the reader might align with a utopian view of the internet and, generally speaking, of technology as a whole. First, I must clarify that this optimism is sound and clear in most of my interviews -- even people that see crowd funding as a kind of intermediary step to an uncertain future believe that by now crowd funding is powerful in putting forward ideas that would probably be left aside by mainstream economic and political thought.

In sum, my interviewees are pretty excited about becoming protagonists through crowd funding. For instance, Lisandro even joked that if until the 1990s people would struggle for their "15 minutes of fame" nowadays people are "famous for 15 people" instead. In spite of that, surely there are also critiques and boundaries on crowd funding pointed out by my interviewees. The next chapter debates the possible downsides of this sort of politics as put forward by crowd funding communities.
