= Politics within crowd funding communities: the dark side (provisional title)
Eduardo Gonçalves
:revremark: Draft of chapter to the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy.
:revdate: September 2017
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
The state is a modern phenomenon and its _raison d'être_ was to develop, or better, to capitalize the power of society — the power resident in the human activities, and transactions that sustain life relationships, and its changing needs. The state became a coercive agency, declaring and enforcing law, punishing miscreants of all descriptions, systematizing taxation, encouraging commerce and manufacture in the direction of national economies, conducting diplomacy, waging war, and seeking empire. Its characteristic form of action is the decision which it “makes” with relentless regularity; its typical expression is the announcement of a “policy,” and its mode of governance ranges from inducements to force (Wolin 1983:17).

The last chapter departed from a discussion regarding introspective take Arendt takes on citizens when reflecting the political realm. In a normative way she claims that at the core of politics should lie the concept of action leading citizens to the _vita activa_. In spite of that her diagnosis of modern representative democracies is far from this ideal. As discussed in the previous chapter there is a lack of space for action. On top of that Arendt ponders on the motives underneath this privatization of the public realm – not in the neoliberal way of conceding public interest entrepreneurship to the private initiative, but as a way to signal that private interests are acting in places in which public interests were expected:

[quote]
That men (_sic_) do not know what they are doing with respect to others, that they may intend good and achieve evil, and vice versa, and that nevertheless they aspire in action to the same fulfillment of intention that is the sign of mastership in their intercourse with natural, material things, has been the one great topic of tragedy since Greek antiquity. The tradition never lost sight of this tragic element in all action, nor failed to understand, though usually in a nonpolitical context, that forgiving is among the greatest of human virtues. It was only with the sudden and disconcerting rush of the gigantic technical developments after the industrial revolution that the experience of fabrication achieved such an overwhelming predominance that the uncertainties of action could be forgotten altogether; talk could then begin about “making the future” and “building and improving society” as though one were talking about making chairs and building and improving houses” (Arendt 2005:58).

According to her, and in spite of the normative approach discussed earlier, humans themselves have a blurred understanding of the boundaries of private and public interests – let alone the realms for each of these approaches. In ancient Greece just a small percentage of citizens were allowed in the public arena; among other reasons because only the ones with land and slaves were able to provide for themselves and their families, or in other words were able to leave private interest aside when stepping into the public arena.

Industrial revolutions and specially the rapid industrial growth in the second half of twentieth century might have made labor and work easier and abundant, and as a result made the production of goods cheaper and also abundant. In other words those arguably logical arguments would end up alleviate the pressure over citizens shoulder when it come to private interest: arguably it would be easier to provide for one's family in order to be free from these worries and to engage in action in the public realm. Nowadays wage earners and entrepreneurs would easily be as well off as their ancient Greek ancestor. Paradoxically this is not what happened. For Arendt the ease with people deal with labor and work actually lead them to try to apply the same logic to the public sphere – which lead to its transformation in a massive social realm: as aforementioned, a massive bookkeeping activity we see in the news about our democratic chosen representatives.

Even worst for Arendt normative speculations the state have become a place for bureaucratic rulers, not for doers of great deeds. And in fact for her this was not a surprise: 

[quote]
The concept of rule, as we find it in Plato and as it became authoritative for the tradition of political thought, has two distinct sources in private experience. One is the experience which Plato shared with other Greeks, according to which rule was primarily rule over slaves and expressed itself in the master-servant relationship of command and obedience. The other was the “utopian” need of the philosopher to become the city's ruler, that is, to enforce in the city those ‘ideas’ which can be perceived only in solitude” (Arendt 2005:52-53).

Therefore beyond being able to get into action through crowd funding as previous chapter discussed, my interviewees also circumvent this tradition of political thought based on rule and obedience: their way to praise autonomy and their non-confrontation strategy empowers them to move on without rulers or regulation. In spite of the fact that some of my interviews proudly acknowledge these strategies political theory might call these same strategies into questioning.

This chapter analyzes two branch of critiques relevant in this scenario. First by dismissing authority altogether by adopting a marginal path to institutions and by praising autonomy crowd funding communities end up in sort of self sustaining echo chamber: technology allowed people with common interest to easily gang up and support the existence of projects that are unanimous inside this bubble. This seems a typical antipolitical anything goes mindset as suggested by Schedler (1997); at the same time this is a weak perception of the political: democracy without an agonistic public realm is not also antipolitical Mouffe (2005) claims.  

Second the critique of sociology of ignorance might be another source to better understand the world view and the power structures involved in the crowd funding communities. This is the case when many interviewees seems to be so excited about the doors opened by crowd funding while they seems to have a blurred view – if any – of the boundaries and risks of such engagement. The bubble effect mentioned in the last paragraph is an example: most of the crowd funding community would say that being famous for 15 people (as Lisandro put it) is inherently a good thing, without asking themselves if empowering any kind of 15 people group is actually a desired effect of politics. This a characteristic of a strategic usage of ignorance useful to

[quote]
maintain and to disrupt social and political orders, allowing both governors and the governed to deny awareness of things it is not in their interest to acknowledge (McGoey 2012:4).

## Anti-political and Mouffe

Adam: filter bubble
Lisandro about people/project he supports:

[quote]
Mesmo quando não são pessoas que eu conheço pessoalmente, são pessoas ou que você está seguindo no Twitter, são autores que você gosta e você tem uma aproximação por conta de Twitter, de seguir determinadas coisas que eles fazem, e você se sente um pouco muito próximo desse grupo … tem algumas iniciativas de ensaístas de vídeo do YouTube que eu apoio, porque eu assisto os vídeos, poderia pagar US$ 1.00 por mês para apoiar os caras, para mim não é nada. desde que eles continuem produzindo. Então, eu vejo isso como uma troca muito clara. Para mim, eu não sou um cara, assim, eu não vou... Todo mundo aqui já baixou filme de porte, essas coisas todas e tal, mas eu procuro pagar pelo conteúdo. E quando você está num... Você conhece a pessoa, mesmo que seja não fisicamente, mas você conhece a pessoa pela interação que você está tendo com ela via Twitter, ou via pelas redes sociais, isso facilita muito que você esteja apoiando os projetos delas.

## Ignorance

Lisandro and Sam on anti crowd sourcing
Heather and Potter again

[quote]
Social scientists, in writing about ignorance, must better acknowledge their own ignorance of the unarticulated or simply unconscious rationales of the individuals they suggest may be deliberately harnessing ignorance (McGoey 2012:11).


== References

[references]
* Arendt, H. (2005). _The promise of politics_. New York: Schocken.
* McGoey, L. (2012). Strategic Unknowns: Towards a Sociology of Ignorance, _Economy and Society_ 41(1). Pp. 1-16.
* Mouffe, C. (2005). _On the Political_. London and New York: Routledge.
* Schedler, A. (1997). Introduction: Antipolitics — Closing and colonizing the public sphere. In Schedler, A. (ed.) _The end of Politics? Explorations into Modern Antipolitics_. New York: Macmillan. Pp. 1-20.
* Wolin, S. (1983). Hannah Arendt: Democracy and The Political. _Salmagundi_, 60. Pp. 3-19.
