= Politics within crowd funding communities: the dark side (provisional title)
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
The state is a modern phenomenon and its _raison d'être_ was to develop, or better, to capitalize the power of society — the power resident in the human activities, and transactions that sustain life relationships, and its changing needs. The state became a coercive agency, declaring and enforcing law, punishing miscreants of all descriptions, systematizing taxation, encouraging commerce and manufacture in the direction of national economies, conducting diplomacy, waging war, and seeking empire. Its characteristic form of action is the decision which it “makes” with relentless regularity; its typical expression is the announcement of a “policy,” and its mode of governance ranges from inducements to force (Wolin 1983:17).

Last chapter started with the introspective standpoint Arendt's analysis have on citizens, specially when theorizing about the political realm. In a normative way she claims that at the core of politics should lie the concept of action, what would lead citizens to the _vita activa_. In spite of that her diagnosis of modern representative democracies is far from this ideal. As discussed in the previous chapter Arendt herself concluded there is a lack of space for action, for example. On top of that she ponders on the motives underneath this privatization of the public realm – not in the neoliberal way of conceding public interest entrepreneurship to the private initiative, but as a way to signal that private interests are acting in places in which public interests were expected.

At a certain point Arendt discusses the concept of forgiveness together with action and the industrial revolution (2005:57-59). According to her as action is the foundation of the anew, forgiving  “attempts the seemingly impossible, to undo undo what has been done.” As a consequence “it [forgiveness] succeeds in making a new beginning where beginnings seemed to be no longer possible.” This is relevant in her argument as she foresee a structure that is typical in complexity theory:footnote:[To be clear I am not saying that Arendt is referring nor subscribing to complexity theory. Also I am not claiming she is a precursor of this field. The point is that, as Arendt (2005:58) put, “men (_sic_) do not know what they are doing with respect to others, that they may intend good and achieve evil, and vice versa, and that nevertheless they aspire in action to the same fulfillment of intention that is the sign of mastership in their intercourse with natural, material things, has been the one great topic of tragedy since Greek antiquity.” To a certain extent this acknowledgement is also found in complexity theory in which systems are non-linear, non-teleological, and their outcomes are highly unpredictable (Mitleton-Kelly 2003).] that actions leads to “a chain of of unpredictable consequences” in which even the person who acted ends up as “both actor and victim in this chain of consequences.” Finally she highlights how last decades technological advances together with this complexity of action and forgiveness have made of action a sort of volatile basis for modern democracies:

[quote]
It was only with the sudden and disconcerting rush of the gigantic technical developments after the industrial revolution that the experience of fabrication achieved such an overwhelming predominance that the uncertainties of action could be forgotten altogether; talk could then begin about “making the future” and “building and improving society” as though one were talking about making chairs and building and improving houses” (Arendt 2005:58).

According to her, and in spite of the normative approach discussed earlier, humans themselves have a blurred understanding of the boundaries of private and public interests – let alone the realms for each of these approaches. In ancient Greece just a small percentage of citizens were allowed in the public arena; among other reasons because only the ones with land and slaves were able to provide for themselves and their families, or in other words were able to leave private interests aside when stepping into the public arena.

Industrial revolutions and specially the rapid industrial growth in the second half of twentieth century might have made labor and work easier and abundant, and as a result made the production of goods cheaper and also abundant. 
Arguably it could be expected that this new technological progress would end up alleviating the weight on citizen shoulders when it come to private interest: it would be easier for them to provide for their families, labour would be gradually taken over by machines, the production of food, supplies and all sort of goods would be cheaper and cheaper over time. And once the pressure to provide was facilitated by this new condition engaging in action in the public realm would be easier than ever. With factories and automation wage earners and entrepreneurs would easily be well off, specially when compared to their ancient Greek ancestors.

Paradoxically this is not what happened. For Arendt the success in managing private interest instead of enabling more and more citizen to devote themselves to the public interests actually pushed society in an attempt to transpose the logic of one realm to the other, in other words an attempt to apply the same logic guiding the private realm into the public realm. And yet according to Arendt (1973) that move has lead to a bold transformation: the once public realm became a massive social realm – a massive bookkeeping activity as we see in the news about our democratic chosen representatives. Even worst for Arendt normative speculations the state have become a place for bureaucratic rulers, not for doers of great deeds. And in fact for her this was not a surprise: 

[quote] 
The concept of rule, as we find it in Plato and as it became authoritative for the tradition of political thought, has two distinct sources in private experience. One is the experience which Plato shared with other Greeks, according to which rule was primarily rule over slaves and expressed itself in the master-servant relationship of command and obedience. The other was the “utopian” need of the philosopher to become the city's ruler, that is, to enforce in the city those “ideas” which can be perceived only in solitude (Arendt 2005:52-53).

Last chapter discussion on my interviewees efforts to get into action through crowd funding was also an attempt circumvent this tradition of political thought based on rule and obedience: their way to praise autonomy and their non-confrontation strategy empowered them to go on without rulers or regulation – as they would probably put it. In spite of the fact that some of my interviews proudly acknowledge these strategies from a political theory perspective these same strategies need further investigation.

This chapter analyzes two branches of critiques relevant in this scenario. First by dismissing authority altogether, by praising autonomy and adopting a marginal path to institutions crowd funding communities end up in sort of self-sustaining echo chamber: technology allowed people with common interests to easily gather and support each other, raising funds for projects that arguable are unanimous only inside their own bubble, their own social circle. This seems a typical antipolitical _anything goes_ mindset as suggested by Schedler (1997:8): for him a political community “needs to be free from external constrains” as much as, “at least to a minimal degree, it must be able to impose internal constrains on its members.” At the same time this isolation in autonomous bubble is also a problem for the political in Mouffe's (2005:3) analysis:

[quote]
Instead of trying to design the institution which, through supposedly “impartial” procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant “agonistic” public sphere of contestation where different hegemonic political projects can be confronted.  

Besides this anti-political aspect sociology of ignorance is another source to shed light on the world view and the power structures involved in the crowd funding communities. This is the case when many interviewees seems to be so excited about the doors opened by crowd funding while they seems to have a blurred view – if any – of the boundaries and risks of such engagement. The bubble effect mentioned above is an example: most of the crowd funding community would say that being famous for 15 people (instead of having their 15 minutes of fame, as Lisandro put it) is inherently a good thing, without asking themselves if empowering any kind of 15 people group is actually a desired effect of politics. This is a characteristic of a strategic usage of ignorance useful “to maintain and to disrupt social and political orders, allowing both governors and the governed to deny awareness of things it is not in their interest to acknowledge” (McGoey 2012:4). 

The next two sections explore both the antipolitical and the sociology of ignorance critiques based on a few interviews in which my informants seemed to be keen of these possible downsides. Interestingly even those who pointed in the direction of these critiques were people convinced that being part of the crowd funding community – supporting projects and eventually creating their own projects – was a very interesting possibility in social, cultural and financial aspects. The tensions in handling these apparent opposing views are also explored below.

== Antipolitical crowdfunding

Adam, the Parisian amateur filmmaker introduced in chapter 3, was one among my interviewees who basically supported two kind of projects: the ones from friends or acquaintances, and the ones for causes he believed in. As he was describing this last category of projects I had the feeling they were basically progressive in terms of political affiliation: healthy organic cooking, woman empowerment, collaborative redesign of public spaces and so on. Following on that he declared he was very enthusiastic about crowd funding not only because it enabled him to donate to these causes, but basically because this mechanism allowed niche content to be produced, distributed and to reach their very specific public. He added that advertisement business model like the one behind YouTube (in which the creator of the video gets a percentage of the income from advertising according to the number of views of the video) has failed on that, however crowd funding had a higher chance of succeeding.

His argument is based on the small percentage – less than 50% — of ad income that goes to the creator. Also he added this revenue is only a reality for videos with a really high number of views. For example a creator posting 20 videos per week with 1 million subscriber gets between 7 and 8 dollars per thousand views (Edwards 2014). This is a lot of effort to produce a massive amount of content – and still Google keeps more than half of the money.

Following Adam's thought if only 1% of the 1 million subscribers of the creator from the figures above donated her 1 dollar every month she would end up with the same annual income. Therefore Adam believes there is a huge potential for more productivity, more quality and less worries with inflating production and views in ad based platforms – let aside battling ad blockers. In order to make a living of niche content crowd funding seems more promising than YouTube ad income distribution. And my interviewees in general are very optimist about seeing more and more niche projects out there.

Next Adam and I talked about niches in the internet and he shared an opinion that seemed pretty much convergent to the idea of echo chambers contained in small bubbles around the digital world. This is how he described the phenomenon:

[quote]
I have seen a lot of my old friends talking to the hand, people talking with people that agree with them. There is no debate at all. There is nothing being build that way either. People take things to the extreme and they manage to find other people agreeing with them. All out of sudden extremist ideas are a consensus. People start believing that whatever they were willing to believe beforehand is a consensus, is the obvious. For me this is the dynamics of social media nowadays.

Lisandro also also believes that these bubbles exists and that crowd funding revolves around these small communities. He actually used to get involved in the community going to meet ups and meeting people in person specially in some fields he is passionate about, such as literature for example. In fact this was an old habit from the time when he owned a second-hand bookstore: the business was not exactly profitable but it worth it because of the community that regularly gathered around the venue. This bubble effect is still valid in his crowd funding routine, as he describes the relationship between him and the project creators he usually supports:

[quote]
Even when I do not know them in person they are people I follow on Twitter, authors I like. I feel close to them as I follow the projects they run, so it is a group, you feel like you are part of it. There are also some video initiatives on YouTube I support because I watch the videos. I can pay one dollar a month for them, I can afford it if they keep on shotting new videos. I see this as clearcut exchange … I am willing to pay for the content [I consume] and when you actually know the person [creating that content], even if not in person but via social media, it is way easier to support their projects.

Emily, part of the team who founded a British crowd funding platform,footnote:[See chapter 3.] believes that this community effect around crowd funding is more attractive than the possibility of making money. In other words it is about a collaborative relationship, and not merely patron relationship in which one part supports the other financially:

[quote]
I do not think there is all that many people who set out because they are like “I want to make millions of pounds.” They kind of set out because they are like “I think this is a really interesting business model.” It shifts things so that some of the most effective Kickstarter projects are ones effectively getting user information. You get to connect with your users. You get to iterate and change your project much faster as you are going along and you get advanced orders so the risk is lower. It feels like a much more connected relationship that those projects typically have with the people who will be using that project.

Surely she is not denying that there are different mindset around crowd funding but for her this is not so common in regular crowd funding: “maybe that is something more [common] on the kind of equity based crowd funding platforms,” she ponders. Her argument also brings in a business mindset shared by other interviewees (Daniel, the German interested in board games, for example): the case in which a community of people connected by stronger ties reduces the economic risk of a enterprise. In sum there are different approaches the crowd funding community recurs in order to emphasizes how the personal side of their relations grants a more coherent space for them. Within this space, and with cash circulating among people in this bubble, a lot of anew can be funded.

At this point it worth it call into question what are the issues the crowd funding enthusiasts might be leaving behind. If in last chapter I highlighted that Mouffe criticized Arendt's idea of politics on the grounds that her ideas would be too optimistic for the public realm, the same question is valid for my interviewee's world view. If the point of view argued in the last paragraph was the only side of this coin, autonomy would allow a plethora of ideas and actions in the public space, and crowd funding would allow people to join forces to make them happen. If that all was actually happening Mouffe (2005:3) arguments would be a harsh attack on the success of crowd funding as a form of political engagement:

[quote]
Instead of trying to design the institution which, through supposedly “impartial” procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant “agonistic” public sphere of contestation where different hegemonic political projects can be confronted (Mouffe 2005:3).

Therefore the point is to highlight that crowd funding fails in all criteria of a this sort of heuristic proposed from this quote. First of all crowd funding is not a impartial procedure. This issue is multifaceted and probably it is not feasible to exhaust all possible ways to argue that impartiality is not a strength of crowd funding. As seen my interviewees would argue in a kind of libertarian tone that anyone could pledge in any crowd funding campaign – and that would be enough to label crowd funding as “democratic.” Surely this is not the case. The basic argument would be that not everybody is online (48% of the world is, 41% if we take only developing countries, or 81% in developed countries) and that not everybody online actually trusts the web enough to make an online payment (79% of Americans that are online are in fact shopping online).footnote:[Figures regarding population with internet access according to ICT (2017) and the one about online payments according to Pew Research Center (2016).] 

However even moving away from numbers it is possible to discuss the impartiality of crowd funding. For instance my interviewees, as discussed before, are very similar in terms of their social and educational background. They usually are people that have had access to higher education, that can easier take risks because they have a safety net. Those from outside the global north have fluent English and at least some experiences abroad. This fact cannot be ignored when pondering about the impartiality of crowd funding: these trajectories have social impact in the way these individuals face the world, on their personal values, strategies, aspirations and notions of right and wrong, of success and failure. All these aspects end up internalized as a disposition to act in a similar fashion (Bourdieu 1970). As Swartz (1997:109) summarizes this argument:

[quote]
It is one thing to say that working-class youth do not enter French universities because they fear failure, and quite another to say that getting a higher education does not belong to their world view or class structure. In the former case, these youths might value higher learning and have hopes of attending the university but choose not to attend because they expect to fail. In the latter case, they would have no desire to attend the university and therefore no expectations.

In other words the crowd funding community share so much in common that it is expected that it will reproduce their values instead of acting as impartial platform — specially when some of the platform founders and staff I interviewed explicitly recurred to the analogy of putting the curatorial layer to keep the platform a garden not a thicket (that is to say, they cherry pick the projects that go online, they help creators to produce videos, text and images passing a specific kind of message etc.). Even in face of some tensions (such as whether it is OK or not to use Kickstarter basically as a shop window) my interviewees share similar world views in many other perspectives.

Following Mouffe's quote crowd funding does not reconcile conflicting interests and values either. Beyond the similarity discussed above the mechanism itself is not focused in debating, in contrasting ideas, but mostly in isolating the needs (the financial target of each campaign) from the rest of the campaigns. In this scenario even contradictory projects could end up funded and their supporter would never meet to discuss if these ideas can cohabit in the very same society. At the same time as a white supremacist might be raising funds to keep their podcast production running, supporters of Black Lives Matter might be funding a documentary about their social movement. Actually there were attempts from these opposing groups to raise funding through crowd funding. From the example mentioned a studio from London launched a campaign to shoot a documentary called “The Third Dimension: #BlackLivesMatter” (Indiegogo 2016). On the other hand after being accused of hosting campaigns for white supremacists and neo-Nazis many platforms turn them down (Independent 2017).

In both cases there was no debate on the validity of these ideas to society, neither on the possibility of the coexistence of these ideals in a civic public space. And even when the decision to not host campaigns for groups of a given credo, the decision was unilateral, non agonistc, as Mouffe belives democratic bodies should be. And yet this kind of decision might be an argument in favor of the similar world views shared by the crowd funding communities. By these means there is a great possibility that even if politically speaking the crowd funding community allows multiple initiatives to be launched, and to make ends meet, it is arguably a political tool focused in a specific kind of public: it will attend this public demand and amplify their range of action – ending up as an ever growing echo chamber. However even if my interviewees believe they have the greatest intentions, this is not necessarily democratic in Mouffe's sense. 

Finally Mouffe's quote refers not only to the confrontation of idea, but also to hegemonic political projects. In that sense there is arguably a two fold critique towards the crowd funding communities: the kind of projects they put forward are at most public goods with limited range. Cases like the crowd funding of public transportation or of museums are quite rare (Indiegogo 2014), and even if it can be considered a remarkable public good does not put different hegemonic political projects face to face. This museum case, for instance, put on evidence the figure of Nikola Tesla: they raised fund to buy the site of a well-known antenna designed by him and plan to open a museum there. In the popular culture the name of such a engineering arguably reinforces a very specific set of characteristics common to many of my interviewees: a utopian view of technology, a kind of vote for a frugal life, a controversial disavowal for copyright and patents etc. And, again, if this political project is put forward by crowd funding, there is no hegemonic antagonism to it within the crowd funding community.

In Shedler (1997:3) words politics involves “the definition of societal problems and conflicts, the elaboration of binding decisions and the establishment of its own rules.” Crowd funding is a kind of open space where ideas run in their own bubbles, without running into each other; in other words the notion of conflict is downgraded because anyone can submit any idea, and the notion of problem is reduced in a pecuniary total, the target of the campaign. Once these pecuniary targets are reached there is no need for binding decisions or any kind of dependence between people involved in such projects and outsiders. And surely the highest bar crowd funding afforded to put in rules are unilateral decision taken by founders and staff of the platforms together with individual decision to support or not each project. Therefore in spite of action empowering in Arendt's sense, there are strong critiques to consider crowd funding community as political from the perspective of the way they organize the interaction among its members.
 
== Dodging dystopia

Certainly Adam's idea of niche contents (mentioned earlier in this chapter) is not an odd statement. Indeed it is similar to Pariser's (2012) best seller _The Filter Bubble_, a book basically blaming algorithms for isolating people in bubbles of their users alike: for example, Google show results similar to the ones you have already clicked in the past, or your Facebook feed is assembled from posts of things data science predicts you will probably like. This strategy pull apart controversial contents for each and every online user.

However, in opposition to Parisier, Adam does not seem convinced that algorithms filtering our content is actually the only cause of these bubbles. Actually he is closer to Bishop's (2008) argument in _The Big Sort_: as a result of the success of the welfare state, the book claims, Americans felt free to move wherever they wanted within the continental country. These freedom resulted in a clearcut polarization reflecting like-minded groups: in general liberals moved to metropolitan centers such as New York and San Francisco while conservatives grouped in Orange County and Colorado Springs for example. This is a contrast compared to the 1970s when college degrees were not not polarized in specific urban centers. As Bishop Adam believes that technology is not the one to blame in these bubble effects:

[quote]
Corporations have no ideology. They do what makes the most money, what gives them more profits – except in rare cases in which Facebook [for example] stands for Israel, for Jews etc. But most of the time you take any of the big media companies and you see some to the right, some to the left, but all of them will be focus in the return of investments. If you take Fox News in the USA, there are people interested in that kind of content, people willing to put money on that. If we did not have these people, we would not have it [Fox News]. I do not like this idea that Fox [News] causes conservatism. Both [people interested in Fox News contents, and Fox News itself] are parts of a cycle. And that is the same with crowd funding, and with social media. One can create mechanisms to bring conflict in, to bring discourse in, to promote the debate of opposing ideas. But people just do not care. That is not what they want.

What Adam is suggesting is that there are several aspects of the way that people spread their messages is highly debatable: there is unequivocal bias in this process. Therefore even if the crowd funding platforms themselves are not really stakeholders in the global economy, or at least in the global media, they depend on the strategies and side effects of social media to spread the word about each campaign. This introduces a kind of unattended bias in the crowd funding community – in other words when my interviewees claim that there are projects out there and people are free to pledge in any project they like, that might not be only way to take the story into account (18).

In fact there are studies on the dynamic of grassroots online petitions campaigns describing a importance of a new kind of leadership: there is “a general shift from leaders and elite to members or individuals” (Margetts _et al_ 2013:3). In other words characteristics typical from online petition (and I might add, online crowd funding) campaigns create a new dynamic for political action in which:

[quote]
contemporary political mobilisations can become viable without leading individuals and organisations to undertake organisation and coordination costs, proceeding to critical mass and even achieving the policy or political change at which they are aimed (Margetts _et al_ 2013:19). 

These characteristics includes, for example, micro donations (of time in online petitions and of time and money in crowd funding), low start-up costs (no need of great investments to launch an online petition or crowd funding campaign) and the importance of certain number of people willing to start (signing the petition or donating to crowd funding). Actually this last example is crucial: most of the successful online petitions that reached a significant amount of signatures had a steep rise in the very first days. Margetts _et al_ (2013) argues that instead of basing trustworthiness from the credentials of more traditional incumbent institutions and leaders, these new online mobilizations are pore passive to externalities – that is to say depending on the number of signatures already added to a given petition (and I might add, the amount of money already pledged in a crowd funding campaign) and on the people who shared the link to such a campaign, for example, possible enthusiasts of this polical action deicide if they are joining it or not. As Margetts _et al_ (2013:18) summarize:

[quote]
In this environment, leadership is the aggregate of many low-cost actions undertaken by those willing to start, rather than the raft of actions and characteristics of the few with which it is normally associated. Of course, the group of starters will usually include at least one leader in a more traditional mould who has taken a higher-cost action: for example, the person who sets up a petition and circulates it to close associates in their immediate social networks. But the number of starters needed to get the mobilisation off the ground will be beyond that possible to obtain with strong ties to the initiator alone, but will be attained with weak ties, such as the friend of a friend of a friend on a social networking site, or the retweet of the retweet of a tweet … By providing this social information, internet-based platforms circumvent the need for other activities traditionally performed by leaders. 

In this scenario the unattended subjectivities of how information circulates is very important and in spite of some interviewees as Adam seems to be willing to discuss the power of the multinational corporations behind and the way they forge what happens under the umbrella of crowd funding, this discussion is not a detail, but a crucial sociological fact in understanding the social and political consequences of such way of getting people together. This resonated in a two fold critique Lisandro proposed me. On the one hand while debating about two kind of powers acting in a crowd funding community he called expressiveness into question. For him there are two sorts of powers: incumbent power (basically external from the community, power that has its sources in the incumbent institutions) and an effective power (felt as stronger within the crowd funding community):

[quote]
My idea is that you basically flatten relationships, thus in reality incumbent power ends up weaker than effective power. And this effective power is established due to one's own expression skills. Those who know better how to express themselves have some advantages because they can clearly show how passionate they are about a certain subject. The have way more power than people imbued with institutional power.

On the other hand Lisandro also critiques the way corporation power is managing not only crowd funding but the sharing economy as a whole:

[quote]
I live in Copacabana, in Rio [Rio de Janeiro, Brazil] in in my building I guess there are only four permanent residents. The rest is all Airbnb. In a certain way these are disaggregating activities, [activities that makes] you monetize collaboration. 

With these quotes Lisandro clearly traces a line highlighting two topics that are left behind when people (including Lisandro himself and Adam) take a optimist view on the potential of crowd funding. First we have all the subjectives qualities of platforms and creators in launching what might be a successful campaign. Second we have the perception of a more open and collaborative mechanism to sort out ideas that is only possible through a very centralized mechanism: the crowd funding platform them selves. It is only by ignoring these issues, and only by ignoring what unfolds from it (such as the effect of algorithms regulating social media, or the power of the platforms as intermediaries) that these kind of communities can be perceived as efficient news ways of political and democratic action.

Sam, an expert in sharing economy I interviewed, extends the critique initiated by Lisandro to the whole field of online sharing economy as we have today:

[quote]
AirBnB is intermediary for short-term rentals and Uber is a taxi service, neither of which are really sharing. Especially Uber, I would say, is not sharing because it's a taxi service. You're not actually sharing a ride. From an environmental perspective, and I know there's the environmental arguments for the sharing economy, as far as Uber goes, it's people driving around in cars to pick other people up. It's facilitating greenhouse gas emissions, rather than preventing it.

NOTE: Samrock on local Uber

NOTE: Emily and Chris's take on collaborative economy and crowd funding.

[quote]
Social scientists, in writing about ignorance, must better acknowledge their own ignorance of the unarticulated or simply unconscious rationales of the individuals they suggest may be deliberately harnessing ignorance (McGoey 2012:11).

NOTE: Heath and Potter (2005) on capitalism success in swallowing counter movements.
