= Politics within crowd funding communities: the dark side (provisional title)
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
The state is a modern phenomenon and its _raison d'être_ was to develop, or better, to capitalize the power of society — the power resident in the human activities, and transactions that sustain life relationships, and its changing needs. The state became a coercive agency, declaring and enforcing law, punishing miscreants of all descriptions, systematizing taxation, encouraging commerce and manufacture in the direction of national economies, conducting diplomacy, waging war, and seeking empire. Its characteristic form of action is the decision which it “makes” with relentless regularity; its typical expression is the announcement of a “policy,” and its mode of governance ranges from inducements to force (Wolin 1983:17).

The last chapter departed from a discussion regarding the sort of introspective take Arendt's analysis lie on citizens when reflecting the political realm. In a normative way she claims that at the core of politics should lie the concept of action leading citizens to the _vita activa_. In spite of that her diagnosis of modern representative democracies is far from this ideal. As discussed in the previous chapter there Arendt herself concluded there is a lack of space for action, for example. On top of that she ponders on the motives underneath this privatization of the public realm – not in the neoliberal way of conceding public interest entrepreneurship to the private initiative, but as a way to signal that private interests are acting in places in which public interests were expected.

At a certain point Arendt discusses the concept of forgiveness together with action and the industrial revolution (2005:57-59). According to her as action is the foundation of the anew, forgiving is “attempts the seemingly impossible, to undo undo what has been done” and as a consequence “it succeeds in making a new beginning where beginnings seemed to be no longer possible.” This is relevant in her argument as she foresee a structure that is typical in complexity theory:footnote:[To be clear I am not saying that Arendt is referring to complexity theory, founding or subscribing to it. The point is that, as Arendt (2005:58) put, “men (_sic_) do not know what they are doing with respect to others, that they may intend good and achieve evil, and vice versa, and that nevertheless they aspire in action to the same fulfillment of intention that is the sign of mastership in their intercourse with natural, material things, has been the one great topic of tragedy since Greek antiquity.” To a certain extent this acknowledgement is also found in complexity theory in which systems are non-linear, non-teleological, and their outcomes are highly unpredictable (Mitleton-Kelly 2003).] that actions leads to “a chain of of unpredictable consequences” in which even the person who acted ends up as “both actor and victim in this chain of consequences.” Finally she highlights how last decades technological advances together with this complexity of action and forgiveness have made of action a sort of volatile basis for modern democracies:

[quote]
It was only with the sudden and disconcerting rush of the gigantic technical developments after the industrial revolution that the experience of fabrication achieved such an overwhelming predominance that the uncertainties of action could be forgotten altogether; talk could then begin about “making the future” and “building and improving society” as though one were talking about making chairs and building and improving houses” (Arendt 2005:58).

According to her, and in spite of the normative approach discussed earlier, humans themselves have a blurred understanding of the boundaries of private and public interests – let alone the realms for each of these approaches. In ancient Greece just a small percentage of citizens were allowed in the public arena; among other reasons because only the ones with land and slaves were able to provide for themselves and their families, or in other words were able to leave private interests aside when stepping into the public arena.

Industrial revolutions and specially the rapid industrial growth in the second half of twentieth century might have made labor and work easier and abundant, and as a result made the production of goods cheaper and also abundant. 

Arguably it could be expected that this new technological conquests would end up alleviating the weight on citizen shoulders when it come to private interest: it would be easier for them to provide for their families in order to, being free of this pressure, engaging in action in the public realm. With factories and automation wage earners and entrepreneurs would easily be as well off, specially when compared to their ancient Greek ancestors. Paradoxically this is not what happened. For Arendt the success in managing private interest instead of enabling more and more citizen to devote themselves to the public interests actually pushed society to apply to attempt a transposition: applying the same logic guiding the private realm to the public realm which lead to its transformation in a massive social realm – as aforementioned, a massive bookkeeping activity we see in the news about our democratic chosen representatives. Even worst for Arendt normative speculations the state have become a place for bureaucratic rulers, not for doers of great deeds. And in fact for her this was not a surprise: 

[quote]
The concept of rule, as we find it in Plato and as it became authoritative for the tradition of political thought, has two distinct sources in private experience. One is the experience which Plato shared with other Greeks, according to which rule was primarily rule over slaves and expressed itself in the master-servant relationship of command and obedience. The other was the “utopian” need of the philosopher to become the city's ruler, that is, to enforce in the city those “ideas” which can be perceived only in solitude (Arendt 2005:52-53).

The last chapter discussion on my interviewees efforts to get into action through crowd funding was also an attempt circumvent this tradition of political thought based on rule and obedience: their way to praise autonomy and their non-confrontation strategy empowered them to go on without rulers or regulation – as they would put probably put it. In spite of the fact that some of my interviews proudly acknowledge these strategies from a political theory perspective these same strategies need further investigation.

This chapter analyzes two branch of critiques relevant in this scenario. First by dismissing authority altogether, by praising autonomy and adopting a marginal path to institutions crowd funding communities end up in sort of self-sustaining echo chamber: technology allowed people with common interests to easily gather and support each other raising funds for projects that are unanimous inside this bubble. This seems a typical antipolitical _anything goes_ mindset as suggested by Schedler (1997:8): for him a political community “needs to be free from external constrains” as much as, “at least to a minimal degree, it must be able to impose internal constrains on its members.” At the same time this isolation in autonomous bubble is also a problem for the political in Mouffe's (2005:3) analysis:

[quote]
Instead of trying to design the institution which, through supposedly “impartial” procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant “agonistic” public sphere of contestation where different hegemonic political projects can be confronted.  

Besides this anti-political aspect sociology of ignorance is another source to shed light on the world view and the power structures involved in the crowd funding communities. This is the case when many interviewees seems to be so excited about the doors opened by crowd funding while they seems to have a blurred view – if any – of the boundaries and risks of such engagement. The bubble effect mentioned above is an example: most of the crowd funding community would say that being famous for 15 people (instead of having their 15 minutes of fame, as Lisandro put it) is inherently a good thing, without asking themselves if empowering any kind of 15 people group is actually a desired effect of politics. This is a characteristic of a strategic usage of ignorance useful to “maintain and to disrupt social and political orders, allowing both governors and the governed to deny awareness of things it is not in their interest to acknowledge” (McGoey 2012:4). 

The next two sections explore both the antipolitical and the sociology of ignorance critiques based on a few interviews in which my informants seemed to be keen of these possible downsides. Interestingly even those who pointed in the direction of these critiques were people convinced that being part of the crowd funding community – supporting projects and eventually creating their own projects – was a very interesting possibility in social, cultural and financial aspects. The tensions in handling these apparent opposing views are also explored below.

## Antipolitical crowdfunding

Adam, the Parisian amateur filmmaker introduced in chapter 3, was one among my interviewees who basically supported two kind of projects: the ones from friends or acquaintances, and the ones for causes he believed in. As he described this last category of projects I had the feeling they were basically progressive in terms of political affiliation: health organic cooking, woman empowerment, collective redesign of public spaces and so on. Following on that he declared he was very enthusiastic about crowd funding not only because it enabled him to donate to these causes, but basically because this mechanism allowed niche content to be produced, distributed and to reach their very specific public. He added that advertisement business model like the one behind YouTube (in which the creator of the video gets a percentage of the income from advertising according to the number of views of the video) failed on that, but crowd funding had a higher chance of succeeding.

His argument is based on the small percentage – less than 50% — of ad income that goes to the creator, and that only happens for videos with a really high number of views. For example a creator posting 20 videos per week with 1 million subscriber gets between 7 and 8 dollars per thousand views (Edwards 2014). This is a lot of effort to produce a massive amount of content – and still Google keeps more than half of the money.

Following Adam's thought if only 1% of the 1 million subscribers of the creator from the figures above donated her 1 dollar every month she would end up with the same annual income. Therefore Adam believes  there is potential for more productivity, more quality and less worries with inflating production and views in ad based platforms – let aside battling ad blockers. In order to make a living of niche content crowd funding seems more promising than YouTube ad income distribution. And my interviewees in general are very optimist about seeing more and more niche projects out there.

Next Adam and I talked about niches in the internet and he exposed an opinion that seemed pretty much convergent to the idea of echo chambers contained in small bubbles around the digital world. This is how he described the phenomenon:

[quote]
I have seen a lot of my old friends talking to the hand, people talking with people that agree with them.There is no debate at all. There is nothing being build that way either. People take things to the extreme and they manage to find other people agreeing with them. All out of sudden extremist ideas are a consensus. People start believing that whatever they were willing to believe beforehand is a consensus, is the obvious. For me this is the dynamics of social media nowadays.

Lisandro also also believes that these bubbles exists and that crowd funding revolves around this small communities. He actually used to get involved in the community going to meet ups and meeting people in person specially in some fields he is passionate about, such as literature for example. In fact this was an old habit from the time when he owned a second-hand bookstore: the business was not exactly profitable but it worth it because of the community that regularly gathered around the venue. This bubble effect is still valid in his crowd funding routine, as he describes the relationship between him and the project creators he usually supports:

[quote]
Even when I do not know them in person they are people I follow on Twitter, authors I like. I feel close to them as I follow the projects they run, so it is a group, you feel like you are part of it. There are also some video initiatives on YouTube I support because I watch the videos. I can pay one dollar a month for them, I can afford it if they keep on shotting new videos. I see this as clearcut exchange … I am willing to pay for the content [I consume] and when you actually know the person [creating that content], even if not in person but via social media, it is way easier to support their projects.

Emily, part of the team who founded a British crowd funding platform platform,footnote:[See chapter 3.] believes that this community effect around crowd funding is more attractive than the possibility of making money. In other words it is about a collaborative relationship, and not merely patron relationship in which one part supports the other financially:

[quote]
I do not think there is all that many people who set out because they are like “I want to make millions of pounds.” They kind of set out because they are like “I think this is a really interesting business model.” It shifts things so that some of the most effective Kickstarter projects are ones effectively getting user information. You get to connect with your users. You get to iterate and change your project much faster as you are going along and you get advanced orders so the risk is lower. It feels like a much more connected relationship that those projects typically have with the people who will be using that project.

Surely she is not denying that there are different mindset around crowd funding but for her this is not so common in regular crowd funding: “maybe that is something more [common] on the kind of equity based crowd funding platforms,” she ponders. Her argument also brings in a business mindset shared by other interviewees (Daniel, the German interested in board games, for example): the case in which a community of people connected by stronger ties reduces the economic risk of a enterprise. In sum there are different approaches the crowd funding community recurs to in order to emphasizes how the personal side of their relations grants a more coherent space for them. Within this space, and with cash circulating among people in this bubble, a lot of anew can be funded.

At this point it worth it call into question what are the issues the crowd funding enthusiasts might be leaving behind. If in last chapter I highlighted that Mouffe criticized Arendt's thoughts on the political on the grounds that her ideas would be too optimistic for the public realm, the same question is valid for my interviewee's world view. If the point of view argued in the last paragraph was the only side of this coin, autonomy would allow a plethora of ideas and actions in the public space, and crowd funding would allow people to join forces to make them happen. If that all was actually happening Mouffe (2005:3) arguments would be a harsh attack on the success of crowd funding as a form of political engagement:

[quote]
Instead of trying to design the institution which, through supposedly “impartial” procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant ‘agonistic’ public sphere of contestation where different hegemonic political projects can be confronted (Mouffe 2005:3).

Therefore the point is to highlight that crowd funding fails in all criteria of a this sort of heuristic proposed from this quote […]

NOTE: Expand on Mouffe arguing crowd funding 1) it is not impartial, 2) it does not reconcile conflicting interests and values (it is mostly an echo chamber) and 3) it does not allow hegemonic political projects to be confronted. Bring Shedler (1997) in to support the antipolitical side of it.

## Dodging dystopia

Adam's idea of niche contents mentioned in last section is indeed similar to Pariser's (2012) best seller _The Filter Bubble_ but Adam does not seem convinced that algorithms filtering our content is actually the only cause of these bubbles. Actually he is closer to Bishop's (2008) argument in _The Big Sort_: as a result of the success of the welfare state, the book claims, Americans felt free to move wherever they wanted in the continental country. These freedom resulted in a clearcut polarization reflecting like-minded groups: in general liberals moved to metropolitan centers such as New York and San Francisco while conservatives grouped in Orange County and Colorado Springs for example. This is a contrast compared to the 1970s when college degrees were not not polarized in specific urban centers. As Bishop Adam believes that technology is not the one to blame:

[quote]
Corporations have no ideology. They do what makes the most money, what gives them more profits – except in rare cases in which Facebook [for example] stands for Israel, for Jews etc. But most of the time you take any of the big media companies and you see some to the right, some to the left, but all of them will be focus in return of investments. If you take Fox News in the USA, there are people interested in that kind of content, people willing to put money on that. If we did not have these people, we would not have [Fox News]. I do not like this idea that Fox [News] causes conservatism. Both [people interested in Fox News contents, and Fox News itself] are parts of a cycle. And that is the same with crowd funding, and with social media. One can create mechanisms to bring conflict in, to bring discourse in, to promote the debate of opposing ideas. But people just do not care. That is not what they want.


NOTE: Lisandro and Sam as “anti crowd sourcing” voices – at least when not actually promoting the _sharing_ in the sharing economy.

NOTE: Emily and Chris's take on collaborative economy and crowd funding.

[quote]
Social scientists, in writing about ignorance, must better acknowledge their own ignorance of the unarticulated or simply unconscious rationales of the individuals they suggest may be deliberately harnessing ignorance (McGoey 2012:11).

NOTE: Heath and Potter (2005) on capitalism success in swallowing counter movements.
