= Conclusion and discussion
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
Antipolitical individualism celebrates unrestricted subjectivity, anti political tribalism unrestricted collectivity (or on a sub communal level). Both versions of anti-authoritarian revolt follow the same anarchical impulse: anything goes (Schedler 1997:9).

As this research discussed, crowd funding is not merely a technological platform. The way people engage with it establish a two-way relationship with the social surroundings: people come to these platforms with certain values and expectations and, in turn, those values and expectations are created and transformed in the community organized around the crowd funding campaigns. This is true about many phenomenon that have been created in the digital culture, also as discussed in this thesis. Beyond that the point was to inquiry about the nature of politics empowered and transformed by the emergence of crowd funding.

If I consider the extremes of an utopian and a dystopian perspective on that specific nature, the brightest possibility would be to understand that politics can be about empowering action — and not only about contemplation and deliberation, as in ancient Greece. Therefore opening more possibilities for ordinary people to act in a public space could be a form of (re)engagement in politics. That would sound promising in a world diagnosed by many scholars as anti-political, or even in societies in which other scholars have been labeling the new generations as disinterested in politics. 

Extending this hypothetical scenario, crowd funding would fight individualistic branches of antipolitics in as so far as each ideas, projects or proposals would still be dependent on a plurality in order to become action – (even if this plurality can be considerably smaller than the majority usually required by formal democracies. One could even argue that this new configuration for politics might favor plurality better than process such as consensus or deliberation, in which only one idea is allowed to survive after thriving. The intrinsic need of financial and community support to execute projects through crowd funding would create a kind of gatekeeper for individual moral and judgements, and, at the same time, create free and open spaces for the most different sort of dreams and initiatives.

However there is also the opposite scenario, an hypothetical scenario in which the nature of politics put forward by crowd funding is only dark and degrading. First of all the human right for a political voice would be dispensable: this kind of voice would be a privilege of those who can spare some money to pledge on campaigns – in other words it would consolidate many of the social and economic inequalities as _de facto_ political advantages and disadvantages. Secondly, constructive debating contrasting opposing ideas would became unnecessary as competing ideas would not need to be put to scrutiny if they are able to gather enough supporters. And in the process of gathering people to pledge in one or other project, probably social network range  and charisma would be consolidated as an official trace of political power.

Finally, in this dystopian future of crowd funding politics the public realm as a space to face the unknown, the different, the other would probably disappear. This emphasis on pluralism would make room for a multitude of tiny realms, which one of them ignoring the existence of the others. Maybe this might looks like a conglomerate of independent little tribes - a world in which empathy for the others, for people from different tribes, would be unimaginable: there would be no social ties between these tribes and humanity would probably be a thin red line between a Hobbesian tribalism and a hippie mindset.

Surely those extremes are not what we can find today. The nuances of the crowd funding community, together with the complexity of the modern society make the analysis much richer than that. However these scenarios might work as typologies useful for understanding critiques put forward by crowd funding, the possibilities opened by it, its limits, and also what is left behind when one look at crowd funding as a form of political action. 

The chapter before the previous one described what could be seen as the bright side of this form of politics. In sum this community has a coherent set of critiques towards incumbent institutions that are not unworthy allegations: they are aligned with a series of critiques from different scholars and different schools - they are not to be considered a rant from the young generations, but a picture of the dissatisfaction with the way power is handled in most of modern democracies nowadays. In addition the empowerment enabled by crowd funding is indeed capable of impacting the public realm some how: maybe by funding public goods, maybe as way to fund-raise for political causes, maybe by becoming an alternative career path for others (which might be seen as something belonging from the private sphere; however, the point here is not the personal choice of one or another individual for their own careers, but the very political act of saying and demonstrating in public that there are more options out there than advertised by governments and corporations).

In contrast, last chapter described how this reading of the political aspect of crowd funding has its own bias: I cannot discard the fact that many of my informants seem to favor the utopian typology of crowd funding. I understand they might not feel represented in their democracies, and they might not feel respected in careers in more traditional companies. I also can relate to the critiques they raise calling in to question the lack of freedom from social, political and economic inequalities. However I do understand that what I have heard are their personal accounts, and I must take things in perspective to address the subjectivities: the dark ones emerging from all these dissatisfactions, but also the bright ones that might emerge in the cases they can find some comfort. As crowd funding might be at the core of the spaces in which they find some comfort, it is expected they favor the utopia over the dystopia.

In spite of that, the sociological analysis from that chapter shed light on strategies my informants recur to – either in conscious or unconscious ways. These strategies are clear signposts of the antipolitical aspect embedded in the nature of the politics of crowd funding, that is to say, they are the rapport of those who succeeded in crowd funding, who are happy and engaged in the community. In addition these strategies corroborates what I claimed in last paragraph: a systematic and comprehensive over valuation of crowd funding as the mechanism that opened many doors for my informants; and, at the same time, a systematic act of ignoring other social aspects that would not contribute for the consolidation of their comfort zone through crowd funding.

Surely a more complete analysis on the topic should include more critiques of crowd funding, people who have had mostly bad experiences or even people who would decline to take part in these platforms altogether. If the most common example of the success of crowd funding is the musician next door who now can have their album recorded, a holistic state of the art of crowd funding should take into account the voice of incumbent representatives of the major players in the recording industry – something considered valuable, but out of the scope of this research.

This research offered a comprehensive and complex description of people highly engaged in crowd funding, in different countries and in different platforms. The findings were pretty much in consonance with a diverse literature discussing the boundaries of modern democracies. In that sense, crowd funding might be another case study in social science schools arguing that representativeness is a weak characteristic of most political spaces nowadays, in the ones articulating complex relations between the public and the private, and in the field of politics and digital culture.

Specific in these studies of internet and society, the case built here on crowd funding reinforces arguments such as the power of micro donations of time, and of the re-shaping of (political) leadership in the digital world. It also corroborates the critiques of the limits and boundaries that usually come altogether in these studies. Yet, in a more broader sense, the study of crowd funding and society showed itself relevant in discussions about the social life of money and the social aspects of jobs and careers.

Underneath the choice to study a particular case, using very qualitative methodologies, was the potential to understand the broader and complex social environment we live in from these small scales case studies. Here the digital version of passing the hat was a powerful entry point to discuss overarching topics on political theory and modern states.

That said, some readers might ask what to expect from crowd funding. Being normative or prescriptive is not the task of this descriptive sociological inquiry. However some important points can be reinforced in this last few paragraphs.

First of all is the problematic – or even inexistent – public realm in modern societies. To put it differently, the over privatization of every realm of social life pushed people to forge alternatives. Crowd funding was a way through which my interviewees found some relief, a place in the margins (as Felipe said) in which they can risk the anew.

Second, this perception call into question scholars that defend that people are alienated from politics. In fact, the very same people might be seen as desperately citizens trying to find a way to be political – precisely because incumbent political institutions seems too corrupted by private interests, they have to pave their own way to try to be political.

Lastly, the (self) perception that crowd funding is indeed working in the political sense for some people is not enough: the political is not about merely freedom of expression and waving your own banners. Politics is about dealing with differences – and there are several ways to do that: balancing powers and imposing constrains, trying to address conflicts with debates and so on. Crowd funding might mimic one or another trace of this ideal public space, but it fails in several others. On the one hand it is an alternative to empower some non-hegemonic world views, to support minorities, and to try to execute projects that are out of the radars of incumbent institutions. This is very political indeed. However, on the other hand, crowd funding also is undeniable a private realm: it is not universally accessible, it has minimum (if any) social control on imposing its own boundaries, and its parallel to vote is in fact money – one of more iconic symbol of worlds inequalities. These tensions coexist in crowd funding – as well as in many other instances of the problematic public space most modern democracies have today.
