= Conclusion and discussion
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

'''
(lost bits from methodology & literature review)

Returning once more to the extremes of an utopian and a dystopian perspective, the brightest possibility would be to understand that politics can be about empowering action — and not only about contemplation and deliberation, as in ancient Greece (Arendt 1998). Therefore opening more possibilities for ordinary people to act in public could be a form of (re)engagement in politics. In that scenario individualistic antipolitics would be declined in as so far as each idea, project or proposal would still be dependent on a plurality in order to become action (even if this plurality can be considerably smaller than the majority usually required by formal democracies; and surely that suggests that plurality would emerge stronger than consensus or deliberation). The intrinsic need of financial and community support to execute projects through crowdfunding creates a kind of gatekeeper for individual moral and judgements, and, at the same time, create free and open spaces for the most different sort of dreams and initiatives.

However political theory also suggests a dark possibility. For instance Weber’s (1986) late writings argue that his disavowal of the bureaucratic administration could be overcome by a charismatic leader — a concept usually employed as opposed to tradition and legal forms of authority in Weberian theory. He argued that a leader was necessary to revitalize the arguably inefficient German government. The problem was the “completely outmoded system of management by notables” (Weber 1986:130), that is to say, old professional and bureaucratic politicians, which was actually preventing the brightest intellectuals from engaging in politics. Charisma would be the basis of this new political leader, who should be strong enough to dissolve the parliament if needed. Explicitly he argued for a strong president, empowered through election, as an alternative to challenge the power of the parliament, the outmoded system.

Weber passed away in 1920 and between his and Arendt’s oeuvre Germany testified the emergence of the National Socialist dictatorship. A leader in fact was granted these powers in 1934 by almost 90% of the voters. A leader that would merge the role of president and chancellor, dissolve the parliament and opposing parties and interrupt all efforts to revive democracy in Germany after the Great War. Ironically a leader whose terror is one of the most important inspirations for Arendt’s first writings on politics and philosophy. In sum, politics based on individual impulses, even if controlled by formal institutions, can destroy democracy and politics.

This sort of theoretical questions are the background of this research: the more practical predisposition of people engaged with crowdfunding, as well as their justifications in terms of world views, are at the foreground of this research; at the same time the background is set by these overarching dilemmas of political theory, such as freedom, political action and what constitutes a democratic and active public sphere.

'''

NOTE:  _Authority vs. Anything goes_ (Schedler 1997). Politics “must be able to impose internal constrains on its members” (8). Horizontal and positive idea of power (Arendt 1973) vs.  Weberian negative and vertical, based on the use of violence exclusively by the state.  “Antipolitical individualism celebrates unrestricted subjectivity, anti political tribalism unrestricted collectivity (or on a sub communal level). Both versions of anti-authoritarian revolt follow the same anarchical impulse: anything goes” (9).
