= Isolation, silence and absence
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
The state is a modern phenomenon and its _raison d'être_ was to develop, or better, to capitalize the power of society – the power resident in the human activities, and transactions that sustain life relationships, and its changing needs. The state became a coercive agency, declaring and enforcing law, punishing miscreants of all descriptions, systematizing taxation, encouraging commerce and manufacture in the direction of national economies, conducting diplomacy, waging war, and seeking empire. Its characteristic form of action is the decision which it "makes" with relentless regularity; its typical expression is the announcement of a "policy," and its mode of governance ranges from inducements to force (Wolin 1983:17).

The last chapter started with the introspective tone of Arendt's analysis on citizenship, especially when theorizing about the political realm. In a normative way she claims the concept of action is what should lie at the core of politics, and as a consequence, citizens were expected to engage in a _vita activa_. However, in practice that is not what happened: her diagnosis of modern representative democracies is far from this ideal. As discussed Arendt herself concluded that there is a lack of space for action, for example, since the private realm expanded too far from its original intends.

On top of that she ponders on the motives underneath this privatization of the public realm – not a privatization in the neoliberal way of conceding public interest endeavours to the private initiative, but as a way to signal that private interests are acting in places in which public interests were expected.

At a certain point Arendt discusses the concept of forgiveness together with action and the industrial revolution (2005:57-59). According to her as action is the foundation of the anew, forgiving "attempts the seemingly impossible, to undo what has been done." As a consequence, "it [forgiveness] succeeds in making a new beginning where beginnings seemed to be no longer possible." This is relevant in her argument as she foresees a structure that is typical in complexity theory:footnote:[To be clear I am not saying that Arendt is referring nor subscribing to complexity theory. Also I am not claiming she is a precursor of this field. The point is that, as Arendt (2005:58) put, "men (_sic_) do not know what they are doing with respect to others, that they may intend good and achieve evil, and vice versa, and that nevertheless they aspire in action to the same fulfillment of intention that is the sign of mastership in their intercourse with natural, material things, has been the one great topic of tragedy since Greek antiquity." To a certain extent this acknowledgement is also found in complexity theory in which systems are non-linear, non-teleological, and their outcomes are highly unpredictable (Mitleton-Kelly 2003).] that actions leads to "a chain of unpredictable consequences" in which even the person who acted ends up as "both actor and victim in this chain of consequences." Finally, she highlights how the technological advances in the last decades, together with this complexity of action and forgiveness, have made of action a sort of volatile basis for modern democracies:

[quote]
It was only with the sudden and disconcerting rush of the gigantic technical developments after the industrial revolution that the experience of fabrication achieved such an overwhelming predominance that the uncertainties of action could be forgotten altogether; talk could then begin about "making the future" and "building and improving society" as though one were talking about making chairs and building and improving houses" (Arendt 2005:58).

Her normative approach allows her to critically study the shifting boundaries of the private and the public, and discuss how citizens themselves have a blurred understanding of the boundaries of private and public interests – let alone the realms for each of these approaches. In ancient Greece only a small percentage of citizens were allowed in the public arena; among other reasons because only the ones with land and slaves were able to provide for themselves and their families, or in other words were able to leave private interests aside when stepping into the public arena.

Industrial revolutions and specially the rapid industrial growth in the second half of the twentieth century might have made labor and work easier and abundant, and as a result made the production of goods cheaper and also abundant. Arguably it could be expected that this new technological progress would end up alleviating the weight on citizen shoulders when it comes to meeting their private interest and needs: it would be easier for them to provide for their families, labor would be gradually taken over by machines, the production of food, supplies and all sort of goods would get cheaper over time. And once the pressure to provide was minimized by this new condition, engaging in action in the public realm would be easier than ever. In sum, with the help from industrial equipment and automation, wage earners and entrepreneurs would easily be well off, especially when compared to their ancient Greek ancestors.

However this is not what happened. For Arendt the success in managing private interest has not enabled more and more citizens to devote themselves to the public interests. Instead it has actually pushed society to transpose the logic of one realm to the other, that is to say, this scenario has led to an attempt to apply the same logic guiding the private realm into the public realm. And yet according to Arendt (1973) that move has led to a bold transformation: indeed, what was known as the public realm became a massive social realm – a gigantic bookkeeping activity, as we see in the news about our democratic chosen representatives. Even worst for Arendt's normative speculations: the state has become a place for bureaucratic rulers, not for doers of great deeds. And for her this was not a surprise: in ancient Greek there were already two ideas of rulers and ruled, a very authoritative source of power, and another that was more interesting for freedom of ideas and politics:

[quote]
The concept of rule, as we find it in Plato and as it became authoritative for the tradition of political thought, has two distinct sources in private experience. One is the experience which Plato shared with other Greeks, according to which rule was primarily rule over slaves and expressed itself in the master-servant relationship of command and obedience. The other was the "utopian" need of the philosopher to become the city's ruler, that is, to enforce in the city those "ideas" which can be perceived only in solitude (Arendt 2005:52-53).

The preceding chapter focused on my interviewees efforts to get into action through crowd funding was also an attempt to circumvent this tradition of political thought based on rule and obedience: their way to praise autonomy and their non-confrontation strategy empowered them to go on without rulers or regulation – as they would probably put it. Whilst some of my interviewees proudly acknowledge these strategies, from a political theory perspective these strategies require further investigation.

This chapter analyzes two branches of critiques relevant in this scenario. First by dismissing authority altogether, by praising autonomy and adopting a marginal path to institutions crowd funding communities end up in sort of self-sustaining echo chamber: technology allowed people with common interests to easily gather and support each other, raising funds for projects that arguably are unanimous inside their own bubble, their own social circle – and, in some cases, unanimous only inside these circles. This scenario is indeed similar to a typical antipolitical _anything goes_ mindset as suggested by Schedler (1997:8): for him a political community "needs to be free from external constrains" as much as, "at least to a minimal degree, it must be able to impose internal constrains on its members." Yet at the same time this isolation in autonomous bubbles is also a problem for the political in Mouffe's (2005:3) analysis:

[quote]
Instead of trying to design the institution which, through supposedly "impartial" procedures, would reconcile all conflicting interests and values, the task for democratic theorist and politicians should be to envisage the creation of a vibrant "agonistic" public sphere of contestation where different hegemonic political projects can be confronted.

The first half of this chapter takes on this antipolitical argument. Following this, I draw on the sociology of ignorance in order to shed light on the world view and the power structures involved in the crowdfunding communities. This is the case when many interviewees seem to be so excited about the doors opened by crowd funding while they seem to have a blurred view – if any – of the boundaries and risks of such engagement. The bubble effect mentioned earlier is an example: most of the crowd funding community would say that being famous for 15 people (instead of having their 15 minutes of fame, as Lisandro put it) is inherently a good thing, without asking themselves if empowering any kind of 15 people group is actually a desired effect in political terms. This is a characteristic of a strategic usage of ignorance useful, "to maintain and to disrupt social and political orders, allowing both governors and the governed to deny awareness of things it is not in their interest to acknowledge" (McGoey 2012:4). The second half of this chapter goes deeper in this argument.

What follows is based on a few interviews in which my informants seemed to be keen to discuss these possible social and political costs of crowdfunding and platform building Interestingly even those who pointed in the direction of the antipolitical or ignorance critiques were people convinced that being part of the crowdfunding community – supporting projects and eventually creating their own projects – was a very interesting possibility in social, cultural and financial aspects. The tensions in handling these apparent opposing views were important sources of information for this chapter. Lastly, in some cases the unsaid ended up telling interesting parts of the history, therefore I try and explicate the importance of silences and absence when relevant to the analysis. When this happens the reader is clearly informed about it.

== Antipolitical crowd funding

Adam, the Parisian amateur filmmaker, was one among my interviewees who supported two kinds of projects: the ones from friends or acquaintances, and the ones for causes he believed in. As he was describing this last category of projects I had the feeling they were progressive in terms of political affiliation: healthy organic cooking, woman empowerment, collaborative redesign of public spaces and so on. Following on that he declared he was very enthusiastic about crowd funding not only because it enabled him to donate to these causes, but basically because this mechanism allowed niche content to be produced, distributed and to reach their very specific public. He added that advertisement business model like the one behind YouTube (in which the creator of the video gets a percentage of the income from advertising according to the number of views of the video) has failed on that. However, he sustains, crowd funding has a higher chance of succeeding in that task.

His argument is based on the small percentage – less than 50% — of ad income that goes to the creator. Also, he added this revenue is only a reality for videos with a really high number of views. For example, a creator posting 20 videos per week with 1 million subscriber gets between 7 and 8 dollars per thousand views (Edwards 2014). This is a lot of effort to produce a massive amount of content – and still Google keeps more than half of the money.

Following Adam's thought, together with the figures above, if only 1% of the 1 million subscribers of a given creator donated her 1 dollar every month, she would end up with the same annual income. Therefore, Adam believes there is, in crowd funding, a huge potential for more productivity, more quality and less worries about inflating production and views (as in ad based platforms; let aside battling ad-blockers). In sum, for him, in order to make a living of niche content crowd funding seems more promising than YouTube ad income distribution. And my interviewees in general are very optimist about seeing more and more niche projects out there.

Next Adam and I talked about niches in the internet and he shared an opinion that seemed convergent to the idea of echo chambers contained in small bubbles around the digital world. This is how he described the phenomenon:

[quote]
I have seen a lot of my old friends talking to the hand, people talking with people that agree with them. There is no debate at all. There is nothing being build that way either. People take things to the extreme and they manage to find other people agreeing with them. All out of sudden extremist ideas are a consensus. People start believing that whatever they were willing to believe beforehand is a consensus, is the obvious. For me this is the dynamics of social media nowadays.

Lisandro also believes that these bubbles exist, and that crowd funding revolves around these small communities. He actually used to get involved in the community going to meet ups and meeting people in person; especially in some fields he is passionate about, such as literature for example. In fact, this was an old habit from the time when he owned a second-hand bookstore: the business was not exactly profitable but it worth it because of the community that regularly gathered around the venue, he claimed. This bubble effect is still valid in his crowd funding routine, as he describes the relationship between him and the project creators he usually supports:

[quote]
Even when I do not know them in person they are people I follow on Twitter, authors I like. I feel close to them as I follow the projects they run, so it is a group, you feel like you are part of it. There are also some video initiatives on YouTube I support because I watch the videos. I can pay one dollar a month for them, I can afford it if they keep on shooting new videos. I see this as clear-cut exchange … I am willing to pay for the content [I consume] and when you actually know the person [creating that content], even if not in person but via social media, it is way easier to support their projects.

Emily, part of the team who founded a British crowd funding platform, believes that this community effect around crowd funding is more attractive than the possibility of making money. In other words, it is about a collaborative relationship, and not a merely patron relationship in which one part financially supports the other:

[quote]
I do not think there is all that many people who set out because they are like "I want to make millions of pounds." They kind of set out because they are like "I think this is a really interesting business model." It shifts things so that some of the most effective Kickstarter projects are the ones effectively getting user information. You get to connect with your users. You get to iterate and change your project much faster as you are going along, and you get advanced orders, so the risk is lower. It feels like a much more connected relationship that those projects typically have with the people who will be using that project.

She is not denying that there are different mindset around crowdfunding, but for her friends and contacts, trying to become rich  through crowdfunding was not seen as common or widespread in this environment: “maybe that is something more [common] on the kind of equity based crowdfunding platforms,” she ponders. Her argument also brings in a business mindset shared by other interviewees (Daniel, the German interested in board games, for example): the case in which a community of people connected by stronger ties reduces the economic risk of a enterprise. In sum there are different approaches the crowdfunding community recurs in order to emphasizes how the more personal side of their relations grants a more coherent space for them. Within this space, and with cash circulating among people in this bubble, a lot of anew can be funded.

At this point it worth it call into question what are the issues the crowd funding enthusiasts might be leaving behind. If in last chapter I highlighted that Mouffe criticized Arendt's idea of politics, on the grounds that Arendt's ideas would be too optimistic for the public realm, the same sort of question is valid for my interviewees' world view. If the point of view argued in the last paragraph was the only side of this coin, autonomy would allow a plethora of ideas and actions in the public space, and crowd funding would allow people to join forces to make them happen. If that all was actually happening Mouffe (2005:3) arguments would be a harsh attack on the success of crowd funding as a form of political engagement: that would be to completely eliminate the "agonistic" side of the public realm in favor of a multitude of niche endeavours that would never collapse and debate with each other. Different (and arguably hegemonic) projects and ideas could emerge, but they would hardly ever (if ever) be confronted.

To start with and taking Mouffe's quote from the beginning of this chapter, crowd funding is not an impartial procedure. This might be a multifaceted issue and probably it is not feasible to exhaust all possible ways to argue that impartiality is not a strength of crowd funding. My interviewees would argue in a kind of libertarian tone that anyone could pledge in any crowd funding campaign – and that would be enough to label crowd funding as "democratic" as they say, or as "impartial" as inferred by them. Surely this is not the case. The basic argument would be that not everybody is online (48% of the world is, 41% if we take only developing countries, or 81% in developed countries) and that not everybody online actually trusts the web enough to make an online payment (21% of Americans that are online are do not shopping online).footnote:[Figures regarding population with internet access according to ICT (2017) and the one about online payments according to Pew Research Center (2016).]

Moving away from assumptions based by quantitative surveys it is possible to discuss the impartiality of crowd funding also from qualitative standpoints. For instance, my interviewees, as discussed before, are very similar in terms of their social and educational background. They usually are people that have had access to higher education, that can take risks easier that others because they have a reliable safety net. Those from outside the global north have fluent English and some experiences abroad (usually they studied and/or worked in the global north). This fact cannot be ignored when pondering about the impartiality of crowd funding: these trajectories socially influence the way these individuals face the world, also influencing their personal values, strategies, aspirations and notions of right and wrong, of success and failure. All these aspects end up internalized as a disposition to act in a similar fashion (Bourdieu 1970):

[quote]
It is one thing to say that working-class youth do not enter French universities because they fear failure, and quite another to say that getting a higher education does not belong to their world view or class structure. In the former case, these youths might value higher learning and have hopes of attending the university but choose not to attend because they expect to fail. In the latter case, they would have no desire to attend the university and therefore no expectations (Swartz 1997:109).

In other words the crowd funding community share so much in common that it is expected that it will reproduce their values instead of acting as impartial platform (Tufekci 2014 and 2016) — especially when some of the platform founders and staff I interviewed explicitly recurred to the analogy of putting the curatorial layer to keep the platform a garden not a thicket (that is to say, they cherry pick the projects that go online, they help creators to produce videos, text and images passing a specific kind of message etc.). Even in face of some tensions (such as whether it is OK or not to use Kickstarter basically as a shop window) my interviewees share similar world views in many other perspectives.

Following Mouffe's quote crowd funding does not reconcile conflicting interests and values either. Beyond the similarity discussed above the mechanism itself is not focused in debating, in contrasting ideas, but mostly in isolating the needs (the financial target of each campaign) from the rest of the campaigns. In this scenario, even contradictory projects could end up funded and their supporters would never meet to discuss if these ideas can cohabit in the very same society. For example, at the same time as a white supremacist might be raising funds to keep their podcast production running, supporters of Black Lives Matter might be funding a documentary about their social movement. Actually, there were attempts from these opposing groups to raise funding through crowd funding. From the example mentioned a studio from London launched a campaign to shoot a documentary called "The Third Dimension: #BlackLivesMatter" (Indiegogo 2016). On the other hand, after being flagged in the media for hosting campaigns for white supremacists and neo-Nazis, many platforms started to bring down these specific campaigns (Independent 2017) – they were happy with political crowd funding, but certain agendas such as these extreme right-winged campaigns were not considered acceptable by the platforms terms.

I spite of these attempts for diversity of ideas and debate, this is might not be even expected in crowd funding. Chris is a scholar, an expert in sharing economy. He pondered on a basic profile of people engaged in crowd funding and in the sharing economy as a whole:

[quote]
What I've observed in the discourse around the sharing economy is the values and qualities that people project onto this technology are then reflected back out again in terms of the stories, the narratives about the sharing economy. Say those people who believe the internet is an inherently liberating democratic technology: that belief then shapes what they think the sharing economy is and can become. You get the actors who essentially talk about a sharing economy which is a very digitally enabled society and economy, but which is very libertarian, but more from the libertarian left philosophy.

The corpus of my field work tends to corroborate Cris's idea. But even if this is not true and the community is really diverse, ranging from neo-Nazis to #BlackLivesMatter, in both campaign examples above there was no debate on the validity of these ideas to society, neither on the possibility of the coexistence of these ideals in a civic public space. And even when the decision to not host campaigns for groups of a given credo, the decision was unilateral, non agonistc, as Mouffe believes democratic bodies should be. And yet this kind of decision might be, by itself, an argument in favor of the similar world views shared by the crowd funding communities: there is a great possibility that even if the crowd funding community allows multiple and diverse initiatives to be launched, it is arguably a political tool focused in a specific kind of public: it will respond to the specific demands of this specific public and amplify their range of action – ending up as an ever-growing echo chamber. Even if my interviewees believe they have the greatest intentions, this is not necessarily democratic in Mouffe's sense.

Finally, Mouffe's quote refers not only to the confrontation of ideas, but also to hegemonic political projects. In that sense there is arguably a two fold critique towards the crowd funding communities: the kind of projects they put forward are at most public goods with limited range. Cases like the crowd funding of public transportation or of museums are quite rare (Indiegogo 2014), and even if it can be considered a remarkable public good, it does not put different hegemonic political projects face to face. This museum case, for instance, put on evidence the figure of Nikola Tesla: they raised fund to buy the site of a well-known antenna designed by him and plan to open a museum there. In the popular culture the name of such this famous engineer arguably reinforces a very specific set of characteristics common to many of my interviewees: a utopian view of technology, a kind of vote for a frugal life, an open knowledge approach to people's own work (or, to put it differently, a controversial disavowal for copyright and patents) etc. And, again, if this political project is put forward by crowd funding, there is no hegemonic antagonism to it within the crowd funding community.

In Shedler's (1997:3) words politics involves "the definition of societal problems and conflicts, the elaboration of binding decisions and the establishment of its own rules." Crowd funding is a kind of open space where ideas mature in their own bubbles, without running into each other; in other words, the notion of conflict is downgraded because anyone can submit any idea, and the notion of problem is reduced in a pecuniary total, the target of the campaign. Once these pecuniary targets are reached there is no need for binding decisions or any kind of dependence between people involved in such projects and outsiders. And surely the highest bar crowd funding afforded to put in rules are unilateral decision taken by founders and staff of the platforms together with individual decision to support or not each project. Therefore, in spite of action empowering in Arendt's sense, there are strong critiques to consider crowd funding community as political from the perspective of the way they organize the interaction among its members.

Probably my interviewees would stand for crowd funding claiming that at least it allows projects to be funded outside the agenda of incumbent institutions. As government and corporations are important stakeholders in funding new endeavours, this argument is indeed important. For instance, from within the sociology of ignorance field, Hess (2015) alerts for the impacts of undone science (studies that strategically are not funded or are underfunded) in social movements and social change. For him (2015:142) "the idea of undone science draws attention to a kind of non-knowledge that is systematically produced through the unequal distribution of power in society," and this does not happen unintentionally; on the contrary "it involves the systematic underfunding of a specific research agenda, and the underfunding occurs through a continuum of mechanisms" (2015:143). As his research is based on undone science and social movements, the reinforces that certain kinds of investments are not made by incumbent institutions in order to refrain advances of certain agendas:

[quote]
Thus, in the U.S. today there is a proliferation of local first movements, bank local and local currency movements, cooperatives, credit unions, B corporations, worker ownership, and, to a lesser degree, the municipalization or remunicipalization of services, but these innovations tend to remain in a niche position with respect to the model of the publicly traded, large corporation. Instead, large corporations have selectively adopted some of the elements of the movements while simultaneously rejecting the fundamental challenge that they had aimed to propose (Hess 2015:148).

Sociology of ignorance can shed light on the dark side of crowd funding from a perspective that embraces an arguably positive use of ignorance, as described in this section: situation in which some aspects are left aside to empower an agenda that is cherished by the community. However sociology of ignorance can also shed light in other dissonances crowd funding recurs to in order to keep to its promises, revealing a negative aspect of leaving ideas and discussions unveiled and untouched; and that is what the following section is about.

== Dodging dystopia

Certainly, Adam's idea of niche contents (mentioned earlier in this chapter) is not an odd statement. Indeed, it is similar to Pariser's (2012) best seller _The Filter Bubble_, a book basically blaming algorithms for isolating people in bubbles of users alike: for example, Google show results similar to the ones you have already clicked in the past, or your Facebook feed is assembled from posts of things data science predicts you will probably engage with (like, share, comment or whatever keeps your attention within the social media website). This strategy pulls apart controversial contents from each and every online user.

However, in opposition to Parisier, Adam does not seem convinced that algorithms filtering our content is actually the only cause of these bubbles. Actually, he is closer to Bishop's (2008) argument in _The Big Sort_: as a result of the success of the welfare state, the book claims, Americans felt free to move wherever they wanted within the continental country. This freedom resulted in a clear-cut polarization reflecting like-minded groups: in general liberals moved to metropolitan centers such as New York and San Francisco, while conservatives grouped in Orange County and Colorado Springs for example. This bubble effect happened even before social media and the internet. As Bishop, Adam believes that technology is not the one to blame when it come to this topic:

[quote]
Corporations have no ideology. They do what makes the most money, what gives them more profits – except in rare cases in which Facebook [for example] stands for Israel, for Jews etc. But most of the time you take any of the big media companies and you see some to the right, some to the left, but all of them will be focus in the return of investments. If you take Fox News in the USA, there are people interested in that kind of content, people willing to put money on that. If we did not have these people, we would not have it [Fox News]. I do not like this idea that Fox [News] causes conservatism. Both [people interested in Fox News contents, and Fox News itself] are parts of a cycle. And that is the same with crowd funding, and with social media. One can create mechanisms to bring conflict in, to bring discourse in, to promote the debate of opposing ideas. But people just do not care. That is not what they want (Adam).

What Adam is suggesting is that there is an unequivocal bias in the way people communicate and in the way institutions intermediate this communication. Therefore, even if the crowd funding platforms have no active voice in the global and mainstream media, they depend on the strategies for reaching as many people as possible. This tends to build a strong dependency between crowd funding campaign and social media corporations – this is the best and cheapest way many of my interviewees have found to spread the word about each campaign. This fact introduces a kind of unattended bias in the crowd funding community as a whole: when my interviewees claim that there are projects out there, and that there people are free to contribute to any project they like, my informants are neglecting their own reliance on corporate media in order to publicize their platforms – thus compounding a cathartic but false impression of autonomy from the corporate realm. This reliance must be minimized and denied, even to themselves: strategic ignorance is thus embraced in order for their perception of their own autonomy to persist.

A starting point to re-frame this story, highlighting the often unknown or ignored aspects of crowd funding dynamics, can be found on the studies about how micro-donations are influencing politics (Margetts _et al_ 2013). In the case of online petitions campaigns there is a prominent importance of a new kind of leadership: there is "a general shift from leaders and elite to members or individuals" (Margetts _et al_ 2013:3). In other words, characteristics typical from online petition (and I might add, online crowd funding) campaigns create a new dynamic for political action in which:

[quote]
contemporary political mobilisations can become viable without leading individuals and organisations to undertake organisation and coordination costs, proceeding to critical mass and even achieving the policy or political change at which they are aimed (Margetts _et al_ 2013:19).

These characteristics includes, for example, micro donations (of time in online petitions and of time and money in crowd funding), low start-up costs (no need of great investments to launch an online petition or crowd funding campaign) and the importance of certain number of people willing to start (signing the petition or donating to crowd funding). Actually, this last example is crucial: most of the successful online petitions that reached a significant amount of signatures had a steep rise in the very first days. Margetts _et al_ (2013) argues that instead of having the trustworthiness of more incumbent institutions and leaders, these new online mobilizations are more passive to externalities – that is to say depending on the number of signatures already added to a given petition (and I might add, the amount of money already pledged in a crowd funding campaign) and on the people who shared the link for the campaign page. As Margetts _et al_ (2013:18) summarizes:

[quote]
In this environment, leadership is the aggregate of many low-cost actions undertaken by those willing to start, rather than the raft of actions and characteristics of the few with which it is normally associated. Of course, the group of starters will usually include at least one leader in a more traditional mould who has taken a higher-cost action: for example, the person who sets up a petition and circulates it to close associates in their immediate social networks. But the number of starters needed to get the mobilisation off the ground will be beyond that possible to obtain with strong ties to the initiator alone, but will be attained with weak ties, such as the friend of a friend of a friend on a social networking site, or the retweet of the retweet of a tweet … By providing this social information, internet-based platforms circumvent the need for other activities traditionally performed by leaders.

In this scenario the unattended subjectivities of how information circulates are very important. In spite of some of my interviewees (as Adam, for example) being willing to discuss the power of social media underneath the success of crowd funding, that kind of reflection was mostly seen in experts I interviewed for this research. And, as mentioned, this discussion is not a detail, but a relevant topic for any sociological inquiry aiming at understanding the social and political nature of crowd funding. Most of the people I talked too has shown a very optimist, maybe naïve, approach to the topic. Emily, for instance, focus on close networks, stronger ties, and link the emergence of crowd funding to national macroeconomic changes:

[quote]
It sort of feels like a shift away from consumer who just buys and producer into a much more collaborative relationship … Certainly the people that I've spoken with just tend to be characterized by a much more collaborative approach to the way that they want to run the project or the business … I do have some skepticism over the position of crowd funding more generally, particularly over Nesta involvement (I suppose) with it.footnote:[Nesta stands for National Endowment for Science, Technology and the Arts. It is a British innovation foundation that started with a £250 million endowment from the UK National Lottery. They were funders of the crowd funding platform Emily worked for.] Not that I think that it comes from any personal, not that I doubt the personal intentions of anyone, but I think the timing of it was coming in right when the government cuts were sort of being ushered in. Right after. There's a handy narrative.

Lisandro is an enthusiast of this sort of more collaborative business model, but he made a two-fold critique on crowd funding as political nowadays. While debating about kinds of powers acting in society he called expressiveness into question: for him there are two sorts of powers, an incumbent power (basically external from the community, power that has its sources in the incumbent institutions) and an effective power (felt as stronger within the crowd funding community). Therefore, this more collaborative empowerment was promising in putting people close to each other:

[quote]
My idea is that you basically flatten relationships, thus in reality incumbent power ends up weaker than effective power. And this effective power is established because one's own expression skills. Those who know better how to express themselves have some advantages because they can clearly show how passionate they are about a certain subject. The have way more power than people imbued with institutional power.

In addition, Lisandro also criticized the way corporate power is managing not only crowd funding but the sharing economy as a whole:

[quote]
I live in Copacabana, in Rio [Rio de Janeiro, Brazil]. In my building I guess there are only four permanent residents. The rest is all Airbnb. In a certain way these are disaggregating activities, [activities that makes] you monetize collaboration.

With these quotes Lisandro clearly highlight two topics that are left behind when people (including Lisandro himself) take an optimist view on the potential of crowd funding. First, we have all the subjective qualities of platforms and creators (for example, as he said, how well one can communicate their own ideas to the world), we also have the bubble effect. Second, we have the perception of a more open and collaborative mechanism to sort out ideas that is only possible through very centralized mechanisms: the crowd funding platform themselves and the social media with some reach, for example. It is only by ignoring these issues, and only by ignoring what unfolds from it (such as the effect of algorithms regulating how messages spread through social media, or the power of the platforms as intermediaries) that these kinds of communities can be perceived as an efficient and new form of political and democratic action.

When discussing autonomy, many interviewees mentioned the power of crowd funding to tackle the intermediary, the middleman, in some markets. I have discussed earlier how this might end up as the opposite: more power concentrated in the hand of a few platforms, less choices, (because these platforms have influence on the content reach) and, as a consequence, less debate. In other words, the libertarian freedom necessary for the _motto_ "there are projects out there and people are free to pledge in any of them" cannot be taken for granted. Beyond that, what might be left of the argument is the idea of crowd funding nurturing a more collaborative environment. At this point Sam, an expert in sharing economy, offered some critiques similar to Lisandro's:

[quote]
AirBnB is intermediary for short-term rentals and Uber is a taxi service, neither of which are really sharing. Especially Uber, I would say, is not sharing because it's a taxi service. You're not actually sharing a ride. From an environmental perspective, and I know there's the environmental arguments for the sharing economy, as far as Uber goes, it's people driving around in cars to pick other people up. It's facilitating greenhouse gas emissions, rather than preventing it.

The point here is that there are a series of questions that might downplay the political potential of crowd funding, or at least call into question how democratic these political possibilities really are. Hence it is crucial to ask whether this attitude of ignoring some issues grants some strategic advantages to enthusiasts of crowd funding (as well as to advocates of the sharing economy). It is not a matter of labeling informants naïve or Machiavellian, but as McGoey (2012:11) puts:

[quote]
Social scientists, in writing about ignorance, must better acknowledge their own ignorance of the unarticulated or simply unconscious rationales of the individuals they suggest may be deliberately harnessing ignorance.

In order to assess what is political about crowd funding it is mandatory to inquiry about the nature of the optimism declared by most of my interviewees. In other words, the claimed collaborative aspect as well as the social impacts expected from it must be investigated. At this point one possibility is to frame crowd funding together with social entrepreneurship, social innovation and other expressions commonly used to describe social impact of crowd sourcing, crowd funding and other economies brought to life by the intense use of the internet. Following this argument, the next step would be to understand what actually these labels mean – however as McGoey (2015) argues that is not a trivial task:

[quote]
What sets the 'social' entrepreneur apart from more traditional ones is an emphasis on _motivation_. According to Elkington and Hartigan, the new breed of socially aware entrepreneur is motivates by a deep sense of injustice at market imbalances that prevent disadvantaged from accessing market goods. 'Time and again,' they write, 'these entrepreneurs have had a life-transforming experience, some sort of an epiphany that launched them on their current mission (McGoey 2015:67, emphasis in original).footnote:[In this passage, McGoey is citing Elkington and Hartigan (2008), "two well regarded proponents of the concept [of social entrepreneurship\]" as McGoey (2015:66) introduces them.]

Following up with the discussion, she adds in the very next paragraph: "Unfortunately, specific definition of what that 'mission' may be and how it is accomplished are often quite vague" (McGoey 2015:67). In other words, recurring to social entrepreneurship and related areas might not offer a proper framework to discuss crowd funding as it is a blurred field _per se_. Moreover, even if this social mission was a valid purpose, it is another challenge to discuss how successful ventures actually are:

[quote]
Corporate benchmarks such as increased revenue, more generous dividends, or higher share valuations simply don't translate as neatly into measuring social outcomes as social entrepreneurs often presume. Most social entrepreneurs want to prove that their business practices or their activism yield positive social results – something that's dubbed, in the TED Head world, 'social return on investment' (SROI). Like generations before them, they quickly confront one of the oldest challenges of social sciences: proving causality. […] Given this challenge, many philanthropic institutions and social enterprises turn to proxy measures in order to gauge their effectiveness (McGoey 2015:70).

The point here is that there is much unsaid and unspecified about the social impact of crowd funding promises such as bringing people together, nurturing niche markets, and offering an arguably more collaborative alternative to the standard political options. In spite of the ideological and aspirational good vibes of the crowd funding community, there is no way to clearly prove or deny their social impact. As mentioned, it sounds reasonable to expect crowd funding to be a counterpoint to incumbent fund-raising agendas (as in Hess 2015, for example), however the general tone of their autonomy, (based on their "running on the margins of society" assumption) makes it difficult to assert the claims found during the my fieldwork. Even if it all seems to make sense, one must be attentive: for example, when McGoey (2015:77-78) discuss micro credit, despite the optimistic fuzz, the Nobel prizes, and all the acknowledgment of this arguably revolutionary loan mechanism, its real social impact is a failure for communities it was supposed to empower. Crowd funding still lacks such scrutiny  to be able to sustain its claims.

In other words, we can confirm that many projects came to life through a series of micro-donations coordinates my crowd funding platforms and social media – many projects that, a couple of decades ago, might have been unconceivable. In spite of that the political (and economic) effects of such endeavors is based on a naïve understanding of freedom: for crowd funding to be open and accessible for everyone to pledge in anything they like, one must consider that everybody is online, that filter bubbles does not exist, that everybody can spare some cash to pledge, that everybody is minimally digital literate and so on. In sum, a series of requirements that are not out there in the world. Alternatively crowd funding could be a strong political tool for specific groups: groups that is connected to the internet in a daily basis, groups of people close to each other online, groups that can save some money to donate to causes, content producers and gadgets, and groups that are either digital natives or well literate in technology. That is indeed a possibility, but this possibility is not what my interviewees claimed – they usually supported a more libertarian tone instead. Dismissing this libertarian tone what is left is, potentially, a rich political tool for a very specific public.

'''

Stephen, the British entrepreneur in the startup market, was one of the most skeptical on the possibilities of crowd funding as political action. But even him seemed to find a possibility, a kind of workaround to the arguably antipolitical and strategic use if unknowns within crowd funding:

[quote]
So, something like Uber and Airbnb: I have a real problem with them because I think if they were local businesses it would be fantastic. I love the use of technology but the fact that these guys now are… I mean Uber will end up owning every fucking taxi driver in the world … And then if you talk to some of the guys who use it they go "yeah, well it's quite good for us because we get more businesses." But in the end, it's a lot of power in one company. And I think it's kind of what I object to, there's no trickle, so it's making richer people even richer.

What is at stake here is a tension similar to the one discussed earlier: in the attempt to replace the middleman, crowd funding community vouched for a new middleman – replacing the stakeholder, but politically speaking, keeping a very specific gatekeeper for the political voices. This process is very similar to what happened in the digital culture industry (Allen-Robertson 2013): free culture activists pushed against pre-established cultural gatekeeper institutions (recording labels), break them down (with piracy and MP3 sharing) and open the door for a new range of corporation gatekeepers to take over (Spotify and Apple iTunes, for example). Likely what we have in this attempt from crowd funding to empower people ended up nurturing more institutions to manage people's political voices. On that matter Chris envisages that the hopes and aspirations of utopian (and maybe libertarian) takes on technology might be compromised by the way things evolve in modern capitalism – in an argument that resonates the power of capitalism to swallow counter culture, as suggested by Heath and Potter (2005), by Boltanski and Chiapello (2011), and as discussed in the previous chapter:

[quote]
I personally think that obviously the internet has the potential to support that type of economy, but it also has the potential if you view the internet as a commercial opportunity – and then that feeds into the idea that the sharing economy is a huge commercial opportunity as well. Then you get stories of the next app [mobile application] of the sharing economy is the next phase of e-business or is the next phase of the evolution of the internet.

In the stream of this argument this chapter shed light on the possibility of crowdfunding failing in its attempt to empower ordinary citizens – in spite of its potential to challenge incumbent institutions. The risk here is not that it might fail but that it might achieve the precise opposite: crowdfunding dependency on strong ties in social relations may fall short on the effects of isolation bubbles – in practice echo chambers that are not political at all. The illusion that this isolation might be fruitful in building a better world (as many interviewees mention) is blurred by the internal cohesion it fosters: inside the bubble everybody agrees with each other, money circulates enabling a plethora of projects and this gives the impression of success. However these bubbles are ineffective in changing its surrounding — and actually people form other bubbles might ignore the other bubble existence for good.

Beyond that it is inevitable to ponder on the power concentrated in the platform themselves — even if this argument was quite rare during my fieldwork. As discussed here it is not unthinkable to consider that platforms from times to times might diverge from their audience. This was the case with white supremacists and neo-Nazis, as mentioned, but also with nudity and adult content in struggles between creators and Patreon, for example (Dellinger 2018). As they play a central role, not only from the point of view of controlling what is allowed online, and not only as a financial trusty between enthusiasts and creators, platforms themselves become landmarks in the crowd funding scenario. People know what to expect from each platform, how  much to trust their online payment methods, what kind of users and projects are expected there and so on. Even if technology is available (as mentioned there are open source alternatives out there) the sort of trust and popularity one or other platform achieves is crucial for the success of the projects, making of it another barrier for diversity and confrontation.

Lastly crowd funding optimist claims seems to ignore its own bias, its own privileges in favor of a promise that is impossible to keep track of. This might not be a problem _per se_, but it is relevant when the question asked is whether or not crowd funding is a new and revolutionary way to do politics in the twentieth-first century. With a discourse that fails to offer the audience a clear path to social impact, crowd funding might fall short as well social entrepreneurship: it established its own values without dialoguing with the external world. Huge investments can go here and there (in social entrepreneurship and crowd funding) and outsiders will still lack precise measures of success or impact.

The first part of this chapter discussed the antipolitical aspects of crowd funding while the last part took into account possible strategic uses of ignorance. One could argue whether the dark side of crowd funding (from this chapter) is more or less relevant than the bright side (previous chapter). However, both analytical standpoints are important in framing a critical analysis of the possibility of crowd funding as politics. In fact, this tension might be relevant for other online mediums and might be interesting for sociology and political theory of the web as whole: usually phenomenon as such are not good or bad, right or wrong; usually they carry a share of incongruence and tensions, and shedding light on these topics is the role of social science.
