[#8-conclusions-and-discussion]
= Conclusions and discussion
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

[.lead]
Antipolitical individualism celebrates unrestricted subjectivity, antipolitical tribalism unrestricted collectivity (or on a sub communal level). Both versions of anti-authoritarian revolt follow the same anarchical impulse: anything goes (Schedler 1997:9).

As this research has discussed, crowd funding is not merely a technological platform. The way in which people engage with it is to establish a two-way relationship with the social surroundings: people come to these platforms with certain values and expectations and, in turn, those values and expectations are created and transformed in the community organized around the crowd funding campaigns. This is true about many phenomena that have been created in the digital culture, as also discussed in this thesis. Beyond that the point was to inquire about the nature of politics empowered and transformed by the emergence of crowd funding.

If I consider the extremes of a utopian and a dystopian perspective on that specific nature, the brightest possibility would be to understand that the politics put forward by these communities can be about empowering action to create the anew -- and, in most cases, the anew not allowed within the incumbent institutions. Therefore, crowd funding might be opening more possibilities for ordinary people to act in a public space, what could be read as a form of (re)engagement in politics and as a way to (re)balance the strengths in modern states' political arena. That would sound promising in a world diagnosed by many scholars as antipolitical, or even in societies in which new generations are labeled as disinterested in politics.

Extending this hypothetical scenario, crowd funding would fight individualistic branches of antipolitics in as so far as every idea, project or proposal would still be dependent on a plurality in order to become action -- even if this plurality can be considerably smaller than the majority usually required by formal democracies. It would also be possible to argue that this new configuration for politics might favor plurality better than current political mechanisms that are arguably set to stand for plurality, such as consensus or deliberation. Empowering numerous smaller groups might even sound more plural than processes in which only one idea is allowed to survive after a majority election, for example. The intrinsic need of financial and community support to execute projects through crowd funding would create a kind of gatekeeper for individual morals and judgements, and, at the same time, create free and open spaces for the most different sorts of ideas and initiatives.

However, there is also the opposite possibility; an hypothetical scenario in which the nature of politics as put forward by crowd funding is dark and degrading. First of all, it is a mechanism that dismisses the idea of political voice as a human right: this kind of voice would be a privilege of those who can spare some money to pledge on campaigns. In other words, it would consolidate many of the social and economic inequalities as _de facto_ political advantages and disadvantages. Second, constructive debating and contrasting opposing ideas would become unnecessary as competing ideas would not compete among them if they are able to gather enough supporters -- many ideas would became real without scrutiny or consensus. And in the process of gathering people to pledge in one or other project, it would probably be the case that the social network range and charisma would be consolidated as an official and crucial asset of political power.

Finally, in this dystopian future of crowd funding politics, the public realm as a space to face the confronting idea, the different, the other, would probably disappear. This emphasis on pluralism would make room for a multitude of tiny realms, with each one of them ignoring the existence of the others. Maybe this might look like a conglomerate of independent little tribes - a world in which empathy for the others, for people from different tribes, would be unimaginable: there would be no social ties between these tribes (and humanity as a whole) and there would probably be a thin red line between a Hobbesian tribalism (between each group) and a hippie mindset (within each group).

Surely those extremes are not what we can find today. The nuances of the crowd funding community, together with the complexity of the modern state and its private and public realms, make the analysis much richer than that. However, these scenarios might work as typologies useful for understanding critiques put forward by the phenomenon of crowd funding, the possibilities opened by it, its limits, and also what is left behind when one look at crowd funding as a form of political action.

Chapter 6, _A New Realm to Empower Action_, described what could be seen as the bright side of this form of politics. In sum, the crowd funding community has a coherent set of critiques towards incumbent institutions, critiques that cannot be completely dismissed: they are aligned with different analysis and criticism from different scholars and different schools of political theory, sociology and anthropology, as discussed in this thesis. This alignment is an argument to dismiss the possibility of taking this discourse, focused on challenging incumbent institutions, as mere rants from the young generation. In opposition, this political position helps in an overarching framework to address the dissatisfaction with the way power is handled in most modern democracies nowadays. In addition the empowerment enabled by crowd funding is indeed capable of impacting on the public realm somehow: maybe by funding public goods, maybe as a way to fund-raise for political causes not usually supported by other means, maybe by becoming an alternative career path for others. This last case might be seen as something belonging to the private sphere, however, the point is not the personal choice of one or another individual regarding their own careers, but the very political act of saying and demonstrating in public that there are more options out there than the traditional career path and life goals put forward by governments and corporations.

In contrast, the last chapter, _Isolation, Silence and Absence_, described how this reading of the political aspect of crowd funding has its own bias: it is impossible to dismiss the fact that many of my informants seem to favor the utopian typology of crowd funding; I understand they might not feel represented in their democracies, and they might not feel their personal values and goals are respected in careers in more traditional companies. I also can relate to the critiques they raise calling in to question the lack of freedom from social, political and economic inequalities. However, I do understand that what I have heard are their personal accounts, and I must take things in perspective to address the subjectivities: the dark ones emerging from all these dissatisfactions, but also the bright ones that might emerge in the cases where they can find some comfort. As crowd funding might be at the core of the spaces in which they find some comfort, it is expected they favor the utopia over the dystopia.

In spite of that, the sociological analysis from that chapter has shed light on strategies my informants refer to, either in conscious or unconscious ways. These strategies are clear signposts of the antipolitical aspect embedded in the nature of the politics of crowd funding. Yet, these rapports refer to people who have succeeded in crowd funding, who are happy and engaged in the community. In addition, these strategies corroborate what I claimed in the paragraph above: a systematic and comprehensive overvaluation of crowd funding as the mechanism that opened many doors for my informants, and, at the same time, a systematic act of ignoring other social aspects that would not contribute to the consolidation of their comfort zone through crowd funding.

Another crucial aspect of crowd funding is the platforms themselves. As discussed earlier, instead of a neutral support for this mechanism, they become a powerful player in politics if is there a possibility of politics within crowd funding. My informants seem to overlook this potential problem as most of the time they feel aligned and represented by the curatorial layer imposed by these platforms. However, in an Arendtian sense, the freedom to act politically, the freedom to create the anew cannot depend on the behavior and directions of private platforms as crowd funding companies. Beyond that, the mechanism at stake is quite dependent on social networks -- another layer of control directly influenced by the private sphere. In both cases, crowd funding platforms and social network platforms, the corporate policies and algorithms have a direct impact on the supposed neutrality of the utopia if there are projects out there and anyone can pledge on them:

[quote]
On many platforms, including Facebook, algorithmic manipulations are performed routinely; they range from purposes as mundane as deciding the color of a button, to decisions as significant as which news article is shown to the public. These decisions are increasingly central to social, political, and civic processes; consequently, the algorithmic harms that may arise from such computational form a brand new category, including a spectrum of issues from libel to violence (Tufekci 2015:205).

Although this concern was not so clear in the voice of my informants, this might also be justified by their success and alignment within the crowd funding community, whilst this does not suffice to completely dismiss the argument raised by the platform capitalism critique. If Arendt argued that citizens must be free and empowered to participate in the public realm, it is problematic to consider that a privately owned set of platforms are the basis for this participation. This debate is crucial and it is not about how evil or how benevolent a corporation can be. Instead, this is a matter of paramount importance to rethink the public and private spheres, agency and the future of our society as a whole:

[quote]
Computational agency is expanding into more and more spheres […] They are armed with our data, and can even divine private information that we have not disclosed. They are interactive, act with agency in the world, and are often answerable only to the major corporations that own them. As the internet of things and connected, "smart" devices become more widespread, the data available to them, and their opportunities to act in the world will only increase. And as more and more corporations deploy them in many processes from healthcare to hiring, their relevance and legal, political and policy importance will also rise. This is a novel challenge, with little to draw from human history as either a metaphor or an analogy (Tufekci 2015:217).

Surely a more complete analysis on the topic should include more critiques of crowd funding, people who have had mostly bad experiences or even people who would decline to take part in these platforms altogether. If the most common example of the success of crowd funding is the musician next door who can now have their album recorded, a state of the art crowd funding should take into account the voice of incumbent representatives of the major players in the recording industry, or people criticizing the fact that the musician next door should get his album recorded, what Keen (2007) calls the _cult of amateur_. Those voices are valuable, but out of the scope of this research.

This research has offered an in-depth and nuanced description of people highly engaged in crowd funding, in different countries and in different platforms. The findings resonates with a diverse literature discussing the boundaries of modern democracies. In that sense, crowd funding might be another case study in social science schools arguing that representativeness is a weak characteristic of most political spaces nowadays, in the ones articulating complex relations between the public and the private, and also in the field of politics and digital culture.

Specifically in these studies of the internet and society, the case built here on crowd funding reinforces arguments such as the power of micro donations of time, and of the re-shaping of (political) leadership in the digital world (Margetts _et al_ 2013). It also corroborates the critiques of the limits and boundaries that usually come altogether in these studies, and correlated areas such as platform capitalism (Tufekci 2014, 2015 and 2016). Yet, in a broader sense, the study of crowd funding and society showed itself relevant in discussions about the social life of money (Graeber 2011, Dodd 2014) and the social aspects of jobs and careers (Potter 2015).

Underlying the choice to study a series of particular cases and life trajectories, using very qualitative methodologies, was the potential to understand the broader and complex social environment we live in from these small scale case studies. Crowd funding, the digital version of passing the hat, was a powerful entry point to discuss overarching topics such as world views, personal values and aspirations and, as a consequence, political theory and modern states.

That said, some readers might ask what to expect from crowd funding. Being normative or prescriptive is not the task of this descriptive sociological inquiry. However, some important points can be reinforced in these last few lines. The first of all is the problematic -- or even nonexistent -- public realm in modern societies. To put it differently, the over-privatization of every realm of social life has pushed people to forge alternatives in which they can do something that is not career- or profit-driven in the more traditional sense. Crowd funding is a way through which my interviewees find some relief, a place in the margins (as Felipe said) in which they can risk (and fund) the anew. Second, this perception calls into question scholars that defend that people are alienated from politics. In fact, the very same people might be seen as desperate citizens trying to find a way to be political -- and precisely because incumbent political institutions seem too corrupted by private interests, they have to pave their own way to try to be political. Finally, the (self) perception that crowd funding is indeed working in the political sense for some people is not enough: the political is not merely about freedom of expression and waving your own banners. Politics is about dealing with differences -- and there are several ways to do that: balancing powers and imposing constraints, trying to address conflicts with debates and so on. Crowd funding might mimic one or another trace of this ideal public space, but it fails in several others. On the one hand it is an alternative to empower some non-hegemonic world views, to support minorities, and to try to empower projects that are out of the radars of incumbent institutions. This is very political indeed. However, on the other hand, crowd funding is also undeniably and intrinsically linked to the private realm: it has minimum (if any) social control on imposing its own boundaries, and it is not universally accessible as money is its ballot -- one of more iconic symbols of worldwide inequalities. On top of that, crowd funding is usually built upon centralizing platforms that converge in themselves a series of powers in terms of curatorial, financial and strategic positioning. These tensions coexist in crowd funding -- as well as in many other instances of the problematic public space most modern democracies have today.

On top of that, this research was based on a very specific public in terms of class. As mentioned in chapter 4, _Re-signifying Money_, in spite of their origins from all around the globe most of my interviewees represent a very specific cutout in terms of social and economic class. Therefore their opinions and, consequentially, the tone of this thesis are representative of a particular public: high level of digital fluency, well-educated and well-off in terms of making a living -- to mention a few characteristics relevant for the understanding of the context surrounding the arguments sustained here. The point is that even when discussing digital culture and the internet as a whole, this might not be a typical profile. I based this research on a culture of internet heavy users, graduated, relatively privileged in the economic sense and, finally, with some degree of entrepreneurship in their veins (a risky endeavor propelled, at least in part, by a safety net assured by their social and economic position of privilege).

Hence this research also highlighted what crowd funding can tell us about the tensions present in the overarching society we live in. In other words, the possibility of political action discussed so far can stretch, at maximum, to a very specific group (and minority), represented by the point of view of my atypical and privileged interviewees. In spite of that, most of these tensions resonates the literature about the modern state, democracy and antipolitical concepts in the last few decades. This research focused on crowd funding reinforced many of the critiques held by theses scholars, linking this theories and arguments to the debates held by STS (Science and Technology Studies). The utopian view on the openness of the internet is present in the free way people connect to each other to support projects and causes in the platform capitalism. Also, this thesis brought in the will to be political and to be social in both these contexts: the open internet and the turbulent political institutions from the twentieth century. Yet the fact that my informants seem to have restrictions on incumbent institutions such as governments and corporations shows that these institutions are failing in making a world in which people are free to act according to their will, reinforcing the challenges we face in terms of contemporary political institutions and in terms of contemporary political theory.
