= Thesis outline
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

== Introduction
_~3k words (pending)_

== Methodology and literature review
_1st draft done: 11k words_

== Resignifying money
_1st draft done: 12k words_

=== TODO
* Reinforce how they are more difficult to be “captured” by corporations because money cannot buy them as professionals.
* Reinforce that they are looking for more “authenticity” within capitalism (in the sense of being less corporative)
* Move literature review to the beginning of the chapter
* Contrast secondary research data with theory and with interviews

== Autonomy
_1st draft done: 10k words_

=== TODO
_Feedback pending._

== Politics within crowd funding communities: the bright side (provisional title)
_1st draft done: 10k words_

=== TODO
* Reinforce their belief that bringing people together (instead of following corporation/government initiatives) means bringing power to the people;
* Reinforce how this challenge should not be on the level of discourse (eg. academic/opinion in the media) or confront (eg. anti-G8, occupy), but of concrete and tangible action (that's why they value money and autonomy, and also that's why they challenge incumbent institutions).  

== Politics within crowd funding communities: the dark side (provisional title)_10k words (pending)_
_~12k words (in progress, 3k done)_

== Discuss & conclusions
_~6k words (pending)_
