= Thesis outline
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

== Introduction
_~3k words (pending)_

== Methodology and literature review
_1st draft: 11k words (1st version done)_

== Resignifying money

_1st draft: ~11.5 words (1st version done)_

Describe their approach to money, that is to say, they differ (even if slightly) from the accumulative behavior; highlight that money means at the same time autonomy and the possibility to make some projects tangible (in other words, making something meaningful real; for them, meaning beats accumulation as an end in itself).

=== TODO
* Reinforce how they are more difficult to be “captured” by corporations because money cannot buy them as professionals.
* Reinforce that they are looking for more “authenticity” within capitalism (in the sense of being less corporative)
* Move literature review to the beginning of the chapter
* Contrast data with theory

== Autonomy
_10k words (1st version done)_

Describe the way they define and pursue autonomy, as they dismiss external judgement in general (specially from incumbent institutions) they are not afraid to assume their own subjective judgements about the world and about their own choices; yet, by assuming this subjectivity, they usually dismiss the idea of _changing the world_ as they would like to make room for everybody to be autonomous (specially when it comes to being independent from any incumbent institutions).

== Politics: the bright side
_~12k words (pending)_

* Describe their arguments to distrust the way decisions are made by arguably instrumentalized institutions, and how they believe that bringing people together means bringing power to the people; yet this challenge should not be on the level of discourse (eg. academic/opinion in the media) or confront (eg. anti-G8, occupy), but of concrete and tangible action (that's why they value money and autonomy, and also that's why they challenge incumbent institutions).  
* Arendt's ideal of the political as a space for action and crowd funding community efforts to distance themselves from labor.
* Reinforce that even if they are acting in public, building public goods, the public sphere itself still apolitical (no discussion/debate, little and scattered deliberation, and isolation in bubbles)
* One the one hand it is still impossible to pursue the classical public sphere, but on the other hand something anew is being confirmed in the sense of a chaotic pluralism.

== Politics: the dark side
_10k words (pending)_

* Discuss Arendt ideal of democracy (and mainly its problems) based on Wolin (1983).
* Compare Chantal Mouffe and Arendt's ideals of agonist democracy

== Discuss & conclusions
_~3k words (pending)_
