= Thesis outline
:numbered:
:sectanchors:
:icons: font
:stylesheet: ../contrib/print.css

_Total: 56k words_

== Introduction
_3k words_

== Methodology and literature review
_13k words_

=== TODO
* Arendt: early-adopter of _the social_ (Halewood 2014), but arguably she mostly referred to the _the social realm_ (which has a way ore precise definition)

== Resignifying money
_11k words_

=== TODO
* Reinforce how they are more difficult to be "captured" by corporations because money cannot buy them as professionals.
* Reinforce that they are looking for more "authenticity" within capitalism (in the sense of being less corporative)
* Move literature review to the beginning of the chapter
* Contrast secondary research data with theory and with interviews

== Autonomy
_10k words_

=== TODO
* I still have to work on the feedback given (Word document with comments & suggestions)

== A new realm to empower action
_9k words_

=== TODO
* Reinforce their belief that bringing people together (instead of following corporation/government initiatives) means bringing power to the people;
* Reinforce how this challenge should not be on the level of discourse (eg. academic/opinion in the media) or confront (eg. anti-G8, occupy), but of concrete and tangible action (that's why they value money and autonomy, and also that's why they challenge incumbent institutions).  

== Isolation, silence and absence
_8k words_

=== TODO
* I still have to work on the feedback given (Word document with comments & suggestions)

== Discuss & conclusions
_2k words_
