= Thesis outline
Eduardo Cuducos
:homepage: http://cuducos.me
:numbered:
:toc:
:sectanchors:
:icons: font

*Eduardo Gonçalves* +
_3^rd^ year PhD student in sociology, University of Essex_

. *Introduction* _(~3k words)_
. *Methodology and literature review*
. *Money* _(~10-12k words)_: describe their approach to money as different from the accumulative behavior, highlighting that money means at the same time autonomy and the possibility to make some projects tangible (in other words, making something meaningful real, for the, beats accumulation as an end in itself; also reinforce how they are more difficult to be “captured” by corporations because money cannot buy them as professionals.
. *Autonomy* _(~10-12k words)_: describe the way they define and pursue autonomy, whereas they dismiss any external judgement (specially from incumbent institutions) they are not afraid to assume their own subjective judgements about the world and about their own choices; yet, by assuming this subjectivity, they usually dismiss the idea of _changing the world_ as they would like to make room for everybody to be autonomous (specially when it comes to being independent from any incumbent institutions).
. *Challenge* _(~10-12k words)_: describe their arguments to distrust the way decisions are made by arguably instrumentalized institutions, and how they believe that bringing people together means bringing power to the people; yet this challenge should not be on the level of discourse (eg. academic/opinion in the media) or confront (eg. anti-G8, occupy), but of concrete and tangible action (that's why they value money and autonomy, and why they challenge incumbent institutions).  
. *Politics* _(~10-12k words)_: start to trace similarities between this pragmatic approach to action, this critique to corporations and governments to Arendt's concepts of action, work and labour; next discuss how they seem aligned to this differentiation.
. *Discuss & conclusions* _(~3k words)_: TBD

