= Crowd funding in-between politics and antipolitics
Eduardo Vicente Gonçalves
:doctype: book
:last-update-label!:
:numbered!:
:revdate: April 2018
:revremark: Draft of the thesis.
:sectanchors:
:stylesheet: ../contrib/print.css
:toc: macro
:toclevels: 3

[colophon]

[.colophon]
Draft of the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy. +
Supervisors: Dr. Linsey McGoey and Dr. James Allen-Robertson.

<<<
[dedication]

[.dedication]
For my grandma, who has taught me so much.

<<<
toc::[]

<<<
[abstract]
== Abstract

Crowd funding platforms make projects financially viable through contributions from ordinary people, in a way that apparently dismiss institutional support from government or corporations. This realm is not precisely public but allows this community to put forward strong political claims. The tension in the divide between the public and the private is the core of this sociological investigation: the emphasis put on action within the crowd funding community reinforces a world view that puts forward the anew in the form of a very specific realm – one that blurs the public and the private realm.

The relationship between these realms has been long debated in the literature. Arendt criticized the role of modern state as a guardian of individual freedom, highlighting that possibilities of political action are still restricted to elites. Private interests of corporations have compromised the political sphere, as Wolin and Schedler have argued: states take decisions within the private realm, diminishing public interests. Finally, Bellah has argued this scenario emphasizes private interests, favoring individualism. Yet, he adds, people are uncomfortable: the lack of social ties makes citizens eager for connections. The thesis combines these critiques together with a hacker culture that focus on action, as described by Palmås.

This research draws on interviews I conducted with people engaged with crowd funding. The analysis suggests that if the institutional conjuncture seems to seize the public sphere from people, citizens might be fighting back recreating the public realm within this purportedly private space. Yet cathartic self-perceptions and dissonances blur antipolitical traces in this trend, calling into question the potential of crowd funding communities as an alternative political action. This research contributes the understanding of digital culture, mainly debating how online networks impact areas such as politics, professional careers, and our understanding of money.

[.keywords]
**Keywords**: crowd funding, politics, antipolitics, public space, private space.

:leveloffset: +1
:numbered:

include::1-introduction.adoc[]

include::2-methodology-and-literature-review.adoc[]

include::3-resignifying-money.adoc[]

include::4-autonomy.adoc[]

include::5-a-new-realm-to-empower-action.adoc[]

include::6-isolation-silence-and-absence.adoc[]

include::7-conclusions-and-discussion.adoc[]

include::8-references.adoc[]

:numbered!:
:leveloffset: -1

== Notes
