= Crowd funding in-between politics and antipolitics
Eduardo Vicente Gonçalves
:doctype: book
:last-update-label!:
:numbered!:
:revdate: April 2018
:revremark: Draft of the thesis.
:sectanchors:
:stylesheet: ../contrib/print.css
:toc: macro
:toclevels: 3

[colophon]

[.colophon]
Draft of the thesis to be submitted to the Department of Sociology of the University of Essex for the degree of Doctor of Philosophy. +
Supervisors: Dr. Linsey McGoey and Dr. James Allen-Robertson.

<<<
[dedication]

[.dedication]
For my grandma, who has taught me so much.

<<<
toc::[]

<<<
[abstract]
== Abstract

Crowd funding platforms such as Kickstarter or Indiegogo make projects (financially) viable through donations from ordinary people, in a way that apparently dismiss institutional support from government or corporations. This creates a realm for action that is not precisely public, but allows the crowd funding community to put forward clear and strong political claims. This tension in the divide between the public and the private, permeated by the empowering of political voice, is the core of this sociological investigation.

This PhD thesis shows that the emphasis put on action by the crowd funding community reinforces a world view rich in social and political values. Also this thesis calls into question the possibility of politics derived from this community: on the one hand crowd funding puts forward the anew in the form of a very specific realm that blurs the public and the private realm; on the other hand, the idea that this new realm might be neutral, autonomous and independent in relation to incumbent institutions relies on a series of isolations and dissonances.

The relationship between public and private spheres of action has been long debated in the literature. Arendt criticized the role of modern state as a guardian of individual freedom, highlighting that real possibilities of political action are still restricted to political elites. Simultaneously private interests of corporations have compromised the political sphere, argued Wolin and Schedler. According to them states take decisions within the private realm, diminishing the spaces for public interests. Finally Bellah argued that this scenario and its emphasis in the private interests favored individualism. Yet, he adds, people are not comfortable with it: the lack of social ties makes them eager for connections. The theoretical background consists in combining these critiques together with a hacker culture that focus on action, as described by Palmås. Beyond that, this research draws on dozens of interviews I conducted with people engaged with crowd funding in 8 different countries.

The analysis suggests that if the institutional conjuncture seems to seize the public sphere from people, citizens might be fighting back recreating the public realm within this purportedly private space. Instead of traditional political organizations (such as parties or social movements) crowd funding benefits from practical disruptions emerged from new technologies that allows people within their network to make a living and, meanwhile, to put their ideas forward. In spite of that the closeness and the cathartic self-perception this same community call into question the potential of crowd funding communities as an alternative political avenue. The analysis proposed here contributes to an overarching understanding of the impact of digital culture in the world, mainly debating how emerging technologies that takes prominent role in everyday life might challenge incumbent organization and push further social impacts in different areas, such as politics, civic engagement, professional careers, and our understanding of money.

[.keywords]
**Keywords**: crowd funding, politics, antipolitics, public space, private space.

:leveloffset: +1
:numbered:

include::1-introduction.adoc[]

include::2-methodology-and-literature-review.adoc[]

include::3-resignifying-money.adoc[]

include::4-autonomy.adoc[]

include::5-a-new-realm-to-empower-action.adoc[]

include::6-isolation-silence-and-absence.adoc[]

include::7-conclusions-and-discussion.adoc[]

include::8-references.adoc[]

:numbered!:
:leveloffset: -1

== Notes
